### ISSUE TITLE
Supply pre-built binaries

### ISSUE THREAD

**Issue by casey** [KhronosGroup/MoltenVK#100]
Installation is a bit complex, so it would be lovely if pre-built binaries were supplied. Alternately, allowing installation via homebrew would also help.

**Comment by mmaldacker** [comment]
You can find them here https://vulkan.lunarg.com/

**Comment by casey** [comment]
Ah, excellent. It might be good to note the link in the readme, so that users know building from source isn't the only way to install molten.

**Comment by billhollings** [comment]
Fixed in PR #104.
