### ISSUE TITLE
Crash in vkCmdWriteTimestamp executed outside of a render pass

### ISSUE THREAD

**Issue by js6i** [KhronosGroup/MoltenVK#1007]
The crash occurs here:
https://github.com/KhronosGroup/MoltenVK/blob/412c9ddb6763b5b80a60fcad90366b4eefea5ce3/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm#L638
with the render pass related data uninitialized. I guess I could add some sort of inRenderpass() check as a fix?

**Comment by cdavis5e** [comment]
Sorry about that. The patch in #1010 should fix this.
