### ISSUE TITLE
Problem on building with travis-ci and LunarG binaries (MoltenVK v.1.69.0)

### ISSUE THREAD

**Issue by PooyaEimandar** [KhronosGroup/MoltenVK#101]
I've got following error when I want to build MoltenVK on travis-ci, however the code built on my macbook successfully.
I used binaries of MoltenVK v 1.69.0 which released by [LunarG](https://vulkan.lunarg.com/ )

Here is the error:
```
˜/vulkan/Mac/macOS/Frameworks/vulkan.framework/vulkan, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 ) which is not the architecture being linked (x86_64): /Users/travis/build/WolfSource/Wolf.Engine/engine/dependencies/vulkan/Mac/macOS/Frameworks/vulkan.framework/vulkan
Undefined symbols for architecture x86_64:
``` 
Here is my log:
[Wolf.Engine.macOS](https://travis-ci.org/WolfSource/Wolf.Engine/builds/352761108)

I think something is wrong with vulkan.framework architecture.
any help is really appreciated?

Thanks
Pooya
[Wolf.Engine](https://github.com/WolfSource/Wolf.Engine)

**Comment by billhollings** [comment]
Pinging @karl-lunarg @lenny-lunarg @mikes-lunarg @MarkY-LunarG for help with the LunarG builds and frameworks.

For what it is worth...the MoltenVK PR #98 changed MoltenVK `.travis.yml`. I'm not expecting that to matter...but I thought I'd mention it.

**Comment by karl-lunarg** [comment]
@PooyaEimandar The problem is that you managed to destroy the symlink structure in the vulkan framework when you placed it in the vulkan.zip file that you made and then had Travis unzip before building.

The framework as delivered in the SDK looks like:
```
MrMackey:vulkan.framework karl$ ls -lR
total 24
lrwxr-xr-x  1 karl  staff   24 Feb 25 18:44 Headers -> Versions/Current/Headers
lrwxr-xr-x  1 karl  staff   26 Feb 25 18:44 Resources -> Versions/Current/Resources
drwxr-xr-x  4 karl  staff  136 Feb 25 18:44 Versions
lrwxr-xr-x  1 karl  staff   23 Feb 25 18:44 vulkan -> Versions/Current/vulkan

./Versions:
total 8
drwxr-xr-x  5 karl  staff  170 Feb 25 18:44 A
lrwxr-xr-x  1 karl  staff    1 Feb 25 18:44 Current -> A

./Versions/A:
total 648
drwxr-xr-x  8 karl  staff     272 Feb 25 18:44 Headers
drwxr-xr-x  3 karl  staff     102 Feb 25 18:44 Resources
-rwxr-xr-x  1 karl  staff  329416 Feb 25 18:44 vulkan

./Versions/A/Headers:
total 3840
-rw-r--r--  1 karl  staff     5356 Feb 25 18:44 vk_icd.h
-rw-r--r--  1 karl  staff     6525 Feb 25 18:44 vk_layer.h
-rw-r--r--  1 karl  staff     3903 Feb 25 18:44 vk_platform.h
-rw-r--r--  1 karl  staff     1913 Feb 25 18:44 vk_sdk_platform.h
-rw-r--r--  1 karl  staff   332065 Feb 25 18:44 vulkan.h
-rw-r--r--  1 karl  staff  1603663 Feb 25 18:44 vulkan.hpp

./Versions/A/Resources:
total 8
-rw-r--r--  1 karl  staff  761 Feb 25 18:44 Info.plist
```

and in your zip file:

```
MrMackey:vulkan.framework karl$ ls -lR
total 24
-rw-r--r--@ 1 karl  staff   24 Feb 26 04:14 Headers
-rw-r--r--@ 1 karl  staff   26 Feb 26 04:14 Resources
drwx------@ 4 karl  staff  136 Feb 26 04:14 Versions
-rw-r--r--@ 1 karl  staff   23 Feb 26 04:14 vulkan

./Versions:
total 8
drwx------@ 5 karl  staff  170 Feb 26 04:14 A
-rw-r--r--@ 1 karl  staff    1 Feb 26 04:14 Current

./Versions/A:
total 648
drwx------@ 8 karl  staff     272 Feb 26 04:14 Headers
drwx------@ 3 karl  staff     102 Feb 26 04:14 Resources
-rw-r--r--@ 1 karl  staff  329416 Feb 26 04:14 vulkan

./Versions/A/Headers:
total 3840
-rw-r--r--@ 1 karl  staff     5356 Feb 26 04:14 vk_icd.h
-rw-r--r--@ 1 karl  staff     6525 Feb 26 04:14 vk_layer.h
-rw-r--r--@ 1 karl  staff     3903 Feb 26 04:14 vk_platform.h
-rw-r--r--@ 1 karl  staff     1913 Feb 26 04:14 vk_sdk_platform.h
-rw-r--r--@ 1 karl  staff   332065 Feb 26 04:14 vulkan.h
-rw-r--r--@ 1 karl  staff  1603663 Feb 26 04:14 vulkan.hpp

./Versions/A/Resources:
total 8
-rw-r--r--@ 1 karl  staff  761 Feb 26 04:14 Info.plist
```

The other clue that led to finding this is that the hex codes from your error message decode to "Versions/Current" which suggests that the wrong thing is being found in the framework.
Further, if you dump the contents of the `vulkan` file in the top of the framework in your zip file, you'll see that it contains this text.

The fact that it worked on your local machine and didn't on Travis also suggests a "packaging for Travis" problem and not some fundamental problem with the framework.

You might try using `tar` to make the archive or do something else that preserves symlinks.

**Comment by PooyaEimandar** [comment]
Thanks a lot @karl-lunarg 
I used tar.gz instead of zip
https://travis-ci.org/WolfSource/Wolf.Engine/builds/353694809
