### ISSUE TITLE
MoltenVK mac os static library as Universal macOS Binary

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#1023]
We would like to test our app together with MoltenVK on an Apple Silicon mac computer.

Is it possible to build MoltenVK and the dependency libraries with arm64 support and thus create a Universal macOS Binary?

As for MoltenVK this is simple, one just needs to change Xcode build setting 'Architectures' to 'Standard architectures'. However this causes a link issue since all other libraries like the 'spire-tools' are not compiled with arm64 support.

Is it possible to compile all dependency libraries with arm64 support on mac os?

**Comment by billhollings** [comment]
The `xcode12` branch of this repo includes support for `XCFramework` and fat platform dylbs, each of which includes both `x86_64` and `arm64` _(Intel + Apple Silicon)_ architectures on _macOS_.

One small inconsistency for now is that Xcode doesn't seem to be able to build fat dylibs for _iOS/tvOS Simulator_ builds _(Intel + Apple silicon)_.

The `xcode12` branch will be merged with master later this fall once _Xcode 12_, _iOS 14_, and _macOS 11_ are out of beta.

**Comment by aerofly** [comment]
Thank you, that was quick. I can confirm that with the MoltenVK xcode12 branch we can use native arm64 code on Apple silicon computers with macOS now.

So MoltenVK is running either with Rosetta 2 or native arm64 on macOS.
