### ISSUE TITLE
Vulkan SDK release feature cut-off Friday Sept 25

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1025]
LunarG is planning the next Vulkan SDK release in the week of Monday Sept 28.

MoltenVK PRs approved by Friday Sept 25 will be included, and a MoltenVK SDK release will be made Monday Sept 28.

From a notional feature and functionality perspective, this is a significant release that includes support for Vulkan 1.1 (thanks to the heroic and skillful efforts of @cdavis5e), plus support for the new `VK_KHR_portability_subset` extension, marking MoltenVK's support of the Khronos _Vulkan Portability Initiative_.

With this release, the version of MoltenVK is being upgraded to MoltenVK 1.1.0. 

@cdavis5e @HansKristian-Work @richard-lunarg

**Comment by past-due** [comment]
@billhollings Where would be the proper place to inform of an issue with the official Vulkan SDK builds for macOS?

Specifically, it seems that some of the additional tools (ex. `glslc`) do not run on macOS < 10.14. Without digging thoroughly into it, I'm going to suspect it may be a similar issue as https://github.com/ninja-build/ninja/issues/1764 (where `MACOSX_DEPLOYMENT_TARGET` was not being set when compiling - fixed by https://github.com/ninja-build/ninja/pull/1765)

If this is the case, it might be as simple as just specifying `MACOSX_DEPLOYMENT_TARGET=10.12` or similar in the environment before building those parts of the SDK.

**Comment by Gcenx** [comment]
@past-due the correct place for VulkanSDK issues would be https://vulkan.lunarg.com/issue

**Comment by richard-lunarg** [comment]
You can officially report it here:

https://vulkan.lunarg.com/issue/home?limit=10;q=;mine=false;org=false;khronos=false;lunarg=false;indie=false;status=new,open <https://vulkan.lunarg.com/issue/home?limit=10;q=;mine=false;org=false;khronos=false;lunarg=false;indie=false;status=new,open>

Unofficially, it winds up on my desk anyway. I’ve newly taken responsibility for the macOS SDK portion of the Vulkan SDK here at LunarG. I’ll have a look at this. I’m not sure we have an official statement of the minimum target version of macOS, but we should.

For your needs is 10.12 old enough?

Richard

**Comment by past-due** [comment]
> For your needs is 10.12 old enough? Richard

Yes, for our purposes macOS 10.12 as a deployment target (for build-time tools like `glslc`, etc) would be old enough. (And that's what ninja-build has stabilized on as well.)

Thank you!

**Comment by billhollings** [comment]
@richard-lunarg 

With each SDK release, MoltenVK uses the same versions as the SDK for the following dependency library repositories:

- `KhronosGroup/Vulkan-Headers`
- `KhronosGroup/glslang`
- `KhronosGroup/Vulkan-Tools`
- `LunarG/VulkanSamples`

For these repos, can you provide me the repo tags or commits that you will be using for this SDK, please and thanks?

**Comment by richard-lunarg** [comment]
@billhollings 

The KhronosGroup/glslang is going to be commit: bacaef3237c515e40d1a24722be48c0a0b30f75f
All the others will be branch sdk-1.2.154, which won't appear until Monday.

Richard

**Comment by billhollings** [comment]
@cdavis5e Any need or benefit to updating the `SPRIV-Cross` version beyond the current version within MoltenVK?

**Comment by cdavis5e** [comment]
There are some bug fixes related to conditional branches we might consider pulling in.

**Comment by billhollings** [comment]
@richard-lunarg 

Release [v1.1.0](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.0) is ready to be included in the SDK.
