### ISSUE TITLE
Issues building from the release 1.0.0

### ISSUE THREAD

**Issue by norman784** [KhronosGroup/MoltenVK#107]
I've downloaded the compressed file of the v 1.0.0 and seems that theres some files missing, also fetchDependencies is not present there.

> MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRV-Cross/spirv.hpp:  No such file or directory

Will be cool to have a functional stable release to use.

**Comment by billhollings** [comment]
Thanks for pointing out the discrepancy.

Yes...the 1.0.0 stable release has slightly different instructions. Please read the `README.md` file that comes with that release.

But perhaps now that installation is simpler...we should commit a 1.0.1 release.

**Comment by norman784** [comment]
that will be awesome, thanks

**Comment by billhollings** [comment]
Release 1.0.1 has been released with the simpler build instructions presented in the repository `README.md`.

**Comment by norman784** [comment]
Cool, thanks!
