### ISSUE TITLE
_mtlValidateArgumentsForTextureViewOnDevice error 'Texture Creation newLevelRange.length must not be 0.

### ISSUE THREAD

**Issue by cyotic** [KhronosGroup/MoltenVK#1083]
Hi, we are getting this error when we updated to iOS 14 and wondered if this is something that has been overlooked?
We were a bit behind on the source, so we grabbed master and it still still causing this issue.  Any help would be greatly appreciated.  Thanks

**Comment by billhollings** [comment]
Can you provide some context? Do you have a small sample app that illustrates the issue? Or do you have a logged stack trace?

**Comment by Christopher-Amato** [comment]
Hey, I'm posting this log and screenshot on behalf of @cyotic, because I'm right now the only one with an updated iPhone so I'm the only one able to reproduce the crash.

Here I leave you a full log of the app and a screenshot with the stack and where it stops.

Please tell me if you need more info or something more specific. I'll be happy to provide it.

Thanks!.

![Screen Shot 2020-10-16 at 12 01 59](https://user-images.githubusercontent.com/8563732/96276484-74e53480-0fa9-11eb-83ac-a8e2c59f1803.png)
[VulkanCrashLog.txt](https://github.com/KhronosGroup/MoltenVK/files/5392534/VulkanCrashLog.txt)

**Comment by cdavis5e** [comment]
According to your screenshot, this failure happens on `vkQueueSubmit()`, so this was likely caused by a texture view created internally by MoltenVK.

What commands did you call in that batch?

**Comment by cdavis5e** [comment]
Also, do you have a full backtrace, including the frames from inside MoltenVK? That should shed some light on where MoltenVK attempted to create the texture view.

**Comment by Christopher-Amato** [comment]
Here the full thread stack from the iPhone logs, also @cyotic confirmed having the same issue after upgrading to iOS 14.
[CrashLog.txt](https://github.com/KhronosGroup/MoltenVK/files/5393515/CrashLog.txt)

If you need more info please give me a hint on how to get it, still new to this library and the project where it's used.

**Comment by cdavis5e** [comment]
From your backtrace, the crash is happening inside `MVKImageView::newMTLTexture()`, which is called on a `VkImageView` to create the actual `MTLTexture` underlying it.

How did you create that `VkImageView`? What `VkImageSubresourceRange` did you pass to `vkCreateImageView()` here? Does this work on other platforms? Does the Vulkan validation layer accept it?

**Comment by cyotic** [comment]
Thanks for the information. After some digging we found the offending creation. Not sure why 13 allows this?
```

    VkImageViewCreateInfo imageViewCi = {};
    imageViewCi.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    imageViewCi.pNext = VK_NULL_HANDLE;
    imageViewCi.flags = 0;
    imageViewCi.image = VK_NULL_HANDLE;
    imageViewCi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    imageViewCi.format = VK_FORMAT_R8_UNORM;
    imageViewCi.components = { VK_COMPONENT_SWIZZLE_R, VK_COMPONENT_SWIZZLE_G, VK_COMPONENT_SWIZZLE_B, VK_COMPONENT_SWIZZLE_A };
    imageViewCi.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    imageViewCi.subresourceRange.baseArrayLayer = 0;
    imageViewCi.subresourceRange.baseMipLevel = 0;
    imageViewCi.subresourceRange.layerCount = 1;
    imageViewCi.subresourceRange.levelCount = 1;  // Works on iOS 14
    //imageViewCi.subresourceRange.levelCount = 0; // Works on 13, but not 14
```

**Comment by cdavis5e** [comment]
Frankly, I'm surprised they're doing any validation like this at all. Catching errors like this is supposed to be the job of the API validation layer.

**Comment by cdavis5e** [comment]
I'm pretty sure that [setting `levelCount` to 0 is invalid usage in Vulkan](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap12.html#resources-image-views-compatibility), so this is not our bug.

**Comment by billhollings** [comment]
>I'm pretty sure that setting levelCount to 0 is invalid usage in Vulkan, so this is not our bug.

Specifically from the Vulkan spec:

- `VUID-VkImageSubresourceRange-levelCount-01720`
If levelCount is not `VK_REMAINING_MIP_LEVELS`, it must be greater than `0`
- `VUID-VkImageSubresourceRange-layerCount-01721`
If layerCount is not `VK_REMAINING_ARRAY_LAYERS`, it must be greater than `0`

@cyotic If this made it through the Vulkan validation layers, consider requesting an update to the [Validations Layers](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues).

**Comment by cyotic** [comment]
Yea not your bug.  Thanks again for your help.
