### ISSUE TITLE
How to enable Vulkan/MoltenVK on Dota 2

### ISSUE THREAD

**Issue by wesleyhf** [KhronosGroup/MoltenVK#109]
I'm new with this world but I want to try `vulkan / moltenVK` on `Dota 2`, just to test and learn more about it.

I followed this installation steps, https://github.com/KhronosGroup/MoltenVK#install but I don't know how to setup my `Dota 2` to open with `vulkan`.

**Comment by zakk4223** [comment]
Dota2 with vulkan support on macOS hasn't been released yet.

**Comment by Daniel-Slabaugh** [comment]
Dota2 with vulkan support on macOS is now available, please update this issue.

**Comment by zakk4223** [comment]
To enable vulkan in dota2: 

In the steam properties for Dota2, go to the DLC tab, and install "Dota 2- Vulkan support"

Launch Dota2, go to the video options, select Vulkan renderer. Restart Dota2

**Comment by 7sedam7** [comment]
Hi, I don't see the option "Dota 2- Vulkan support" in the DLC tab. Did something change since 2018, or I'm doing sth wrong..

**Comment by PinkDusttt** [comment]
Hi, I also still don't see the option "Dota 2- Vulkan support" in the DLC tab for MAC. Is there a guide to successfully run Dota 2 using Vulkan on Mac?

**Comment by billhollings** [comment]
>Hi, I also still don't see the option "Dota 2- Vulkan support" in the DLC tab for MAC. Is there a guide to successfully run Dota 2 using Vulkan on Mac?

@danginsburg
