### ISSUE TITLE
API-Samples-macOS broken (15-draw_cube)

### ISSUE THREAD

**Issue by nedelec** [KhronosGroup/MoltenVK#1102]
This may be a problem with the Examples, rather than MoltenVK itself, but the compilation of API-Samples-macOS seems broken on OSX 10.14.6:

Line 65 and 66 of '15-draw_cube.cpp' include files that do not exist anywhere in the package:
#include "15-draw_cube.vert.h"
#include "15-draw_cube.frag.h"

Error message:
'15-draw_cube.vert.h' file not found

**Comment by billhollings** [comment]
@nedelec Looks like you might have missed running `generateSPIRVShaders.sh`. Instructions on how to do that can be found in `Demos\README.md`.

**Comment by nedelec** [comment]
Indeed. It works now! Thank you
