### ISSUE TITLE
Mapping between UBOs bindings weirdness

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/MoltenVK#1107]
So I'm trying to bind some buffers to UBOs and somehow I get weird (wrong) mapping to MSL: is there any detailed explanation on how it is done internally, exactly? (I know from #421 how it works in general, but not in detail)
Couple of questions:
 - do shader stages influence the binding mapping? Or are these just done independently?
 - do unused bindings declared in a desc. layout work?
 - if UBOs are optimized away, does this break stuff?
 - when binding buffers: does the order in which they are updated in the descriptor set matter?

I've got 3 descriptor sets (the third only has textures). Just for fragment shader: Set layout 0 contains 6 buffers (some are fragment only, some are all_graphics), but two of them are not used in the shader (afaik is legal): one is optimized away (???) (I think), the other is not even there. Set layout 1 contains 2 buffers, one for vertex and one for fragment.

Now when I look at the generated msl (for fragment) I get buffers 0 to 3 mapped to the set 0 buffers. Then buffer 4 does not appear. And buffer 5 corresponds to the set 1 one.

When it comes to "setFragmentBuffer" the weirdness intensifies: I get the following binds:
 - bind index 0
 - bind index 2
 - bind index 3
 - bind index 4 (this does not exist in MSL, but it binds the buffer that should go to buffer 5)
 - bind index 5 (with the incorrect buffer)
 - bind index 1
 (Moreover XCode shows buffers 6 and 7 being there, but do not know if that matters)

I'm guessing it has to do either with the buffer being optimized away, or with declaring stuff that is not there in the shader.

**Comment by FilippoLeon** [comment]
Ok, so of course 30 minutes after writing the issue I found the cause: I am use two different layouts for set 1 (one to create the pipeline layout and one to create the descriptor set itself), the order does not match: the bindings are itentical but listed in different order in "pBindings". It this is illegal in vulkan then my bad, otherwise moltenvk should do something about it (crash or do it as expected).

**Comment by billhollings** [comment]
>I am use two different layouts for set 1 (one to create the pipeline layout and one to create the descriptor set itself), the order does not match: the bindings are identical but listed in different order in "pBindings"

Interesting. I'm trying to find in the Vulkan spec where this would be resolved. The closest I've found is language in the section on [Pipeline Layout Compatibility](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#descriptorsets-compatibility):

>Two pipeline layouts are defined to be “compatible for set N” if they were created with _identically defined_ descriptor set layouts for sets zero through N

The italicization is from the spec. MoltenVK interprets this to mean that the binding numbers will be defined by the layout, not the descriptors themselves (ie- identically defined layouts would have the same bindings in the same order). 

You seem to be interpreting it to mean the binding numbers travel with the descriptors and are matched to the layout bindings based on these binding numbers.

Is there language in the spec that nails this down? And is your interpretation working in other Vulkan implementations?

**Comment by FilippoLeon** [comment]
In hindsight, I think the way MoltenVK interprets it is the right one (or the "originally intended"). "Identically defined" seems pretty clear now that you point it out. It never occurred to me that the order had to matter, but since there is at least one implementation for which it does, it's clear the letter of the law wins.

Maybe is weird because for the end user there is no real difference when defining the layouts. But then again, is also a pretty specific edge case.

> Is there language in the spec that nails this down?

I am interested in the issue and will investigate further, but I do not recall any more specific explanation.

> And is your interpretation working in other Vulkan implementations?

So, weirdly enough this worked on all the different desktop implementations I've tested.

Maybe I could head over to the validation layer group and suggest an extra validation check specifically for this. (Btw, I think there is a validation for incompatible layout and I do not recall getting a warning for the problem above, so they might have interpreted it same as me).

**Comment by cdavis5e** [comment]
> > And is your interpretation working in other Vulkan implementations?
> 
> So, weirdly enough this worked on all the different desktop implementations I've tested.
> 
> Maybe I could head over to the validation layer group and suggest an extra validation check specifically for this. (Btw, I think there is a validation for incompatible layout and I do not recall getting a warning for the problem above, so they might have interpreted it same as me).

If other implementations are OK with it and you didn't get a validation error, then you're probably right and we're probably wrong.

Maybe this needs to be brought up with the WG...

**Comment by FilippoLeon** [comment]
At this point, for myself is no longer an issue, and I do not thing this happens very often. I'd just love to find out more and get to the bottom of this, but I also do not want to open too many different bug reports in many places as I do not really know who is actually responsible: is it a doc wording problem, a moltenvk problem, a specs problem or a validation problem (it might also not be a problem). I opened an issue in the validation layers repo in the meantime, because I am now convinced they could warn about that. Maybe the people there can shed a light.

**Comment by mark-lunarg** [comment]
@billhollings, after discussion [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/2233) we think validation is correct.

**Comment by jzulauf-lunarg** [comment]
@billhollings -- "identically defined descriptor set layouts for sets zero through N" -- where N is the *binding* not the ordinal.

**Comment by billhollings** [comment]
@mark-lunarg @jzulauf-lunarg Thanks for the feedback. I've marked this as a MoltenVK bug here now, and am looking into it.

**Comment by jzulauf-lunarg** [comment]
@billhollings there's some dictionary code in VVL for tracking unique DSL definitions and compat for N that maybe interesting as a reference.  Not happy with the theoretical worst case performance of the compat for N logic, but it's never been hit on it's glass jaw in a real life testing.

**Comment by billhollings** [comment]
@FilippoLeon PR #1117 fixes this. Please retest (with your old code) to confirm the fix with the latest code, and if it fixes the problem you were having, please close this issue.
