### ISSUE TITLE
vertexFunction must not be nil

### ISSUE THREAD

**Issue by hodasemi** [KhronosGroup/MoltenVK#112]
Hi,

I have a running vulkan program, which works fine on Linux and Windows. I'm currently trying to get it running on MacOS. 

I got my shaders precompiled in binary SPIR-V format. When I hand over a VkShaderModule with this SPIR-V to vkCreateGraphicsPipelines I get following error:

`[*MoltenVK ERROR*] VK_ERROR_INITIALIZATION_FAILED: Shader module compilation failed (code 3):

Compilation failed:

program_source:9:21: error: 'attribute' attribute cannot be applied to types
    float4 vertex [[attribute(0)]];
                    ^
program_source:9:5: warning: declaration does not declare anything
    float4 vertex [[attribute(0)]];
    ^~~~~~
program_source:22:26: error: expected unqualified-id
    out.gl_Position = in.vertex;
                         ^

-[MTLRenderPipelineDescriptorInternal validateWithDevice😏:2149: failed assertion 'vertexFunction must not be nil.'
Abort trap: 6`

Since this doesnt work, I converted the SPIR-V shaders to metal shaders. It doesnt matter if I convert the GLSL shader directly to metal shader or if I use my SPIR-V shaders, the result is the same. Here I get the following error:

`[*MoltenVK ERROR*] VK_ERROR_INITIALIZATION_FAILED: Shader module does not contain an entry point named ''.
[*MoltenVK ERROR*] VK_ERROR_INITIALIZATION_FAILED: Shader module does not contain an entry point named ''.
-[MTLRenderPipelineDescriptorInternal validateWithDevice😏:2149: failed assertion 'vertexFunction must not be nil.'
Abort trap: 6`

These errors are present with the current version MoltenVK.

**Comment by billhollings** [comment]
The problem will be in shader conversion from SPIR-V to MSL.

Can you provide the SPIR-V or GLSL shader code that is causing the problem, please?

MoltenVK uses `SPIRV-Cross` to generate MSL from SPIR-V. You can also post this as in issue to the [`SPIRV-Cross` repository](https://github.com/KhronosGroup/SPIRV-Cross/issues). If you do, please provide the SPIR-V or GLSL shader code that is causing the problem.

**Comment by hodasemi** [comment]
It is an absolutely basic pass through shader.

`#version 450

layout (location = 0) in vec4 pos;
layout (location = 1) in vec2 uvs;

layout (location = 0) out vec2 uv;

void main() 
{
    uv = uvs;
    gl_Position = vec4(pos);
}`

**Comment by hodasemi** [comment]
They answered: https://github.com/KhronosGroup/SPIRV-Cross/issues/513

**Comment by billhollings** [comment]
Thanks. Yes...I noticed the response there.

I've tested it here too...and the GLSL is indeed being converted correctly through SPIR-V and into compilable MSL.

I notice your error messages above include a reference to:

	float4 vertex [[attribute(0)]];
	
which does not appear in the final MSL code. Also...`vertex` is an MSL keyword.

That leads me to wonder if the SPIR-V code is different that what is being normally generated from the GLSL shader that you include above.

What is the source of your SPIR-V code? And can you post your SPIR-V file itself, so we can run it here to see what's happening?

Here is the `MoltenVKShaderConverter` log from the conversion of your GLSL above to MSL, to compare the SPIR-V that would normally be generated by your GLSL shader:

[MVKGLSLToMSL.txt](https://github.com/KhronosGroup/MoltenVK/files/1844561/MVKGLSLToMSL.txt)

**Comment by hodasemi** [comment]
These are my shaders. The SPIR-V shader is created with `glslangValidator -V` and the metal shader then created with `MoltenVKShaderConverter`. It doesnt matter if you take the GLSL or the SPIR-V as source for the metal shader, the result is the same. The SPIR-V shader is in binary format, I just added the .txt to be able to upload it.

[vert.glsl.txt](https://github.com/KhronosGroup/MoltenVK/files/1844700/vert.glsl.txt)
[vert.metal.txt](https://github.com/KhronosGroup/MoltenVK/files/1844701/vert.metal.txt)
[vert_bin.spv.txt](https://github.com/KhronosGroup/MoltenVK/files/1844702/vert_bin.spv.txt)

**Comment by billhollings** [comment]
Hmmm...when I load the SPIR-V in your SPV file into the Cube Demo app in MoltenVK...it converts as expected. See this file for the MoltenVK log from there.

[MVKSPVToMSL.txt](https://github.com/KhronosGroup/MoltenVK/files/1844977/MVKSPVToMSL.txt)

As far as I can tell...everything is working as expected in MoltenVK.

If you build MoltenVK in Debug mode, it will log the SPIR-V to MSL conversion that is happening in your app. It would be useful to see that, so we can see both the SPIR-V that is actually being submitted by your app, and the corresponding full MSL output.

**Comment by hodasemi** [comment]
Ok, I just figured out that my vulkan debug layer were not active.
Now I get the following message:  `Shader requires VkPhysicalDeviceFeatures::shaderCullDistance but is not enabled on the device.`
This message gets thrown with the `VK_DEBUG_REPORT_ERROR_BIT_EXT` flag.
`vkCreateGraphicsPipeline` returns now with `VK_ERROR_VALIDATION_FAILED_EXT`.

In the early days of vulkan the mesa driver for intel gpus returned the same message, but just with the warning flag. How do I work around this issue?

**Comment by billhollings** [comment]
When I mentioned Debug mode...I meant building MoltenVK Debug mode in Xcode. I was not referring to the SDK validation layers.

The two issues are not likely related...because your GLSL shader above does nothing with cull distances. 

`shaderCullDistance` is not supported in Metal.

**Comment by hodasemi** [comment]
I just found the error. In the original shader (just the names were altered), I named an input parameter `vertex`. If I change the name everything works. Here is an example:

[vert.txt](https://github.com/KhronosGroup/MoltenVK/files/1851018/vert.txt)

**Comment by billhollings** [comment]
Thanks for the update. I'm going to add an issue to the SPIRV-Cross list to add `vertex`, and other keywords to the MSL compiler illegal word screening.
