### ISSUE TITLE
Color mask and Occlusion queries

### ISSUE THREAD

**Issue by FilippoLeon** [KhronosGroup/MoltenVK#1125]
I am totally unsure if what I'm doing is legal vulkan, but I think this is the best place to ask since I have this issue exclusively on Molten. And again is a pretty corner case which probably stretches the normal usage of the specs.

I have a pipeline which is setup to not write to the depth attachment (VkPipelineDepthStencilStateCreateInfo::depthWriteEnable is false) and to mask both color attachments (VkPipelineColorBlendAttachmentState::colorWriteMask is 0) (so a pipeline to do nothing, essentially). However, the renderpass and the framebuffer are setup so that they have 2 color attachments and a depth attachment.

The shader does a discard, but otherwise specifies no color attachment (so the fragment shader has no output layout). Maybe this is illegal but I also tried with two color attachments writing dummy values and nothing changes.

Then I have an occlusion query counting the samples passed by the shader, which executes either a discard, or writes noting to the attachment. I want the query to count only the times no "discard" is issued.

"25.8. Sample Counting" does not mention color masks, so I would assume as for the specs fully masked colors should still count:
> The occlusion query sample counter increments by one for each sample with a coverage value of 1 in each fragment that survives all the per-fragment tests, including scissor, sample mask, alpha to coverage, stencil, and depth tests.

I have the feeling somewhere along the way Metal is optimizing away something that I do not want.

Now: one alternative would be just have a renderpass with no attachment, but I have a feeling that this would also result in the wrong occlusion counts (I will test this later on).

The alternative seems to be not to mask the color attachments, which works on MoltenVK, but in theory (if I understand the specs correctly) results in undefined values written to the attachment (did not observe this in practice).

My question is:
- does somebody know what should happen according to the specs? and if I'm doing something illegal?
- is the alternative of not masking the color a good solution (workaround) for molten (since I do not know what metal does under the hood)? Or am I shooting myself in the foot?

By the way, it seems this issue happens only on Intel Iris mac, but on a Mac book pro it seems to work as expected, so it might be a Metal issue.

**Comment by cdavis5e** [comment]
So what's happening is, because your fragment shader has no output layout, when MoltenVK transforms it to MSL so it can be passed to Metal, the shader returns `void`. I'm wondering, then, if you are correct, and Metal is discarding the fragment whether or not the shader calls `discard_fragment()`, because no color is produced. Maybe it shouldn't. I'll file a feedback.
