### ISSUE TITLE
Question: interest on adding artifacts support to exisiting CI?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#1127]
Hi,
don't know if requested before by me (bad memory :-)) or others, but can't seem to find a similar open or closed issue so just asking.. MoltenVK supports Travis since a while ago (https://github.com/KhronosGroup/MoltenVK/pull/63) so asking if it's possible for MoltenVK to add artifacts support to Travis CI? don't know much about Travis CI and if it's free to support artifacts for open source projects like these.. or if other CI systems can support this (AppVeyor for ex.)..
for example wanted the artifacts of recent build for quick testing:
https://travis-ci.com/github/KhronosGroup/MoltenVK/builds/194818878
thanks..

**Comment by billhollings** [comment]
>wanted the artifacts of recent build for quick testing

What artifacts are you looking for...and why?

**Comment by oscarbg** [comment]
a quick update:
*just confirm https://github.com/Gcenx/macOS_Wine_builds include libMoltenVK.dylib for example latest 5.20 in:
Wine Staging.app/Contents/Resources/wine/lib64/libMoltenVK.dylib
so we could test the eventual CI artifact libMoltenVK.dylib by overwriting this file..
*really comparing MoltenVK.dylib shipped by Crossover 20 (which has DXVK support) vs standard shows all needed to fakely expose is:
geometryShader                 = true
shaderCullDistance           = true
as said a custom enviroment variable could do the job of forcely reporting this two caps or not..

**Comment by oscarbg** [comment]
Hi,
altough little unrelated, just seen MetalAngle project has done a new release and includes as an artifact a compressed dylib file:
https://github.com/kakashidinho/metalangle/releases/tag/gles3-0.0.3
perhaps also future MoltenVK releases could have similar artifacts in addition to source code only, or download the Vulkan SDK MacOS release.. I think MetalAngle devs see their project more as an end user upgradeable runtime library and as such their releases include a dylib..
just saying.. no pressure to implement any ofmy wishes.. :-)
