### ISSUE TITLE
Shader compilation failure with indexed location and sampler2DArray array

### ISSUE THREAD

**Issue by VinDuv** [KhronosGroup/MoltenVK#113]
I’m attempting to enable the Vulkan renderer of the [Dolphin](https://github.com/dolphin-emu/dolphin) emulator on macOS with MoltenVK.
I’ve put the necessary glue code in place, and I patched MoltenVK to work around #61. The emulation starts up fine but some of the GLSL shaders generated by Dolphin fail to compile once translated to MSL, with two reported errors.

The first error is
```
program_source:59:20: error: 'color' has a duplicate index '0'
    float4 ocol1 [[color(0)]];
                   ^
program_source:58:20: note: duplicate 'color' index '0' here
    float4 ocol0 [[color(0)]];
```

It seems to be caused by the following code in the GLSL shader:
```
layout(location = 0, index = 0) out vec4 ocol0;
layout(location = 0, index = 1) out vec4 ocol1;
```
which gets translated to
```
float4 ocol0 [[color(0)]];
float4 ocol1 [[color(0)]];
```
causing the error. Apparently the specified index is ignored by the converter. I’ve noted that this shader code also causes [problems](https://github.com/dolphin-emu/dolphin/blob/b6ef0691e79e22d0bdf2c29bf1b922e9a9f92bc3/Source/Core/VideoCommon/DriverDetails.h#L232) with some native Vulkan drivers: Dolphin [emits](https://github.com/dolphin-emu/dolphin/blob/9f4d5122a2a1b2d0dbfd6164a616d1c859ef0d0b/Source/Core/VideoCommon/PixelShaderGen.cpp#L554) a `layout(location = 0)/layout(location = 1)` instead in that case.

The second error is
```
program_source:103:26: error: type 'texture2d_array<float>' does not provide a subscript operator
    float4 param_1 = samp[0].sample(samp[0]Smplr, float3(float2(tevcoord.xy) * _126.texdim[0].xy, 0.0).xy, uint(round(float3(float2(tevcoord.xy) * _126.texdim[0].xy, 0.0).z))) * 255.0;
```

The GLSL shader contains:
```
layout(set = 1, binding = 0) uniform sampler2DArray samp[8];
[…]
texture(samp[0], …)
```
which seems to be converted to 
```
fragment main0_out main0(texture2d_array<float> samp [[texture(0)]], …
[…]
samp[0].sample(samp[0]Smplr, …)
```
which doesn’t work because `samp` is no longer an array. The `samp[0]Smplr` bit also seems suspicious, even though the compiler doesn’t complain about it.

I’m attaching the [generated GLSL shader](https://github.com/KhronosGroup/MoltenVK/files/1838968/generated_shader.txt), the [MoltenVK log](https://github.com/KhronosGroup/MoltenVK/files/1838973/moltenvk_log.txt) (with the converted MSL) and a [reduced test case](https://github.com/KhronosGroup/MoltenVK/files/1838983/test_frag.txt) that reproduces the erroneous code generation when run through `MoltenVKShaderConverter`.

**Comment by VinDuv** [comment]
One thing I just noticed in the MoltenVK log is that the SPIR-V does contains both the layout and location info for `ocol0`/`ocol1`, but the “Estimated original GLSL” doesn’t:
```
               OpName %389 "ocol0"
               OpName %391 "ocol1"
               OpDecorate %389 Index 0
               OpDecorate %389 Location 0
               OpDecorate %391 Index 1
               OpDecorate %391 Location 0
```

```
layout(location = 0) out vec4 ocol0;
layout(location = 0) out vec4 ocol1;
```

**Comment by billhollings** [comment]
Thanks for the detailed report.

Since it is a shader conversion issue...can you also report it to [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/issues), so it can be tracked and fixed there, please?

The texture array issue might be a similar to [this issue](https://github.com/KhronosGroup/SPIRV-Cross/issues/507).

**Comment by HansKristian-ARM** [comment]
This is related to dual-source blending I think. Does Molten support that?

**Comment by VinDuv** [comment]
@billhollings, thanks for pointing me to the right direction. I’ve created https://github.com/KhronosGroup/SPIRV-Cross/issues/516 and commented on https://github.com/KhronosGroup/SPIRV-Cross/issues/507#issuecomment-376293546 (which indeed seems related). I’m closing this issue.

**Comment by billhollings** [comment]
Reopening to make sure SPIRV-Cross fixes are propagated and used by MoltenVK.

**Comment by billhollings** [comment]
Replaced by enhancement issue #123. Closing.
