### ISSUE TITLE
MoltenVKPackaging.xcodeproj build failure -  cp: /MoltenVK/build/Release/MoltenVK.framework: No such file or directory

### ISSUE THREAD

**Issue by robotogre** [KhronosGroup/MoltenVK#114]
I have installed clang and python3 via brew. I then open MoltenVKPackaging.xcodeproj in Xcode and build, using "MyMac" as the target. I get the following error in both Release and Debug schemes:

`cp: /Users/tom/Downloads/MoltenVK/build/Release/MoltenVK.framework: No such file or directory`

Here is the full build log:

> PhaseScriptExecution Package\ MoltenVK build/MoltenVKPackaging.build/Release/MoltenVK.build/Script-A9FEADD61F3517480010240E.sh
    cd /Users/tom/Downloads/MoltenVK
    export ACTION=build
    export ALTERNATE_GROUP=staff
    export ALTERNATE_MODE=u+w,go-w,a+rX
    export ALTERNATE_OWNER=tom
    export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
    export ALWAYS_SEARCH_USER_PATHS=YES
    export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
    export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
    export APPLE_INTERNAL_DIR=/AppleInternal
    export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
    export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
    export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
    export APPLICATION_EXTENSION_API_ONLY=NO
    export APPLY_RULES_IN_COPY_FILES=NO
    export ARCHS=x86_64
    export ARCHS_STANDARD=x86_64
    export ARCHS_STANDARD_32_64_BIT="x86_64 i386"
    export ARCHS_STANDARD_32_BIT=i386
    export ARCHS_STANDARD_64_BIT=x86_64
    export ARCHS_STANDARD_INCLUDING_64_BIT=x86_64
    export AVAILABLE_PLATFORMS="appletvos appletvsimulator iphoneos iphonesimulator macosx watchos watchsimulator"
    export BITCODE_GENERATION_MODE=marker
    export BUILD_ACTIVE_RESOURCES_ONLY=NO
    export BUILD_COMPONENTS="headers build"
    export BUILD_DIR=/Users/tom/Downloads/MoltenVK/build
    export BUILD_ROOT=/Users/tom/Downloads/MoltenVK/build
    export BUILD_STYLE=
    export BUILD_VARIANTS=normal
    export BUILT_PRODUCTS_DIR=/Users/tom/Downloads/MoltenVK/build/Release
    export CACHE_ROOT=/var/folders/s9/yp_kn08n6xjddsgb3lkzwq680000gn/C/com.apple.DeveloperTools/9.2-9C40b/Xcode
    export CCHROOT=/var/folders/s9/yp_kn08n6xjddsgb3lkzwq680000gn/C/com.apple.DeveloperTools/9.2-9C40b/Xcode
    export CHMOD=/bin/chmod
    export CHOWN=/usr/sbin/chown
    export CLANG_MODULES_BUILD_SESSION_FILE=/Users/tom/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation
    export CLASS_FILE_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/JavaClasses
    export CLEAN_PRECOMPS=YES
    export CLONE_HEADERS=NO
    export CODESIGNING_FOLDER_PATH=/Users/tom/Downloads/MoltenVK/build/Release/
    export CODE_SIGNING_ALLOWED=NO
    export COLOR_DIAGNOSTICS=NO
    export COMBINE_HIDPI_IMAGES=NO
    export COMMAND_MODE=legacy
    export COMPILER_INDEX_STORE_ENABLE=Default
    export COMPOSITE_SDK_DIRS=/Users/tom/Downloads/MoltenVK/build/CompositeSDKs
    export COMPRESS_PNG_FILES=NO
    export CONFIGURATION=Release
    export CONFIGURATION_BUILD_DIR=/Users/tom/Downloads/MoltenVK/build/Release
    export CONFIGURATION_TEMP_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release
    export COPYING_PRESERVES_HFS_DATA=NO
    export COPY_HEADERS_RUN_UNIFDEF=NO
    export COPY_PHASE_STRIP=YES
    export COPY_RESOURCES_FROM_STATIC_FRAMEWORKS=YES
    export CP=/bin/cp
    export CREATE_INFOPLIST_SECTION_IN_BINARY=NO
    export CURRENT_ARCH=x86_64
    export CURRENT_VARIANT=normal
    export DEAD_CODE_STRIPPING=NO
    export DEBUGGING_SYMBOLS=YES
    export DEBUG_INFORMATION_FORMAT=dwarf
    export DEFAULT_COMPILER=com.apple.compilers.llvm.clang.1_0
    export DEFAULT_KEXT_INSTALL_PATH=/Library/Extensions
    export DEFINES_MODULE=NO
    export DEPLOYMENT_LOCATION=NO
    export DEPLOYMENT_POSTPROCESSING=NO
    export DEPLOYMENT_TARGET_CLANG_ENV_NAME=MACOSX_DEPLOYMENT_TARGET
    export DEPLOYMENT_TARGET_CLANG_FLAG_NAME=mmacosx-version-min
    export DEPLOYMENT_TARGET_SETTING_NAME=MACOSX_DEPLOYMENT_TARGET
    export DERIVED_FILES_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/DerivedSources
    export DERIVED_FILE_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/DerivedSources
    export DERIVED_SOURCES_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/DerivedSources
    export DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export DEVELOPER_FRAMEWORKS_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_FRAMEWORKS_DIR_QUOTED=/Applications/Xcode.app/Contents/Developer/Library/Frameworks
    export DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
    export DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
    export DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export DEVELOPMENT_LANGUAGE=English
    export DO_HEADER_SCANNING_IN_JAM=NO
    export DSTROOT=/tmp/MoltenVKPackaging.dst
    export DT_TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export DWARF_DSYM_FILE_NAME=.dSYM
    export DWARF_DSYM_FILE_SHOULD_ACCOMPANY_PRODUCT=NO
    export DWARF_DSYM_FOLDER_PATH=/Users/tom/Downloads/MoltenVK/build/Release
    export EMBEDDED_CONTENT_CONTAINS_SWIFT=NO
    export EMBEDDED_PROFILE_NAME=embedded.provisionprofile
    export EMBED_ASSET_PACKS_IN_PRODUCT_BUNDLE=NO
    export ENABLE_BITCODE=NO
    export ENABLE_DEFAULT_HEADER_SEARCH_PATHS=YES
    export ENABLE_HEADER_DEPENDENCIES=YES
    export ENABLE_ON_DEMAND_RESOURCES=NO
    export ENABLE_TESTABILITY=NO
    export EXCLUDED_INSTALLSRC_SUBDIRECTORY_PATTERNS=".DS_Store .svn .git .hg CVS"
    export EXCLUDED_RECURSIVE_SEARCH_PATH_SUBDIRECTORIES="*.nib *.lproj *.framework *.gch *.xcode* *.xcassets (*) .DS_Store CVS .svn .git .hg *.pbproj *.pbxproj"
    export EXPANDED_CODE_SIGN_IDENTITY=
    export EXPANDED_CODE_SIGN_IDENTITY_NAME=
    export EXPANDED_PROVISIONING_PROFILE=
    export FILE_LIST=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/Objects/LinkFileList
    export FIXED_FILES_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/FixedFiles
    export FRAMEWORK_VERSION=A
    export GCC3_VERSION=3.3
    export GCC_PFE_FILE_C_DIALECTS="c objective-c c++ objective-c++"
    export GCC_TREAT_WARNINGS_AS_ERRORS=NO
    export GCC_VERSION=com.apple.compilers.llvm.clang.1_0
    export GCC_VERSION_IDENTIFIER=com_apple_compilers_llvm_clang_1_0
    export GENERATE_MASTER_OBJECT_FILE=NO
    export GENERATE_PKGINFO_FILE=NO
    export GENERATE_PROFILING_CODE=NO
    export GENERATE_TEXT_BASED_STUBS=NO
    export GID=20
    export GROUP=staff
    export HEADERMAP_INCLUDES_FLAT_ENTRIES_FOR_TARGET_BEING_BUILT=YES
    export HEADERMAP_INCLUDES_FRAMEWORK_ENTRIES_FOR_ALL_PRODUCT_TYPES=YES
    export HEADERMAP_INCLUDES_NONPUBLIC_NONPRIVATE_HEADERS=YES
    export HEADERMAP_INCLUDES_PROJECT_HEADERS=YES
    export HEADERMAP_USES_FRAMEWORK_PREFIX_ENTRIES=YES
    export HEADERMAP_USES_VFS=NO
    export HIDE_BITCODE_SYMBOLS=YES
    export HOME=/Users/tom
    export ICONV=/usr/bin/iconv
    export INFOPLIST_EXPAND_BUILD_SETTINGS=YES
    export INFOPLIST_OUTPUT_FORMAT=same-as-input
    export INFOPLIST_PREPROCESS=NO
    export INLINE_PRIVATE_FRAMEWORKS=NO
    export INSTALLHDRS_COPY_PHASE=NO
    export INSTALLHDRS_SCRIPT_PHASE=NO
    export INSTALL_DIR=/tmp/MoltenVKPackaging.dst
    export INSTALL_GROUP=staff
    export INSTALL_MODE_FLAG=u+w,go-w,a+rX
    export INSTALL_OWNER=tom
    export INSTALL_ROOT=/tmp/MoltenVKPackaging.dst
    export JAVAC_DEFAULT_FLAGS="-J-Xms64m -J-XX:NewSize=4M -J-Dfile.encoding=UTF8"
    export JAVA_APP_STUB=/System/Library/Frameworks/JavaVM.framework/Resources/MacOS/JavaApplicationStub
    export JAVA_ARCHIVE_CLASSES=YES
    export JAVA_ARCHIVE_TYPE=JAR
    export JAVA_COMPILER=/usr/bin/javac
    export JAVA_FRAMEWORK_RESOURCES_DIRS=Resources
    export JAVA_JAR_FLAGS=cv
    export JAVA_SOURCE_SUBDIR=.
    export JAVA_USE_DEPENDENCIES=YES
    export JAVA_ZIP_FLAGS=-urg
    export JIKES_DEFAULT_FLAGS="+E +OLDCSO"
    export KASAN_DEFAULT_CFLAGS="-DKASAN=1 -fsanitize=address -mllvm -asan-globals-live-support -mllvm -asan-force-dynamic-shadow"
    export KEEP_PRIVATE_EXTERNS=NO
    export LD_DEPENDENCY_INFO_FILE=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/Objects-normal/x86_64/MoltenVK_dependency_info.dat
    export LD_GENERATE_MAP_FILE=NO
    export LD_MAP_FILE_PATH=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/MoltenVK-LinkMap-normal-x86_64.txt
    export LD_NO_PIE=NO
    export LD_QUOTE_LINKER_ARGUMENTS_FOR_COMPILER_DRIVER=YES
    export LEGACY_DEVELOPER_DIR=/Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer
    export LEX=lex
    export LIBRARY_FLAG_NOSPACE=YES
    export LIBRARY_KEXT_INSTALL_PATH=/Library/Extensions
    export LINKER_DISPLAYS_MANGLED_NAMES=NO
    export LINK_FILE_LIST_normal_x86_64=
    export LINK_WITH_STANDARD_LIBRARIES=YES
    export LOCALIZABLE_CONTENT_DIR=
    export LOCAL_ADMIN_APPS_DIR=/Applications/Utilities
    export LOCAL_APPS_DIR=/Applications
    export LOCAL_DEVELOPER_DIR=/Library/Developer
    export LOCAL_LIBRARY_DIR=/Library
    export LOCROOT=
    export LOCSYMROOT=
    export MACOSX_DEPLOYMENT_TARGET=10.13
    export MAC_OS_X_PRODUCT_BUILD_VERSION=17D102
    export MAC_OS_X_VERSION_ACTUAL=101303
    export MAC_OS_X_VERSION_MAJOR=101300
    export MAC_OS_X_VERSION_MINOR=1303
    export METAL_LIBRARY_FILE_BASE=default
    export METAL_LIBRARY_OUTPUT_DIR=/Users/tom/Downloads/MoltenVK/build/Release/
    export MODULE_CACHE_DIR=/Users/tom/Library/Developer/Xcode/DerivedData/ModuleCache
    export NATIVE_ARCH=i386
    export NATIVE_ARCH_32_BIT=i386
    export NATIVE_ARCH_64_BIT=x86_64
    export NATIVE_ARCH_ACTUAL=x86_64
    export NO_COMMON=YES
    export OBJECT_FILE_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/Objects
    export OBJECT_FILE_DIR_normal=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/Objects-normal
    export OBJROOT=/Users/tom/Downloads/MoltenVK/build
    export ONLY_ACTIVE_ARCH=NO
    export OS=MACOS
    export OSAC=/usr/bin/osacompile
    export PASCAL_STRINGS=YES
    export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PATH_PREFIXES_EXCLUDED_FROM_HEADER_DEPENDENCIES="/usr/include /usr/local/include /System/Library/Frameworks /System/Library/PrivateFrameworks /Applications/Xcode.app/Contents/Developer/Headers /Applications/Xcode.app/Contents/Developer/SDKs /Applications/Xcode.app/Contents/Developer/Platforms"
    export PKGINFO_FILE_PATH=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/PkgInfo
    export PLATFORM_DEVELOPER_APPLICATIONS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export PLATFORM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export PLATFORM_DEVELOPER_LIBRARY_DIR=/Applications/Xcode.app/Contents/Developer/Library
    export PLATFORM_DEVELOPER_SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    export PLATFORM_DEVELOPER_TOOLS_DIR=/Applications/Xcode.app/Contents/Developer/Tools
    export PLATFORM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export PLATFORM_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
    export PLATFORM_DISPLAY_NAME=macOS
    export PLATFORM_NAME=macosx
    export PLATFORM_PREFERRED_ARCH=x86_64
    export PLATFORM_PRODUCT_BUILD_VERSION=9C40b
    export PLIST_FILE_OUTPUT_FORMAT=same-as-input
    export PRECOMPS_INCLUDE_HEADERS_FROM_BUILT_PRODUCTS_DIR=YES
    export PRECOMP_DESTINATION_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/PrefixHeaders
    export PRESERVE_DEAD_CODE_INITS_AND_TERMS=NO
    export PRODUCT_MODULE_NAME=MoltenVK
    export PRODUCT_NAME=MoltenVK
    export PRODUCT_SETTINGS_PATH=
    export PROFILING_CODE=NO
    export PROJECT=MoltenVKPackaging
    export PROJECT_DERIVED_FILE_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/DerivedSources
    export PROJECT_DIR=/Users/tom/Downloads/MoltenVK
    export PROJECT_FILE_PATH=/Users/tom/Downloads/MoltenVK/MoltenVKPackaging.xcodeproj
    export PROJECT_NAME=MoltenVKPackaging
    export PROJECT_TEMP_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build
    export PROJECT_TEMP_ROOT=/Users/tom/Downloads/MoltenVK/build
    export RECURSIVE_SEARCH_PATHS_FOLLOW_SYMLINKS=YES
    export REMOVE_CVS_FROM_RESOURCES=YES
    export REMOVE_GIT_FROM_RESOURCES=YES
    export REMOVE_HEADERS_FROM_EMBEDDED_BUNDLES=YES
    export REMOVE_HG_FROM_RESOURCES=YES
    export REMOVE_SVN_FROM_RESOURCES=YES
    export REZ_COLLECTOR_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/ResourceManagerResources
    export REZ_OBJECTS_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/ResourceManagerResources/Objects
    export SCAN_ALL_SOURCE_FILES_FOR_INCLUDES=NO
    export SCRIPT_INPUT_FILE_COUNT=0
    export SCRIPT_OUTPUT_FILE_COUNT=0
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
    export SDK_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
    export SDK_DIR_macosx10_13=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
    export SDK_NAME=macosx10.13
    export SDK_NAMES=macosx10.13
    export SDK_PRODUCT_BUILD_VERSION=17C76
    export SDK_VERSION=10.13
    export SDK_VERSION_ACTUAL=101300
    export SDK_VERSION_MAJOR=101300
    export SDK_VERSION_MINOR=1300
    export SED=/usr/bin/sed
    export SEPARATE_STRIP=NO
    export SEPARATE_SYMBOL_EDIT=NO
    export SET_DIR_MODE_OWNER_GROUP=YES
    export SET_FILE_MODE_OWNER_GROUP=NO
    export SHALLOW_BUNDLE=NO
    export SHARED_DERIVED_FILE_DIR=/Users/tom/Downloads/MoltenVK/build/Release/DerivedSources
    export SHARED_PRECOMPS_DIR=/Users/tom/Downloads/MoltenVK/build/SharedPrecompiledHeaders
    export SKIP_INSTALL=YES
    export SOURCE_ROOT=/Users/tom/Downloads/MoltenVK
    export SRCROOT=/Users/tom/Downloads/MoltenVK
    export STRINGS_FILE_OUTPUT_ENCODING=UTF-16
    export STRIP_BITCODE_FROM_COPIED_FILES=NO
    export STRIP_INSTALLED_PRODUCT=YES
    export STRIP_PNG_TEXT=NO
    export STRIP_STYLE=all
    export STRIP_SWIFT_SYMBOLS=YES
    export SUPPORTED_PLATFORMS=macosx
    export SUPPORTS_TEXT_BASED_API=NO
    export SWIFT_PLATFORM_TARGET_PREFIX=macosx
    export SYMROOT=/Users/tom/Downloads/MoltenVK/build
    export SYSTEM_ADMIN_APPS_DIR=/Applications/Utilities
    export SYSTEM_APPS_DIR=/Applications
    export SYSTEM_CORE_SERVICES_DIR=/System/Library/CoreServices
    export SYSTEM_DEMOS_DIR=/Applications/Extras
    export SYSTEM_DEVELOPER_APPS_DIR=/Applications/Xcode.app/Contents/Developer/Applications
    export SYSTEM_DEVELOPER_BIN_DIR=/Applications/Xcode.app/Contents/Developer/usr/bin
    export SYSTEM_DEVELOPER_DEMOS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Utilities/Built Examples"
    export SYSTEM_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SYSTEM_DEVELOPER_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library"
    export SYSTEM_DEVELOPER_GRAPHICS_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Graphics Tools"
    export SYSTEM_DEVELOPER_JAVA_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Java Tools"
    export SYSTEM_DEVELOPER_PERFORMANCE_TOOLS_DIR="/Applications/Xcode.app/Contents/Developer/Applications/Performance Tools"
    export SYSTEM_DEVELOPER_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes"
    export SYSTEM_DEVELOPER_TOOLS=/Applications/Xcode.app/Contents/Developer/Tools
    export SYSTEM_DEVELOPER_TOOLS_DOC_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/documentation/DeveloperTools"
    export SYSTEM_DEVELOPER_TOOLS_RELEASENOTES_DIR="/Applications/Xcode.app/Contents/Developer/ADC Reference Library/releasenotes/DeveloperTools"
    export SYSTEM_DEVELOPER_USR_DIR=/Applications/Xcode.app/Contents/Developer/usr
    export SYSTEM_DEVELOPER_UTILITIES_DIR=/Applications/Xcode.app/Contents/Developer/Applications/Utilities
    export SYSTEM_DOCUMENTATION_DIR=/Library/Documentation
    export SYSTEM_KEXT_INSTALL_PATH=/System/Library/Extensions
    export SYSTEM_LIBRARY_DIR=/System/Library
    export TAPI_VERIFY_MODE=ErrorsOnly
    export TARGETNAME=MoltenVK
    export TARGET_BUILD_DIR=/Users/tom/Downloads/MoltenVK/build/Release
    export TARGET_NAME=MoltenVK
    export TARGET_TEMP_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build
    export TEMP_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build
    export TEMP_FILES_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build
    export TEMP_FILE_DIR=/Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build
    export TEMP_ROOT=/Users/tom/Downloads/MoltenVK/build
    export TOOLCHAINS=com.apple.dt.toolchain.XcodeDefault
    export TOOLCHAIN_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
    export TREAT_MISSING_BASELINES_AS_TEST_FAILURES=NO
    export UID=501
    export UNSTRIPPED_PRODUCT=NO
    export USER=tom
    export USER_APPS_DIR=/Users/tom/Applications
    export USER_LIBRARY_DIR=/Users/tom/Library
    export USE_DYNAMIC_NO_PIC=YES
    export USE_HEADERMAP=YES
    export USE_HEADER_SYMLINKS=NO
    export VALIDATE_PRODUCT=NO
    export VALID_ARCHS="i386 x86_64"
    export VERBOSE_PBXCP=NO
    export VERSION_INFO_BUILDER=tom
    export VERSION_INFO_FILE=MoltenVK_vers.c
    export VERSION_INFO_STRING="\"@(#)PROGRAM:MoltenVK  PROJECT:MoltenVKPackaging-\""
    export WRAP_ASSET_PACKS_IN_SEPARATE_DIRECTORIES=NO
    export XCODE_APP_SUPPORT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Xcode
    export XCODE_PRODUCT_BUILD_VERSION=9C40b
    export XCODE_VERSION_ACTUAL=0920
    export XCODE_VERSION_MAJOR=0900
    export XCODE_VERSION_MINOR=0920
    export XPCSERVICES_FOLDER_PATH=/XPCServices
    export YACC=yacc
    export arch=x86_64
    export variant=normal
    /bin/sh -c /Users/tom/Downloads/MoltenVK/build/MoltenVKPackaging.build/Release/MoltenVK.build/Script-A9FEADD61F3517480010240E.sh
cp: /Users/tom/Downloads/MoltenVK/build/Release/MoltenVK.framework: No such file or directory

**Comment by billhollings** [comment]
Are you using the LunarG Vulkan SDK, or instructions from the `README.md` MoltenVK from this repository?

The use of `build/Release/MoltenVK.framework` is not a standard directory. I'm curious where that is coming from.

`clang` is already part of Xcode...and installing it separately is not required.

**Comment by karl-lunarg** [comment]
I was able to build the repo fine, both by cloning it and downloading the zip. Also, the CI machine is building it successfully.   There's something else going on here, and the original report and log contents are not enough to determine what it is.

And the LunarG SDK is probably not involved;  it doesn't build anything.

**Comment by robotogre** [comment]
Never mind!! I was simply failing to "Archive".  (I had just been "building", but not "Archiving")
