### ISSUE TITLE
Question: About Metal DXTC support on Apple Macs and implications on MoltenVK (if any)..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#1145]
Hi,
I think it's as stupid question, as it may have an obvious answer, but let me answer anyway..
must say I have not thought much about Mac ARM until yesterday.. seeing Apple M1 chip, and the performance uplift on running Shadow of Tomb Raider, I'm thinking how they can run it, as well, it's a Metal game, but surely they are using DXTC (also called BC) compressed textures.. as none of the Apple Axx SOCs support Metal DXTC (https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf), the question is how M1 can run it.. possible answers:
1)Apple M1, in contrast to A14, supports BC textures
2)Apple M1 doesn't support BC in HW, but Apple Rosetta 2 exposes BC textures on Metal when running Metal x86/x64 Mac apps, altough not on native ARM Mac apps..

I think correct answer is 2) and that will also help other Mac x86/x64 apps, as Wine running DX11 games using DXTC textures under DXVK under MoltenVK without modification..
I'm pretty sure of 2) because Crossover 20.0.1 is already sharing news about Mac ARM support:
https://www.codeweavers.com/crossover/changelog

asked here because if Rosetta 2 doesn't exposed these a way to support running DX11 apps under Wine would be to  MoltenVK expose fake BC support on Mac ARM by doing CPU decode of these texture formats and storing as uncompressed textures on GPU mem..

**Comment by galad87** [comment]
M1 does support BC textures and more, see https://developer.apple.com/videos/play/tech-talks/10859 .

**Comment by oscarbg** [comment]
thanks!

**Comment by billhollings** [comment]
>M1 does support BC textures and more, see https://developer.apple.com/videos/play/tech-talks/10859 .

Good to know! Hopefully Apple updates their [Metal Feature Set tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf) soon.

**Comment by billhollings** [comment]
I'm reopening this for info purposes.
