### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by iMonZ** [KhronosGroup/MoltenVK#1156]
Cannot compile: [Compilation](https://github.com/Homebrew/homebrew-core/pull/65009/checks?check_run_id=1416900874)

Error: fatal error: 'glslang/build_info.h' file not found

gosling is correctly installed!

**Comment by cdavis5e** [comment]
You'll have to take this up with Homebrew. We are not responsible for how they build this.

Did you remember to run the `fetchDependencies` script? If you want to use a particular version of `glslang`, you can use the `--glslang-root` option, but the directory has to have the `glslang` source, and there has to be a `build` directory in there that was built with `glslang`'s `build_info.py` script. Sorry; we don't yet support using a pre-built `glslang` from a package manager.
