### ISSUE TITLE
Documentation instructions about DYLD_LIBRARY_PATH are inaccurate

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/MoltenVK#1158]
This [page](https://vulkan.lunarg.com/doc/view/latest/mac/getting_started.html#set-up-the-runtime-environment-manually) suggests configuring `DYLD_LIBRARY_PATH` as one of the option to load MoltenVK dynamic library. However, `DYLD_LIBRARY_PATH` as well as `LD_LIBRARY_PATH` are ignored on Mac OS if System Integrity Protect (SIP) is enabled. That makes all these instructions rather misleading: the application will still fail to run even after configuring everything as described.
The page should either mention that SIP must be disabled in order for the instructions to take effect, or rather say that libraries must be in rpath.

**Comment by billhollings** [comment]
This is an issue with the SDK. Can you post this on the [LunarG SDK issues list](https://vulkan.lunarg.com/issue/home), please?

**Comment by TheMostDiligent** [comment]
https://vulkan.lunarg.com/issue/view/5fc2b8f45df1126a9f453624
