### ISSUE TITLE
MoltenVK as a standalone dependency

### ISSUE THREAD

**Issue by Haeri** [KhronosGroup/MoltenVK#1160]
First of all, thanks for the great project and apologies for a potentially stupid question, but I have been reading the documentation and issues but still can't wrap my head around how I am supposed to use this library.

Quick context: I am working on a cross platform gui library with a Vulkan backend. I use glad as the Vulkan loader and glfw for window creation. I have also a dependency on glslang to compile to SpirV. This works perfectly on windows and Linux. Everything is managed with regular cmake and I can run the project with GitHub actions to produce different binaries.
Now I would like to expand the supported platforms and add macOS support with MoltenVK. I have read the MoltenVK_Runtime_UserGuide.md up and down and there is only talk about how to drag and drop stuff to configure with XCode, which is a bit awkward since I need to be able to have the binaries be generated by a CI. 

So my question is:
- What are the necessary steps to compile and run an existing Vulkan project with moltenVK on a Mac. (Do I have to include additional headers even though I already have vulkan.h included through glad? Do I have to further modify the project assuming my Vulkan code does not cut into the Non-compliance area?)

I have read comments that this project, as it lives in the Apple eco system, is only oriented to be built with XCode, which I understand. But I don't understand how to interface to it like it is usually done for regular c/c++ dependencies.

**Comment by richard-lunarg** [comment]
You really only need XCode for building MoltkenVK itself. You can link to the libraries with the toolset of your choice (I’ve been using Qt Creator myself). The normal Vulkan Headers are sufficient as well. Prebuilt binaries for MoltenVK can be obtained from the Vulkan SDK distributed by LunarG here:

https://vulkan.lunarg.com/ <https://vulkan.lunarg.com/>

You will find a MoltenVK.xcframework folder in the SDK (you can also build this yourself with Xcode and the MoltenVK source), which is directly consumed by Xcode projects… but…

You can also easily extract just the static libraries. For macOS, it is in /macOS-x86_64/libMoltenVK.a

If you link directly to this library you can create a VulkanInstance, and enumerate the GPU’s available, etc.

If you want link dynamically, libMoltenVK.dylib is in /MoltenVK/dylib

Further… you can use the Vulkan Loader and treat MoltenVK as an ICD. This will allow you make use of the Vulkan Validation layers, or even use another Vulkan implementation such as SwiftShader.

The Vulkan Loader is in the SDK in the /macOS/lib folder.

This is brief, and not complete… but you said you’ve been scanning the other documentation, so these little hints may fill in the gaps for you I hope.

Richard

**Comment by Gcenx** [comment]
If your using GitHub actions to compile your project already then use the `macos-latest` the image will contain multiple versions of Xcode.

You’ll also able to use homebrew within GitHub actions for grabbing things like cmake, there’s also an unofficial tap for installing the VulkanSDK.

As for making changes to your project so it compiles nobody can really answer that without seeing your source.

**Comment by billhollings** [comment]
@richard-lunarg 's answer is your best bet if you want to avoid building from source.

If you do want to build from source (for example if you need a later version of MoltenVK than is included in the Vulkan SDK), follow the instructions for [_Building from the Command Line_](https://github.com/KhronosGroup/MoltenVK#building) in the `README.md` document. It uses `make`, so you can include it in larger build scripts.

There are some common prerequisites (`Xcode` and `python3`), but you'll need those to build your own app anyway.

**Comment by Haeri** [comment]
Thanks for the answers so far. Maye to clarify, the issue is not compiling the project. I am doing that already by using the provided dependency script and make file. I have also wrapped it up in a vcpkg custom port for my project [link](https://github.com/Haeri/ElementalDraw/blob/master/external/custom-ports/moltenvk/portfile.cmake). This is completely fine and it gives me:
- MoltenVK headers files
- MoltenVKShaderConverter header files
- A `libMoltenVK.a` static library
- A `libMoltenVK.dylib`dynamic library
- A `MoltenVKShaderConverter` executable

But the initial question still remains: How do I integrate these resources into my project. Do I have to include the header files? If so, what functionality do I need to use from those headers? Can I still use my glad vulkan loader? (The SDK was mentioned but if possible I would love to avoid that since it is an enormous install. I managed to also get by on windows and linux without them)

**Comment by billhollings** [comment]
>How do I integrate these resources into my project.

If you're using the Vulkan SDK, you can start with the [Getting Started with the macOS Vulkan SDK](https://vulkan.lunarg.com/doc/sdk/latest/mac/getting_started.html) document.

If you're using MoltenVK directly, integration instructions are in the [`Docs/MoltenVK_Runtime_UserGuide.md`](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md#install) document. That document is referenced from the [`README.md`](https://github.com/KhronosGroup/MoltenVK#using) document that contains the build instructions.
