### ISSUE TITLE
Catalyst and Apple silicon support?

### ISSUE THREAD

**Issue by qiudaomao** [KhronosGroup/MoltenVK#1163]
The build script lack of arm macOS, arm iOS simulator and Catalyst intel/arm support.

**Comment by dokipen3d** [comment]
I've been able to build moltenvk on apple m1 mac mini. I've actually gone through a crazy process to recreate the lunarG sdk. I've managed to run the cube app from Vulkan-Tools and it runs, but vulkan info fails....

```
ERROR at /Users/danielelliott/Documents/projects/SDk/Vulkan-Tools/vulkaninfo/vulkaninfo.h:248:vkEnumerateInstanceExtensionProperties failed with ERROR_OUT_OF_HOST_MEMORY
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

```

not sure what that is about. 

Also, I'm not sure how to build a universal app, all the builds seem to be Apple Silicon only.

**Comment by dokipen3d** [comment]
![Screen Shot 2020-11-28 at 6 46 24 PM](https://user-images.githubusercontent.com/7567809/100494800-0996a100-31aa-11eb-9774-37055b4a30ca.png)

**Comment by dokipen3d** [comment]
So while vulkaninfo and the cube apps run, I'm getting a crash on my minimal triangle example...

https://github.com/dokipen3d/vulkanHppMinimalExample/edit/master/main.cpp 

(Yes I know the validation layers is deprecated, but after moving it to the new name, it still crashes).

**Comment by billhollings** [comment]
> The build script lack of arm macOS, arm iOS simulator and Catalyst intel/arm support.

If you run `fetchDependencies --all` and `make`, it will build MoltenVK with Apple Silicon and Simulator support in the resulting `XCFramework`. 

We're working on Mac Catalyst support.

**Comment by dokipen3d** [comment]
Yes building is working and moltenvk is working with cube apps and vulkan info, so the seg faults in seeing g might be to do with the loader, or layers lib. I will wait for the official SDK. I wish there was a build script for the sdk (which I've been trying to put together, but it's a bit error prone). Its all amazing stuff though. Great work everyone.

**Comment by qiudaomao** [comment]
Close as already supported on the latest release.

**Comment by monkeyking** [comment]
This works for me.

**Comment by monkeyking** [comment]
> Close as already supported on the latest release.

This works for me!
TY
