### ISSUE TITLE
Shader translation bug

### ISSUE THREAD

**Issue by ikryukov** [KhronosGroup/MoltenVK#117]
I faced with issue that MoltenVK runtime translates mat4 (probably all mat's) vertex attributes to metal without specification of location:
GLSL code:
```
layout(location = 0) in vec3 inPosition;
layout(location = 1) in mat4 inTransform;
layout(location = 5) in vec4 inColor;
```
Converted MSL:
```
struct main0_in
{
    float4 inColor [[attribute(5)]];
    float3 inPosition [[attribute(0)]];
};

struct main0_in29
{
    float4x4 inTransform;
};
```
I found workaround - to split mat4 by 4 vec4:
```
layout(location = 1) in vec4 inTransform0;
layout(location = 2) in vec4 inTransform1;
layout(location = 3) in vec4 inTransform2;
layout(location = 4) in vec4 inTransform3;
```

**Comment by mattparks** [comment]
I am having the same issue but with the mat3 type. I also used a workaround like the one mentioned.

**Comment by billhollings** [comment]
Metal does not allow a matrix to be passed as a `stage_in` attribute. Hence the reason that SPIRV-Cross moves them to a different buffer, where typically per-instance steps would be defined.

The expectation is that a Vulkan app would use two different `VkBuffers` for the per-vertex and per-instance information.

What is the buffer structure that you are looking for? How do the vertex (position, color) and instance (transform) data relate to each other in buffers?

**Comment by ikryukov** [comment]
I have 2 buffers: 1) vertex position (per vertex) and 2) instance data: transform and color (per instance). I understand that passing mat4 as transform in vertex attributes is not good idea, but...  So I expected that mat4 would be converted to 4 vec4 or reports an error...

**Comment by billhollings** [comment]
Closing as fixed.
