### ISSUE TITLE
MTLCommandBufferErrorDeviceRemoved not available on macCatalyst

### ISSUE THREAD

**Issue by woachk** [KhronosGroup/MoltenVK#1176]
MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:312:10: error: 
      'MTLCommandBufferErrorDeviceRemoved' is unavailable: not available on macCatalyst
                                case MTLCommandBufferErrorDeviceRemoved:

when doing a make all build.

System: Apple M1 on macOS 11.0.1, with Xcode 12.2

**Comment by billhollings** [comment]
Fixed in PR #1177.
