### ISSUE TITLE
Crashes on com.Metal.CompletionQueueDispatch thread

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1178]
I'm in a weird situation where a Metal thread keeps crashing on me and i'm not sure where i should be looking next so i'm hoping someone here could provide some ideas.
The crash is only occurring when i'm using a separate queue family to execute transfers.
I've set MVKConfiguration::specializedQueueFamilies to true, this causes my family index detection to use index 0 for graphics and index 3 for transfers. Then while uploading data i'm following the path as-if it's a dedicated gpu. I'm creating a staging buffer and an exclusive owned image. The staging buffer is filled with data and a copy is recorded into a command buffer. Then a release barrier is recorded and the command buffer is submitted to the transfer queue. Then another command buffer is recorded for the graphics queue containing just an acquire barrier. These two buffers are synchronised using a semaphore. The command buffers originate from pools created for their respective queues and the queues are locked while submitting to them.
Naturally i've been trying to disable stuff to try and find what's causing it and the leanest i could get it was an empty transfer command buffer that signals a semaphore and then the graphics command buffer waiting on that semaphore while initialising the image. This setup also crashes, so the issue is probably in the semaphore synchronisation.
The buffers aren't being destroyed, the semaphore and command buffers are but only after a fence got signalled by the graphics command buffer finishing execution. The weird thing is that it only crashes sometimes. Sometimes it crashes right away and sometimes i can run it for a few seconds, uploading data each frame. It doesn't seem to crash during initialisation where i'm not rendering frames yet though, so perhaps something swapchain related?
On windows i have no issue on either NVidia or AMD. No validation layer errors are reported on either windows or moltenvk. I can work around this by setting the transfer queue family index the same as the graphics index, but i'd prefer solving this.

The crash i'm getting most of the time shows this:
EXC_BAD_ACCESS
    0x10021583b <+107>: callq  0x10023a1f0               ; MVKGPUCaptureScope::endScope()
    0x100215840 <+112>: movq   0x40(%r13), %r14
    0x100215844 <+116>: testq  %r14, %r14
    0x100215847 <+119>: je     0x100215868               ; <+152>
    0x100215849 <+121>: xorl   %ebx, %ebx
    0x10021584b <+123>: nopl   (%rax,%rax)
    0x100215850 <+128>: movq   0x38(%r13), %rax
    0x100215854 <+132>: movq   (%rax,%rbx,8), %rdi
    0x100215858 <+136>: movq   (%rdi), %rax
    0x10021585b <+139>: xorl   %esi, %esi
->  0x10021585d <+141>: callq  *0x58(%rax)
    0x100215860 <+144>: incq   %rbx
    0x100215863 <+147>: cmpq   %rbx, %r14
    0x100215866 <+150>: jne    0x100215850               ; <+128>
    0x100215868 <+152>: movq   0x50(%r13), %rdi
    0x10021586c <+156>: testq  %rdi, %rdi
    0x10021586f <+159>: je     0x100215876               ; <+166>

Other times i'm getting an empty callstack on some thread that's not mine, and then the assembly window sais it cant find symbols for some type (sometimes even types of mine, which is weird that it needs that on an external thread)

Any ideas where i could be looking next?

**Comment by billhollings** [comment]
@MennoVink Are you able to provide a better stack trace, showing the call stack?

**Comment by MennoVink** [comment]
Unfortunately not much is available:

Thread 6 Queue : com.Metal.CompletionQueueDispatch (serial)
#0	0x00000001002054dd in ___ZN31MVKQueueCommandBufferSubmission28commitActiveMTLCommandBufferEb_block_invoke ()
#18	0x000000010256049b in start_wqthread ()

Would it help if i build MoltenVK from source and use that instead of the sdk library?

**Comment by tomazos** [comment]
I too found intermittant problems when having separate queues (and queue families, as moltenvk only presents one queue per queue family) for transfer, graphics and presentation.  Your stacktrace looks familiar.  My workaround was to use only one queue (of one queue family) for everything.  Seems stable after that.

**Comment by billhollings** [comment]
>Would it help if i build MoltenVK from source and use that instead of the sdk library?

That would provide more info. As would tuning your app from Xcode.

But the stack trace I'm looking for should show up already when your app crashes. I'm interested in the stack trace, in the calling thread, of the calls that lead up to the `EXC_BAD_ACCESS`
in `MVKGPUCaptureScope::endScope()`.

**Comment by MennoVink** [comment]
I'm assuming that was a typo and you ment to say 'running' it from xcode should show more info? This is already as it is running in xcode. I'm not sure what you mean when you say 'stack trace', my previous comment contains the stack trace, is that not what you are looking for? It's not an application thread calling into MoltenVK and it crashing synchronously if that is what you are thinking. It's something that seems to get queued for asynchronous execution on a dispatch queue.

**Comment by billhollings** [comment]
Yeah...fat finger and autocorrect strike again!

I was hoping to get something along the lines of the following call stacks. The first is a debug call stack captured in Xcode. The second is a crash report when the app is run outside of debugging.

![Screen Shot 2020-12-29 at 1 34 55 PM](https://user-images.githubusercontent.com/356402/103306364-5f45af80-49db-11eb-87c0-287688a0b82b.jpg)

![Screen Shot 2020-12-29 at 1 37 59 PM](https://user-images.githubusercontent.com/356402/103306374-64a2fa00-49db-11eb-992f-f7d3197816e0.jpg)
 
For example purposes, I triggered these by forcing a null access inside the method you reported. It would be helpful to see something similar on the crash you're seeing.

Or in general, some way to force the same issue in a trackable manner.

**Comment by MennoVink** [comment]
Right so the callstack was from a release build so probably inlining caused that information to be lost. Here's the callstack with debug MVK built from tag v1.1.1.

I have no idea about MVK's internal workings, but perhaps that refcount is an indication of a released object?
<img width="1440" alt="Screenshot 2021-01-02 at 17 03 18" src="https://user-images.githubusercontent.com/26071817/103461159-7c041f00-4d1c-11eb-89bf-dd6dca758587.png">

I'm compiling the application with ARC enabled but i'm no expert on obj-c reference counting so not sure if that would affect anything?

**Comment by billhollings** [comment]
>I have no idea about MVK's internal workings, but perhaps that refcount is an indication of a released object?

Yes. That refcount definitely looks odd.

>I'm compiling the application with ARC enabled but i'm no expert on obj-c reference counting so not sure if that would affect anything?

Are you compiling a build of MoltenVK with ARC enabled? Or just your app? It shouldn't matter about your app, but it would definitely matter if you are building MoltenVK itself with ARC enabled.

**Comment by MennoVink** [comment]
ARC is just enabled for the app not for MoltenVK.

I've done some digging an i believe i know what may be happening. What i'm submitting is cmdA -> sema -> cmdB -> fence. Then my code is waiting on the fence and once it's triggered it'll immediately destroy the command buffers and the semaphore.

Now i see in MoltenVK that the MVKQueueCommandBufferSubmission::finish call is dispatched to a different thread using the addCompletedHandler function. I don't know exactly how this works but i see two threads that are capable of handling these finish calls. My hypothesis is that these two command buffers may finish at the same time causing the finish callbacks to run in parallel. Now if the cmdB finish callback is executed first, that will trigger the fence. Then if my thread is scheduled in i'll destroy the semaphore in response to the fence being triggered. Then the finish for cmdA gets scheduled in, trying to trigger the semaphore (which i just destroyed).

I made some changes to test:
1. In the MVKQueueCommandBufferSubmission constructor i've added ss.first->retain().
2. In the finish() callback i've added ss.first->release()
This solves the crashes for me.

Would you say this lack of semaphore retention would be the issue here?

**Comment by MennoVink** [comment]
Any idea on how to make progress on this issue? I don't have enough metal knowledge to validate how the second command buffer could be completed before the cross-queue semaphore was triggered but i do believe this is an issue in MVK and not my implementation. Should i just provide a pull request adding the retains?

**Comment by billhollings** [comment]
>In the MVKQueueCommandBufferSubmission constructor i've added ss.first->retain().
In the finish() callback i've added ss.first->release()
This solves the crashes for me.

Based on that, it looks like this was fixed in #1367, triggered by a different bug.

Can you pull the latest version of MoltenVK, and verify that it has been fixed, please? This will also be in next week's Vulkan SDK release anyway, so you can test it there if you prefer. But testing it before Monday 28th will ensure the fix works before being baked into the pending Vulkan SDK release.

**Comment by MennoVink** [comment]
jep that fixes it, thanks 👍
