### ISSUE TITLE
Support sampler arrays containing multi planar samplers

### ISSUE THREAD

**Issue by markreidvfx** [KhronosGroup/MoltenVK#1181]
Hi, 

I've been messing around trying to get MoltenVK to work with ffmpeg's vulkan filters. I've gotten it mostly working without much effort, but on multi planar pixels formats I get this error:

`[mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: Sampler arrays contaning multi planar samplers are not supported.`

from [here](https://github.com/KhronosGroup/MoltenVK/blob/bf65caa7e4c97dea5e702927adc1aa670ec94cc9/MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm#L461)

Is this even a feature in Metal and could MoltenVK could support it?

(also side note `containing` is spelled incorrectly :p)

**Comment by billhollings** [comment]
@Lichtso Can you review the code identified above, please? It seems to be testing for arrays of immutable samplers, but doesn't actually seem to be testing for multi-planar formats, contrary to what the error messages indicates. And then code immediately following that seems to do exactly what the error message seems to forbid.

**Comment by markreidvfx** [comment]
If it helps I just tested, commenting out that [line](https://github.com/KhronosGroup/MoltenVK/blob/bf65caa7e4c97dea5e702927adc1aa670ec94cc9/MoltenVK/MoltenVK/GPUObjects/MVKDescriptor.mm#L461) does seem to allow the multi planar pixels formats to work correctly.

**Comment by Lichtso** [comment]
The problem is that `pBinding->descriptorCount` can not distinguish between sampler arrays and multiple planes, both need multiple descriptors.

So we have to prevent mixing up the two, so that the error message only triggers if both features are requested together (sampler arrays of multi planar images).

**Comment by markreidvfx** [comment]
I looked a bit more into how ffmpeg is using compute shaders for filters. It's using a separate image for each rgb plane with its planer pixel formats.
here is what the glsl declaration looks like
```
layout (set = 0, binding = 0) uniform sampler2D input_img[3];
```

I'm not sure I understand @Lichtso, I thought `descriptorCount` is just the size of sampler array? I think I'm just a bit confused by the term `multi planar sampler`, is the that same as an immutable sampler?

**Comment by Lichtso** [comment]
The error message is wrong on many levels, still the question remains if we can handle using sampler arrays and multi planar images simultaneously without confusing the indices of the samplers.

@markreidvfx Have you tried using sampler arrays after you removed the line which throws the error?

**Comment by markreidvfx** [comment]
@Lichtso, yes when i remove the line, the sampler arrays seem to work fine with ffmpeg's compute shaders. The images it generates appear correct too.

**Comment by Lichtso** [comment]
@markreidvfx Well then, can you create a pull request in which you remove the line?
