### ISSUE TITLE
[SDK] libvulkan.dylib is x86_64-only

### ISSUE THREAD

**Issue by flibitijibibo** [KhronosGroup/MoltenVK#1182]
For the Vulkan 1.2.162 SDK, MoltenVK for macOS includes both an x86_64 and arm64 binary, but the Vulkan loader itself is still only x86_64. To support Apple Silicon, the SDK will need to be updated to include an arm64 build of libvulkan.dylib.

**Comment by cdavis5e** [comment]
This is an SDK issue, so this should be filed on vulkan.lunarg.com.

**Comment by flibitijibibo** [comment]
Issue filed: https://vulkan.lunarg.com/issue/view/5fe3d7055df112bcbc11adc9
