### ISSUE TITLE
Building #34dc3783 Demos missing '15-draw_cube.vert.h'

### ISSUE THREAD

**Issue by jjoganic** [KhronosGroup/MoltenVK#1195]
Of the three examples, Cube and Hologram build and run directly in Xcode.  The API-Samples however does not build as it is missing 15-draw_cube.vert.h and 15-draw_cube.frag.h.  These files do not appear to exist in the project.  If they are generated files, they do not appear to be generated at the point that they are required.  I did not see anything in the readme that would suggest an extra step.  Is this an oversight?

Line 65 of 15-draw_cube.cpp.  They are appear to be required as the sizeof __draw_cube_vert is used immediately after and does not appear to be defined either.

**Comment by billhollings** [comment]
The API-Samples section of [`Demos/README.md`](https://github.com/KhronosGroup/MoltenVK/blob/master/Demos/README.md#lunarg-vulkan-samples-api) explains what to do:

>Each of the API-Samples demos loads SPIR-V shader code from a file. Before any of the API-Samples demos are run, these SPIR-V files need to be generated as follows:

```
cd MoltenVK/Demos/LunarG-VulkanSamples/API-Samples
./generateSPIRVShaders
```
>You only need to do this step once. It generates the SPIR-V shader code files for all of the API-Samples demos.

**Comment by jjoganic** [comment]
Thank you for the above information.

Just for the record, in following the above link, I am not seeing this text in the Demos/README.md file.  Perhaps it was moved or is no longer on the master branch?  The README.md file is quite short.  Aside from a high-level description of the project, it has no technical information at this time.

**Comment by billhollings** [comment]
> I am not seeing this text in the Demos/README.md file

Yes. Since this issue was first reported above, the `API-Samples` have been removed from the MoltenVK Demos, due to those demos being sunsetted by their developers.
