### ISSUE TITLE
Feature request: VK_KHR_maintenance1 

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#12]
There are two aspects of VK_KHR_maintenance1 that source 2 has relied on:

* Viewport inversion 
* vkAllocateDescriptorSets failing with VK_ERROR_OUT_OF_POOL_MEMORY_KHR

I have recently removed the reliance on viewport inversion, but the engine still does rely on vkAllocateDescriptorSets failing when pool memory is exceeded.

We can get by without these two features, but adding maintenance1 support would be convenient.

**Comment by cdavis5e** [comment]
Since I implemented this in #230, it should be possible to close this now, no?

**Comment by billhollings** [comment]
Added in PR #230.
