### ISSUE TITLE
vkGetBufferMemoryRequirements2KHR crash

### ISSUE THREAD

**Issue by f32by** [KhronosGroup/MoltenVK#1216]
I'm using Vulkan Memory Allocator and the program crashes when calling vkGetBufferMemoryRequirements2KHR(https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/src/vk_mem_alloc.h#L16489).

Following code is taken from VMA with some modifications:
```cpp
VkBuffer hBuffer;

VkBufferCreateInfo creator = {
      .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
      .size = 256,
      .usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
      .sharingMode = VK_SHARING_MODE_EXCLUSIVE
  };

// success
vkCreateBuffer(m_hDevice, &creator, nullptr, &buffer);

VkBufferMemoryRequirementsInfo2KHR memReqInfo = { VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2_KHR };

memReqInfo.buffer = hBuffer;

VkMemoryDedicatedRequirementsKHR memDedicatedReq = { VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS_KHR };

VkMemoryRequirements2KHR memReq2 = { VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR };
VmaPnextChainPushFront(&memReq2, &memDedicatedReq);

// crash
vkGetBufferMemoryRequirements2KHR(m_hDevice, &memReqInfo, &memReq2);
```

I'm using a MacBook Pro 16-inch 2019 and the program is linked against MoltenVK statically.

**Comment by billhollings** [comment]
After modifying your code to the code below, to replace `VmaPnextChainPushFront`, and then adding it to cube.c in the Cube Demo in MoltenVK, I do not encounter a crash.

What is the nature of the crash? Can you provide a stack call trace?

```
	VkBuffer hBuffer;

	VkBufferCreateInfo creator = {
		.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
		.size = 256,
		.usage = VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
		.sharingMode = VK_SHARING_MODE_EXCLUSIVE
	};

	// success
	vkCreateBuffer(demo->device, &creator, NULL, &hBuffer);

	VkBufferMemoryRequirementsInfo2KHR memReqInfo = { VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2_KHR };
	memReqInfo.buffer = hBuffer;

	VkMemoryDedicatedRequirementsKHR memDedicatedReq = { VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS_KHR };

	VkMemoryRequirements2KHR memReq2 = { VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR };

//	VmaPnextChainPushFront(&memReq2, &memDedicatedReq);
	memReq2.pNext = &memDedicatedReq;

	// crash
	vkGetBufferMemoryRequirements2KHR(demo->device, &memReqInfo, &memReq2);
```

**Comment by bytanuky** [comment]
On my Mac the created `hBuffer` is 0x0000290000000029 which is an invalid address and the program crashes when casting `pInfo->buffer` to `MVKBuffer`.

![](https://i.imgur.com/3h9djhq.png)

**Comment by billhollings** [comment]
Can you provide some further context?

Is that crash report a result of running my code above? Or your code above, which doesn't set `hBuffer` before using it in `VkBufferMemoryRequirementsInfo2KHR`. Or VMA?

Specifically, is the `pInfo->buffer` value assigned directly from what is returned from `vkCreateBuffer()`? In other words...is the value returned from `vkCreateBuffer()` that same bad `0x0000290000000029` pointer?

**Comment by billhollings** [comment]
And just to be certain, when you say you link against MoltenVK statically, are you linking directly to MoltenVK, or through the Vulkan SDK?

**Comment by bytanuky** [comment]
It's linked through the Vulkan SDK.
`vkCreateBuffer()` returns `0x0000290000000029`.
![](https://i.imgur.com/KMhQpOs.png)

I tried the latest Vulkan SDK(MoltenVK version 1.1.2. Vulkan version 1.1.162) and it still crashes.

**Comment by billhollings** [comment]
Okay. It's likely an SDK issue then. 

Each layer in the SDK has different Vulkan handle types, so that `0x0000290000000029` handle is probably arising in one of the layers. It needs to be submitted back to that same layer for interpretation. It's possible that somewhere in the mix of VMA and SDK, the object is being submitted to the wrong layer and ending up coming into MoltenVK incorrectly.

Can you post a link to this issue in the [Vulkan SDK issue list](https://vulkan.lunarg.com/issue/home), please, so they can have a look?

BTW...Vulkan SDK 1.2.162 should be using MoltenVK 1.1.1, not 1.1.2.
