### ISSUE TITLE
./fetchDependencies fails

### ISSUE THREAD

**Issue by bfree-github** [KhronosGroup/MoltenVK#1221]
When running ./fetchDependencies with either --macos, --ios, or --all I get:

Please be patient on first build
Building external libraries for platform macOS and destination macOS
./fetchDependencies: /usr/local/bin/xcpretty: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

I'm on MacOS 10.15.7 (Catalina) with Xcode 12.4

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby does not exist, but
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby does.

I manually installed xcpretty: sudo gem install xcpretty
then: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

./fetchDependencies then succeeds; you might want to update your documentation.

**Comment by past-due** [comment]
xcpretty isn't necessary, but `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` looks to be what was needed in your case.

**Comment by billhollings** [comment]
@bfree-github 

> xcpretty isn't necessary, but `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` looks to be what was needed in your case.

`xcode-select` shouldn't have been necessary. Is there an issue here that needs to be addressed, or was it just that your Xcode installation needed this realignment?

**Comment by cdavis5e** [comment]
> `xcode-select` shouldn't have been necessary. Is there an issue here that needs to be addressed, or was it just that your Xcode installation needed this realignment?

I think it's that the active Developer dir needed to be an Xcode installation, because the command line tools for whatever reason don't support `xcodebuild`.

**Comment by past-due** [comment]
> I think it's that the active Developer dir needed to be an Xcode installation, because the command line tools for whatever reason don't support `xcodebuild`.

That matches my reading of the problem as well.

A reference: https://stackoverflow.com/a/17980786
