### ISSUE TITLE
Linking with MoltenVK.xcframework using CMake

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/MoltenVK#1225]
Hello!

I am trying to set up my CMake scripts so that XCode project works for both simulator and device builds. Unfortunately, as of version 3.19, CMake does not support xcframeworks, so as a workaround I was linking with both arm64 and x86_64 static libraries from the framework. This worked fine in 1.2.154.0 even though the linker was complaining about x86 library been provided for device build:

```
ld: ignoring file /Volumes/vulkansdk-macos-1.2.154.0/MoltenVK/MoltenVK.xcframework/ios-x86_64-simulator/libMoltenVK.a, building for iOS-arm64 but attempting to link with file built for iOS Simulator-x86_64
```

 However, in 1.2.162.1 it now generates the error:

```
ld: in /Volumes/vulkansdk-macos-1.2.162.1/MoltenVK/MoltenVK.xcframework/ios-arm64_x86_64-simulator/libMoltenVK.a(libMoltenVK.a-arm64-master.o), building for iOS, but linking in object file (/Volumes/vulkansdk-macos-1.2.162.1/MoltenVK/MoltenVK.xcframework/ios-arm64_x86_64-simulator/libMoltenVK.a(libMoltenVK.a-arm64-master.o)) built for iOS Simulator, file '/Volumes/vulkansdk-macos-1.2.162.1/MoltenVK/MoltenVK.xcframework/ios-arm64_x86_64-simulator/libMoltenVK.a'
```

Do you know why it does not work anymore and can you maybe suggest a way to handle this in CMake?

**Comment by billhollings** [comment]
The fat libraries in the `XCFrameworks` are aligned by platform now. 

The `arm64` architecture in the `MoltenVK.xcframework/ios-arm64_x86_64-simulator/libMoltenVK.a` library is built for the Simulator running on an `arm64` M1 macOS platform, not for an `arm64` running on an iOS device.

Unfortunately, there doesn't seem to be a way to combine all three architectures into one fat binary for use on iOS devices and both Simulator architectures. This appears to be one motivator for Apple creating the `XCFramework` approach.

**Comment by TheMostDiligent** [comment]
OK, I see why it fails to link now. There used to be only x86_64 architecture for simulator in 1.2.154.0, so there was no conflict when specifying both simulator and device libraries.

Do you happen to know if there is some way to handle this in CMake?

**Comment by nsklaus** [comment]
i have a kind of similar question,
i'm trying to compile wine with moltenvk support, but the problem i have is that: 

if i install moltenvk through homebrew (in `/usr/local/`) i get and old version of moltenvk, but wine ./configure pick it up and compile with moltenvk support fine,
on the other hand, if i build moltenvk myself without using homebrew, i get fresh moltenvk installed in `/Library/Frameworks/MoltenVK.xcframework/` (which is more or less just one big 18mb file `libMoltenVK.a` but then wine ./configure doesn't pick that up and i cannot build wine with moltenvk support..

how am i supposed to link the apps i'm compiling to moltenvk from command line ? (cmake, make, ..)

**Comment by cdavis5e** [comment]
To use MoltenVK with Wine, you need the dylib, either directly or through the Vulkan loader. When you build MoltenVK yourself, you can find that file in `<moltenvk dir>/Package/Latest/MoltenVK/dylib/macOS`. You should be able to place that file in `/usr/local/lib/`, and Wine's `configure` script will pick it up.

**Comment by nsklaus** [comment]
thank you for the answer,
while trying to do as you described, i ran into that issue: 
```
?1 klaus $ ll /usr/local/lib/*Molten*
lrwxr-xr-x  1 klaus  admin    46B Feb 23 14:14 /usr/local/lib/libMoltenVK.a -> ../Cellar/molten-vk/1.0.41_2/lib/libMoltenVK.a
lrwxr-xr-x  1 klaus  admin    50B Feb 23 14:14 /usr/local/lib/libMoltenVK.dylib -> ../Cellar/molten-vk/1.0.41_2/lib/libMoltenVK.dylib
lrwxr-xr-x  1 klaus  admin    66B Feb 23 14:14 /usr/local/lib/libMoltenVKGLSLToSPIRVConverter.a -> ../Cellar/molten-vk/1.0.41_2/lib/libMoltenVKGLSLToSPIRVConverter.a
lrwxr-xr-x  1 klaus  admin    70B Feb 23 14:14 /usr/local/lib/libMoltenVKGLSLToSPIRVConverter.dylib -> ../Cellar/molten-vk/1.0.41_2/lib/libMoltenVKGLSLToSPIRVConverter.dylib
lrwxr-xr-x  1 klaus  admin    65B Feb 23 14:14 /usr/local/lib/libMoltenVKSPIRVToMSLConverter.a -> ../Cellar/molten-vk/1.0.41_2/lib/libMoltenVKSPIRVToMSLConverter.a
lrwxr-xr-x  1 klaus  admin    69B Feb 23 14:14 /usr/local/lib/libMoltenVKSPIRVToMSLConverter.dylib -> ../Cellar/molten-vk/1.0.41_2/lib/libMoltenVKSPIRVToMSLConverter.dylib
-> klaus $ 
```
these files are what i get when i install molten-vk through homebrew (so it's an old version).

now, from the molten-vk sources i'm compiled myself fresh from the last 1.2.170 release, i see that i have these files:
```
libMoltenVK.a
libMoltenVK.dylib
```
so i can put those in `/usr/local/lib/` no problem, but for the rest:
```
libMoltenVKGLSLToSPIRVConverter.a
libMoltenVKGLSLToSPIRVConverter.dylib
libMoltenVKSPIRVToMSLConverter.a.a
libMoltenVKSPIRVToMSLConverter.a.dylib
```
i do not have those.
will it be a problem if i only put `libMoltenVK.a` and `libMoltenVK.dylib` in `/usr/local/lib/` ?
or do i need to do something else to create the missing files ?

**Comment by cdavis5e** [comment]
> will it be a problem if i only put `libMoltenVK.a` and `libMoltenVK.dylib` in `/usr/local/lib/` ?

For Wine, you don't need those other libraries. You only need `libMoltenVK.dylib`.

> was there some regression, or am i missing something ?

It never worked without hacks. See #203.

**Comment by nsklaus** [comment]
@cdavis5e 
when you say hacks, you mean adding a few lines to these two files ?

MVKDevice.mm
```
    _features.geometryShader = true;  // XXX Required by DXVK for D3D10
    _features.tessellationShader = true;  // XXX Required by DXVK for D3D11
    _features.logicOp = true;  // XXX Required by DXVK for D3D11.1
    _features.shaderCullDistance = true;  // XXX Required by DXVK for 10level9
```

MVKEnvironment.h
```
#   define MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE    1
```

with hacks and custom built wine, dxvk, and molten-vk, i'm able to have wine to start a game, screen opens, i see a few game menu, then it crashes after 5sec.
that's a progress.. before i couldn't get wine to start a game or open a screen for an app that required dx10 or dx11.

many thanks for the help and advices!
