### ISSUE TITLE
Dev poll: Ongoing support for Xcode 11?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1228]
A few months ago, several devs identified the need to continue to support building with Xcode 11.7 for a while. But at some point, we'll need to sunset that support. So I'd like to get an idea of the need for this support.

At the time, the requests were for macOS targets.

1) Is support for building MoltenVK using Xcode 11.7 still needed for macOS targets (I know it is, but confirmation will help)?

2) Does anyone need to build MoltenVK for iOS targets using Xcode 11. 7?

**Comment by billhollings** [comment]
Investigating adding a Github Action for a macOS build using Xcode 11.7.

**Comment by Gcenx** [comment]
I don’t personally need this anymore but it would still be nice to have the support as it’s possible to still build MoltenVK on macOS Mojave using Xcode11.7 via Retroactive.
