### ISSUE TITLE
Report on using new Wine 6.x WineD3D Vulkan backend and issue found on simple app..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#1233]
Hi,
with Wine 6.x release a new native Vulkan backend is added to WineD3D for supporting D3D1x apps in addition to OpenGL.. i.e. an alternative to DXVK for running D3D11 apps via Vulkan..
*see: https://www.winehq.org/announce/6.0

note a wine64 regedit key has to be added:
"renderer"="vulkan" under "HKEY_CURRENT_USER\Software\Wine\Direct3D"

if can be checked being used as it will be printed:
01a4:err:winediag:wined3d_dll_init Using the Vulkan renderer.

this is nice as existing WineD3D GL4.x backend is unusable on Macos due to Mac max GL 4.1 limitation as it would require higher GL support for working for example compute shaders are part of GL4.3..
so wanted to test how it compares to DXVK.. DXVK requires some "modifications" to work on Mac as it requires a Vulkan driver with geometry shader support for example to be present and Metal can't support it due to Metal limitations..
Of course that MoltenVK (due to Metal) limitations limit also WineD3D Vulkan but it seems WineD3D Vulkan backend is more fine grained in requesting Vulkan features as needed as for example it runs a simple D3D11 compute app OK with no modifications:
https://github.com/doitsujin/dxvk/blob/master/tests/d3d11/test_d3d11_compute.cpp with correct result:
Sum of the numbers 1 to 128 = 8256
note it's first time such an D3D11 compute app runs on Mac with no modifications to DXVK or MoltenVK..
for testing I'm using a Wine Mac build with this native WineD3D Vulkan support builtin:
https://github.com/Gcenx/macOS_Wine_builds/releases/tag/6.1
note thanks to @Gcenx for providing it as per my request.. as early 6.0 build was built with Vulkan support, but WineD3D Vulkan support also requires libvkd3d-shader lib to be present also at build time and shipped..

Well now the problem running a simple d3d11-triangle fails:
it fails to compile a shader but not from the app it's from builtin MoltenVK shader:
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Could not compile support shader from MSL source (Error code 3):
#include <metal_stdlib>
using namespace metal;

typedef struct {
    float4 v_position [[position]];
    float3 v_texCoord;
} VaryingsPosTex;

typedef struct {
    float4 color [[color(0)]];
} FragmentOutputs;

typedef struct {
    uint slice;
    float lod;
} TexSubrez;

constexpr sampler ce_sampler(mip_filter::nearest, filter::nearest);
fragment FragmentOutputs fragCmdBlitImage(VaryingsPosTex varyings [[stage_in]],
                         textureunsupported<float> tex [[texture(0)]],
                         constant TexSubrez& subRez [[buffer(0)]]) {
    FragmentOutputs out;
    out.color = tex.sample(ce_sampler, varyings.v_texCoord, level(subRez.lod));
    return out;
}

Compilation failed: 

program_source:20:26: error: no template named 'textureunsupported'
                         textureunsupported<float> tex [[texture(0)]],
                         ^
```
hope problem can be solved somewhat easily so more testing can be done on WineD3D VUlkan backend..

thanks..

**Comment by cdavis5e** [comment]
That shader is used for `vkCmdBlitImage()`. What type of texture was it trying to blit?

**Comment by oscarbg** [comment]
ok..
I forget to include line after compilation error:
01c8:fixme:d3d:wined3d_texture_vk_upload_data Not supported for multisample textures.
perhaps it helps..
maybe a multisample texture not supported?
if not app code is from :
https://github.com/doitsujin/dxvk/commits/master/tests/d3d11/test_d3d11_triangle.cpp
but executable I have was compiled before adding tess shader to the source code i.e. before commit:
https://github.com/doitsujin/dxvk/commit/fdcb47cc45371f571b0b8197f1d22e372a7076fb#diff-597ba47b9c6ea11a521c0770c6de7d1b838955700eca2dd75cf8eb479175a53e
shows:
https://github.com/doitsujin/dxvk/commits/master/tests/d3d11/test_d3d11_triangle.cpp
full log:
wine64 d3d11-triangle

> 0224:fixme:esync:do_esync eventfd not supported on this platform.
> 022c:fixme:esync:do_esync eventfd not supported on this platform.
> 0234:fixme:esync:do_esync eventfd not supported on this platform.
> 0224:err:winediag:wined3d_dll_init Setting maximum allowed wined3d GL version to 4.1.
> 0224:err:winediag:wined3d_dll_init Using the Vulkan renderer.
> [mvk-info] MoltenVK version 1.1.1. Vulkan version 1.1.162.
> 	The following 67 Vulkan extensions are supported:
> 		VK_KHR_16bit_storage v1
> 		VK_KHR_8bit_storage v1
> 		VK_KHR_bind_memory2 v1
> 		VK_KHR_create_renderpass2 v1
> 		VK_KHR_dedicated_allocation v3
> 		VK_KHR_depth_stencil_resolve v1
> 		VK_KHR_descriptor_update_template v1
> 		VK_KHR_device_group v4
> 		VK_KHR_device_group_creation v1
> 		VK_KHR_driver_properties v1
> 		VK_KHR_external_fence v1
> 		VK_KHR_external_fence_capabilities v1
> 		VK_KHR_external_memory v1
> 		VK_KHR_external_memory_capabilities v1
> 		VK_KHR_external_semaphore v1
> 		VK_KHR_external_semaphore_capabilities v1
> 		VK_KHR_get_memory_requirements2 v1
> 		VK_KHR_get_physical_device_properties2 v2
> 		VK_KHR_get_surface_capabilities2 v1
> 		VK_KHR_image_format_list v1
> 		VK_KHR_maintenance1 v2
> 		VK_KHR_maintenance2 v1
> 		VK_KHR_maintenance3 v1
> 		VK_KHR_multiview v1
> 		VK_KHR_portability_subset v1
> 		VK_KHR_push_descriptor v2
> 		VK_KHR_relaxed_block_layout v1
> 		VK_KHR_sampler_mirror_clamp_to_edge v3
> 		VK_KHR_sampler_ycbcr_conversion v14
> 		VK_KHR_shader_draw_parameters v1
> 		VK_KHR_shader_float16_int8 v1
> 		VK_KHR_shader_subgroup_extended_types v1
> 		VK_KHR_storage_buffer_storage_class v1
> 		VK_KHR_surface v25
> 		VK_KHR_swapchain v70
> 		VK_KHR_swapchain_mutable_format v1
> 		VK_KHR_timeline_semaphore v2
> 		VK_KHR_uniform_buffer_standard_layout v1
> 		VK_KHR_variable_pointers v1
> 		VK_EXT_debug_marker v4
> 		VK_EXT_debug_report v9
> 		VK_EXT_debug_utils v2
> 		VK_EXT_descriptor_indexing v2
> 		VK_EXT_fragment_shader_interlock v1
> 		VK_EXT_hdr_metadata v2
> 		VK_EXT_host_query_reset v1
> 		VK_EXT_image_robustness v1
> 		VK_EXT_inline_uniform_block v1
> 		VK_EXT_memory_budget v1
> 		VK_EXT_metal_surface v1
> 		VK_EXT_private_data v1
> 		VK_EXT_robustness2 v1
> 		VK_EXT_scalar_block_layout v1
> 		VK_EXT_shader_stencil_export v1
> 		VK_EXT_shader_viewport_index_layer v1
> 		VK_EXT_subgroup_size_control v2
> 		VK_EXT_swapchain_colorspace v4
> 		VK_EXT_texel_buffer_alignment v1
> 		VK_EXT_vertex_attribute_divisor v3
> 		VK_AMD_gpu_shader_half_float v2
> 		VK_AMD_negative_viewport_height v1
> 		VK_AMD_shader_trinary_minmax v1
> 		VK_INTEL_shader_integer_functions2 v1
> 		VK_GOOGLE_display_timing v1
> 		VK_MVK_macos_surface v3
> 		VK_MVK_moltenvk v29
> 		VK_NV_glsl_shader v1
> [mvk-info] GPU device:
> 		model: AMD Radeon RX Vega 64
> 		type: Discrete
> 		vendorID: 0x1002
> 		deviceID: 0x687f
> 		pipelineCacheUUID: 00002775-0300-07D2-E8E4-21896991D64B
> 	supports the following Metal Versions, GPU's and Feature Sets:
> 		Metal Shading Language 2.2
> 		GPU Family Mac 2
> 		GPU Family Mac 1
> 		GPU Family Common 3
> 		GPU Family Common 2
> 		GPU Family Common 1
> 		macOS GPU Family 2 v1
> 		macOS GPU Family 1 v4
> 		macOS GPU Family 1 v3
> 		macOS GPU Family 1 v2
> 		macOS GPU Family 1 v1
> 		macOS Read-Write Texture Tier 2
> [mvk-info] Created VkInstance with the following 2 Vulkan extensions enabled:
> 		VK_KHR_surface v25
> 		VK_EXT_metal_surface v1
> [mvk-info] Using MTLEvent for Vulkan semaphores.
> [mvk-info] Created VkDevice to run on GPU AMD Radeon RX Vega 64 with the following 3 Vulkan extensions enabled:
> 		VK_KHR_sampler_mirror_clamp_to_edge v3
> 		VK_KHR_swapchain v70
> 		VK_EXT_vertex_attribute_divisor v3
> [mvk-info] Created 2 swapchain images with initial size (106, 2).
> 0224:fixme:d3d:wined3d_swapchain_init The application requested more than one back buffer, this is not properly supported.
> Please configure the application to use double buffering (1 back buffer) if possible.
> [mvk-info] Created 2 swapchain images with initial size (1024, 600).
> [mvk-info] Created 2 swapchain images with initial size (1024, 600).
> [mvk-error] VK_ERROR_INITIALIZATION_FAILED: Could not compile support shader from MSL source (Error code 3):
> #include <metal_stdlib>
> using namespace metal;
> 
> typedef struct {
>     float4 v_position [[position]];
>     float3 v_texCoord;
> } VaryingsPosTex;
> 
> typedef struct {
>     float4 color [[color(0)]];
> } FragmentOutputs;
> 
> typedef struct {
>     uint slice;
>     float lod;
> } TexSubrez;
> 
> constexpr sampler ce_sampler(mip_filter::nearest, filter::nearest);
> fragment FragmentOutputs fragCmdBlitImage(VaryingsPosTex varyings [[stage_in]],
>                          textureunsupported<float> tex [[texture(0)]],
>                          constant TexSubrez& subRez [[buffer(0)]]) {
>     FragmentOutputs out;
>     out.color = tex.sample(ce_sampler, varyings.v_texCoord, level(subRez.lod));
>     return out;
> }
> 
> Compilation failed: 
> 
> program_source:20:26: error: no template named 'textureunsupported'
>                          textureunsupported<float> tex [[texture(0)]],
>                          ^
> 
> 0248:fixme:d3d:wined3d_texture_vk_upload_data Not supported for multisample textures.

**Comment by oscarbg** [comment]
also it's strange this same executable is running under MoltenVK when using the modified DXVK with no issues..
so maybe the issue it's not from Vulkan code coming from the app but from WineD3D Vulkan backend in that case maybe a search of one of *_vk.c files in
https://source.winehq.org/git/wine.git/tree/HEAD:/dlls/wined3d
may reveal the problem..

**Comment by cdavis5e** [comment]
Multisample textures aren't supported at all for `vkCmdBlitImage()`. What WineD3D is doing here is invalid. Question is, why is it calling `vkCmdBlitImage()` with a multisampled source? (A multisampled destination would actually work, because MoltenVK uses the blit machinery for resolve ops as well.)

**Comment by oscarbg** [comment]
really don't know why..
one thing to note is that I also have run same executable under WineD3D Vulkan backend on Linux with no issues.. 
I think it worked with all Vulkan drivers on Linux: Radv, NV, AMDVLK, Anvil so either this drivers support multisample textures vkCmdBlitImage() or as it was tested with 6.0 version maybe 6.1 has brokened support.. but don't think from 6.0 to 6.1 they have broken WineD3D Vulkan support..
@cdavis5e as seems it's a WineD3D issue, maybe it's better to open a separate Wine issue? 
as you are more knowledgeable than me in Vulkan technical details maybe it's better if you open the issue or if you want I go ahead on open it linking to this issue?

**Comment by oscarbg** [comment]
@cdavis5e seems d3d11-triangle issue is present on Linux as well so sorry for false information.. it's seems I tested ComputeMark there and was working on all drivers..
altough it seems there have been some changes in between 6.0 and 6.1 regarding this sample as on Linux I get:
Wine 6.0:
```
00f0:err:winediag:wined3d_dll_init Using the Vulkan renderer.
00f0:fixme:d3d:wined3d_swapchain_init The application requested more than one back buffer, this is not properly supported.
Please configure the application to use double buffering (1 back buffer) if possible.
Failed to create DXGI swap chain
```
doesn't anything render at all and program closes.. 

Wine 6.1:

```
00f0:err:winediag:wined3d_dll_init Using the Vulkan renderer.
00f0:fixme:d3d:wined3d_swapchain_init The application requested more than one back buffer, this is not properly supported.
Please configure the application to use double buffering (1 back buffer) if possible.
00fc:fixme:d3d:wined3d_texture_vk_upload_data Not supported for multisample textures.
```
renders bad.. (a black screen on Linux) (red on Mac)

**Comment by cdavis5e** [comment]
If it happens on Linux, too, it's almost certainly a WineD3D issue. I'll talk to Henri about it tomorrow.

**Comment by cdavis5e** [comment]
So I talked with him and he thinks there are two possible issues here. One is that this sample for some inexplicable reason uses tessellation, and there may be some brokenness around tessellation shaders. The other is that this sample uses a multisampled RT, so wined3d is indeed passing a multisampled image to `vkCmdBlitImage()`, when it should really be using `vkCmdResolveImage()` in that case.

In any case, I don't think this is MoltenVK's bug.

**Comment by oscarbg** [comment]
Thanks for commenting Henri the bug, as said the build I have is prior to tesselation usage commits, so has to be a multisampled RT bug.. will keep an eye on Wine updates..

**Comment by oscarbg** [comment]
quick test on minimal d3d11 tesselation app attached on this issue(with source code): https://github.com/KhronosGroup/MoltenVK/issues/628
shows also issues running on WineD3D Vulkan backend..
seems I'm uncovering more bugs of WineD3D Vulkan on simple apps but @cdavis5e can take a quick look at the attached log to confirm it's no MoltenVK bug:

```
fixme:vkd3d_dxbc_compiler_check_index_range: Unhandled index range write mask 0x1 (0xf).
fixme:vkd3d_dxbc_compiler_emit_dcl_index_range: Ignoring dcl_index_range 0x6 3.
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:87:23: error: array type 'device half [2]' is not assignable
    gl_TessLevelInner = half(_88.x);
    ~~~~~~~~~~~~~~~~~ ^
program_source:110:5: error: no matching function for call to 'fork0'
    fork0(0u, opc, cb0_0, spvTessLevel[gl_PrimitiveID].edgeTessellationFactor, v_47, v_50, v_53);
    ^~~~~
program_source:73:6: note: candidate function not viable: no known conversion from 'half device[3]' to 'device half (&)[4]' for 4th argument
void fork0(uint vForkInstanceId, thread spvUnsafeArray<float4, 4> (&opc), constant cb1_struct& cb0_0, device half (&gl_TessLevelOuter)[4], thread float4& v_47, thread float4& v_50, thread float4& v_53)
     ^
program_source:111:5: error: no matching function for call to 'fork0'
    fork0(1u, opc, cb0_0, spvTessLevel[gl_PrimitiveID].edgeTessellationFactor, v_47, v_50, v_53);
    ^~~~~
program_source:73:6: note: candidate function not viable: no known conversion from 'half device[3]' to 'device half (&)[4]' for 4th argument
void fork0(uint vForkInstanceId, thread spvUnsafeArray<float4, 4> (&opc), constant cb1_struct& cb0_0, device half (&gl_TessLevelOuter)[4], thread float4& v_47, thread float4& v_50, thread float4& v_53)
     ^
program_source:112:5: error: no matching function for call to 'fork0'
    fork0(2u, opc, cb0_0, spvTessLevel[gl_PrimitiveID].edgeTessellationFactor, v_47, v_50, v_53);
    ^~~~~
program_source:73:6: note: candidate function not viable: no known conversion from 'half device[3]' to 'device half (&)[4]' for 4th argument
void fork0(uint vForkInstanceId, thread spvUnsafeArray<float4, 4> (&opc), constant cb1_struct& cb0_0, device half (&gl_TessLevelOuter)[4], thread float4& v_47, thread float4& v_50, thread float4& v_53)
     ^
program_source:114:5: error: no matching function for call to 'fork1'
    fork1(opc, cb0_0, spvTessLevel[gl_PrimitiveID].insideTessellationFactor, v_85);
    ^~~~~
program_source:91:6: note: candidate function not viable: no known conversion from 'device half' to 'device half (&)[2]' for 3rd argument
void fork1(thread spvUnsafeArray<float4, 4> (&opc), constant cb1_struct& cb0_0, device half (&gl_TessLevelInner)[2], thread float4& v_85)
     ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Tessellation control shader function could not be compiled into pipeline. See previous logged error.
00f8:err:d3d:wined3d_context_vk_apply_draw_state Failed to get graphics pipeline.
00f8:err:d3d:adapter_vk_draw_primitive Failed to apply draw state.
[mvk-info] Created 2 swapchain images with initial size (800, 600).
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Tessellation control shader function could not be compiled into pipeline. See previous logged error.
00f8:err:d3d:wined3d_context_vk_apply_draw_state Failed to get graphics pipeline.
```

**Comment by cdavis5e** [comment]
That's almost certainly a bug in SPIRV-Cross--as you figured out on your own.

**Comment by oscarbg** [comment]
@cdavis5e as the SPIRV-Cross bug has been fixed, can we get a SPIRV-Cross revision update (at least up to https://github.com/KhronosGroup/SPIRV-Cross/commit/bae17e82043848c722f2494dbe60171cb16874ec) for MoltenVK..
altough seems the latest master (https://github.com/KhronosGroup/SPIRV-Cross/commit/621884d70917038caf7509f7b1b3c143807ff43f) has more MSL fixes..
would be nice to have this bug fixed in next SDK release..
