### ISSUE TITLE
maxUniformBufferRange is 0 on Mac Mini M1

### ISSUE THREAD

**Issue by BeastLe9enD** [KhronosGroup/MoltenVK#1240]
I noticed that the uniform buffer range is 0 on my M1 Mac mini. 
This leads to errors when validation layers are enabled. Without validation layers enabled, its working fine

A screenshot of the VkPhysicalDeviceProperties:
https://i.imgur.com/Eh2C4jb.png 

I used Vulkan SDK 1.2.162.1 version

**Comment by cdavis5e** [comment]
We're setting that field by casting the maximum buffer size to a `uint32_t`. This is a mistake. If the maximum buffer size is 4 GiB or greater, the upper 32 bits will be lost. This value really needs to be clamped to 4 GiB - 1.

**Comment by cdavis5e** [comment]
Does #1242 help? We now have build artifacts from PRs, so you don't need to build it yourself anymore.

**Comment by BeastLe9enD** [comment]
Thanks, its working !:)
https://i.imgur.com/dzAtb5V.png
