### ISSUE TITLE
fullImageViewSwizzle configuration is redundant

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/MoltenVK#1241]
Swizzle flag is already a part of the [VK_KHR_portability_subset](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_portability_subset.html) extension, under the name of "imageViewFormatSwizzle".
If the user needs, they have to not only to check the flag, but also pass it as `true` inside "pNext chain of VkDeviceCreateInfo". So the portability extension already gives you the clear opt-in from the user on when this function needs to be enabled. There is no need to have a [separate flag](https://github.com/KhronosGroup/MoltenVK/blob/efba5968a08810ad8497c4d284fce1eeedc0dc81/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L432) in the MVK config.

**Comment by cdavis5e** [comment]
It's... not quite redundant. The portability feature in MoltenVK indicates whether or not we have native image swizzling. Without it, we emulate the swizzling in the shader, which is quite expensive. Also, the `fullImageViewSwizzle` toggle predates the portability extension.

I wonder if there should be some sort of `imageViewFormatSwizzleNative` property (as opposed to a feature) for the portability extension.

**Comment by kvark** [comment]
That makes sense, thanks for explaining!
