### ISSUE TITLE
Can't build Cube demo (actually any demo)

### ISSUE THREAD

**Issue by krupitskas** [KhronosGroup/MoltenVK#1249]
Problem in the weird linking. What I've done
1) ./fetchDependencies --macOS 
2) Open MoltenVkPackaging and built MoltenVk Package (macOS only) (target MyMac)
3) Generated   	./generateSPIRVShaders
4) Open Demos.xcworkspace and built Cube-macOS (target MyMac)

This really looks wrong and I don't understand why it's saying anything about arm64 here:

```
Link Cube(arm64) 0.1 seconds:

ld: warning: ignoring file /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Products/Release/libMoltenVK.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

Part of the log:

```
Ld /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Intermediates.noindex/Cube.build/Release/Cube-macOS.build/Objects-normal/arm64/Binary/Cube normal arm64 (in target 'Cube-macOS' from project 'Cube')
    cd /Users/krupitskas/Code/MoltenVK/Demos/LunarG-VulkanSamples/Cube
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-macos10.11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Products/Release -F/Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Products/Release -filelist /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Intermediates.noindex/Cube.build/Release/Cube-macOS.build/Objects-normal/arm64/Cube.LinkFileList -Xlinker -object_path_lto -Xlinker /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Intermediates.noindex/Cube.build/Release/Cube-macOS.build/Objects-normal/arm64/Cube_lto.o -fobjc-link-runtime -ObjC -lstdc++ -lMoltenVK -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Intermediates.noindex/Cube.build/Release/Cube-macOS.build/Objects-normal/arm64/Cube_dependency_info.dat -o /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Intermediates.noindex/Cube.build/Release/Cube-macOS.build/Objects-normal/arm64/Binary/Cube

ld: warning: ignoring file /Users/krupitskas/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Products/Release/libMoltenVK.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_vkAllocateCommandBuffers", referenced from:
      _demo_prepare in DemoViewController.o
```

Actual result:

<img width="1091" alt="Screenshot 2021-02-10 at 12 27 29" src="https://user-images.githubusercontent.com/5683877/107490748-5a0f7f00-6b9b-11eb-8328-f225750c41f6.png">

**Comment by billhollings** [comment]
The Cube Demo is expecting to build for both `X86_64` and `arm64` platforms, and based on the error, it looks like the MoltenVK build did not include the `arm64` platform. 

Please verify that the `MoltenVk Package (macOS only)` Xcode Scheme is set to build in `Release` mode, and that in doing so the Build Active Architecture (`ONLY_ACTIVE_ARCH`) build setting is set to `NO`.

**Comment by krupitskas** [comment]
ONLY_ACTIVE_ARCH is NO

<img width="1339" alt="Screenshot 2021-02-10 at 19 01 38" src="https://user-images.githubusercontent.com/5683877/107536046-682cc200-6bd2-11eb-812f-bd95d88927a5.png">

MoltenVk Package (macOS only) is set to Release

<img width="907" alt="Screenshot 2021-02-10 at 19 04 49" src="https://user-images.githubusercontent.com/5683877/107536549-f4d78000-6bd2-11eb-8883-6d683178f52d.png">

**Comment by billhollings** [comment]
Strange. 

What's inside `MoltenVK/Package/Latest/MoltenVK.xcframework`? There should be a `macos-arm64_x86_64` folder and the `libMoltenVK.a` inside it should indicate both architectures from `lipo -archs libMoltenVK.a`.

Also repeat the same `lipo` on the `libMoltenVK.a` you have highlighted above.

**Comment by krupitskas** [comment]
Have next output:

```
[~/Code/MoltenVK/Package/Release/MoltenVK/MoltenVK.xcframework/macos-arm64_x86_64]> lipo -archs libMoltenVK.a

arm64 x86_64
```

```
└[~/Library/Developer/Xcode/DerivedData/Demos-fcgmqltvbchnmzcubykcinscyapm/Build/Products/Release]> lipo -archs libMoltenVK.a

x86_64
```

**Comment by billhollings** [comment]
Those are clearly different libraries. Looks like your Cube build is not using the current MoltenVK library.

Try cleaning your Cube project build by either running _**Product->Clean Build Folder**_ from the Cube project, or just clearing out your `DerivedData` folder.

**Comment by krupitskas** [comment]
Interesting but this does work, thanks! Surprised that this didn't worked out of box. Like build moltenvk, open demos, build cube ¯\_(ツ)_/¯.
Anyway, really thanks, now I can start experiment
