### ISSUE TITLE
`vkGetBufferMemoryRequirements` reports wrong buffer alignment when running in the iOS simulator

### ISSUE THREAD

**Issue by georged-youi** [KhronosGroup/MoltenVK#1250]
When running a Metal app in the iOS simulator, Apple requires that align constant buffer offsets for render commands to be 256 bytes. (see: https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator?language=objc)

Trying to allocate a uniform buffer, `vkGetBufferMemoryRequirements` returns the alignment as 64 bytes. This leads to the following assert from the `metal API validation`: `validateFunctionArguments:3722: failed assertion 'Fragment Function(main0): the offset into the buffer _23 that is bound at buffer index 0 must be a multiple of 256 but was set to 24960.'`

The issue seems to be coming from this file: https://github.com/KhronosGroup/MoltenVK/blob/05066429e29cb5bf11d21cb2bc2b5ebfff94e7ae/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm where `mtlBufferAlignment` is set to 256 only for `MVK_MACOS`, but there's no check for the iOS simulator.

**Comment by billhollings** [comment]
Thanks for reporting this.

Simulator on `arm64` macOS will probably be okay, but `X86_64` needs to be adjusted.
