### ISSUE TITLE
Clean up build warnings on M1 devices

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1268]
Building MoltenVK on an M1 machine seems to spit out warnings of the type:

```
objc[51715]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x2031b0188) and ?? (0x11826c2b8). One of the two will be used. Which one is undefined.
objc[51715]: Class AMSupportURLSession is implemented in both ?? (0x2031b01d8) and ?? (0x11826c308). One of the two will be used. Which one is undefined.
```

The build succeeds, but removing this warning logging noise would be helpful.

**Comment by cdavis5e** [comment]
I think this is a bug in Xcode on M1.

**Comment by billhollings** [comment]
>I think this is a bug in Xcode on M1.

Yup. I looked into it. It's emanating directly from `xcodebuild` and is unrelated to the project. A simple `xcodebuild -help` triggers it.

Not much to be done beyond jumping through some creative `grep` hoops on the output. It's not causing trouble, so I'm going to leave it for Apple to clean up at their leisure.

**Comment by cdavis5e** [comment]
Huh. On 11.3, I actually see which are the two modules. They're `/usr/lib/libauthinstall.dylib` and `/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice`. Both AMFI-related, I assume. I'll file a feedback for this. Maybe now that the two modules can be identified, they can actually fix this now.

**Comment by theking200794** [comment]
Facing same issue on m1 pro 
`Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x21ae86be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104204318). One of the two will be used. Which one is undefined.
`  Tried with updating my react version to 64.1 and 'Flipper' => '0.74.0', 'Flipper-Folly' => '2.5.3'  on ios 15.2. Also tried erasing on emulator but no success.
