### ISSUE TITLE
CTS Multithreading tests hitting race conditions

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1269]
Some of the CTS multithreading tests:

    dEQP-VK.api.object_management.multithreaded*

are occasionally hitting race conditions and crashing.

Investigating.

**Comment by billhollings** [comment]
dEQP-VK.api.object_management.multithreaded_per_thread_resources.graphics_pipeline
    dEQP-VK.api.object_management.multithreaded_per_thread_resources.compute_pipeline

are hitting race conditions around the simultaneous compilation and destruction of `MTLFunctions` and Metal pipelines.

There is an internal object web inside `MTLDevice`, which is not entirely guarded across calls. 

- Metal will return the exact same `MTLFunction` object, from multiple different `MTLLibraries`, if the MSL code is identical, so synchronizing on the `MTLLibrary` is not safe enough.

- Destroying a Metal pipeline state while another is being created, can cause race conditions on internal components, including the contents of the pipeline descriptors.

**Comment by billhollings** [comment]
dEQP-VK.api.object_management.multithreaded_per_thread_resources.sampler
    dEQP-VK.api.object_management.multithreaded_shared_resources.sampler

**Comment by cdavis5e** [comment]
No wonder I could never solve this. I was wondering why it kept crashing no matter how much I fiddled with the locking...
