### ISSUE TITLE
Compilation error of case sensitive filesystems (plus fix)

### ISSUE THREAD

**Issue by smellslikedonkey** [KhronosGroup/MoltenVK#128]
In build phases "Create Dynamic Library"

Switch:
export MVK_PLATFORM_SDK_DIR="${PLATFORM_DEVELOPER_SDK_DIR}/${PLATFORM_NAME}.sdk"

To:
export MVK_PLATFORM_SDK_DIR="${SDK_DIR}"

**Comment by billhollings** [comment]
Fixed in PR #129.
