### ISSUE TITLE
Incorrect metal version requirement for 64 bit integers.

### ISSUE THREAD

**Issue by VZout** [KhronosGroup/MoltenVK#1291]
See https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L1657.

That code implies 2.3 is required. But according to metal spec it was introduced in 2.2
Is this done on purpose?

**Comment by cdavis5e** [comment]
Yes. While 64-bit integers are supported in MSL 2.2, you can't load or store them directly until MSL 2.3.

**Comment by VZout** [comment]
Huh alright good to know. Must have read over that in the spec.
