### ISSUE TITLE
VK_COLOR_SPACE_PASS_THROUGH_EXT doesn't work

### ISSUE THREAD

**Issue by Dauron** [KhronosGroup/MoltenVK#1292]
This line says that the default CAMetalLayer.colorspace value is nil, while it is sRGB on my Catalina:
https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm#L331

I had to explicitly set it to nil to skip OSX colorspace conversion:
_mtlLayer.colorspace = nil;

**Comment by billhollings** [comment]
Fixed in PR #1305. Please retest and close this issue if it is repaired.
