### ISSUE TITLE
Memory issue about rotating device on iOS

### ISSUE THREAD

**Issue by intufy** [KhronosGroup/MoltenVK#1324]
Hello,
I added below lines in DemoViewController implementation of Demos/Cube/iOS/DemoViewController.m

- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
  [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
  demo_resize(&demo);
}

Now I build & run and try to rotate my device, then I see the demo keeps increasing the memory about 20 MB continuously whenever I rotate my device.
I tested it with MoltenVK 1.1.3 on iPhone 11 Pro Max, iOS 14.4.1 and iPhone 6s Plus, iOS 13.3.1. They show the same phenomenon.
Is it a memory leak bug or missing some necessary implementations in the demo? 
Or am I missing something? Thank you for any help.

**Comment by intufy** [comment]
Technically, the memory is increased when vkQueueSubmit is called.

**Comment by billhollings** [comment]
Confirmed. Looks like the swapchain is leaking. Looking into it.

**Comment by billhollings** [comment]
This is fixed in PR #1325 . Please retest and close this issue if successful.

**Comment by intufy** [comment]
@billhollings 
It works perfectly on my phones. Thank you!
