### ISSUE TITLE
-[AGXA10FamilyCommandBuffer logs]: unrecognized selector sent

### ISSUE THREAD

**Issue by CrystalBlack** [KhronosGroup/MoltenVK#1336]
When I run the Demo project on the iPhone7 Device iOS 12.3.1, the following error occurred

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AGXA10FamilyCommandBuffer logs]: unrecognized selector sent to instance 0x10310fb50'

**Comment by billhollings** [comment]
Presumably this is happening only with debug mode enabled at runtime?

In any case, this is fixed in PR #. Please retest and confirm, and close this issue if successful.

**Comment by CrystalBlack** [comment]
Thank you.  It has been fixed.
