### ISSUE TITLE
Imageless framebuffer creation crashes at vkCreateFramebuffer

### ISSUE THREAD

**Issue by buzmeg** [KhronosGroup/MoltenVK#1350]
Validation layers are clean (so feature is properly enabled) and this is validated to not crash on nVidia on Windows 10 for Vulkan 1.2.141 and fails on MoltenVK on OS X 10.14.6 for Vulkan 1.2.170.

The API dump doesn't get very far so presumably it crashes really early:

```
Thread 1, Frame 0:
vkGetPhysicalDeviceFormatProperties(physicalDevice, format, pFormatProperties) returns void:
    physicalDevice:                 VkPhysicalDevice = 0x7fe3fcc14130
    format:                         VkFormat = VK_FORMAT_B8G8R8A8_UNORM (44)
    pFormatProperties:              VkFormatProperties* = 0x70000e4abb60:
        linearTilingFeatures:           VkFormatFeatureFlags = 54275 (VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT | VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT | VK_FORMAT_FEATURE_BLIT_SRC_BIT | VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT | VK_FORMAT_FEATURE_TRANSFER_SRC_BIT | VK_FORMAT_FEATURE_TRANSFER_DST_BIT)
        optimalTilingFeatures:          VkFormatFeatureFlags = 56707 (VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT | VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT | VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT | VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT | VK_FORMAT_FEATURE_BLIT_SRC_BIT | VK_FORMAT_FEATURE_BLIT_DST_BIT | VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT | VK_FORMAT_FEATURE_TRANSFER_SRC_BIT | VK_FORMAT_FEATURE_TRANSFER_DST_BIT)
        bufferFeatures:                 VkFormatFeatureFlags = 88 (VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT | VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT | VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT)

Attempting to create imageless framebuffer
Thread 1, Frame 0:
vkCreateFramebuffer(device, pCreateInfo, pAllocator, pFramebuffer) returns VkResultSegmentation fault: 11
```

**Comment by cdavis5e** [comment]
We don't even support that extension yet. You *did* make sure to check that the `VK_KHR_imageless_framebuffer` extension is present, right?

**Comment by buzmeg** [comment]
This is base in 1.2.

**Comment by cdavis5e** [comment]
We don't support 1.2, either. The loader lets you create `VkDevice`s for the MoltenVK ICD from a 1.2 instance regardless. But you're responsible for making sure the functionality you want is available. At least, that's my understanding of how this works in Vulkan.

**Comment by buzmeg** [comment]
I confirm that vkEnumerateInstanceVersion does lie to me and indicate a Vulkan 1.2 instance has been instantiated.  I'm not sure this is a great idea.

I also confirm that VkPhysicalDeviceImagelessFramebufferFeatures does not get set either direction, the imagelessFramebuffer value simply remains at whatever it was.  This is a touch surprising and was the bug in my code.  I would expect an unrecognized feature should get explicitly set to VK_FALSE rather than just ignored, but what does the standard say?

I also confirm that vkCreateDevice happily allows me to create a device with imagelessFramebuffer enabled with nary a complaint.

**Comment by billhollings** [comment]
>vkEnumerateInstanceVersion does lie to me and indicate a Vulkan 1.2 instance has been instantiated

Are you linking to MoltenVK directly, or using the Vulkan SDK Loader and Layers environment?

The value returned by MoltenVK in `vkEnumerateInstanceVersion()` is the same value that MoltenVK logs when a `VkInstance` is created, so you can verify what MoltenVK is reporting. It will be something like:

    [mvk-info] MoltenVK version 1.1.4, supporting Vulkan version 1.1.176.

The value logged here is Vulkan 1.1. MoltenVK never sets this to 1.2.

If you are using the Vulkan SDK Loader and Layers, the error is almost certainly happening within a layer above MoltenVK. For that, you can post an issue to the [Vulkan Loader and Layers issue list](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues), or the [Vulkan SDK issue list](https://vulkan.lunarg.com/issue/home).

**Comment by buzmeg** [comment]
Direct dynamic link as far as I know.  I'm not intentionally using a Vulkan Loader and Layer thing.

**Comment by buzmeg** [comment]
Bug is moot since I no longer have macOS hardware.  Closing.

Thanks.

**Comment by cdavis5e** [comment]
> Bug is moot since I no longer have macOS hardware.

Well that, and now we actually support the extension.
