### ISSUE TITLE
setDepthClipMode is not allowed on MTLFeatureSet_iOS_GPUFamily1_v4

### ISSUE THREAD

**Issue by TillAlex** [KhronosGroup/MoltenVK#136]
While testing MoltenVK with an A7 GPU i found the following Metal validation error:

-[MTLDebugRenderCommandEncoder setDepthClipMode:]:2502: failed assertion `-[MTLDebugRenderCommandEncoder setDepthClipMode:] is only supported on MTLFeatureSet_iOS_GPUFamily2_v1 and later'

Seems to be detected wrongly in https://github.com/KhronosGroup/MoltenVK/blob/206461371f6683b0e3ce93dc5ee9be8349b2919c/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L329

**Comment by billhollings** [comment]
Fixed in PR #140. Please retest.

**Comment by TillAlex** [comment]
Works for me
