### ISSUE TITLE
VulkanSDK 1.2.176.1 fails to install on macOS 10.14.6 Mojave

### ISSUE THREAD

**Issue by buzmeg** [KhronosGroup/MoltenVK#1360]
Hi, folks,

I just tried to install the latest Vulkan SDK on Mojave and it failed on two different computers.  One completely pristine and one that had a previous Vulkan installation on it.

Installation of VulkanSDK on macOS 10.14.6 Mojave fails with "Error during installation process (com.lunarg.vulkan):
Execution failed (Unexpected exit code: 255): "python3 /Users/username/VulkanSDK/1.2.176.1/install_vulkan.py --install-json-location /Users/username/VulkanSDK/1.2.176.1 --force-install""

Same SDK version succeeds on macOS Catalina 10.15.7.

Thanks.

(Sorry.  I originally posted this on the Vulkan/LunarG issues area, but then realized that this is probably a better choice.  Let me know if you want me to delete the one over on the Vulkan/LunarG area.)

**Comment by richard-lunarg** [comment]
Hello @buzmeg ,

Over on LunarG is actually the perfect place to report this since we package the SDK. I've taken an initial stab at your issue and followed up on that post over there:

https://vulkan.lunarg.com/issue/view/609cf8d85df1127f84292948#issue/assign/609cf8d85df1127f84292948/5e8ddae0e0d2a33ca1602dfa

Richard

**Comment by buzmeg** [comment]
Thanks.  I responded over there and will close the issue here.

**Comment by asmaloney** [comment]
(I tried to create an account over on LunarG, but it wouldn't let me login.)

I ran into this error trying to install VulkanSDK 1.2.182.0 on macOS 10.14.6.

For anyone who lands here by googling this issue, the solution is to click "Ignore" when it gives the error, then install it on the command line like this (substitute your USERNAME):

> sudo python3 /Users/USERNAME/VulkanSDK/1.2.182.0/install_vulkan.py --install-json-location /Users/USERNAME/VulkanSDK/1.2.182.0/ --force-install
