### ISSUE TITLE
Missing required extension in MVK in VulkanSDK 1.2.176.1?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/MoltenVK#1363]
I am getting the validation warning:

```
Missing extension required by the device extension VK_KHR_portability_subset: VK_KHR_get_physical_device_properties2. The Vulkan spec states: All required extensions for each extension in the VkDeviceCreateInfo::ppEnabledExtensionNames list must also be present in that list (https://vulkan.lunarg.com/doc/view/1.2.176.1/mac/1.2-extensions/vkspec.html#VUID-vkCreateDevice-ppEnabledExtensionNames-01387)"
```

`VK_KHR_get_physical_device_properties2` is not in the list returned by enumerateDeviceExtensionProperties (vulkan.hpp name) so I can't enable it. What am I doing wrong or is the extension missing? If I ignore the validation warning, <del>everything works.</del> it crashes. (I was confusing this and an earlier validation warning telling me I needed to enable VK_KHR_portability_subset when I wrote the original.)

**Comment by MarkCallow** [comment]
I did an internet search for example using VK_KHR_portability_subset and found nothing.

**Comment by cdavis5e** [comment]
> `VK_KHR_get_physical_device_properties2` is not in the list returned by enumerateDeviceExtensionProperties

Of course not. It's an instance extension. Did you enable it on the instance?

**Comment by MarkCallow** [comment]
> Of course not. It's an instance extension. Did you enable it on the instance?

The validation message came during createDevice so I thought it must be a device extension. Furthermore since `VK_KHR_portability_subset` is a device extension how am I supposed to know when I create the instance that I need to enable `VK_KHR_get_physical_device_properties2`. Should I just do it on spec. in case the app finds it is running on a Portability implementation?

**Comment by richard-lunarg** [comment]
>Should I just do it on spec. in case the app finds it is running on a Portability implementation?

The short answer is yes.

The longer explanation is the portability extension is provisional, and may yet change again. The main purpose is to "alert" you that you are running on a portability implementation and thus your app may be compromised if it is not aware of this. The Validation error you are getting is doing it's job by telling you that you are indeed on a portability extension and you have not made any efforts to check to see if this is the case, and/or accommodate that. Any application that expects to be able to run without issue on a fully conformant Vulkan implementation can leave this unimplemented and a validation error will be thrown if the environment is not what it expects. Conversely, by making use of the extension you are saying your app expects to find itself on a portability implementation (like MoltenVK), and your app has been coded accordingly.

I hope that helps.

**Comment by billhollings** [comment]
>how am I supposed to know when I create the instance that I need to enable VK_KHR_get_physical_device_properties2

@MarkCallow You make a good point. As @richard-lunarg indicates, the `VK_KHR_portability_subset` extension is provisional, so we can possibly modify it before it becomes final. I've [posted a discussion question](https://github.com/KhronosGroup/Vulkan-Portability/issues/25) to the portability group about the instance vs device requirement.

**Comment by MarkCallow** [comment]
> I hope that helps.

Yes. Thanks. I now check for `VK_KHR_get_physical_device_properties2` and if it exists I enable it assuming doing so is basically harmless if not used. The cost is a loop over the list of enumerated instance extensions and many `strncmp`s.

**Comment by billhollings** [comment]
I'm closing this as answered here. Further followup will occur in the the portability issue listed above.
