### ISSUE TITLE
VkPhysicalDevicePortabilitySubsetFeaturesKHR::imageViewFormatSwizzle is VK_FALSE even when MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE is set

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/MoltenVK#1364]
I have the environment variable `MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE` set to 1. Nevertheless I am getting the following validation error: 

```
Validation Error: [ VUID-VkImageViewCreateInfo-imageViewFormatSwizzle-04465 ] Object 0: handle = 0x10782b018, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x82ae5050 | vkCreateImageView (portability error): swizzle is disabled for this device. The Vulkan spec states: If the [VK_KHR_portability_subset] extension is enabled, and VkPhysicalDevicePortabilitySubsetFeaturesKHR::imageViewFormatSwizzle is VK_FALSE, all elements of components must be VK_COMPONENT_SWIZZLE_IDENTITY. (https://vulkan.lunarg.com/doc/view/1.2.176.1/mac/1.2-extensions/vkspec.html#VUID-VkImageViewCreateInfo-imageViewFormatSwizzle-04465)
```

According to this message the portability feature bit is false. Shouldn't it be true since the env. var is set? 

If the bit was true, is there something I should do programmatically to enable use of swizzle?

**Comment by billhollings** [comment]
Yes...if you have enabled `MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE`, then `VkPhysicalDevicePortabilitySubsetFeaturesKHR::imageViewFormatSwizzle` will return `VK_TRUE`.

It's hard to see where this could be going wrong in MoltenVK:

https://github.com/KhronosGroup/MoltenVK/blob/6f980c3d3eb8a457dd22f2b692ae1dd5bb6fd377/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L244-L245

<br/>
Can you verify that this value is being returned correctly by MoltenVK in your environment, please? If so, then it is likely an [issue within the validation layer](https://vulkan.lunarg.com/issue/home).

**Comment by MarkCallow** [comment]
I added the query for `VkPhysicalDevicePortabilitySubsetFeaturesKHR` into my program. Here's the output from the Xcode debugger:

```
imageViewFormatSwizzle	vk::Bool32	1
```

Looks like it is an issue with the validation layer.

**Comment by MarkCallow** [comment]
I've created [issue #1029](https://vulkan.lunarg.com/issue/view/60a5114e5df112f29ee3314e) at LunarG.

**Comment by richard-lunarg** [comment]
Mark, 

I thought the same thing at first, but we are/were only half way there. You have queried for the capability, but you have not enabled it.

For example to get the features struct filled out:

VkPhysicalDevicePortabilitySubsetFeaturesKHR portabilityFeatures = {};
portabilityFeatures.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PORTABILITY_SUBSET_FEATURES_KHR;

VkPhysicalDeviceFeatures2KHR physicalDeviceFeatures2 = {};
physicalDeviceFeatures2.sType =  VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2;
physicalDeviceFeatures2.pNext = & portabilityFeatures;
vkGetPhysicalDeviceFeatures2(physicalDevice, &physicalDeviceFeatures2);

What we've done now is queried for device capabilities. You also have to enable them when you create the device by passing in the same struct in the VkDeviceCreateInfo's pNext element:

// Create the physical device
VkDeviceCreateInfo createInfo = {};
createInfo.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
createInfo.pQueueCreateInfos = &queueCreateInfo;
createInfo.queueCreateInfoCount = 1;
createInfo.pEnabledFeatures = pVulkanInstance->getPhysicalDeviceFeatures(nDeviceToUse);
createInfo.enabledExtensionCount = extNamesDevice.size();
createInfo.ppEnabledExtensionNames = extNamesDevice.data();
createInfo.pNext = (VkPhysicalDevicePortabilitySubsetFeaturesKHR*)&portabilityFeatures;

In my code snipet from above (stolen from one of my projects), I've set createInfo.pNext to the portabilityFeatures structure that is filled in with the features you want to use (I just take all of them). If you do this, you'll see the validation error go away.

**Comment by billhollings** [comment]
I'm going to close this as not a MoltenVK issue. Assuming the feedback from @richard-lunarg fixes this, it's not an issue anywhere, and any residual issue after testing will be in the validation layers.

**Comment by MarkCallow** [comment]
Thank you @richard-lunarg. After "enabling" the feature I no longer get the validation error. Two points though:

* the validation message is misleading. It strongly give the impression that it fails because the feature bit is false. There is no hint that it has to be enabled.
* it feels weird to have to enable something that is a standard Vulkan feature. I know Vulkan extensions normally require things to be enabled but this is not an extension. It is a contraction. Shouldn't you be trying to confirm that the app is ready to handle the absence of a standard feature not that it is ready to use it?

**Comment by ncesario-lunarg** [comment]
@MarkCallow If you were writing your app to run on a "Vulkan compliant" implementation, you are correct, this should not (and is not) necessary. However, you are writing an app to run on "Vulkan portable" implementation, which requires querying for some "standard" features before using them to make your app "portable" (@billhollings please correct me if I'm wrong here). MoltenVK enables this feature, but another portable implementation may not, and MoltenVK uses the "Vulkan portability interface."

The [spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap41.html) is pretty clear that _features_ *must* be enabled before they are used, so this looks like the validation layers are behaving as expected.
