### ISSUE TITLE
Moving beyond C++11?

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1372]
We're looking for some dev-user input on whether it would be appropriate to move forward from `C++11` to `C++14` or `C++17` at this time?

The additional language features would allow us to simplify some internal code. 

This change would of course have no impact on the Vulkan API itself, which is `C` based.

Since each move has a potential impact on everyone, as a first choice, we'd probably like to move directly to `C++17`, to help defer any additional jumps a little further down the road.

Thoughts and comments?

**Comment by aerofly** [comment]
I would support this step. C++ 17 is in XCode already for some years, so I assume it's safe to assume that basically all MoltenVK users are using an XCode version with C++ 17 support. But I might be wrong.

**Comment by past-due** [comment]
I don't see an issue, provided it doesn't impact the minimum deployment target. (Which means staying away from things like `<filesystem>` which requires a minimum deployment target of macOS 10.15, IIRC.)
