### ISSUE TITLE
Block compression on IOS?

### ISSUE THREAD

**Issue by BeastLe9enD** [KhronosGroup/MoltenVK#1378]
Hey, I noticed that in the MVKDevice.mm where the VkPhysicalDeviceFeatures are queried, there is a check that block compression is only available on MacOS. Since the new iPad Pro has the M1 processor and it supports BC, it should be available on IOS too i think? (I dont have an iPad Pro to test this, but it makes sense for me)

**Comment by cdavis5e** [comment]
You'd think so, but the `MTLPixelFormat` enumerants for the BCn formats aren't available yet on iOS AFAIK.

**Comment by cdavis5e** [comment]
Welp, the betas are out, but the BCn formats *still* aren't available on iOS. I don't think we're gonna see them anytime soon.

**Comment by BeastLe9enD** [comment]
yea, I hoped that tooo... I have the feeling that apple ignores everything related to new graphics-api features

**Comment by billhollings** [comment]
Hmmm..maybe a patent royalty question? They had to cover BC for Macs since it was legacy there, but perhaps don't want to pay for it for the billions of iOS devices.
