### ISSUE TITLE
Query pool CTS tests failing on M1

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1385]
Strangely, for the CTS tests in `vk-default/query-pool.txt`:

- AMD & Intel: Pass: 188 / Fail:  0.
- M1: Pass: 48 / Fail: 140.

The M1 numbers can sometimes change, indicating some form of race condition. Some failing tests can pass occasionally when running in batch, but always fail when run alone.

It seems to be connected to those tests that have multiple render passes with occlusion queries in them. Subsequent renderpass queries seem to be overwriting, or corrupting previous ones, but in ways that have no obvious cause as yet. The writes seem to be occurring to the correct buffer offsets, and appear so in GPU capture, but then the buffer offsets seem to be shifted when reading the contents back to the CPU for test verification.

I'm currently looking into this.

@cdavis5e I'm continuing with this...but if any possible causes pop into your head, feel free to suggest paths for me to research. So far I have eliminated the type of Vulkan wait used before the CPU read, and buffer alignment corruption on the copy from temporary buffer to visibility buffer. Next attempt will be to see if M1 somehow requires `MTLFences` or `MTLEvents` on the `MTLBuffers` between visibility compute encoders (which it shouldn't per docs).

**Comment by js6i** [comment]
I was just investigating an issue with a game where shadows are flickering, and it's this exact problem. What I found to work is a) changing visibility buffer offsets for each render pass, so we don't use the same offset twice in a command buffer, and b) fencing - update on accumulation, wait on subsequent queried rendering.
a) might be better performance wise, but I don't know if it's worth the extra complication of making sure we have enough space in the visibility buffer. Perhaps we could use a temporary allocation for it and get a new one once we run out.

**Comment by billhollings** [comment]
@js6i

Thanks very much for your input. Very valuable!

I just have a couple of questions before delving into a fixes like this in MoltenVK...

> issue with a game 

Was this a MoltenVK game, or a Metal-only game? If MoltenVK...did you have a PR you could submit here?

> it's this exact problem

Do you mean it appeared only for M1 and not AMD/Intel, like here?

> don't use the same offset twice in a command buffer

Do you mean Vulkan or Metal command buffer (I assume Metal but want to be sure). And if Metal, do you mean command buffer or command encoder? Metal docs talk about command encoders needing this restriction, but not command buffers (but of course the docs may not be taking into consideration all platforms).

> a) ... _**and**_ b) ...

Can you clarify whether you needed to do **_both_** of these, or one or the other. The _and_ implies both, but your subsequent discussion seems to indicate a choice.

> Perhaps we could use a temporary allocation

This is already how visibility buffers are handled in MoltenVK, so it should be fairly straightforward to extend this to keeping a pool of these temporary buffers and potentially using more than one per Metal command buffer.

**Comment by js6i** [comment]
Yeah, sorry for the terseness..

> > issue with a game
> 
> Was this a MoltenVK game, or a Metal-only game? If MoltenVK...did you have a PR you could submit here?

It's a Windows game that I ran with wine and MoltenVK. Sure, I'll clean it up and prepare a PR.

> > it's this exact problem
> 
> Do you mean it appeared only for M1 and not AMD/Intel, like here?

Yes, and I tracked it down to wrong visibility results. I.e. stuff was flickering (I suppose) due to 0's overwriting other values, and I also saw repeated values for different queries - sounds exactly like what you saw.

> > don't use the same offset twice in a command buffer
> 
> Do you mean Vulkan or Metal command buffer (I assume Metal but want to be sure). And if Metal, do you mean command buffer or command encoder? Metal docs talk about command encoders needing this restriction, but not command buffers (but of course the docs may not be taking into consideration all platforms).

As far as I could tell, we already use different offsets within an encoder (like the docs say). That was not relevant for my case, as there only was a single query per encoder anyway. I meant Metal command buffer.

> > a) ... _**and**_ b) ...
> 
> Can you clarify whether you needed to do **_both_** of these, or one or the other. The _and_ implies both, but your subsequent discussion seems to indicate a choice.

Sorry, just either of these. It looks like fences synchronize the buffer accesses (as if the vis buffer wasn't tracked like other usages are), and using different locations in the buffer sidesteps the issue of synchronization altogether.

> > Perhaps we could use a temporary allocation
> 
> This is already how visibility buffers are handled in MoltenVK, so it should be fairly straightforward to extend this to keeping a pool of these temporary buffers and potentially using more than one per Metal command buffer.

Right, I guess it should be fine.

**Comment by js6i** [comment]
The two commits above are (more or less) what I did to work around this issue. Note that I didn't design them for the general case, only for what was needed for the particular case I encountered, so they are likely deficient in some ways!

**Comment by billhollings** [comment]
> The two commits above

Thanks! I can take it from here to generalize this if you'd like.

If both solutions work, did you find either solution to be preferable? I'd probably lean towards buffer offset management rather than introducing `MTLFences` here. But if the other works better or is more efficient, we can use fences.

Does your environment only have one Vulkan command buffer per queue submit? The lifespan of `MVKCommandEncoderState` (and the containing `MVKCommandEncoder`) is tied to the execution of a single Vulkan command buffer...whereas MoltenVK typically assigns one `MTLCommandBuffer` per Vulkan submit, which can have many Vulkan command buffers. 

This means many `MVKCommandEncoderStates` may come and go during the lifespan of one `MTLCommandBuffer`, so if the restriction about not reusing offsets is tied to a `MTLCommandBuffer`, we might have to move `_mtlVisibilityResultOffset` to `MVKQueueCommandBufferSubmission`.

**Comment by js6i** [comment]
> > The two commits above
> 
> Thanks! I can take it from here to generalize this if you'd like.

Sure, go ahead, any generalization should probably be more driven by the conformance tests.. unless you have other stuff queued up, then I'll probably want to cook something up sooner.

> If both solutions work, did you find either solution to be preferable? I'd probably lean towards buffer offset management rather than introducing `MTLFences` here. But if the other works better or is more efficient, we can use fences.

The results looked the same - I didn't benchmark it in any meaningful way. I'd expect avoiding fences to be faster in general. I guess I could time it.

> Does your environment only have one Vulkan command buffer per queue submit? The lifespan of `MVKCommandEncoderState` (and the containing `MVKCommandEncoder`) is tied to the execution of a single Vulkan command buffer...whereas MoltenVK typically assigns one `MTLCommandBuffer` per Vulkan submit, which can have many Vulkan command buffers.

Well, the occlusion queries were limited to a single Vulkan and Metal command buffer. Not sure about the rest, but I think it shouldn't matter.
 
> This means many `MVKCommandEncoderStates` may come and go during the lifespan of one `MTLCommandBuffer`, so if the restriction about not reusing offsets is tied to a `MTLCommandBuffer`, we might have to move `_mtlVisibilityResultOffset` to `MVKQueueCommandBufferSubmission`.

I see, I don't know for sure that's the restriction, but I can't think of any other natural cutting point that could be it. So I would assume that it's a single `MTLCommandBuffer`. Maybe the tests can shed some more light on it.

**Comment by billhollings** [comment]
Okay...not reusing an offset during the life of a Vulkan command buffer fixes all the CTS query tests.

I did have to modify your patch to perform the offset increase in `MVKOcclusionQueryCommandEncoderState::endOcclusionQuery()` instead, otherwise it sets the incorrect offset into the Metal encoder.

I am going to extend the solution to cover an entire `MTLCommandBuffer` before submitting this as a PR.

**Comment by js6i** [comment]
Cool, thanks!

> I did have to modify your patch to perform the offset increase in `MVKOcclusionQueryCommandEncoderState::endOcclusionQuery()` instead, otherwise it sets the incorrect offset into the Metal encoder.

Oh right, I moved the `+ kMVKQuerySlotSizeInBytes` below the `push_back` call while cleaning up and broke that.
