### ISSUE TITLE
Feature request: support VkPipelineCache with MSL shaders

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#14]
Source 2 caches compiled shaders by retrieving cached VkPipelineCache with vkGetPipelineCacheData and loading pipeline cache with VkPipelineCacheCreateInfo.pInitialData.  Since MoltenVK at runtime converts from SPIR-V to MSL, it would be ideal if it could store the generated MSL inside of a VkPipelineCache (hashed on the SPIR-V to avoid subsequent conversions).

Ideally the VkPipelineCache would store Metal shader binaries, but as I understand it there is no way to reflect this at runtime so it seems caching the MSL is the best that can be done for now.

**Comment by hideyhole** [comment]
We'd love to have this feature as well!

**Comment by danginsburg** [comment]
Implemented by @billhollings in #118 .  Tested and confirmed it is working great (huge reduction in stutters in Dota).  Closing.
