### ISSUE TITLE
Assertion failure when declared uniform size > memory allocated even if size in shader has been specialized

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/MoltenVK#1420]
I have the following shader:

```
// Copyright 2017 Mark Callow
// SPDX-License-Identifier: Apache-2.0

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (location = 0) in vec4 inPos;
layout (location = 1) in vec2 inUV;

struct Instance
{
	mat4 model;
};

layout(constant_id = 1) const int instanceCount = 20;

layout (binding = 0, std140) uniform UBO
{
	mat4 projection;
	mat4 view;
	Instance instance[instanceCount];
} ubo;

layout (location = 0) out vec2 outUV;
layout (location = 1) out flat float lambda;

void main() 
{
	outUV = inUV;
        lambda = gl_InstanceIndex+0.5;
	mat4 modelView = ubo.view * ubo.instance[gl_InstanceIndex].model;
	gl_Position = ubo.projection * modelView * inPos;
}
```

I allocate the memory for the uniform buffer with

```
    uint32_t uboSize = _PAD16(sizeof(uboVS.matrices))
             + instanceCount * sizeof(UboInstanceData);

    // Vertex shader uniform buffer block
    vkctx.createBuffer(
        vk::BufferUsageFlagBits::eUniformBuffer,
        vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent,
        uboSize,
        nullptr,
        &uniformDataVS.buffer,
        &uniformDataVS.memory,
        &uniformDataVS.descriptor);
```

If the c++ variable `instanceCount < 20` I get the following assertion during VkQueueSubmit:

```
validateFunctionArguments:3727: failed assertion `Vertex Function(main0): argument ubo[0] from buffer(1) with offset(0) and length(1024) has space for 1024 bytes, but argument has a length(1408).'

```

The bug is that this assertion failure happens even when I have specialized  the shader constant `instanceCount` to be equal to the c++ `instanceCount`, if the specialized value is < 20.

I know that my specialization code is working because if I change the default constant value to 1 in the shader, my app correctly show all n instances when n > 1.

**Comment by billhollings** [comment]
As [mentioned](https://github.com/KhronosGroup/MoltenVK/issues/1421#issuecomment-898627313) the other issue you posted, Metal does not support using function constants (specialization) to specify the length of an array.

So I suspect that the shader expects that the buffer needs to be `sizeof(Instance) * 20`, and you are under-allocating it when the app knows the actual number is less than `20`.

**Comment by MarkCallow** [comment]
> So I suspect that the shader expects that the buffer needs to be sizeof(Instance) * 20, and you are under-allocating it when the app knows the actual number is less than 20.

Probably correct. Please see my  comment in issue #1421 for further info and question.

**Comment by billhollings** [comment]
>Probably correct. Please see my comment in issue #1421 for further info and question.

Closing this...and a secondary effect of the discussion in #1421.
