### ISSUE TITLE
vkCreateMacOSSurfaceMVK crashed with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by SpectralDragon** [KhronosGroup/MoltenVK#1422]
I try to create surface on my mac using MTKView, but I got crash `EXC_BAD_ACCESS`, but for SDL2, `SDL_Vulkan_CreateSurface` return correct `VkSurfaceKHR` with same `VkInstance`.

Vulkan SDK: 1.2.182.0

Layers: `VK_LAYER_KHRONOS_validation`
Extensions: `VK_KHR_get_physical_device_properties2`, `VK_KHR_surface`, `VK_EXT_debug_utils`, `VK_MVK_macos_surface`

This is how my implementation looks:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/6003467/129428047-73b98fef-8d0d-4c25-81ef-416a9bf0739c.png">

Also, proof that my view contents `CAMetalLayer`:
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/6003467/129428109-6ed8fe48-7f38-4b5f-8583-9fe2ba142e55.png">

I can't find any resolved issue with my problem(

**Comment by cdavis5e** [comment]
How did you get the `VkInstance` object? How are you linking to `vkCreateMacOSSurfaceMVK()`? Are you linking to MoltenVK, or to the Vulkan loader (`vulkan.framework` on macOS)?

If instead of using Swift, you use Objective-C for your class, does it still break?

Where does Xcode say within MoltenVK the crash occurs? It doesn't even matter if you don't have a source location; the function and offset are enough.

**Comment by SpectralDragon** [comment]
@cdavis5e

> How did you get the VkInstance object?

I published source code: https://github.com/LiteCode/AdaEngine
`AdaEditor/main.swift` - Create window and initialize Vulkan
`Vulkan/` - all wrappers

> Are you linking to MoltenVK, or to the Vulkan loader (vulkan.framework on macOS)?

Currenly has `libvulkan.dylib` and set required env variables:

```bash
export VULKAN_SDK="/Users/v.prusakov/VulkanSDK/1.2.182.0/macOS"
export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"
export VK_ICD_FILENAMES="$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"

```

> If instead of using Swift, you use Objective-C for your class, does it still break?
I can try tomorrow.

> Where does Xcode say within MoltenVK the crash occurs?

App crashed in `MVKSurface` constructor
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/6003467/129429837-fef1e321-9104-470d-8ed3-a1f95e591fc7.png">

**Comment by cdavis5e** [comment]
So it's crashing trying to figure out whether the passed-in object is an `NSView` or a `CAMetalLayer`. To do this, it needs to invoke an Objective-C method. This leads me to suspect that this is the offending line in your code:
```swift
            pView: withUnsafePointer(to: view, { $0 }))
```
That is, you think you're getting a raw pointer to an Objective-C object, but you might not be. It might, for example, be a pointer to the *variable* holding the Objective-C pointer.

This is why I suspect that it would work if you used Objective-C. If it does, we'll know this is the most likely explanation.

You need to convert *the object reference itself* to an `UnsafeRawPointer`. The easiest way to do that, I think, is to simply pass the reference here and let implicit bridging work its magic:
```swift
            pView: view)
```
Did you try that before, and the compiler complained?

**Comment by cdavis5e** [comment]
Another possibility is that the raw pointer is being destroyed before you expect. According to (the docs for `withUnsafePointer(to:_:)`)[https://developer.apple.com/documentation/swift/2998149-withunsafepointer]:

> The pointer argument is valid only for the duration of the function’s execution.

If what I suggested above doesn't work, then the solution may be to enclose the entire call to `vkCreateMacOSSurface()` in the closure passed to `withUnsafePointer(to:_:)`.

**Comment by SpectralDragon** [comment]
Yeah! You was right, that `withUnsafePointer(to:_:)` return pointer to local variable. I fixed that crash and pass `UnsafeMutableRawPointer` using `Unmanaged.passRetain().autorelease().toOpaque()` call. It's work very well, but I don't think that is safety way :D

Thanks for your suggestions you saved my day! And thanks, that you answer so fast, like a Flash, that was important for me <3
