### ISSUE TITLE
vulkan.hpp wont compile by default?

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1424]
Not sure if this is a vulkan.hpp issue or a MoltenVK issue, but i'm getting this error:
In file included from libs/MoltenVK-1.2.182.0/include/vulkan/vulkan.hpp:6405:
libs/MoltenVK-1.2.182.0/include/vulkan/vulkan_structs.hpp:32564:5: error: defaulted definition of copy assignment operator is not constexpr
    VULKAN_HPP_CONSTEXPR_14 MetalSurfaceCreateInfoEXT &
    ^

It complains about this code:
    VULKAN_HPP_CONSTEXPR_14 MetalSurfaceCreateInfoEXT &
                            operator=( MetalSurfaceCreateInfoEXT const & rhs ) VULKAN_HPP_NOEXCEPT = default;

I'm just removing the VULKAN_HPP_CONSTEXPR_14 usage, is this something that might need to be changed in the generator as well?

**Comment by cdavis5e** [comment]
This does sound like a `vulkan.hpp` issue. The `VK_EXT_metal_surface` extension is by no means specific to MoltenVK--in fact, it was originally proposed by @kvark because he wanted a WSI extension for Metal that *wasn't* specific to MoltenVK.
