### ISSUE TITLE
MoltenVK reports that Vulkan version is 1.2, but descriptor indexing extension is not promoted.

### ISSUE THREAD

**Issue by zakarumych** [KhronosGroup/MoltenVK#1430]
In my application I optionally use descriptor indexing.
For Vulkan < 1.2 I check for the extension `VK_EXT_descriptor_indexing` and if it has one I fetch `VkPhysicalDeviceDescriptorIndexingFeatures`.
For Vulkan >= 1.2 I expect same features to appear in `VkPhysicalDeviceVulkan12Features`.
On my platform content of `VkPhysicalDeviceDescriptorIndexingFeatures` and corresponding fields in `VkPhysicalDeviceVulkan12Features` differ. Specifically all fields in `VkPhysicalDeviceVulkan12Features` are `0` and non`0` in `VkPhysicalDeviceDescriptorIndexingFeatures`

**Comment by billhollings** [comment]
>Naturally when I link to manually built MoltenVK.dylib I link directly to it and it advertises Vulkan 1.1

You can experiment with this by renaming the `libMoltenVK.dylib` in the SDK package to something else, and then replacing it with the version you compiled from MoltenVK. Comparing the results will indicate whether the results are coming from MoltenVK or the loader and layers.

**Comment by SRSaunders** [comment]
I have noticed the following when linking to the latest SDK using either:
a) the SDK loader and layers (/usr/local/lib/libvulkan.dylib) or
b) the SDK version of MoltenVK (VulkanSDK/1.2.198.1/MoltenVK/dylib/macOS/libMoltenVK.dylib)

1. For both cases above, when I query the version using `vkGetPhysicalDeviceProperties(gpu.device, &gpu.props)` and the following Vulkan convenience macros, I get:

`VK_API_VERSION_MAJOR(gpu.props.apiVersion)` = 1 (expected)
`VK_API_VERSION_MINOR(gpu.props.apiVersion)` = 1 (unexpected, was expecting 2)
`VK_API_VERSION_PATCH(gpu.props.apiVersion)` = 198 (expected)

2. When I run vulkaninfo or vkconfig I get 1.2.198 as expected

So it appears that MoltenVK always reports its internal version (1.1) when using this method, even for bundled versions from the SDK.  Should I be using a different method to retrieve the official Vulkan SDK version (1.2)?

**Comment by zakarumych** [comment]
@SRSaunders why were you expecting version 1.2 though? It doesn't not support 1.2 features yet.

**Comment by cfnptr** [comment]
Yeah, MoltenVK currently supports up to Vulkan 1.1, and in [this](https://github.com/KhronosGroup/MoltenVK/pull/1446) pull request were added check and correction for the `VK_API_VERSION_MINOR`.

**Comment by SRSaunders** [comment]
Thank you both for your quick feedback.  I guess I was naively expecting the Vulkan instance version and API version to be aligned in the context of the Vulkan SDK.  However, for the reasons stated above by @zakarumych this should not be the case.  They need to be decoupled for alignment with version-specific feature sets.  To get the instance version (i.e. the SDK version), I now realize that I should call `vkEnumerateInstanceVersion(&instanceVer)` and use the same macros as above.

I now get:

`VK_API_VERSION_MAJOR(instanceVer)` = 1 (expected)
`VK_API_VERSION_MINOR(instanceVer)` = 2 (expected)
`VK_API_VERSION_PATCH(instanceVer)` = 198 (expected)

**Comment by LeeTeng2001** [comment]
Just want to say this has been a helpful thread! It fixes my issue with api version.
