### ISSUE TITLE
Document supported version of Vulcan/SPIRV

### ISSUE THREAD

**Issue by mcclure** [KhronosGroup/MoltenVK#144]
The README for MoltenVK has a section titled "MoltenVK and Vulkan Compliance" which explicitly lists the difference between the Vulkan spec and the subset implemented by MoltenVK. However, it does not specify which *version* of the spec this difference is against. I do not see an explanation of which version of Vulcan is targeted in the user's guide, either.

Since Vulkan 1.1 has been released, the MoltenVK README/"docs" should specify which version of Vulkan and which version of SPIRV MoltenVK targets. If Vulkan 1.0 is being targeted, it should say so, and it should furthermore say whether Vulkan 1.1 support is on-the-way or whether Vulkan 1.1 support in MoltenVK is not currently planned.

**Comment by billhollings** [comment]
Docs updated in PR #154.
