### ISSUE TITLE
Image Creation Issue

### ISSUE THREAD

**Issue by amagdach** [KhronosGroup/MoltenVK#1440]
Hi, I am creating VkImage with usage VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT and number of layers is bigger than 1 (VkImageCreateInfo.arrayLayers > 1). App is crashing with next log: [mvk-error] VK_ERROR_FEATURE_NOT_PRESENT: vkCreateImage() : This device does not support rendering to array (layered) attachments. 

But I don't using layered rendering. I need this usage flag to create image view (2D) for concrete slice and use it as colour attachment. So formally I didn't break some rules. And Metal lets me to do this kind of work, but not MoltenVK.

If I am creating image without this usage flag everything works in iOS, but in MacOS I get errors(not crashes) from validation layers because image views haven't this flag and used as colour attachments.

Will be happy to see your thoughts on this case.

**Comment by billhollings** [comment]
>But I don't using layered rendering. I need this usage flag to create image view (2D) for concrete slice and use it as colour attachment. So formally I didn't break some rules. And Metal lets me to do this kind of work, but not MoltenVK.

Thanks for catching this. You are correct. This error is inappropriate during `VkImage` creation, and should be moved to `VkImageView` creation, instead.

**Comment by billhollings** [comment]
>This error is inappropriate during VkImage creation, and should be moved to VkImageView creation, instead.

@amagdach This is fixed in PR #1443. Please retest with latest version of MoltenVK, and close this issue if fixed.

**Comment by amagdach** [comment]
This fix resolves initial issue and raises next question. If I need to create image view for all layers does it mean that I should shrink usage of image view by using VkImageViewUsageCreateInfo to exclude VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT?

**Comment by cdavis5e** [comment]
Yes that is correct.

**Comment by amagdach** [comment]
Thank you
