### ISSUE TITLE
Invalid SPIR-V binary version 1.5 for target environment SPIR-V 1.3

### ISSUE THREAD

**Issue by cfnptr** [KhronosGroup/MoltenVK#1445]
I am getting a validation layer error when creating VkShaderModule from compiled shader with glslc --target-env=vulkan1.2. But instance is created with VkApplicationInfo apiVersion = VK_API_VERSION_1_2. Looks like this is a validation layer bug because the shader module is being created and rendering is working correctly.

Vulkan ERROR: Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x7fdc9f069a18, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.5 for target environment SPIR-V 1.3 (under Vulkan 1.1 semantics).

Vulkan API: 1.2.189
MacOS 11.6
GPU: Intel Iris Plus Graphics 645

**Comment by cdavis5e** [comment]
We don't support Vulkan 1.2, so you can't use SPIR-V 1.5 yet.

The Vulkan loader is weird here. The *instance* Vulkan version may be 1.2 even as the *driver* Vulkan version is 1.1. That's what's probably happening here.

**Comment by cfnptr** [comment]
> We don't support Vulkan 1.2, so you can't use SPIR-V 1.5 yet.
> 
> The Vulkan loader is weird here. The _instance_ Vulkan version may be 1.2 even as the _driver_ Vulkan version is 1.1. That's what's probably happening here.

Oh, ok, thank you. When do you plan to add 1.2 support?

**Comment by cdavis5e** [comment]
> When do you plan to add 1.2 support?

Unfortunately, it's a ways off, especially since we're busy with trying to fix test conformance with 1.1. Since 1.2 also requires `KHR_buffer_device_address` support, it may never happen.
