### ISSUE TITLE
Swift Package Manager support?

### ISSUE THREAD

**Issue by wtholliday** [KhronosGroup/MoltenVK#1450]
I think MoltenVK would benefit from Swift Package Manager support, to make it easier to add to Xcode projects.

Does that seem like a good idea? I'm happy to help.

**Comment by wtholliday** [comment]
I'm currently wrapping the XCFramework. It's just not as pleasant of a workflow as source. Updating the XCFramework is harder, I have to put it somewhere, and it won't be versioned automatically. It's also harder to debug. Quoting the link above:

"Carefully consider whether you want to distribute your code in binary form because doing so comes with drawbacks. For example, a Swift package that contains a binary is less portable because it can only support platforms that its included binaries support."

There are probably other advantages to source (I'm no SPM expert). I think the only reasons for doing a XCFramework would be to protect IP (as apple mentions), or if the dependencies are too hard to deal with (though they could be packaged as binaries, which isn't ideal but at least would make the workflow easier).

**Comment by wtholliday** [comment]
Ah. My use case is probably a bit different than most. I've got an app which allows you to edit/run shadertoy-style GLSL shaders, so I need runtime conversion of shaders.

It actually might be better for me to use glslang and spire-cross directly rather than using MoltenVK, but I thought I'd offer my help anyway :)

**Comment by wtholliday** [comment]
I've created a package for SPIRV-Cross: https://github.com/KhronosGroup/SPIRV-Cross/pull/1769

Looks like adopting SPM would greatly simplify MoltenVKPackaging.xcodeproj. I think a lot of the scripts would go away, and `fetchDependencies` would go away (or be greatly simplified). The platform specific targets would go away as well (`MoltenVK-iOS/macOS/tvOS`) while still being able to build an XCFramework.

**Comment by SpectralDragon** [comment]
Hey! @wtholliday can you explain me how to integrate this dependency to existing SPM project? I got a lot of problems here with glm.hpp and so on. Maybe I should use some hacks to add it to my project?

**Comment by wtholliday** [comment]
Hi @SpectralDragon, sorry I ended up using SPIRV-Cross and glslang directly so I didn't use MoltenVK. Really I just needed to translate GLSL to metal for my app. So I never finished making a Swift Package for MoltenVK.

**Comment by SpectralDragon** [comment]
> Hi @SpectralDragon, sorry I ended up using SPIRV-Cross and glslang directly so I didn't use MoltenVK. Really I just needed to translate GLSL to metal for my app. So I never finished making a Swift Package for MoltenVK.

Ok, thanks) I’ll digging deeper, mb I can fix it)
