### ISSUE TITLE
Delayed frames

### ISSUE THREAD

**Issue by casey** [KhronosGroup/MoltenVK#146]
I'm using MoltenVK with Vulkano, a Vulkan wrapper for Rust.

I wrote a program which implements basic live-shader reloading. However, after loading the bytecode, it takes 10-30 seconds to see the new shader. 

I tried it on a linux box, and the reloaded shader was visible instantly, so I think the issue may be with MoltenVK.

My theory is that frames are stacking up without being displayed, so that by the time a new shader is ready, there are many frames queued up to be displayed.

Unfortunately, my code is in rust, so it may not be super helpful for debugging. The binary is here:
https://github.com/casey/vulkano-test/tree/shader-hot-reload

And I'm using a custom version of Vukano here:
https://github.com/casey/vulkano/tree/refactor-vulkano-shaders

**Comment by billhollings** [comment]
Any way we can get something specific to replicate the issue?

**Comment by casey** [comment]
I can create a minimal repro, but it would be in rust using Vulkano. Would that help?

**Comment by HalfVoxel** [comment]
I am also seeing this in Vulkano (the included 'triangle' example). As far as I can tell, it is related to AcquireNextImageKHR not blocking when it is supposed to block. According to the spec when using a FIFO swapchain it will pop one image per vsync, however I am getting FPS values way higher than any reasonable vsync rate (several hundred). On the other hand if I do block until the rendering is complete between every frame it runs at almost exactly 120 fps (which is likely the relevant vsync rate).

I also tried to call AcquireNextImageKHR with a timeout of 0, which according to the spec:

> If timeout is zero, then vkAcquireNextImageKHR does not wait, and will either successfully acquire an image, or fail and return VK_NOT_READY if no image is available.

However I am not seeing any VK_NOT_READY at all, and now it runs at more than 7000 fps even when supposedly rendering 100000 triangles per frame.

**Comment by HindrikStegenga** [comment]
I have dabbled with this stuff and MoltenVK in the past. vkAcquireImageKHR doesn't need to block. You should NOT rely on it for synchronizing your framerate. You should use external fences right before calling vkAcquireNextImageKHR instead. Take the cube example vulkan app and implement syncing with fences similar to that one.

**Comment by billhollings** [comment]
Closing. Please reopen if more information becomes available.
