### ISSUE TITLE
Slow timeline semaphore creation

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1472]
Is the creation/destruction of timeline semaphores expected to be really slow?

I'm creating an application that does work off-screen and i'm creating and destroying a single timeline semaphore each frame. On macOS this is taking up 15% of all time spent on my background thread, this does not include waiting on the submits. In comparison on a comparable windows amd machine this takes only 0.6%. I'm reading that timeline semaphores use MTLSharedEvent if it's supported. I'm running on macOS 10.15, so i gues that's what's being used. Is there any configuration maybe i can do to try and get the time it takes to create/destroy semaphores down?

**Comment by cdavis5e** [comment]
> Is the creation/destruction of timeline semaphores expected to be really slow?

No. I would assume that this is a problem with `MTLSharedEvent`. Does this happen on Big Sur or (especially) Monterey? If it does, maybe I can prod them into making it faster.

**Comment by MennoVink** [comment]
I'll get some more numbers friday when i got access to some mac pros with both catalina and big sur, it's where i did the initial measurements too.

Doing a test locally on a mbp 2015 i'm seeing most timeline semaphore creations take between 0.08 and 0.18ms, destruction takes around 0.05ms. Sometimes creations spike to 1.2ms however. While this doesn't seem much on average, my offscreen process runs at a very high framerate. I've got about 65ms of work per frame, however on a 28 core mac pro I'm using 26 cores for this, so that's able to run at around 2.5ms/frame. In that case a 0.2ms for semaphore creation+destruction is already 8%, a spike of 1.2ms though well that's almost 50%.

There's no way the mac pro actually runs at 2.5ms/f though, because i've got other bottlenecks on the renderthread (#1473) so the actual average time has to be higher on the mac pros for it to reach 15%, more info on friday.

I do realize that this use-case is kind of eccentric and on a 16.6ms budget frame this is not too bad. I also wouldn't i know what MVK could do to make it faster as it's just forwarding to a metal call. I gues i'm just confused why timeline semaphore creation+destruction would take 0.2ms on macos while it only takes about 0.021ms on windows. Trying on a newer os is definitely a good suggestion so i'll try that. As workaround i can just reuse the timeline semaphores across frames of-course and just keep incrementing it's value through the frames.

**Comment by MennoVink** [comment]
I didn't manage to access a mac with one of these os'es so cant be sure how it performs on those versions, our minimum target is lower anyway so it doesn't matter as much anyway.
I've found that the way timeline semaphores are specified they aren't really ment to be used for fine-grained synchronization. They're more of a one-per-thread kind of thing, so in that sense taking 0.2ms to create one is fine.
