### ISSUE TITLE
Vertex shader function could not be compiled into pipeline

### ISSUE THREAD

**Issue by palmerj** [KhronosGroup/MoltenVK#1484]
When trying to run Mortal Kombat XL on MacOS running Wineskin/crossover/MoltenVK I get the following errors. 

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:473:9: error: no member named 'gl_CullDistance' in 'main0_out'
    out.gl_CullDistance[0] = out.o5;
    ~~~ ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_48c64a754f51018d85d9719a2c5751764481a5d6
err:     fs  : FS_bae6d9d5b407ddd219b7dcaeb457942a161fc78e
[mvk-info] Converting SPIR-V:
```

and

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:686:9: error: no member named 'gl_CullDistance' in 'main0_out'; did you mean 'gl_ClipDistance'?
    out.gl_CullDistance[0] = out.o0.z;
        ^~~~~~~~~~~~~~~
        gl_ClipDistance
program_source:114:11: note: 'gl_ClipDistance' declared here
    float gl_ClipDistance [[clip_distance]] [2];
          ^
```

I read that gl_CullDistance is not supported in Metal. https://github.com/KhronosGroup/SPIRV-Cross/issues/1403. If that's the case, what is the work around?

The original downstream issue which contains more logging output is [here](https://github.com/Gcenx/WineskinServer/issues/184)

Many thanks.

**Comment by billhollings** [comment]
> I read that `gl_CullDistance` is not support in Metal. KhronosGroup/SPIRV-Cross#1403. If that's the case, what is the work around?

That is correct. As is the SPIRV-Cross discussion you quote.

However, it might make sense to modify SPIRV-Cross to at least support compilation and setting an output value, even if it can't be used as an MSL built-in, and will have no actual affect on the rendering behavior.

Can you file this, along with my comments, on the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues), please?

**Comment by palmerj** [comment]
> However, it might make sense to modify SPIRV-Cross to at least support compilation and setting an output value, even if it can't be used as an MSL built-in, and will have no actual affect on the rendering behavior.

> Can you file this, along with my comments, on the SPIRV-Cross issue list, please?

Ok many thanks.  Filled https://github.com/KhronosGroup/SPIRV-Cross/issues/1840

**Comment by billhollings** [comment]
> Filled KhronosGroup/SPIRV-Cross#1840

Thanks. Closing this here.
