### ISSUE TITLE
Wrong VkClearColorValue color values when using sRGB swapchain/textures

### ISSUE THREAD

**Issue by saschasc** [KhronosGroup/MoltenVK#1504]
In the method `MVKPixelFormats::getMTLClearColor` there is a fix to increment the clear value by half the ULP. This results in errors when using linear color values in combination with sRGB swapchain/textures.

https://github.com/KhronosGroup/MoltenVK/blob/f99384da9630717684e2838c70f13cdc1bae15bf/MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm#L472

Excerpt from the [Vulkan specs](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkClearColorValue.html):

> Floating point values are automatically converted to the format of the image, with the clear value being treated as linear if the image is sRGB.

So what does that mean when using a linear swapchain fromat like `VK_FORMAT_B8G8R8A8_SRGB` with a color space `VK_COLOR_SPACE_SRGB_NONLINEAR_KHR`?  Assume we want to have a clear color value of sRGB(11 / 255, 22 / 255, 33 / 255). To use this color we have to convert it to linear as the specs states. To accomplish this the well known formula can be used (e.g. [found in chapter 7.7.7 of the Metal Shading Language](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf#//apple_ref/doc/uid/TP40014364?language=objc)).

1. Desired clear color in sRGB color space: sRGB(11 / 255, 22 / 255, 33 / 255) = sRGB(0.043, 0.086, 0.123)
2. Manual conversion for `VkClearColorValue`: linear(0.0033, 0.0080, 0.0152)
3. bug introduced in `MVKPixelFormats::getMTLClearColor`by incrementing the clear color by half the ULP: linear(0.0053, 0.0099, 0.0172)
4. Conversion back to sRGB colorspace done by Vulkan: sRGB(16 / 255, 25 / 255, 35 / 255)

In my opinion, one should simply pass on the SRGB values without changing them. Any other opinions on this? @billhollings @cdavis5e?

The image below shows a triangle rendered with sRGB(11 / 255, 22 / 255, 33 / 255) and the background with the measured sRGB value of sRGB(16 / 255, 25 / 255, 35 / 255).

![image](https://user-images.githubusercontent.com/84325903/149034722-857b945a-3851-48e0-8148-18f74cd8659c.png)

**Comment by billhollings** [comment]
I'm having trouble following the details of your steps 1-4:

Does this flow (1-4) exist already?

- (2) doesn't exist yet, correct? And so (3) is currently operating on the sRGB value itself (sRGB(0.043, 0.086, 0.123))?
- (4) What do you mean "done by Vulkan"? 

> In my opinion, one should simply pass on the SRGB values without changing them.

Just to be clear, it sounds like you are recommending that we just remove the sRGB formats from the existing ULP adjustment case statements, so the sRGB values are not adjusted...and _**not**_ introduce the sRGB->Linear conversion in (2)?

**Comment by saschasc** [comment]
> does this flow (1-4) exist already?

I don't know what you mean with your question. It's just a normal clear color call using the swap chain format VK_FORMAT_B8G8R8A8_SRGB. If it helps I can provide you a diff for the Vulkan tutorials from Sascha Willems to reproduce it.

Step 1) This is the sRGB color (non-linear) which a user wants to clear. The sRGB with the floating point representation is the same.

Step 2) This calculation has to be done by the user, since Vulkan specification expects this in linear color space as mentioned above in the excerpt from the Vulkan spec.
Step 3) Introduces the bug.
Step 4) When using a swap chain with the fromat VK_FORMAT_B8G8R8A8_SRGB and a color space of VK_COLOR_SPACE_SRGB_NONLINEAR_KHR the color transformation from linear to sRGB is done automatically. In contrary when using the format `VK_FORMAT_B8G8R8A8_UNORM` where the user would need to apply the transformation from linear to sRGB within the shader.

```
float linear = do_processing();
float s;
if (linear <= 0.0031308) s = linear * 12.92;
else s = 1.055 * pow(linear, 1.0/2.4) - 0.055; 
```

> Just to be clear, it sounds like you are recommending that we just remove the sRGB formats from the existing ULP adjustment case statements, so the sRGB values are not adjusted...and not introduce the sRGB->Linear conversion in (2)?

Step 2 is needed and done by the user! But skipping the ULP adjustment solves the bug.

**Comment by billhollings** [comment]
> I don't know what you mean with your question.

Thanks. You've clarified my confusion now. I was initially reading it that you felt we should be doing (2) inside MoltenVK somewhere, based on input coming from (1).

> skipping the ULP adjustment solves the bug

It looks like we can accomplish this by removing all the `*_SRGB` values from the case statements in `switch(vkFormat)` in `MVKPixelFormats::getMTLClearColor()`.

It's an easy enough fix. Do you want to submit a PR for that, that you have tested against your use case? Or do you want me to take care of it.

**Comment by saschasc** [comment]
> It's an easy enough fix. Do you want to submit a PR for that, that you have tested against your use case? Or do you want me to take care of it.

It would be great if you could take care of it. I never compiled the Vulkan SDK on my self.

What I did to test the bug was to add the ULP calculation to the Vulkan triangle tutorial and this resulted in the exact same error.

**Comment by billhollings** [comment]
> It would be great if you could take care of it. I never compiled the Vulkan SDK on my self.

No worries. I'll take care of it.

**Comment by saschasc** [comment]
Great. Let me know if you need help or further information.

**Comment by billhollings** [comment]
@saschasc  This is fixed in PR #1545. Please retest and close this issue if your issue is fixed.

**Comment by saschasc** [comment]
@billhollings What would be the easiest way to test it? I never compiled MoltenVK. Do I need to compile it?

**Comment by billhollings** [comment]
> What would be the easiest way to test it? I never compiled MoltenVK. Do I need to compile it?

Yes. You can follow the [instructions](https://github.com/KhronosGroup/MoltenVK#install) to fetch and build MoltenVK.

If you are using the SDK, you would then replace the `libMoltenVK.dylib` in the SDK (rename the old one first to revert afterwards). Typically, this means replacing `/usr/local/lib/libMoltenVK.dylib` with the file `MoltenVK/Package/Latest/MoltenVK/dylib/macOS/libMoltenVK.dylib`. I personally use symlinks to do this. See the [SDK Getting Started document](https://vulkan.lunarg.com/doc/sdk/1.3.204.1/mac/getting_started.html) for more info on how the SDK installs its components.

Or...you can wait for an updated MoltenVK with this code change to appear in the next SDK release, and test and verify these changes then.

**Comment by saschasc** [comment]
According to my current workload, it looks more like your last suggestion, unfortunately.

At least our codebase now compiles with the latest 1.3 SDK, which is not the case before. This should make the test relatively easy. I have looked at the code adjustments again and they look fine. Thanks!
