### ISSUE TITLE
Argument buffers: shader performance issues

### ISSUE THREAD

**Issue by adevaykin** [KhronosGroup/MoltenVK#1508]
## Argument Buffers Performance Issues

Hi there. First of all thanks for great job!

I started using argument buffers feature to have "bindless" textures and encountered shader runtime and MTL shader compiler performance issues quickly. 

1. Setting size of the array of texture bindings to a few thouthands (while actually sampling from the first 32 of them) in the very basic VulkanSamples descriptor_indexing sample already gives 0 FPS. The same for my shaders.
2. Using large arrays also leads to having HUGE compiled metal shader files. This can be observed by manually compiling metal shaders. Not a big issue, but for some shaders MTLCompilerService even hangs and never returns. Not directly moltenvk issue, but the reason is the nonoptimal metal shader code generated by moltenvk (or spirv-cross?)

Here is what I found out.

## Metal Shader Address Spaces

Metal shader generated by MoltenVK has an issue with address spaces. When array of textures inside argument buffer is accessed from within a function (as opposed to directly accessing it from `main()`), that array is provided as a function argument in _thread space_ which I guess results in copying all the data for every thread in runtime, which decreases performance to unusable state. 

As an example a bit adjusted shader from VulkanSamples descriptorindexing to have sampling operation inside a dedicated function. GLSL code:
```glsl
#version 450

#extension GL_EXT_nonuniform_qualifier : require

layout (set = 0, binding = 1) uniform sampler2D textures[];

layout (location = 0) in vec2 inUV;
layout (location = 1) flat in int inTexIndex;

layout (location = 0) out vec4 outFragColor;

vec4 getTextureValue(vec2 uv, int textureId)
{
	return texture(textures[nonuniformEXT(textureId)], uv);
}

void main() 
{
	outFragColor = getTextureValue(inUV, inTexIndex);
}
```

Resulting Metal code:
```metal
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct spvDescriptorSetBuffer0
{
    constant void* _m0_pad [[id(0)]];
    array<texture2d<float>, 1024> textures [[id(1)]];
    array<sampler, 1024> texturesSmplr [[id(1025)]];
};

struct main0_out
{
    float4 outFragColor [[color(0)]];
};

struct main0_in
{
    float2 inUV [[user(locn0)]];
    int inTexIndex [[user(locn1)]];
};

static inline __attribute__((always_inline))
float4 getTextureValue(thread const float2& uv, thread const int& textureId, thread const array<texture2d<float>, 1024> textures, thread const array<sampler, 1024> texturesSmplr)
{
    int _23 = textureId;
    return textures[_23].sample(texturesSmplr[_23], uv);
}

fragment main0_out main0(main0_in in [[stage_in]], constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
{
    main0_out out = {};
    float2 param = in.inUV;
    int param_1 = in.inTexIndex;
    out.outFragColor = getTextureValue(param, param_1, spvDescriptorSet0.textures, spvDescriptorSet0.texturesSmplr);
    return out;
}
```

As you can see I have adjusted textures array size to 1024 to show it hits performance. Much higher values result in shader not even beeing able to compile in reasonable time. This code results in 6 FPS on my mbp with AMD 5500M.

I'm not metal shader language expert, but I think `getTextureValue(...)` signature should have had `texturesSmplr` argument type `device const array<texture2d<float>, 1024>& texturesSmplr`.

Original shader with sampling done directly in `main()` runs with 60 FPS (VSync enabled):
```glsl
void main() 
{
	outFragColor = texture(textures[nonuniformEXT(inTexIndex)], inUV);
}
```

and corresponding Metal shader `main()`:
```metal
fragment main0_out main0(main0_in in [[stage_in]], constant spvDescriptorSetBuffer0& spvDescriptorSet0 [[buffer(0)]])
{
    main0_out out = {};
    int _19 = in.inTexIndex;
    out.outFragColor = spvDescriptorSet0.textures[_19].sample(spvDescriptorSet0.texturesSmplr[_19], in.inUV);
    return out;
}
```

This version does not use thread address space for that big array.

## Repro Case With VulkanSamples 

I have created a fork of VulkanSamples repo with a big array size to demonstrate how slow it runs.
This PR contains shader changes that result in the code showed above: https://github.com/SaschaWillems/Vulkan/pull/922/files

## Repo Case With Apple Sample

Just to verify that my assumption about using device instead of thread address space helps, here is an example of bad and good versions written in Metal based on Apple's sample for argument buffers.
https://github.com/adevaykin/slowmetalargbuffer

Main branch contains the nonoptimal case - shader compilation takes ages:
https://github.com/adevaykin/slowmetalargbuffer/blob/main/Renderer/AAPLShaders.metal

This PR contains the fix:
https://github.com/adevaykin/slowmetalargbuffer/pull/1/files

Thank you and I hope this will help making the great MoltenVK even better :)

**Comment by cdavis5e** [comment]
In the bad-performing shader, a *copy* of the array is made. This is the source of the bad performance. If the array isn't being mutated, we probably shouldn't be passing it by value.

This is really, however, an issue with SPIRV-Cross. I encourage you to file this bug there.

**Comment by adevaykin** [comment]
Indeed spirv-cross alone already outputs the bad version. Thank you, I'll report it there.
