### ISSUE TITLE
MoltenVK standalone lib incorrectly reports VK_EXT_debug_utils as available

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#1511]
When linking to MoltenVK directly (not libvulkan), the results of the instance query `vkEnumerateInstanceExtensionProperties()` shows the `VK_EXT_debug_utils` instance extension as available.  I then include `VK_EXT_debug_utils` in `vkCreateInstance()` to enable the extension.  However, when I later attempt to define the following procvars I get null pointers in return:

```
	vkGetDeviceProcAddr( vkcontext.device, "vkQueueBeginDebugUtilsLabelEXT" )
	vkGetDeviceProcAddr( vkcontext.device, "vkQueueEndDebugUtilsLabelEXT" )
	vkGetDeviceProcAddr( vkcontext.device, "vkCmdBeginDebugUtilsLabelEXT" )
	vkGetDeviceProcAddr( vkcontext.device, "vkCmdEndDebugUtilsLabelEXT" )
	vkGetDeviceProcAddr( vkcontext.device, "vkCmdInsertDebugUtilsLabelEXT" )
```

However, if I link to libvulkan.dylib instead of MoltenVK.dylib, the above procvars are properly defined and are not null.

Perhaps MoltenVK should not be reporting `VK_EXT_debug_utils` as available when packaged as a standalone lib vs. being included as part of libvulkan.  Or is the functionality truly meant to be present, but not wired correctly when standalone?

**Comment by billhollings** [comment]
Since `VK_EXT_debug_utils` is an instance extension, MoltenVK returns those function pointers via the `vkGetInstanceProcAddr()` call.

**Comment by SRSaunders** [comment]
Using `vkGetInstanceProcAddr()` works perfectly - thank you very much.

It's interesting that libvulkan seems to cover over this difference and somehow allows `vkGetDeviceProcAddr()` to handle this case.  MoltenVK is more strict but correct.  Strange, but live and learn...

**Comment by billhollings** [comment]
Thanks for the feedback. Closing this now.
