### ISSUE TITLE
vkCreateSampler() returns VK_SUCCESS even when exceeding VkPhysicalDeviceLimits::maxSamplerAllocationCount

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#1512]
The application I am working on (RBDOOM-3-BFG) creates thousands (>6000) of image samplers bound to descriptor sets of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER.  When using libvulkan.dylib with validation layers enabled, I receive thousands of validation errors because the game exceeds the maxSamplerAllocationCount of my device (for my AMD Radeon 580 the limit is 2048).  Specifically, an example validation error is:

`[Vulkan] ERROR: [ Validation ] Code 0 : 'Validation Error: [ VUID-vkCreateSampler-maxSamplerAllocationCount-04110 ] Object 0: handle = 0x10b88f818, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xb408bc0b | vkCreateSampler(): Number of currently valid sampler objects (4665) is not less than the maximum allowed (2048). The Vulkan spec states: There must be less than VkPhysicalDeviceLimits::maxSamplerAllocationCount VkSampler objects currently created on the device (https://vulkan.lunarg.com/doc/view/1.2.198.1/mac/1.2-extensions/vkspec.html#VUID-vkCreateSampler-maxSamplerAllocationCount-04110)'`

In spite of this the game seems to function correctly so this is more of a question at this point:  Why does `vkCreateSampler()` return `VK_SUCCESS` under these conditions, and what is the actual behaviour of MoltenVK once the allocated sampler count exceeds the device limit?  Are new samplers still created?   Are pre-existing samplers still valid?  I am not sure how to interpret the validation error and if I need to take action in the code to mitigate this.

**Comment by billhollings** [comment]
The simple answer is that you are in "undefined behavior" territory here.

MoltenVK does not explicitly count the number of allocated samplers and then take a particular action when that count is exceeded. The actual results will depend on the underlying GPU and driver resource behavior.

For its part, Metal does not specifically limit sampler creation outside of argument buffers, but does have a limit for samplers created for use in argument buffers. For `VkPhysicalDeviceLimits::maxSamplerAllocationCount`, MoltenVK reports the limit value Metal returns for argument buffers. But if you are not using these in argument buffers, then you may be getting a free ride from Metal, until some unreported limit internal to Metal is encountered, and then undefined behavior will occur.

**Comment by SRSaunders** [comment]
Thanks @billhollings for your answer.  I am sorry for my delay in responding, but I have been trying to understand the implications over the past week.

First of all, I am using only the Vulkan API and not Metal directly.  Does the Metal argument buffer limitation place any direct restrictions on my use of MoltenVK's Vulkan API for sampler creation?  In other words, are there Vulkan API calls I should be using or avoiding to limit the number of samplers MoltenVK creates within Metal argument buffers?

Secondly,  I am not using the MVK configuration setting `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS`, which I believe is off by default with current MoltenVK builds.  If I leave it off, will MoltenVK not use Metal argument buffers and thus the sampler limitation implied by maxSamplerAllocationCount is moot and can be ignored?

Lastly, I am concerned about MoltenVK's apparent redefinition of the meaning of maxSamplerAllocationCount, which I don't think aligns with Windows or Linux that treat it as a global maximum.  For instance, for my AMD Radeon 580, Vulkan on Windows 10 allows a maximum of 1,048,576 samplers, while Vulkan on linux allows up to 65,536 samplers.  MoltenVK's reported maximum of 2048 samplers for the same hardware is several orders of magnitude smaller.  Is there a different limit that perhaps should be used to express the Metal argument buffer restriction?

Rightly or wrongly, I am just ignoring this limit until I understand it better. Hopefully answers to the above questions will help.  And when I am working with validation layers, I found a way to hide this specific validation error by setting the environment variable `VK_LAYER_MESSAGE_ID_FILTER` to the specific error message ID (0xb408bc0b).

**Comment by billhollings** [comment]
> If I leave it off, will MoltenVK not use Metal argument buffers and thus the sampler limitation implied by maxSamplerAllocationCount is moot and can be ignored?

Yes. Your assumption is correct.

> I am concerned about MoltenVK's apparent redefinition of the meaning of maxSamplerAllocationCount, which I don't think aligns with Windows or Linux that treat it as a global maximum.

This is a valid point. Unfortunately, Metal does not provide any information, via API or documentation, about whether there is any limit at all, or what it might be. Sometimes we just let such values be arbitrarily large (say `INT_MAX`). But in this case, since there was a corresponding argument-buffer-based limit that is specified, we aligned it (arbitrarily, and as you mention, probably incorrectly) to the only sampler limit number we do have.

**Comment by SRSaunders** [comment]
Thanks for your quick answer.  This is good news from the standpoint of sampler scalability in my case (i.e. Metal Argument buffers off).

If I may make a suggestion, perhaps MoltenVK's maxSamplerAllocationCount should be set to a large number when `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` (or the MVK config option `useMetalArgumentBuffers`) is set to VK_FALSE.  However, if either option is set to VK_TRUE, then perhaps you could use the current approach of setting maxSamplerAllocationCount to the Metal Argument Buffer limit.  This means the limit would change based on a config setting, but it would make more sense and be consistent with other Vulkan implementations.  Just my 2 cents.

Thanks again for your help and great work on this project.

**Comment by billhollings** [comment]
PR #1544 fixes this issue. 

The value of `maxSamplerAllocationCount` is now a very large, indeterminate number, which is how MoltenVK reports limits that are not well defined in Metal. Please retest and close this issue if the solution fixes the problem you were having.

As a Vulkan driver, per Vulkan requirements, MoltenVK performs minimal validation, so `vkCreateSampler()` continues to **_not_** validate the count of `VkSamplers` or report when `maxSamplerAllocationCount` is exceeded. That is the function of the Validation Layers.

**Comment by SRSaunders** [comment]
Thanks @billhollings for fixing this issue.  My test case requires the Vulkan SDK validation layers.  I will test and respond once this fix migrates into the next SDK release.

**Comment by SRSaunders** [comment]
Validated fixed as of Vulkan SDK 1.3.211.0 (containing MoltenVK 1.1.9).

Thanks @billhollings for solving this issue.  Much appreciated.
