### ISSUE TITLE
In the cube demo, --use-staging is needed for iossim because vkGetPhysicalDeviceFormatProperties returns wrong

### ISSUE THREAD

**Issue by MagicPoulp** [KhronosGroup/MoltenVK#1513]
In the cube demo of this repository, why do we pass --use-staging in main function's args, whilst it should be detected automatically whether or not the simulator supports props.linearTilingFeatures? It seems to be a quick fix in place hiding the underlying problem with vkGetPhysicalDeviceFormatProperties returning wrong.

This is the exception produced:
`"MTLValidateFeatureSupport:4818: failed assertion `Linear textures from shared buffers is not supported on this device'"`
vkGetPhysicalDeviceFormatProperties does not detect the lack of support.

```
in cube.c of the Demo
vkGetPhysicalDeviceFormatProperties(vulkanDSL->gpu, tex_format, &props);
for (i = 0; i < DEMO_TEXTURE_COUNT; i++) {
        VkResult U_ASSERT_ONLY err;

if (props.linearTilingFeatures & VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT) && !vulkanDSL->use_staging_buffer) {
            //NSLog(@"--> Linear tiling is supported");
            /* Device can texture using linear textures */
            demo_prepare_texture_image(vulkanDSL, tex_files[i], &vulkanDSL->textures[i], VK_IMAGE_TILING_LINEAR, VK_IMAGE_USAGE_SAMPLED_BIT,
                                       VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
            // Nothing in the pipeline needs to be complete to start, and don't allow fragment
            // shader to run until layout transition completes
            demo_set_image_layout(vulkanDSL, vulkanDSL->textures[i].image, VK_IMAGE_ASPECT_COLOR_BIT, VK_IMAGE_LAYOUT_PREINITIALIZED,
                                  vulkanDSL->textures[i].imageLayout, 0, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
                                  VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
            vulkanDSL->staging_texture.image = 0;
        }
```

definitions from the Vulkan specification. So the linear on is for the first if in the cube.c code
linearTilingFeatures is a bitmask of VkFormatFeatureFlagBits specifying features supported by images created with a tiling parameter of VK_IMAGE_TILING_LINEAR.

VK_IMAGE_USAGE_SAMPLED_BIT specifies that the image can be used to create a VkImageView suitable for occupying a VkDescriptorSet slot either of type VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE or VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, and be sampled by a shader.

```
VkFormatProperties is built as seen below

vulkan.mm
MVK_PUBLIC_VULKAN_SYMBOL void vkGetPhysicalDeviceFormatProperties(
    VkPhysicalDevice                            physicalDevice,
    VkFormat                                    format,
    VkFormatProperties*                         pFormatProperties) {
        
        MVKTraceVulkanCallStart();
	MVKPhysicalDevice* mvkPD = MVKPhysicalDevice::getMVKPhysicalDevice(physicalDevice);
	mvkPD->getFormatProperties(format, pFormatProperties);
	MVKTraceVulkanCallEnd();
}


MVKPixelFormats.mm
kMVKVkFormatFeatureFlagsTexRead     = (VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT |
[...]
then it is added in optimal
enableFormatFeatures(Read, Tex, mtlPixFmtCaps, vkProps.optimalTilingFeatures);
...
and then optimal is copied.

// Linear tiling is not available to depth/stencil or compressed formats.
        // GBGR and BGRG formats also do not support linear tiling in Metal.
        if ( !(vkDesc.formatType == kMVKFormatDepthStencil || vkDesc.formatType == kMVKFormatCompressed ||
                   (chromaSubsamplingPlaneCount == 1 && vkDesc.blockTexelSize.width > 1)) ) {
                // Start with optimal tiling features, and modify.
                vkProps.linearTilingFeatures = vkProps.optimalTilingFeatures;

                // Linear tiling can support atomic writing for some formats, even though optimal tiling does not.
                enableFormatFeatures(Atomic, Tex, mtlPixFmtCaps, vkProps.linearTilingFeatures);

#if !MVK_APPLE_SILICON
                // On macOS IMR GPUs, linear textures cannot be used as attachments, so disable those features.
                mvkDisableFlags(vkProps.linearTilingFeatures, (kMVKVkFormatFeatureFlagsTexColorAtt |
                                                                                                           kMVKVkFormatFeatureFlagsTexDSAtt |
                                                                                                           kMVKVkFormatFeatureFlagsTexBlend));
#endif
        }

```

So there is no test to check if the device does support.
I do have an APPLE_SILICON process M1 so the last if does not concern me. Or perhaps it is different in the simulator.

It seems like a gray area. Perhaps certain simulators support it and not others, without a clear way to query it with a function.

**Comment by billhollings** [comment]
> So there is no test to check if the device does support.

What do you propose we test?

The test for `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` seems like overkill, because sampling an image is not the same as mapping it to host memory. It's quite feasible to load a linear image on the GPU side (through transfer or compute, etc), and then sample it. Unless we argue that such a non-host-visible image should actually be considered optimal tiling, which I suppose could be reasonable.

What is needed is a host-visible linear image flag, but Vulkan doesn't really have specifically that in either `vkGetPhysicalDeviceFormatProperties()` or `vkGetPhysicalDeviceImageFormatProperties()`.

**Comment by MagicPoulp** [comment]
Thanks for your comments.

It seems to me that --use-staging should not be passed in arg. It should be auto-detected so that we do not crash in the simulator.

It seems to me that VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT is required if we do not want to use a separate staging buffer. The image is used via sampling in the fragment shader.

**Comment by billhollings** [comment]
> It should be auto-detected

As I ask above, what do you propose we test? If we remove `VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT` from linear image formats, it means linear images cannot be sampled. That feels like overkill to me. But we can discuss that further in the [new issue](https://github.com/KhronosGroup/MoltenVK/issues/1515).

With that in mind, I'm going to close this issue as covered by that broader issue.
