### ISSUE TITLE
Add support for VK_KHR_synchronization2

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1514]
Would it be possible to add support for this extension to mvk itself?

On windows i can choose to use the sdk layer if the driver doesn't support the extension. With mvk however this wont work for my app. There's two ways i can link mvk. Either statically as framework, or dynamically through the loader. In order to get access to layers on macos i need to link dynamically. I dont think i can do that because as i understand it [the runtime user guide](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md) mentions this will make it so that i can only use vkGetMoltenVKConfigurationMVK and vkSetMoltenVKConfigurationMVK.
My application requires access to the other functions as well. My application has some low level metal code in order to make vulkan<->opengl interop work.
The functions i need:
- vkGetPhysicalDeviceMetalFeaturesMVK
- vkGetMTLDeviceMVK
- vkSetMTLTextureMVK
- vkGetMTLTextureMVK
In the future i might also need vkGetIOSurfaceMVK if/when opengl is dropped and [Syphon](https://github.com/Syphon/Syphon-Framework) needs to be implemented with the low level io surfaces or metal directly.

Are there any alternatives i could use to get both sync2 support as well as access to the metal id's that are used under the hood?

**Comment by billhollings** [comment]
Thanks for this enhancement request.

We can certainly look to implement `VK_KHR_synchronization2`. It should be fairly straightforward, and implementable within the short term, although, as with existing synchronization, we may not be able to provide full Vulkan functionality.

--------------

> On windows i can choose to use the sdk layer if the driver doesn't support the extension

I'm confused about what is happening when you do this. How does the Vulkan layer environment implement `VK_KHR_synchronization2` if the underlying driver does not?

--------------

> `vkGetMoltenVKConfigurationMVK()` and `vkSetMoltenVKConfigurationMVK()`.

These should be currently useable even with the SDK, as long as `libMoltenVK.a/dylib` is linked, because the `VkInstance` parameter in these calls is actually ignored. In addition, you can use the equivalent environment variables during app launch and completely bypass using `vkGetMoltenVKConfigurationMVK()` and `vkSetMoltenVKConfigurationMVK()`

--------------

>`vkGetMTLDeviceMVK()`
>`vkSetMTLTextureMVK()`
>`vkGetMTLTextureMVK()`

Over the next few months, the intention is to move these functions to a proposed new `VK_EXT_metal_objects` extension, which will be an official Vulkan extension and supported by the SDK.

--------------

>`vkGetPhysicalDeviceMetalFeaturesMVK()`

This is specific to MoltenVK and will not be supported in any future Vulkan extensions. It's probably best to avoid using this function altogether.

**Comment by billhollings** [comment]
> shouldn't it also contain `vkGetMTLBufferMVK`, `vkUseIOSurfaceMVK` and `vkGetIOSurfaceMVK`?

Actually, it does. The proposed header is:

[vulkan_metal.h.zip](https://github.com/KhronosGroup/MoltenVK/files/7936096/vulkan_metal.h.zip)

Metal object gets will be performed through `VkGetMetal*InfoEXT` structures in the `pNext` chain in `vkGetMetalObjectsEXT()`, and sets will be performed through a `Vk*Create*EXT` structure in the `pNext` chain of a standard Vulkan `vkCreate*()` call.

**Comment by mbechard** [comment]
Adding my +1 for this. I'd like to start using this extension to simplify the sync code throughout my app. But I'll need it working in MoltenVK before I can make use of it.
Thanks

**Comment by devshgraphicsprogramming** [comment]
btw `synchronization2` will probably become a blocker for a lot of extensions such as video encode/decode and `raytracing_maintenance1`

its simply because they ran out of access and pipeline stage bits
```c

static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_SAMPLED_READ_BIT = 0x100000000ULL;
static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_SAMPLED_READ_BIT_KHR = 0x100000000ULL;
static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_STORAGE_READ_BIT = 0x200000000ULL;
static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_STORAGE_READ_BIT_KHR = 0x200000000ULL;
static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT = 0x400000000ULL;
static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT_KHR = 0x400000000ULL;
// Provided by VK_KHR_video_decode_queue
static const VkAccessFlagBits2 VK_ACCESS_2_VIDEO_DECODE_READ_BIT_KHR = 0x800000000ULL;
// Provided by VK_KHR_video_decode_queue
static const VkAccessFlagBits2 VK_ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR = 0x1000000000ULL;
#ifdef VK_ENABLE_BETA_EXTENSIONS
// Provided by VK_KHR_video_encode_queue
static const VkAccessFlagBits2 VK_ACCESS_2_VIDEO_ENCODE_READ_BIT_KHR = 0x2000000000ULL;
#endif
#ifdef VK_ENABLE_BETA_EXTENSIONS
// Provided by VK_KHR_video_encode_queue
static const VkAccessFlagBits2 VK_ACCESS_2_VIDEO_ENCODE_WRITE_BIT_KHR = 0x4000000000ULL;
#endif
// Provided by VK_KHR_synchronization2 with VK_EXT_transform_feedback
static const VkAccessFlagBits2 VK_ACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXT = 0x02000000ULL;
// Provided by VK_KHR_synchronization2 with VK_EXT_transform_feedback
static const VkAccessFlagBits2 VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT = 0x04000000ULL;
// Provided by VK_KHR_synchronization2 with VK_EXT_transform_feedback
static const VkAccessFlagBits2 VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT = 0x08000000ULL;
// Provided by VK_KHR_synchronization2 with VK_EXT_conditional_rendering
static const VkAccessFlagBits2 VK_ACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXT = 0x00100000ULL;
// Provided by VK_KHR_synchronization2 with VK_NV_device_generated_commands
static const VkAccessFlagBits2 VK_ACCESS_2_COMMAND_PREPROCESS_READ_BIT_NV = 0x00020000ULL;
// Provided by VK_KHR_synchronization2 with VK_NV_device_generated_commands
static const VkAccessFlagBits2 VK_ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_NV = 0x00040000ULL;
// Provided by VK_KHR_fragment_shading_rate with VK_KHR_synchronization2
static const VkAccessFlagBits2 VK_ACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR = 0x00800000ULL;
// Provided by VK_KHR_synchronization2 with VK_NV_shading_rate_image
static const VkAccessFlagBits2 VK_ACCESS_2_SHADING_RATE_IMAGE_READ_BIT_NV = 0x00800000ULL;
// Provided by VK_KHR_acceleration_structure with VK_KHR_synchronization2
static const VkAccessFlagBits2 VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR = 0x00200000ULL;
// Provided by VK_KHR_acceleration_structure with VK_KHR_synchronization2
static const VkAccessFlagBits2 VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR = 0x00400000ULL;
// Provided by VK_KHR_synchronization2 with VK_NV_ray_tracing
static const VkAccessFlagBits2 VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_NV = 0x00200000ULL;
// Provided by VK_KHR_synchronization2 with VK_NV_ray_tracing
static const VkAccessFlagBits2 VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_NV = 0x00400000ULL;
// Provided by VK_KHR_synchronization2 with VK_EXT_fragment_density_map
static const VkAccessFlagBits2 VK_ACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXT = 0x01000000ULL;
// Provided by VK_KHR_synchronization2 with VK_EXT_blend_operation_advanced
static const VkAccessFlagBits2 VK_ACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT = 0x00080000ULL;
// Provided by VK_EXT_descriptor_buffer
static const VkAccessFlagBits2 VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT = 0x20000000000ULL;
// Provided by VK_HUAWEI_invocation_mask
static const VkAccessFlagBits2 VK_ACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEI = 0x8000000000ULL;
// Provided by VK_KHR_ray_tracing_maintenance1 with VK_KHR_synchronization2 and VK_KHR_ray_tracing_pipeline
static const VkAccessFlagBits2 VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR = 0x10000000000ULL;
// Provided by VK_EXT_opacity_micromap
static const VkAccessFlagBits2 VK_ACCESS_2_MICROMAP_READ_BIT_EXT = 0x100000000000ULL;
// Provided by VK_EXT_opacity_micromap
static const VkAccessFlagBits2 VK_ACCESS_2_MICROMAP_WRITE_BIT_EXT = 0x200000000000ULL;
// Provided by VK_NV_optical_flow
static const VkAccessFlagBits2 VK_ACCESS_2_OPTICAL_FLOW_READ_BIT_NV = 0x40000000000ULL;
// Provided by VK_NV_optical_flow
static const VkAccessFlagBits2 VK_ACCESS_2_OPTICAL_FLOW_WRITE_BIT_NV = 0x80000000000ULL;
```

**Comment by richard-lunarg** [comment]
There is a layer in the Vulkan SDK that provides this extension. Would that be sufficient?

**Comment by cdavis5e** [comment]
> There is a layer in the Vulkan SDK that provides this extension. Would that be sufficient?

No, because the new extensions require the 64-bit flags that `VK_KHR_synchronization2` requires.

**Comment by mbechard** [comment]
Using the layer provided by the Vulkan SDK wouldn't work for me since I link directly with MoltenVK.dylib

**Comment by devshgraphicsprogramming** [comment]
> Using the layer provided by the Vulkan SDK wouldn't work for me since I link directly with MoltenVK.dylib

the layer doesn't implement the whole of `synchronization2` and its interactions anyway.

**Comment by billhollings** [comment]
I'm starting work on this now.

**Comment by billhollings** [comment]
PR #2021 implements `VK_KHR_synchronization2`.
