### ISSUE TITLE
Updated glslang is needed for building on macOS 12.3

### ISSUE THREAD

**Issue by mrpippy** [KhronosGroup/MoltenVK#1526]
`fetchDependencies` is failing on macOS 12.3 because `glslang`'s Python scripts use `#!/usr/bin/env python`, and `/usr/bin/python` is now gone.
I fixed the issue upstream (https://github.com/KhronosGroup/glslang/commit/25555a7f62cf10e301f110142eea49d20fac27f9), but the external needs to be updated. Not sure if you want to wait for a release version or not.

**Comment by billhollings** [comment]
Fixed in #1527, but untested on macOS 12.3. 

Please confirm `fetchDependencies --all` runs successfully on macOS 12.3 and close this issue if successful.

**Comment by mrpippy** [comment]
Thanks, fix is working for me on 12.3 beta 2
