### ISSUE TITLE
vkCmdPipelineBarrier no longer works

### ISSUE THREAD

**Issue by tellowkrinkle** [KhronosGroup/MoltenVK#1538]
Attempting to use `vkCmdPipelineBarrier` does not result in any barriers being issued to Metal

Broken by 18642002ce68fa3071885afbaf4fa42e6ea17ded

Specifically the change on `MVKDevice.mm:1450`, which makes it so `_metalFeatures.textureBarriers = true;` is only set on macOS 10.15 and lower

**Comment by billhollings** [comment]
Fixed in PR #1540. Please retest and close this issue if it fixes the problem you encountered.

**Comment by tellowkrinkle** [comment]
Can confirm it fixes the issue
