### ISSUE TITLE
Compilation error when trying to use a SSBO in a fragment shader

### ISSUE THREAD

**Issue by Ant01n3** [KhronosGroup/MoltenVK#155]
Hi,

First of all, thanks for this incredible tool that is MoltenVK allowing us to use Vulkan under MacOs.

I try to use a SSBO in my fragment shader with :

```
layout(std140, binding = 1) buffer src {
	vec4 AB[];	// A and B concentration.
};
```

But the generated spv fragment shader produces this error when used :

```
Shader module compilation failed (code 3):
program_source:37:59: error: reference argument to fragment function must be const
fragment main0_out main0(main0_in in [[stage_in]], device Src& src [[buffer(0)]], constant Parameters& v_26 [[buffer(1)]])
```

The buffer comes from a compute shader where the same declaration compiles well. In addition, I tested the code under Windows and the fragment shader compiles.

Am i misusing it ?

Thanks

**Comment by billhollings** [comment]
@Ant01n3 

Thanks.

Can you post this exact issue to the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues), please?

That's where it will get fixed.

**Comment by Ant01n3** [comment]
Thanks, it's done. Should I close the issue here ?

**Comment by billhollings** [comment]
No...we'll keep this open until the fix makes the round-trip back here.

**Comment by billhollings** [comment]
The [SPIRV-Cross fix](https://github.com/KhronosGroup/SPIRV-Cross/issues/580) has been pulled into MoltenVK now.

Please retest and close this issue.

**Comment by Ant01n3** [comment]
Thanks. The shader is used without error when creating the pipeline now. I still don't have the expected result, but it is probably due to a problem in my code now. What is strange is that it works well under Windows. But I do not thing this is due to the SPIRV code.

Thanks again.

**Comment by billhollings** [comment]
@Ant01n3 

If during your testing it turns out there is another issue within MoltenVK that is causing the problem to remain, please reopen this issue.

**Comment by Ant01n3** [comment]
Ok, It works perfectly finally. My SSBO only uses two floats. On macOS apparently the "std140" tag effectively aligns the buffer on vec2. On Windows it seems it aligns on vec4, wasting 2 floats (although I don't know how to determine this by advance yet). With the correct align, all works as expected. 

Thanks a lot !
