### ISSUE TITLE
Add support for VK_EXT_sample_locations extension

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1552]

**Comment by cdavis5e** [comment]
I've actually wanted to do this for a long time. It's something we need for `vkd3d` in order to support programmable sample positions in D3D12 apps. I've had this on the back burner, though, because of an apparent lack of demand.

**Comment by billhollings** [comment]
Starting work on this now.

**Comment by billhollings** [comment]
Implemented in #1566.
