### ISSUE TITLE
Buffer labels not set via vkSetDebugUtilsObjectNameEXT

### ISSUE THREAD

**Issue by adevaykin** [KhronosGroup/MoltenVK#1565]
Hello.

It seems that buffer objects don't get labels assigned. I set labels using `vkSetDebugUtilsObjectNameEXT()` and it works for images, atttachments and shaders, but not for buffer objects. Which means all buffers are unnamed in Metal captures in XCode.

The same application running on Windows captured with RenderDoc does have debug labels set for those buffers.

Thank you.

**Comment by billhollings** [comment]
It might depend on a couple of things, such as timing, and whether the device memory is dedicated.

Was the `VkDeviceMemory` (where the `MTLBuffer` actually lives) dedicated to the `VkBuffer` when it was created? That's required for the device memory's `MTLBuffer` to be named after a particular `VkBuffer`.

If it **_is_** dedicated, it might also be that you are calling `vkSetDebugUtilsObjectNameEXT()` before the `VkBuffer` is bound to the `VkDeviceMemory`.

**Comment by adevaykin** [comment]
Thank you @billhollings 
Device memory is not dedicated for specific VkBuffer indeed.
