### ISSUE TITLE
MVKCmdDraw::encode() applies vertex push constants regardless of bound pipeline state

### ISSUE THREAD

**Issue by bangnoise** [KhronosGroup/MoltenVK#1569]
If we call `vkCmdPushConstants()` for a bound pipeline, then subsequently bind another pipeline which doesn't use push constants, the push constants are being applied to the draw command for the second pipeline. Since 2a17f757e1 this unwanted binding replaces our intended binding at Metal's buffer index 0.

Possibly `MVKCommandEncoder::finalizeDrawState()` should take a `MVKGraphicsPipeline` argument, and `MVKGraphicsPipeline` could gain a function to query `_stageUsesPushConstants` for the current stage so `finalizeDrawState()` would only apply the `_vertexPushConstants.encode(stage);` line where applicable.

If this sounds appropriate, I can prepare a PR if that's helpful.

**Comment by nastys** [comment]
This is probably what's currently causing issues in RPCS3. The previous commit works perfectly fine, while 2a17f75 and later are unstable and some games freeze before booting, consistently.

**Comment by billhollings** [comment]
@bangnoise @nastys 

Thanks for reporting this (and @bangnoise thanks for the suggested fix).

PR #1573 should fix this. Please retest using that PR and let me know if it fixes the issue.

**Comment by nastys** [comment]
It looks like it's fixed, thank you 👍

**Comment by billhollings** [comment]
Thanks for reporting back. Closing this issue now.

**Comment by bangnoise** [comment]
Yes fixed, thanks.
