### ISSUE TITLE
Function prototype mismatch vkSetMoltenVKConfigurationMVK

### ISSUE THREAD

**Issue by smanhaeve** [KhronosGroup/MoltenVK#1577]
The type of the second argument to `vkSetMoltenVKConfigurationMVK` is missing a `const` qualifier in the function typedef.

Compare the following two lines:

https://github.com/KhronosGroup/MoltenVK/blob/1236d2f5350062327a2428f80dee615a2e67304f/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L996

https://github.com/KhronosGroup/MoltenVK/blob/1236d2f5350062327a2428f80dee615a2e67304f/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L1089-L1092

**Comment by billhollings** [comment]
Fixed in PR #1578.
