### ISSUE TITLE
Stencil-only attachments and MTLPixelFormatInvalid

### ISSUE THREAD

**Issue by adevaykin** [KhronosGroup/MoltenVK#1579]
Hello.

I cannot use Metal API Validation feature in XCode because for the stencil-only attachment I get API validation error that looks like this:
```
-[MTLDebugRenderCommandEncoder setRenderPipelineState:]:1580: failed assertion Set Render Pipeline State Validation
For depth attachment, the renderPipelineState pixelFormat must be MTLPixelFormatInvalid, as no texture is set.
```

For stencil-only attachments I use `vk::ImageLayout::eDepthReadOnlyStencilAttachmentOptimal` layout with `eD32SfloatS8Uint` or `eD24UnormS8Uint` image.
It would be very nice to get rid of this "false positive" validation error to be able to use API Validation.

Did I miss something in stencil-only setup maybe to make MoltenVK set depth format to Invalid for such attachments?

**Comment by asivitz** [comment]
I'm not the original reporter, but I am getting this error as well. In my case, I'm using dynamic rendering (vkCmdBeginRenderingKHR) and providing a color attachment but not a depth attachment.

Happy to report/collect other info if that helps.

Thanks

**Comment by adevaykin** [comment]
Still trying to reproduce it with a simple triangle from Vulkan samples with no success. Meanwhile Metal capture of the problematic pipeline where depth part of depth-stencil attachment is missing, but format is still ldefined:
![Screenshot 2023-03-21 at 15 17 40](https://user-images.githubusercontent.com/3807468/226636319-bf2e4d1d-f42e-4229-9e86-471a98c16e17.png)

versus usual complete depth-stencil attachment pipeline where both attachment parts and formats are present:
![Screenshot 2023-03-21 at 15 17 23](https://user-images.githubusercontent.com/3807468/226636433-3b2aee8f-dec1-4ceb-b8c8-e70a9516c45f.png)

**Comment by adevaykin** [comment]
Works now! You are my hero! Thank you!
P.S.: no Metal validation errors so far :P

**Comment by adevaykin** [comment]
On the other hand: there are validation errors about mixing depth and stencil store operations. Not sure if this is our bug or another MoltenVK issue. I'll investigate.

```-[MTLDebugRenderCommandEncoder endEncoding_private]:7084: failed assertion `End Encoding Validation
endEncoding called with store action for depth attachment still set to MTLStoreActionUnknown
MTLDebugRenderCommandEncoder: mixing MTLStoreActionUnknown and MTLStoreActionStore store actions for the depth and stencil render pass attachments is not allowed.```

**Comment by billhollings** [comment]
>  there are validation errors about mixing depth and stencil store operations

Odd. That didn't show up in testing here. Thanks for reporting it. I'll look into it.

**Comment by billhollings** [comment]
PR #1885 should fix this. Please retest with latest MoltenVK, and close this issue if it is fixed.

**Comment by adevaykin** [comment]
Latest version has no more issues with separate depth and stencil attachments. Thank you!
