### ISSUE TITLE
vkCmdTimestampQuery producing inconsistent results

### ISSUE THREAD

**Issue by amdfan045** [KhronosGroup/MoltenVK#1585]
I have the following sequence of Vulkan commands:

```
vkResetCommandBuffer // Preparing to record
vkCmdClearColorImage // Initial clear for the image

vkCmdWriteTimestamp // timestampStart

vkCmdBeginRenderPass // Beginning the render pass
// Set some state
vkCmdBindPipeline
vkCmdSetViewport
vkCmdSetScissor
vkCmdBindDescriptorSets
vkCmdBindVertexBuffers

vkCmdDraw // a big draw with lots of vertex/fragment processing

vkCmdEndRenderPass // Ending the render pass

vkCmdWriteTimestamp // timestampEnd
vkCmdCopyQueryPoolResults // Resolve both queries above

vkEndCommandBuffer // Closing recording
vkQueueSubmit // submitting the cmd buffer to queue for execution
```

At the end of this, I expect to call a `vkMapMemory` on the query pool memory and get the values of timestampStart and timestampEnd and get the time taken for the draw call.

But I keep getting inconsistent (and nearly 0 time values).
I am using the Metal M1 GPU with the performance state locked to max using the Instruments profiler. I can see the time taken is consistent in the profiler capture, yet the timestamp queries return wrong results.

On reading more within the MoltenVK code, I see that the timestamp queries are being put as per-stage Metal queries on dummy blit calls inserted automatically by MoltenVK ICD. However, I see that Apple M1 GPU seems to be overlapping the blit calls with render encoder calls and hence ends up calling both timestampStart and timestampEnd nearly back-to-back. Hence, we end up with the query results not capturing the intended duration.

Here is what the driver processing thread sequence sees (which is correct):
![Screenshot 2022-05-02 at 5 29 08 PM](https://user-images.githubusercontent.com/104767862/166628465-ee96626d-baf0-4402-b4b8-216661ad3126.png)

But here is what the GPU workload captured for this shows (which is wrong):
![a](https://user-images.githubusercontent.com/104767862/166232117-58ad754e-98d7-4d64-a182-55cccef2621a.png)

Can we fix this and help get accurate query functionality on M1 GPUs?

**Comment by billhollings** [comment]
Interesting...and odd. Thanks for the research.

There exists a `MTLFence` between the `MTLRenderEncoder` and the dummy `MTLBLITEncoder`. It is updated by the fragment stage of the rendering. But for some reason the BLIT encoder is not waiting for that fence to be updated, or the fence is being updated too early.

I believe what's happening is that the `MTLRenderEncoder` is unaware of the upcoming `vkCmdWriteTimestamp`  for `timestampEnd` because it is outside the renderpass, and as a result does not update the fence.

What happens if you move the `vkCmdWriteTimestamp`  for `timestampEnd` before the `vkCmdEndRenderPass`? If this fixes it, we'll have to find a way to (efficiently) update the fence if we expect a `vkCmdWriteTimestamp` will follow the renderpass.

Also, can you confirm that your `vkCmdDraw()` is definitely running a fragment stage?

**Comment by amdfan045** [comment]
> What happens if you move the vkCmdWriteTimestamp for timestampEnd before the vkCmdEndRenderPass? If this fixes it, we'll have to find a way to (efficiently) update the fence if we expect a vkCmdWriteTimestamp will follow the renderpass.
Wow - that works! : i.e. if timestampStart stays where it is above, and timestampEnd is inserted before vkCmdEndRenderPass, we see correct timestamps.
Another observation is : if I move the timestampStart also inside the renderpass (after vkCmdStartRenderPass), both timestamps are updated in Metal after the renderpass's draw - and again get wrong results.
So the only combination which works right now is : put timestampStart before beginning the render pass, and timestampEnd before ending the render pass.

> Also, can you confirm that your vkCmdDraw() is definitely running a fragment stage?
Yes - the draw has a fragment stage (didn't show up in the figure above as I zoomed in to focus on timestamp queries)

**Comment by billhollings** [comment]
> Wow - that works! : i.e. if timestampStart stays where it is above, and timestampEnd is inserted before vkCmdEndRenderPass, we see correct timestamps.

Thanks for testing and confirming. With that understood, as I mentioned, we'll have to explore how to update the fence at the end of the renderpass, for any timestamps appearing after the renderpass.

> if I move the timestampStart also inside the renderpass (after vkCmdStartRenderPass), both timestamps are updated in Metal after the renderpass's draw - and again get wrong results.

Yes...that would be expected. Apple SoC timestamps are generated at the end of the current encoding pass. All timestamps in the renderpass will have the same timestamp. IM GPU's are different and support the kind of per-draw timestamping that Vulkan defines.

**Comment by billhollings** [comment]
@amdfan045  PR #1590 should fix this. Can you retest with the updated version of MoltenVK, and close this issue if it fixes the situation you encountered.

**Comment by amdfan045** [comment]
Retested with the updated version of MoltenVK - it fixes the situation fully!
Thank you very much for the quick investigation and fix.
Closing.
