### ISSUE TITLE
Cube example doesn't update contentsScale for different monitor scales

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#1591]
If you have a hiDPI (contentsScale=2) and regular monitor (contentsScale=1) connected to your computer, when dragging the window between the monitors the contentsScale isn't updated, so the swap chain isn't the optimal resolution for the current display the window is on.
Interestingly, even if the window is originally opened on the regular monitor, the first call to makeBackingLayer gets a viewScale == 2 from the View. I'm not sure if that behaviour is dependable, so if somehow the View returned a scale == 1 on first open, then dragging the window onto the scale==2 monitor could result in a very ugly output.

**Comment by billhollings** [comment]
PR #1668 fixes this. Please retest and close this issue if it fixes the problem you encountered. 

The contents scale is now logged for easy verification.
