### ISSUE TITLE
Crash when calling `vkDestroyDevice` after creating device with 1 queue from every available queue family

### ISSUE THREAD

**Issue by Valakor** [KhronosGroup/MoltenVK#1598]
I've started using `vk-bootstrap` in my little Vulkan framework to reduce boilerplate setup code. By default `vk-bootstrap` will specify that it wants 1 queue from every available queue family; however, my application later crashes upon calling `vkDestroyDevice` if I use this default behavior. If I instead specify that I just want a single queue from queue family 0 then I get no crash.

Some very cursory testing shows that creating 2 queues (1 queue from 2 different families) works fine, but creating 3 or more crashes.

The following is the callstack I get when things crash (I'm currently using Vulkan 1.3.211.0 with the bundled MoltenVK libraries):
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000019bb224d0 in objc_retain ()
#1	0x00000001027a5140 in ___lldb_unnamed_symbol1236$$libMTLCapture.dylib ()
#2	0x00000001027a5384 in ___lldb_unnamed_symbol1238$$libMTLCapture.dylib ()
#3	0x00000001027d37d0 in ___lldb_unnamed_symbol1878$$libMTLCapture.dylib ()
#4	0x0000000115baa82c in MVKGPUCaptureScope::~MVKGPUCaptureScope() ()
#5	0x0000000115b8ee40 in MVKQueue::~MVKQueue() ()
#6	0x0000000115b8eef8 in MVKQueue::~MVKQueue() ()
#7	0x0000000115b72984 in MVKDevice::~MVKDevice() ()
#8	0x0000000115b72c74 in MVKDevice::~MVKDevice() ()
#9	0x0000000115b05328 in vkDestroyDevice ()
#10	0x0000000120024938 in vulkan_layer_chassis::DestroyDevice(VkDevice_T*, VkAllocationCallbacks const*) ()
#11	0x0000000114d24278 in loader_layer_destroy_device ()
#12	0x0000000114d2bc60 in vkDestroyDevice ()
#13	0x00000001022935f8 in vkb::destroy_device(vkb::Device)
```

**Comment by julianrex** [comment]
FWIW we've also been seeing this call stack, and traced it to these lines:

https://github.com/KhronosGroup/MoltenVK/blob/a909822b6989ea438ec347af3c8f13884d4bd0e9/MoltenVK/MoltenVK/OS/MVKGPUCapture.mm#L68-L75

If these are commented out, I no longer see a crash. Looking at memory graphs & retain counts all seems to be well - which makes me wonder if the referenced bug has been fixed.

This was with Xcode 13.4.1 running on iPadOS 15.4.1.

As an aside it would also be nice to nil out `[MTLCaptureManager sharedCaptureManager].defaultCaptureScope`.

**Comment by MennoVink** [comment]
@billhollings Is this crash planned to be solved next release?
@Valakor mentioned this might be fixed by https://github.com/KhronosGroup/MoltenVK/pull/1632. I am unable to confirm this as Im probably doing something wrong involving the fetchDependencies script. i didn't manage to build the repo from source anymore after that pr got merged.

**Comment by Valakor** [comment]
Unfortunately I don't remember what version of MacOS or Vulkan I was on at the time of reporting (kicking myself for that now). I'm fairly certain I was on MacOS 12.4 and Vulkan SDK 1.3.211.0.

Further, I can't seem to reproduce the issue with my current setup for some reason.
- MacOS 12.4 on a MacBook Pro w/ M1
- Vulkan 1.3.216.0

I'll try downgrading my Vulkan SDK to see if I can reproduce the issue.

**Comment by Valakor** [comment]
Update: No luck reproducing with a downgraded SDK. It's possible I was still on 12.3, but I wonder if maybe there was some patch to 12.4 that I've taken since I was running into this that fixed the issue...? I'm not really familiar with Apple's patching process.

**Comment by MennoVink** [comment]
I had this same issue on macOS 12.4 using sdk 1.3.216.0 (on mbp 2015). I dont know how to figure out if apple's patch is present on 12.4 but if i make the change proposed in this pr then i can shut down without crashing in vkDestroyDevice again.
