### ISSUE TITLE
vkGetPhysicalDeviceImageFormatProperties returns "Success" for ETC2 formats when they are not supported

### ISSUE THREAD

**Issue by mellinoe** [KhronosGroup/MoltenVK#160]
To decide between BC3 and ETC2 textures for one of my projects, I first check if ETC2 is supported. I do this by calling vkGetPhysicalDeviceImageFormatProperties. On MoltenVK, this returns "Success", and fills in the structure with regular info (e.g. maxExtent=16384x16384x1). Notably, the VkPhysicalDeviceFeatures for this physical device has "false" for "textureCompressionETC2" -- so on some level it's known to be unsupported.

For completeness, I'm passing this to vkGetPhysicalDeviceImageFormatProperties:

format: VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK
type: VK_IMAGE_TYPE_2D
tiling: VK_IMAGE_TILING_OPTIMAL
usage: VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SAMPLED_BIT
flags: 0

It looks like [the implementation](https://github.com/KhronosGroup/MoltenVK/blob/d5272484acc4c5c5a70d71ce45768bc29d704167/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L100) isn't doing any support checks, and will always return VK_SUCCESS.

**Comment by billhollings** [comment]
I'll fix this per the further discussion in PR #162.

**Comment by mellinoe** [comment]
I pulled the change down and ran a quick test. Everything looks correct to me now. Thanks for the quick fix!
