### ISSUE TITLE
Why is maxPerStageDescriptorSamplers = 16 so low?

### ISSUE THREAD

**Issue by rcoreilly** [KhronosGroup/MoltenVK#1610]
Most of the platforms that have this low of a constraint are mobile platforms:
https://vulkan.gpuinfo.org/listreports.php?limit=maxPerStageDescriptorSamplers&value=16&platform=all

(also 16 for related properties)

It seems surprising that the modern laptop GPU's on Mac hardware couldn't support more..

This puts strong constraints on code that is designed to run cross-platform without modification, in terms of the critical resource of number of textures in a descriptor set.

**Comment by cdavis5e** [comment]
That is because that report was run without argument buffer support turned on. This is the maximum that Metal supports passing directly to a shader function. With argument buffers, the limit is much higher.

**Comment by rcoreilly** [comment]
Looking at #1186 in reference to argument buffers - it looks like this is not yet pushed to master branch?

**Comment by billhollings** [comment]
> You would config it like this:
> ...
>         mvkConfig.useMetalArgumentBuffers = VK_TRUE;
>...

It might also be easier to use the `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` environment variable. See the description of that in the documentation for [`MVKConfiguration::useMetalArgumentBuffers`](https://github.com/KhronosGroup/MoltenVK/blob/334e0cee69c60c13ac0355ca257da857e5c95aad/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L807-L829) (oops...just noticed that doc mistakenly says it's `enabled` by default, but it's actually `disabled` by default).

All MoltenVK config values have a corresponding environment variable that does exactly the same thing.

**Comment by billhollings** [comment]
Metal argument buffer support is intended to support `VK_EXT_descriptor_indexing`.

You might have to enable and use `VK_EXT_descriptor_indexing` to get the validation layer to look at `maxPerStageDescriptorUpdateAfterBindSamplers` instead of `maxPerStageDescriptorSamplers`.

If enabling `VK_EXT_descriptor_indexing` doesn't fix it...then we may need to modify `maxPerStageDescriptorSamplers` to take into consideration `VK_EXT_descriptor_indexing`. Vulkan is not clear about how the value of `maxPerStageDescriptorSamplers` is determined in the presence of `VK_EXT_descriptor_indexing`.

**Comment by pjako** [comment]
It seems to work now, I was missing the various UPDATE_AFTER_BIND flags you need to set.

**Comment by billhollings** [comment]
> Is this also supported for MoltenVK right now?

Yes. Tier2 is supported, where available, if you enable argument buffers via the `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` environment variable. See the documentation in the `mvk_config.h` file in MoltenVK.

**Comment by ashkann** [comment]
Hello. Running the latest SDK on a a Mac Book Pro (M1 MAX), the `maxPerStageDescriptorUpdateAfterBindSamplers` and *not* the other one (`maxPerStageDescriptorSamplers`) is still`16`.  This is preventing me from doing bindless. I'm not sure I'm understanding it all correctly but this should be much much higher than `16`, no ?

![image](https://github.com/KhronosGroup/MoltenVK/assets/1901570/665f338f-46ac-40ba-856e-247b8c751863)

**Comment by ashkann** [comment]
Since this issue was already closed and I think this is different, created a new issue https://github.com/KhronosGroup/MoltenVK/issues/2227
