### ISSUE TITLE
FFXIV macOS 13 developer beta new crash in same zone we previously fixed

### ISSUE THREAD

**Issue by ZoeyCluff** [KhronosGroup/MoltenVK#1614]
Hey Y'all:

I just installed macOS 13 today to test XIV on Mac as I usually do with betas. 

We usually have users enable "modern moltenVK" for crashes in a specific zone (Azys Lla) when you load into it. This used to be mostly required on AMD GPU's on macOS  however macOS 13 on my 14" Macbook Pro the zone now crashes with both our stable and modern versions.

I switched over to the the build we tested in #1592 and it's resolved, sitting in the zone while typing this.

I don't know if this is anything that needs to be fixed on your end or not (or is a symptom of a new problem with metal changes). Just putting it out there. 

I don't have all the games that @Gcenx usually tests on, but maybe they're affected too?

**Comment by Gcenx** [comment]
Can you retest using MoltenVK-v1.1.10

**Comment by ZoeyCluff** [comment]
![image](https://user-images.githubusercontent.com/2716914/172477957-38f38f76-ec8a-4b1a-aaa9-039074c13b51.png)
this one? Doesn't crash, both XOM's stable and modern version will crash guaranteed.

**Comment by Gcenx** [comment]
If stock MoltenVK-v1.1.10 works without issue that’s an XOM problem.

**Comment by ZoeyCluff** [comment]
This is new specifically with macOS 13. This version that is linked here was the one we used to fix this crash for everyone. I think it's possibly metal 3 related?
[Uploading modern.dylib.zip…]()

**Comment by Gcenx** [comment]
I think it’s unreasonable for Bill to fix prior releases to work on macOS 13 beta if the latest release doesn’t have any problems.
