### ISSUE TITLE
vkGetRefreshCycleDurationGOOGLE() doesn't work on multi-display.

### ISSUE THREAD

**Issue by kleinerm** [KhronosGroup/MoltenVK#1617]
@billhollings @spnda I finally got a moment to test merged PR #1596 on a dual-display setup, and it doesn't work on non-main displays, e.g., an external display connected to a MBP - It always falls back to querying the NSMainScreen, regardless of which screen the window is on.

At least not with my code that manually creates a CAMetalLayer and assigns it to the contentView of my NSWindow, ie., assigned via:

    [[window contentView] setWantsLayer:YES];
    [[window contentView] setLayer: [CAMetalLayer layer]];

I think this is called a layer hosting view?

I haven't tested this with MTKView or a self-made layer backed NSView, so maybe this is just a failure specific to above method, but above method is recommended in various places as one of the valid ways to do it. 

The while(layer.superlayer) - loop finds and selects a superlayer which does not match the view.layer of the windows contetnView, so no NSWindow is found -> No proper NSScreen is assigned and we always end with the NSMainScreen, which often is the wrong choice for a multi-display setup.

One simple solution is to remove that while loop and stick with _mtlLayer instead of layer. Iow, my original solution from my closed pull request #1358, with its associated limitations.

Another thing i tried, and which also worked for me, is the following replacement for the while(layer.superlayer) loop:

	while (![layer.delegate isKindOfClass: [PLATFORM_VIEW_CLASS class]] && layer.superlayer) {
		layer = layer.superlayer;
	}

    if ([layer.delegate isKindOfClass: [PLATFORM_VIEW_CLASS class]]) {
        NSView* view = (NSView*) layer.delegate;
        NSWindow* window = view.window;
        if (window) {
            screen = [window screen];
        }
    }

Iow. iterate upwards through the superlayers if needed, until a layer.delegate is found which is a NSView. Use that views associated NSWindow to get the screen.

This was inspired by the implementation of MVKSurface::initLayerObserver(), which uses the Metal layers delegate as a source of wisdom for the layer observer, assuming that delegate is an NSView or UIView. And some bits in Apple docs which suggests that if a view is created as a CAMetalLayer backed view, it will assign itself as the layers delegate.

Also I just realized that this is very similar to what @cdavis5e proposed in our original discussion at comment https://github.com/KhronosGroup/MoltenVK/pull/1358#discussion_r628809014

I don't know if the latter solution is better than simply going back to my original proposal, or something else, my understanding of all this layer stuff is very limited. Also, I'm out of time again for further testing or refining this. But adding this additional snippet would be a step into the right direction i guess, although short of attempting the more comprehensive solution attempt that @cdavis5e proposed in his comment.

**Comment by spnda** [comment]
I find it weird that the NSView backing a NSWindow can have a super layer... but so be it. Sorry about this though.

Your suggested solution that did work with manually setting the `CAMetalLayer` on the `NSWindow` would work in your case, but as previously discussed won't work with AppKit. So, I just thought of this other implementation, and while it really isn't the quickest (though most apps will only have a single NSWindow) it should actually be the best solution. This doesn't assume that the highest level view is in fact the window's `contentView` but will instead iterate as far as needed. Would you mind testing this snippet?
```objc
	CALayer* layer = _mtlLayer;
	NSScreen* screen = nil;
	NSApplication* app = [NSApplication sharedApplication];
	while (layer.superlayer) {
		layer = layer.superlayer;

		for (NSWindow* window in [app windows]) {
			NSView *view = [window contentView];
			if (view && ([view layer] == layer)) {
				screen = [window screen];
			}
		}
		
		if (screen != nil)
			break;
	}
```

**Comment by cdavis5e** [comment]
What if it's a subview of the content view?

**Comment by spnda** [comment]
Well that's why we do a loop checking each super layer? We go up the view tree until we arrive at the window's contentView. Or does this not work?

**Comment by cdavis5e** [comment]
> Well that's why we do a loop checking each super layer? We go up the view tree until we arrive at the window's contentView. Or what exactly do you mean?

What if the subview is a layer-hosting view, but the content view doesn't use layers at all? (Is that even possible?)

**Comment by spnda** [comment]
Still surprised that the currently implemented code doesn't work. How is the topmost layer not the layer assigned to NSWindow directly... To quote Apple's docs: 
> The window’s content view, the highest accessible view object in the window’s view hierarchy.

> What if the subview is a layer-hosting view, but the content view doesn't use layers at all? (Is that even possible?)

Do you know of any situation where this happens with normal Apple API? Though if you want to be really pedantic, you could also check all superviews in the NSView.

```objc
    NSScreen* screen = [NSScreen mainScreen];
    CALayer* layer = _mtlLayer;
    NSApplication* app = [NSApplication sharedApplication];
    while (layer.superlayer) {
        layer = layer.superlayer;

        for (NSWindow* window in [app windows]) {
            NSView *view = [window contentView];
            if (view == nil)
                continue;
            
            if ([view layer] == layer) {
                screen = [window screen];
                break;
            }
            
            // Use a C++ lambda instead?
            std::function<NSScreen*(NSView*)> checkSubviews = ^(NSView* subview) {
                for (NSView* kSubview in [subview subviews]) {
                    if ([kSubview layer] == layer) {
                        return [window screen];
                    } else {
                        checkSubviews(kSubview);
                    }
                }
                return (NSScreen*)nil;
            };
            screen = checkSubviews(view);
        }

        if (screen != nil)
            break;
    }
```
With many NSView's and NSWindow's this could get crazy expensive... but for most people this would work in pretty much all cases now. At this point, however, I ask myself why we don't ask the user for a NSWindow or the topmost NSView when creating the surface?

**Comment by kleinerm** [comment]
> > Well that's why we do a loop checking each super layer? We go up the view tree until we arrive at the window's contentView. Or what exactly do you mean?
> 
> What if the subview is a layer-hosting view, but the content view doesn't use layers at all? (Is that even possible?)

Fwiw: Docs for the NSView wantsLayer instance property say: "Setting the value of this property to YES turns the view into a layer-backed view—that is, the view uses a [CALayer](https://developer.apple.com/documentation/quartzcore/calayer?language=objc) object to manage its rendered content. Creating a layer-backed view implicitly causes the entire view hierarchy under that view to become layer-backed. Thus, the view and all of its subviews (including subviews of subviews) become layer-backed."

**Comment by billhollings** [comment]
PR #1669 should fix this across multiple display screens. Please test with latest.

That PR now uses both techniques...first attempting to retrieve the layer's `delegate` view, through which to retrieve the screen, and if this fails, attempts to retrieve the window the layer is on by iterating through the windows and then the layers of the window's `contentView`.

That second iterative approach is now modified to check first the `CAMetalLayer`, and each super layer against the `contentView` layer. It checks each level of the layer hierarchy, beginning at the bottom, because it appears that Apple can sometimes add synthetic super layers under the covers, even though the view remains attached to the lower-level view. So we need to accommodate both an app-created layer hierarchy within the view, and a synthetic CA-created layer hierarchy.

**Comment by kleinerm** [comment]
Just retested with a dual-display 60 Hz + 120 Hz setup and can confirm this works correctly with my setup, both when setting a suitable layer delegate, and with the slower fallback path. Tested on Catalina and Monterey.

Thanks.
