### ISSUE TITLE
Incorrect messageTypes value in pfnUserCallback when using VK_EXT_debug_utils

### ISSUE THREAD

**Issue by ayevtushenko** [KhronosGroup/MoltenVK#1622]
When using `VK_LAYER_KHRONOS_validation` extension for logging I often receive `VK_DEBUG_UTILS_MESSAGE_TYPE_FLAG_BITS_MAX_ENUM_EXT` in messageTypes argument.
I believe, this is incorrect, because if I use `string_VkDebugUtilsMessageTypeFlagsEXT()` function from `vk_enum_string_helper.h` it returns something like:
`VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT|VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT|Unhandled VkDebugUtilsMessageTypeFlagBitsEXT`

As I understand, the issue is in `debugUtilsMessage(messageSeverity, VK_DEBUG_UTILS_MESSAGE_TYPE_FLAG_BITS_MAX_ENUM_EXT, &dumcbd)` call that is in `MVKInstance::debugReportMessage()`.
Think, it should be `debugUtilsMessage(messageSeverity, VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT, &dumcbd)`

Please, let me know if I understand this correctly.

**Comment by billhollings** [comment]
The use of `VK_DEBUG_UTILS_MESSAGE_TYPE_FLAG_BITS_MAX_ENUM_EXT` was intended as a shorthand way of selecting all message type streams.

PR #1671 fixes this and selects more appropriate Vulkan debug message types based on the MoltenVK message reporting level. Please retest using the latest code, and close this issue if if fixes the problem you encountered.

**Comment by ayevtushenko** [comment]
@billhollings
I'll check it this week and let you know, thank you.

**Comment by ayevtushenko** [comment]
Everything works fine now, thanks!
