### ISSUE TITLE
GL_EXT_buffer_reference support?

### ISSUE THREAD

**Issue by Jackal-one** [KhronosGroup/MoltenVK#1623]
Hi, I am trying to use `GL_EXT_buffer_reference` extension in `MoltenVK` without luck so far. Is this feature supported? I can provide an example if required.

**Comment by billhollings** [comment]
`GL_EXT_buffer_reference` requires the Vulkan extension `VK_KHR_buffer_device_address`. That is under development, but is not available yet. It should be in place over the next few weeks.

**Comment by billhollings** [comment]
Implemented in PRs #1619 and #1638.
