### ISSUE TITLE
Problems on the Mac with Vulkan SDK 1.3.216.0

### ISSUE THREAD

**Issue by rainergericke** [KhronosGroup/MoltenVK#1626]
Hi!

I am working with Vulkan on the Mac (see attachments). Up to Vulkan SDK 1.3.211.0 there were no problems. Switching to Vulkan SDK 1.3.216.0 breaked all builds yet. The reason seems to be somewere inside instance creation. There are some nice example collections by Khronos (https://github.com/KhronosGroup/Vulkan-Samples.git) and by Sascha Willems (https://github.com/SaschaWillems/Vulkan.git). Both work with SDK 1.3.211.0 and earlier but not with SDK 1.3.216.0.

**In the actual Vulkan SDK Docs there is a proposal how to change the sources:
Opting in is simple. First add the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit to your VkInstanceCreateInfo structures .flags member, then add two instance extensions to your instance extensions list: VK_KHR_portability_enumeration, and VK_KHR_get_physical_device_properties2.

Typically the code to add support for intance extensions looks something like this:

std::vector<const char*>
extNames.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);

extNames.push_back(VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME);

VKInstanceCreateInfo inst_info = {};
ins_info.flags = VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR;
inst_info.enabledExtensionCount = static_cast<uint32_t>(extNames.size());
inst_info.ppEnabledExtensionNames = extNames.data();**

I modified two source files of Sascha Willems examples, but was not successful getting a working program.
By the way: on Windows 10 with VS2022 all examples run well with SDK 1.3.216.0!

[error1.txt](https://github.com/KhronosGroup/MoltenVK/files/8933252/error1.txt)
[vkvia.html.zip](https://github.com/KhronosGroup/MoltenVK/files/8933256/vkvia.html.zip)
[vulkanexamplebase.h.zip](https://github.com/KhronosGroup/MoltenVK/files/8933258/vulkanexamplebase.h.zip)
[vulkanexamplebase.cpp.zip](https://github.com/KhronosGroup/MoltenVK/files/8933259/vulkanexamplebase.cpp.zip)

Can you help me?

**Comment by JaryGuo** [comment]
I encountered this problem today, and I solved it by the following codes:

for the VkInstanceCreateInfo
```
extNames.push_back(VK_KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2_EXTENSION_NAME);
extNames.push_back(VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME);//VK_KHR_portability_enumeration
```

for the VkDeviceCreateInfo
```
extNamesForDevice.push_back(VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME);//VK_KHR_portability_subset
```

The solution was enlightened by the code from:
https://github.com/KhronosGroup/Vulkan-Tools/blob/master/cube/cube.c

**Comment by rainergericke** [comment]
You are right, @ragadan has found a solution like you proposed. @SaschWillems examples are working again. Thanks.
