### ISSUE TITLE
vkResetDescriptorPool is incredibly slow

### ISSUE THREAD

**Issue by tellowkrinkle** [KhronosGroup/MoltenVK#1628]
This comes up a lot in Dolphin, which likes to submit a lot of command buffers when it thinks it might need to wait on GPU completion, as well as during bbox emulation where there can be upwards of 20-30 spots where the CPU waits for GPU completion.

Here's a trace of LoZ Skyward Sword Skyloft (right in the beginning of the game), which runs at 75vps in Vulkan and 140vps in Metal due to about 63% of all GPU thread time being taken in `vkResetDescriptorPool`: [DolphinSkyloft.trace.zip](https://github.com/KhronosGroup/MoltenVK/files/8972523/DolphinSkyloft.trace.zip) (Something's breaking stack traces, but if you check `Invert call tree` all the MVK stuff will pop up on top)

bbox games also suffer from this.  Paper Mario TTYD has a scene near the beginning where a boat flipping around drops the frame rate to 15vps on Vulkan while staying around 60 in Metal, and it too has an extremely high percentage of GPU thread time taken by `vkResetDescriptorPool`.  Part of this one is just from the additional overhead of the Vulkan → Metal translation, as the root cause is 20-30 CPU-GPU synchronizations (command buffer submission + wait for completion), but the slow descriptor pool reset is not helping.

Sadly Dolphin's fifolog playback mechanism doesn't include readbacks, but if you happen to have a copy of Skyward Sword, you can reproduce the issue on the title screen as soon as you can see Skyloft in the background.  (Press and hold tab to fast forward, since Vulkan just barely manages to hold the game's 30fps but can't go any higher.)  For TTYD, you're looking for this scene:
<details>
<summary>Paper Mario TTYD Slow Scene</summary>

(You might need to disable dual core in the Dolphin settings to get here without crashing)

https://user-images.githubusercontent.com/3315070/175452397-49d3f2eb-5007-4071-b5d4-802e4cf50637.mp4
</details>

If you want to test the Metal renderer for comparison, [it's currently available in a PR](https://github.com/dolphin-emu/dolphin/pull/10754)

**Comment by italomandara** [comment]
Have you tried to fiddle with `MVK_ALLOW_METAL_FENCES` and `MVK_ALLOW_METAL_EVENTS` ?

**Comment by italomandara** [comment]
Hi i tested both metal and moltenvk renderers and metal is indeed almost 2x faster, couldn't test some flags that usually give me better performances on moltenvk, i run the dolphin binary from terminal with some env variables to see if it's a semaphores issue, but it doesn't seem to affect performances at all, is there a better way to do use env variables on dolphin??

**Comment by billhollings** [comment]
What version of MoltenVK are you using?

And what is the status of the `MVKConfiguration::preallocateDescriptors` flag, which is determined by the `MVK_CONFIG_PREALLOCATE_DESCRIPTORS` environment variable? This flag is enabled by default (since MoltenVK 1.1.3), but if it is disabled, it will slow down `vkResetDescriptorPool()`.

**Comment by tellowkrinkle** [comment]
MoltenVK 1.1.10
Looks like we take about the fastest path possible through `MVKDescriptorSet::free`:

<details>
<summary>Path through `MVKDescriptorSet::free`</summary>

```
libMoltenVK.dylib`MVKDescriptorSet::free:
->  0x1758d7bb0 <+0>:   push   rbp
->  0x1758d7bb1 <+1>:   mov    rbp, rsp
->  0x1758d7bb4 <+4>:   push   r15
->  0x1758d7bb6 <+6>:   push   r14
->  0x1758d7bb8 <+8>:   push   rbx
->  0x1758d7bb9 <+9>:   push   rax
->  0x1758d7bba <+10>:  mov    r15, rdi
->  0x1758d7bbd <+13>:  mov    qword ptr [rdi + 0x30], 0x0 ; _layout = nullptr;
->  0x1758d7bc5 <+21>:  mov    qword ptr [rdi + 0x70], 0x0 ; _dynamicOffsetDescriptorCount = 0; _variableDescriptorCount = 0;
->  0x1758d7bcd <+29>:  test   esi, esi
->  0x1758d7bcf <+31>:  je     0x1758d7bd9               ; <+41>
->  0x1758d7bd1 <+33>:  mov    qword ptr [r15 + 0x68], 0x0 ; _metalArgumentBufferOffset = 0;
->  0x1758d7bd9 <+41>:  mov    rdi, qword ptr [r15 + 0x28] ; _pool
->  0x1758d7bdd <+45>:  cmp    byte ptr [rdi + 0x440], 0x0 ; _pool->_hasPooledDescriptors
->  0x1758d7be4 <+52>:  je     0x1758d7beb               ; <+59>
->  0x1758d7be6 <+54>:  test   sil, sil
->  0x1758d7be9 <+57>:  jne    0x1758d7c2a               ; <+122>
    0x1758d7beb <+59>:  mov    r14, qword ptr [r15 + 0x40]
    0x1758d7bef <+63>:  test   r14, r14
    0x1758d7bf2 <+66>:  je     0x1758d7c2a               ; <+122>
    0x1758d7bf4 <+68>:  mov    rax, qword ptr [r15 + 0x38]
    0x1758d7bf8 <+72>:  mov    rsi, qword ptr [rax]
    0x1758d7bfb <+75>:  call   0x1758d7ca0               ; MVKDescriptorPool::freeDescriptor(MVKDescriptor*)
    0x1758d7c00 <+80>:  cmp    r14, 0x1
    0x1758d7c04 <+84>:  je     0x1758d7c2a               ; <+122>
    0x1758d7c06 <+86>:  mov    ebx, 0x1
    0x1758d7c0b <+91>:  nop    dword ptr [rax + rax]
    0x1758d7c10 <+96>:  mov    rdi, qword ptr [r15 + 0x28]
    0x1758d7c14 <+100>: mov    rax, qword ptr [r15 + 0x38]
    0x1758d7c18 <+104>: mov    rsi, qword ptr [rax + 8*rbx]
    0x1758d7c1c <+108>: call   0x1758d7ca0               ; MVKDescriptorPool::freeDescriptor(MVKDescriptor*)
    0x1758d7c21 <+113>: add    rbx, 0x1
    0x1758d7c25 <+117>: cmp    r14, rbx
    0x1758d7c28 <+120>: jne    0x1758d7c10               ; <+96>
->  0x1758d7c2a <+122>: mov    qword ptr [r15 + 0x40], 0x0 ; _descriptors.clear();
->  0x1758d7c32 <+130>: mov    rdi, qword ptr [r15 + 0x38] ; _descriptors.ptr
->  0x1758d7c36 <+134>: lea    rbx, [r15 + 0x48]           ; _descriptors.get_default_ptr()
->  0x1758d7c3a <+138>: cmp    rdi, rbx                    ; _descriptors.ptr == _descriptors.get_default_ptr()
->  0x1758d7c3d <+141>: je     0x1758d7c4d               ; <+157>
    0x1758d7c3f <+143>: test   rdi, rdi
    0x1758d7c42 <+146>: je     0x1758d7c49               ; <+153>
    0x1758d7c44 <+148>: call   0x175d1b4c0               ; symbol stub for: operator delete[](void*)
    0x1758d7c49 <+153>: mov    qword ptr [r15 + 0x38], rbx
->  0x1758d7c4d <+157>: mov    rdi, qword ptr [r15 + 0x50] ; _metalArgumentBufferDirtyDescriptors._data
->  0x1758d7c51 <+161>: mov    rax, qword ptr [r15 + 0x58] ; _metalArgumentBufferDirtyDescriptors._bitCount
->  0x1758d7c55 <+165>: mov    qword ptr [r15 + 0x58], 0x0 ; _metalArgumentBufferDirtyDescriptors._bitCount = 0;
->  0x1758d7c5d <+173>: add    rax, -0x1
->  0x1758d7c61 <+177>: jae    0x1758d7c6e               ; <+190>
    0x1758d7c63 <+179>: cmp    rax, 0x40
    0x1758d7c67 <+183>: jb     0x1758d7c6e               ; <+190>
    0x1758d7c69 <+185>: call   0x175d1b5e0               ; symbol stub for: free
->  0x1758d7c6e <+190>: mov    qword ptr [r15 + 0x50], 0x0 ; _metalArgumentBufferDirtyDescriptors._data = 0
->  0x1758d7c76 <+198>: mov    qword ptr [r15 + 0x60], 0x0 ; _metalArgumentBufferDirtyDescriptors._minUnclearedSectionIndex = 0
->  0x1758d7c7e <+206>: mov    dword ptr [r15 + 0xc], 0x0  ; _configurationResult = VK_SUCCESS;
->  0x1758d7c86 <+214>: add    rsp, 0x8
->  0x1758d7c8a <+218>: pop    rbx
->  0x1758d7c8b <+219>: pop    r14
->  0x1758d7c8d <+221>: pop    r15
->  0x1758d7c8f <+223>: pop    rbp
->  0x1758d7c90 <+224>: ret    
    0x1758d7c91 <+225>: nop    word ptr cs:[rax + rax]
    0x1758d7c9b <+235>: nop    dword ptr [rax + rax]
```
</details>

It looks like the main issue is that we're looping over all descriptor sets in `_descriptorSets`, regardless of whether or not they were used.  [Dolphin is very unsure of how many descriptor sets it'll need, and allocates space for 100000 in the pool](https://github.com/dolphin-emu/dolphin/blob/b02653722d88577b059b51c8bb76add081158f04/Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp#L105-L112), meaning that 100000 descriptor sets get scanned for every reset.

Ideally, some optimizations around pools without `VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT` would be nice, but I think most of the performance could be gotten just by tracking the highest used index and only scanning to that.

**Comment by billhollings** [comment]
>It looks like the main issue is that we're looping over all descriptor sets in _descriptorSets, regardless of whether or not they were used. [Dolphin is very unsure of how many descriptor sets it'll need, and allocates space for 100000 in the pool](https://github.com/dolphin-emu/dolphin/blob/b02653722d88577b059b51c8bb76add081158f04/Source/Core/VideoBackends/Vulkan/CommandBufferManager.cpp#L105-L112), meaning that 100000 descriptor sets get scanned for every reset.

Ah. Very helpful. Thanks for that additional info.

**Comment by billhollings** [comment]
PR #1676 should improve this. Please retest with latest MoltenVK and close this issue if performance is improved.

**Comment by tellowkrinkle** [comment]
Looks pretty fixed to me
