### ISSUE TITLE
Segfault when creating a pipeline with an empty shader module

### ISSUE THREAD

**Issue by danielkeller** [KhronosGroup/MoltenVK#1629]
If I create a compute pipeline using the spirv `0x07230203, 0x00010000, 0, 0, 0, 0x0003000e, 0, 1`, which is
```c
; Magic:     0x07230203 (SPIR-V)
; Version:   0x00010000 (Version: 1.0.0)
; Generator: 0x00000000
; Bound:     0
; Schema:    0
               OpMemoryModel Logical GLSL450
```
I get a segfault from MoltenVK, inside
```
MVK_spirv_cross::CompilerMSL::is_msl_resource_binding_used
mvk::SPIRVToMSLConverter::convert
```

**Comment by cdavis5e** [comment]
This is a bug in [SPIRV-Cross](/KhronosGroup/SPIRV-Cross/issues).

**Comment by billhollings** [comment]
Closing. As indicated, please post this issue to the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues).
