### ISSUE TITLE
vkQuake 1.20.0 shader does not compile

### ISSUE THREAD

**Issue by Novum** [KhronosGroup/MoltenVK#1630]
See issue here: https://github.com/Novum/vkQuake/issues/491

Compiler reports
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:106:16: error: use of undeclared identifier '_349'; did you mean '_363'?
        _363 = _349;
               ^~~~
               _363
program_source:45:12: note: '_363' declared here
    float4 _363;
           ^
```

The shader is validation error free and I believe correct.

**Comment by cdavis5e** [comment]
This is a [SPIRV-Cross](/KhronosGroup/SPIRV-Cross/issues) bug.

**Comment by Novum** [comment]
Thanks, I'll check if I can reproduce it with the standalone, that makes it easier!
