### ISSUE TITLE
Fix `shaderSharedCompositeVariables` CTS failures

### ISSUE THREAD

**Issue by cdavis5e** [KhronosGroup/MoltenVK#1655]
This is in support of a Khronos contract to reduce CTS failures in MoltenVK, leading up to certification as a Vulkan Portability implementation.

There are two apparent causes of these failures:
* [x] Erroneously (?) inserted casts from `bool` to `short`. These prevent the MSL compiler from compiling stores of `bool` values. We will fix these by ascertaining the cause of these casts, and fixing SPIRV-Cross not to emit them. I suspect, but am not certain, that this is related to work I did to pass `bool` types in subgroup operations.
* [x] The lack of a constructor for the `threadgroup` AS on matrices. This oversight on the part of Apple appears to be unintentional, since `threadgroup` AS overloads exist of all other matrix methods. Two possible workarounds have been identified:
  * Create a new type which is implicitly convertible to matrix type. I intend to pursue this avenue. Alternatively:
  * Use a `threadgroup` compute function parameter instead of a `threadgroup` global. This would require work on both SPIRV-Cross (to emit the `threadgroup` parameter) as well as MoltenVK (to populate it in the `MTLComputeCommandEncoder`).

53 CTS failures will be fixed by these changes.

@billhollings If the work to be done is on SPIRV-Cross, should these issues be filed there or here?

**Comment by billhollings** [comment]
> If the work to be done is on SPIRV-Cross, should these issues be filed there or here?

I think whichever is more useful. For fixes that are completely contained within SPIRV-Cross, I'm fine to see them identified and tracked there. The important part is to identify a chunk of work that is underway (to avoid duplication of effort), and have a mechanism to potentially discuss design options (if suitable). So, either venue is fine when it comes to SPIRV-Cross fixes.

BTW...both repos have a _**CTS**_ label, which we should use for these kind of work items. For instance, during earlier testing I created a short list of [SPRIV-Cross CTS issues](https://github.com/KhronosGroup/SPIRV-Cross/issues?q=is%3Aissue+is%3Aopen+label%3ACTS+). Modifying and adding to that where appropriate would be good.

**Comment by cdavis5e** [comment]
Fixes have been merged.

**Comment by billhollings** [comment]
Sweet! For the SDK release this coming weekend, I'll be pulling in latest SPIRV-Cross...so it'll make it in here then...so no need for a separate PR to bring it in here.
