### ISSUE TITLE
Issue (black screen) on Stray 64-bit on DirectX 11

### ISSUE THREAD

**Issue by zenodallavalle** [KhronosGroup/MoltenVK#1665]
I was trying to run Stray on my 14-inch Macbook Pro with M1-Pro. I'm using Crossover 21.2 (21.2.0.33926).
I tried in three different ways:

1. **With MoltenVK and DXVK backend included with Crossover [MVK:1.1.3 DXVK: ]**
2. **With MoltenVK included and DXVK backend 1.10.2**
3. **With MoltenVK 1.1.10 and DXVK backend 1.10.2**

I attach here log generated for every combination.
The result is always the same, although I noticed an increment in FPS switching from 1 to 2 and even more from 2 to 3.
I see only menu, black screen and some kind of shapes formed by green points.

If more log are needed please just tell me. I attach also screenshots taken in scenario number 3.
<img width="1512" alt="Schermata 2022-07-28 alle 18 37 54" src="https://user-images.githubusercontent.com/48842588/181593963-083f2040-31c9-49f5-878b-511808c802cc.png">
<img width="1512" alt="Schermata 2022-07-28 alle 18 37 51" src="https://user-images.githubusercontent.com/48842588/181593991-4a880810-ad5a-44d6-b5f3-2ee3d303199d.png">
[3.stray-log.mvk.1.1.10.dxvk.1.10.2.cxlog.zip](https://github.com/KhronosGroup/MoltenVK/files/9212715/3.stray-log.mvk.1.1.10.dxvk.1.10.2.cxlog.zip)
[2.stray-log.dxvk.1.10.2.cxlog.zip](https://github.com/KhronosGroup/MoltenVK/files/9212716/2.stray-log.dxvk.1.10.2.cxlog.zip)
[1.stray-log_default_crossover.cxlog.zip](https://github.com/KhronosGroup/MoltenVK/files/9212717/1.stray-log_default_crossover.cxlog.zip)

**Comment by italomandara** [comment]
Let me guess... UE4 game?

**Comment by zenodallavalle** [comment]
Yes. Should I close?

**Comment by italomandara** [comment]
> Yes. Should I close?

I'm just a user like you advocating for UE4 games support on MoltenVK. You can leave it, maybe it's something that's not what i think it is thus fixable... I checked the logs i can only see some unsupported format from vkd3d which is weird since you're using dxvk. You can leave it open.

**Comment by yogithesymbian** [comment]
did you solve ? i have same issue but with other games .
i have tried with put -dx10 on run option for the game but still no graphic appears , only text menu , audio and others.
