### ISSUE TITLE
Expose experimental Vulkan features using internal Metal API

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/MoltenVK#1670]
As noted by @cdavis5e in #1657, there's a few things in Metal which are not documented or exposed. These features could possibly be used to experiment supporting some Vulkan features that would not be supportable otherwise. The initial idea is to have a compile-time option which would enable these experimental features, as using these private APIs would not allow shipping an app with MoltenVK into the App Store and should therefore not be the default. This issue shall act as some sort of a tracker of potential features and their implementations by looking into the symbols and Objective-C metadata.

5 patches have already been written to support some features (although not entirely stable):
https://github.com/KhronosGroup/MoltenVK/issues/1657#issuecomment-1197438815

I have also just gone ahead and extracted the symbols of the `Metal` binary found in the `Metal.framework` shipped with the latest macOS 13 beta, meaning with support for Metal 3 and Metal IO. I couldn't get `class-dump` to not crash with this binary, so this is just the basic output of `nm`:
[metal_symbols.txt](https://github.com/KhronosGroup/MoltenVK/files/9224185/metal_symbols.txt)
[metalkit_symbols.txt](https://github.com/KhronosGroup/MoltenVK/files/9224704/metalkit_symbols.txt)

Some few things I've found in metal_symbols.txt:
- `-[MTLHeap _gpuAddress]`
- `MTLDeviceFeatureQueries` contains A LOT of interesting queries about GPU features, of which most are not exposed normally.
- Metal acceleration structures seem to be built using `MTLGPUBVHBuilder`, which seems to be more like something from MPS.
- `_MTLDevice` has a lot of other interesting queries about GPU capabilities.
- `_MTLPipelineCache` is a thing.
- `setLineWidth:` (as used by one of the patches linked above) is not listed anymore.
- `-[MTLRenderPipelineColorAttachmentDescriptor setLogicOpEnabled:]` is not listed anymore. However, `-[MTLRenderPipelineDescriptor setLogicOperation:]` is available.
- `-[MTLToolsRenderCommandEncoder useResourceGroup:usage:stages:]`... I wonder what resource groups are. (found in MetalTools)

**Comment by billhollings** [comment]
> `setLineWidth:` (as used by one of the patches linked above) is not listed anymore.

Nice sleuthing.

Interestingly, `-[_MTLDevice maxLineWidth]` _**is**_ still there.

Hmmm...unless it's moved to a different library that is accessible...this is the kind of thing where it can get really messy to try to support these kind of private-API calls...and frustrating for users if something arrives for a while and then gets taken away.

**Comment by tellowkrinkle** [comment]
Just a heads up: Just because the method is there, doesn't mean it works, or works well.

Some others I've found:
- Intel Skylake GPUs and up support framebuffer fetch, but the GPU locks up if you try to use both that and dual source blending at the same time
- `MTLRenderPipelineDescriptor` has things for logic ops, but I've only gotten it to work on Intel Skylake+ (AMD, Nvidia, and older Intel act like blending is disabled when you set those)
  <details>
  <summary>Test script and results from an AMD and Intel GPU</summary>

  ```objc
  #import <Foundation/Foundation.h>
  #import <Metal/Metal.h>
  
  typedef NS_ENUM(NSUInteger, MTLLogicOperation) {
  	MTLLogicOperationClear = 0,
  	MTLLogicOperationSet = 1,
  	MTLLogicOperationCopy = 2,
  	MTLLogicOperationCopyInverted = 3,
  	MTLLogicOperationNoOp = 4,
  	MTLLogicOperationInvert = 5,
  	MTLLogicOperationAnd = 6,
  	MTLLogicOperationNand = 7,
  	MTLLogicOperationOr = 8,
  	MTLLogicOperationNor = 9,
  	MTLLogicOperationXor = 10,
  	MTLLogicOperationEquiv = 11,
  	MTLLogicOperationAndReverse = 12,
  	MTLLogicOperationAndInverted = 13,
  	MTLLogicOperationOrReverse = 14,
  	MTLLogicOperationOrInverted = 15,
  };
  
  @interface MTLRenderPipelineDescriptor()
  - (void)setLogicOperationEnabled:(BOOL)enabled;
  - (BOOL)isLogicOperationEnabled;
  - (MTLLogicOperation)logicOperation;
  - (void)setLogicOperation:(MTLLogicOperation)operation;
  @end
  
  NSString* libstring = @""
  "#include <metal_stdlib>\n"
  "using namespace metal;\n"
  "\n"
  "vertex float4 fullscreen_triangle(uint vid [[vertex_id]]) {\n"
  "	return float4(vid & 1 ? 3 : -1, vid & 2 ? 3 : -1, 0, 1);\n"
  "}\n"
  "\n"
  "fragment float4 fs_base() {\n"
  "	return 0b1100 / 255.f;\n"
  "}\n"
  "fragment float4 fs_logic() {\n"
  "	return 0b1010 / 255.f;\n"
  "}\n";
  
  int main(int argc, const char * argv[]) {
  	@autoreleasepool {
  		for (id<MTLDevice> gpu in MTLCopyAllDevices()) {
  			id<MTLLibrary> lib = [gpu newLibraryWithSource:libstring options:nil error:nil];
  			printf("Testing %s\n", [[gpu name] UTF8String]);
  			MTLRenderPipelineDescriptor* desc = [MTLRenderPipelineDescriptor new];
  			[desc setVertexFunction:[lib newFunctionWithName:@"fullscreen_triangle"]];
  			[desc setFragmentFunction:[lib newFunctionWithName:@"fs_base"]];
  			[desc.colorAttachments[0] setPixelFormat:MTLPixelFormatRGBA8Unorm];
  			NSError* err = nil;
  			id<MTLRenderPipelineState> pipeBase = [gpu newRenderPipelineStateWithDescriptor:desc error:&err];
  			MTLTextureDescriptor* tdesc = [MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm width:16 height:1 mipmapped:NO];
  			[tdesc setUsage:MTLTextureUsageRenderTarget];
  			[tdesc setStorageMode:MTLStorageModePrivate];
  			id<MTLTexture> tex = [gpu newTextureWithDescriptor:tdesc];
  			id<MTLBuffer> buf = [gpu newBufferWithLength:4 options:MTLResourceStorageModeShared];
  			MTLRenderPassDescriptor* rpdesc = [MTLRenderPassDescriptor new];
  			id<MTLCommandQueue> q = [gpu newCommandQueue];
  			[desc setLogicOperationEnabled:YES];
  			[desc setFragmentFunction:[lib newFunctionWithName:@"fs_logic"]];
  			for (int i = 0; i < 16; i++) {
  				@autoreleasepool {
  					rpdesc.colorAttachments[0].texture = tex;
  					rpdesc.colorAttachments[0].loadAction = MTLLoadActionLoad;
  					rpdesc.colorAttachments[0].storeAction = MTLStoreActionStore;
  					[desc setLogicOperation:i];
  					id<MTLRenderPipelineState> pipeLogic = [gpu newRenderPipelineStateWithDescriptor:desc error:&err];
  					if (err) {
  						printf("Failed to make logic op pipe: %s\n", [[err localizedDescription] UTF8String]);
  					}
  					id<MTLCommandBuffer> cb = [q commandBuffer];
  					id<MTLRenderCommandEncoder> enc = [cb renderCommandEncoderWithDescriptor:rpdesc];
  					[enc setRenderPipelineState:pipeBase];
  					[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];
  					[enc setRenderPipelineState:pipeLogic];
  					[enc drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];
  					[enc endEncoding];
  					id<MTLBlitCommandEncoder> download = [cb blitCommandEncoder];
  					[download copyFromTexture:tex
  					              sourceSlice:0
  					              sourceLevel:0
  					             sourceOrigin:MTLOriginMake(0, 0, 0)
  					               sourceSize:MTLSizeMake(1, 1, 1)
  					                 toBuffer:buf
  					        destinationOffset:0
  					   destinationBytesPerRow:4
  					 destinationBytesPerImage:4];
  					[download endEncoding];
  					[cb commit];
  					[cb waitUntilCompleted];
  					unsigned int result = *(unsigned int*)[buf contents];
  					printf("1100(D) <op %2d> 1010(S) → %c%c%c%c\n", i, result & 8 ? '1' : '0', result & 4 ? '1' : '0', result & 2 ? '1' : '0', result & 1 ? '1' : '0');
  				}
  			}
  		}
  	}
  	return 0;
  }
  ```
  
  Results:
  ```
  Testing Intel(R) UHD Graphics 630
  1100(D) <op  0> 1010(S) → 0000
  1100(D) <op  1> 1010(S) → 1111
  1100(D) <op  2> 1010(S) → 1010
  1100(D) <op  3> 1010(S) → 0101
  1100(D) <op  4> 1010(S) → 1100
  1100(D) <op  5> 1010(S) → 0011
  1100(D) <op  6> 1010(S) → 1000
  1100(D) <op  7> 1010(S) → 0111
  1100(D) <op  8> 1010(S) → 1110
  1100(D) <op  9> 1010(S) → 0001
  1100(D) <op 10> 1010(S) → 0110
  1100(D) <op 11> 1010(S) → 1001
  1100(D) <op 12> 1010(S) → 0010
  1100(D) <op 13> 1010(S) → 0100
  1100(D) <op 14> 1010(S) → 1011
  1100(D) <op 15> 1010(S) → 1101
  Testing AMD Radeon Pro 5600M
  1100(D) <op  0> 1010(S) → 1010
  1100(D) <op  1> 1010(S) → 1010
  1100(D) <op  2> 1010(S) → 1010
  1100(D) <op  3> 1010(S) → 1010
  1100(D) <op  4> 1010(S) → 1010
  1100(D) <op  5> 1010(S) → 1010
  1100(D) <op  6> 1010(S) → 1010
  1100(D) <op  7> 1010(S) → 1010
  1100(D) <op  8> 1010(S) → 1010
  1100(D) <op  9> 1010(S) → 1010
  1100(D) <op 10> 1010(S) → 1010
  1100(D) <op 11> 1010(S) → 1010
  1100(D) <op 12> 1010(S) → 1010
  1100(D) <op 13> 1010(S) → 1010
  1100(D) <op 14> 1010(S) → 1010
  1100(D) <op 15> 1010(S) → 1010
  ```
  </details>

I'd expect `setLineWidth:` to continue to exist as long as OpenGL does, at least on Apple GPUs, since I'm pretty sure they use it internally for the OpenGL → Metal translation layer, which is used for OpenGL support on Apple.  I think it's not showing up there because protocols aren't emitted into binaries, and no classes implementing `MTLRenderCommandEncoder` are in `Metal.framework` (they're all in the individual drivers).

The stand-in command encoder used by the Metal frame capture API (e.g. if you run from Xcode) implements more methods than the underlying command encoder may, and will blindly forward them.  So just checking if the command encoder has a method isn't enough, you have to call it from a `@try {}` to check if it throws an exception (or detect capture and api validation encoders and get their underlying encoders).  (e.g. capture encoders have a `setPointSize:` in addition to the `setLineWidth:`, which seems to actually exist on Apple GPUs but nothing else)

If you really wanted to expose them in MoltenVK, you'd have to either individually whitelist/blacklist GPUs, or test each feature at runtime to ensure they actually work.

**Comment by jiseok419** [comment]
hello i'm korean server developer slave. yayyyyy

**Comment by billhollings** [comment]
PR #2137 fixes this for wide lines.
