### ISSUE TITLE
Vulkan SDK release feature cut-off Friday Aug 12

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1673]
LunarG is planning the next Vulkan SDK release.

A MoltenVK SDK release for this Vulkan SDK will be made Monday Aug 15.

MoltenVK PRs approved by Friday Aug 12 will be included in this release.

@cdavis5e @HansKristian-Work @richard-lunarg @KarenGhavam-lunarG

**Comment by KarenGhavam-lunarG** [comment]
The following branches are for the SDK and can be used for building MoltenVK for this SDK:

https://github.com/KhronosGroup/glslang/tree/sdk-1.3.224
https://github.com/KhronosGroup/Vulkan-Headers/tree/sdk-1.3.224
https://github.com/KhronosGroup/Vulkan-Tools/tree/sdk-1.3.224

**Comment by billhollings** [comment]
[MoltenVK v1.1.11](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.11) is released for SDK 1.3.124.
