### ISSUE TITLE
Add support for VK_KHR_shader_float_controls

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1684]
`VK_KHR_shader_float_controls` is required for Vulkan 1.2 support (see #1567).

Creating this issue to specifically discuss and track the development of this extension.

See also [this discussion](https://github.com/KhronosGroup/MoltenVK/issues/1209#issuecomment-768555357) in a previous issue.

I am currently working on this extension.

**Comment by spnda** [comment]
Hasn't this already been done with #1691?

**Comment by billhollings** [comment]
> Hasn't this already been done with #1691?

Yes. Thanks for catching the oversight in connecting and closing this.

Fixed in #1691. Closing now.
