### ISSUE TITLE
VK_KHR_dynamic_rendering in MacOS

### ISSUE THREAD

**Issue by SakuragiHnmch** [KhronosGroup/MoltenVK#1687]
When I run the dynamic rendering examples of [SaschaWillems](https://github.com/SaschaWillems) in macos, I encountered some problems. The program did not run as expected, and thrown some error message:

Enabled device extension "VK_KHR_dynamic_rendering" is not present at device level
Could not create Vulkan device:
ERROR_EXTENSION_NOT_PRESENT

I wondered if the dynamic rendering extension is supported by MoltenVK, and I failed to find any answer on the Internet.
Could this be the problem of the version of Monterey version or hardware support? My graphic card is AMD Radeon Pro 5500M 4 GB and OS version is 12.5

**Comment by SakuragiHnmch** [comment]
And I used the "vkEnumerateDeviceExtensionProperties" to list all the extensions available, dynamic rendering is not included:

available device extension: VK_KHR_16bit_storage
	available device extension: VK_KHR_8bit_storage
	available device extension: VK_KHR_bind_memory2
	available device extension: VK_KHR_create_renderpass2
	available device extension: VK_KHR_dedicated_allocation
	available device extension: VK_KHR_depth_stencil_resolve
	available device extension: VK_KHR_descriptor_update_template
	available device extension: VK_KHR_device_group
	available device extension: VK_KHR_driver_properties
	available device extension: VK_KHR_external_fence
	available device extension: VK_KHR_external_memory
	available device extension: VK_KHR_external_semaphore
	available device extension: VK_KHR_get_memory_requirements2
	available device extension: VK_KHR_imageless_framebuffer
	available device extension: VK_KHR_image_format_list
	available device extension: VK_KHR_maintenance1
	available device extension: VK_KHR_maintenance2
	available device extension: VK_KHR_maintenance3
	available device extension: VK_KHR_multiview
	available device extension: VK_KHR_portability_subset
	available device extension: VK_KHR_push_descriptor
	available device extension: VK_KHR_relaxed_block_layout
	available device extension: VK_KHR_sampler_mirror_clamp_to_edge
	available device extension: VK_KHR_sampler_ycbcr_conversion
	available device extension: VK_KHR_shader_draw_parameters
	available device extension: VK_KHR_shader_float16_int8
	available device extension: VK_KHR_shader_subgroup_extended_types
	available device extension: VK_KHR_storage_buffer_storage_class
	available device extension: VK_KHR_swapchain
	available device extension: VK_KHR_swapchain_mutable_format
	available device extension: VK_KHR_timeline_semaphore
	available device extension: VK_KHR_uniform_buffer_standard_layout
	available device extension: VK_KHR_variable_pointers
	available device extension: VK_EXT_debug_marker
	available device extension: VK_EXT_descriptor_indexing
	available device extension: VK_EXT_fragment_shader_interlock
	available device extension: VK_EXT_hdr_metadata
	available device extension: VK_EXT_host_query_reset
	available device extension: VK_EXT_image_robustness
	available device extension: VK_EXT_inline_uniform_block
	available device extension: VK_EXT_memory_budget
	available device extension: VK_EXT_private_data
	available device extension: VK_EXT_robustness2
	available device extension: VK_EXT_scalar_block_layout
	available device extension: VK_EXT_shader_stencil_export
	available device extension: VK_EXT_shader_viewport_index_layer
	available device extension: VK_EXT_subgroup_size_control
	available device extension: VK_EXT_texel_buffer_alignment
	available device extension: VK_EXT_vertex_attribute_divisor
	available device extension: VK_AMD_gpu_shader_half_float
	available device extension: VK_AMD_negative_viewport_height
	available device extension: VK_AMD_shader_trinary_minmax
	available device extension: VK_INTEL_shader_integer_functions2
	available device extension: VK_GOOGLE_display_timing
	available device extension: VK_NV_glsl_shader
Enabled device extension "VK_KHR_dynamic_rendering" is not present at device level
Could not create Vulkan device: 
ERROR_EXTENSION_NOT_PRESENT

**Comment by cdavis5e** [comment]
What version of MoltenVK are you using? The current version in Git [does in fact](https://github.com/KhronosGroup/MoltenVK/blob/d447ea79400f0250d5e16cb669be18406240d885/MoltenVK/MoltenVK/Layers/MVKExtensions.def#L55) [support this extension](https://github.com/KhronosGroup/MoltenVK/blob/d447ea79400f0250d5e16cb669be18406240d885/MoltenVK/MoltenVK/Vulkan/vulkan.mm#L2495).

**Comment by SakuragiHnmch** [comment]
Thanks for your reply!
I use the vulkan sdk version of 1.3.216.0, and the version of MoltenVK is 
334e0cee69c60c13ac0355ca257da857e5c95aad : https://github.com/KhronosGroup/MoltenVK.git
I checkout to that commit, and it does have supported the `VK_KHR_dynamic_rendering` extension, but I do not know why the listed extensions from `vkEnumerateDeviceExtensionProperties`  does not include it, and when I add the `VK_KHR_dynamic_rendering`  to the enabled_device_extesions arrray,  the device can not be created successfully.

**Comment by SakuragiHnmch** [comment]
I used the following code to print api version:
```
      uint32_t instanceVersion = VK_API_VERSION_1_0;
      vk::enumerateInstanceVersion(&instanceVersion);
      uint32_t major = VK_VERSION_MAJOR(instanceVersion);
      uint32_t minor = VK_VERSION_MINOR(instanceVersion);
      uint32_t patch = VK_VERSION_PATCH(instanceVersion);
      std::cout << "Vulkan Version:" << major << "." << minor << "." << patch << std::endl;
```
and it print:
`Vulkan Version:1.3.216`

I am sure that I am using the vulkan sdk of version 1.3.216.0

**Comment by SakuragiHnmch** [comment]
Emmm. maybe there was something wrong when the vulkan sdk is built.
So, can I get the current MoltenVK version through some vk api? 
The `VERSIONS.txt` in the package of 1.3.216 said the Revisions used to build this SDK of MoltenVK is 334e0cee69c60c13ac0355ca257da857e5c95aad

**Comment by SakuragiHnmch** [comment]
Sorry for disturbance, 
I have run the `vulkaninfo` in the package and it did print `VK_KHR_dynamic_rendering` in device extensions. So I uninstalled the vulkan sdk and reinstall it, but something wrong happened when creating the instance, `enumerateInstanceLayerProperties` returned zero count.
That is what I should check through first.
Again, thanks for your reply!

**Comment by billhollings** [comment]
Uggh. I forgot that the version of MoltenVK in the SDK disables MoltenVK logging by default.

When running your app, if you create and enable the environment variable `MVK_CONFIG_LOG_LEVEL=3`, you should see some log activity like this, which will tell you the MoltenVK version, and list the supported extensions:

```
[mvk-info] MoltenVK version 1.1.12, supporting Vulkan version 1.1.224.
	The following 82 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v35
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
```

**Comment by SakuragiHnmch** [comment]
Emm, as @billhollings said, this problem was caused by that the loader was actually loading the old version of sdk.
When I throughly cleaned up the all the sdks, and reinstall it, everything became normal.
Thanks all for your helps!
