### ISSUE TITLE
Vulkan Samples Conservative Rasterization shader doesn't compile

### ISSUE THREAD

**Issue by gpx1000** [KhronosGroup/MoltenVK#1688]
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:17:81: error: cannot reserve 'texture' resource locations at index 0
fragment main0_out main0(main0_in in [[stage_in]], array<texture2d<float>, 640> Textures [[texture(0)]], sampler ImmutableSampler [[sampler(0)]])

That's the reported error from this shader run.  NB: https://github.com/KhronosGroup/Vulkan-Samples/pull/497 fixes the instance creation bug to get this error to happen.
To run it:
vulkan_samples sample descriptor_indexing

**Comment by cdavis5e** [comment]
You need to turn on argument buffers. They actually aren't on by default. You can pass the environment variable `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1` to enable them for one run; and you can define that (use `GCC_PREPROCESSOR_DEFINITIONS='$(inherited) ...'` on the `xcodebuild` command line) when building to enable it by default. (I wonder if we should rig up `VK_EXT_descriptor_indexing` so that turning it on also turns on argument buffers...)

Setting that aside, I'm not sure how well a conservative rasterization sample will run on MoltenVK, since MoltenVK doesn't implement the `VK_EXT_conservative_rasterization` extension due to a lack of support in Metal. (Unless, of course, it doesn't actually *need* that extension...)

**Comment by gpx1000** [comment]
That makes sense, thanks Chip.

Having it auto turn on could be a challenge as the samples are all available in the current architecture and you select the sample you want via the command line.  We can add to the environment variables using CMake, which would be the most portable.  The only problem I can think of with that idea is it's only necessary for the one sample.  I guess we can solve that with documentation for the sample?  Seems not as clean as it could be.

I was kinda expecting that conservative rasterization would fail with the expected "not supported" error line as it bails out.  Other extensions will do similar.  

Okay, safe to close this bug, wanted to highlight it incase it was unknown.

**Comment by billhollings** [comment]
> I wonder if we should rig up VK_EXT_descriptor_indexing so that turning it on also turns on argument buffers...

Yeah. That sounds like a good idea, and makes sense. Added a separate issue #1689 to track that.

**Comment by SRSaunders** [comment]
In the mean time, you could call `setenv("MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS", "1", 1)` at runtime for the macOS platform (using an #ifdef block) within the specific example that needs Metal Argument buffers enabled (e.g. descriptor indexing).  I did this recently in Sascha Willems' Vulkan examples project (https://github.com/SaschaWillems/Vulkan) for his descriptor indexing sample.  This avoids doing something in CMake that would impact all examples, which I have found to be problematic (specifically Sascha's _computeraytracing_ and _specializationscontants_ examples currently do not like Metal Argument Buffers enabled).

FYI - the conservative rasterization example within Sascha Willems' repository does properly fail out with the runtime message: _Enabled device extension "VK_EXT_conservative_rasterization" is not present at device level_.  Not sure what is different about the Khronos Group example.

**Comment by gpx1000** [comment]
That's not a bad idea.  It might make sense to go through and do something similar for each sample that needs this.  I personally would prefer to keep the code in the samples as clean as possible and do what needs to be done in CMake to keep the intent of it being a learning resource.  Will have to think about solutions; although this isn't a bad one...
