### ISSUE TITLE
Is it feasible to support XQuartz windows?

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [KhronosGroup/MoltenVK#1694]
(I am coming from a point of no knowledge about Metal or the workings of XQuartz/Cocoa so forgive me if this is a nonsense question)

Given that XQuartz windows support some kind of GPU acceleration via. GLX - is it possible that MoltenVK could support creating surfaces from XQ windows? I think this would be rather useful as it basically entirely removes the need for ObjectiveC/++ code in portable projects and allows a lot more shared code between macOS and Linux (As well as leaving less work for those who want to roll their own windowing when writing rendering code with Vulkan ;3).

If this is a question of XQ exposing some kind of internal Quartz/Cocoa handle to MVK then IG it would probably require some kind of patched XQ or getting some sort of XQ-specific extension added for retrieving the handle.

From this then, comes the question of implementing the X WSI in MVK on top of/alongside the Cocoa one - which might be more hassle and technical weight than it's worth idk.

If anyone could shed some light as to the feasibility of this it'd be much appreciated! ^-^

**Comment by Gcenx** [comment]
You probably should first ask on https://github.com/XQuartz/XQuartz to see if Jeremy would Ben interested in adding Vulkan support via MoltenVK.

**Comment by billhollings** [comment]
> You probably should first ask on https://github.com/XQuartz/XQuartz to see if Jeremy would Ben interested in adding Vulkan support via MoltenVK.

Yes. This would be the approach. MoltenVK implements the Vulkan standard `vkCreateMetalSurfaceEXT()` call. So `XQuartz` can support Vulkan by using this call to provide the appropriate `CAMetalLayer` from within the `XQuartz` framework.

**Comment by Gcenx** [comment]
@billhollings upstream said no so guess you can close this.
