### ISSUE TITLE
Support MVK_ALLOW_METAL_EVENTS on NVIDIA and Rosetta2

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1695]
MoltenVK [disables](https://github.com/KhronosGroup/MoltenVK/blob/ea5a53d13c4ff7bad454ea44de9ca7e00113a3cd/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L4417) the use of `MTLEvents` for semaphores on NVIDIA and Rosetta2, since testing indicates that `MTLEvents` were problematic in this situation.

However, further testing indicates that this is not always the case, and we should create a runtime environment that permits `MTLEvents` to be used in these situations, if selected by the app.

Potentially override `MVK_ALLOW_METAL_EVENTS` and `MVK_ALLOW_METAL_FENCES` with an enum config that would allow options like "use MTLEvents always" and "prefer MTLEvents in most cases", as well as "prefer MTLFences", to allow taking into consideration the NVIDIA and Rosetta2 issues, but also allow them to be overridden by the app.

**Comment by tellowkrinkle** [comment]
BTW do we have a small, consistent reproduction of the MTLEvent lockup on Nvidia/Rosetta2?  Or is it just whole games at the moment?

**Comment by billhollings** [comment]
Merge PR #1709 permits this, providing the ability to use enumerated env var `MVK_CONFIG_VK_SEMAPHORE_SUPPORT_STYLE` to force `MTLEvents` to always be used, regardless of the GPU or platform, for apps that can safely run on those platforms.
