### ISSUE TITLE
Set proper VkPhysicalDeviceSubgroupSizeControlProperties::minSubgroupSize for AMD RX6600 device

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#1703]
A minor issue, but the `minSubgroupSize` should probably be set to 32 for the AMD RX6600 (DeviceId 0x73FF) which is supported by macOS as of Monterey.  As you state in the comments within `MVKDevice.mm`, this is unfortunately extracted manually from the Windows platform info in Sascha Willems' database and hardcoded in MoltenVK.  DeviceIds for other supported 5X00 and 6X00 cards are present in `MVKDevice.mm`, but the 6600 is missing.

See https://vulkan.gpuinfo.org/displayreport.php?id=15928#properties_core_13

**Comment by SRSaunders** [comment]
Probably too old and unimportant to worry about now.  Most machines going forward have Apple Silicon GPUs anyways.  Closing issue.

**Comment by cdavis5e** [comment]
I still have x86 hardware. As long as macOS continues to support x86 Macs, I think it's worth keeping this open.

**Comment by SRSaunders** [comment]
Ok that's fine.  Actually my main dev machine is x86, but I test on Apple Silicon as well.

I was looking at my open PRs and thought closing this one might help reduce the backlog, given that you and Bill probably have more important and pressing issues to focus on.

**Comment by billhollings** [comment]
This is easy enough to fix. Sorry for the long wait!

PR #2299 fixes this.

I'm curious though, do any AMD devices that Apple uses have any value other than 32 for this? We have the default for AMD at 64, but is that accurate? Should we just avoid the `switch()` and just set all AMD to 32?

**Comment by SRSaunders** [comment]
Thanks for fixing this old one.

> I'm curious though, do any AMD devices that Apple uses have any value other than 32 for this? We have the default for AMD at 64, but is that accurate? Should we just avoid the switch() and just set all AMD to 32?

I think your current logic is correct.  For instance, looking at the database the RX580 minSubgroupSize is 64.  Other older AMD GPUs (e.g. Vega) show only a subgroup size of 64.
