### ISSUE TITLE
`MVK_CONFIG_VK_SEMAPHORE_SUPPORT_STYLE_METAL_EVENTS_WHERE_SAFE` implementation doesn't match documentation

### ISSUE THREAD

**Issue by tellowkrinkle** [KhronosGroup/MoltenVK#1712]
Somehow missed this when looking over the PR, but while the documentation on `MVK_CONFIG_VK_SEMAPHORE_SUPPORT_STYLE_METAL_EVENTS_WHERE_SAFE` says "This will revert to same as MVK_CONFIG_VK_SEMAPHORE_USE_SINGLE_QUEUE on some NVIDIA GPUs and Rosetta2, due to potential challenges with MTLEvents on those platforms"
https://github.com/KhronosGroup/MoltenVK/blob/5bae97a4ae3cc7405f835167880f00f467c8ba52/MoltenVK/MoltenVK/API/vk_mvk_moltenvk.h#L110

The implementation uses `MVK_CONFIG_VK_SEMAPHORE_SUPPORT_STYLE_CALLBACK` (`MVKSemaphoreStyleUseEmulation`) where MTLEvent is potentially broken, instead of SINGLE_QUEUE
https://github.com/KhronosGroup/MoltenVK/blob/5bae97a4ae3cc7405f835167880f00f467c8ba52/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L3126-L3134

These should probably be adjusted to match each other, preferably matching the documentation (fallback is SINGLE_QUEUE)

**Comment by billhollings** [comment]
Thanks. Good catch.

> preferably matching the documentation (fallback is SINGLE_QUEUE)

While developing this I decided to change it to defaulting to Emulation (without apparently updating the corresponding documentation), on the assumption of preferring behavioral consistency over performance. 

In other words, when falling back, emulation will allow the multiple queues that some applications likely need. The app is then free to set the config accordingly on that platform if it wants to trade off using a single queue for added performance during the fallback.

**Comment by tellowkrinkle** [comment]
[Intel iGPUs only have a single queue](https://vulkan.gpuinfo.org/displayreport.php?id=16405#queuefamilies) so if an application doesn't support single queue, it'll break on every Intel iGPU.  Which I would hope isn't common.

BTW we might want to have separate options for the two fallbacks, since as it is right now, an application would have to figure out for itself whether it's on an Nvidia GPU or Rosetta to get the other fallback with the same "only for non-MTLEvent-supporting GPUs" behavior.

**Comment by billhollings** [comment]
PR #1738 fixes this. Closing now.
