### ISSUE TITLE
macOS 13 introduced CTS failures

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1725]
CTS testing on macOS 13 Beta 8 has introduced several thousand new CTS failures in the families of tests similar to these:

- `dEQP-VK.ssbo.phys.layout.single_basic_type.std140.lowp_float`
- `dEQP-VK.binding_model.buffer_device_address.set0.depth1.baseubo.load.nostore.single.std140.comp`

**Comment by rcaridade145** [comment]
Looking at the latest CTS run and bugs similar to those

`Test case 'dEQP-VK.binding_model.buffer_device_address.set0.depth1.baseubo.load.store.single.std140.comp'..
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:43:50: error: member reference type 'device _21 *' is a pointer; did you mean to use '->'?
    device _21* _84 = ((device _21*)_24._m2[0].x).x;`

That seems to be the issue that was fixed on https://github.com/KhronosGroup/SPIRV-Cross/pull/2043

**Comment by billhollings** [comment]
> > That seems to be the issue that was fixed on [KhronosGroup/SPIRV-Cross#2043](https://github.com/KhronosGroup/SPIRV-Cross/pull/2043)
> 
> Ah. Thanks for pointing that out. I'll follow up with some testing using that fix.

Unfortunately, https://github.com/KhronosGroup/SPIRV-Cross/pull/2043 doesn't address the pointer translation bug that is triggered by `dEQP-VK.binding_model.buffer_device_address.set0.depth1.baseubo.load.nostore.single.std140.comp`, which appears to be more complicated than that particular fix addressed. That will require some more assessment.

However, on the good news side, as shown in tracking issue #1664, the full macOS 13.0 release does seem to have resolved the additional unexpected CTS failures that were the primary reason for this issue (`dEQP-VK.binding_model.buffer_device_address.set0.depth1.baseubo.load.nostore.single.std140.comp` might have been included in the sample list above as a result of a copy-pasto by me), so I'm closing this issue now.
