### ISSUE TITLE
Add support for VK_KHR_copy_commands2 extension

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1734]
This extension provides extensible versions of the Vulkan buffer and image copy commands. The new commands are functionally identical to the core commands, except that their copy parameters are specified using extensible structures that can be used to pass extension-specific information.

**Comment by spnda** [comment]
Could you assign this to me? I'll get to this tomorrow.

**Comment by billhollings** [comment]
> Could you please assign this to me? I'll get to this tomorrow.

Thanks! I've assigned you. Were you not able to assign yourself in the top right above?

**Comment by spnda** [comment]
No, I can unassign myself but I can't assign anyone or change anything.
