### ISSUE TITLE
Support VK_EXT_extended_dynamic_state, VK_EXT_extended_dynamic_state2 & VK_EXT_extended_dynamic_state3

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1739]
Not all of the functionality of `VK_EXT_extended_dynamic_state`, `VK_EXT_extended_dynamic_state2` & `VK_EXT_extended_dynamic_state3` can be supported in Metal but the following dynamic state functionality can be supported:

`VK_EXT_extended_dynamic_state`:

- VK_DYNAMIC_STATE_CULL_MODE
- VK_DYNAMIC_STATE_FRONT_FACE
- VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY
- VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT
- VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT
- ~VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE~ _(unsupported)_
- VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE
- VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE
- VK_DYNAMIC_STATE_DEPTH_COMPARE_OP
- ~VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE~  _(unsupported but `VkPhysicalDeviceFeatures::depthBounds` disabled already)_
- VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE
- VK_DYNAMIC_STATE_STENCIL_OP

`VK_EXT_extended_dynamic_state2`:

- VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE
- ~VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE~ _(unsupported)_
- ~VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE~ _(unsupported)_
- ~VK_DYNAMIC_STATE_LOGIC_OP_EXT~  _(unsupported but can be disabled and `VkPhysicalDeviceFeatures::logicOp` disabled already)_
- VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT

`VK_EXT_extended_dynamic_state3` **_(each unsupported dynamic state can be individually disabled)_**:

- ~VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT~
- ~VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT~
- ~VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT~
- ~VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT~
- ~VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT~
- ~VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT~
- ~VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT~
- ~VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV~
- ~VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV~
- ~VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV~
- ~VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV~
- ~VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV~
- ~VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV~
- VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT
- VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT
- ~VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT~
- ~VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT~
- ~VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT~
- ~VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT~
- ~VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT~
- VK_DYNAMIC_STATE_POLYGON_MODE_EXT
- ~VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT~
- ~VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT~
- ~VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT~
- ~VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV~
- VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT
- ~VK_DYNAMIC_STATE_SAMPLE_MASK_EXT~
- ~VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV~
- ~VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT~
- ~VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV~
- ~VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV~

**Comment by spnda** [comment]
I created a branch to support EXT_dynamic_state a long time ago (https://github.com/spnda/MoltenVK/tree/KHR_extended_dynamic_state). However, there's a couple of things we can't support with Metal.

**Comment by oscarbg** [comment]
@spnda the depth stuff is optional? if yes, would be nice if a PR is done and eventually merged?

**Comment by spnda** [comment]
@oscarbg As I understand is none of it is optional. Unless you can quote the spec where it says what is optional and what isn't.

**Comment by spnda** [comment]
`VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE` can now be partially implemented with Metal 3.1:
https://developer.apple.com/documentation/metal/mtlrendercommandencoder/4126949-setvertexbuffer?changes=latest_minor&language=objc

However, the Vulkan functions still allow to change the vertex input rate (per vertex, per instance, ...) which Metal still doesn't allow.

**Comment by corporateshark** [comment]
Is there a way to partially enable some dynamic states from `VK_EXT_extended_dynamic_state` now? Maybe using `VK_KHR_portability_subset` etc...

**Comment by billhollings** [comment]
I'm starting working on this.

> I created a branch to support EXT_dynamic_state a long time ago (https://github.com/spnda/MoltenVK/tree/KHR_extended_dynamic_state). However, there's a couple of things we simply can't support with Metal, specifically the depth stuff I think.

@spnda Thanks. I've pulled your start in to save me some typing (and give you credit).

**Comment by reduz** [comment]
This feature would be super useful for Godot on MacOS / iOS, even without the depth buffer / input stride support.

**Comment by billhollings** [comment]
PR #2036 implements `VK_EXT_extended_dynamic_state` & `VK_EXT_extended_dynamic_state2`.

**Comment by billhollings** [comment]
PR #2036 implements `VK_EXT_extended_dynamic_state3`.
