### ISSUE TITLE
make sense to integrate general UE4 MacOS hack/fix via some enviroment variable?

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#1741]
Hi,

seeing https://www.youtube.com/watch?v=Yl86dLJjTW0 learned there is a hack/patch allowing lots more UE4 games to render more or less correctly on MacOS M1/M2 using DXVK+MoltenVK..
the patch is here:
https://github.com/nastys/MoltenVK/commit/be6488dede9f0f351cffc08d3d0a0dd488255817
what's new is the SPIRVToMSLConverter.cpp part of the patch.. there other parts enable DXVK+MoltenVK as before..
there is a prebuilt MoltenVK release listing the bug of many UE4 games more precisely:
https://github.com/nastys/MoltenVK/releases/tag/ue4-workaround-1

> This happens because, presumably due to a bug, the "CombineLUTs" step generates a 32x32x32 3D texture with all "layers" black except the first one, resulting in a black frame after post-processing.
> I have patched the shader to bypass the LUT for now.

would be nice if that part of the patch can be integrated in MoltenVK and enabled via some enviroment variable (like MVK_FIX_UE4_games?).. makes sense?

thanks..

**Comment by Gcenx** [comment]
Most of that commit is faking extensions to keep DXVK-CX happy

I’d ripped out the relevant changes to the following commit

https://github.com/The-Wineskin-Project/MoltenVK/commit/6f5dc572cc89b801d4bce9f420dab776aac255fb

**Comment by Gcenx** [comment]
I don’t believe these kind of hacks should become part of MoltenVK once the real issue has been tracked down this could probably be fixed correctly.

What _might_ be acceptable is playing private APIs behind an env/compile option.

**Comment by cdavis5e** [comment]
> > This happens because, presumably due to a bug, the "CombineLUTs" step generates a 32x32x32 3D texture with all "layers" black except the first one, resulting in a black frame after post-processing.
> > I have patched the shader to bypass the LUT for now.

And this, in turn, happens because MoltenVK doesn't yet support geometry shaders. UE4 uses geometry shaders for layered rendering, because D3D11 originally didn't let you set the `SV_RenderTargetArrayIndex` and `SV_ViewportArrayIndex` sysvals from vertex or tessellation shaders.

**Comment by Gcenx** [comment]
The above is _why_ I hate faking Vulkan extensions in MoltenVK to keep DXVK happy.

Allowing DXVK to avoid geometry shaders but provide a message when required helps show things like this.

**Comment by nastys** [comment]
If it is because of geometry shaders in post-processing (I haven't really had the time to look into it), I think it would make more sense to implement partial support for geometry shaders (using compute shaders, CPU callbacks or whatever) and lock it behind an environment variable.
My hack doesn't work for all games, probably because the recompiled shader is sometimes slightly different.

**Comment by italomandara** [comment]
> If it is because of geometry shaders in post-processing (I haven't really had the time to look into it), I think it would make more sense to implement partial support for geometry shaders (using compute shaders, CPU callbacks or whatever) and lock it behind an environment variable.
> My hack doesn't work for all games, probably because the recompiled shader is sometimes slightly different.

I guess you could even do full geometry shaders support with compute shaders, with little overhead. It's just a matter of someone's will to do it.

**Comment by Gcenx** [comment]
Something for everyone to keep in mind, Bill is the only person working on MoltenVK full-time.

Chips is working on fixing CT failures (Khronos contract)

**Comment by italomandara** [comment]
> Something for everyone to keep in mind, Bill is the only person working on MoltenVK full-time.
> 
> Chips is working on fixing CT failures (Khronos contract)

When I say someone I mean anyone that opens a pull request in the repo, like me or you or anyone else.

**Comment by billhollings** [comment]
> When I say someone I mean anyone that opens a pull request in the repo, like me or you or anyone else.

Issue #1524 is the request for geometry shaders. And @italomandara has made some suggested implementations there. Compute or mesh shaders are options for solutions. Let's continue discussion of geometry shaders in #1524.

**Comment by billhollings** [comment]
Closing as duplicate.
