### ISSUE TITLE
Support permanently open vkMapMemory() on coherent image memory

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#175]
Texture memory is not coherent on Metal. This means that when a texture is bound to a `VkDeviceMemory` that is coherent, it is not possible to leave `vkMapMemory()` open and have CPU updates to the memory automatically applied to that texture. In such cases, a `vkUnmapMemory()` call is needed to trigger the texture update...which MoltenVK detects and updates the texture.

Investigate whether coherent textures could be supported by:

- Limiting coherent images to only a linear layout where **_only_** transfer operations are permitted (as per Vulkan spec)
- Implement this simple linear texture using an underlying `MTLBuffer` instead of a `MTLTexture`
- Internally...use Metal copy-to-and-from-buffer instead of copy-to-and-from-texture for these coherent images.
- Limit the size of coherent images to the max size of a `MTLBuffer`...which is less than the max size of a `MTLTexture`.

**Comment by kikaxa** [comment]
Since this is a pretty fundamental issue that is not easy to discover without a lot of debugging, i want to suggest adding this to the **limitations** list in the docs. 
I myself spent half a year wondering why my textures don't update until discovering this issue page accidentally while debugging another issue.

**Comment by billhollings** [comment]
PR #1098 completes the fixes for host-coherent memory on macOS starting with 10.15.6. 

PR #1103 fixes the documentation concern identified [above](https://github.com/KhronosGroup/MoltenVK/issues/175#issuecomment-706135324).
