### ISSUE TITLE
vkAcquireNextImageKHR returns VK_SUCCESS even when window is resized

### ISSUE THREAD

**Issue by johnpayne-dev** [KhronosGroup/MoltenVK#1753]
Happens on both v1.1.11 and v1.2.0 for me, I don't remember this always being an issue so I'll try and find a regression.

When I fullscreen the window VK_SUBOPTIMAL_KHR is returned, it's just resizing that continues to return VK_SUCCESS.

**Comment by timprepscius** [comment]
I am also seeing that the behavior for vkAcquireNextImageKHR has changed.
I believe it changed before 1.1.4.

In the cube demo for 1.1.11
The vkAcquireNextImageKHR isn't the driver for recreation, but the

```
    } else if (err == VK_SUBOPTIMAL_KHR) {
        // SUBOPTIMAL could be due to a resize
        VkSurfaceCapabilitiesKHR surfCapabilities;
        err = demo->fpGetPhysicalDeviceSurfaceCapabilitiesKHR(demo->gpu, demo->surface, &surfCapabilities);
        assert(!err);
        if (surfCapabilities.currentExtent.width != (uint32_t)demo->width ||
            surfCapabilities.currentExtent.height != (uint32_t)demo->height) {
            demo_resize(demo);
        }
    }
```

In my code, I also never get a VK_SUBOPTIMAL_KHR from the present frame :-/
I'm not sure what this means.

**Comment by billhollings** [comment]
MoltenVK returns `VK_SUBOPTIMAL_KHR` if it detects that the `CAMetalLayer` underlying the `NSView/UIView` has changed dimensions (resized) or content scale (eg. moved to a different physical display).

However, as a Vulkan driver, MoltenVK does not manage resizing the view. It is the responsibility of the app to configure the view to be resizable. It's possible that your app does not support the view being resized to different dimensions (as opposed to simply being stretched).

**Comment by timprepscius** [comment]
Yeah.  Before I could rely on VK_SUBOPTIMAL_KHR or some other Vulkan exception occurring (I forget exactly), which I would use to trigger rebuilding the surface.

Now, for whatever reason, they no longer occur (after I updated MoltenVK), and I now rely on the apple:
    func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize)

i'm not exactly sure if this is completely in line with what you wrote or not.

**Comment by billhollings** [comment]
Interesting. As I mentioned, MoltenVK will still return `VK_SUBOPTIMAL_KHR` if it detects that the size or scale of the surface has changed. However, if your update system is changing the `drawableSize` directly, then MoltenVK might not be detecting it.

We might have to return to remembering the old `drawableSize` as well, to better determine that.

What version of MoltenVK were you using before, so we can check how `VK_SUBOPTIMAL_KHR` was used then?

**Comment by billhollings** [comment]
PR #1835 should fix this issue. Please retest and close this issue if the problem you encountered has been resolved.
