### ISSUE TITLE
CounterSets retain needs to be applied to 0x8a5c

### ISSUE THREAD

**Issue by tellowkrinkle** [KhronosGroup/MoltenVK#1761]
Just got a user in Dolphin with an `8A5C` Iris Plus and crashing counter sets

Must've been on one of these: <https://everymac.com/systems/apple/macbook-air/specs/macbook-air-core-i3-1.1-dual-core-13-retina-display-2020-scissor-specs.html>

**Comment by billhollings** [comment]
Fixed in PR #1772. Please retest with latest code.

**Comment by billhollings** [comment]
Fixed in PR #1773.
