### ISSUE TITLE
semaphoreUseMTLFence why would i not want this?

### ISSUE THREAD

**Issue by MennoVink** [KhronosGroup/MoltenVK#1762]
I'm using MVK 1.3.224.0. On nvidia based macs my application freezes. This happens when i try to synchronize two command buffers using a semaphore. First i'm submitting a texture copy to the transfer queue, and then i'm submitting an exclusive acquire barrier to the graphics queue. This freezes in `MVKSemaphoreEmulated::encodeWait`, even though the signal has already been submitted.

On non-nvidia macs this works fine, probably because MTLEvent is available. I can reproduce the freeze on these machines though. I just have to disable semaphoreUseMTLEvent and it shows the same behaviour.

Now i saw that there is a semaphoreUseMTLFence option, but it's disabled by default. In it's comment it sais _if it is available on the device_, what does this mean exactly? What leads to them being available or unavailable on a device? Can i rely on them being available to prevent emulated semaphore usage?
Then it moves on to say _On NVIDIA GPUs, MTLEvent is disabled for VkSemaphores, so CPU-based synchronization will be used unless semaphoreUseMTLFence is enabled and MTLFence is available_. I am wondering, why wouldn't i want to use MTLFences if they are available? Is there something i should be aware of before turning this on?

**Comment by MennoVink** [comment]
As-in across queues in the same family, or also across families? If it's the latter, then with metal's submission order being execution order guarantees, does that then mean that MTLFence's are only intended to submit out of order?

**Comment by cdavis5e** [comment]
> As-in across queues in the same family, or also across families?

Both.

> If it's the latter, then with metal's submission order being execution order guarantees, does that then mean that MTLFence's are only intended to submit out of order?

They are only intended to order execution of command encoders within a single queue. Metal *can* and *will* execute them out of order if it thinks it can prove they don't affect each other. They're primarily needed if you're also using hazard-untracked resources, which MoltenVK does not yet (but probably should).

**Comment by MennoVink** [comment]
Thanks for the answers!
I'm not sure i understand why this option is present in the public API then but for me it's not what i need since i need to synchronize cross family.
Gues i'll have to dig in to mvk to figure out why it does a wait without command buffer to begin with.

**Comment by billhollings** [comment]
> I'm not sure i understand why this option is present in the public API

The `semaphoreUseMTLFence` config option was added during the early days of exploring techniques for `VkSemaphore` support in MoltenVK. It was added before `MTLEvents` were available, and `MTLFence` was the only option possible other than CPU callbacks.

In the current MoltenVK, it is now officially deprecated, and both `semaphoreUseMTLFence` and `semaphoreUseMTLEvents` have been superseded by `semaphoreSupportStyle`, which is an enumeration that allows more options for selecting the type of Metal sync to use for `VkSemaphore`, based on what is available on the platform.
