### ISSUE TITLE
I got an error when running the MoltenVK-iOS Demo Applications

### ISSUE THREAD

**Issue by tankwei** [KhronosGroup/MoltenVK#180]
My application crashed with the reason:'NSInvalidArgumentException', reason: '-[AGXG4PDevice supportsTextureSampleCount:]: unrecognized selector sent to instance 0x102b44000'  ,I had compiled and built the MoltenVK succefully but I got the error ,how can I fix this problem?

**Comment by tankwei** [comment]
MVKDevice.mm
    for (uint32_t sc = VK_SAMPLE_COUNT_1_BIT; sc <= VK_SAMPLE_COUNT_64_BIT; sc <<= 1) {
        BOOL support = [_mtlDevice supportsTextureSampleCount: mvkSampleCountFromVkSampleCountFlagBits((VkSampleCountFlagBits)sc)];
        if (support) {
            _metalFeatures.supportedSampleCounts |= sc;
        }
    }
}
I't seems that MVKDevice.mm didn't implement the supportsTextureSampleCount:
method of MTLDevice protocol.
I'm trying to find the implement of 'supportsTextureSampleCount'  and find nothing.

**Comment by billhollings** [comment]
@tankwei 

What version of OS are you running?

MoltenVK requires macOS 10.11 or iOS 9.0.

It is not `MVKDevice` that implements `supportsTextureSampleCount`...it is `MTLDevice`. That `MTLDevice` method was added in those two OS versions.

**Comment by tankwei** [comment]
@billhollings  Thanks for your help! 
 I'm running an iOS 8.1.2  and Xcode 9.0 for development.
 This morning I upgraded my iPhone to iOS 11.4 and then the Cube Demo is running!

**Comment by billhollings** [comment]
@tankwei  Glad you got it working!
