### ISSUE TITLE
VK_EXT_swapchain_maintenance1, VK_EXT_surface_maintenance1 support

### ISSUE THREAD

**Issue by egorov-k** [KhronosGroup/MoltenVK#1803]
There are some gaps in vulkan WSI spec. The spec doesn't explain clearly when it's safe to destroy a swapchain and destroy a semaphore passed to VkPresentInfo.waitSemaphores. VK_EXT_swapchain_maintenance1, VK_EXT_surface_maintenance1 fixes these gaps.

**Comment by billhollings** [comment]
PR #1835 implements this request.
