### ISSUE TITLE
Mixed up R5G6B5 and B5G6R5 formats

### ISSUE THREAD

**Issue by cfnptr** [KhronosGroup/MoltenVK#1805]
Hello!

Looks like the formats are mixed up here: <ins>R</ins>5G6<ins>B</ins>5_UNORM_PACK16 -> <ins>B</ins>5G6<ins>R</ins>5Unorm.
Perhaps there is some reason why they map like that?

https://github.com/KhronosGroup/MoltenVK/blob/c8f581088f87ddc32fa99dbe1af917ce3fc18904/MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.mm#L781-L782

**Comment by billhollings** [comment]
Are you experiencing a problem in practice, or just curious about the pixel format layouts as defined in their names?

You'll notice that this same "reverse" mapping occurs for all packed pixel formats.

Apple pixel formats are always described in a little-endian layout, for both packed and unpacked formats. Vulkan formats support the endianness of the platform for unpacked formats, but the names of the packed formats are defined in terms of a big-endian layout.

So, we end up with:

- `VK_FORMAT_R8G8B8A8_UNORM <=> MTLPixelFormatRGBA8Unorm ` (both with `R` in byte 0)
- `VK_FORMAT_R5G6B5_UNORM_PACK16 <=> MTLPixelFormatB5G6R5Unorm` (both with `R` in high-end bits)

**Comment by cfnptr** [comment]
No problem in practice, just noticed that metal supports one format variant and Vulkan claims another. My first thought was that they were mixed up, since I don't write image data from the CPU side. Thank you for the clarification.
