### ISSUE TITLE
Static linking and dynamic loading of Vulkan functions

### ISSUE THREAD

**Issue by puzzlepaint** [KhronosGroup/MoltenVK#1809]
I just used MoltenVK for the first time, porting a small application that uses SDL and Vulkan to iOS. It worked fine on macOS with the Vulkan SDK. However, on iOS, SDL reported "Failed to load Vulkan Portability library", which really confused me. The problem turned out to be as follows:

The application generally uses a Vulkan loader (volk) to dynamically load the Vulkan functions. No Vulkan function is called directly. Because of that, it seems that on iOS, where all of the Vulkan functions are linked statically, they were stripped from the executable because they were unused from the compiler's point of view. Thus, `dlsym()`, as used internally by volk and SDL, could not find the functions and returned null.

As a workaround, I edited the `MVK_PUBLIC_SYMBOL` define in MoltenVK's Common/MVKCommonEnvironment.h, adding `__attribute__((used))`:
```c++
/** Directive to identify public symbols. */
#define MVK_PUBLIC_SYMBOL        	__attribute__((visibility("default"))) __attribute__((used))
```

While this workaround is not ideal, as directly calling the Vulkan functions would be more efficient, it allowed the application to run without possibly larger changes (and for this specific application which is an internal tool, neither the binary size nor the performance matter strongly).

Since it took me some time to figure out what the exact problem was here, I would like to suggest to add a note about this somewhere in the Readme (unless I missed it and it is already there somewhere), warning that the use of dynamic Vulkan function lookup (as used by volk or SDL, for example) may not work with the static linking. There is a section "Hiding Vulkan API Symbols" in the main Readme, which actually contributed to my confusion because it seemed to imply that the symbols are always available by default, and are only unavailable if using the optional flag `MVK_HIDE_VULKAN_SYMBOLS`.

Since it seems to me like nearly every project that uses SDL and MoltenVK on iOS would run into this issue, I am also speculating whether this may not be the default behavior, and instead my (CMake-generated) XCode project might have gotten some non-standard option for aggressive stripping of unused functions enabled accidentally.

**Comment by billhollings** [comment]
> all of the Vulkan functions are linked statically, they were stripped from the executable because they were unused from the compiler's point of view

The symbols are visible in the static build of MoltenVK, as built by the MoltenVK build configuration. So, if I understand correctly, you mean that these static symbols are subsequently stripped during the app build, because the app itself never calls the static functions?

If that is the case, I'm surprised that the app build is not recognizing the link to the static functions established within the MoltenVK build in `MVKInstance.mm`:

https://github.com/KhronosGroup/MoltenVK/blob/7a320974d1b349c86149b0dbc9a2e796d8992ee0/MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm#L397-L398


> As a workaround, I edited the `MVK_PUBLIC_SYMBOL` define in MoltenVK's Common/MVKCommonEnvironment.h, adding `__attribute__((used))`:

In principal, I don't see a problem in formally marking the static functions as used, either in `MVK_PUBLIC_SYMBOL` or `ADD_ENTRY_POINT_MAP`, once we understand why the app build is not already seeing that the static links are being used in `ADD_ENTRY_POINT_MAP`.

**Comment by puzzlepaint** [comment]
> [...] you mean that these static symbols are subsequently stripped during the app build, because the app itself never calls the static functions?

Yes, I believe that this is what happened. (And in principle that should be fine, except for the ability to conveniently use the same dynamic function loading code in the app as is used on other platforms.)

> once we understand why the app build is not already seeing that the static links are being used in ADD_ENTRY_POINT_MAP.

Is there any chance that the function in which the ADD_ENTRY_POINT macros are used, `MVKInstance::initProcAddrs()`, is itself seen as unused?

**Comment by billhollings** [comment]
> Is there any chance that the function in which the ADD_ENTRY_POINT macros are used, MVKInstance::initProcAddrs(), is itself seen as unused?

`MVKInstance::initProcAddrs()` flows procedurally from `vkCreateInstance()`. If the app build is tearing things apart at that level, it would basically be removing the entire MoltenVK code base.

How does your app call `vkCreateInstance()`?

**Comment by puzzlepaint** [comment]
I don't think that there is any static link from my app to MoltenVK. The initialization flow should be as follows:

In SDL2/src/video/uikit/SDL_uikitvulkan.m, in code called by `SDL_CreateWindow()`, the pointer to `vkGetInstanceProcAddr` is retrieved with `dlsym()`:
```c++
#define DEFAULT_HANDLE RTLD_DEFAULT

// [...]

PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr = NULL;

// [...]

/* Handle the case where Vulkan Portability is linked statically. */
vkGetInstanceProcAddr =
(PFN_vkGetInstanceProcAddr)dlsym(DEFAULT_HANDLE,
                                 "vkGetInstanceProcAddr");

// [...]

_this->vulkan_config.vkGetInstanceProcAddr = (void *)vkGetInstanceProcAddr;
```

Then my app uses `SDL_Vulkan_GetVkGetInstanceProcAddr()` to get this pointer and passes it to `volkInitializeCustom()`. That function stores it in a global function pointer `pvkGetInstanceProcAddr` that is declared in volk.h, and uses it with a `null` instance parameter to query functions like `vkCreateInstance()`:
```c++
static PFN_vkVoidFunction vkGetInstanceProcAddrStub(void* context, const char* name)
{
	return pvkGetInstanceProcAddr((VkInstance)context, name);
}

void volkInitializeCustom(PFN_vkGetInstanceProcAddr handler)
{
	pvkGetInstanceProcAddr = handler;

	volkGenLoadLoader(NULL, vkGetInstanceProcAddrStub);
}

static void volkGenLoadLoader(void* context, PFN_vkVoidFunction (*load)(void*, const char*))
{
	/* VOLK_GENERATE_LOAD_LOADER */
#if defined(VK_VERSION_1_0)
	pvkCreateInstance = (PFN_vkCreateInstance)load(context, "vkCreateInstance");
	pvkEnumerateInstanceExtensionProperties = (PFN_vkEnumerateInstanceExtensionProperties)load(context, "vkEnumerateInstanceExtensionProperties");
	pvkEnumerateInstanceLayerProperties = (PFN_vkEnumerateInstanceLayerProperties)load(context, "vkEnumerateInstanceLayerProperties");
#endif /* defined(VK_VERSION_1_0) */
#if defined(VK_VERSION_1_1)
	pvkEnumerateInstanceVersion = (PFN_vkEnumerateInstanceVersion)load(context, "vkEnumerateInstanceVersion");
#endif /* defined(VK_VERSION_1_1) */
	/* VOLK_GENERATE_LOAD_LOADER */
}
```

My app subsequently uses the function pointer retrieved by volk to call `vkCreateInstance()`:
```c++
if (!VulkanCheckResult(pvkCreateInstance(&instance_info, nullptr, &instance_))) {
  // [...]
}
```

I did modify volk's function pointer names by adding the prefix 'p' (this is why the function is called as "pvkCreateInstance()" in the snippet above). This is because on the one hand, using the original function names caused issues on another platform (see https://github.com/zeux/volk/issues/1), and on the other hand, the hidden symbol visibility that was used to resolve this first issue in volk caused another issue (https://github.com/zeux/volk/issues/51); prefixing the function pointer names solved both issues.

**Comment by billhollings** [comment]
Thanks for the further details. They are really helpful.

From your code description, I can see that even `vkGetInstanceProcAddr()` is not statically linked, and I understand now, the need for the `used` attribute. 

But, I'm curious. As an experiment, rather than mark **_all_** functions with the `used` attribute, what happens if you remove it from your `MVK_PUBLIC_SYMBOL` definition, and add it **_only_** to `vkGetInstanceProcAddr` in `vulkan.mm`, as follows:

    MVK_PUBLIC_VULKAN_SYMBOL __attribute__((used)) PFN_vkVoidFunction vkGetInstanceProcAddr(

or better yet even, **_only_** to `vk_icdGetInstanceProcAddr` (a special loader API function) in `vulkan.mm`

    MVK_PUBLIC_SYMBOL __attribute__((used)) PFN_vkVoidFunction vk_icdGetInstanceProcAddr(

I'm wondering if after marking that as `used`, then all the other functions will flow from that, and be kept.

**Comment by billhollings** [comment]
PR #1818 fixes this issue by implementing suggestion above.

@puzzlepaint I've implemented your [suggested solution](https://github.com/KhronosGroup/MoltenVK/issues/1809#issue-1517493553). But it would be informative if you could try your app with `__attribute__((used))` limited to **_only_** one of the functions I [mentioned above](https://github.com/KhronosGroup/MoltenVK/issues/1809#issuecomment-1376309779), to allow us to better understand the linker dependencies between the symbols. Thanks.

**Comment by puzzlepaint** [comment]
I tested your suggestions to only apply the used attribute to one of the two mentioned functions, and my app starts successfully in both cases. Since the app's use of Vulkan is rather basic, this testing probably only covers some of the most common functions, however.

The app also works with the up-to-date main branch, so I will close this issue. Thank you!
