### ISSUE TITLE
Missing formats on M1/M2 devices

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/MoltenVK#1814]
Some packed formats (specifically 4 bit packed formats like R4G4B4A4_PACK16) are not advertised as supported on M1/M2 devices. After reading MVKPixelFormats.mm I found that those formats are not advertised at all on macOS. While for older Macs with Intel and AMD GPUs this is true, it does not hold for the new Apple Silicon Macs. These are part of the Apple7 and Apple8 families and do support all of the formats. I will look into correcting it based on the Metal feature tables, given that the formats do actually match and work together.

All of the missing formats get kMVKMTLFmtCapsNone for macOS, which then makes isSupported return false:
https://github.com/KhronosGroup/MoltenVK/blob/7a320974d1b349c86149b0dbc9a2e796d8992ee0/MoltenVK/MoltenVK/GPUObjects/MVKPixelFormats.h#L176

**Comment by billhollings** [comment]
> These are part of the Apple7 and Apple8 families and do support all of the formats. 

Thanks for catching this. Yes, we've fallen a bit behind in tracking recent platform format support.

> I will look into correcting it based on the Metal feature tables

Thanks! I've assigned it to you.

> All of the missing formats get kMVKMTLFmtCapsNone for macOS

The Metal format capabilities are assigned in `MVKPixelFormats::initMTLPixelFormatCapabilities()`. You can map the values in the Metal feature tables to `MTLPixelFormats` there.

**Comment by spnda** [comment]
I just did a bit more research while finally fixing the PR (#1825) and I noticed a big mistake I made. I was looking at [this report](http://vulkan.gpuinfo.org/displayreport.php?id=18072#formats_optimal) which did, in fact, not advertise support for all the formats. Now, looking at other reports it seems that all reports which go in as `x86_64` are reporting the 130 formats and missing the packed formats and all others I identified. All reports that are `arm64` report the full 176 formats as I would expect.

I looked at Activity Monitor and noticed that all components of the SDK are being built as `x86_64`. Therefore, MoltenVK is being built with `MVK_APPLE_SILICON` as `0`, making all those formats get disabled. This is why all the reports that use MoltenVK from the SDK don't have the formats show up. I will update the PR in a second in which I just update the definitions to use `MVK_XCODE_12_2` to identify `macOS 11` as the target. I seriously dislike all this macro usage to determine target capabilities, and would wholeheartedly recommend a refactor that uses `if (@available(...))` (not `mvkOSVersionIsAtLeast` as that serves a different purpose) to exclude formats. See: https://developer.apple.com/documentation/swift/marking-api-availability-in-objective-c

**Comment by billhollings** [comment]
Our use of `mvkOSVersionIsAtLeast()` predated the introduction of `@available()`, but they accomplish the same thing, which is to select code at runtime based on the runtime OS version.

The use of the `MVK_XCODE_*` macros serves a different purpose, which is to ensure the SDK used during the build is available if someone is building MoltenVK using an older version of Xcode that doesn't have the symbols even defined.
