### ISSUE TITLE
Please rename default branch from 'master' to 'main' per Khronos policy

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/MoltenVK#1816]
To repository owners: please rename the default branch of this repository from 'master' to 'main', using the [Github renaming tool](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch). This request is per policy set by the Khronos Promoters in May 2021, to follow Github community practice for respectful naming.

The Github renaming tool sets up URL redirections and retargets outstanding pull requests, so the impact on repository users is minimal. The most visible issue is that people with local repo clones will probably want to rename their clone's 'master' branch, following the popup instructions that will be seen when browsing the github repository after the change; or just delete 'master' and pull the new 'main', if it's purely a tracker with no local content.

You may wish to coordinate with @outofcontrol if you are doing auto-updates from this repository to another location, whether via push/pull mirroring or other mechanisms. The redirects setup by Github should accommodate most such uses transparently, but it's still good practice.

Based on experience with other KhronosGroup repositories which have undergone this renaming already, this is a reasonable approach:

* Agree on a date for the renaming within the Working Group or other owners of the repository, and document that date here.
  * Date can be adjusted to avoid interaction with major releases in flight.
* Provide notice to repository users outside Khronos, insofar as possible (adding a comment in the repo README with the switchover date is one way).
* Once the renaming is done, edit the new 'main' branch to replace hardwired references to 'master' with (preferably) 'default branch' or 'main'.
* Update the repo README to note the change.

If you have questions or issues about this, please raise them on Khronos internal gitlab 'khronos-general' issue 106 if possible. If not possible, you can @-tag me here.

While we will not force any WG into acting precipitously, this is our agreed policy. Please try to accommodate renaming relatively soon.

Note that this issue is automatically generated, due to the large number of KhronosGroup repositories it's being raised in.

**Comment by billhollings** [comment]
The MoltenVK repository default branch has been renamed from `master` to `main`. See #1819.
