### ISSUE TITLE
Is linear filtering not supported?

### ISSUE THREAD

**Issue by Overv** [KhronosGroup/MoltenVK#183]
I use a command like the following from one layer to the next repeatedly to generate the mipmap layers for an image:

    vkCmdBlitImage(commandBuffer, image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, VK_FILTER_LINEAR);

This works fine on NVIDIA and AMD graphics cards on Windows and Linux, but none of the MoltenVK image formats seem to support `VK_FORMAT_FEATURE_FILTER_LINEAR_BIT`. Is this an actual limitation or an oversight? If it is a limitation, do mipmaps need to be generated in software?

**Comment by billhollings** [comment]
@Overv

Yes...MoltenVK supports linear filtering sampling for `vkCmdBlitImage()` rescaling.

Are you referring to `VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT`?

If yes...then a large number of the image formats do include that bit in their optimal tiling properties.

There may indeed by some mistakes in the data filling of specific formats. Can you please have a look at the tables in `mvk_datatypes.mm` where the image properties are data-filled...and see if they are set according to what you should be expecting for your formats?

If there are any specific errors, please let us know. Thanks.

**Comment by Overv** [comment]
I am running into the issue with the format `VK_FORMAT_R8G8B8A8_UNORM`, but it looks like it does have the right property in those tables. Let me check again and get back to you.

**Comment by kbob** [comment]
I reported this bug to @Overv.  It looks like @billhollings added FILTER_LINEAR_BIT in 871a39a4.  That commit came after LunarG released Vulkan SDK 1.1.73.

I will try again with LunarG SDK 1.1.77 and, if necessary, build MoltenVK from source.

**Comment by billhollings** [comment]
@kbob 

Thanks for the background. If things are working now...please close this issue.

BTW...credit where credit is due...that 871a39a4 fix to linear filtering that you mention was made by @csmartdalton86.

**Comment by Overv** [comment]
If @kbob confirms that it's working then I'll close the issue (I don't run OSX myself).

**Comment by kbob** [comment]
I confirm that it is working in LunarG SDK 1.1.77.  @Overv's "Chapter 28" demo runs without changes on MacOS now.

Thanks, all.
