### ISSUE TITLE
Loader cannot find MoltenVK_icd.json in app bundle.

### ISSUE THREAD

**Issue by tomilov** [KhronosGroup/MoltenVK#1830]
Executable in app bundle, that load `../Frameworks/vulkan.1.dylib` using `dlopen`+`dlsym`, should set current working directory of itself to its base directory (i.e. `appname.app/Contents/MacOS/` for `appname.app/Contents/MacOS/appname`) in order to relative paths in `VK_DRIVER_FILES` to work. Otherwise loader cannot find `../Resources/MoltenVK_icd.json` and further `../Resources/../Frameworks/libMoltenVK.dylib`. This is because by default current directory is `/` for apps in app bundles.
This is not true:
 > The macOS loader also looks in the application's bundle for ICD and layer JSON files. It looks in the bundle's `Resources/vulkan/icd.d` directory for ICD JSON files

quoted from [here](https://vulkan.lunarg.com/doc/view/latest/mac/getting_started.html).

**Comment by cdavis5e** [comment]
Okay... what do you want *us* to do? We do not control the current working directory of the app--according to your description, this is happening *before* MoltenVK even gets a chance to load.

**Comment by tomilov** [comment]
@cdavis5e there is two ways:
 - to find a way to get absolute path of some fixed subpath in app budle directory and use it as base path to search ICD descriptions relative to it
 - to correct the documentation in accordance with reality

**Comment by tomilov** [comment]
Ah, ok. This should be addressed in loader repo. Sorry.

**Comment by cdavis5e** [comment]
Eh, it's all right.
