### ISSUE TITLE
Explicit LOD Workaround for Apple silicon regression

### ISSUE THREAD

**Issue by italomandara** [KhronosGroup/MoltenVK#1838]
I encountered this issue only on Resident Evil 3 Remake so far (using crossover on M1 Max), I have tried few other games but couldn't see any issue so far. This could happen on more games that aren't in my game library, like all re-engine games https://en.wikipedia.org/wiki/RE_Engine.

Probably this issue is related to this commit: 2c01c8b7e066ec9c95c53b4613066e7561a6ac4a

before the commit:
![Before](https://user-images.githubusercontent.com/12135454/218267481-cae8ed1f-4d60-4e5b-aea6-9d3c10fe0c6a.png)

after:
![after](https://user-images.githubusercontent.com/12135454/218267491-676472be-7d39-40d0-a15e-11a29196b5c4.png)

Machine: Apple M1 Max 14" 32GB RAM
os: 13.1 (22C65) Ventura
software: Crossover, Steam, Resident Evil 3 Remake (DX11 version)

**Comment by italomandara** [comment]
This happens also using VKD3D so definitely not a Crossover + DXVK issue

**Comment by billhollings** [comment]
> Probably this issue is related to this commit: [2c01c8b](https://github.com/KhronosGroup/MoltenVK/commit/2c01c8b7e066ec9c95c53b4613066e7561a6ac4a)
> Machine: Apple M1 Max 14" 32GB RAM os: 13.1 (22C65) Ventura software: Crossover, Steam, Resident Evil 3 Remake (DX11 version)

@cdavis5e Are you able to look into this?

**Comment by cdavis5e** [comment]
> @cdavis5e Are you able to look into this?

I don't have access to that game, especially now that I don't work for CW anymore.

@italomandara What happens when you run it with validation enabled?

**Comment by italomandara** [comment]
> > @cdavis5e Are you able to look into this?
> 
> I don't have access to that game, especially now that I don't work for CW anymore.
> 
> @italomandara What happens when you run it with validation enabled?

I'll test and let you know meanwhile can you quickly remind me how to enable the validation please?

**Comment by cdavis5e** [comment]
> I'll test and let you know meanwhile can you quickly remind me how to enable the validation please?

Set the environment variables `METAL_DEVICE_WRAPPER_TYPE=1`, `MTL_DEBUG_LAYER=1`, `MTL_SHADER_VALIDATION=1`.

**Comment by italomandara** [comment]
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL:
MSL conversion error: Combined image samplers have no default expression representation.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL:
MSL conversion error: Combined image samplers have no default expression representation.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL:
MSL conversion error: Combined image samplers have no default expression representation.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.

**Comment by cdavis5e** [comment]
Was that in the log without Metal validation? This would've been helpful to know before...

**Comment by italomandara** [comment]
I get the same errors

**Comment by cdavis5e** [comment]
Can you provide the SPIR-V or GLSL for the shader that failed this way?

**Comment by italomandara** [comment]
[MSL+GLSL+Error.txt](https://github.com/KhronosGroup/MoltenVK/files/10731456/MSL%2BGLSL%2BError.txt)

**Comment by italomandara** [comment]
@cdavis5e if there are other ways to debug issue e.g. xcode Metal tools, I'm happy to help. Even pair programming if you will.

**Comment by italomandara** [comment]
@billhollings perhaps we could temporarily feature flag the workaround introduced with https://github.com/KhronosGroup/MoltenVK/commit/2c01c8b7e066ec9c95c53b4613066e7561a6ac4a
until the fix is done? maybe I could try it myself in a PR, it should be simple.

**Comment by italomandara** [comment]
@cdavis5e I noticed I gave you the wrong trace, it's a compute shader while the error complains about a fragment shader. I'll try to give you the right info soon.

**Comment by italomandara** [comment]
[Error_and_partial_MSL.txt.zip](https://github.com/KhronosGroup/MoltenVK/files/11154086/Error_and_partial_MSL.txt.zip)
[Estimated_GLSL.txt.zip](https://github.com/KhronosGroup/MoltenVK/files/11154087/Estimated_GLSL.txt.zip)

**Comment by italomandara** [comment]
@billhollings 
**Games currently/potentially affected:**

Resident Evil 7: Biohazard
Resident Evil 2
Devil May Cry 5
Resident Evil 3
Resident Evil: Resistance
Devil May Cry 5: Special Edition
Capcom Arcade Stadium
Ghosts 'n Goblins Resurrection
Monster Hunter Rise
Resident Evil Village
Capcom Arcade 2nd Stadium
Resident Evil Re:Verse
Resident Evil 4
Street Fighter 6
Sunset overdrive

also if this is the fix: https://github.com/KhronosGroup/SPIRV-Cross/commit/34cd230e5e22d08869be878055a2267ba66cc601

all you have to do is pull that in your dependencies right?

**Comment by billhollings** [comment]
> also if this is the fix: https://github.com/KhronosGroup/SPIRV-Cross/commit/34cd230e5e22d08869be878055a2267ba66cc601

Forgive my ignorance, but do we understand how the issues above are related to this SPIRV-Cross fix, which from the description (GLSL fix and no mention of MSL), and fix, seem unrelated to me, on the surface.

And if we do understand that, does that SPIRV-Cross fix mean the entire workaround controlled by `needsSampleDrefLodArrayWorkaround` is not longer needed? Or does it just fit the regression that the workaround caused, but we still need the workaround?

> if it helps I can open a PR where I bump up the revision and revert the commit where i introduced the feature flag to enable/disable the LOD workaround, how about that?

If we do have all that understood, I'm fine with you submitting a PR. The MoltenVK release (#1894) for the upcoming SDK will be cut on Mon May 22, so let's try to get it in by then.
- If the SPIRV-Cross fix means `needsSampleDrefLodArrayWorkaround` is no longer needed, leave it in the `MVKPhysicalDeviceMetalFeatures` for backwards compatibility, and leave it set to `false` always. If the `needsSampleDrefLodArrayWorkaround` flag is still needed, just revert your change from #1861.
- For an SDK release, we normally pull in the latest SPIRV-Cross commit (currently `12542fc6fc05000e04742daf93892a0b10edbe80`), so pull in the latest SPIRV-Cross commit, instead of the one you suggest.

**Comment by italomandara** [comment]
Let's see if my assumption is right.
Correct me if I'm wrong:
The original error for this issue was: `MSL conversion error: Combined image samplers have no default expression representation.`

I was just interpreting this line https://github.com/KhronosGroup/SPIRV-Cross/commit/34cd230e5e22d08869be878055a2267ba66cc601#diff-be4b0e499f62a9c91e1f74e4dfa617934711419be4b43e057a571cf7ab62c93aR10906
as a possible fix of the Combined image samplers issue that caused the failed the shader compilation, hence resulting in the model having black textures?

that piece of code was part of the original work  (on the SPIRV-cross side) for the LOD workaround IIRC.
So just to confirm, i did a test build of moltenVK  (i bumped up the revision and ran fetchDependencies), re-tested and was indeed fixed somehow.
So I assumed that commit in the SPIRV-cross repo was fixing the issue that's all.
If that's so this issue was all about a bug introduced in SPIRV-Cross that now is fixed.

**Comment by italomandara** [comment]
Furthermore if this is indeed fixed, there's no longer use for `MVK_ENABLE_EXPLICIT_LOD_WORKAROUND` and the commit for that feature flag can be easily reverted.

**Comment by italomandara** [comment]
>And if we do understand that, does that SPIRV-Cross fix mean the entire workaround controlled by needsSampleDrefLodArrayWorkaround is not longer needed?

no that workaround might still be needed, but that workaround introduced a regression and that's the thing that has been fixed.

**Comment by billhollings** [comment]
Okay. Thanks for the background.

Since you're the originator of #1861, I'm comfortable with you submitting the PR you suggest:

- Leave the workaround in place
- Revert #1861.
- Move to latest SPIRV-Cross (HEAD) commit

Thanks for all your research on this issue!
