### ISSUE TITLE
Overwatch 2 part of UI invisible

### ISSUE THREAD

**Issue by marzent** [KhronosGroup/MoltenVK#1869]
This is with the latest version of DXVK 1.X and MoltenVK (works fine with a native Vulkan driver).

There appear to be certain 2d UI elements missing (transparent) in Overwatch, whereas 3d is working perfectly fine as far as I can tell.

For example battle pass icons are missing:
![image](https://user-images.githubusercontent.com/44967463/232313353-754d80b6-ffa7-453e-b9cb-8c81e167b42e.png)

And main menu "cards":
![image](https://user-images.githubusercontent.com/44967463/232313416-66979476-e0a4-41ae-bcb8-27d9268b4c34.png)

For reference this is how they are supposed to look like:
![image](https://user-images.githubusercontent.com/44967463/232313580-2bd4eab9-949f-45b7-8220-6e5524977ed3.png)

Everything is clickable and fully interactable, except for being transparent (not for all 2d ui elements though).

At the start there is the following error logged once by DXVK (not sure if this is a problem though since 3D seems to be fine)

```
err:   D3D11: CreateGeometryShaderWithStreamOutput:
err:     Transform feedback not supported by device
```

After that the following is logged around 8 times on the main menu
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 3):
Compiler encountered an internal error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_3ea0d26fdcae7c441e771ff97fc600119cfca47a
err:     fs  : FS_f99b075ceb1ffc8704c44fd957e89365c6089508
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R16G16B16A16_SINT, offset 0
err:     attr 1 : location 1, binding 0, format VK_FORMAT_R32_UINT, offset 8
err:     binding 0 : binding 0, stride 12, rate 0, divisor 0
```

**Comment by marzent** [comment]
I have attached a log with 
```
MVK_CONFIG_LOG_LEVEL=3
MVK_DEBUG=1
```
as well, hopefully this provides more insight.

I also made a mistake above on the order of events, the first render pipeline compile failure happens before the DXVK geometry shader error.

[ow2.log](https://github.com/KhronosGroup/MoltenVK/files/11247034/ow2.log)

**Comment by billhollings** [comment]
> Compiler encountered an internal error.

This error is coming from the Metal pipeline compiler. Unfortunately, it's not very helpful.

Can you try running the game with the following environment variables, to see if Metal logs any validation errors?

```
METAL_DEVICE_WRAPPER_TYPE=1
METAL_ERROR_MODE=3
METAL_DEBUG_ERROR_MODE=3
```

Also...there are several mentions of geometry shaders. I assume the game has detected the lack of geometry shaders and is finding other rendering paths? If the game is ignoring that, it will not run properly.

**Comment by cdavis5e** [comment]
> assume the game has detected the lack of geometry shaders and is finding other rendering paths?

Not likely. That's a D3D11 game. OP mentioned DXVK, for which you of course need to fake support for geometry shaders.

**Comment by marzent** [comment]
> OP mentioned DXVK, for which you of course need to fake support for geometry shaders.

No extensions from MVK have been faked (which is completely stock), the version of DXVK is a special one though that reverts https://github.com/doitsujin/dxvk/commit/2cac70fbb6bc3e9d69c29082b66dfa7b639432cc, and a few other minor patches to make it run better on macOS.

The game also only calls once into `CreateGeometryShaderWithStreamOutput()` even after an extended period of flawless (not counting main menu interactions) gameplay.

Not sure if the metal validation env vars did much but I did attach the updated log.

[ow2_val.log](https://github.com/KhronosGroup/MoltenVK/files/11255754/ow2_val.log)

**Comment by billhollings** [comment]
> Not sure if the metal validation env vars did much but I did attach the updated log.

Yeah. Nothing helpful added. Uggh. Okay. So the problem is that Metal is choking on that particular pipeline. 

The shaders involved in those failed pipeline compile are quite complex for a UI, which is odd. Given this is a port from DX, I guess it's not going to be possible to simplify those shaders or that pipeline definition? Are there any game config options that could modify that?

**Comment by marzent** [comment]
Not sure if there can be done much config wise, but the failures happen very early on during the connecting to DC loading bar (this is also the exact point in time at which the logs above end).
<img width="2056" alt="Screenshot 2023-04-18 at 00 21 47" src="https://user-images.githubusercontent.com/44967463/232623416-6e7f23bd-5c05-4e35-89f2-a27be648dcce.png">

To my eye this screen still looks and behaves like it is running on windows.

After login in the main menu proper the log grows to 1GB+ (although with only a 4-5 more of the same pipeline failures).

After that they don't show up anymore at all as far as I could tell during gameplay or going back to the main menu.

It might also very well be that this is related to the missing geometry shader support somehow, although this would not explain the pipeline failure before the first CreateGeometryShaderWithStreamOutput call.

**Comment by Gcenx** [comment]
> > assume the game has detected the lack of geometry shaders and is finding other rendering paths?
> 
> Not likely. That's a D3D11 game. OP mentioned DXVK, for which you of course need to fake support for geometry shaders.

For DXVK-CX or upstream 1.10.x and below yeah but not [DXVK-macOS](https://github.com/Gcenx/DXVK-macOS)

**Comment by ileeric** [comment]
Having the same problem too!
Missing the UI for settings, battle pass, match making and fails to log in for the first time I turn on the game, and log in is available after I re-log in inside the game client

**Comment by NathanielH-snek** [comment]
Bump

**Comment by marzent** [comment]
Well it seems the problem must be somehow Metal related as macOS 14 beta 1 and 2 seem to not have the render pipeline compile error and the UI renders correctly with the latest MVK
