### ISSUE TITLE
`VK_ERROR_FEATURE_NOT_PRESENT` in `MVKDevice::enableFeatures` does not actually print the missing feature

### ISSUE THREAD

**Issue by IsaacMarovitz** [KhronosGroup/MoltenVK#1871]
I'm currently trying my luck at getting Doom (2016) running and quickly ran into a slight issue, specifically with how this error is declared in `MVKDevice`

```obj-c++
void MVKDevice::enableFeatures(VkBool32* pEnabledBools, const VkBool32* pRequestedBools, const VkBool32* pAvailableBools, uint32_t count) {
	for (uint32_t i = 0; i < count; i++) {
		pEnabledBools[i] = pRequestedBools[i] && pAvailableBools[i];
		if (pRequestedBools[i] && !pAvailableBools[i]) {
			setConfigurationResult(reportError(VK_ERROR_FEATURE_NOT_PRESENT, "vkCreateDevice(): Requested feature is not available on this device."));
		}
	}
}
```

This is the only usage of `VK_ERROR_FEATURE_NOT_PRESENT` in MoltenVK that does not actually log the requested feature that is missing and it means I don't actually know what unsupported feature Doom is trying to use.

**Comment by billhollings** [comment]
PR #1905 fixes this issue, and identifies the struct name and member index of the improperly enabled feature flag. Please retest and close this issue if it fixes the problem.
