### ISSUE TITLE
Commands using mtlComputeEnc in MVKCmdTransfer.mm polluting the tracked encoder state?

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#1874]
I have an error that seems incorrect, where I have an argument buffer of size 12 at index 1, but metal is saying only 4 bytes are bound to it. Tracing through the code, I can see the code is avoiding re-binding at that index because it thinks it's not dirty.
However just before this command, I'm using `vkCmdFillBuffer`, which I can see is calling setBytes with a size of 4 for index 1.
I do have a command before the vkCmdFillBuffer that is binding the buffer to index 1, which is why the state tracking thinks it's already bound with the correct size of 12.

Isn't `vkCmdFillBuffer` (and likely other similar ones in the file), changing the encoder state, but those changes aren't being tracked in `MVKResourcesCommandEncoderState`?

**Comment by billhollings** [comment]
PR #1922 should fix this. Please retest with latest MoltenVK and close this issue if it corrects the problem.

**Comment by mbechard** [comment]
This commit seems to introduce a regression, as I now get
`-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:1047: failed assertion `computePipelineState must not be nil.'`
On startup in my app, which worked fine before. Seems like there is a new case where the compute pipeline encoder isn't executing.
