### ISSUE TITLE
Depth/stencil Sample-0 resolve support exposed through `VkPhysicalDeviceVulkan12Properties`, but not `VK_KHR_depth_stencil_resolve`

### ISSUE THREAD

**Issue by James2022-rgb** [KhronosGroup/MoltenVK#1875]
On iOS devices without support for `MTLFeatureSet_iOS_GPUFamily3_v1` (including iOS simulator on Mac), which should support Sample-0 depth resolve (but not other modes),
the Vulkan extension `VK_KHR_depth_stencil_resolve` doesn't seem to be advertised:
https://github.com/KhronosGroup/MoltenVK/blob/5cbeaaa82cec5029741aa7fbb0220bda77424b1b/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L3037-L3041

As a core 1.2 feature, however, Sample-0 depth resolve support seems to be advertised through `VkPhysicalDeviceVulkan12Properties::supportedDepthResolveModes` (although I haven't checked this behavior yet):
https://github.com/KhronosGroup/MoltenVK/blob/5cbeaaa82cec5029741aa7fbb0220bda77424b1b/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L512-L514

This leads to apps/engines with only Vulkan 1.0/1.1 in mind believing the device has no depth resolve support at all, when it actually supports Sample-0 resolve.

I'm of the opinion that `VK_KHR_depth_stencil_resolve` should be exposed as well, if the device supports Sample-0 resolve,
since this is the only resolve mode whose support is mandated by the extension's spec.

**Comment by billhollings** [comment]
Thanks for the catch. Fixed in PR #1920.
