### ISSUE TITLE
Two issues with vkGetPastPresentationTimingGOOGLE()

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#1882]
I have found two issues with the implementation of this feature:

1. `VkPastPresentationTimingGOOGLE.presentID` return values are sometimes mangled/nonsensical following calls to `vkGetPastPresentationTimingGOOGLE()`
2. `VkPastPresentationTimingGOOGLE.actualPresentTime` return values appear to be zero when in fullscreen (or borderless fullscreen) mode. Valid non-zero values are returned for presented swapchain images when in windowed mode.

Regarding issue 1, it seems that the `presentInfo` parameter is passed by reference to the function `MVKPresentableSwapchainImage::addPresentedHandler()` which in turn passes the same `presentInfo` parameter by reference to `MVKSwapchain::recordPresentTime` within the callback code.  These pass by reference operations are not thread safe, and are being overwritten due to async operations.  I changed the `presentInfo` parameters to be passed by value and the problem is eliminated.  With this change `vkGetPastPresentationTimingGOOGLE()` returns expected `presentID` values.

Regarding issue 2, I have not researched why the `actualPresentTime` return values are zero when in fullscreen (or borderless fullscreen) mode.  Is this a limitation of the feature or a defect?

**Comment by billhollings** [comment]
Thanks very much for your detective work. 

PR #1890 includes your fix for issue 1 above. The race was likely the queue submission being destroyed after it finished its run, and taking the `presentInfo` reference with it. I've done pass-by-value wherever the struct is being passed to a callback.

Regarding the second issue, very odd. 

`MVKSwapchain::recordPresentTime(..., uint64_t actualPresentTime)` includes the following:

	if (actualPresentTime == 0) { actualPresentTime = presentInfo.desiredPresentTime; }

so the only way that the returned `actualPresentTime` could be zero is if the Metal drawable is returning zero _**and**_ `VkPresentTimeGOOGLE::desiredPresentTime` is set to zero by the app.

Are you able to debug a bit more and see what value is being returned by `drawable.presentedTime` in `MVKPresentableSwapchainImage::addPresentedHandler`, please?

**Comment by SRSaunders** [comment]
Sorry for my delay in response but I have been working on a similar issue regarding swap chain present timing on the Windows DX12 side of things.  Specifically I have been using Optick (https://github.com/bombomby/optick), a cool multi-platform profiler, to show game timings including input to present time latency.

Regarding issue 1, getting the frame number (presentID) correct was important for latency profiling.  I have verified your changes and they work correctly.  Thanks very much for this.

Regarding issue 2, I did see your MoltenVK logic regarding `actualPresentTime` and `desiredPresentTime`.  Since I am profiling and just want to show actuals, my `desiredPresentTime` will always be 0.  This means that Metal must be returning 0 in `drawable.presentedTime` when fullscreen (or borderless fullscreen) is active.  Contrasting things with Windows, DXGI also does not return presentation stats when in true fullscreen mode (but does in borderless), so this limitation does not surprise me now in comparison.  I suspect presentation stats collection on most platforms has something to do with the screen compositing phase, which is bypassed when in true dedicated fullscreen mode.

However, I am still confused why Metal would not attempt to return valid stats when in borderless fullscreen mode.  I am speculating here, but perhaps the Mac gets rid of compositing when in borderless fullscreen mode, and if Metal stats depends on this, then it can only return 0.  I can't find much documentation on Metal's `drawable.presentedTime` capability, so perhaps you could shed some light on my thoughts.

**Comment by billhollings** [comment]
I think your assessment is correct. In either of the fullscreen modes, `CoreAnimation` is likely bypassing the compositor, which causes Metal to have no `presentedTime` info resolved. There seem to be a few similar complaints online.

PR #1906 ensures the Vulkan value is never zero, by populating it with the current time, if both the `presentedTime` and `desiredPresentTime` are zero. In my testing, this seems to be accurate to within a millisecond, and even half a millisecond on a light app. Not great, but better than no info at all.

**Comment by SRSaunders** [comment]
I just tested your workaround for issue 2 and it works quite well.  I agree - better to populate the info with an approximation than nothing at all.  Thanks very much for addressing these two issues quickly.  I look forward to the fixes in the upcoming release and SDK.
