### ISSUE TITLE
Failing to run vulkaninfo after installing vulkan on Mac 

### ISSUE THREAD

**Issue by F-l-y-i-n-g-S-t-a-r** [KhronosGroup/MoltenVK#1887]
When I try to download the Vulkan SDK on Mac, I basically downloaded vulkansdk-macos-1.3.216.0.dmg and installed it in my home directory. But when I try to run command vulkaninfo, I got an error message saying segmentation fault. Did I miss any installation steps? 

The error message is like this UNASSIGNED-khronos-validation-createinstance-status-message(INFO / SPEC): msgNum: -671457468 - Validation Information: [ UNASSIGNED-khronos-validation-createinstance-status-message ] Object 0: handle = 0x142818800, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xd7fa5f44 | Khronos Validation Layer Active:
    Settings File: Found at /Users/chuyaolizazhang/.local/share/vulkan/settings.d/vk_layer_settings.txt specified by VkConfig application override.
    Current Enables: None.
    Current Disables: VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT.

    Objects: 1
        [0] 0x142818800, type: 1, name: NULL
UNASSIGNED-khronos-Validation-fine-grained-locking-warning-message(WARN / PERF): msgNum: 2081428434 - Validation Performance Warning: [ UNASSIGNED-khronos-Validation-fine-grained-locking-warning-message ] Object 0: handle = 0x142818800, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x7c1013d2 | Fine-grained locking is disabled, this will adversely affect performance of multithreaded applications.
    Objects: 1
        [0] 0x142818800, type: 1, name: NULL
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.216

Instance Extensions: count = 14
===============================
	VK_EXT_debug_report                    : extension revision 10
	VK_EXT_debug_utils                     : extension revision 2
	VK_EXT_metal_surface                   : extension revision 1
	VK_EXT_swapchain_colorspace            : extension revision 4
	VK_EXT_validation_features             : extension revision 2
	VK_KHR_device_group_creation           : extension revision 1
	VK_KHR_external_fence_capabilities     : extension revision 1
	VK_KHR_external_memory_capabilities    : extension revision 1
	VK_KHR_external_semaphore_capabilities : extension revision 1
	VK_KHR_get_physical_device_properties2 : extension revision 2
	VK_KHR_get_surface_capabilities2       : extension revision 1
	VK_KHR_portability_enumeration         : extension revision 1
	VK_KHR_surface                         : extension revision 25
	VK_MVK_macos_surface                   : extension revision 3

Layers: count = 5
=================
VK_LAYER_KHRONOS_profiles (Khronos Profiles layer) Vulkan version 1.3.216, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (Apple M1)
		Layer-Device Extensions: count = 1
			VK_EXT_tooling_info : extension revision 1

VK_LAYER_KHRONOS_synchronization2 (Khronos Synchronization2 layer) Vulkan version 1.3.216, layer version 1:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (Apple M1)
		Layer-Device Extensions: count = 1
			VK_KHR_synchronization2 : extension revision 1

VK_LAYER_KHRONOS_validation (Khronos Validation Layer) Vulkan version 1.3.216, layer version 1:
	Layer Extensions: count = 3
		VK_EXT_debug_report        : extension revision 9
		VK_EXT_debug_utils         : extension revision 1
		VK_EXT_validation_features : extension revision 2
	Devices: count = 1
		GPU id = 0 (Apple M1)
		Layer-Device Extensions: count = 3
			VK_EXT_debug_marker     : extension revision 4
			VK_EXT_tooling_info     : extension revision 1
			VK_EXT_validation_cache : extension revision 1

VK_LAYER_LUNARG_api_dump (LunarG API dump layer) Vulkan version 1.3.216, layer version 2:
	Layer Extensions: count = 0
	Devices: count = 1
		GPU id = 0 (Apple M1)
		Layer-Device Extensions: count = 1
			VK_EXT_tooling_info : extension revision 1

VK_LAYER_LUNARG_override (LunarG Override Layer) Vulkan version 1.3.216, layer version 1:
	Layer Extensions: count = 3
		VK_EXT_debug_report        : extension revision 9
		VK_EXT_debug_utils         : extension revision 1
		VK_EXT_validation_features : extension revision 2
	Devices: count = 1
		GPU id = 0 (Apple M1)
		Layer-Device Extensions: count = 3
			VK_EXT_debug_marker     : extension revision 4
			VK_EXT_tooling_info     : extension revision 1
			VK_EXT_validation_cache : extension revision 1

Presentable Surfaces:
=====================
GPU id : 0 (Apple M1):
	Surface types: count = 2
		VK_EXT_metal_surface
		VK_MVK_macos_surface
	Formats: count = 60
		SurfaceFormat[0]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[1]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[2]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[3]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[4]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
		SurfaceFormat[5]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
		SurfaceFormat[6]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
		SurfaceFormat[7]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
		SurfaceFormat[8]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
		SurfaceFormat[9]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT
		SurfaceFormat[10]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_DCI_P3_NONLINEAR_EXT
		SurfaceFormat[11]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_DCI_P3_NONLINEAR_EXT
		SurfaceFormat[12]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_DCI_P3_NONLINEAR_EXT
		SurfaceFormat[13]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_DCI_P3_NONLINEAR_EXT
		SurfaceFormat[14]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_DCI_P3_NONLINEAR_EXT
		SurfaceFormat[15]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
		SurfaceFormat[16]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
		SurfaceFormat[17]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
		SurfaceFormat[18]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
		SurfaceFormat[19]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_BT709_NONLINEAR_EXT
		SurfaceFormat[20]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
		SurfaceFormat[21]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
		SurfaceFormat[22]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
		SurfaceFormat[23]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
		SurfaceFormat[24]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_ADOBERGB_NONLINEAR_EXT
		SurfaceFormat[25]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_PASS_THROUGH_EXT
		SurfaceFormat[26]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_PASS_THROUGH_EXT
		SurfaceFormat[27]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_PASS_THROUGH_EXT
		SurfaceFormat[28]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_PASS_THROUGH_EXT
		SurfaceFormat[29]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_PASS_THROUGH_EXT
		SurfaceFormat[30]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
		SurfaceFormat[31]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
		SurfaceFormat[32]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
		SurfaceFormat[33]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
		SurfaceFormat[34]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT
		SurfaceFormat[35]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
		SurfaceFormat[36]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
		SurfaceFormat[37]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
		SurfaceFormat[38]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
		SurfaceFormat[39]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT
		SurfaceFormat[40]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_DISPLAY_P3_LINEAR_EXT
		SurfaceFormat[41]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_DISPLAY_P3_LINEAR_EXT
		SurfaceFormat[42]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_DISPLAY_P3_LINEAR_EXT
		SurfaceFormat[43]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_DISPLAY_P3_LINEAR_EXT
		SurfaceFormat[44]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_DISPLAY_P3_LINEAR_EXT
		SurfaceFormat[45]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_BT2020_LINEAR_EXT
		SurfaceFormat[46]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_BT2020_LINEAR_EXT
		SurfaceFormat[47]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_BT2020_LINEAR_EXT
		SurfaceFormat[48]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_BT2020_LINEAR_EXT
		SurfaceFormat[49]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_BT2020_LINEAR_EXT
		SurfaceFormat[50]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_HDR10_HLG_EXT
		SurfaceFormat[51]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_HDR10_HLG_EXT
		SurfaceFormat[52]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_HDR10_HLG_EXT
		SurfaceFormat[53]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_HDR10_HLG_EXT
		SurfaceFormat[54]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_HDR10_HLG_EXT
		SurfaceFormat[55]:
			format = FORMAT_B8G8R8A8_UNORM
			colorSpace = COLOR_SPACE_HDR10_ST2084_EXT
		SurfaceFormat[56]:
			format = FORMAT_B8G8R8A8_SRGB
			colorSpace = COLOR_SPACE_HDR10_ST2084_EXT
		SurfaceFormat[57]:
			format = FORMAT_R16G16B16A16_SFLOAT
			colorSpace = COLOR_SPACE_HDR10_ST2084_EXT
		SurfaceFormat[58]:
			format = FORMAT_A2B10G10R10_UNORM_PACK32
			colorSpace = COLOR_SPACE_HDR10_ST2084_EXT
		SurfaceFormat[59]:
			format = FORMAT_A2R10G10B10_UNORM_PACK32
			colorSpace = COLOR_SPACE_HDR10_ST2084_EXT
	Present Modes: count = 2
		PRESENT_MODE_FIFO_KHR
		PRESENT_MODE_IMMEDIATE_KHR
	VkSurfaceCapabilitiesKHR:
	-------------------------
		minImageCount = 2
		maxImageCount = 3
		currentExtent:
			width  = 512
			height = 512
		minImageExtent:
			width  = 1
			height = 1
		maxImageExtent:
			width  = 16384
			height = 16384
		maxImageArrayLayers = 1
		supportedTransforms: count = 1
			SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		currentTransform = SURFACE_TRANSFORM_IDENTITY_BIT_KHR
		supportedCompositeAlpha: count = 3
			COMPOSITE_ALPHA_OPAQUE_BIT_KHR
			COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR
			COMPOSITE_ALPHA_INHERIT_BIT_KHR
		supportedUsageFlags: count = 5
			IMAGE_USAGE_TRANSFER_SRC_BIT
			IMAGE_USAGE_TRANSFER_DST_BIT
			IMAGE_USAGE_SAMPLED_BIT
			IMAGE_USAGE_STORAGE_BIT
			IMAGE_USAGE_COLOR_ATTACHMENT_BIT

Device Groups:
==============
Group 0:
	Properties:
		physicalDevices: count = 1
			Apple M1 (ID: 0)
		subsetAllocation = 0

zsh: segmentation fault  vulkaninfo

**Comment by billhollings** [comment]
This is a Vulkan SDK issue. Please repost to the [Vulkan SDK Issues List](https://vulkan.lunarg.com/issue/home).
