### ISSUE TITLE
./fetchDependencies --macos ERROR

### ISSUE THREAD

**Issue by Kev-Long** [KhronosGroup/MoltenVK#1888]
========== Started building dependency libraries at 12:50:44 下午 ==========
Please be patient on first build
Building external libraries for platform macOS and destination macOS
2023-05-05 12:50:44.556 xcodebuild[63367:4912063] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
xcframework successfully written out to: /Users/sl/Git.opts/MoltenVK/External/build/Release/SPIRVCross.xcframework
xcframework successfully written out to: /Users/sl/Git.opts/MoltenVK/External/build/Release/SPIRVTools.xcframework
xcframework successfully written out to: /Users/sl/Git.opts/MoltenVK/External/build/Release/glslang.xcframework
/bin/sh: /Applications/Dev: No such file or directory
make: *** [clean] Error 127
Command PhaseScriptExecution failed with a nonzero exit code
note: Building targets in dependency order
** BUILD FAILED **

xcode14.  macpro M1
how to fix it?

**Comment by cdavis5e** [comment]
Where did you put Xcode? (I've got a sneaking feeling that you put it in a path with spaces, and this confused `make(1)`.)

**Comment by Kev-Long** [comment]
It locates in /Applications/Dev apps, but it's system default path

**Comment by cdavis5e** [comment]
> /Applications/Dev apps

That's what I thought. You actually cannot put Xcode in a folder whose name has spaces in it. (It's not Xcode itself so much as that `make(1)` and `sh(1)` have trouble with paths that have spaces in them when you don't quote them. This was what the error:
> ```
> /bin/sh: /Applications/Dev: No such file or directory
> ```
meant.) You'll have to move it into a folder that doesn't have a space in its name.

**Comment by Kev-Long** [comment]
> You'll have to move it into a folder that doesn't have a space in its name.
thank you !
