### ISSUE TITLE
Including binaries with MoltenVK GitHub releases

### ISSUE THREAD

**Issue by Steveice10** [KhronosGroup/MoltenVK#1891]
I have a use case where I'd want to download MoltenVK artifacts to use in a universal CI build. Currently I can just download the Vulkan SDK, but it's a bit large when I really just want to link against MoltenVK itself for these builds. I also can't use the corresponding commits' Actions builds as [GitHub specifies that artifacts only live for up to 90 days](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts), so long-term the URL isn't stable.

I wanted to query if adding the Actions artifacts to releases is something you could consider doing, as that way I could just set my download link to the latest release to fetch MoltenVK without all of the extra SDK components.

**Comment by billhollings** [comment]
Interesting scenario. 

Yes, adding a build artifact to MoltenVK releases would be helpful.

Although every PR to the MoltenVK repository creates and uploads binary artifacts, as you mention, these only exist for 90 days. That 90 days limit is set by our organization, Khronos. We could possibly investigate extending it.

Currently, we create official MoltenVK releases manually, to align with Vulkan SDK releases. If you are familiar with GitHub Actions, how do you suggest we upload an artifact to a release? And can that upload have a longer duration than 90 days?

If we can't figure this out, you can always download an artifact from the PR action of your choice, and cache it somewhere more permanent within your resources.

**Comment by Steveice10** [comment]
> Currently, we create official MoltenVK releases manually, to align with Vulkan SDK releases. If you are familiar with GitHub Actions, how do you suggest we upload an artifact to a release? And can that upload have a longer duration than 90 days?

The most straightforward way would be to just download the artifacts from the CI and upload them to the releases when you manually create them.

If you wanted to automate it, it’s also possible to set up an actions workflow to automatically cut releases when a commit is tagged, and as part of the workflow you can choose to build and upload artifacts to the release.

Example walking through this idea: https://trstringer.com/github-actions-create-release-upload-artifacts/

**Comment by Steveice10** [comment]
> I don't see a direct way to do this manually from the GitHub web UI.

It’s not something they give a direct button or anything for, no. Basically you’d go into the release commit’s actions summary, download the artifact, go to your release that you’re creating, and upload the artifact as a release asset.

> In the meantime, if you have the time and inclination to submit a PR to add a release-artifact workflow, please do so.

I’ll try to take a shot at it, I think it might be possible with conditionals to just tack the release bits on the end and share code with the normal action.

**Comment by Steveice10** [comment]
Opened a PR: https://github.com/KhronosGroup/MoltenVK/pull/1895

Could be preferable if there were still artifacts split out by platform, by the way, as if one only needs to compile for macOS that cuts the size down by 1/4 compared to the full bundle.

**Comment by billhollings** [comment]
> Opened a PR: #1895

Thanks!

> Could be preferable if there were still artifacts split out by platform, by the way, as if one only needs to compile for macOS that cuts the size down by 1/4 compared to the full bundle.

I wanted to be able to make it really easy to point people at a single-source of binary content for any build environment.

The MoltenVK distribution bundle is only used during app development, not at runtime. If an app dev is statically linking MoltenVK into their app, the app will only include what it's using. If an app dev is dynamically linking, they should only bundle one of the `libMoltenVK.dylib` files with the app. So for almost all users of this artifact bundle, distro size shouldn't matter.

For your external CI requirements, the full `tar/zip` file is about 107MB, and I didn't think it would be too much for an external CI to pull down and extract. If this does end up being a real problem, we can look to streamline. For instance,  the `MoltenVKShaderConverter` directory is not needed for almost everyone, and removing would shrink the distro to less that 1/3 of it's current size, so we could add a second `MoltenVK-only` artifact as an option (or maybe call them `MoltenVK` and `MoltenVK + ShaderConverter`).

**Comment by Steveice10** [comment]
> For your external CI requirements, the full `tar/zip` file is about 107MB, and I didn't think it would be too much for an external CI to pull down and extract.

GitHub itself lists the new combined artifact as ~400MB but I think you’re right as they actually list the size as that of the uncompressed contents instead of the zip size.

There could be a problem though in that, when you download artifacts to upload to a release in GitHub Actions you get them without that layer of compression, so the release asset is ~400MB. To keep the size down to the ~100MB you’re seeing we would either need to add compression to the tar or decompress it in the release workflow. Any thoughts?

**Comment by Steveice10** [comment]
Closing this out as the new release has artifacts, thanks!

**Comment by billhollings** [comment]
@Steveice10 Thanks for your contributions on this one!
