### ISSUE TITLE
Question: How to detect MVK version for config API changes?

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#1899]
Given the coming MVK config API change from `vkGetMoltenVKConfigurationMVK()` to  `vkGetMoltenVKConfiguration2MVK()`, what is the supported way going forward to detect the MVK version in client code?  My objective is to statically link to the correct MVK config API function based on the installed MoltenVK version.

1. Should we use `MVK_VERSION >= MVK_MAKE_VERSION(1,2,4)`, or
2. Should we use `MVK_CONFIGURATION_API_VERSION >= XX` (previously `VK_MVK_MOLTENVK_SPEC_VERSION`)?

FYI, I notice that you have not bumped the `MVK_CONFIGURATION_API_VERSION` for the coming release. If this will be the same between SDK 1.3.243.0 and the new version, can it be used to detect the config API changes?

**Comment by billhollings** [comment]
> Given the coming MVK config API change from `vkGetMoltenVKConfigurationMVK()` to `vkGetMoltenVKConfiguration2MVK()`, what is the supported way going forward to detect the MVK version in client code? My objective is to statically link to the correct MVK config API function based on the installed MoltenVK version.
> 
> 1. Should we use `MVK_VERSION >= MVK_MAKE_VERSION(1,2,4)`, or
> 2. Should we use `MVK_CONFIGURATION_API_VERSION >= XX` (previously `VK_MVK_MOLTENVK_SPEC_VERSION`)?

Use (1): `MVK_VERSION`. 

- `MVK_VERSION` provides the MoltenVK version (currently at `1.2.4` for next SDK) as an integer value, and increments just after a MoltenVK release is made for a Vulkan SDK release.
- `MVK_CONFIGURATION_API_VERSION` is incremented when the `MVKConfiguration` structure changes in some way. This is a way of telling the app dev that there are potentially new configuration options.

> FYI, I notice that you have not bumped the `MVK_CONFIGURATION_API_VERSION` for the coming release. If this will be the same between SDK 1.3.243.0 and the new version, can it be used to detect the config API changes?

Actually, `MVK_CONFIGURATION_API_VERSION` doesn't exist in previous MoltenVK releases (including previous SDK releases). And the original  now-deprecated `VK_MVK_MOLTENVK_SPEC_VERSION` was last updated in March, when one of the structures (probably `MVKConfiguration`) changed.

**Comment by SRSaunders** [comment]
Thanks very much for the explanation and intent regarding `MVK_VERSION` and `MVK_CONFIGURATION_API_VERSION`.

However, given your comments above regarding adding/removing config2, I won't need to detect `MVK_VERSION` for the time being.  Thanks for coming back and explaining your rationale for this.
