### ISSUE TITLE
VkPhysicalDeviceLimits has non-compliant value

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/MoltenVK#190]
The input_attachment API sample works fine on my MacBook AFAICT (Radeon Pro 560), but vulkaninfo reports a value of 0 for `maxPerStageDescriptorInputAttachments`.

If 0 were the actual limit, then the test would fail to create a valid descriptor set layout. This causes validation errors.

This value must be at least 4 on compliant Vulkan implementations, and I don't see a note about this in the **Known MoltenVK Limitations** section.

**Comment by billhollings** [comment]
Fixed in PR #191. Please retest and close.
