### ISSUE TITLE
Support for `VK_EXT_depth_clip_control`

### ISSUE THREAD

**Issue by IsaacMarovitz** [KhronosGroup/MoltenVK#1917]
Would it be possible to support `VK_EXT_depth_clip_control`? Ryujinx is adding a [fix](https://github.com/Ryujinx/Ryujinx/pull/5027) for Legend of Zelda: Tears of the Kingdom that uses this extension.

**Comment by oscarbg** [comment]
Why closed?

**Comment by IsaacMarovitz** [comment]
> Why closed?

Metal only supports depth from 0 -> 1
