### ISSUE TITLE
Add support for Vulkan Events if available

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#192]
The latest version of Metal now supports some form of behaviour similar to Vulkan Events.

**Comment by iOS4all** [comment]
@billhollings please can we add vulkan to ppsspp to could select it as a backend?
Of course I mean iOS devices

**Comment by billhollings** [comment]
@iOS4all 

Is this related to Vulkan Events? It sounds like this should be posted as a separate enhancement topic.

We definitely encourage the PPSSPP team integrate MoltenVK into their Vulkan implementation for iOS and macOS...and we would be happy to provide assistance.

**Comment by mbarriault** [comment]
It looks like events might be able to implemented with a combination of MTLSharedEvent (for CPU triggering) and MTLEvent (for stage synchronization).

**Comment by kristofferR** [comment]
The lack of Vulkan Events support in MoltenVK is currently blocking DXVK support:
https://github.com/doitsujin/dxvk/issues/1077#issuecomment-495954819

**Comment by billhollings** [comment]
SIGGRAPH generated some good feedback regarding interest in this feature.

I'll start working on this feature this week. If anyone has started work on this already...or has design ideas...please let me know. 

@cdavis5e

**Comment by cdavis5e** [comment]
I haven't started on this.

I have, however, looked at gfx-rs's implementation. They're just delaying command buffer submission, similar to what we do with `VkSemaphore`. We could probably have that as a fallback in case `MTLSharedEvent` isn't supported.

**Comment by billhollings** [comment]
Support added in #708.

**Comment by ovvldc** [comment]
So this can now be removed from the list of Known Limitations in https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md#limitations ?

That list its getting impressively short, by the way.

**Comment by billhollings** [comment]
> So this can now be removed from the list of Known Limitations

Oops! Good catch! I'll update the doc.
