### ISSUE TITLE
When vkCreateInstance is called, not all extensions are printed

### ISSUE THREAD

**Issue by DUOLabs333** [KhronosGroup/MoltenVK#1928]
What gets printed is 
```
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 86 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_K
```
Notice that not all extensions are printed. A `fflush` does not fix the problem either.

**Comment by billhollings** [comment]
Do you see any further `[mvk-info]` logging occurring later in your log?

If so, that MoltenVK log entry might be interrupted by an app log from another thread, and the remainder of it will occur later.

Or if not, I suspect what's happening is that your app is redirecting `stderr` somewhere (possibly even to `null`).

**Comment by DUOLabs333** [comment]
There was no other `[mvk-info]`, and `stderr` is not being redirected anywhere.

**Comment by billhollings** [comment]
> There was no other `[mvk-info]`, and `stderr` is not being redirected anywhere.

The log entry you show above is cut off in mid-stream, and all further MoltenVK logging is missing. So something in the app runtime environment is definitely getting in the way of logging to `stderr`.

**Comment by DUOLabs333** [comment]
I was going to test vkcube, but I use homebrew's distribution, and I don't want to have to download the 10G XCode to compile it myself.

**Comment by DUOLabs333** [comment]
I was gong to try it, but I didn't want to download the 10G XCode just to compile it.

**Comment by billhollings** [comment]
> I was gong to try it, but I didn't want to download the 10G XCode just to compile it.

Where are you getting MoltenVK binaries from? If from the Vulkan SDK, the SDK also includes a built Cube app (and others). I believe the SDK builds disable logging, so you might have to set the environment variable `MVK_CONFIG_LOG_LEVEL=3`n when running the apps.

But I wouldn't put too much effort into running those demos to confirm logging. MoltenVK logging is working. I use it every day for development and debugging. In your situation, something environmental must be getting in the way.

**Comment by DUOLabs333** [comment]
Interesting, I installed `vulkan-tools` from homebrew, and I get `vkEnumerateInstanceExtensionProperties failed to find the VK_KHR_surface extension`.

**Comment by DUOLabs333** [comment]
However, I can throw out the possibility that some other thread is hijacking the stderr stream because if I add a `fprintf` statement immediately after the createInstance call, it works.

**Comment by DUOLabs333** [comment]
As part of further experiments, I call createInstance earlier and earlier in my code, but the same thing happens. In fact, if I have two calls in two separate places, I will get two copies of the same message, both cut off.

**Comment by DUOLabs333** [comment]
Oh, I figured out the problem --- for some reason, stderr has a buffer of 1024, and it would truncate anything else.

**Comment by billhollings** [comment]
> Oh, I figured out the problem --- for some reason, stderr has a buffer of 1024, and it would truncate anything else.

Ah. I'm glad you figured it out. It definitely had the feel of an environmental issue. Good work!

**Comment by DUOLabs333** [comment]
However, when I try to make a string of size of 1023, I actually get a string of size 984, which is weird. However, even if the bugger size is at fault, that doesn't explain why it only shows up in my application.

**Comment by DUOLabs333** [comment]
Ok, found out the real reason: I was working on QEMU, and `-nographic` is the option that caused this issue. Specifically, this line: `add_device_config(DEV_SERIAL, "mon:stdio");`.
