### ISSUE TITLE
Segmentation fault in Vulkan CTS in MVKGraphicsPipeline::initShaderConversionConfig

### ISSUE THREAD

**Issue by zhuowei** [KhronosGroup/MoltenVK#1929]
To reproduce:

- build Vulkan CTS (I'm using https://github.com/KhronosGroup/VK-GL-CTS/commit/356e6d2f87965794ce05dfedd2ce0e219485ad60)
- setup MoltenVK from the Vulkan 1.3.250.0 SDK
- create `failing_test.txt` with:

```
dEQP-VK.draw.dynamic_rendering.primary_cmd_buff.offscreen_viewport.x_on_screen_y_off_screen_negative
```

- run the CTS:

```
runcts -o deqp_5.txt failing_test.txt
```

I get:

```
Testing started at 02:14:29 am
runcts: line 125:  2352 Segmentation fault: 11  "./deqp-vk" --deqp-log-images=disable --deqp-log-shader-sources=disable --deqp-caselist-file="${caselist_file}" >&"${results_file}"
Testing complete in 0 seconds
```

Crash log: https://gist.github.com/zhuowei/17df734a438fc76061700a8194d56307

I'm currently using a really ancient macOS 13 beta 1. I can try installing a fresh macOS release and see if that fixes it, but I doubt it since this is happening inside MoltenVK itself?

**Comment by galad87** [comment]
Running the first beta of a major macOS release after one years is weird. The first beta is so buggy that it's a miracle it runs at all. I am not related to MoltenVK in any way, but it would be better to test on the latest stable release.

**Comment by zhuowei** [comment]
> it would be better to test on the latest stable release
I'll install a newer macOS and re-test tomorrow.

**Comment by billhollings** [comment]
> I'll install a newer macOS and re-test tomorrow.

Not to say you shouldn't upgrade in general, but you may not need to do so for this alone.  😉

Current CTS is known to tigger crashes in MoltenVK, and we're looking into it.
