### ISSUE TITLE
Problem with simple polygon mesh that does not get drawn, except if useless vkCmdBindPipeline and vkCmdBindDescriptorSets commands are recorded

### ISSUE THREAD

**Issue by elmar-k** [KhronosGroup/MoltenVK#1931]
Dear MoltenVK-Team,

many thanks for your help with the previous issue https://github.com/KhronosGroup/MoltenVK/issues/1811 , I now upgraded my MacBook Air M1 (2020) to MacOS Ventura 13.4 and continued testing. The good news is that our extensive Vulkan testsuite (which takes 45 minutes) ran through without another VK_ERROR_DEVICE_LOST. Comparing the screenshots with their counterparts on PC, I found a few graphical glitches, which are hopefully all due to the same issue(s).

Here I report the main problem: Some polygon meshes are not drawn or invisible, even though the draw commands are recorded to the command buffer correctly. I spent a few hours to narrow the problem down and found the following interesting details:

This command sequence to draw the mesh doesn't work, nothing is visible:

vkCmdBindPipeline(VK_PIPELINE_BIND_POINT_GRAPHICS,Pipeline0);
vkCmdBindDescriptorSets(combuff,VK_PIPELINE_BIND_POINT_GRAPHICS,Layout0,0,1,&Set0,0,NULL); 
vkCmdBindDescriptorSets(combuff,VK_PIPELINE_BIND_POINT_GRAPHICS,Layout0,1,1,&Set1,0,NULL); 
vkCmdPushConstants(combuff,...)
vkCmdDrawIndexed(combuff,....)

But I can make the mesh magically appear correctly if I record three additional, useless commands before, that bind a different pipeline that is never used, since nothing is drawn with this Pipeline1: 

vkCmdBindPipeline(VK_PIPELINE_BIND_POINT_GRAPHICS,Pipeline1);
vkCmdBindDescriptorSets(combuff,VK_PIPELINE_BIND_POINT_GRAPHICS,Layout1,0,1,&Set0,0,NULL); 
vkCmdBindDescriptorSets(combuff,VK_PIPELINE_BIND_POINT_GRAPHICS,Layout1,1,1,&Set1,0,NULL); 
vkCmdBindPipeline(VK_PIPELINE_BIND_POINT_GRAPHICS,Pipeline0);
vkCmdBindDescriptorSets(combuff,VK_PIPELINE_BIND_POINT_GRAPHICS,Layout0,0,1,&Set0,0,NULL); 
vkCmdBindDescriptorSets(combuff,VK_PIPELINE_BIND_POINT_GRAPHICS,Layout0,1,1,&Set1,0,NULL); 
vkCmdPushConstants(combuff,...)
vkCmdDrawIndexed(combuff,....)

All three extra commands are needed, binding only Pipeline1 is not enough, and binding only the descriptor sets with Layout1 is also not enough.

I'm now preparing a minimal test application and will send the download link to your support email separately in a few hours.

Best regards and many thanks for your help,
Elmar

**Comment by billhollings** [comment]
Thanks for reporting this, for your debugging work, and for the sample app.

This might be related to #1839.

**Comment by elmar-k** [comment]
Thanks for the hint. I read through #1839, and I'm aware that it's not exactly clear according to the Vulkan specs when descriptor sets have to be rebound. Binding costs performance, so I avoid it when possible. But in the code example above and also in the test application I sent, I deliberately rebind the descriptor sets after each vkCmdBindPipeline to exclude this potential cause of problems.

**Comment by elmar-k** [comment]
Here is an update, just in case you guys haven't already fixed the problem for the forthcoming SDK release:
The good news is that the issue is most likely *not* caused by something inside Metal that would require Apple's attention.
I now tried the various Vulkan SDKs available for download, and found that the problem appeared between SDK 1.3.216 (still OK) and 1.3.224 (bug present). So I could "solve" the issue by simply replacing the libMoltenVK.dylib with an older one from SDK 1.3.216. Hopefully this helps to trace the bug, by looking what changed between 216 and 224.
Best regards and many thanks for your help,
Elmar

**Comment by billhollings** [comment]
> I'm now preparing a minimal test application and will send the download link to your support email separately in a few hours.

I just tried running the sample app, but unfortunately am hitting a snag. Screenshot and runtime log here:

![Screenshot 2023-08-16 at 11 23 03 AM](https://github.com/KhronosGroup/MoltenVK/assets/356402/1dabba94-5943-43ef-973d-49cded67519c)

[yasara.log](https://github.com/KhronosGroup/MoltenVK/files/12360956/yasara.log)

**Comment by elmar-k** [comment]
Sorry for that, a bug fix has just been sent to your support email.

**Comment by billhollings** [comment]
PR #2001 (A Coding Odyssey) fixes this issue. Please retest with latest MoltenVK and close this issue if the fix is successful.

**Comment by elmar-k** [comment]
Wow, biggest thanks for taking Ulysses' job and hunting down this issue. I compiled the latest Github snapshot (great build system, BTW), and our 45-minute Vulkan testsuite ran through fine. Comparing 172 screenshots with the PC counterparts, almost all differences disappeared with the fix, and the remaining two differences are most likely a bug on our side. Thanks again!
