### ISSUE TITLE
Add support for/ expose EXT_image_drm_format_modifier and EXT_queue_family_foreign device extensions

### ISSUE THREAD

**Issue by DUOLabs333** [KhronosGroup/MoltenVK#1934]
I'm working on getting Vulkan working on virtual machines on M1 devices. However, for this to work, EXT_image_drm_format_modifier and EXT_queue_family_foreign device need to be exposed. However, I don't know whether these extensions are too Linux-specific to be implemented by MoltenVK.

**Comment by aarononeal** [comment]
@DUOLabs333, I'm interested in your findings. Any luck getting Vulkan support in a VM or working around the `VK_EXT_image_drm_format_modifier` dependency of VirGL?

**Comment by DUOLabs333** [comment]
I actually gave up trying to retrofit VirGL's venus renderer for MacOS, and wrote my own (found here: https://github.com/DUOLabs333/vulkan-stream). As it turns out, the extension is not needed at all (except for maybe some edge case), which is why I closed the issue. So, after around 2 months, I can successfully use Vulkan in a VM. However, making it *performant* is harder.
