### ISSUE TITLE
Atomic image operations with Metal 3.1

### ISSUE THREAD

**Issue by spnda** [KhronosGroup/MoltenVK#1939]
Metal 3.1 has added support for various atomic operations on 1D/2D/3D textures. These are a few quotes from the [Metal language specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf):
> [6.12] Metal 3.1 introduces new atomic texture member functions supported on 1D texture, 1D texture array, 2D texture, 2D texture array, 3D texture, and texture buffer for int, uint, ulong color types:
• atomic_load - atomic load from a texture,
• atomic_store – atomic store to a texture,
• atomic_exchange - atomic exchange a value for a texture,
• atomic_compare_exchange_weak - atomic compare and exchange in a texture,
• atomic_fetch_op_explicit – atomic fetch and modify where op can be add, and,
max, min, or, sub, or xor for int and uint color type.
• atomic_max - atomic max in a texture for ulong color type.
• atomic_min - atomic min in a texture for ulong color type.

Note that images must be marked with `MTLTextureUsageShaderAtomic`.

Is this enough to cover what is required by the core Vulkan spec. Afaik Vulkan requires atomic image operations on compute shaders by default, which I guess was previously not possible with MoltenVK? I guess this would only require some modifications of SPIRV-Cross, but I don't know how that works so not sure if I wanna do that myself.

I think `VK_EXT_shader_image_atomic_int64` is however not supportable, as the Metal spec wants the RG32Uint format for 64-bit integers, whereas the Vulkan extension uses the R64 formats: 
> Since Metal 3.1, texture support atomic functions for element T where T is int, uint,or ulong:
• When the element T is int or uint, the texture on the Metal needs to be either
MTLPixelFormatR32Uint, or MTLPixelFormatR32Sint,
• When the element T is ulong, the texture on the Metal needs to be
MTLPixelFormatRG32Uint.

Somewhat related: Metal 3.1 also supports `ulong4` sparse textures now it seems, as `sparse_color` now supports `ulong` as a template parameter. It also supports `bfloatn` now (16-bit "brain float").

**Comment by billhollings** [comment]
Additional discussion in #1938.

**Comment by spnda** [comment]
@billhollings Has this been addressed by #2164? I think we can close this now.

**Comment by billhollings** [comment]
> @billhollings Has this been addressed by #2164? I think we can close this now.

@js6i What are you thoughts? Do we now cover enough to satisfy this enhancement request?

**Comment by js6i** [comment]
> > @billhollings Has this been addressed by #2164? I think we can close this now.
> 
> @js6i What are your thoughts? Do we now cover enough to satisfy this enhancement request?

I would say so, although that's up to the requester.. One thing that's (still) not supported is atomics on cube / cube array textures. Maybe doable, I just haven't looked into it.

**Comment by billhollings** [comment]
> I would say so, although that's up to the requester.

Thanks. It was the requestor that was asking. 

@spnda Looks like it's fine for you to close this if that makes sense to you.

**Comment by oscarbg** [comment]
cube texture atomics added in Metal 4 and Apple10 faimly but SPIRV-Cross is not yet ready (created issue), so for MoltenVK support, SPIRV-Cross will need to be updated  once fixed: https://github.com/KhronosGroup/SPIRV-Cross/issues/2560
