### ISSUE TITLE
Update SPIRV-Cross to fix compilation regression on some shaders

### ISSUE THREAD

**Issue by rcombs** [KhronosGroup/MoltenVK#1941]
KhronosGroup/SPIRV-Cross@17ddd5912e91a8463945cddee6ec25dc81474c0c fixes a major regression introduced in KhronosGroup/SPIRV-Cross@41007cdc7d9c3a1f9b61e307d149f94a68fa3c9c, which caused MSL compilation errors when shaders had particular patterns of constants. This breaks libplacebo and mpv.

I'm not sure if this is the right place to ask for the version to be bumped; if it's not, please point me in the right direction!

**Comment by billhollings** [comment]
Yup...this is the right place. Thanks for the info.

Feel free to submit a PR here if you want, otherwise, I'll take care of it soon.
