### ISSUE TITLE
Is it possible to use descriptor indexing on Intel Iris Pro 640 graphics running on macOS Ventura (Metal 3)?

### ISSUE THREAD

**Issue by GasimGasimzada** [KhronosGroup/MoltenVK#1970]
I have a Vulkan engine that uses descriptor indexing with `UPDATE_AFTER_BIND` descriptors for combined image samplers and storage images. I have created a descriptor set with 1000 descriptors.

On MoltenVK, I keep getting pipeline compilation errors with regards to limits:

> Max per-stage sampler bindings count (1000) exceeds maxPerStageDescriptorUpdateAfterBindSamplers limit (16)
> Max per-stage sampled image bindings count (1000) exceeds maxPerStageDescriptorUpdateAfterBindSampledImages limit (128)
> Max per-stage storage image bindings count (1000) exceeds device maxPerStageDescriptorUpdateAfterBindStorageImages limit (8)

I have defined `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` with hope that the limits would be higher (they were all `16` , initially). 

Is this a limitation of the GPU or am I missing something in configuration?

**Comment by billhollings** [comment]
> Is this a limitation of the GPU

Yes. Support for the larger quantities for bindless resources is dependent on the GPU supporting Tier2 Metal Argument Buffers. According to the [Metal docs](https://developer.apple.com/documentation/metal/buffers/about_argument_buffers?language=objc): 

> Tier 2 argument buffers are supported by macOS devices with a discrete GPU and by the A13 GPU.

**Comment by GasimGasimzada** [comment]
Makes sense thank you!
