### ISSUE TITLE
How does MoltenVK achieve Full Bindless Support?

### ISSUE THREAD

**Issue by JonahGoldsmith** [KhronosGroup/MoltenVK#1971]
Can someone please explain how MoltenVk is able to allow something like 
`[[vk::binding(0, 1)]] ByteAddressBuffer bindless_buffers[];

[[vk::binding(0, 1)]] RWByteAddressBuffer bindless_rwbuffers[];`

But when programming in Metal API, aliasing like this is not allowed? And ByteAdressBuffers in Vulkan could potentially hold multiple different struct types inside of it and then be casted to the correct type. How is this achieved in MoltenVk? Does it just convert it at the IR level to the correct types since Metal doesn't support type casting on device* buffers? 

Would really love if someone was able to explain this as I am very curious to fully understand how MoltenVk works...

Side note - currently working with Metal Shader Converter to convert DirectX12 code to Metal (including mesh shaders and ray tracing) and I want to see if some of the concepts will be able to help MoltenVk support those extensions... but first I need to keep learning how MoltenVk works...)

**Comment by K0bin** [comment]
MoltenVK does not support bindless.

**Comment by JonahGoldsmith** [comment]
> MoltenVK does not support bindless.

even when using MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS? I thought it was possible as long as argument buffers are turned on. When I run a Vulkan test it shows me that I can have bindless storage buffers, and most other types...

**Comment by K0bin** [comment]
The array limits are very low and as far as I know, it doesn't support PARTIALLY_BOUND.

**Comment by billhollings** [comment]
> even when using MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS? I thought it was possible as long as argument buffers are turned on. When I run a Vulkan test it shows me that I can have bindless storage buffers, and most other types...

MoltenVK does support bindless resources and descriptor indexing. The larger bindless resource quantities are supported if the GPU supports Tier2 Metal Argument Buffers.

There is a significant enhancement under development for improving performance and features of bindless resources in MoltenVK.

> Side note - currently working with Metal Shader Converter to convert DirectX12 code to Metal (including mesh shaders and ray tracing) and I want to see if some of the concepts will be able to help MoltenVk support those extensions... but first I need to keep learning how MoltenVk works...)

There is also a significant enhancement planned to integrate Apple's Shader Converter tech, including Geom & Tess shaders. Feel free to participate.

See the [MoltenVK Enhancement Roadmap](https://github.com/KhronosGroup/MoltenVK/issues/1975) for more info on these coming enhancements.

**Comment by JonahGoldsmith** [comment]
Hey thank you for the answer @billhollings! Since I see you are the one working on the updated bindless support I wanted to ask another question. How is it possible that you guys support the bindless storage buffers? Do you use "device void*" in the argument buffers and save offsets into a MTLBuffer or is there some other technique you use to enable that feature?

**Comment by billhollings** [comment]
> How is it possible that you guys support the bindless storage buffers?

When you run your app, if you set the following environment variables:

```
MVK_CONFIG_LOG_LEVEL=3
MVK_DEBUG=1
```

then MoltenVK will log the shader conversions, including the resulting MSL source code, and you'll be able to see from that how the MSL binds resources. You can run this with or without the `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` environment variable set, so you can observe the shader differences when using bindless resources.

**Comment by JonahGoldsmith** [comment]
So i see that a ByteAddressBuffer array essentially gets converted into an array of raw bytes in the argument buffer. This is what I assumed. The part that confuses me is how we are able to upload different buffers into this one array. If i have two storage buffers of two different sizes how does the host code and shader code know how big the struct is? If I load a struct at index one of the array and load a different struct at index 2 thats a little bit bigger how does the implementation differentiate between the two if its just raw bytes?
