### ISSUE TITLE
Vulkan SDK release feature cut-off Monday August 14

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#1973]
LunarG is planning the next Vulkan SDK release.

A MoltenVK SDK release for this Vulkan SDK release will be made Tuesday August 15.

MoltenVK PRs approved by Monday August 14 will be included in this release.

@cdavis5e 
@spnda 
@AntarticCoder 
@richard-lunarg 
@KarenGhavam-lunarG

**Comment by AntarticCoder** [comment]
Do you know when the next cut off would be?

**Comment by billhollings** [comment]
In broad terms, the SDK cycle is about 2 months.

More specifically, based on LunarG's SDK current roadmap, the next MoltenVK cutoff will likely be Sept 25.

**Comment by italomandara** [comment]
I hope the new Vulkan SDK release fixes this: https://github.com/KhronosGroup/MoltenVK/issues/1974

**Comment by AntarticCoder** [comment]
@billhollings Thanks

**Comment by oscarbg** [comment]
Any planned delay on the release?

**Comment by richard-lunarg** [comment]
The current SDK cycle has been delayed. Earliest release date is a week after SigGraph (August 21st).

**Comment by billhollings** [comment]
Unfortunately, delays were encountered in upstream libraries for the SDK. 

This issue has been updated above with new date expectations.

@cdavis5e
@spnda
@AntarticCoder
@richard-lunarg
@KarenGhavam-lunarG
