### ISSUE TITLE
MoltenVK supposedly inherited a regresson from Vulkan SDK

### ISSUE THREAD

**Issue by italomandara** [KhronosGroup/MoltenVK#1974]
Some games in crossover + dxvk + moltenVK won't launch.
error:
`Assertion failed!`
`File: /..wineddlls/winevulkan/loader_thunks.c
Line: 3133`

example:
<img width="443" alt="Screenshot 2023-07-10 at 14 30 22" src="https://github.com/KhronosGroup/MoltenVK/assets/12135454/77267a89-1b49-4dda-a1bd-c792c3918a66">

This issue introduced in april 2023 is mentioned [here](https://github.com/xenia-canary/xenia-canary/issues/158) in a vulkan based project on linux not sure if it's helpful to spot when this was introduced in vulkan SDK... please let me know if this needs to be raised somewhere else.

**Comment by italomandara** [comment]
Using MVK 1.2.3 or earlier will fix the issue for now.

**Comment by italomandara** [comment]
> FWIW That assert usually means there was a crash in the Vulkan driver (MoltenVK in this case).

So not necessarily related to Vulkan SDK? Well, that'd be better, I could gather more info and this could be fixed in this repo potentially.

**Comment by billhollings** [comment]
Do we have any intel on what the regression is?

**Comment by italomandara** [comment]
> Do we have any intel on what the regression is?

I will gather more info, but as @K0bin pointed it could be just MVK's Vulkan loader crashing.

**Comment by italomandara** [comment]
Closing this since it is currently working fine in the latest main branch
