### ISSUE TITLE
VkPhysicaDeviceLimits::maxComputeWorkGroupInvocations returning incorrect value

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/MoltenVK#198]
Calling vkGetPhysicalDeviceProperties and looking at `pProperties->limits.maxComputeWorkGroupInvocations`, on my GPU (Intel HD 5300) is returning 1024. However, attempting to use a compute kernel with this size throws an error confirming that the max invocations is actually 256.

For additional reference, `pProperties->limits.maxComputeWorkGroupSize[]` returns (1024,1024,1024), also believed to be incorrect but the total invocations issue prevents verifying this.

I've verified with OpenCL that my GPU's limits are (256,256,256), with local threadgroup total size capped at 256.

The full reported error is

    -[MTLDebugComputeCommandEncoder _validateThreadsPerThreadgroup:]:949: failed assertion `(threadsPerThreadgroup.width(1024) * threadsPerThreadgroup.height(1) * threadsPerThreadgroup.depth(1))(1024) must be <= 256. (kernel threadgroup size limit)'

**Comment by billhollings** [comment]
Fixed in PR #200. Please retest and close.

**Comment by mbarriault** [comment]
Confirmed, now reporting the correct physical device limits. Thanks!
