### ISSUE TITLE
Support VK_EXT_custom_border_color

### ISSUE THREAD

**Issue by Steveice10** [KhronosGroup/MoltenVK#1987]
The upcoming Vulkan backend for the [Citra](https://github.com/citra-emu/citra) emulator uses VK_EXT_custom_border_color to implement border colors on the guest system GPU. Without the extension some games experience noticable visual glitches, so it would be ideal if this could be implemented in MoltenVK.

Metal seems to have a property for this: https://developer.apple.com/documentation/metal/mtlsamplerdescriptor/2092299-bordercolor

**Comment by cdavis5e** [comment]
> Metal seems to have a property for this: https://developer.apple.com/documentation/metal/mtlsamplerdescriptor/2092299-bordercolor

That's for the fixed "Model T-style" border color that is already supported in base Vulkan 1.0. Custom border colors need an undocumented SPI.

**Comment by Steveice10** [comment]
Ah, I misunderstood the docs on that as examples and didn't realize there were only 3 possible fixed values. That's unfortunate.

**Comment by Steveice10** [comment]
We managed to implement an emulated version of what we need in shaders. Will leave this open though as it could be a useful extension for others.
