### ISSUE TITLE
Flickering horizontal line output on macOS 12

### ISSUE THREAD

**Issue by Steveice10** [KhronosGroup/MoltenVK#1990]
Over in Citra we've been getting reports since starting testing for our new Vulkan backend that specifically macOS 12 users are frequently getting strange flickering horizontal line video output covering the entire render area.

I don't know if anyone has tested on macOS 11 (our minimum), but no one on macOS 13 or above has encountered this issue. We haven't seen it on any other platform either.

We have tried enabling the Metal validation layer and didn't get any errors out, and we don't think any of the Vulkan validation errors we've seen are related. Primarily because they've come and gone over the course of development on this backend, but this issue remains constant.

I'm not sure if this is a MoltenVK issue, a Metal bug, or something about our usage of Vulkan, but I figured it would be a good idea to reach out and see if you guys have any insights into why this might be happening.

Issue describing the problem: https://github.com/citra-emu/citra/issues/6562

Source with Vulkan support: https://github.com/GPUCode/citra/tree/vulkan-but-better

Builds with Vulkan support: https://github.com/citra-emu/citra-canary/releases

Example screenshot from a user:
![image](https://github.com/KhronosGroup/MoltenVK/assets/1269164/54849e70-a16b-4480-bd35-559c9a27428c)

**Comment by Steveice10** [comment]
There's also a video someone sent us a while back demonstrating the issue **(warning: rapid flashing)**:

https://github.com/KhronosGroup/MoltenVK/assets/1269164/d69a2f4a-2fd2-4328-ae97-d6dc0c1b7ff3

**Comment by billhollings** [comment]
Is this happening across multiple users, or just the user that filed the Citra issue you posted above?

What value are you setting in `VkSwapchainCreateInfoKHR::presentMode`? Using `VK_PRESENT_MODE_IMMEDIATE_KHR` may sometimes cause tearing.

**Comment by Steveice10** [comment]
> Is this happening across multiple users, or just the user that filed the Citra issue you posted above?
> 
> What value are you setting in `VkSwapchainCreateInfoKHR::presentMode`? Using `VK_PRESENT_MODE_IMMEDIATE_KHR` may sometimes cause tearing.

It’s happening to several users, always ones running macOS 12.

If the user has Vsync enabled we use FIFO. Otherwise we check for Mailbox, and if that isn’t present we use Immediate. According to the user log they have Vsync enabled, so they should be using FIFO.

**Comment by Steveice10** [comment]
If you want a test case by the way, Citra has downloads with Vulkan support available here (the downloads labeled “macos”): https://github.com/citra-emu/citra-canary/releases

Click the API toggle in the bottom left of the window to switch it to Vulkan, then you can load in any piece of freely available homebrew, for example: https://smealum.github.io/3dscraft/

**Comment by billhollings** [comment]
> According to the user log they have Vsync enabled, so they should be using FIFO.

Hmmm...and from the MoltenVK log in the user report to Citra, you are using 3 swapchain images. Is that correct?

There's certainly nothing that MoltenVK would be doing to interfere with rendering and presenting in a way that would cause this kind of interlacing or tearing (and particularly only on macOS 12). 

If you've generally eliminated other environmental concerns, based on it happening to multiple users, the only thing I can think of is that we're encountering some kind of bug with the compositor on macOS 12...although I never encountered anything like this in the year or so of developing and testing MoltenVK on macOS 12. And I can't find anything else indicating such an issue via online searches.

**Comment by Steveice10** [comment]
> Hmmm...and from the MoltenVK log in the user report to Citra, you are using 3 swapchain images. Is that correct?

Yes that’s correct.
 
> There's certainly nothing that MoltenVK would be doing to interfere with rendering and presenting in a way that would cause this kind of interlacing or tearing (and particularly only on macOS 12).
> 
> If you've generally eliminated other environmental concerns, based on it happening to multiple users, the only thing I can think of is that we're encountering some kind of bug with the compositor on macOS 12...although I never encountered anything like this in the year or so of developing and testing MoltenVK on macOS 12. And I can't find anything else indicating such an issue via online searches.

Yeah the part that’s stumped me is how it’s only happening on macOS 12, which led me to believe that there must be some sort of difference like some missing API capability, Metal bug, etc that could cause this. No other platform or macOS version is experiencing this problem.

I wish I had a macOS 12 device to debug this on but I don’t, and none of the rest of the dev team uses a Mac, as far as I know.

**Comment by Steveice10** [comment]
One extra detail, I had a user try out disabling VSync to see if a different present mode would change things, but it seems it did not.

**Comment by cdavis5e** [comment]
Since macOS 13 has been out for a year and Apple is now working on macOS 14, I don't expect this problem to ever get fixed on 12. I fear at this point there may be nothing anyone can do short of recommending upgrading to the latest macOS.

**Comment by Steveice10** [comment]
Did some debugging on an M1 Mac cloud instance running macOS 12 but unfortunately didn’t get anywhere with it yet. Only difference I noticed in the debugger was that on macOS 12 it only had 2 textures marked as CAMetalLayer drawables under All Resources whereas my local machine had 5. They both looked correct though, nothing like the actual bugged window contents.

The blit operation in the submit also didn’t have any destination show under Bound Resources and there was no [MTLDrawable present] at the end, not sure if that’s just the older Xcode compatible with macOS 12 having less information in the debugger.

**Comment by Steveice10** [comment]
Upgraded to macOS 12.6.8 and Xcode 14.2 and now I'm noticing something of note. On frames when the window contents are glitched, the debugger shows "Invalid" for the format on the CAMetalLayer Display Drawable info in the top right.

There's no swapchain recreation between these frames, and we're using vkGetPhysicalDeviceSurfaceFormatsKHR to resolve the pixel format to use, so any idea what might be happening here?

Bad:
<img width="681" alt="Screenshot 2023-08-26 at 3 13 28 PM" src="https://github.com/KhronosGroup/MoltenVK/assets/1269164/29de36e6-4286-4df2-b0e1-5c9aa07d153d">

Good:
<img width="681" alt="Screenshot 2023-08-26 at 3 14 27 PM" src="https://github.com/KhronosGroup/MoltenVK/assets/1269164/5c41b4e5-ec18-4577-b208-fc27fc120101">

**Comment by billhollings** [comment]
> the debugger shows "Invalid" as part of the format on the CAMetalLayer Display Drawable

That's good detective work!

PR #2012 checks for an invalid `CAMetalDrawable` format, and first attempts a few times to extract a different drawable to find one with a valid forma, and if that doesn't work, it returns `VK_ERROR_OUT_OF_DATE_KHR` from `vkQueuePresentKHR()` 
  and `vkAcquireNextImageKHR()`. If your app checks for that error and recreates the swapchain, that might help force the system to get the drawables right.

Please retest with the latest MoltenVK that includes that PR, and close this issue if it fixes the problem.

**Comment by Steveice10** [comment]
Thanks, I’ll see if I can get a build set up with the PR change included and provide it to someone who can test. Will get back to you as soon as able.

**Comment by Steveice10** [comment]
Had someone on macOS 12 test with the PR's CI artifacts and unfortunately the flickering issue is still present.
