### ISSUE TITLE
SHA mismatch gnuplot

### ISSUE THREAD

**Issue by GaryEBenson** [KhronosGroup/MoltenVK#2000]
brew install gnuplot

==> Downloading https://github.com/KhronosGroup/MoltenVK/archive/v1.2.5.tar.gz
==> Downloading from https://codeload.github.com/KhronosGroup/MoltenVK/tar.gz/refs/tags/v1.2.5
##=O=#   #                                                                                                                     
Error: gnuplot: SHA256 mismatch
Expected: b4468aee1abf7dcc79dc12a817b1eb3b8fcef9e44f547f32ea1fdcd7a9d2c8ba
  Actual: 946d8f0e7ae3b47774b03a610d3a3e7e4bcbef3e667e1362325936839035a115
    File: /Users/gary/Library/Caches/Homebrew/downloads/e385609ede51ecc4242c3cae13cd0c23c373679bebceb3089b5758459f72cc0b--MoltenVK-1.2.5.tar.gz
To retry an incomplete download, remove the file above.

Direct download of file has "Actual" SHA256.

**Comment by cdavis5e** [comment]
More fallout from #1998, it looks like. For now, just have Homebrew update the expected SHA-256 hash for MoltenVK v1.2.5.
