### ISSUE TITLE
Metal validation error when accessing storage image uniform atomically without argument buffers

### ISSUE THREAD

**Issue by Steveice10** [KhronosGroup/MoltenVK#2005]
We have a block of code in our fragment shaders to emulate shadow rendering that looks like the following:
```
layout(set = 2, binding = 6, r32ui) uniform uimage2D shadow_buffer;

...

void main() {
    ...
    uint d = uint(clamp(depth, 0.0, 1.0) * float(0xFFFFFF));
    uint s = uint(last_tex_env_out.g * float(0xFF));
    ivec2 image_coord = ivec2(gl_FragCoord.xy);

    uint old = imageLoad(shadow_buffer, image_coord).x;
    uint new1;
    uint old2;
    do {
        old2 = old;

        uvec2 ref = DecodeShadow(old);
        if (d < ref.x) {
            if (s == 0u) {
                ref.x = d;
            } else {
                s = uint(float(s) / (shadow_bias_constant + shadow_bias_linear * float(d) / float(ref.x)));
                ref.y = min(s, ref.y);
            }
        }
        new1 = EncodeShadow(ref);
    } while ((old = imageAtomicCompSwap(shadow_buffer, image_coord, old, new1)) != old2);
    ...
}
```

Our shadow buffer is R8G8B8A8Unorm, has the storage usage bit, we're using a R32Uint view, and it should be suitable to be used this way. We don't get any Vulkan validation errors from our usage.

Under the default MoltenVK configuration, this is causing us to hit the following Metal validation error:
```
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5775: failed assertion `Draw Errors Validation
Fragment Function(main0): missing buffer binding at index 7 for shadow_buffer_atomic[0].
```

Some further details about the images this game uses for shadow rendering:
```
Image 1:
 - Width: 256, Height: 256, Levels: 4
 - Aspect: { Color }, Access: { ShaderRead | ShaderWrite | TransferRead | TransferWrite }, Pipeline Stage: { FragmentShader | ComputeShader | Transfer }
 - Native: R8G8B8A8Unorm, Usage: { TransferSrc | TransferDst | Sampled | Storage | ColorAttachment }

Image 2:
 - Width: 256, Height: 256, Levels: 5
 - Aspect: { Color }, Access: { ShaderRead | ShaderWrite | TransferRead | TransferWrite }, Pipeline Stage: { FragmentShader | ComputeShader | Transfer }
 - Native: R8G8B8A8Unorm, Usage: { TransferSrc | TransferDst | Sampled | Storage | ColorAttachment }
```

Any ideas why this would work with argument buffers but not without? This is our descriptor layout: https://github.com/GPUCode/citra/blob/vulkan-but-better/src/video_core/renderer_vulkan/vk_pipeline_cache.cpp#L55-L81

I'm a bit hesitant to just enable argument buffers without knowing why it isn't working without them, as I've heard support is still beta quality.

**Comment by cdavis5e** [comment]
Prior to Metal 3.1, Metal didn't support atomics on textures. So Epic Games (yes, that Epic, the one behind Unreal Tournament and Fortnite) graciously upstreamed a change to SPIRV-Cross to emulate this by operating on a buffer underlying the image. MoltenVK is supposed to detect this situation and bind the underlying buffer, but it looks like we're binding the wrong buffer slot. This is nontrivial without argument buffers, because buffers and textures have separate numbering spaces, and we also have to account for other uses like vertex buffers. With argument buffers, this becomes trivial, so the buffer is bound correctly.

Metal supports texture atomics *now*, so one of these days, I should go back in SPIRV-Cross and use that, so we don't need that extra buffer anymore, at least on macOS 14.

**Comment by Steveice10** [comment]
> Prior to Metal 3.1, Metal didn't support atomics on textures. So Epic Games (yes, that Epic, the one behind Unreal Tournament and Fortnite) graciously upstreamed a change to SPIRV-Cross to emulate this by operating on a buffer underlying the image. MoltenVK is supposed to detect this situation and bind the underlying buffer, but it looks like we're binding the wrong buffer slot. This is nontrivial without argument buffers, because buffers and textures have separate numbering spaces, and we also have to account for other uses like vertex buffers. With argument buffers, this becomes trivial, so the buffer is bound correctly.

Do you think there might likely be a near-term fix possible for binding the wrong buffer slot, or should we just try to go with argument buffers for now?

**Comment by Steveice10** [comment]
With argument buffers enabled we've started seeing validation errors like this show up sometimes:
```
-[MTLDebugRenderCommandEncoder setVertexBufferOffset:attributeStride:atIndex:]:1874: failed assertion `Set Vertex Buffer Offset Validation
index(29) must have an existing buffer.
'
```

**Comment by Steveice10** [comment]
We switched to using shader interlock instead so we don’t have this anymore, and can’t verify if it’s still an issue, so I’ll close as stale.
