### ISSUE TITLE
Depth clamp feature not supported by device

### ISSUE THREAD

**Issue by VladyslavSan** [KhronosGroup/MoltenVK#2010]
I’ve noticed that there is no way to turn on depth clamping (disable depth clipping) while using vulkan over metal. Is there any reason why it’s not implemented? I see that this thing is widely supported by metal api - https://developer.apple.com/documentation/metal/mtldepthclipmode/clamp.

So I wonder if there are pitfalls I don’t know of. If not then maybe I can make a pull request to add this?

**Comment by cdavis5e** [comment]
This *is* implemented. See [here][1] and [here][2].

[1]: https://github.com/KhronosGroup/MoltenVK/blob/fd418aa7fe5c69ddba00b8cfd6611cef03f13011/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L310
[2]: https://github.com/KhronosGroup/MoltenVK/blob/fd418aa7fe5c69ddba00b8cfd6611cef03f13011/MoltenVK/MoltenVK/GPUObjects/MVKPipeline.mm#L542

**Comment by VladyslavSan** [comment]
How do I use it then? I’ve tried enabling this feature by setting VkPhysicalDeviceFeatures::depthClamp to 1u and it didn’t work for me saying it is not supported.

**Comment by VladyslavOdobesku-TomTom** [comment]
Ok, found an issue, indeed it is supported!
