### ISSUE TITLE
Switch vkQueuePresent to use a retainedRefs command buffer?

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#2014]
In the last two Dota releases, we've encountered crashes with the Steam Overlay.  The most recent one was reproducible on Apple M1 and occurred without any Metal Validation errors (https://github.com/ValveSoftware/Dota-2/issues/2449).  The first time this happened on 03/24/23, I worked around it locally by having `MVKQueuePresentSurfaceSubmittion::execute` add a parameter true to getMTLCommandBuffer on this line:

https://github.com/KhronosGroup/MoltenVK/blob/473ea0c2f18e4d13389cfe1412b4042c5f3b83ba/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm#L625

...so that the command buffer was created with retainedReferences.  I shipped that fix, but then after some more investigation we found a bug in the Steam Overlay (caught by Metal validation) where the Steam Overlay command buffer was relying on the command buffer to retain references to its MTLRenderPassDescriptor.  We fixed that by doing a retain on it and releasing it in a MtlCommandBuffer completion handler.

This time (our latest update shipping with latest MoltenVK) with no changes we are aware of to the Steam Overlay a similar crash happened on Apple M1 (the bug linked above). There were no validation errors so I don't know what the problem could be with the Overlay.  It was intermittent.  However, I again applied the local fix to use retainedReferences on the vkQueuePresent command buffer and that worked around it.

I'm going to need to carry that workaround locally now.  I wonder if it should just be the default behavior?  It seems there is little downside and it will prevent crashes/hangs with any misbehaving injected layers?

**Comment by billhollings** [comment]
Any chance you have any of the Metal validation errors logged?

It would look something like:

    -[MTLDebugDevice notifyExternalReferencesNonZeroOnDealloc:], line 2885: error 'The following Metal object is being destroyed while still required to be alive by the command buffer 0x16a0f1a00 (label: vkQueueSubmit MTLCommandBuffer on Queue 0-0):

except on the `vkQueuePresentKHR MTLCommandBuffer`.

You're right. For `vkQueuePresentKHR`, it wouldn't be too expensive to just retain references, but it would be good to know what object(s) we're losing track of.

**Comment by danginsburg** [comment]
> Any chance you have any of the Metal validation errors logged?

Unfortunately, there are no Metal validation errors logged in the current case so I don't actually know the root cause of the problem, other than that using a retained command buffer works around the crash.

**Comment by danginsburg** [comment]
If you want to try it yourself, build a local copy of MoltenVK, overlay it on to the copy used by Dota in Steam (which has this fix) and from the main page go to View Treasure and try to purchase the Collector's Cache.  On an Apple M1, every now and then it would crash/exit without the workaround.

**Comment by billhollings** [comment]
The only things we add to a `vkQueuePresentKHR MTLCommandBuffer` would be the `MTLEvent` associated with each wait `VkSemaphore`...plus handler callbacks...but I would expect those would be retained automatically.

> If you want to try it yourself

Okay. I'll give that a shot.

**Comment by billhollings** [comment]
PR #2015 fixes this per the [description above](#issue-1886313511).
