### ISSUE TITLE
Severe swapchain performance regression

### ISSUE THREAD

**Issue by tycho** [KhronosGroup/MoltenVK#2019]
Starting with commit 9f64faadbcf, there's been some kind of major regression in swapchain handling.

My app allows toggling full screen and windowed mode (via SDL). When toggling from windowed to fullscreen, MVK behaves as expected, the swapchain is re-created as needed and the framerate returns to a solid 120Hz. But when toggling from fullscreen to windowed, something seriously wrong happens:

<img width="253" alt="Screenshot 2023-09-13 at 6 04 12 AM" src="https://github.com/KhronosGroup/MoltenVK/assets/29616/0a31db5a-6e0a-41ba-8a95-0abdfc6bc328">

I'm not sure what the exact cadence is, but every few frames it will stall for over a second waiting for a new drawable (approx. 1024ms at 99th percentile). Note that if I start the application windowed, it does not encounter this problem. It only occurs when transitioning from fullscreen to windowed mode.

Here's a sampling profile from Activity Monitor. The relevant slowdown is in Thread_140701:
[Sample of Darwinia.txt](https://github.com/KhronosGroup/MoltenVK/files/12597693/Sample.of.Darwinia.txt)

It spends a gigantic amount of time waiting in `MVKPresentableSwapchainImage::getCAMetalDrawable`.

Rolling back to commit fd418aa7fe5c avoids the issue, and a bisect points to 9f64faadbcf as the first bad commit.

Any ideas? Any other information I can provide?

macOS version: 14.0 (23A339)
System: MacBook Pro 14", 2021, M1 Max

**Comment by tycho** [comment]
Additionally, if a mode switch happens sometime during the run of the game, the game will freeze on exit, waiting for some VK fence that never completes.

**Comment by billhollings** [comment]
PR #2020 addresses this, and may provide a fix. Please retest with that code.

**Comment by tycho** [comment]
Thank you, yes, that PR works much better! Stable framerates, no hang on exit.
