### ISSUE TITLE
Deadlock on shutdown with debug callbacks

### ISSUE THREAD

**Issue by etang-cw** [KhronosGroup/MoltenVK#2027]
To reproduce:
Run `vulkaninfo` against MoltenVK

Expected result:
vulkaninfo exits

Actual result:
vulkaninfo doesn't exit
Sampling the process gives this trace (lldb wouldn't attach because annoying macOS restrictions on debugging signed apps):
<img width="992" alt="image" src="https://github.com/KhronosGroup/MoltenVK/assets/123040589/3608f86f-ae95-4938-b557-d2c3ff9aa380">

Seems related to ~MVKInstance logging under `_dcbLock`
https://github.com/KhronosGroup/MoltenVK/blob/568cc3acc0e2299931fdaecaaa1fc3ec5b4af281/MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm#L726-L731

Not sure whether you meant to log before clearing the debug report callbacks, or to drop the lock before logging, but either of the two should fix it

**Comment by billhollings** [comment]
PR #2037 fixes this.
