### ISSUE TITLE
DebugReportCallback regression with TOT

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/MoltenVK#2035]
During recent integration testing with top of tree on MoltenVK, I found that vulkaninfo was hanging up (not crashing) on termination. 

I've tested building Vulkan-Tools/vulkaninfo with XCode 15 and 14, and MoltenVK's top of tree and v1.2.5.

Only top of tree exhibits the bug, and it occurs with both XCode 14 and 15.

I've traced the hangup to the use of the VkDebugReportCallbackCreateInfoEXT structure in the pNext chain of the VkInstanceCreateInfo structure. If I set pNext to null, there is no hangup on termination.

I believe on termination, some class destructor is causing (more likely) a warning message to be emitted and this is getting hung up now with recent changes (or maybe it's when the instance is destroyed). I suspect it's the recent work on using the pNext data structure to facilitate the new instance settings extension work?

**Comment by billhollings** [comment]
PR #2037 fixes this.

**Comment by richard-lunarg** [comment]
I can confirm the fix worked.
