### ISSUE TITLE
Crash in vkQueueSubmit()

### ISSUE THREAD

**Issue by aaronmjacobs** [KhronosGroup/MoltenVK#2038]
Hey! After updating to the 1.3.261.1 SDK (from 1.3.236.0), I hit a crash when calling vkQueueSubmit(). I'm running on macOS Sonoma (14.0), and am building with Xcode 15.0

I built a debug package of MoltenVK locally to test against; here's my callstack:
```
#0	0x0000000107297d78 in mvk_smallvector_allocator<MVKRenderSubpass, 0>::operator[](unsigned long) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Utility/MVKSmallVectorAllocator.h:78
#1	0x0000000107297d5c in MVKSmallVectorImpl<MVKRenderSubpass, mvk_smallvector_allocator<MVKRenderSubpass, 0>>::operator[](unsigned long) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Utility/MVKSmallVector.h:305
#2	0x0000000107291458 in MVKRenderPass::getSubpass(unsigned int) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKRenderPass.h:302
#3	0x0000000107293df8 in MVKCommandEncoder::getSubpass() at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:642
#4	0x00000001073a7f94 in MVKGraphicsResourcesCommandEncoderState::encodeBindings(MVKShaderStage, char const*, bool, std::__1::function<void (MVKCommandEncoder*, MVKMTLBufferBinding&)>, std::__1::function<void (MVKCommandEncoder*, MVKMTLBufferBinding&, MVKArrayRef<unsigned int const>)>, std::__1::function<void (MVKCommandEncoder*, MVKMTLTextureBinding&)>, std::__1::function<void (MVKCommandEncoder*, MVKMTLSamplerStateBinding&)>) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm:726
#5	0x00000001073a9254 in MVKGraphicsResourcesCommandEncoderState::encodeImpl(unsigned int) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm:814
#6	0x000000010729531c in MVKCommandEncoderState::encode(unsigned int) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.h:92
#7	0x0000000107295208 in MVKCommandEncoder::finalizeDrawState(MVKGraphicsStage) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:735
#8	0x000000010728d9c8 in MVKCmdDrawIndexed::encode(MVKCommandEncoder*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCmdDraw.mm:408
#9	0x00000001072929d8 in MVKCommandEncoder::encodeCommandsImpl(MVKCommand*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:380
#10	0x0000000107292260 in MVKCommandEncoder::encodeCommands(MVKCommand*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:373
#11	0x000000010729208c in MVKCommandEncoder::encode(id<MTLCommandBuffer>, MVKCommandEncodingContext*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:347
#12	0x000000010729232c in MVKCommandBuffer::submit(MVKQueueCommandBufferSubmission*, MVKCommandEncodingContext*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Commands/MVKCommandBuffer.mm:240
#13	0x0000000107371994 in MVKQueueFullCommandBufferSubmission<1ul>::submitCommandBuffers() at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:635
#14	0x000000010736f57c in MVKQueueCommandBufferSubmission::execute() at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:453
#15	0x000000010736c4b4 in execute(MVKQueueSubmission*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:72
#16	0x000000010736c438 in MVKQueue::submit(MVKQueueSubmission*) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:90
#17	0x000000010736cf48 in VkResult MVKQueue::submit<VkSubmitInfo>(unsigned int, VkSubmitInfo const*, VkFence_T*, MVKCommandUse) at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:129
#18	0x000000010721da04 in vkQueueSubmit at /Users/aaron/Projects/MoltenVK/MoltenVK/MoltenVK/Vulkan/vulkan.mm:434
```

In `MVKGraphicsResourcesCommandEncoderState::encodeBindings()`, `_cmdEncoder->_pEncodingContext->_renderPass` is null (causing the crash in `_cmdEncoder->getSubpass()->getFirstViewIndexInMetalPass()`.

My project uses the `VK_KHR_dynamic_rendering` extension, in case that's relevant.

Please let me know if there is any more information I can provide to help track this down.

Thanks!

**Comment by billhollings** [comment]
Hard to tell what's going on here, relative to this report. As far as I can tell, any changes to code relevant to this issue, changed well before the Vulkan 1.3.236.0 MoltenVK release. 

> In `MVKGraphicsResourcesCommandEncoderState::encodeBindings()`, `_cmdEncoder->_pEncodingContext->_renderPass` is null (causing the crash in `_cmdEncoder->getSubpass()->getFirstViewIndexInMetalPass()`.

The call stack at the top seems to indicate that the renderpass was retrieved, and the `getSubpass()` call is not finding the correct subpass.

> My project uses the VK_KHR_dynamic_rendering extension, in case that's relevant.

Are you using multiview as well? There might be an issue with reaching the subpass for the mulitview. That did change between the 1.3.236.0 and 1.3.261.1 releases.

If you are using multiview, Is it possible to get more information about how you are using it?

Are you able to post access to a sample app that demonstrates the issue?

**Comment by billhollings** [comment]
> My project is located at https://github.com/aaronmjacobs/Forge

I'm having a tough time cloning your repo (same thing happens without the `--recurse-submodules`). Have you encountered this before?

```
$ git clone --recurse-submodules https://github.com/aaronmjacobs/Forge.git
Cloning into 'Forge'...
remote: Enumerating objects: 3493, done.
remote: Counting objects: 100% (550/550), done.
remote: Compressing objects: 100% (336/336), done.
remote: Total 3493 (delta 328), reused 361 (delta 210), pack-reused 2943
Receiving objects: 100% (3493/3493), 2.04 MiB | 16.33 MiB/s, done.
Resolving deltas: 100% (2377/2377), done.
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by cdavis5e** [comment]
> ```git-lfs filter-process: git-lfs: command not found```

Looks like you need to install `git-lfs`.

**Comment by aaronmjacobs** [comment]
My apologies, I forgot that I had set up `git-lfs` for the project a while back. Installing `git-lfs` before cloning the repo should allow it to succeed. Alternatively, if you'd prefer not to install it, I've uploaded a full copy of the repo here: https://drive.google.com/file/d/171IH_cD1aIpyP-P6m8rOtjIxT754E97I/view?usp=share_link

**Comment by billhollings** [comment]
>  I've uploaded a full copy of the repo

Thanks. I got it working from your upload.

I've attached a Vulkan call trace:  [Forge-Vulkan-Call-Trace.txt.zip](https://github.com/KhronosGroup/MoltenVK/files/13032672/Forge-Vulkan-Call-Trace.txt.zip)

In the trace, there are many `vkCmdDraw*` calls prior to the first and only occurrence of `vkCmdBeginRenderPass`. You mention using the `VK_KHR_dynamic_rendering` extension, in which case there should be a call to `vkCmdBeginRendering` prior to any `vkCmdDraw*` calls.

BTW...you can enable Vulkan call tracing by adding the `MVK_CONFIG_TRACE_VULKAN_CALLS=1` environment variable before running your app.

**Comment by aaronmjacobs** [comment]
Thanks for the heads up about `MVK_CONFIG_TRACE_VULKAN_CALLS`, that should be helpful in tracking down issues in the future.

It's true that I only call `vkCmdBeginRenderPass()` once per frame, as all my rendering uses `vkCmdBeginRendering()` instead, except for Dear ImGui. What's strange is, if I set `MVK_CONFIG_TRACE_VULKAN_CALLS`, I can see the log output, but when I step over the call to `vkCmdBeginRendering()`, it doesn't get logged.

It seems like the core issue here is likely that the call isn't being registered for some reason. Any ideas why that might be?

Thanks!

**Comment by aaronmjacobs** [comment]
After trying out a few things, I discovered that things seem to fall apart in the validation layer somehow. I call `vkCmdBeginRendering()`, but `vkCmdBeginRendering()` in `vulkan.mm` never gets hit. I tried disabling validation layers in my code, and sure enough, everything works as expected.

I'm not sure where the validation layer / `vulkan_layer_chassis` code lives, so it's hard for me to investigate further.

**Comment by cdavis5e** [comment]
Wait, are you calling `vkCmdBeginRendering()`, or `vkCmdBeginRenderingKHR()` (with the `KHR` suffix)? The former requires Vulkan 1.3. The latter is what is exposed by `VK_KHR_dynamic_rendering`.

**Comment by aaronmjacobs** [comment]
I'm calling `vkCmdBeginRendering()`, not `vkCmdBeginRenderingKHR()`. My project uses Vulkan 1.3, and also requests the `VK_KHR_dynamic_rendering` extension. If I don't request the extension, I hit an error in the validation layer when creating pipelines (`VUID-VkGraphicsPipelineCreateInfo-pNext-pNext`, "vkCreateGraphicsPipelines: Includes a pNext pointer (pCreateInfos[0].pNext) to a VkStructureType (VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO), but its parent extension VK_KHR_dynamic_rendering has not been enabled").

**Comment by cdavis5e** [comment]
MoltenVK does not yet support Vulkan 1.3 (see #1852). It reports Vulkan 1.2. Therefore, attempting to use `vkCmdBeginRendering()` on MoltenVK is, according to the Vulkan standard, undefined behavior (i.e. you **must** not do this--emphasis theirs). It happens to work in MoltenVK alone, but the validation layer checks that you are not violating the standard by invoking undefined behavior. So it refuses to forward `vkCmdBeginRendering()` to MoltenVK, even though MoltenVK's `vkGetDeviceProcAddr()` returns a non-null pointer for that function. If you want the validation layer to pass, you must call `vkCmdBeginRenderingKHR()` when the ICD advertises `VK_KHR_dynamic_rendering` but not core 1.3. (Admittedly, the validation layer could probably handle this better, e.g. by printing a validation failure message when you call `vkCmdBeginRendering()` without core 1.3.)

Note that a 1.1+ instance will actually allow you to create a downlevel device by default, so if you really do need 1.3, you have to check the version of Vulkan that the physical device supports.

**Comment by aaronmjacobs** [comment]
Thanks for the detailed info, that all makes sense. Calling `vkCmdBeginRenderingKHR()` does indeed fix the issue, and everything works as expected.

I definitely agree that it would be helpful for the validation layer to output a message if it decides to not forward the function call. Where would be the best place for me to request that feature?

Thank you!

**Comment by cdavis5e** [comment]
On [the issues page of the KhronosGroup/Vulkan-ValidationLayers project](/KhronosGroup/Vulkan-ValidationLayers/issues).

**Comment by billhollings** [comment]
> Wait, are you calling `vkCmdBeginRendering()`, or `vkCmdBeginRenderingKHR()` (with the `KHR` suffix)? The former requires Vulkan 1.3. The latter is what is exposed by `VK_KHR_dynamic_rendering`.

Ah! Good thinking!


> the validation layer could probably handle this better, e.g. by printing a validation failure message when you call

>I definitely agree that it would be helpful for the validation layer to output a message if it decides to not forward the function call. Where would be the best place for me to request that feature?

And yes...I would expect the validation layer to spit out errors on any calls not supported by a Vulkan API version, or enabled extensions. Might be an oversight, and worth reporting to them.
