### ISSUE TITLE
Timestamp calibration issue on Apple Silicon

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2039]
This was discussed previously in #1996, but I think the problem still remains.

It appears that on Apple Silicon, macOS GPU timestamp units are recorded and returned by MoltenVK in nanoseconds.  However, by changing the `timeStampPeriod` from `1.0` to `41.667` this causes a mis-calibration with external applications that are required to multiply returned Vulkan timestamps by the device property `timeStampPeriod`.  Final values are therefore too large by a factor of `41.667`.

This is not an issue with MoltenVK 1.2.4 and earlier, but is an issue starting in SDK 1.3.261.1 and MoltenVK 1.2.5.  It is not likely an application problem either, since the same cross platform application logic for Vulkan GPU timing works correctly on Windows, Linux, and macOS Intel.

Perhaps we should return to `timeStampPeriod = 1.0` for macOS on Apple Silicon, or if you require `timeStampPeriod = 41.667`, then "raw" timeStamps from queries would need to be returned in ticks not nanoseconds.

Please let me know if I am looking at this correctly, or if I have misinterpreted something.

**UPDATE**:  I was able to demonstrate that `timeStampPeriod` should be 1.0 for macOS on Apple Silicon by commenting out the following condition in MoltenVK and forcing time stamp calibration on my M1 Air.  The returned timeStampPeriod was 1.0 (with `LowPassAlpha = 1.0` to eliminate filtering).

```
// On Apple GPUs, CPU & GPU timestamps are the same, and timestamp period never changes.
void MVKPhysicalDevice::updateTimestampPeriod() {
	if ( /* _properties.vendorID != kAppleVendorId && */
		[_mtlDevice respondsToSelector: @selector(sampleTimestamps:gpuTimestamp:)]) {
...

```

**Comment by billhollings** [comment]
PR #2043 fixes this issue. Please retest with latest MoltenVK, and close this issue if it resolves the issue.

`timestampPeriod` is now set to 1.0 for Apple GPU's.

**Comment by SRSaunders** [comment]
Thanks for fixing.  The only thing I am concerned about is possible impact on iOS.  I am less familiar than with macOS, so I don’t want my request for a fix on macOS to break this for iOS.

Is it possible that timestampPeriod should be 1.0 for macOS but remain 41.667 for iOS?

**Comment by billhollings** [comment]
> Thanks for fixing. The only thing I am concerned about is possible impact on iOS. I am less familiar than with macOS, so I don’t want my request for a fix on macOS to break this for iOS.
> 
> Is it possible that timestampPeriod should be 1.0 for macOS on Apple Silicon but remain 41.667 for iOS on A-series chips?

Good catch. Thanks for pointing that out.

The `timestampPeriod` was originally set to `41.667` on iOS when timestamps were generated by the CPU instead of the GPU, because that's the CPU tick on Apple Silicon.

For older devices that do not support GPU timestamps, I've now pushed an additional change to have the CPU-timestamps use nanoseconds instead of CPU ticks. That way, `timestampPeriod` can be 1.0, even with CPU-generated timestamps.

So, the only situation where `timestampPeriod` deviates from 1.0, should now be for GPU-generated timestamps on non-Apple GPU's.

**Comment by SRSaunders** [comment]
Issue is fixed for macOS on Apple Silicon.  Thanks.
