### ISSUE TITLE
Dynamic vertex input binding stride breaks rendering 

### ISSUE THREAD

**Issue by tycho** [KhronosGroup/MoltenVK#2041]
My application uses ANGLE + MoltenVK for rendering on macOS.

After updating to the current HEAD (61b871217838effcf74346509dba9f67109a8abd), my app was no longer rendering anything correctly. The framebuffer clear worked as intended, but that's about all. No other geometry renders.

Attaching the Xcode debugger with Metal API validation enabled results in this during the first draw or so:

```
validateCommonDrawErrors:instanceCount:baseInstance:maxVertexID:]:5708: failed assertion `Draw Errors Validation
providing `attributeStride` value of 64 when stride at buffer-layout index 25 is static.
providing `attributeStride` value of 64 when stride at buffer-layout index 26 is static.
providing `attributeStride` value of 64 when stride at buffer-layout index 27 is static.
providing `attributeStride` value of 64 when stride at buffer-layout index 28 is static.
providing `attributeStride` value of 16 when stride at buffer-layout index 29 is static.
providing `attributeStride` value of 16 when stride at buffer-layout index 30 is static.
```

I did discover a workaround for this problem. If I disable the ANGLE feature named `useVertexInputBindingStrideDynamicState`, all the remaining dynamic state functionality appears to function as intended and the game renders perfectly.

I am not certain how to debug this, or what further data I can provide. I can provide a demo app if needed to reproduce the problem.

**Comment by tycho** [comment]
Here's a redistributable demo build of the game in question:

https://www.uplinklabs.net/files/Darwinia-macOS-demo-2.3.2-53-g7625f44ff.zip

You'll have to remove the `com.apple.quarantine` xattr in order for it to read the overrides.txt and enable the repro case. (By default the game currently uses a workaround to disable the feature that breaks rendering.)

**Comment by cdavis5e** [comment]
Ah, dammit, I should've caught this in my review. When dynamic vertex strides are used, this has to be explicitly enabled in the vertex descriptor, by setting the stride there to `MTLBufferLayoutStrideDynamic`. (Conversely, when using the new array method to set the vertex buffer and the stride is *not* dynamic, the stride in the method must be `MTLAttributeStrideStatic`. But we don't use the array method yet.)

**Comment by billhollings** [comment]
Thanks for submitting this, and the _**very helpful**_ demo app!

PR #2042 fixes this. Please retest with latest MoltenVK and close this issue if it fixes the issue you encountered.

**Comment by billhollings** [comment]
> When dynamic vertex strides are used, this has to be explicitly enabled in the vertex descriptor, by setting the stride there to `MTLBufferLayoutStrideDynamic`.

We were actually doing that already...but not in the case where the pipeline stride is set to zero, which, in the static stride case, triggers the step-function work-around.

**Comment by tycho** [comment]
Sorry for the delay. I can confirm this fixed the issue. Thank you for the rapid turnaround on the fix!
