### ISSUE TITLE
Did SDK 1.3.268 pick up MoltenVK 1.2.5 by mistake?

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2048]
I just downloaded the new SDK 1.3.268.0 from LunarG [vulkansdk-macos-1.3.268.0.dmg](https://sdk.lunarg.com/sdk/download/1.3.268.0/mac/vulkansdk-macos-1.3.268.0.dmg), and it appears to contain MVK 1.2.5.

From the mvk_config.h file: 

```
#define MVK_VERSION_MAJOR   1
#define MVK_VERSION_MINOR   2
#define MVK_VERSION_PATCH   5
```

Some of the recent fixes I was expecting appear to be missing :(

**Comment by richard-lunarg** [comment]
Yes... you are correct. The new rc process needs to be "check listed" in our process. A .1 macOS SDK release is in progress right now.

**Comment by richard-lunarg** [comment]
The new macOS SDK is now live:
https://vulkan.lunarg.com/sdk/home#mac
This one does include MoltenVK 1.2.6
