### ISSUE TITLE
Support `VK_EXT_headless_surface`

### ISSUE THREAD

**Issue by DUOLabs333** [KhronosGroup/MoltenVK#2049]
For a project, I want to be able to create a surface so I can copy the contents of the images rendered somewhere else. However, I don't want it to actually display anywhere.

**Comment by K0bin** [comment]
Just don't create a swapchain and render to a regular image.

**Comment by DUOLabs333** [comment]
I'm overriding certain Vulkan commands that will be called by other applications, so I can't control whether they use a surface or not.

**Comment by cdavis5e** [comment]
This seems to me to be a good candidate for an extension that could be provided by a layer. Then you could add it to *any* driver, not just MoltenVK. I wonder if there already *is* such a layer...

**Comment by DUOLabs333** [comment]
Can I just call `vkCreateMetalSurfaceEXT` with a NULL pLayer?

**Comment by billhollings** [comment]
> Can I just call `vkCreateMetalSurfaceEXT` with a NULL pLayer?

Highly doubtful. It's not expected, and the current swapchain images would expect to pull a `MTLTexture` from a `CAMetalDrawable` from a `CAMetalLayer`.

However, `VK_EXT_headless_surface` is fairly simple, and should be fairly straightforward to implement, after some refactoring of the contract between swapchain images and surfaces within MoltenVK.

**Comment by DUOLabs333** [comment]
There's this: https://gitlab.freedesktop.org/mesa/vulkan-wsi-layer, which may work (although they say it's for Linux, there's nothing in the headless support that requires Linux-specific features).
