### ISSUE TITLE
Support for RPCS3 (+via Wine)..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#205]
Hi,
trying to run simple gs_gcm_basic_triangle.elf on RPCS3 running via Wine with Vulkan enabled I get an error..
log shows error is:
[***MoltenVK ERROR***] VK_ERROR_EXTENSION_NOT_PRESENT: Vulkan extension VK_EXT_debug_report is not supported.

Wine rpcs3.exe selected output:

> [mvk-info] MoltenVK version 1.0.12. Vulkan version 1.0.77.
> [mvk-info] GPU device:
> 		model: AMD Radeon RX Vega 56
> 		type: Discrete
> 		vendorID: 0x10de
> 		deviceID: 0x1d81
> 		pipelineCacheUUID: 00000000-0000-0000-0000-27130000271C
> 	supports the following Metal Feature Sets:
> 		macOS GPU Family 1 v3
> 		macOS GPU Family 1 v2
> 		macOS GPU Family 1 v1
> [***MoltenVK ERROR***] VK_ERROR_EXTENSION_NOT_PRESENT: Vulkan extension VK_EXT_debug_report is not supported.
> 0058:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-7

**Comment by billhollings** [comment]
Similar to #11.

**Comment by oscarbg** [comment]
Hi,
I renamed issue title to "support for RPCS3" as VK_EXT_debug_report is just the first issue I found..
really just wanted to say that seems "Vulkan Portability" devs are working with RPCS3 devs for Macos support and they are lifting a lot of requirements on their Vulkan code very fast like removing needed swizzle support of Vulkan implementation that would also likely help MoltenVK:
https://github.com/RPCS3/rpcs3/pull/4996
as you can see issues being fixed on both sides:
  *Too many samplers are requested by a pipeline layout. Metal only supports 16 samplers per stage on all devices, while RPCS3 requested 20.
   *Texture swizzling is (almost) not supported.
   *Occlusion queries are missing.
   *Buffers in HOST_VISIBLE memory with TEXEL_BUFFER usage are requested but not supported
also Macos related commits from RPCS3 side:
"vk: Implement double-buffered heaps for platforms without universal support for host visibility (APPLE)"
"vk: Support sw component swizzle decode because metal sucks "
as said before just pointing out in case somebody wants to work on this support..

**Comment by galad87** [comment]
RPCS3 has got a macOS version (that uses MoltenVK). Maybe this issue could be closed.

**Comment by oscarbg** [comment]
yep.. closing..
