### ISSUE TITLE
polygonMode line broken on SDK `1.3.268.1`

### ISSUE THREAD

**Issue by mokafolio** [KhronosGroup/MoltenVK#2056]
Moltenvk shipping with SDK `1.3.268.1` seems to have broken `VkPipelineRasterizationStateCreateInfo` `polygonMode`. `VK_POLYGON_MODE_LINE` used to work previously but now just renders an opaque blob (see screenshots attached). For what it's worth, the pinned moltenvk revision of `1.3.268.1` is 9e4ee9e679a6e1eb612bf82824ea0f68f43e558c. The revision that still works from the `1.3.261.1` sdk is 02a8c011a8ca077dfaa09f3b7ebf68be869dc26f

<img width="570" alt="Screenshot 2023-11-02 at 10 32 58 AM" src="https://github.com/KhronosGroup/MoltenVK/assets/10217168/951f0852-cc46-4570-802e-be89251a64b2">
<img width="570" alt="Screenshot 2023-11-02 at 10 35 33 AM" src="https://github.com/KhronosGroup/MoltenVK/assets/10217168/f0a45820-b517-4a77-aebc-4a0713083d8d">

**Comment by billhollings** [comment]
Thanks for catching and reporting this.

This was caused during the addition of `VK_EXT_extended_dynamic_state` & `VK_EXT_extended_dynamic_state2`. Polygon mode is actually part of `VK_EXT_extended_dynamic_state3`, so it wasn't testing properly.

I'll include a fix for this when support for `VK_EXT_extended_dynamic_state3` is added, within the next week or two.

**Comment by billhollings** [comment]
PR #2066 includes a fix for this. Please retest using latest version, and close this issue if the problem is fixed.

**Comment by mokafolio** [comment]
can confirm that this is fixed in current tip of `main`.

**Comment by xxxmonsterxxx** [comment]
> PR #2066 includes a fix for this. Please retest using latest version, and close this issue if the problem is fixed.

Funny situation. I didn't use this option exactly after you broke it =) And today I got confused with it using 1.3.268.1... Yeah, I spent half a day searching for a bug in my code, but it turned out to be simple. I usually try to find a solution myself first, and only then resort to Google. Thank for report and for solution.
