### ISSUE TITLE
`vkCmdClearAttachments` flips viewport in SDK `1.3.268.1`

### ISSUE THREAD

**Issue by mokafolio** [KhronosGroup/MoltenVK#2057]
Moltenvk shipping with SDK `1.3.268.1` seems to break the viewport orientation after a call to `vkCmdClearAttachments` (this is using opengl style viewports with `VK_KHR_Maintenance1`). Please see the attached screenshots. The correct one is with SDK `1.3.261.1` while the flipped one is with SDK `1.3.268.1`. This issue only happens when using `vkCmdClearAttachments` and I assume it might be due to some internal state tracking of moltenvk that goes wrong?

For what it's worth, the pinned moltenvk revision of 1.3.268.1 is  9e4ee9e679a6e1eb612bf82824ea0f68f43e558c. The revision that still works from the 1.3.261.1 sdk is 02a8c011a8ca077dfaa09f3b7ebf68be869dc26f.

<img width="912" alt="Screenshot 2023-11-02 at 11 40 59 AM" src="https://github.com/KhronosGroup/MoltenVK/assets/10217168/1c9ed565-a83d-4164-9e49-cf3a5e91a743">
<img width="912" alt="Screenshot 2023-11-02 at 11 38 38 AM" src="https://github.com/KhronosGroup/MoltenVK/assets/10217168/b9977f98-12b4-413f-bce6-07b72784e820">

**Comment by billhollings** [comment]
Thanks for catching and reporting this.

This was caused during the addition of `VK_EXT_extended_dynamic_state` & `VK_EXT_extended_dynamic_state2`.

I'll include a fix for this when support for `VK_EXT_extended_dynamic_state3` is added, within the next week or two.

**Comment by billhollings** [comment]
PR #2066 includes a fix for this. Please retest using latest version, and close this issue if the problem is fixed.

**Comment by mokafolio** [comment]
can confirm that this is fixed when using the current tip of `main`. thanks!
