### ISSUE TITLE
Metal argument buffer assert when Xcode Metal API validation enabled

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2062]
If I have Xcode's Metal API validation enabled when `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS > 0`, I get the following Metal assert during destruction of descriptor pools inside `~MVKDescriptorPool()`.  It looks like the Metal API validation wrapper  is creating a dependency between the associated command buffer and descriptor pool objects including the argument buffer.  This does not happen when `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS = 0`, or if Metal API validation is turned off.

```
-[MTLDebugDevice notifyExternalReferencesNonZeroOnDealloc:]:2885: failed assertion `The following Metal object is being destroyed while still required to be alive by the command buffer 0x1d01aea00 (label: vkQueueSubmit MTLCommandBuffer on Queue 0-0):
<MTLToolsObject: 0x6000069105b0> -> <GFXAAMD_MtlBuffer: 0x1cfe3efd0>
    label = Argument buffer 
    length = 40 
    cpuCacheMode = MTLCPUCacheModeDefaultCache 
    storageMode = MTLStorageModeShared 
    hazardTrackingMode = MTLHazardTrackingModeTracked 
    resourceOptions = MTLResourceCPUCacheModeDefaultCache MTLResourceStorageModeShared MTLResourceHazardTrackingModeTracked  
    purgeableState = MTLPurgeableStateNonVolatile'
```

I looked at the code inside `~MVKDescriptorPool()` and see a hard release `[_metalArgumentBuffer release]` even though the retained object `_metalArgumentBuffer` is created inside an autorelease pool.  As an experiment, I changed the destructor code to `[_metalArgumentBuffer autorelease]` and the problem disappears, with no Metal asserts even with argument buffers enabled and Metal API validation turned on.

I am not sure if you consider this an important enough issue to solve, or if I am on the right path for a solution.  In any case, I wanted to report this here in case others have faced the same issue.

**Comment by billhollings** [comment]
Thanks for reporting this, and for the detective work, and solution proposal!

**Comment by cdavis5e** [comment]
Wait, if you call `-[MTLBuffer autorelease]`, then unless the call to `~MVKDescriptorPool()` is inside an autorelease pool, the buffer will be leaked.

This would instead suggest that the `MVKDescriptorPool` needs to be retained by in-flight command buffers that reference it. I thought we were already doing that... are we?

**Comment by SRSaunders** [comment]
Not sure if this helps, but I have collected empirical data by tracing my C++ application (not ObjC++) using the Xcode Instruments Leak tool.  Linking to a custom build of MoltenVK containing `[_metalArgumentBuffer autorelease]`, I cannot observe any leaks occurring.  However, if I comment out the line entirely to simulate an ineffective or out-of-scope `autorelease`, thousands of leaks are registered.  So it seems that it is somehow working as I would hope, even without calling `~MVKDescriptorPool()` from within an autorelease pool (not possible anyways with a C++ application).

As you say above, perhaps the `MVKDescriptorPool` is already retained by in-flight command buffers, and the autorelease is deferred until those are completed.  But in the end, you guys are the experts in how MoltenVK works under the covers, and need to be comfortable with any change here.

**Comment by billhollings** [comment]
Looking into this more closely...

> I looked at the code inside ~MVKDescriptorPool() and see a hard release [_metalArgumentBuffer release] even though the retained object _metalArgumentBuffer is created inside an autorelease pool.

Although `_metalArgumentBuffer` is created and assigned inside an autorelease pool, `autorelease` is never called on it, so the wrapping autorelease pool will not release it, and it will be retained, and the `[_metalArgumentBuffer release]` in the `~MVKDescriptorPool()` seems to be doing what it should.

> Linking to a custom build of MoltenVK containing [_metalArgumentBuffer autorelease], I cannot observe any leaks occurring.

I suspect what is happening here is that the destructor is being called from a thread that contains a Obj-C runloop, possibly the thread that launched the app (ie. main execution thread of the app). Such threads include a default autorelease pool to catch any autoreleased objects that are not caught by more local autorelease pools. In that scenario, changing `release` to `autorelease` will still result in the object being released, and no leak occurs, whereas using neither call means the object is never released, and results in a leak.

------------------------

Before delving to this any further, the Vulkan spec is clear that the app is responsible for ensuring that objects referenced by an executing command buffer are not destroyed before the command buffer completes (the link defines _Pending State_), so we should confirm your app is compliant with this:

>The application must not destroy any other type of Vulkan object until all uses of that object by the device (such as via command buffer execution) have completed.

>The following Vulkan objects must not be destroyed while any command buffers using the object are in the [pending state](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#commandbuffers-lifecycle):

>VkEvent
>VkQueryPool
>VkBuffer
>VkBufferView
>VkImage
>VkImageView
>VkPipeline
>VkSampler
>VkSamplerYcbcrConversion
>VkDescriptorPool
>VkFramebuffer
>VkRenderPass
>VkCommandBuffer
>VkCommandPool
>VkDeviceMemory
>VkDescriptorSet
>VkIndirectCommandsLayoutNV
>VkAccelerationStructureNV
>VkAccelerationStructureKHR
>VkVideoSessionKHR
>VkVideoSessionParametersKHR

**Comment by SRSaunders** [comment]
Thanks for your response and the technical details about command buffer state - interesting.  However, I am pretty sure my app is obeying this, as it's implemented/enforced by Nvidia's [nvrhi](https://github.com/NVIDIAGameWorks/nvrhi) cross-platform portability library for Vulkan and DX12.  The library checks first for completed command buffers before attempting to release any associated resources, in this case Binding Sets which have associated Descriptor Pools.  The command buffer is then recycled into a free pool for later reuse.  And there is definitely no ObjC++ or autorelease pool construct in the call path - the application and nvrhi library are cross platform for Windows, Linux, and macOS and are pure C++.  See the following code snippet and application-side stack trace when a Metal assert occurs.  Note the `cmd->submissionID <= lastFinishedID` comparison below is based on a Vulkan timeline semaphore for command buffer completions:

![Screenshot 2023-11-17 at 11 18 21 AM](https://github.com/KhronosGroup/MoltenVK/assets/82544213/36ced270-b4bb-4d3f-b967-144b8078d261)

![Screenshot 2023-11-17 at 11 19 38 AM](https://github.com/KhronosGroup/MoltenVK/assets/82544213/f4d42231-b1dc-48f1-acbc-fae9243b96a6)


Getting back to the original issue, the problem is not about the app suffering a Metal assert when running normally, but only when _Xcode's Metal API validation option is enabled_.  This debug option seems to create a wrapper object `MTLToolsObject` which surrounds the Metal argument buffer.  The assert is happening on the `MTLToolsObject` proxy and not the argument buffer directly.  If this is a general problem, it should be fairly easy to duplicate on other test applications.  Do you have any Metal Argument buffer test code where you could enable Xcode's Metal API validation option?

**Comment by SRSaunders** [comment]
I am going to close this as answered.  Interestingly, even though Instruments does not show a memory leak when using `[_metalArgumentBuffer autorelease]` vs `[_metalArgumentBuffer release]`, I can detect a problem by monitoring with `mvkPerfStats.device.gpuMemoryAllocated`.  With the change in place, GPU memory continuously grows, but does not with the original code. @cdavis5e is correct about not using autorelease at this place in the code.

The problem is likely a timing edge case where the app and **nvrhi** library may be slightly too aggressive based on the state of the timeline semaphore indicating command buffer completion.  I am speculating but perhaps command buffer execution has completed but cleanup has not.  However, there does not appear to be any ill effect when running the application without Metal API validation enabled - no graphics defects or asserts or any other problem.  The case is limited to when Metal API validation is enabled so I am not too worried and do not plan to fix on the app or library side.

Thanks for your feedback and information provided.
