### ISSUE TITLE
VulkanSDK 1.3.268.1 broken on M3 MBP

### ISSUE THREAD

**Issue by Kurapikov** [KhronosGroup/MoltenVK#2063]
VulkanSDK 1.3.268.1 is broken on latest M3 Macbook Pro.

```
someuser@MacBook-Pro demo % /Users/someuser/VulkanSDK/1.3.268.1/macOS/bin/vulkaninfo
ERROR: [Loader Message] Code 0 : vkCreateInstance: Found no drivers!
Cannot create Vulkan instance.
This problem is often caused by a faulty installation of the Vulkan driver or attempting to use a GPU that does not support Vulkan.
ERROR at /Users/lunarg/Dev/macos-sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.h:688:vkCreateInstance failed with ERROR_INCOMPATIBLE_DRIVER
```

Is this a known issue? Is there more information can I provide?

**Comment by richard-lunarg** [comment]
When you installed the SDK, did you check the box "System Global Installation"?

**Comment by Kurapikov** [comment]
> When you installed the SDK, did you check the box "System Global Installation"?

No. 

I reinstalled with "System Global Installation" and everything is OK now.

So if I'd like to use non global installation, should I pass some argument to vulkaninfo to make it find right install path?

**Comment by richard-lunarg** [comment]
>So if I'd like to use non global installation, should I pass some argument to vulkaninfo to make it find right install path?

Easier, you just need to setup the environment for your shell. From the SDK folder run this:

source ./setup-env.sh

Or, you can put something like this in your startup script:

source /Users/<your login>/VulkanSDK/1.3.268.1/setup-env.sh

Bear in mind, GUI apps (such as vkconfig or hwcapsviewer) launched from Finder or the desktop in macOS do not see these environment variables. You can though, launch them from the command line with these environment variables set. Some people consider this a hassle, thus we have the option to install these files globally where they can be found for developers use only.
