### ISSUE TITLE
Window resize (sometimes) triggers setScissorRect:]:2565: failed assertion

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#207]
Hello,

our Application sometimes crashes due to a Metal Validation error when we resize our window. The issue does not show up all the time just randomly. We get something like the following:

`-[MTLDebugRenderCommandEncoder setScissorRect:]:2565: failed assertion `(rect.x(0) + rect.width(2214))(2214) must be <= render pass width(2176)
`

While debugging this issue it seems that when the NSWindow receives the window resize notification NSWindowWillStartLiveResizeNotification the rendering code is still active in the Display Link Callback function.

We think it is something we are not doing right, so the question is, what is the proper way to handle a window resize with a DisplayLink callback and MoltenVK?

Is there any way to delay the actual resize until the frame rendering has completed?

**Comment by mbarriault** [comment]
I don't know if it's standard practice, but I noticed that `vkAcquireNextImageKHR` will return `VK_OUT_OF_DATE_KHR`, so in my loop I catch that, `vkDeviceWaitIdle`, then rebuild the swapchain with the new size. This has worked great not only on macOS for live window resizing and going into and out of fullscreen, but on iOS for device rotation and changing split view on iPad.

**Comment by billhollings** [comment]
@aerofly 

As @mbarriault indicates, both `vkAcquireNextImageKHR()` and `vkQueuePresentKHR()` return `VK_ERROR_OUT_OF_DATE_KHR` when the swap chain image size is different than the view size. The app can use this result to rebuild the swap chain.

The MoltenVK _Cube_ demo sample (`Demos->cube.c`) includes a sizeable window...and you can see how it handles rebuilding the swap chain after receiving the `VK_ERROR_OUT_OF_DATE_KHR ` result.

**Comment by aerofly** [comment]
Thank you both for the reply. Well, I already check the result of vkAcquireNextImageKHR and vkQueuePresentKHR. And if one of the functions return VK_ERROR_OUT_OF_DATE I indeed resize the swap chain.

But the issue still shows up. When debugging my project, it is as follows:

- I receive a VK_ERROR_OUT_OF_DATE result from vkQueuePresentKHR
- But right after that call, before any other Vulkan functions is called, I do get a validation error in 
`void MVKScissorCommandEncoderState::encodeImpl() {
	[_cmdEncoder->_mtlRenderEncoder setScissorRect: _cmdEncoder->clipToRenderArea(_mtlScissor)];
}`
- When looking at the call trace, I can see that the above function was actually called through a call to vkQueueSubmit that I issued, right before I called vkQueuePresentKHR.

When looking at it, it seems like vkQueuePresentKHR actually detected a resize and returns the result properly, but the call to vkQueueSubmit when used in conjunction with synchronousQueueSubmits flag, causes the issue. E.g. I can't actually resize my swap chain since vkQueueSubmit already receives those changed sizes.

Please note: If I set synchronousQueueSubmits to true, I do NOT see the issue and everything runs fine.

**Comment by billhollings** [comment]
@aerofly Fixed in PR #213. Please retest and close if successful.

**Comment by aerofly** [comment]
I can confirm it's now working. Thank you for the quick fix!
