### ISSUE TITLE
Incorrect heapUsage values from VkPhysicalDeviceMemoryBudgetPropertiesEXT query on non-unified memory machines

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2082]
When calling `vkGetPhysicalDeviceMemoryProperties2()` with `VkPhysicalDeviceMemoryBudgetPropertiesEXT` in the pNext chain, I observe the following for the returned `heapUsage`:

1. `heapUsage[0]` seems to be the total allocated gpu memory, and for my application yields the same value as found in `mvkPerfStats.device.gpuMemoryAllocated.latest`
2. `heapUsage[1]` appears to be something else related to MoltenVK's CPU/system memory footprint.

Looking at VulkanCapsViewer on macOS, Memory heap 0 shows `DEVICE_LOCAL_BIT, HOST_VISIBLE_BIT, and HOST_CACHED_BIT`, while Memory heap 1 shows `HOST_VISIBLE_BIT, HOST_COHERENT_BIT, and HOST_CACHED_BIT`.

As on Vulkan for other platforms, the different heaps correspond to various types of GPU physical device memory, each supporting different access capabilities (e.g. device-only, host-visible, host-coherent, etc).  What do the different heaps represent for MoltenVK?  The reason I am confused is that for my application I would have expected `heapUsage[0] + heapUsage[1]` to represent the total GPU memory in use.  However, the results seem to indicate the total is stored in `heapUsage[0]` and I am left wondering what is stored in `heapUsage[1]` and how to use both pieces of data.

If I am interested in getting the total allocated GPU memory of all types (e.g. similar to what would be displayed in MSI Afterburner on Windows, or MangoHUD on Linux), how should I be using the above `heapUsage` values?

**UPDATE**:  Here is some data collected directly from memory allocators used in my application vs. the query:

Memory Allocator Information (buffers and textures):
Heap 0: 1076 MB
Heap 1:   636 MB
Total:      1712 MB

`vkGetPhysicalDeviceMemoryProperties2()` query (with `VkPhysicalDeviceMemoryBudgetPropertiesEXT`):
Heap 0: 1804 MB from `heapUsage[0]`
Heap 1:  1296 MB from `heapUsage[1]`

As you can see, the `heapUsage[0]` query (1804 MB) is fairly close to the sum of the heap allocations (1712 MB).  However, the `heapUsage[1]` number does not make sense.  Why doesn't the `heapUsage` data from the query better align with the allocator information?  And the sum of the `heapUsage` data should add up to the total allocations, and not be placed in the `heapUsage[0]` slot.  Can you explain what is happening here?

**Comment by cdavis5e** [comment]
At the time I had written that code, I had assumed that `MTLDevice.currentAllocatedSize` only tracked on-device private memory, and that the current memory usage of the current process would be a good proxy for the total shared memory usage. (On devices with non-unified memory, heap 1 is system RAM.) It looks like my assumption was wrong.

**Comment by SRSaunders** [comment]
Just wondering if @cdavis5e or @billhollings consider this a bug to be fixed or not.  I notice that no triage tag has been applied for a few weeks. This should be a pretty simple issue with an easy fix:
1. replace `task_vm_info.phys_footprint` with `task_vm_info.ledger_tag_graphics_footprint` inside `mvkGetUsedMemorySize()`, and
2. modify `MVKPhysicalDevice::getMemoryProperties` similar to what I have prototyped above

Please let me know whether you plan to fix or not.  If not I will need to find a work-around.  Thanks.

**Comment by billhollings** [comment]
> Please let me know whether you plan to fix or not. If not I will need to find a work-around. Thanks.

Dev delays are typically an issue of task priority and time, not a lack of intention.

Thanks for all your detective work on this. Since you have a good handle on this, probably the fastest way of getting this fixed is for you to submit a PR with your fix.

**Comment by SRSaunders** [comment]
Thanks for your quick response.  I totally understand about dev and project priorities - especially since this is a small issue.  My comments above were mostly about triage, and less about the schedule for fixing.  Thanks for marking it as a bug.

Also, thanks for your invitation to create a pull request for this, which I have done with #2098.  I have signed the CLA and look forward to your review/comments.
