### ISSUE TITLE
Some primitives getting drawn inverted since 1.2.6

### ISSUE THREAD

**Issue by jswillard** [KhronosGroup/MoltenVK#2089]
Since the 1.2.6 update to MoltenVK, I've found some instances of primitives being drawn inverted on the vertical axis (see the upside down red north arrow and miles in the screenshot). I'm not sure exactly what's going on but I bisected MoltenVK between 1.2.5 and 1.2.6 and found this to be the offending commit: https://github.com/KhronosGroup/MoltenVK/commit/3c75e114dd04636628cc212e947e420ed5415fca.

If there's anything I should look at that could provide more information as to what is going on, let me know. Thanks for your time.

![image](https://github.com/KhronosGroup/MoltenVK/assets/54554392/2bef119d-a2ae-4089-a015-301c368c500a)

**Comment by billhollings** [comment]
Very odd.

Does your app use any Dynamic State (the purpose of the offending commit)?

**Comment by richard-lunarg** [comment]
It could also be the texture coordinates, not just the primitives.

**Comment by jswillard** [comment]
Yes we use `VK_DYNAMIC_STATE_VIEWPORT`, `VK_DYNAMIC_STATE_SCISSOR`, `VK_DYNAMIC_STATE_DEPTH_BOUNDS`, `VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK`, `VK_DYNAMIC_STATE_STENCIL_WRITE_MASK`, and `VK_DYNAMIC_STATE_STENCIL_REFERENCE`

**Comment by jswillard** [comment]
Everything looks good in main, I tested on e6a3886. I thought I tested that before opening the ticket but apparently not. Will those changes be landing in 1.2.7?

**Comment by juan-lunarg** [comment]
> Will those changes be landing in 1.2.7?

Yes.
