### ISSUE TITLE
Regression with 13998affe, point rendering no longer working

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#2096]
I noticed that point rendering no longer works as of 13998affe. I'm not using polygons with POLYGON_MODE_POINT, I'm using point primitive topology. Tracing through the MoltenVK code, everything seems fine at first glance, cmdEncoder->_mtlRenderEncoder drawIndexedPrimitives is being given the correct primitive type.
Any ideas where else to look as to how this commit broke point rendering?

Further info, if I stop using dynamic primitive topology, then point rendering works again. Not surprising, although unclear how this commit breaks it still

**Comment by billhollings** [comment]
PR #2100 should fix this. Please retest with latest MoltenVK and close this issue if the problem is fixed.

**Comment by mbechard** [comment]
Confirmed it fixes my issue, thanks!
