### ISSUE TITLE
Vulkan driver for M1 reports that it doesn't support wide lines for no mans sky on crossover

### ISSUE THREAD

**Issue by Voyager22222** [KhronosGroup/MoltenVK#2101]
Hi, 
I've been trying to play no mans sky via crossover lately and as soon as I turn it on its says the Vulkan driver for M1 reports that it docent support wide lines. then the game states its encountered a fatal error and needs to close. I barley know anything about coding or anything but any help is appreciated, thanks 
<img width="1368" alt="Screenshot 2023-12-19 at 9 58 26 am" src="https://github.com/KhronosGroup/MoltenVK/assets/154284530/d561b22e-1bcd-42cc-b3ab-e52f22661f77">

**Comment by billhollings** [comment]
The error is accurate. Unfortunately, Metal does not officially support wide lines.

In the next couple of months, we are planning to [add wide line support](https://github.com/KhronosGroup/MoltenVK/issues/1975) for apps that do not use Apple's App Store. But wide lines will continue to be unavailable for apps that are distributed via the App Store.

**Comment by Voyager22222** [comment]
Hi, thanks for the help its really appreciated

**Comment by BolandJS** [comment]
> Hi, thanks for the help its really appreciated

NMS has a native Mac version. You'll have better luck with running that than trying to play it through crossover.
