### ISSUE TITLE
Questions re new VK_EXT_layer_settings feature

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2104]
I have prototyped changes in my app necessary to comply with the new `VK_EXT_layer_settings` extension vs. using the now-legacy `vkSetMoltenVKConfigurationMVK()` method.  It seems to work fine, but I have two questions:

1. The new `VK_EXT_layer_settings` API seems to require MoltenVK configuration only via `vkCreateInstance()`, and does not appear to allow for changes at any later time, i.e. after instance creation but before device creation, or even after device creation.  The older `vkSetMoltenVKConfigurationMVK()` method allowed changes _after_ instance creation, with restrictions based solely on the specific config variable.  Is there any non-deprecated way to set/modify config values after calling `vkCreateInstance()`?
2. It is not clear to me whether the MoltenVK layer needs to be activated and loaded ( via `vkCreateInstance()` ) to use the configuration capabilities of `VK_EXT_layer_settings` (which refers to the MoltenVK layer).  During my prototyping, it appears that layer loading is _not required_, but I am not sure whether this is design intent or accidental.  Please advise.

**Comment by billhollings** [comment]
> 1. ...The older `vkSetMoltenVKConfigurationMVK()` method allowed changes after instance creation, with restrictions based solely on the specific config variable. Is there any non-deprecated way to set/modify config values after calling `vkCreateInstance()`?

Unfortunately, no. Because `VK_EXT_layer_settings` works through `vkCreateInstance()`, there is no mechanism to change configuration after that.

While `vkSetMoltenVKConfigurationMVK()` does permit more flexibility in that respect, it does mix together two behaviour contracts, that of setting configuration information, and that of setting state information dynamically. As such, it's not really a clean design. A better mechanism would be to set configuration content once, and then allow some of it to be overridden dynamically via other extensions containing dedicated calls, or `pNext` structs passed into other existing calls. We'll address adding capabilities for that in the future, on an as-needed basis.

> 2. It is not clear to me whether the MoltenVK layer needs to be activated and loaded

I'm not entirely sure if I'm answering the question, but as a driver, the `"MoltenVK"` layer is always loaded, and this is intentional, and your results seems to be consistent with that.

**Comment by SRSaunders** [comment]
Thanks for your quick answers.

Re item 1, I think it will be fine for my application.  However, I previously used information from `vkEnumeratePhysicalDevices(vkInstance, ...)` to control changes via `vkSetMoltenVKConfigurationMVK()`.  For example I used to test `portabilityFeatures.imageViewFormatSwizzle` to decide whether to enable `pConfig.fullImageViewSwizzle`.  However, in this case I think I can just force `MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE` on for all cases, and MoltenVK will do the right thing under the covers and use the Metal swizzle feature if available.  Is this correct?

> I'm not entirely sure if I'm answering the question, but as a driver, the "MoltenVK" layer is always loaded, and this is intentional, and your results seems to be consistent with that.

Re item 2, that's good to know.  Can you confirm there is no difference for either the Vulkan loader or MoltenVK standalone if you enable (or not) the "MoltenVK" layer in `vkCreateInstance()`?  Is there any change in behaviour at all?

**Comment by juan-lunarg** [comment]
> Can you confirm there is no difference for either the Vulkan loader or MoltenVK standalone if you enable (or not) the "MoltenVK" layer in vkCreateInstance()? Is there any change in behaviour at all?

There is no change in behavior. Using the loader should not impact anything.

**Comment by billhollings** [comment]
> I used to test `portabilityFeatures.imageViewFormatSwizzle` to decide whether to enable `pConfig.fullImageViewSwizzle`.  However, in this case I think I can just force `MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE` on for all cases, and MoltenVK will do the right thing under the covers and use the Metal swizzle feature if available.  Is this correct?

Ah interesting use case. Thanks for identifying it.

But, yes. If native swizzle is available, MoltenVK will use it, and will not use the shader-based swizzle, even if it is enabled in configuration.

**Comment by SRSaunders** [comment]
Thanks for both of your answers.  Merry Christmas and Best Wishes for the New Year.

**Comment by billhollings** [comment]
> Thanks for both of your answers. Merry Christmas and Best Wishes for the New Year.

You're welcome. Thanks, and you too! 🎅🏻🎉
