### ISSUE TITLE
Problem with GL_EXT_buffer_reference

### ISSUE THREAD

**Issue by fknfilewalker** [KhronosGroup/MoltenVK#2111]
I wrote a modern hello world example where I draw a triangle via bindless rendering using buffer references. On Windows this works fine but on the latest MacOS (14.2.1) version with the latest Vulkan SDK (1.3.268.1) this just renders a black screen. Changing the clear color results in a different color. Hardcoding the vertices in the shader also works so the problem seems to stem from the buffer access using a device ptr. (M1 Pro Macbook)

Repo: https://github.com/fknfilewalker/vulkan-triangle-modern

What should work but does not
```glsl
layout(buffer_reference, scalar) readonly buffer Vertex
{ vec3 position; };
layout(push_constant, scalar) uniform pushConstant
{ uint64_t vertexPtr; };

void main() {
    Vertex vertex = Vertex(vertexPtr + sizeOfVec3 * gl_VertexIndex);
    gl_Position = vec4(vertex.position.xy, 0.0, 1.0);
}
```
This works
```glsl
void main() {
    vec3 vertices[3] = {
        {-0.5f, -0.5f, 0.0f },
        { 0.5f, -0.5f, 0.0f },
        { 0.0f,  0.5f, 0.0f }
    };
    gl_Position = vec4(vertices[gl_VertexIndex].xy, 0.0, 1.0);
}
```

**Comment by cdavis5e** [comment]
This appears to be related to #1846. Two others have hit the same problem. It looks like there's a problem with using a buffer reference from a push constant.

**Comment by fknfilewalker** [comment]
Ok good to know. 
I found the problem and it is not linked to push constants. Similar to the linked issue, the problem goes away when I add a vkCmdUpdateBuffer after the memcopy. So I guess the buffer does not get updated/flushed on the metal side without it.

**Comment by billhollings** [comment]
Thanks for reporting this, and submitting your sample app.

Here's what I'm getting from your sample app with the latest version of MoltenVK (from this repo). I assume this is what should be rendering? If so...is there something I need to modify within the app in order for it to demonstrate the issue?

<img width="874" alt="Screenshot 2024-01-02 at 8 45 30 PM" src="https://github.com/KhronosGroup/MoltenVK/assets/356402/3146c5f7-0641-4064-a6b5-15d5e5446635">

I assume this is

**Comment by fknfilewalker** [comment]
It should be fine as it is, I did not commit any bugfixes/workarounds for this issue.

I just tried it with the latest commit but it still does not work.
Is this the expected MoltenVK version or am I missing something else?
`[mvk-info] MoltenVK version 1.2.7, supporting Vulkan version 1.2.273.`
Or should I use the latest entry in the repos release tab instead?

**Comment by spnda** [comment]
> It should be fine as it is, I did not commit any bugfixes/workarounds for this issue. The result you showed is correct.

Yet you say "I just tried it with the latest commit but it still does not work.". Reading through your code it seems like everything is working precisely as it should be. The vertices are declared on the host and updated through mapping and then memcpy'ing the data. I also don't see a vkCmdUpdateBuffer in the code. I get the same output as Bill, though we don't know what you're expecting to see (or what happens on other platforms).

Can you please pinpoint what exactly you are experiencing and what isn't working and when? Using code and images would be best.

Btw I'd recommend not using pointer arithmetic on the GPU with manually calculating struct sizes, when you can just let GLSL take care of it:
```glsl
layout(buffer_reference, scalar) readonly buffer Vertices {
    vec3 positions[];
};
layout(push_constant, scalar) uniform pushConstant {
    Vertices vertexPtr;
};

void main() {
    vec3 position = vertexPtr.positions[gl_VertexIndex];
    gl_Position = vec4(position.xy, 0.0, 1.0);
}
```

**Comment by fknfilewalker** [comment]
I did not commit the code with the `vkCmdUpdateBuffer` fix which solves the problem similar to the issue linked by @cdavis5e.

With the SDK version as well as the freshly compiled MoltenVK dylib I get just the black background, while it should be what Bill posted.
<img width="867" alt="Screenshot 2024-01-03 at 09 43 08" src="https://github.com/KhronosGroup/MoltenVK/assets/15105596/3d540994-9854-4c0c-8215-ff1ad55c4129">

> Btw I'd recommend not using pointer arithmetic on the GPU with manually calculating struct sizes, when you can just let GLSL take care of it:

You are right, I just wanted to make the ptr casting more obvious.

**Comment by johnpayne-dev** [comment]
I am also getting a black screen when I run @fknfilewalker's app, although I'm not on the latest commit of MoltenVK, I'm using the version shipped with the latest sdk

**Comment by billhollings** [comment]
> I'm also using an M1 pro Mac

Interesting. I am using a M3 Pro. So it _might_ be hardware, although something so basic as rendering a triangle shouldn't be a differentiator.

**Comment by spnda** [comment]
> Interesting. I am using a M3 Pro, with successful results. 

I'm also using an M3 Pro and it works fine for me.

**Comment by johnpayne-dev** [comment]
So I see that `MVKDevice::addBuffer` adds a buffer to `_gpuAddressableBuffers` when a buffer is created with `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT`, which I do see happening in my program. But it looks like the only place that `_gpuAddressableBuffers` is used is in `MVKDevice::encodeGPUAddressableBuffers`, but when I set a breakpoint to that symbol I find that my program never calls into that function, is this normal?

**Comment by johnpayne-dev** [comment]
After a little bit more investigation, I'm seeing that `vkQueueSubmit` is calling into `MVKCommandEncoder::finalizeDrawState` but `MVKGraphicsResourcesCommandEncoderState::encodeImpl` is never being called, possibly because `_isDirty` was never set to true? It's hard to tell because I couldn't figure out how to get lldb to load the dSYM file so I'm reading through assembly..

**Comment by johnpayne-dev** [comment]
I think i've confirmed that the problem is that  `_graphicsResourcesState` is never being marked dirty. If I add a call to `vkCmdClearAttachments` into my program, then `MVKCmdClearAttachments<N>::encode` forces `_graphicsResourcesState` to be marked dirty, and sure enough my program starts working as intended.

I have no idea why this seems to be a hardware dependent problem though, I'm not familiar enough with this codebase to know when and when not command encoders are supposed to be marked dirty, I hope this helps though.

**Comment by fknfilewalker** [comment]
Yes, it is working for me now. Thank you for the fix.

**Comment by kanerogers** [comment]
I had a similar issue where a buffer address was set through a push constant, even on an M3. Building on main @ `37361ccd5595ff08c050981856903713f96221d2`solved this issue for me entirely - thank you!
