### ISSUE TITLE
fetchDependencies fails for new SDK 1.3.273

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2120]
When running **./fetchDependencies --macos** on the latest MoltenVK main, I get:

```
...
========== Vulkan-Tools ==========

Vulkan-Tools repo: https://github.com/KhronosGroup/Vulkan-Tools.git
Vulkan-Tools revision: afb8b9e8caeade2489372b8cf78b70b5301c8741
fatal: reference is not a tree: afb8b9e8caeade2489372b8cf78b70b5301c8741
```

**Comment by billhollings** [comment]
Thanks for reporting this. Looks like a Vulkan-Tools commit has gone missing during the lead-up to the SDK release.

This will be fixed today or tomorrow as the SDK environment gets finalized.

**Comment by billhollings** [comment]
PR #2121 fixes this. Closing now.
