### ISSUE TITLE
Once a swapchain is bound to a headless surface, its currentExtent is no longer -1

### ISSUE THREAD

**Issue by DUOLabs333** [KhronosGroup/MoltenVK#2129]
I'm not sure that this is the intended behavior of headless surfaces, but: when a headless surface is created, it has a currentExtent of (-1, -1) (of course, since VkDeviceSize is unsigned, this is just 0xFFFF...). However, once a swapchain is created on the surface, the `currentExtent` returned by `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` is now fixed to the `imageExtent` of the swapchain. This means that if you wanted to attach a swapchain with a larger extent to the surface, you can't, and would have to create a new surface.

Since the surface is headless, there shouldn't be a limit to the extent of any images presented to it.

**Comment by DUOLabs333** [comment]
An alternative may be to provide a MoltenVK way to resize headless surfaces.

**Comment by billhollings** [comment]
> This means that if you wanted to attach a swapchain with a larger extent to the surface, you can't, and would have to create a new surface.

The [Vulkan spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#headless) includes the following text:

> For headless surfaces, `currentExtent` is the reserved value (`0xFFFFFFFF`, `0xFFFFFFFF`). Whatever the application sets a swapchain’s `imageExtent` to will be the size of the surface, after the first image is presented.

Based on this text, MoltenVK updates the extent of a headless `VkSurface` from the swapchain extent, whenever a new swapchain is attached to it. So as far as MoltenVK is concerned, you can attach a new swapchain of any size to the surface, regardless of whether an older swapchain is already attached to that surface, and the surface extent will adjust accordingly.

What are you actually experiencing when you do this? Are you seeing Validation Layer errors? Is your app screening for (`0xFFFFFFFF`, `0xFFFFFFFF`) before attaching a new swapchain, and then not allowing it?

**Comment by DUOLabs333** [comment]
> Is your app screening for (0xFFFFFFFF, 0xFFFFFFFF) before attaching a new swapchain, and then not allowing it?

Yes, more specifically, `vkcube` looks for this. However, it seems that I can just override `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` to return `-1, -1`, and everything should work out, right?

**Comment by billhollings** [comment]
PR #2141 fixes this.

**Comment by DUOLabs333** [comment]
> Yes, more specifically, vkcube looks for this. However, it seems that I can just override vkGetPhysicalDeviceSurfaceCapabilitiesKHR to return -1, -1, and everything should work out, right?

I just tested this, and this does work (of course, this is just a hack).

**Comment by billhollings** [comment]
> of course, this is just a hack

Not so much a "hack". It's the same as the fix in PR #2141. 😉
