### ISSUE TITLE
vkCmdPipelineBarrier2: EXC_BAD_ACCESS (address=0x0)

### ISSUE THREAD

**Issue by HappyKian** [KhronosGroup/MoltenVK#2133]
Hi there! I meet a problem when calling vkCmdPipelineBarrier2. The compilation was successful, but my program threw a runtime error (EXC_BAD_ACCESS). 
I also tried the latest version SDK (1.3.275.0) and also the vkGetDeviceProAddr(device_, "vkCmdPipelineBarrier2") and got a nullptr. I would appreciate any thoughts you might have.

**Comment by billhollings** [comment]
> Hi there! I meet a problem when calling vkCmdPipelineBarrier2. The compilation was successful, but my program threw a runtime error (EXC_BAD_ACCESS).

Can you provide more info? Do you have a stack trace of the crash so we can see where the `EXC_BAD_ACCESS` is occurring?

> I also tried the latest version SDK (1.3.275.0) and also the vkGetDeviceProAddr(device_, "vkCmdPipelineBarrier2") and got a nullptr. I would appreciate any thoughts you might have.

If you are using the SDK Loader, MoltenVK does not advertise support for Vulkan 1.3 yet. So `vkCmdPipelineBarrier2` will not actually be available through the loader. Try using `vkCmdPipelineBarrier2KHR` instead.

**Comment by HappyKian** [comment]
The stack trace doesn't help. The EXC_BAD_ACCESS occurred when the program called vkCmdPipelineBarrier2, and no validation layer error output.

And I did try vkCmdPipelineBarrier2KHR but met a link error (no reference) when I compiled my program.

Finally, I have bypassed it using a trick. I use the following method:

> PFN_vkVoidFunction pVkCmdPipelineBarrier2KHR = vkGetDeviceProcAddr(device_, "vkCmdPipelineBarrier2KHR");
> ((PFN_vkCmdPipelineBarrier2KHR)(pVkCmdPipelineBarrier2KHR ))(commandBuffer, &depInfo);

**Comment by cdavis5e** [comment]
> And I did try vkCmdPipelineBarrier2KHR but met a link error (no reference) when I compiled my program.
>
> Finally, I have bypassed it using a trick. I use the following method:
> 
> > PFN_vkVoidFunction pVkCmdPipelineBarrier2KHR = vkGetDeviceProcAddr(device_, "vkCmdPipelineBarrier2KHR");
> > ((PFN_vkCmdPipelineBarrier2KHR)(pVkCmdPipelineBarrier2KHR ))(commandBuffer, &depInfo);

Well, yeah. That's what you have to do to use an extension function. 😉 IIRC only the core and WSI functions are directly exported from the Vulkan loader.

**Comment by HappyKian** [comment]
Thanks @billhollings and @cdavis5e!
