### ISSUE TITLE
Missing VkPhysicalDeviceVulkan13Features support

### ISSUE THREAD

**Issue by maksym-pasichnyk** [KhronosGroup/MoltenVK#2143]
I'm trying to enable VK_KHR_synchronization2 extension without VkPhysicalDeviceSynchronization2Features, but it doesn't work.
VkPhysicalDeviceSynchronization2Features is provided by VK_VERSION_1_3 and VkPhysicalDeviceVulkan13Features also provided by VK_VERSION_1_3, so it's strange why MoltenVK doesn't support VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES

```c++
auto Core_1_1 = VkPhysicalDeviceVulkan11Features{
    .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES,
    .pNext = {}
};
auto Core_1_2 = VkPhysicalDeviceVulkan12Features{
    .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES,
    .pNext = &Core_1_1
};
auto Core_1_3 = VkPhysicalDeviceVulkan13Features{
    .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES,
    .pNext = &Core_1_2,
    .synchronization2 = VK_TRUE
};
auto Features2 = VkPhysicalDeviceFeatures2{
    .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,
    .pNext = &Core_1_3,
    .features = {}
};
```

**Comment by billhollings** [comment]
MoltenVK does not [yet](https://github.com/KhronosGroup/MoltenVK/issues/1930) support Vulkan 1.3.

Until it does, you need to use the `VK_KHR_synchronization2` structs and functions.
