### ISSUE TITLE
Question: Guidance re MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS option

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2146]
Are there any docs that provide performance guidance on the use of the `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` option?

Up to this point I have been using the setting `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS_DESCRIPTOR_INDEXING` based on the assumption that performance will be improved.  However, empirical evidence shows that I get slightly better performance (~5%) with it set to `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS_NEVER`, especially on my Apple Silicon M1 Air. On my x86 + AMD GPU machine, improvements are also observable with the setting off (i.e. never) but perhaps less pronounced  (<5%) than on the M1.

And using `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS_ALWAYS` gives the same results as `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS_DESCRIPTOR_INDEXING`.  This is expected since `VK_EXT_descriptor_indexing` is enabled for my application.

I am inclined to turn this setting off, but are there any hints or advice on how I should set this option?  Note that I am using push constants almost exclusively for my app so I am not sure how this plays into it.

**Comment by billhollings** [comment]
For now, the big differentiator is how many resources you need. If you can get away with the very small number (31/128) of descriptor resources that are available to Metal without argument buffers, then you can leave `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` disabled.

BTW, the next round of development on this in the next couple of months, should see us move to argument buffers being used by default, particularly when Metal 3 is available.

**Comment by SRSaunders** [comment]
Thanks for the info and heads-up re new developments coming down the pipe.

**Comment by DUOLabs333** [comment]
> BTW, the next round of development on this in the next couple of months, should see us move to argument buffers being used by default

How would this affect `maxSamplerAllocationCount`? With `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=0`, this is `1073741824`, but with `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1`, this is `1024`. With `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1`, this breaks gzdoom (a shader was not able to be successfully compile). This does seem to be fixed in 1.2.11 though.

**Comment by billhollings** [comment]
> > BTW, the next round of development on this in the next couple of months, should see us move to argument buffers being used by default
> 
> How would this affect `maxSamplerAllocationCount`? With `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=0`, this is `1073741824`, but with `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1`, this is `1024`. With `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1`

When Metal Argument Buffers are **_not_** in use, Metal doesn't formally limit the number of samplers that can be created, hence the essentially infinite value returned in `maxSamplerAllocationCount`.

However, Metal does limit the number of samplers that can be used in Metal argument buffers. Therefore, when Metal argument buffers **_are_** in use, MoltenVK returns the limit in `maxSamplerAllocationCount`.

> this breaks gzdoom (a shader was not able to be successfully compile). This does seem to be fixed in 1.2.11 though.

Can you provide more info on what is/was breaking?

**Comment by DUOLabs333** [comment]
On 1.2.9 (the current version packaged by nixpkgs), when starting, a SPIR-V to MSL conversion fails if `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1` --- this error goes away on 1.2.11.

**Comment by DUOLabs333** [comment]
However, after some more testing, 1.2.11 breaks vkdoom, regardless of whether metal argument buffers were used or not --- the error messages are different though:
`MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=0`:
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:429:12: warning: unused variable 'ray_end'
    float3 ray_end = origin + (dir * tmax);
           ^
program_source:587:464: error: cannot reserve 'texture' resource locations at index 0
fragment main0_out main0(main0_in in [[stage_in]], device SurfaceIndexBuffer& _608 [[buffer(1)]], device SurfaceBuffer& _604 [[buffer(2)]], device LightBuffer& _941 [[buffer(3)]], device LightIndexBuffer& _945 [[buffer(4)]], device PortalBuffer& _696 [[buffer(5)]], device ConstantsBuffer& _904 [[buffer(6)]], device NodeBuffer& _131 [[buffer(7)]], device VertexBuffer& _285 [[buffer(8)]], device ElementBuffer& _289 [[buffer(9)]], array<texture2d<float>, 16536> textures [[texture(0)]], array<sampler, 16536> texturesSmplr [[sampler(0)]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ^
program_source:587:511: error: cannot reserve 'sampler' resource locations at index 0
fragment main0_out main0(main0_in in [[stage_in]], device SurfaceIndexBuffer& _608 [[buffer(1)]], device SurfaceBuffer& _604 [[buffer(2)]], device LightBuffer& _941 [[buffer(3)]], device LightIndexBuffer& _945 [[buffer(4)]], device PortalBuffer& _696 [[buffer(5)]], device ConstantsBuffer& _904 [[buffer(6)]], device NodeBuffer& _131 [[buffer(7)]], device VertexBuffer& _285 [[buffer(8)]], device ElementBuffer& _289 [[buffer(9)]], array<texture2d<float>, 16536> textures [[texture(0)]], array<sampler, 16536> texturesSmplr [[sampler(0)]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
```

`MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS=1`:
```
[mvk-error] SPIR-V to MSL conversion error: Argument buffer resource base type could not be determined. When padding argument buffer elements, all descriptor set resources must be supplied with a base type by the app.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Fragment shader function could not be compiled into pipeline. See previous logged error.
```

**Comment by DUOLabs333** [comment]
Hmm..., for some reason, I'm getting this error again on 1.2.11 --- maybe it's something I did (I didn't change much from then to now):
```
SPIR-V to MSL conversion error: Full mutable aliasing of argument buffer descriptors only works on Metal 3+.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline. See previous logged error.
```

EDIT: Never mind -- it turns out that I have two versions installed, and the loader is choosing 1.2.9 over 1.2.11.
