### ISSUE TITLE
MVK_USE_METAL_PRIVATE_API is not mentioned in MoltenVK_Configuration_Parameters

### ISSUE THREAD

**Issue by jeroenbakker-atmind** [KhronosGroup/MoltenVK#2153]
`MVK_USE_METAL_PRIVATE_API` is mentioned in the build instructions and release notes, but I also expected it in the configuration parameters.

**Comment by cdavis5e** [comment]
That's because you can't set it at run time. It's a build-time setting only.

**Comment by jeroenbakker-atmind** [comment]
Ah yes you're right. I will close this issue.
