### ISSUE TITLE
Use of undeclared identifier 'CAMetalLayer'

### ISSUE THREAD

**Issue by jinjuezhou** [KhronosGroup/MoltenVK#222]
run` API-Samples-iOS`

I have Receive a mistake：Use of undeclared identifier 'CAMetalLayer' Inside the DemoViewController.mm page

**Comment by billhollings** [comment]
@jinjuezhou 

Can you provide further information, please?

Are you using MoltenVK from this repository...or are you using it as part of LunarG's Vulkan SDK?

How are you attempting to build the sample?

**Comment by billhollings** [comment]
@jinjuezhou

You will encounter that error if you try to run the samples on an Xcode iOS simulator instead of an actual device.

The Xcode iOS device simulator does not support Metal. You must run iOS Metal apps (including MoltenVK) on an actual iOS device.
