### ISSUE TITLE
maxPerStageDescriptorUpdateAfterBindSamplers  = 16 on an M1 MAX

### ISSUE THREAD

**Issue by ashkann** [KhronosGroup/MoltenVK#2227]
Hello. Running the latest SDK on a Mac Book Pro (M1 MAX), the `maxPerStageDescriptorUpdateAfterBindSamplers` and not the other one (`maxPerStageDescriptorSamplers`) is still `16`. This is preventing me from doing bindless. I'm not sure I'm understanding it all correctly but this should be much much higher than 16, no ? 

![image](https://github.com/KhronosGroup/MoltenVK/assets/1901570/47817997-0da3-43e9-8035-9c62fcf7602f)

Trying to exceed the limit results in a validation error (as expected):

![image](https://github.com/KhronosGroup/MoltenVK/assets/1901570/0f2dd849-aca7-47c4-be73-90b48c08d384)

**Comment by billhollings** [comment]
1. Have you enabled the configuration parameter `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS`? If not, see the _Configuring MoltenVK_ section of `Docs/MoltenVK_Runtime_UserGuide.md` to learn how to do that.

2. Are you running on a GPU that supports Tier 2 argument buffers? On macOS, that would generally be either Apple Silicon, or a discrete GPU.

**Comment by ashkann** [comment]
@billhollings thank you for the quick reply

1. Setting the `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` to `1` or `2` makes the validation error disappear but now my application doesn't work (it was working before since I wasn't in reality using that many descriptors).

2. The chip is reported as `INTEGRATED` in the gpu database. 
<img width="372" alt="image" src="https://github.com/KhronosGroup/MoltenVK/assets/1901570/a7120755-ed9a-48e2-8725-1e490517882d">

**Comment by ashkann** [comment]
Closing since basically got the answer.

**Comment by DUOLabs333** [comment]
@ashkann Did you find a way to get values higher than 1024?

**Comment by billhollings** [comment]
> @ashkann Did you find a way to get values higher than 1024?

This is a Metal value, as determined from [`MTLDevice.maxArgumentBufferSamplerCount`](https://developer.apple.com/documentation/metal/mtldevice/2977322-maxargumentbuffersamplercount?language=objc), which currently returns 1024 for Apple Silicon.
