### ISSUE TITLE
ISO C++11 warnings for constexpr modifier on mvkGetReportingLevelString()

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2229]
Adding `constexpr` to `mvkGetReportingLevelString()` results in many clang warnings.

_ISO C++11 does not allow conversion from string literal to 'char *'_

I am using Ventura 13.6.6 with Xcode 15.2

(adding this here in case you did not see comment on closed PR #2224)

**Comment by SRSaunders** [comment]
I can see that you fixed this in d2677a69c0f3f9b9c7f2f99d53fa048bd523a4d6

Thanks, closing

**Comment by billhollings** [comment]
Yeah. Sorry That was my bad. That's what I get for using GitHub UI to change code functionality!

I should have just pulled your code in and tested locally to see if it warranted any mods.

Sorry for introducing the confusion. 🤦🏻‍♂️ 

And thanks for aiming to fix it.

**Comment by SRSaunders** [comment]
No worries, thanks for fixing.
