### ISSUE TITLE
Vulkan 1.1

### ISSUE THREAD

**Issue by binary132** [KhronosGroup/MoltenVK#223]
Hello.

Sorry if this has already been asked, but I noticed this project targets Vulkan 1.0, even though it was released quite recently.  Is there a plan to support 1.1?

**Comment by billhollings** [comment]
Yes...MoltenVK currently supports Vulkan 1.0, plus several extensions.

Currently the focus is on conformance and optimizing for Vulkan 1.0. We will definitely be working to support Vulkan 1.1 as soon as we can.
