### ISSUE TITLE
Adding constexpr modifiers to functions returning C++ string literal

### ISSUE THREAD

**Issue by ByunghoonKim** [KhronosGroup/MoltenVK#2239]
Hi, I stumbled upon #2229 a bit late. I do not want to disrupt an already closed issue thread, hence opening a new one here.

From [cppreference](https://en.cppreference.com/w/cpp/language/constexpr),

> A constexpr specifier used in an object declaration or non-static member function(until C++14) implies const. A constexpr specifier used in a function or [static](https://en.cppreference.com/w/cpp/language/static) data member(since C++17) declaration implies inline.

My understanding is that you should not omit `const` when you add `constexpr` to a function. Like,
 ```static constexpr const char* mvkGetReportingLevelString(MVKConfigLogLevel logLevel) {```

If this approach works, couldn't many functions returning string literal in `macOS/include/vulkan/vk_enum_string_helper.h`, `macOS/source/SPIRV-Reflect/spirv_reflect.h`, etc., be turned into `constexpr` functions as well?

**Comment by cdavis5e** [comment]
Of course, but many of those aren't our sources, but are from other Khronos projects. I suppose we could look at doing this for our own sources, but for the rest, you'll have to take it up with the owning projects, e.g. [KhronosGroup/SPIRV-Reflect][1].

[1]: /KhronosGroup/SPIRV-Reflect/issues

**Comment by ByunghoonKim** [comment]
Thank you for the quick reply, and your effort going into this project in general.
 I realized that simply `grep`ping VulkanSDK directory and reporting results here wasn't a prudent idea. Indeed it seems the large portion of my grep result was from [KhronosGroup/Vulkan-Utility-Libraries](https://github.com/KhronosGroup/Vulkan-Utility-Libraries) and [KhronosGroup/SPIRV-Reflect](https://github.com/KhronosGroup/SPIRV-Reflect). I will reconsider whether this is an exercise worth a while, and open issues there if necessary.
