### ISSUE TITLE
MSAA with resolveMode=SAMPLE_ZERO uses a compute kernel, even on Apple silicon devices

### ISSUE THREAD

**Issue by stripe2933** [KhronosGroup/MoltenVK#2254]
Also, it requires non-transient attachment. Why this happened? Seems like resolveMode=AVERAGE uses tile based resolve.

**Comment by billhollings** [comment]
The decision to run the resolve compute kernel is not based on the `resolveMode`, but on whether Metal and your GPU support natively resolving the pixel format you are using.

Metal describes which combination of formats and GPUs support native MSAA in the back half of [this document](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf).

Which GPU and pixel format are you using?

For native MSAA on the GPU, Metal uses the equivalent of `AVERAGE`. For simplicity, MoltenVK uses `SAMPLE_ZERO` in the compute kernel when native MSAA is not supported.

If there is demand for it, as an enhancement, we could add support to the kernel function to resolve the other resolve modes. We could also run the compute kernel anytime a resolution mode other than `AVERAGE` is requested.

Regarding the second question, MoltenVK does not yet support tiling shaders.

**Comment by stripe2933** [comment]
I was using R32Uint for 4x MSAA to render gl_InstanceIndex (since the depth attachment was 4x MSAA, there were no other options). As you mentioned, the native resolve is not supported for this format. I decided to separate the instance index rendering pass, so it’s not a problem anymore. Anyway, thank you for your answer.
