### ISSUE TITLE
Does the new Argument Buffer code support the iOS Simulator?

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2266]
Kudos on the new argument buffer code.  I have tested this on macOS (Ventura 13.6.6) and iOS (latest iOS 17.5.1 on iPhone 15) with the _descriptor indexing sample_ in Sascha Willem's repo as well as a _modified descriptor indexing sample_ in the official Vulkan samples repo.  Both are working well.

However, I tried the new code on the iOS simulator and it does not appear to work (missing `VK_EXT_descriptor_indexing`) .  Is this intentional, a limitation of the iOS Simulator,  or an oversight?

Also, it appears that issue #2246 is **not** solved by the new code.

**Comment by AlexanderDevaikinEnscape** [comment]
AFAIK simulator has a very small subset of an old Metal version supported, I would not expect recent features to be present there even on the Metal level => MoltenVK has even less chances to have it implemented for simulator.

**Comment by SRSaunders** [comment]
Closing this since my main concern is covered in #2285:

Should `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` be defaulted to 0 (i.e. disabled) on the iOS Simulator?
