### ISSUE TITLE
Unnecessary 'Metal does not support disabling primitive restart' warnings

### ISSUE THREAD

**Issue by kocdemir** [KhronosGroup/MoltenVK#2279]
Primitive restart is disabled by default on OpenGL and some Vulkan apps, and this is causing too many warnings from MoltenVK due to the possible usage of the restart index value in the index buffer. Issue #1521 highlights a possible problem and there is a solution proposal with a spec change but that unfortunately won't change the status quo much until the applications and ANGLE starts using it. On the other hand, it's not a commonly used path and most of the warning messages are actually not very helpful, as highlighted in the [code](https://github.com/KhronosGroup/MoltenVK/blob/main/MoltenVK/MoltenVK/Commands/MVKCommandEncoderState.mm#L602). So I was wondering if it would be possible to reduce down the false positives. 

Since it'd be too costly to look into every index value in the index buffer bound, my proposal is to move the warning message to draw call time (maybe with a special compile-time setting), and check the length of the bound vertex buffers to see if it's actually possible to use the restart value from the index buffer? E.g. In the example of #1521 with 16-bit index buffer with 0xffff restart index, vertex buffer needs to have at least 2^16 items after the offset. If it's a smaller vertex buffer in use, it should be safe to assume that the index buffer won't have the restart value used and not give a warning. Not sure how tricky it'd be with different draw call cases and if all the necessary states are already tracked though.

Thanks

**Comment by alyssarosenzweig** [comment]
what if the vertex shader uses gl_VertexID?

**Comment by ncesario-lunarg** [comment]
I'm also curious how `gl_VertexID` could be used here. It does sound a bit invasive, but I'm not sure I'm understanding what the approach would be.

**Comment by ncesario-lunarg** [comment]
@kocdemir Is the only issue that needs to be addressed here the warning output frequency? I don't know if MoltenVK has any way of filtering warning messages, but would that perhaps also be a solution if available?

**Comment by kocdemir** [comment]
MoltenVK has logging levels to filter warnings but this and other warnings can actually be important for some apps and would be good to reduce the false positives only. In case of complexity or a performance regression, one approach here can be implementing this with a compile option (e.g MVK_CONFIG_VALIDATE_DRAW_CALLS), and moving/copying it into VVL after the suggested spec changes are released.

To cover `gl_VertexID` usage in the shaders case, e.g. with random buffer fetches with modified indices, it might be enough to always allow the warning when there is no vertex buffer bound, as it won't be easy to calculate the index buffer range used.

**Comment by billhollings** [comment]
> As for a longer-term solution, we should definitely move the log warning from the individual render pass level to something higher scope. I'm going to propose moving it to pipeline creation time, and issue the warning if the pipeline is created either with `primitiveRestartEnable` disabled, or with `VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE`, indicating that the app intends to dynamically disable it at some point.

PR #2296 implements this logging change.

If this fixes the problem reported here, please close this issue.

**Comment by kocdemir** [comment]
That should reduce down the amount of warning messages, and with that change, I guess it makes more sense to implement state and data based warning/error messages directly into VVL once the extension is released then. 

Thanks!
