### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by ioquatix** [KhronosGroup/MoltenVK#228]
I feel like the build process could be improved.

- I just want to build a static library which I can link to add support for Vulkan.
- I already have SDK headers in the app.
- I'd rather explicitly handle dependencies.
- I'd rather avoid using Xcode explicitly to build things.

It would be nice if dependencies could be explicitly documented, and a complete build process to generate static libraries was available.

I feel like for my use case (headless rendering) it would be nice if there was a simpler build process.

**Comment by ioquatix** [comment]
So, here is the first issue I found while trying to compile a static library.

In `Vulkan/mvk_datatypes.mm`, you have `#include "MVKEnvironment.h"`. However, this should be a relative path, i.e. `#include "../Utility/MVKEnvironment.h"`. This is a problem in several areas of the code base.

**Comment by ioquatix** [comment]
I think the reason why this happened was because Xcode doesn't respect directory structure, in the project you can include a header from any file without "worrying" about the pesky file system structure. But with normal build/compiler, it's not possible.

**Comment by billhollings** [comment]
@ioquatix 

Thanks for your thoughts.

As an Apple-focused project that depends on optimized workflow from numerous contributors, this project needs to retain its Xcode focus.

There may be some basic changes that we can make, such as modify file-include references to include the file structure. 

We can also generate a separate static library if it makes sense...but can you clarify why the existing static MoltenVK framework doesn't meet the need for static linking?

Beyond that...if a `cmake`-based workflow is desirable for some development streams...I encourage anyone who is interested in building and maintaining it to do so and submit a PR.

**Comment by maddanio** [comment]
i have problems building the most recent version. steps from readme:
`./fetchDependencies `
`xcodebuild -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK (Debug)" build`
fetchDependencies has a problem:
```
[2/2] cd /Users/daniel/Documents/git/MoltenVK/External/glslang/build/External/spirv-tools && /usr/...s/daniel/Documents/git/MoltenVK/External/glslang/External/spirv-tools/cmake/write_pkg_config.cmake
make: *** No rule to make target `install'.  Stop.
```
that seems to make the build fail:
```
MasterObjectLink build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/MoltenVK-x86_64-master.o
    cd /Users/daniel/Documents/git/MoltenVK/MoltenVK
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld -r -arch x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MTLRenderPipelineDescriptor+MoltenVK.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKResource.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKDescriptorSet.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MTLTextureDescriptor+MoltenVK.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCommandResourceFactory.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCommandEncodingPool.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKWatermark.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKBaseObject.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/NSString+MoltenVK.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKOSExtensions.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/vulkan.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKSurface.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKQueryPool.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKInstance.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKDeviceMemory.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKImage.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCommandPool.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCmdDraw.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCommandBuffer.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCmdRenderPass.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKBuffer.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/mvk_datatypes.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKExtensions.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKFoundation.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKDevice.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MTLRenderPassDescriptor+MoltenVK.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKPipeline.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKQueue.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MTLSamplerDescriptor+MoltenVK.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKRenderPass.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCmdTransfer.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCmdQueries.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/vk_mvk_moltenvk.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKSwapchain.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCommandEncoderState.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKGPUCapture.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCommand.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKShaderModule.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKSync.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCmdPipeline.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKLayers.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKFramebuffer.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKMTLBufferAllocation.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/CAMetalLayer+MoltenVK.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/x86_64/MVKCmdDispatch.o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/Debug/MoltenVKSPIRVToMSLConverter.framework/MoltenVKSPIRVToMSLConverter -o /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/MoltenVK.build/Debug/MoltenVK-macOS.build/Objects-normal/MoltenVK-x86_64-master.o
ld: file not found: /Users/daniel/Documents/git/MoltenVK/MoltenVK/build/Debug/MoltenVKSPIRVToMSLConverter.framework/MoltenVKSPIRVToMSLConverter
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld failed with exit code 1
```

**Comment by billhollings** [comment]
@maddanio 

What's your development environment? 

Are you using MoltenVK directly, or the LunarG SDK?

Which macOS and Xcode versions are you using?

**Comment by maddanio** [comment]
i downloaded the moltenvk source from here, checked out the tag corresponding to the latest lunar release and did the above calls.
xcode version:
Xcode 9.4.1
Build version 9F2000
os version:
10.13.4

**Comment by maddanio** [comment]
since it fetches all of its dependencies itself xcode+os are the only relevant build env details, or am i wrong?

**Comment by billhollings** [comment]
@maddanio 

When I download MoltenVK 1.0.20 and build using the command you used:

    ./fetchDependencies
    xcodebuild -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK (Debug)" build

I do not encounter any errors...and can run the Demos just fine.

The `No rule to make target `install'` warning does occur during the building of `SPRIV-Tools` from `fetchDependencies` does occur...but it does not have any impact on the subsequent building of MoltenVK.

I am running Xcode 9.41. (9F2000) on macOS 10.13.6...but the OS version shouldn't have any impact. My Xcode command line tools are set to use Xcode 9.41. (9F2000) too.

**Comment by kode54** [comment]
Further improve the build process, or at least the build docs: The command line and other parts describe a "MoltenVK (Release)" or "MoltenVK (Debug)" scheme, but the only relevant schemes I see for building the packages are called "MoltenVK Package (Release)" and "MoltenVK Package (Debug)".

**Comment by billhollings** [comment]
@kode54 

Ah...that was a recent change...to accommodate single-platform builds...and I guess I forgot to update the doc.

Nice catch...will fix.

**Comment by binary132** [comment]
> As an Apple-focused project that depends on optimized workflow from numerous contributors, this project needs to retain its Xcode focus.

I question the attitude toward your users that prioritizes the convenience of contributors.  This project is [supposed to facilitate](https://www.khronos.org/vulkan/portability-initiative) portability of Vulkan (i.e., non-Apple) applications, isn't it?

Practically every serious open-source C++ library supports first-class CMake usage.  If I get around to supporting Apple in my build chain, I will see if I can contribute CMake scripts to MoltenVK, but since a) the build process is complicated and poorly documented, and b) MoltenVK does not have 1.1 parity yet, that doesn't seem likely to fit into my limited time budget.

**Comment by ioquatix** [comment]
I think the simplest way to make this work is to:

- List any dependencies - they can be supplied by user in a standard way, e.g. using `pkg-config` and `CFLAGS`.
- Ensure the build process of the library is as simple as compiling all `.c`, `.cpp`, and `.m`, .mm` files, and copying all headers.
- User can choose to compile static or dynamic library as required.
- Retain the Xcode framework, but ensure that a static build using a basic compiler works.
- Expose a Makefile or CMake file which does this (Makefile is more generic IMHO).

**Comment by billhollings** [comment]
Currently, the command-line build process uses _Xcode_ to create both a framework and a dynamic library:

    xcodebuild -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (Release)" build

As I understand it...there are a couple of parts to this discussion:

1. The ability to create a static library instead of the framework from the command-line.
2. The creation of a parallel `make` or `cmake` build process that would run completely independently of `Xcode`.

Providing (1) should be fairly straightforward. That would then allow the above `xcodebuild` command-line process to be included in a general build environment to spit out a static library. 

If that was available...is there a use case for the effort required to build and maintain (2)?

**Comment by ioquatix** [comment]
I don't really mind how the build process works, as long as it's possible to create a static library and install it (along with headers) somewhere. I think we could start with (1) and that doesn't preclude implementing (2) in the future. I'm not really expecting anyone to invest a huge effort to make this possible or maintain it, but it would be good if it was at least possible.

**Comment by ioquatix** [comment]
As an example, I'd be happy to rework the `#include` directives to respect the local directory structure. That's the first step. There might be other issues that need to be addressed. It's not just a problem for the build, but for other tools that don't use Xcode to build things. The way I see it, is it should be possible to install this into `/usr/local/` and then build other things against it. This could be a package in HomeBrew and/or MacPorts. It would be awesome.

**Comment by binary132** [comment]
Here's my use-case for (2).

As a Vulkan game engine developer, I want to provide straightforward cross-platform build for my nascent engine / game, to make it easy for contributors to work on or use it across various platforms, without having to support multiple build chains or IDEs.  So, I'm writing my build pipeline in CMake.

My engine user checks out the engine repo, initializes its git submodules, and either adds it to their own CMake build script, or builds and installs it directly.  They do not need to manually build or install its dependencies.  They do not need to specify the location of library headers in their build process.  They can just grab my source and all of its deps, and build it in one shot, trivially.

This is easily supported by CMake, but only if all of my dependencies support a CMake build.  Most of them do, but a few of them are Makefile based, which is usually pretty simple to bolt on CMake support for (LZ4 and GLAD were both like 3 lines of CMake.)

This one is not so simple.

**Comment by binary132** [comment]
For reference, here is an example of a CMake-based project very similar to the one I described, which ships its dependencies in a `third_party` subfolder.

Here is the CMakeLists.txt file in the project root, where they add their dependency on `moltenvk`:
https://github.com/google/filament/blob/473824b15e9cf2cbeacd4a9383ed5a438560be4c/CMakeLists.txt#L285-L287

Here is the CMakeLists.txt implementation for the `moltenvk` dependency:
https://github.com/google/filament/blob/473824b15e9cf2cbeacd4a9383ed5a438560be4c/third_party/moltenvk/tnt/CMakeLists.txt#L13-L27

Note that this was only able to be accomplished _by adding the compiled library itself_ to the source tree.  Not only is that an insecure practice, and a Git antipattern, but it still does not lend itself to build automation, since if a bugfix is introduced in the MoltenVK upstream, it must be imported to the project manually using the usual MoltenVK build process, and re-vending the dependency, instead of simply using source control and CMake the way they are meant to be used.  😄

**Comment by karl-lunarg** [comment]
> The way I see it, is it should be possible to install this into /usr/local/ and then build other things against it. This could be a package in HomeBrew and/or MacPorts. It would be awesome.

Someone is working on a HomeBrew recipe for installing the latest LunarG macOS SDK to /usr/local.  It just takes the pre-built binaries from the SDK and copies them into the right places under /usr/local.  Presumably it will copy the MoltenVK library as well,  It isn't the same as building from sources and would need to be updated to track SDK releases (unless there's some automatic way to do that in HomeBrew), but there may be some value to this approach for some scenarios.

**Comment by binary132** [comment]
>there is less "need" to make it based on CMake

What I'm getting at is, adding a dependency on MoltenVK currently implies either porting the user project's toolchain to XCode (non-starter) or including statically-compiled binaries in the user codebase (non-starter for public projects imo, probably fine for trusted internal usage.)

I just want it to be simple for MVK users to drop it in as a dependency.  It is true that doesn't necessitate the whole thing lives in CMake land.

From this user's perspective, the order by value-add is like this:

1. MoltenVK exports a CMake module definition, with a library build (instead of "Framework").  That way, I can ship it in my build and use `find_package` to link my libs to it.
2. MoltenVK (or someone) defines a Homebrew package so contributors to MVK user code can easily `brew install moltenvk` and get on with their build.  If MVK maintains this, it's less likely to rot.  🤷‍♂️
3. MoltenVK has a build that can be reliably automated as a CMake custom command, so user code can include the MVK source tree, define its build in-pipeline, and ship it as a dependency artifact.
4. CMake is supported as a first-class citizen in MoltenVK so the user code can rebuild it incrementally after source update, depend on CMake metadata (such as MVK version number) from the MVK build step, configure the MVK build, support different backend toolchains, etc.

**Comment by billhollings** [comment]
Thanks for all the input.

As @karl-lunarg mentions...a CMake build process would definitely be helpful and useful...but since MoltenVK never needs to be built anywhere else...such a system is not a top priority right now.

From what I read above...in terms of priorities...we can focus on getting (1) done...while still relying on an `xcodebuild` compilation step. Moving forward...we can explore the other options against other priorities.

And...as always...priorities are relative...and we would be grateful for any contributions that take us in this direction from devs who feel the need for this most acutely...and who can bring the necessary  CMake expertise to bear.

**Comment by maddanio** [comment]
First up: very cool that you effectively donated this to vulkan. So we cannot expect you to do our work :). still i think cmake is a good option, even on osx. i and probably many others try to avoid platform specific tools, as they strongly constrain portable projects. for example if i have a cross platform project it can have platform specific dependencies, and just pulling in mvk via cmake or homebrew is a _lot_ less work than having to engineer around xcode build inside a cmake or other project.

**Comment by kode54** [comment]
> Hi again! I'm reviewing the Filament build for #307 (see [#228 (comment)](https://github.com/KhronosGroup/MoltenVK/issues/228#issuecomment-429653879) for link) and I noticed they also ship `libvulkan.1.dylib` and `MoltenVK_icd.json` with the `moltenvk` custom target. I had assumed the vendor distributes `libvulkan`, and that `libMoltenVK` would wrap it as necessary. Can you set me straight (maybe @billhollings?) I got `libMoltenVK` out of the MoltenVK build, but the other bits are not clear. (Again, trying to automate the build, so if downloading the SDK is really necessary, so be it, but it would be better if I could build from source.) Thanks in advance!

Hi, I'd like to point out that MoltenVK is designed explicitly for Apple operating systems, and with Apple being the vendor, the vendor is not likely to ever ship their own libvulkan, hence why this wrapper exists in the first place. In fact, the only other libvulkan implementation for macOS at this time is [gfx-portability](https://github.com/gfx-rs/portability/releases).

**Comment by billhollings** [comment]
@binary132 

> I had assumed the vendor distributes libvulkan, and that libMoltenVK would wrap it as necessary.

I'm not sure what you mean here...but `libMoltenVK.dylib` doesn't wrap `libvulkan.dylib`.

`libMoltenVK.dylib` provides the implementations of all the Vulkan calls...and represents the Vulkan driver on Apple products. So linking to that is all you need...as you can see by the Demo apps in this MoltenVK repo. And as you indicate is your desire...you can build `libMoltenVK.dylib` from the source in this MoltenVK repo.

`libvulkan.dylib` and `libvulkan.1.dylib` come from LunarG's Vulkan SDK...which provides the layering abstraction that allows you to run additional validation and debugging layers and tools...but they are not strictly needed in a distributed app.

**Comment by billhollings** [comment]
@ioquatix & @binary132 

PR #325 adds the creation of a static library (along with dynamic library and framework).

That PR also includes a basic `Makefile` to use `make` to build MoltenVK from the command line. It still depends on having Xcode installed on the system...but should simply integration into a larger `make` build environment.

Let us know if these additions help your process integration.

At this point...it might be good to close this issue now...and restart a new issue dedicated to a more comprehensive `CMake` process...if it is required.

**Comment by ioquatix** [comment]
Thanks!
