### ISSUE TITLE
Was Vulkan SDK 1.3.290 released with MoltenVK 1.2.9?

### ISSUE THREAD

**Issue by SRSaunders** [KhronosGroup/MoltenVK#2287]
I thought SDK 1.3.290 would contain MoltenVK 1.2.10.  Did the SDK or MoltenVK release plans change?

**Comment by KarenGhavam-lunarG** [comment]
Per the release notes issued with the macOS SDK release:

> For this SDK release we are keeping the previous MoltenVK version 1.2.9 due to some stability issues in the 1.2.10 release.

**Comment by SRSaunders** [comment]
Thanks @KarenGhavam-lunarG for the explanation.  Too bad, but I understand.
