### ISSUE TITLE
Triangle fans...

### ISSUE THREAD

**Issue by mlfarrell** [KhronosGroup/MoltenVK#229]
I know these aren't supported, but I really could use them.  My engine uses fans in a number of less-performance-critical rendering paths to easily emulate quad rendering (rendering 4 verts in CCW order to form a quad out of two triangles).  It'd be amazing if I didn't have to manually emulate triangle fans in vulkan.  

Consider this a humble feature request.

**Comment by billhollings** [comment]
@mlfarrell 

This is a tough one. Triangle fans are not natively supported by Metal.

Do you have suggestions for an implementation?

**Comment by kvark** [comment]
> rendering 4 verts in CCW order to form a quad out of two triangles

Can't you switch to triangle strips instead? If the order of vertices is critical, you can always render with an index buffer.

**Comment by billhollings** [comment]
Closing as there is nothing to be done.
