### ISSUE TITLE
vkQueueSubmit is leaking 13 GB of memory at every call when using an SSBO

### ISSUE THREAD

**Issue by tomaka** [KhronosGroup/MoltenVK#2307]
Hi,

Hardware: Apple M2
MoltenVK version: happens on both v1.2.8 and v1.2.9 (I haven't tried any newer version, as I'm simply installing the Vulkan SDK).

My toy engine is working well on MacOS. However, as I added an SSBO then did a small tweak to increase its size from ~400kiB to ~10MiB (increasing the level of details of a rendered object), everything became insanely slow.

After investigation, I inserted a call to `vkGetPhysicalDeviceMemoryProperties2` with the `VK_EXT_memory_budget` extension right before and right after every single call to `vkQueueSubmit`, and I noticed this:

- After initializing all the fundamental systems but right before calling `vkQueueSubmit` for the first time, the function indicates a heap usage of ~470 MB, which is reasonable and what I would expect to be allocated at this stage.
- Right after calling `vkQueueSubmit`, the call to `vkGetPhysicalDeviceMemoryProperties2` reports a heap usage of ~13.9 GB.
- Right before calling `vkQueueSubmit` for the second time, the call to `vkGetPhysicalDeviceMemoryProperties2` reports again ~13.9 GB.
- Right after calling `vkQueueSubmit` for the second, this time the heap usage is at ~26.8 GB.
- Right before calling `vkQueueSubmit` for the third time, it is still at ~26.8 GB.
- Right after calling `vkQueueSubmit` for the third time, it is at ~39.8 GB.
- And so on, every time `vkQueueSubmit` is called (once per frame).

It is unclear whether these 13 GB are "actual" memory. When I debug my app in XCode, the memory usage completely explodes, going in the several hundreds of GB, which is obviously not possible. However, everything crashes after around 10 seconds with a popup saying that memory is low.

Validation layers do not report any error or warning (except a small performance warning due to a vertex shader output being silently discarded by the fragment shader).

Here's a full API dump of my app: [vkapidump.txt](https://github.com/user-attachments/files/16582492/vkapidump.txt)

I don't think I'm doing anything out of the ordinary, except for two things: I destroy and recreate framebuffers at every frame (every frame I create a framebuffer and destroy the framebuffer of frame N-2), and I destroy and re-create descriptors at every frame (same method, and I destroy them by resetting the pool).

The leaky behavior seems to happen whenever I use an SSBO. No SSBO, no leak. The larger the SSBO, the bigger the leak. However we're talking about a ~10MB fragment of a buffer, and I don't see how this could explode to 13 GB.

**Comment by tomaka** [comment]
Still happens with v1.2.10-rc2.

**Comment by billhollings** [comment]
Do you have a way we can replicate this?

When I run CTS on thousands of SSBO tests from Xcode, I do not see an explosion in memory.

**Comment by warmenhoven** [comment]
I believe this may be a similar issue to what I'm seeing with RetroArch on tvOS starting with 370e7c14e770ddca71bc99eb34921aa937c76334. When it fails, these are the errors:

```
Execution of the command buffer was aborted due to an error during execution. Discarded (victim of GPU error/recovery) (00000005:kIOGPUCommandBufferCallbackErrorInnocentVictim)
[mvk-error] VK_ERROR_OUT_OF_DEVICE_MEMORY: MTLCommandBuffer "vkQueueSubmit MTLCommandBuffer on Queue 0-0" execution failed (code 1): Discarded (victim of GPU error/recovery) (00000005:kIOGPUCommandBufferCallbackErrorInnocentVictim)
[mvk-info] Encoders for 0x3001e2580 "vkQueueSubmit MTLCommandBuffer on Queue 0-0":
[mvk-info]  - vkCmdDispatch ComputeEncoder: faulted
[mvk-info]  - vkCmdBeginRenderPass RenderEncoder: affected
```

So far I have only seen this happen on tvOS; the same build is working fine on macOS and iOS.

I'm certain I haven't given enough information to help dig further but please let me know what you need. I have logs from running debug builds of moltenvk, or I can point you at [the RetroArch source](https://github.com/libretro/RetroArch) and give you instructions for how to build/run it. Please let me know what's most helpful.

**Comment by warmenhoven** [comment]
Setting `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` back to 0 works around this for me.

**Comment by billhollings** [comment]
> I believe this may be a similar issue to what I'm seeing with RetroArch on tvOS.

Are you seeing a similar massive explosion in GPU heap memory? If so, how are you measuring it? 

Is it only with SSBO's, like above?

> I have logs from running debug builds of moltenvk, or I can point you at [the RetroArch source](https://github.com/libretro/RetroArch) and give you instructions for how to build/run it.

Yes, please ZIP up your logs and post them here. And instructions for replicating this in RetroArch would be helpful.

**Comment by warmenhoven** [comment]
> Are you seeing a similar massive explosion in GPU heap memory?

Actually no. I guess this is a different issue. I'm happy to file a new one if that's easier.

> Is it only with SSBO's, like above?

Yes, and only on some devices. I haven't seen the problem on my iPhone 15 Pro or my 3rd gen AppleTV 4K; but I have seen it on my 2nd gen iPad Pro (A12Z-based) and my 1st gen AppleTV 4K. I haven't seen it on my M1 or M2 Macs.

> Yes, please ZIP up your logs and post them here.

I'm attaching two logs, one from my iPad and one from my atv4k1g. Both of them are using debug builds of MoltenVK from 5b0541309decb093c1e4874e143b5a218847452a as opposed to current main, because of #2329.

[iPadPro.log](https://github.com/user-attachments/files/16965380/iPadPro.log)
[atv4k1g.log](https://github.com/user-attachments/files/16965429/atv4k1g.log)

> And instructions for replicating this in RetroArch would be helpful.

The easiest way will probably be to build from source, https://github.com/libretro/RetroArch. In the latest master branch, the workspace is pkg/apple/RetroArch.xcworkspace; from there you can build macOS, iOS, and tvOS. For macOS, just use the "RetroArch" scheme; the iOS and tvOS schemes are clearly labeled. The MoltenVK.framework it uses is in pkg/apple/Frameworks; you should be able to drop the built Package/Release/MoltenVK/dynamic/MoltenVK.xcframework directly on top of it. There are some entitlements that it uses for iCloud and Top Shelf but those are completely optional and disabling all of those entitlements won't break anything.

Alternatively you can grab an IPA from the libretro buildbot, https://buildbot.libretro.com/nightly/apple/, and replace the embedded framework and resign.

There's no special configuration that needs to be done; if you hit the issue it will simply fail to render.

**Comment by warmenhoven** [comment]
> TBH...I don't think I'll be able to find a ATV or iPad that are that old, if that's the only devices it's happening on.

I understand. I pulled out my iPhone 13 Pro to see if the problem happens there, and it doesn't. It does seem it has to be relatively old hardware. (On the bright side, this doesn't happen on my other 1st gen AppleTV 4k gen, running tvOS 13.3.1, I'm assuming because it's only using Metal 2.2 and so doesn't use argument buffers.)

> Can you try running the app on those devices with the following environment variables set

[ipad.log](https://github.com/user-attachments/files/17000827/ipad.log)

I actually set `MVK_CONFIG_PERFORMANCE_LOGGING_FRAME_COUNT=60` because this happens very early during the app startup and was hoping to catch it early, but I don't see any of the `Performance statistics reporting every: 60 frames` messages. (I do on my old ATV running 13.3.)

**Comment by tomaka** [comment]
(op here)

I don't know if my original problem is the same as the one that is being discussed, but I believe that I've just found the cause of mine.

My code was assuming that `vkAcquireSwapchainImage` with a non-zero timeout would block until the GPU is no longer accessing one of the swapchain image, whereas it seems (if I'm not mistaken) that actually it only blocks until a vsync event.

This means that as soon as it takes more than 16.7ms to render a frame, I would `vkQueueSubmit` a command buffer that draws on a swapchain image despite the fact that an older command buffer drawing on the same swapchain image hasn't finished executing. Over time, the queue of command buffers would simply grow forever.

The fact that it happens only with SSBOs seems to be a coincidence, as it pushes the rendering time over the threshold.

After fixing the issue, the memory usage still seems very high (by using XCode's Metal debugger I see 23 GiB of buffers, whereas I expect around 50 MiB), but it is now stable.

**Comment by billhollings** [comment]
@tomaka 

Thanks for providing more info. I'm glad you've at least found a limit for the memory being used. Unfortunately, you seem to still have a large memory leak.

`vkAcquireNextImageKHR` will return immediately if an image can be acquired (even with a non-zero timeout value), but that does _**not**_ mean that the image is available to be used. Basically, `vkAcquireNextImageKHR` returning really just means "this is the next image you will be writing to", it does not indicate that the image is ready to be used. For that, either the semaphore or fence is used to synchronize. With a semaphore, the next `vkQueueSubmit` will only start writing to that image once it is signalled as free from the previous `vkPresentImage`, or the `fence` can be used instead, to have the app itself wait until the image is ready to be written to.

If the call cannot locate the image to use next, either immediately, or after the timeout duration, the call will return `VK_NOT_READY` or `VK_TIMEOUT`, depending on whether a timeout was provided. So the timeout value is about how long you want the call to wait before returning if it _**cannot**_ locate the image that is to be used next. 

In general, as long as you have enough swapchain images to cover your frames (typically `3`, or sometimes `2` on a lightly-loaded environment), `vkAcquireNextImageKHR` will _**always**_ return immediately.

See this discussion within the spec:

> When successful, `vkAcquireNextImageKHR` acquires a presentable image from swapchain that an application can use, and sets `pImageIndex` to the index of that image within the swapchain. The presentation engine may not have finished reading from the image at the time it is acquired, so the application must use semaphore and/or fence to ensure that the image layout and contents are not modified until the presentation engine reads have completed. Once `vkAcquireNextImageKHR` successfully acquires an image, the semaphore signal operation referenced by semaphore, if not `VK_NULL_HANDLE`, and the fence signal operation referenced by fence, if not `VK_NULL_HANDLE`, are submitted for execution. If `vkAcquireNextImageKHR` does not successfully acquire an image, semaphore and fence are unaffected. The order in which images are acquired is implementation-dependent, and may be different than the order the images were presented.
>
> If timeout is zero, then `vkAcquireNextImageKHR` does not wait, and will either successfully acquire an image, or fail and return `VK_NOT_READY` if no image is available.
>
> If the specified timeout period expires before an image is acquired, `vkAcquireNextImageKHR` returns `VK_TIMEOUT`. If timeout is `UINT64_MAX`, the timeout period is treated as infinite, and `vkAcquireNextImageKHR` will block until an image is acquired or an error occurs.

**Comment by tomaka** [comment]
Thanks for the explanation, I had fixed that simply by passing a fence to `vkAcquireNextImage` and immediately waiting on it right after.
As I've mentioned, I still see a very high memory consumption, but I haven't had the time to properly investigate where that comes from.

**Comment by tomaka** [comment]
I have reduced the memory usage from 20 GiB to 13 GiB by passing the `VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT` flag when resetting a command pool.

**Comment by cdavis5e** [comment]
> it seems that the huge amount of memory consumed comes from the intermediary buffers used for the tessellation shader output.

Those buffers should not actually be a problem. We mark them purgeable with [`-[MTLResource setPurgeableState:]`](https://developer.apple.com/documentation/metal/mtlresource/1515898-setpurgeablestate?language=objc), which means that if the GPU is running low on VRAM, the system is allowed to discard the contents to reclaim their memory. (Compare `IDXGIDevice2::OfferResources()` from Direct3D; currently, Vulkan has no analog to this.) Not freeing them is an optimization on the expectation that multiple draw calls would be submitted.
