### ISSUE TITLE
Crash at vkQueuePresentKHR

### ISSUE THREAD

**Issue by aitor-lunarg** [KhronosGroup/MoltenVK#2321]
Moving issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8473 here since it happens without validation layer enabled.

Comments from @lsdh-fei in order:
Issue description
```
  -  macos 14.6.1 macbook pro 16-inch, 2019
  -  AMD Radeon Pro 5300M 4 GB
  -  sdk version: 1.3.283.0
  -  moltenvk version: 1.2.9
  -  SDL2 version: 2.30.6
  -  tool: vscode + clang

i wrote a demo, it runs well on m1 mac, and when i turned to intel x86, it crashed when call vkQueuePresentKHR, there has no validation info when it crash, stack as below:

libsystem_platform.dylib!_platform_memmove$VARIANT$Haswell (未知源:0)
libVkLayer_khronos_validation.dylib!DispatchQueuePresentKHR(VkQueue_T*, VkPresentInfoKHR const*) (未知源:0)
libVkLayer_khronos_validation.dylib!vulkan_layer_chassis::QueuePresentKHR(VkQueue_T*, VkPresentInfoKHR const*) (未知源:0)

it should run well , the cube demo runs well on the x86 machine, i dont know if there is some error when i use the new sdl2 version, when i use the sdl2 in the sdk, it couldent compile.

here is tasks.json:
{
"label": "cppdebug compile",
"type": "cppbuild",
"command": "/usr/bin/clang++",
"args": [
"-Wno-nullability-completeness",
"-std=c++17",
"-stdlib=libc++",
"-fcolor-diagnostics",
"-fansi-escape-codes",
"-I/usr/local/Cellar/sdl2/2.30.6/include",
"-L/usr/local/Cellar/sdl2/2.30.6/lib",
"-lSDL2",
"-I${workspaceFolder}/include",
"-I${VULKAN_SDK}/include",
"-L${VULKAN_SDK}/lib",
"-Wl,-rpath,${VULKAN_SDK}/lib",
"-lvulkan.1",
"-g",
"${workspaceFolder}/.cpp",
"${workspaceFolder}/include/imgui/.cpp",
"${workspaceFolder}/source/*.cpp",
"-o",
"${workspaceFolder}/output/vulkan"
],
"options": {
"cwd": "${workspaceFolder}"
},
"problemMatcher": [
"$gcc"
],
"group": {
"kind": "build",
"isDefault": true
},
"detail": "vulkan with vscode c++ plugin"
}
```

Second comment
```
after i remoded validation layer，It crashed in MoltenVK, stack as below:

libMoltenVK.dylib!MVKQueuePresentSurfaceSubmission::MVKQueuePresentSurfaceSubmission(MVKQueue*, VkPresentInfoKHR const*) (未知源:0)
libMoltenVK.dylib!MVKQueue::submit(VkPresentInfoKHR const*) (未知源:0)
libMoltenVK.dylib!vkQueuePresentKHR (未知源:0)

i will try the latest MoltenVK later
```

Third comment
```
the code works well with sdk 1.3.239.0 on m1 mac,but crashed with sdk 1.3.283.0 on intel cpu mac. the crash stack is shown in validation, so i post it here, but it seems a bug in MoltenVK.
```

Fourth comment
```
i tested with latest MoltenVK, it crashed with the same stack in MVKQueuePresentSurfaceSubmission.
latest MoltenVK log:

[mvk-info] GPU device:
model: AMD Radeon Pro 5300M
type: Discrete
vendorID: 0x1002
deviceID: 0x7340
pipelineCacheUUID: 18F2B84E-0E06-0200-0000-000100000000
GPU memory available: 4080 MB
GPU memory used: 0 MB
Metal Shading Language 3.1
supports the following GPU Features:
GPU Family Metal 3
GPU Family Mac 2
Read-Write Texture Tier 2
[mvk-info] GPU device:
model: Intel(R) UHD Graphics 630
type: Integrated
vendorID: 0x8086
deviceID: 0x3e9b
pipelineCacheUUID: 18F2B84E-0E06-0200-0000-000100000000
GPU memory available: 1536 MB
GPU memory used: 8 MB
Metal Shading Language 3.1
supports the following GPU Features:
GPU Family Metal 3
GPU Family Mac 2
Read-Write Texture Tier 1
[mvk-info] Created VkInstance for Vulkan version 1.2.290, as requested by app, with the following 3 Vulkan extensions enabled:
VK_KHR_surface v25
VK_EXT_debug_utils v2
VK_EXT_metal_surface v1

[mvk-info] Vulkan semaphores using MTLEvent.
[mvk-info] Descriptor sets binding resources using Metal3 argument buffers.
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 5300M with the following 2 Vulkan extensions enabled:
VK_KHR_portability_subset v1
VK_KHR_swapchain v70
[mvk-info] Created 3 swapchain images with size (1024, 768) and contents scale 1.0 in layer CAMetalLayer: SDL_cocoametalview (0x7fc500746810) on screen Built-in Retina Display.
```

**Comment by billhollings** [comment]
@lsdh-fei  

You mention that the Cube demo runs fine on your x86 machine. 

Do you have any way for us to replicate this? Are we able to access your demo app? Or can you modify the Cube demo to create the same crash?

If not, are you able to build MoltenVK in Debug mode, and run your app from Xcode, so that we can get a more detailed perspective about where in `MVKQueuePresentSurfaceSubmission::MVKQueuePresentSurfaceSubmission()` the app is crashing?

**Comment by lsdh-fei** [comment]
@billhollings i build the latest MoltenVK in Debug mode, and rerun the code, here is the stack:

libMoltenVK.dylib!MVKQueuePresentSurfaceSubmission::MVKQueuePresentSurfaceSubmission(MVKQueue*, VkPresentInfoKHR const*) (/Users/fei.han/Projects/c++/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:829)
libMoltenVK.dylib!MVKQueuePresentSurfaceSubmission::MVKQueuePresentSurfaceSubmission(MVKQueue*, VkPresentInfoKHR const*) (/Users/fei.han/Projects/c++/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:766)
libMoltenVK.dylib!MVKQueue::submit(VkPresentInfoKHR const*) (/Users/fei.han/Projects/c++/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKQueue.mm:149)
libMoltenVK.dylib!vkQueuePresentKHR (/Users/fei.han/Projects/c++/MoltenVK/MoltenVK/MoltenVK/Vulkan/vulkan.mm:3209)

it crashed at here:

<img width="866" alt="image" src="https://github.com/user-attachments/assets/8bfbb18e-4495-4096-8e89-ffef0847dea1">

i think pSCRslts should be nullptr, maybe is doesnot init propely.

**Comment by lsdh-fei** [comment]
i add `present.pResults = nullptr` when create VkPresentInfoKHR and it didnot crash any more, it is a c++ code error, its really annoying

**Comment by billhollings** [comment]
Thanks for including more info about the source of the crash.

> i add `present.pResults = nullptr` when create VkPresentInfoKHR and it didnot crash any more

The Vulkan [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPresentInfoKHR.html#VUID-VkPresentInfoKHR-pResults-parameter) requires that `present.pResults` have a valid value:

>If `pResults` is not NULL, `pResults` **must** be a valid pointer to an array of `swapchainCount` `VkResult` values

From that error above, the value of of `present.pResults` seems to have been set to `0x2d`, which is not a legal pointer address. So setting it to `NULL` fixes that. Otherwise, if you want the results back, you can set it to a valid pointer that has enough space for the returned array.

> it is a c++ code error, its really annoying

Why are you thinking this has something to do with C++? Do you mean that you expected it to be initialized to zeros? If so, to be safe, you can create structures as follows:

`VkPresentInfoKHR presInfo = {};`

**Comment by cdavis5e** [comment]
> Why are you thinking this has something to do with C++? Do you mean that you expected it to be initialized to zeros?

OP may be used to another language like Rust, Go, or Swift, where validly initializing all variables is either a requirement or is done by the compiler automatically.

**Comment by lsdh-fei** [comment]
@billhollings i used clang this time, new compiler didnot init it to zero, i will keep in mind to use {} to initialize all structs, thx

**Comment by billhollings** [comment]
Glad to hear you got it sorted out. Closing this now.
