### ISSUE TITLE
Fails to build for visionOS

### ISSUE THREAD

**Issue by drewbaumann** [KhronosGroup/MoltenVK#2322]
# Summary
Building for the target visionOS from make command and via XCode fail.

# Description
When attempting to build for visionOS in either fashion from the main branch I hit this issue: `error: use of undeclared identifier 'MTLGPUFamilyApple9'`

I am using XCode 15.4.0

# QAing
This can be replicated by running the following code in the project directory:
```shell
./fetchDependencies --visionos
make visionos
```

**Comment by billhollings** [comment]
PR #2326 fixes this.
