### ISSUE TITLE
PushDescriptorWithTemplate has broken size computation

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/MoltenVK#2323]
```
// Work out how big the memory block in pData is.
    const VkDescriptorUpdateTemplateEntry* pEntry =
        _descUpdateTemplate->getEntry(_descUpdateTemplate->getNumberOfEntries()-1);
    size_t size = pEntry->offset;
    // If we were given a stride, use that; otherwise, assume only one info
    // struct of the appropriate type.
    if (pEntry->stride)
        size += pEntry->stride * pEntry->descriptorCount;
```

This assumes that the last element in the template update maps to the highest address. This is a flawed assumption, and breaks Granite. Granite sorts the updates by descriptor type, and push descriptors segfaults.

Also, there's a worrying malloc every push, which seems very suboptimal.

**Comment by billhollings** [comment]
PR #2327 should fix both of these issues. Please retest and close this issue if solved.

**Comment by warmenhoven** [comment]
Worked for me. Thanks!

**Comment by cdavis5e** [comment]
I could've sworn that I had read in the spec that the entries had to be sorted by address.

/me goes to read the spec...

I guess not. I must've been mistaken when I implemented that functionality.

**Comment by billhollings** [comment]
> Worked for me. Thanks!

Great. Closing now.
