### ISSUE TITLE
[Question] Does MoltenVK support storage texel buffer writes without format?

### ISSUE THREAD

**Issue by squidbus** [KhronosGroup/MoltenVK#2338]
Vulkan has a validation that, if you write to a buffer view as a storage texel buffer without format in a shader, the format needs to have `VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT_KHR` specifically in its `bufferFeatures`: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/215dcaf6a35efa4bf86ccf639f11519f7c726307/layers/drawdispatch/descriptor_validator.cpp#L1038-L1049

However, I see that currently MoltenVK only ever sets this flag for `optimalTilingFeatures`. Is it possible to advertise these features for buffer views as well, or is this something that Metal does not support?

**Comment by squidbus** [comment]
I see this got the enhancement label added, but could I get an answer to the question on whether this is something that currently works or not? When I get the validation error I don't necessarily see anything wrong with the rendering output, so it would be good to know if this is something that works but just is not advertised, or if it could cause problems.

**Comment by cdavis5e** [comment]
I think this is something that should just work, as you saw--there's no real difference in the way Metal handles texture buffers vs. other textures--but that we forgot to set in `bufferFeatures`. The "enhancement" would be in setting the missing bit.

**Comment by squidbus** [comment]
Thanks for the info, knowing this should be supported, this is something that looks simple enough that I can go ahead and open a PR myself.

**Comment by squidbus** [comment]
Closing since the PR is merged.
