### ISSUE TITLE
descriptor set trouble

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#2356]
### Discussed in https://github.com/KhronosGroup/MoltenVK/discussions/2344

<div type='discussions-op-text'>

<sup>Originally posted by **beaumanvienna** September 21, 2024</sup>
I get a seg fault in `vkQueueSubmit`:
[crash lucre.txt](https://github.com/user-attachments/files/17085523/crash.lucre.txt)

It looks like MoltenVk cannot find a descriptor set. I have narrowed it down to a `vkCmdBindDescriptorSets` command. 

I created a test scenario, in which I bind two sets: set 0 for global data and set 1 for the diffuse map sampler in the frag shader. I made it so that both set 0 and set 1 are created identically. Set 0 generally works in my engine. It has, among others, a descriptor for a texture in it, so I'm using this to sample from something in the frag shader. When I bind the global set a second time with the above `vkCmdBindDescriptorSets` instruction, it does not crash and I can sample from it in the frag shader with a test cube. The weird part is that when I use an identically created descriptor set, I get the seg fault. </div>

**Comment by billhollings** [comment]
Thanks for submitting this. It looks like MoltenVK might not be retaining the contents of the `VkDescriptorSetLayout` after it is destroyed.

To help us get to the bottom of this, are you also destroying early the `VkPipelineLayout` that the `VkDescriptorSetLayout`s are part of?

**Comment by billhollings** [comment]
PR #2358 should fix this. Please retest with latest MoltenVK.

**Comment by beaumanvienna** [comment]
> Thanks for submitting this. It looks like MoltenVK might not be retaining the contents of the `VkDescriptorSetLayout` after it is destroyed.
> 
> ~To help us get to the bottom of this, are you also destroying early the `VkPipelineLayout` that the `VkDescriptorSetLayout`s are part of?~
> 
> `vkCmdBindDescriptorSets()` takes a `VkPipelineLayout`, which includes `VkDescriptorSetLayouts`. But I assume you mean you allocated a `VkDescriptorSet` from a compatible `VkDescriptorSetLayout`, but which had been destroyed prior to submitting that `VkDescriptorSet` to `vkCmdBindDescriptorSets()`?

yes, that's right
