### ISSUE TITLE
Compute pipeline compile fails with "Compiler encountered an internal error."

### ISSUE THREAD

**Issue by squidbus** [KhronosGroup/MoltenVK#2363]
The below compute shader and pipeline are producing the following error from `vkCreateComputePipelines`:
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Compute pipeline compile failed (Error code 3):
Compiler encountered an internal error.
```

The crash report for MTLCompilerService says the following:
```
unable to legalize instruction: %62:_(s32), %63:_(s1) = 145 %59:_, %55:_
Context:
%62:_(s32), %63:_(s1) = 145 %59:_, %55:_
%59:_(s32) = 181 %58:_(s32)
%55:_(s32) = 90 %57:_(p64) :: (dereferenceable load (s32) from `i32 addrspace(64)* bitcast (i8 addrspace(64)* getelementptr inbounds ([28 x i8], [28 x i8] addrspace(64)* @memorycache0, i32 0, i32 8) to i32 addrspace(64)*)`, !tbaa !50, !alias.scope !54, !noalias !61, addrspace 64)
%58:_(s32) = 19 $r10
%57:_(p64) = 193 %7:_, %17:_(s64)
%7:_(p64) = 71 @memorycache0
%17:_(s64) = 120 i64 8
(in function: agc.main)
```

Compute shader (SPIR-V and generated MSL included): https://gist.github.com/squidbus/50273067f4bd89752473c04683524a93

Pipeline:
* Push Descriptor Layout:
  * Uniform Buffer at Binding 0
  * Uniform Texel Buffer at Binding 1
  * Storage Image at Binding 2
* Push Constants: Offset = 0, Size = 104

System: M3 Max w/ macOS 15.1 Beta 5 (and macOS 15)

This seems to be coming from the last line with the image write, as if I replace the coordinates argument with a fixed zero vector it compiles.

Note that there is no error if I use the command line shader compiler, only when compiling a pipeline at runtime.

I have a feeling this may be triggering a Metal compiler bug, but I felt it would be worth reporting here for a look, in case it could be worked around in the SPIR-V to Metal translation for better compatibility.

**Comment by cdavis5e** [comment]
This _is_ a Metal compiler bug--more specifically, a bug in the AGX backend. I can't see anything wrong with the generated code.

This needs to be reported upstream to Apple. In the meantime, if you want a workaround in SPIRV-Cross, this issue should probably be filed [there](https://github.com/KhronosGroup/SPIRV-Cross/issues).

**Comment by squidbus** [comment]
Okay, I've reported this to SPIRV-Cross as well here: https://github.com/KhronosGroup/SPIRV-Cross/issues/2385

I will try to report to Apple but I'm not sure how much traction feedback reports get.

**Comment by squidbus** [comment]
This is worked around now in SPIRV-Cross: https://github.com/KhronosGroup/SPIRV-Cross/commit/80cdb5e7dbbd2def82958b374742b20fd15a78cf

I assume this should be left open until the SPIRV-Cross revision used here is updated.

**Comment by billhollings** [comment]
> This is worked around now in SPIRV-Cross: [KhronosGroup/SPIRV-Cross@80cdb5e](https://github.com/KhronosGroup/SPIRV-Cross/commit/80cdb5e7dbbd2def82958b374742b20fd15a78cf)
>

Excellent work! Thanks for handling it!

> I assume this should be left open until the SPIRV-Cross revision used here is updated.

It will happen naturally at some point, but feel free to submit a PR that updates the value in `ExternalRevisions/SPIRV-Cross_repo_revision` to the latest HEAD of SPIRV-Cross `main`.
