### ISSUE TITLE
Release v1.2.11 is missing archives.

### ISSUE THREAD

**Issue by Gcenx** [KhronosGroup/MoltenVK#2366]
The action itself does contain builds but those failed to be uploaded to the release.

Also, the release marked "latest" is v1.2.11-rc1 not v1.2.11

**Comment by billhollings** [comment]
Thanks for detecting and reporting this. As you mention, the release build artifacts are available [here](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.11-artifacts).

Also, release [v1.2.11](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.11) is now marked as the latest release.
