### ISSUE TITLE
memory management issue in MVKSwapchain::setHDRMetadataEXT

### ISSUE THREAD

**Issue by NekoAsakura** [KhronosGroup/MoltenVK#2399]
MVK version 1.2.12, supporting Vulkan version 1.2.296
Build from https://github.com/KhronosGroup/MoltenVK/commit/26c7b0234dd093e6153237c4a8d94eedd07f9614

-----

mpv community has reported an issue causing program to crash, after investigation, was found to be caused by a memory management issue in `MVKSwapchain::setHDRMetadataEXT`. https://github.com/mpv-player/mpv/issues/12666#issuecomment-2509030237

According to [README](https://github.com/KhronosGroup/MoltenVK/blob/main/README.md#Memory-Management):

> As a contributor to **MoltenVK**, avoid the use of the *Metal* `autorelease` method, or any object *Metal* creation
methods that imply internal use of `autorelease`, (eg- `[NSString stringWithFormat: ]`, etc). 

https://github.com/KhronosGroup/MoltenVK/blob/26c7b0234dd093e6153237c4a8d94eedd07f9614/MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm#L359-L360

However in `MVKSwapchain::setHDRMetadataEXT` NSData was assigned with type `dataWithBytes`, which is implied with internal use of autorelease:

https://github.com/apportable/Foundation/blob/master/System/Foundation/src/NSData.m#L744-L747

```
+ (id)dataWithBytes:(const void *)bytes length:(NSUInteger)length

{
    return [[[self alloc] initWithBytes:(void *)bytes length:length copy:YES freeWhenDone:NO bytesAreVM:NO] autorelease];
}
```

For manually track and release, it should be 

```
NSData* colorVolData = [[NSData alloc] initWithBytes: &colorVol length: sizeof(colorVol)];
```

**Comment by cdavis5e** [comment]
This should, of course, be fixed by your change #2400. Normally, this is where we'd ask you to test this, but I would presume you did that when you wrote the change.
