### ISSUE TITLE
Memory management of OC objects

### ISSUE THREAD

**Issue by NekoAsakura** [KhronosGroup/MoltenVK#2401]
I noticed that some use of `@autoreleasepool` could be avoided, for example:

https://github.com/KhronosGroup/MoltenVK/blob/1d2ec638532268d076a550262df2e5e5e4fd2c9e/MoltenVK/MoltenVK/Utility/MVKCodec.mm#L148-L182

`srcData` could be created by `[NSData alloc] initWithBytesNoCopy`, `dstData` could be `retain` after the method call. Both objects should then be manually released at the end of the function.

The current code should function properly, but in the [README](https://github.com/KhronosGroup/MoltenVK/blob/main/README.md#Memory-Management) it mentions "manually track and release those objects." I don't have experience in game development, so I'm not sure about the necessity of manual memory management. However, if it's essential, I can review the code and remove them.

**Comment by billhollings** [comment]
Thanks for your suggestion.

You are correct that ideally, we would track and release all Objective-C objects, in order to avoid the need for the `@autoreleaesepool` block.

Unfortunately, sometimes it's not clear when autoreleased objects are created, because a method like `initWithBytesNoCopy` may end up creating a number of autoreleased objects internally (I don't know if this specific case does, but many others do). So, unless it's a particularly performance-sensitive block of code, it's better to be safe than sorry (which is the case here).

We're always happy to receive concrete suggestions of code where an autorelease block in  performance-sensitive code has been demonstrated to be unnecessary because no leaks occur without it!

**Comment by NekoAsakura** [comment]
Thank you for your response. In fact, objc’s memory management is quite straightforward. You can obtain ownership of objects in the following ways:

1. By creating an object using methods `alloc`, `new`, `copy`, or `mutableCopy`.
2. By explicitly taking ownership using the `retain` method.

This means that even if a system-provided API returns an autoreleased object (e.g., `dstData` here), you can override autorelease by calling the `retain` method.

Of course, as you said, for blocks in non-performance-sensitive code, it’s better to safe. Minor memory leak is much better than crush, like what I fix in https://github.com/KhronosGroup/MoltenVK/pull/2400.

**Comment by billhollings** [comment]
> You can obtain ownership of objects in the following ways

Yes. If it were as simple as tracking only the returned object, then we could take ownership of the returned object and release it appropriately, without the need for an `@autoreleasepool`. And we do that in many cases (and thanks for your fix in #2400).

But, inside a system framework call (and hence out of our control), Apple code may (and typically does) create temporary autoreleased objects in its own, that it assumes will be cleaned up with by an autorelease pool at some level in the surrounding code. For example, even a simple string manipulation call might create several internal temporary autoreleased `NSString` objects that we will never be aware of. And a call like a shader compile might create hundreds of autoreleased objects.

> you can override autorelease by calling the retain method.

In calling `retain`, you don't override autorelease, you just add another retain count to the object. When you call the corresponding `release` for your `retain`, the autorelease retain count increment is still there and needs to be cleaned up if you want to avoid a leak. In an Manual Reference Counting app, you can demonstrate this by accessing the `retainCount` property at each step to see how the count grows and shrinks as `alloc`, `retain`, `autorelease` and `release` are invoked on the object.

**Comment by NekoAsakura** [comment]
You are right, thank you for your correction.
