### ISSUE TITLE
Move scripts out of Xcode project files

### ISSUE THREAD

**Issue by ryandesign** [KhronosGroup/MoltenVK#241]
Diffs of Xcode project files are hard to read, especially when the diffs modify embedded scripts, since Xcode stores such scripts in a single line of the project file. A strategy to make diffs of such scripts easier to read, and to make editing such scripts easier, is to move them to separate files and have Xcode run them, using a method such as the one described in [this blog post](http://www.mokacoding.com/blog/better-build-phase-scripts/). Would you be willing to do this for your Xcode projects' scripts, or would you accept a pull request that does so?

**Comment by billhollings** [comment]
@ryandesign 

This makes sense. I'll take care of it.

**Comment by billhollings** [comment]
Added in PR #249.
