### ISSUE TITLE
How to build only the macOS parts

### ISSUE THREAD

**Issue by ryandesign** [KhronosGroup/MoltenVK#242]
What's the best way to programmatically compile only the macOS MoltenVK files and avoid compiling the iOS files?

I recently added MoltenVK to MacPorts, so that we can use it in our Wine ports. For version 1.0.18, I had the build invoke `xcodebuild` 3 times, specifying the schemes `MoltenVKSPIRVToMSLConverter-macOS`, `MoltenVK-macOS` and `MoltenVKGLSLToSPIRVConverter-macOS`. For 1.0.20, I'm encountering an error with that, and I'm wondering if there is an easier or more approved way that I should be doing this.

**Comment by billhollings** [comment]
@ryandesign 

That makes sense. I'll add additional a couple of OS-specific packaging targets.

**Comment by billhollings** [comment]
Added in PR #249.
