### ISSUE TITLE
Add tags for missing versions

### ISSUE THREAD

**Issue by ryandesign** [KhronosGroup/MoltenVK#251]
[Whats_New.md](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/Whats_New.md) describes versions 1.0.4, 1.0.7, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.19, and 1.0.21, but there are no tags for these versions in the git repository. Should these tags be added?

**Comment by billhollings** [comment]
@ryandesign 

Yes...in general they should...but sometimes the tagging gets forgotten in the process.

I've added a tagged release for v1.0.21 now.

If there is a real need to create a formal package release for any of the previous versions, let me know.

**Comment by ryandesign** [comment]
Thanks. The current version is what I need most, since the creation of the tag is how I become aware of the existence of a new version. Having historical tags available can help with regression testing.
