### ISSUE TITLE
Question: Why does MoltenVK use SPIRV-Cross?

### ISSUE THREAD

**Issue by Guy1524** [KhronosGroup/MoltenVK#283]
According to this documentation page, Metal can consume Vulkan SPIR-V shaders: https://mellinoe.github.io/veldrid-docs/articles/shaders.html

**Comment by cdavis5e** [comment]
Where does it say that?

**Comment by zakk4223** [comment]
https://mellinoe.github.io/veldrid-docs/articles/portable-shaders.html

This says right here they use SPIRV-Cross to generate MSL. Metal does not consume SPIR-V.
