### ISSUE TITLE
MoltenVK 1.0.22 released

### ISSUE THREAD

**Issue by romulasry** [KhronosGroup/MoltenVK#289]
https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.22
 Latest release

    v1.0.22
    4c5f7b8

Add extensions and update SPIRV_Cross.

@billhollings billhollings released this 3 hours ago · 9 commits to master since this release
Assets 2

    Source code
    (zip)
    Source code
    (tar.gz)

    Add support for extensions:
        VK_KHR_maintenance2
        VK_EXT_vertex_attribute_divisor
        VK_KHR_sampler_mirror_clamp_to_edge
        VK_KHR_image_format_list
        VK_KHR_dedicated_allocation
        VK_KHR_get_memory_requirements2
        VK_EXT_shader_viewport_index_layer
    Support multiple viewports and scissor rectangles.
    Support sampleRateShading.
    Support pre-filling Metal command buffer on same thread as Vulkan command buffer.
    Support passing either a CAMetalLayer or an NSView/UIView in the pView member
    when creating a surface.
    Support views of the stencil aspect of depth/stencil images.
    Improvements to subviews on 3D textures.
    Enforce single queue per queue family to improve Metal command buffer handling.
    Set Metal render target sizes on iOS.
    Fix potential deadlocks on query results and fences.
    Fix memory leak on SPIRV conversion.
    Update to Vulkan header 1.1.85 and latest version of library dependencies.
    Update to latest SPIRV-Cross version:
        MSL: Handle the ViewportIndex builtin.
        MSL: Handle the SamplePosition builtin.
        MSL: Fix OpAtomicIIncrement and OpAtomicIDecrement.
        MSL: Support array of arrays composites and copying.
        MSL: Fix issues with casting of builtin integer vectors.

**Comment by romulasry** [comment]
No. I meant to put this on valve's tracker. My mistake.

**Comment by billhollings** [comment]
Thanks. Then I'll close this.
