### ISSUE TITLE
MVKGraphicsPipeline::getMTLRenderPipelineDescriptor ->Failed assertion `Cannot create buffer of zero length.'

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#308]
Hello there. Starting with one of the last versions of MoltenVK we get the following assertion message when running our Application in Debug mode:

`-[MTLDebugDevice validateNewBufferArgs:options:]:365: failed assertion `Cannot create buffer of zero length.'`

The issue happens in the MoltenVK function:

`MTLRenderPipelineDescriptor* MVKGraphicsPipeline::getMTLRenderPipelineDescriptor(const VkGraphicsPipelineCreateInfo* pCreateInfo) {`

At the following lines:

`if (_needsVertexAuxBuffer || _needsFragmentAuxBuffer) {
        _auxBuffer = [_device->getMTLDevice() newBufferWithLength: auxBufferSize options: MTLResourceStorageModeShared];
    }`

The variable auxBufferSize is zero, since mvkLayout->getNumTextures(); returns zero, even though textures are properly set.

Any ideas whats wrong here?

A misuse on our side or a bug that was introduced in one of the recent updates?

Our program runs fine in a release build with no validation errors.

If I revert back to an older MoltenVK version, I don't get the above assertion message.

**Comment by billhollings** [comment]
@aerofly 

This has been fixed in PR #305. Please retest and close this issue if successful.
