### ISSUE TITLE
Vulkaninfo returns VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by sir-ion** [KhronosGroup/MoltenVK#309]
I've downloaded and installed the SDK following the documentation from [LunarG](https://vulkan.lunarg.com/doc/sdk/latest/mac/getting_started.html).
Here are my MacBook Pro (15-inch, Late 2011) specs:
- OSX 10.13.6
- OpenGL 16.7.4
- OpenCL 2.8.24
- AMD Radeon HD 6770M (dual configuration with Intel HD Graphics 3000 for low profile usage)

Unfortunately, when I run `vulkaninfo` I get

    $ vulkaninfo 
    ==========
    VULKANINFO
    ==========
    
    Vulkan Instance Version: 1.1.85
    
    /tmp/macos-sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.c:3357: failed with VK_ERROR_INITIALIZATION_FAILED

I'm completely new to this libraries and I don't know what may be the cause of this error (the reason why I need them is to run some windows-only games on my MacBook Pro: a few days ago I wrote this [related question](https://apple.stackexchange.com/questions/339746/running-mtgarena-on-macbook-pro-using-wine-and-dxvk) on AskDifferent but no one answered).

Any help? (sorry, I know that Git issues are not the best place to ask for support, but this is a rather specific topic and I knew no other place to go after AskDifferent didn't help).

**Comment by galad87** [comment]
Your GPU does not support Metal, so MoltenVK won't work.

**Comment by billhollings** [comment]
@galad87 What is your source indicating the 6770M or Intel 3000 won't support Metal? I've only seen Apple list Metal support in terms of Mac models.

@sir-ion 

You can confirm whether your Mac models supports Metal from [this list](https://developer.apple.com/documentation/metal/mtlfeatureset?language=objc).

You can also select **_About This Mac_** from the **_Apple_** menu...then click the **_System Report..._** button and select **_Graphics/Displays_** from the report window that opens. Choose a GPU and the report will tell you whether Metal is supported...and which Metal feature set.

Are you seeing any other errors being logged?

**Comment by galad87** [comment]
sir-ion MacBook is a 2011 model, and Apple lists only 2012 and newer Macs.

**Comment by billhollings** [comment]
@galad87 

Ah! My bad. 

I completely missed sir-ion's indication of his 2011 model! And then when you mentioned the GPU being incompatible...I assumed you were making the determination from the indicated GPU itself. 

Thanks for clarifying.

To simplify things in the future...I'll add an error message to be logged by MoltenVK when the GPU does not support Metal.

**Comment by billhollings** [comment]
In PR #311, error message is now logged if GPU does not support Metal.
