### ISSUE TITLE
Is it MoltenVK that sets the support limits of iMac 2013

### ISSUE THREAD

**Issue by thepian** [KhronosGroup/MoltenVK#310]
I just lost access to a game I play because they switched from from OpenGL to MoltenVK. With a pen stroke my iMac that was running the game fine, while doing many other things yesterday; Is now refusing to run the game.

The vendor claims minimum requirements as iMac 27" 2013. Is that actual MoltenVK requirement?

**Comment by billhollings** [comment]
MoltenVK runs Vulkan on top of Metal, Apple's proprietary graphics API.

Metal was introduced in macOS 10.11 (El Capitan), and unfortunately not all older Mac models are capable of running Metal.

You can confirm whether your Mac model supports Metal from [this list](https://developer.apple.com/documentation/metal/mtlfeatureset?language=objc).

If you are running macOS 10.11 or later, and your iMac is on that list, then you should be able to run MoltenVK without any problems.
