### ISSUE TITLE
MoltenVKSPIRVToMSLConverter folder/file not found

### ISSUE THREAD

**Issue by masteage** [KhronosGroup/MoltenVK#312]
(1) MoltenVK-iOS/MoltenVK-macOS/... build error.
 + error Msg
~/MoltenVK-master/MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/../../External/SPIRV-Cross/spirv.hpp: No such file or directory

(2) .gitignore
 + External/SPIRV-Cross
 + why ignore folder/file use?

**Comment by billhollings** [comment]
Can you give some more info about what you were doing when encountering this error?

1) Did you run `./fetchDependencies`?

2) Everything in the `External` directory is retrieved from other repositories using the`fetchDependencies` script...and therefore should not included in the `MoltenVK` repository...hence their listing in `.gitignore`.
