### ISSUE TITLE
Memory types out of order on macOS

### ISSUE THREAD

**Issue by spadix0** [KhronosGroup/MoltenVK#314]
[According to the specification](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#memory-device), the `memoryTypes` reported by the implementation in a `VkPhysicalDeviceMemoryProperties` must be sorted by `propertyFlags` sets:

> For each pair of elements `X` and `Y` returned in `memoryTypes`, `X` must be placed at a lower index position than `Y` if [...] the set of bit flags returned in the `propertyFlags` member of `X` is a strict subset of the set of bit flags returned in the `propertyFlags` member of `Y`.

On my MacBook Pro running macOS 10.14, running `vulkaninfo` from the 1.1.85.0 release shows:

```text
VkPhysicalDeviceMemoryProperties:
=================================
        memoryHeapCount       = 1
        memoryHeaps[0] :
                size          = 2147483648 (0x80000000) (2.00 GiB)
                flags:
                        VK_MEMORY_HEAP_DEVICE_LOCAL_BIT
        memoryTypeCount       = 3
        memoryTypes[0] :
                heapIndex     = 0
                propertyFlags = 0x1:
                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
        memoryTypes[1] :
                heapIndex     = 0
                propertyFlags = 0xf:
                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
                        VK_MEMORY_PROPERTY_HOST_COHERENT_BIT
                        VK_MEMORY_PROPERTY_HOST_CACHED_BIT
        memoryTypes[2] :
                heapIndex     = 0
                propertyFlags = 0xb:
                        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
                        VK_MEMORY_PROPERTY_HOST_CACHED_BIT
```

Based on my interpretation of the spec, I expect those last two entries to be swapped.  Applications using the suggested search loop to select a memory type will currently be using `COHERENT` memory with MoltenVK whether they requested it or not.

I had a quick look and this doesn't seem hard to fix; I would be happy to craft a PR, if that would be helpful?

**Comment by billhollings** [comment]
@spadix0 

Thanks for noticing and reporting this.

We definitely encourage submissions...so please feel free to submit a PR.

Notwithstanding MoltenVK missing that point in the Vulkan spec...one of the reasons that the `memoryTypes` were organized in the order they are in MoltenVK was out of convenience. Because managed memory type is not available on iOS...so it was placed at the end of a single array of `memoryTypes` used by both macOS and iOS...and then the last element was simply ignored by the iOS implementation. This was just an implementation convenience.

If you are going to reorder this...you might need to populate the `memoryType` array differently for each OS.

**Comment by spadix0** [comment]
> please feel free to submit a PR.

ok!  I'll give it a go.

> managed memory type is not available on iOS...so it was placed at the end of a single array
> ...
> If you are going to reorder this...you might need to populate the memoryType array differently for each OS.

No worries - I guessed this was the case when looking through it.  I'm thinking of just adding another \#if and updating the bitmasks.  Although, I still need to check to make sure that nothing else makes assumptions about the list or masks.

Let me know if you have a different approach in mind; otherwise, I'll send the PR as soon as I get a chance to figure out git.

**Comment by billhollings** [comment]
Go for it. 

As you mention...the changes should be relatively straightforward and we can discuss via the PR submission.
