### ISSUE TITLE
there has no folder  and file named API-Samples

### ISSUE THREAD

**Issue by LWSSS** [KhronosGroup/MoltenVK#315]
as the demo  ,the folder named "API-Samples" has no file exit, so I can not run the demo on phone.

anyone else can help 

??

**Comment by billhollings** [comment]
@LWSSS 

I have no trouble running the `API-Samples` demo on iOS. There are no errors about missing files.

Can you clarify what you are trying to do, how you are trying to do it, and what errors you are seeing?

**Comment by LWSSS** [comment]
Thanks for replay...
I download demo from git at first,  the folder "API-Samples" has no file  , then  I read the  README.md again and reordered  "./fetchDependencies",  and now it is  ok. I can run the demo "API-Samples" success.
em......  when I tried to run next demo "cube", the Xcode  shows all  framework files in folder "framework" was red in project navigator , so it means  there has no file in project, and I can not build  success, here is some informations from Xcode :
        ld: warning: directory not found for option '-L/Users/liuwei/Desktop/华为/MoltenVK-master/Demos/LunarG-VulkanSamples/Cube/../../../MoltenVK/iOS'
        ld: library not found for -lMoltenVK
        clang: error: linker command failed with exit code 1 (use -v to see invocation)

  can you tell me  where can I find these framework files? or is there anything I missed ?
thank you ......

**Comment by billhollings** [comment]
@LWSSS 

All the files should be there already. Looks like the demo can't find MoltenVK.

How are you building MoltenVK? And how are you running the demos?

As described in `README.md`, after downloading MoltenVK:

1. Run the `./fetchDependencies` script
2. Open Xcode and run the `MoltenVK Package (Release)` scheme (or run `xcodebuild -project MoltenVKPackaging.xcodeproj -scheme "MoltenVK Package (Release)" build` from the command line).
3. Open the `Demos.xcworkspace` in Xcode and run any of the demo apps

It should all just work.

**Comment by billhollings** [comment]
Great! I'm glad it worked for you. You are very welcome!
