### ISSUE TITLE
Command buffer aborted error with iOS 12.1 & Xcode 10.1

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/MoltenVK#322]
I just updated Xcode to 10.1 and my iPad to iOS 12.1. I now get the following error when running my app from Xcode that I did not see before

```
Execution of the command buffer was aborted due to an error during execution. Insufficient Permission (to submit GPU work from background) (IOAF code 6)
```
The app seems to run fine despite this.

**Comment by billhollings** [comment]
@MarkCallow 

I'm not seeing this anywhere...even with Xcode 10.1 and iPad 12.1.

Are you able to replicate the error reliably?

**Comment by billhollings** [comment]
Okay. I'm going to close this issue for now. If it returns and we can figure out how to replicate it...reopen this issue and provide more context information if you can.
