### ISSUE TITLE
Packaging Makes macOS Folder Instead of iOS

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#323]
If there is no derived data for the MoltenVK project and the "MoltenVK Package (Debug) (iOS only)" target is the first target built then inside the newly created Package folder there is a macOS folder and not an iOS folder.

**Comment by billhollings** [comment]
PR #325 includes a redesigned build process...and the issue you indicate does not occur.

Please update MoltenVK...retest...and close this issue if it fixes it.

**Comment by DiegoAce** [comment]
Yes. Using the latest commit when I build target "MoltenVK Package (iOS only)" I get the appropriate iOS folder only instead of a macOS folder. Thanks!
