### ISSUE TITLE
vkCreateGraphicsPipelines Crash After Oct 16th Commits on iOS

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#324]
In my iOS project commit 7dd1434 works fine, but if I use commit 6c0ab0f or newer than my project crashes during vkCreateGraphicsPipelines. 
-[MTLDebugDevice validateNewBufferArgs:options:]:467: failed assertion `Cannot create buffer of zero length.'
Specifically I think it crashes during this call 

`_auxBuffer = [_device->getMTLDevice() newBufferWithLength: auxBufferSize options: MTLResourceStorageModeShared];`

in MVKPipeline.mm because auxBufferSize is 0.
I can provide more information if you let me know what you need. I don't think I'm doing anything unusual. Most of my code is from https://vulkan-tutorial.com.

**Comment by cdavis5e** [comment]
Normally, that codepath only gets hit if either shader attempts to sample from a texture. The fact that it's trying to create a buffer of zero size suggests that you're not sampling any textures...

Oh, dammit. Let me guess: does your pipeline layout have exactly one texture in it?

**Comment by DiegoAce** [comment]
I do only have one sampler binding if that's what you mean.

```
VkDescriptorSetLayoutBinding samplerLayoutBinding = {};
        samplerLayoutBinding.binding = 0;
        samplerLayoutBinding.descriptorCount = 1;
        samplerLayoutBinding.descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        samplerLayoutBinding.pImmutableSamplers = nullptr;
        samplerLayoutBinding.stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
        std::array<VkDescriptorSetLayoutBinding, 1> bindings = {samplerLayoutBinding};
        VkDescriptorSetLayoutCreateInfo layoutInfo = {};
        layoutInfo.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
        layoutInfo.bindingCount = static_cast<uint32_t>(bindings.size());
        layoutInfo.pBindings = bindings.data();
       vkCreateDescriptorSetLayout(m_device, &layoutInfo, nullptr, &m_textureDescriptorSetLayout);
        
        VkPipelineLayoutCreateInfo pipelineLayoutInfo = {};
        pipelineLayoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        pipelineLayoutInfo.setLayoutCount = 1;
        pipelineLayoutInfo.pSetLayouts = &m_textureDescriptorSetLayout;
       vkCreatePipelineLayout(m_device, &pipelineLayoutInfo, nullptr, &m_textureGraphicsPipelineLayout);
```

**Comment by cdavis5e** [comment]
Thought so. Does this patch applied on top of 6c0ab0f fix this for you?
[0001-MVKPipeline-Fix-off-by-one-error-in-aux-buffer-size-.txt](https://github.com/KhronosGroup/MoltenVK/files/2535231/0001-MVKPipeline-Fix-off-by-one-error-in-aux-buffer-size-.txt)

**Comment by DiegoAce** [comment]
Sorry, I thought I had tested this crash with the latest master commit but I instead tested with the latest release which actually is 6c0ab0f. I realized because 6c0ab0f uses `getNumTextures();` instead of `getMaxTextureIndex();`
I don't get this crash with the latest master commit. I can still test with your patch on the latest commit if you want.

**Comment by cdavis5e** [comment]
It's fine. (I *thought* I recalled this getting fixed...)

**Comment by billhollings** [comment]
That makes sense. Commit af0c1a0 introduced `getMaxTextureIndex()` which takes the value from the push constant tracker...which already includes the +1 offset relative to the highest real texture index...and therefore represents the actual texture count.

Hmmm...but perhaps `MVKPipeline::getMaxTextureIndex()` should actually be renamed back to `getNumTextures()` to clarify it's use in calculating the size of the aux buffer.

Regarding releases...I am planning to do an updated 1.0.25 release today...which will include the latest master...and therefore af0c1a0.

**Comment by billhollings** [comment]
In any case...looks like we can close this issue now.

**Comment by billhollings** [comment]
Sorry...I meant renaming `MVKPipelineLayout::getMaxTextureIndex()`.

I have some further work to do in this area...and I'll take care of renaming `MVKPipelineLayout::getMaxTextureIndex()` when I work on that.

**Comment by billhollings** [comment]
PR #325 renames `MVKPipelineLayout::getMaxTextureIndex()`.
