### ISSUE TITLE
Vertex attributes not interpolated

### ISSUE THREAD

**Issue by 741g** [KhronosGroup/MoltenVK#328]
In the shader in https://github.com/KhronosGroup/MoltenVK/issues/327 the original vertex/fragment shader was this GLSL:

    #version 450
    #extension GL_ARB_separate_shader_objects : enable
    out gl_PerVertex {
        vec4 gl_Position;
    };
    layout (push_constant) uniform TransformPC { <---- https://github.com/KhronosGroup/MoltenVK/issues/327 
        mat4 mvp;
    } transformPC;
    layout (std140, binding = 0) uniform Transform {
        mat4 mvp;
    } transform;
    layout (location = 0) in vec2 pos;
    layout (location = 1) in vec2 color;
    layout (location = 0) out vec2 color_varying; <----------------this needs to be interpolated
    void main() {
        gl_Position = vec4(pos, 0.0, 1.0);
        color_varying = (transformPC.mvp * vec4(pos, 0.0, 1.0)).xy;
    }
    
    #version 450
    #extension GL_ARB_separate_shader_objects : enable
    layout (location = 0) in vec2 color_varying;
    layout (location = 0) out vec4 fragcolor;
    void main() {
        fragcolor = vec4(color_varying.x, 0.2, color_varying.y, 1.0);
    }

but it doesn't seem to be interpolating in the final image (see the resulting Metal shaders from that issue, or inlined here:)

    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct TransformPC
    {
        float4x4 mvp;
    };
    
    struct Transform
    {
        float4x4 mvp;
    };
    
    struct main0_out
    {
        float2 color_varying [[user(locn0)]]; <----------will this interpolate?
        float4 gl_Position [[position]];
    };
    
    struct main0_in
    {
        float2 pos [[attribute(0)]];
    };
    
    vertex main0_out main0(main0_in in [[stage_in]], constant TransformPC& transformPC [[buffer(1)]])
    {
        main0_out out = {};
        out.gl_Position = float4(in.pos, 0.0, 1.0);
        out.color_varying = (transformPC.mvp * float4(in.pos, 0.0, 1.0)).xy;
        out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
        return out;
    }

    #include <metal_stdlib>
    #include <simd/simd.h>
    
    using namespace metal;
    
    struct main0_out
    {
        float4 fragcolor [[color(0)]];
    };
    
    struct main0_in
    {
        float2 color_varying [[user(locn0)]];
    };
    
    fragment main0_out main0(main0_in in [[stage_in]])
    {
        main0_out out = {};
        out.fragcolor = float4(in.color_varying.x, 0.2, in.color_varying.y, 1.0);
        return out;
    }

**Comment by 741g** [comment]
I can also give the full sequence of API calls; I'm just working on a Hello world sample app at the moment. Link here in AOSP Gerrit:

https://android-review.googlesource.com/c/platform/external/qemu/+/803202/16/android/android-emugl/host/libs/libOpenglRender/samples/HelloVulkan.cpp

**Comment by billhollings** [comment]
@741g 

What makes you think the fragment colours are not being interpolated? 

Is that what is happening on a render? Do you have screenshots to share of what you are expecting...and what is being rendered?

**Comment by 741g** [comment]
Screenshots (also in https://github.com/KhronosGroup/MoltenVK/issues/327#issuecomment-436499731):

Intended look (libportability, Linux / Windows Vulkan drivers):

![image](https://user-images.githubusercontent.com/32140436/48110474-2e093480-e201-11e8-8fb2-9570b4ffa405.png)

With MoltenVK:

![image](https://user-images.githubusercontent.com/32140436/48110477-33ff1580-e201-11e8-984d-4697cb7582e6.png)

Same Vulkan call sequence

https://android-review.googlesource.com/c/platform/external/qemu/+/803202/16/android/android-emugl/host/libs/libOpenglRender/samples/HelloVulkan.cpp

was used in all cases.

**Comment by billhollings** [comment]
Closing this. Let's use #327 to focus on your issue.
