### ISSUE TITLE
iOS Dylib is Built with x86_64

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#337]
Since commit 7354f8d, the create_dylib script is building for arch x86_64 instead of arm64 for iOS. The previous commit 82cf132 builds correctly for arm64 for the iOS dylib.

**Comment by billhollings** [comment]
Thanks. Fixed. Will be released today.

**Comment by billhollings** [comment]
Fixed in PR #340. Please retest and close if successful.

**Comment by DiegoAce** [comment]
Yep! It's fixed now. Thanks!
