### ISSUE TITLE
Absolute path in python scripts

### ISSUE THREAD

**Issue by camots** [KhronosGroup/MoltenVK#342]
Some xcode projects (such as Hologram) fail to compile in OSX due to 'pyton3 not found'. The reason is that in several scripts python3 is invoked by using the absolute path: /usr/bin/python3. In OSX however, due to SIP, one preferably does not install python3 under /usr/bin. If you are using the anaconda distribution for example, it can be located anywhere in order not to violate Mac OSX SIP.

Therefore I suggest to remove the absolute path such as '/usr/bin/python3' in the python-scripts (located for example in External/Vulkan-Tools/scripts) and replace it by 'python3'.
This would offer the flexibility to define the path to 'python3' through the PATH variable.

**Comment by camots** [comment]
@billhollings 

Yes, External/VulkanSamples/Sample-Programs/Hologram/generate-dispatch-table was causing the trouble concerning compilation of Hologram. And in fact, the launch of python3 is done correctly by '#!/usr/bin/env python3'. The problem in my case was that the PATH variable used in Xcode is missing the location of my python3 installation location which is set through .profile. But the Xcode PATH variable contains /usr/local/bin, which is not under OSX SIP. Thus I could create a link to python3 in /usr/local/bin. So External/VulkanSamples/Sample-Programs/Hologram/generate-dispatch-table is fine as it is.

However, a search for '/usr/bin/python3' in the MoltenVK directory reports lots of python scripts (see below). Within those, python3 is invoked by absolute path through /usr/bin which is protected under OSX SIP. Therefore all occurrences of '#!/usr/local/bin/python3' should be replaced by '#!/usr/bin/env python3'

Do you want me to report this issue to VulkanSamples repository?

----------------
grep -r "/usr/bin/python3" *
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/cgenerator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/lvl_genvk.py:#!/usr/bin/python3
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/threading_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/object_tracker_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/loader_extension_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/mock_icd_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/parameter_validation_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/helper_file_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/reg.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/unique_objects_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/VulkanSamples/scripts/dispatch_table_helper_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/Vulkan-Tools/scripts/kvt_genvk.py:#!/usr/bin/python3
Demos/LunarG-VulkanSamples/Vulkan-Tools/scripts/mock_icd_generator.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/Vulkan-Tools/scripts/common_codegen.py:#!/usr/bin/python3 -i
Demos/LunarG-VulkanSamples/Vulkan-Tools/scripts/vulkan_tools_helper_file_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/cgenerator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/lvl_genvk.py:#!/usr/bin/python3
External/VulkanSamples/scripts/threading_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/object_tracker_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/loader_extension_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/mock_icd_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/parameter_validation_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/helper_file_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/reg.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/unique_objects_generator.py:#!/usr/bin/python3 -i
External/VulkanSamples/scripts/dispatch_table_helper_generator.py:#!/usr/bin/python3 -i
External/Vulkan-Headers/registry/cgenerator.py:#!/usr/bin/python3 -i
External/Vulkan-Headers/registry/genvk.py:#!/usr/bin/python3
External/Vulkan-Headers/registry/generator.py:#!/usr/bin/python3 -i
External/Vulkan-Headers/registry/reg.py:#!/usr/bin/python3 -i
External/Vulkan-Tools/scripts/kvt_genvk.py:#!/usr/bin/python3
External/Vulkan-Tools/scripts/mock_icd_generator.py:#!/usr/bin/python3 -i
External/Vulkan-Tools/scripts/common_codegen.py:#!/usr/bin/python3 -i
External/Vulkan-Tools/scripts/vulkan_tools_helper_file_generator.py:#!/usr/bin/python3 -i

**Comment by camots** [comment]
@billhollings 

Excuse my typo in the previous post. I would like to say:
Therefore all occurrences of '#!/usr/bin/python3' should be replaced by '#!/usr/bin/env python3'

**Comment by camots** [comment]
@karl-lunarg 
Yes, your summary of my post is correct.
Thank you for the article. It points to PEP 394. 
The article does not state '#!/usr/bin/env python3' isn't good. 
It rather says:
'#!/usr/bin/env python' should never be used and instead 
'#!/usr/bin/env python 2' OR '#!/usr/bin/env python 3.' should be used.

This is also stated in the referring PEP 394:
"In order to tolerate differences across platforms, all new code that needs to invoke the Python interpreter should not specify python, but rather should specify either python2 or python3 (or the more specific python2.x and python3.x versions; see the Migration Notes). This distinction should be made in shebangs, when invoking from a shell script, when invoking via the system() call, or when invoking in any other context."

While this recommendation is strictly followed through all scripts in the MoltenVK package, I think assuming python2 or python3 to be installed in /usr/bin is generally too restrictive and in macOS specifically (due to SIP) it is simply a no go. In my opinion '#!/usr/bin/env pythonX' gives the user the possibility to make the script working without tweaking the OS in a dirty way.

**Comment by billhollings** [comment]
Closing as not a MoltenVK issue. The scripts of concern are components of other repositories.
