### ISSUE TITLE
GLSL > MSL imageAtomicAdd error

### ISSUE THREAD

**Issue by remoe** [KhronosGroup/MoltenVK#345]
Version: 1.0.26

This GLSL code:

```glsl
...
layout(binding = 15, r32ui) uniform uimageBuffer gLightsCounter;
...
uint _449 = imageAtomicAdd(gLightsCounter, 0, 1u);
```

generates wrong MSL code:

```c++
uint _449 = atomic_fetch_add_explicit((volatile thread atomic_uint*)&(gLightsCounter, 0), 1u, memory_order_relaxed);
```

The error:

[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (error code 3):
Compilation failed: 

program_source:170:87: warning: expression result unused
                uint _449 = atomic_fetch_add_explicit((volatile thread atomic_uint*)&(gLightsCounter, 0), 1u, memory_order_relaxed);
                                                                                      ^~~~~~~~~~~~~~
program_source:170:85: error: cannot take the address of an rvalue of type 'int'
                uint _449 = atomic_fetch_add_explicit((volatile thread atomic_uint*)&(gLightsCounter, 0), 1u, memory_order_relaxed);
                                                                                    ^ ~~~~~~~~~~~~~~~~~

**Comment by cdavis5e** [comment]
There is no "right" code for this, because Metal doesn't support this. This is known to Apple (rdar://41859236); dunno when it'll be fixed.

**Comment by cdavis5e** [comment]
But when it *is* fixed in Metal, we'll still be generating incorrect code for this. But that's an issue with [SPIRV-Cross](/KhronosGroup/SPIRV-Cross), which MoltenVK uses to handle shader modules.

**Comment by billhollings** [comment]
Is there anything to be done on this issue for now...or can we close it?
