### ISSUE TITLE
MSL conversion error: Cannot yet map non-aliased parameter to Metal resource!

### ISSUE THREAD

**Issue by kruseborn** [KhronosGroup/MoltenVK#346]
I am compiling this simple shader file with the newest version of MoltenVK. And I´m getting  non-aliased error from the Shader Converter tool.

```
./MoltenVKShaderConverter -gi test.glsl -mo test.metal -t f
Read GLSL from file: test.glsl
Could not convert SPIR-V in file: test.glsl
MSL conversion error: Cannot yet map non-aliased parameter to Metal resource!
```

```
#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
layout (std140, set = 0, binding = 0) uniform UBO {
mat4 mvp;
} ubo;
vec4 frontToBackAlpha(sampler2D inputTexture) {
return texture(inputTexture, vec2(1.0,1.0));
}
layout (location = 0) out vec4 outFragColor;
layout (set = 1, binding = 0) uniform sampler2D frontTexture;
void main() {
vec4 color = frontToBackAlpha(frontTexture);
outFragColor = color;
}
```

It looks like the error came from:
```
spirv_msl.cpp
if (auto *var = maybe_get_backing_variable(img_var))
{
   if (var->parameter && !var->parameter->alias_global_variable)
      SPIRV_CROSS_THROW("Cannot yet map non-aliased parameter to Metal resource!");
   img_var = var->self;
}
```

But if you look at the definition for `alias_global_variable`, it says:
```
// Set to true if this parameter aliases a global variable,
// used mostly in Metal where global variables
// have to be passed down to functions as regular arguments.
// However, for this kind of variable, we should not care about
// read and write counts as access to the function arguments
// is not local to the function in question.
bool alias_global_variable;
```

**Comment by kruseborn** [comment]
So what is the solutions, to rewrite all shader functions to use global image variables instead? What´s the timeline for a fix?

**Comment by kruseborn** [comment]
I don´t know if this is related, but I reverted the `!var->parameter->alias_global_variable` flag, everything worked but now our volume `shader` is a lot slower than previous version

**Comment by kruseborn** [comment]
We have a pretty large raycaster for a 3D-volume rendering, with shadows, blending etc. So a lot of texture lookups. We saw a drop from ~40 fps to ~10 fps.

**Comment by billhollings** [comment]
@kruseborn 

Among other things...Issue #306 proposes allowing the ability to turn swizzling off via MoltenVK configuration.

Would that help in your case? Do you need texture swizzling?

If not...can you try turning it off by setting `swizzle_texture_samples` to `false` in `spirv-msl.hpp` and then recompiling MoltenVK?

**Comment by kruseborn** [comment]
@billhollings Turning swizzling off via a configuration sounds like a good idea. I tested to set the swizzle_texture_samples flag to false and the speed was back again.

**Comment by billhollings** [comment]
Closing this to merge it into issue #306.

**Comment by billhollings** [comment]
PR #450 add config settings for texture swizzling...and disables it by default...and removes the problem that was causing the OP's error (thanks to @cdavis5e).
