### ISSUE TITLE
16-bit pixel formats packing order

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/MoltenVK#353]
Vulkan's channels order in packed formats enum names is usually reversed comparing to Metal.

Compare:
- `VK_FORMAT_R4G4B4A4_UNORM_PACK16` -> `MTLPixelFormatABGR4Unorm`
- `VK_FORMAT_R5G5B5A1_UNORM_PACK16` -> `MTLPixelFormatA1BGR5Unorm`
- `VK_FORMAT_A2B10G10R10_UNORM_PACK32` -> `MTLPixelFormatRGB10A2Unorm`
- `VK_FORMAT_A2B10G10R10_UINT_PACK32` -> `MTLPixelFormatRGB10A2Uint`
- `VK_FORMAT_B10G11R11_UFLOAT_PACK32` -> `MTLPixelFormatRG11B10Float`
- `VK_FORMAT_E5B9G9R9_UFLOAT_PACK32` -> `MTLPixelFormatRGB9E5Float`

However, these two mappings from `mvk_datatypes.mm` don't follow this rule:
https://github.com/KhronosGroup/MoltenVK/blob/2fa610a51059ec1003b9a844cc4aae5f1f5297be/MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm#L208

https://github.com/KhronosGroup/MoltenVK/blob/2fa610a51059ec1003b9a844cc4aae5f1f5297be/MoltenVK/MoltenVK/Vulkan/mvk_datatypes.mm#L210
Was it an overlook?

**Comment by billhollings** [comment]
Metal documentation is not explicit on those specific packed formats.

But you are right...based on consistency...it is likely that the orders are reversed...and they will not display correctly.

I'll attempt to test those formats explicitly with Vulkan CTS.

Have you encountered issues with those formats in testing? Or have you just noticed it in the mappings?

**Comment by KenThomases** [comment]
The docs for `MTLPixelFormat` do state that data is stored in little-endian order. And, an older version of the docs used to have this sentence:

> For example, `MTLPixelFormatB5G6R5Unorm` data would be stored in memory as: `gggbbbbb rrrrrggg`.

That is: a byte whose least significant bits held the blue value and whose most significant bits held part of the green value, then a byte whose LSBs held the rest of the green value and whose MSBs held the red value. So, the left-to-right order of the components in the format name is the least-to-most significant ordering in bits and bytes.

**Comment by billhollings** [comment]
@KenThomases 

Thanks for the older doc reference. Yes...it looks from that reference that Metal is consistent with their little-endian approach...even with packed formats. That mapping will be reversed from the Vulkan spec.
