### ISSUE TITLE
Slow performance when binding multiple compute pipelines in single command buffer

### ISSUE THREAD

**Issue by mark-grimes** [KhronosGroup/MoltenVK#356]
When writing a compute operation that has to perform several stages in series:

1. global input -> compute shader 1 -> output image 1
2. output image 1 -> compute shader 2 -> output image 2
3. ...
4. output image [n-1] -> compute shader [n] -> global output

So in Vulkan:
```
for( all [n] stages ) {
    vkUpdateDescriptorSets(...)
    vkCmdBindPipeline(...)
    vkCmdBindDescriptorSets(...)
    vkCmdDispatch(...)
    vkCmdPipelineBarrier(...)
}
```

The compute shaders are each unique specialisations of about 4 different fundamental types, i.e. I have ~4 different shader SPIR-V files but each has unique VkSpecializationInfo.  The shaders aren't doing anything particularly difficult (mostly convolutions). Everything is recorded into a single command buffer and everything is created and recorded ahead of time.

Everything works except that I'm experiencing horrendous performance, to the point that at n=~80 the operation fails with `Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error (IOAF code 2)`.  If I omit the `vkCmdBindPipeline(...)` command after all but the first shader, I get the wrong result (obviously, since I'm using the wrong code) but performance is more what I'd expect.

The following figure is the runtime for several values of [n] on the x-axis to try and factor out uncertainties from submission overheads.
![vulkancomputeperformance](https://user-images.githubusercontent.com/6480160/49154288-e95c4f00-f30f-11e8-8949-a57054537239.png)
Yes, the y axis is in *seconds*.  The green line is what I'd expect given the simplicity of the calculations.

The shaders could be better optimised but I'm confident they're not doing anything fundamentally stupid.  My work group sizes are at the maximum allowed on the hardware.

So this raises the questions:

1. Is frequent binding of different pipelines (created in advance) expected to be this expensive in either Vulkan generally or MoltenVK specifically, or is this a bug?
2. Are derivative pipelines implemented in MoltenVK, and would they help in this situation? From the [vulkan spec](
https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#pipelines-pipeline-derivatives): "...more efficient (on either host or device) to switch/bind between children of the same parent".
3. Am I better off architecting to have one single uber shader and switching functionality based on values passed in buffers and/or push constants so that I only ever have one `vkCmdBindPipeline(...)`?

**Comment by mark-grimes** [comment]
There's some flaw in my logic about attributing to bind pipeline.  If I run with all the binds and no-op shaders it's fast, so I must be doing something stupid in the shaders.  Closing.

**Comment by billhollings** [comment]
@mark-grimes 

Thanks for the detailed analysis and troubleshooting!

If you check out your shaders...and it turns out that the shaders are running slowly due to suboptimal SPIR-V to MSL conversion...please post an issue to the [SPRIV-Cross issues list](https://github.com/KhronosGroup/SPIRV-Cross/issues)...so we can sort it out.
