### ISSUE TITLE
Xcode can not find Prefix.pch file when run Vulkan Examples

### ISSUE THREAD

**Issue by LWSSS** [KhronosGroup/MoltenVK#357]
When all steps suggested by  README_MoltenVK_Examples.md have been done  and tried build examples provided by Vulkan ,Xcode show error :
    error: Build input file cannot be found: '/Users/.../Vulkan/xcode/iOS/Prefix.pch'
Is that a issue can be resolved by MotenVK?

**Comment by billhollings** [comment]
At present...MoltenVK is tested against a [different fork](https://github.com/brenwill/Vulkan) of the Sascha Willems Vulkan demos.

Can you try testing against that...and let us know if you still encounter the issue?

Eventually we will sync the two repos properly.

**Comment by LWSSS** [comment]
@billhollings 
I have redownload MoltenVK of the fork , and do the same steps by Read.me . now xcode can build examples success. it looks like i downloaded wrong fork of  MoltenVK . >_<
Another question is when build scheme MoltenVK package / MoltenVK package(ios only),my mac`s  CPU usage rate   will rise very high , more than 90%(My MAC and Xcode will be really kartun). Perhaps there something`s wrong in program.
I haven`t build scheme MoltenVK Package for mac yet. 
Thanks for reply again because real helpful  ^-^

**Comment by billhollings** [comment]
@LWSSS 

I'm glad you are able to build the Vulkan examples now.

Regarding CPU usage...are you saying the CPU usage is very high when you build MoltenVK? Or are you saying the CPU usage is very high when you run one of the Vulkan examples (and if so...which one)?

**Comment by LWSSS** [comment]
@billhollings 
When build MoltenVK , with scheme MoltenVK package  or MoltenVK package (ios only) ,cpu usage rised high .

**Comment by LWSSS** [comment]
@billhollings 
Hi...
     I want to know what does it mean  Scheme  : examples-ios -> build setting ->  Preprogressor  Macros -> Debug -> DEBUG = 1 _DEBUG
     I noticed the fps will changed on iPhone device screen with the DEBUG value changed (DEBUG = 0 or DEBUG = 1 even DEBUG = 2)
   Is that means DEBUG = 0 ,demo build examples with OpenGL ES or DEBUG = 1 ,demo build examples with Metal ?

**Comment by billhollings** [comment]
It's normal for the CPU to run high during a build of MoltenVK from source. Xcode runs multiple threads to maximize the CPU and reduce build times.

`DEBUG=1` and `_DEBUG` are commonly used build setting macros used to selectively include debugging features in a library or app. Typically these debugging features will add overhead and it is not surprising that you would see a reduced FPS. 

If you are curious...you can search through the S-W source code for where those two macros are used to include debugging features.

When building an app for production, you should use the `Release` build mode, which does not enable those kind of debugging macros...in order to provide the best performance possible.

**Comment by LWSSS** [comment]
@billhollings 
Hi...
   I think there is a bug on program
   when building demos on iPhone , the fps showed on screen is changed very different everytime launch app(some times 61fps, sometimes 152fps, or  some times 212fps).it is normal .
so , I read the program carefully, then I think there has a bug in vulkan-master -> base ->vulkanexamplebase.cpp , line 259 : "lastFPS = frameCounter; " I think it is not correct, it should be "lastFPS = static_cast<uint32_t>((float)frameCounter *(1000.0f/fpsTimer));"  
     will you read the program again and verify that it is correct?
     Thankyou...

**Comment by billhollings** [comment]
You are correct! Thanks for pointing that out. I've fixed it and updated the `brenwill/Vulkan` repository.

And when I get a chance...I'll try work towards synchronizing the `Sascha-Willems/Vulkan` repository with the `brenwill/Vulkan` repository.

I'm closing this issue now. If you encounter other concerns, please open a new issue.
