### ISSUE TITLE
vk::createInstance() returns vk::Result::eSuccess even when apiVersion = VK_API_VERSION_1_1

### ISSUE THREAD

**Issue by francoisbertelatschrodinger** [KhronosGroup/MoltenVK#358]
I am using SDK 1.1.92.1 (27-Nov-2018) on macOS Mojave 10.14.1 on a mid-2012 MacBook Pro.
I both tried with the VK_ICD_FILENAMES environment variable pointing to the MoltenVK_icd.json in the SDK hierarchy and to a file pointing to a MoltenVK_icd.json in a fresh debug build of MoltenVK. They both depict the same behavior.

As far as I understand, MoltenVK does not support Vulkan 1.1 yet. Still if you pass VK_API_VERSION_1_1 instead VK_API_VERSION_1_0 to apiVersion attribute of vk::ApplicationInfo struct, vk::createInstance() returns vk::Result::eSuccess where it should return vk::Result::eErrorIncompatibleDriver.

With a success to report support of 1.1, negative height for VkViewport should be allowed. However,
in this context, when calling vkCmdSetViewport(), the validation layer report the following message:

validation layer: vkCmdSetViewport: pViewports[0].height (=-270.000000) is not greater 0.0. The Vulkan spec states: height must be greater than 0.0 (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkViewport-height-01772)

This warning disappears as soon as I enable VK_KHR_maintenance1 or VK_AMD_negative_viewport_height extension on the logical device (wether I pass VK_API_VERSION_1_0 or VK_API_VERSION_1_1 as apiVersion to vk::ApplicationInfo struct).

I have been reported this issue in the validation layers project: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/503 but it was suggested that the bug is in MoltenVK itself. This is why I am opening this issue here.

**Comment by cdavis5e** [comment]
At a first glance, I don't see why this is happening. We're already doing this check [here](https://github.com/KhronosGroup/MoltenVK/blob/85ba42a0a7ee69f1c6ce52e23c1c10876dd0ab15/MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm#L126). That you're able to ask for a 1.1 instance and get a 1.0 instance back is strange. I wonder if something in the Vulkan loader is responsible for this.

**Comment by francoisbertelatschrodinger** [comment]
Thank you for clarifying this.

To close the loop, I am just giving you the output of my MacBook pro here to confirm what you are suggesting:

Note also that I read the 1.1.86 spec section "3.2 Instances" page 53 about `VkApplicationInfo` where it recommends to first check if `vkGetInstanceProcAddr(nullptr,"vkEnumerateInstanceVersion")` returns a non null pointer as a way to figure out if the instance supports 1.1 or not.

For my machine, it does. Subsequently I called `vk::EnumerateInstanceVersion()` which return 1.1.0 once decoded with the Vulkan Version Number Macros `VK_VERSION_MAJOR|MINOR|PATCH().` (Appendix F: API Boilerplate)

Once I request a 1.1 instance, the properties of the first physical device returned are:

apiVersion=1.0.92
driverVersion=10027
vendorID=4318
deviceID=4053
deviceType=DiscreteGpu
deviceName=NVIDIA GeForce GT 650M

**Comment by billhollings** [comment]
PR #450 logs the requested Vulkan API version and the supported API version in human readable form.
