### ISSUE TITLE
Support for VK_KHR_shader_float16_int8 float16 capability

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#368]
Hi,

already opened SPIRV-Cross issue..
https://github.com/KhronosGroup/SPIRV-Cross/issues/783
interested in float16 part of the spec.. altough int8 support would be nice also.. don't know if Metal also supports it natively..
maybe it's very easy to implement seeing:
https://github.com/KhronosGroup/MoltenVK/issues/86

thanks..

**Comment by cdavis5e** [comment]
Just as soon as Vulkan-Headers picks up the 1.1.95 changes...
