### ISSUE TITLE
Binding memory to an object after mapping results in an invalid mapped pointer

### ISSUE THREAD

**Issue by ArtVandelae** [KhronosGroup/MoltenVK#377]
I began experiencing strange memory corruption and crashes when dealing with host-visible mapped memory after updating MoltenVK on code that has no validation errors and no issues with Nvidia and Intel on Linux and Windows.  After building MoltenVK with the address sanitizer enabled I discovered the cause:

My application maps host-visible memory immediately after allocation but before it's bound to a buffer, the underlying behavior of which was changed in commit 958f56fb853cf8a9cdaec9f329d1efdc691f810d inside MVKDeviceMemory.mm. Calling vkMapMemory() on an allocated chunk of host visible memory that has not yet been bound to a buffer results in an internal call to ensureHostMemory(), which allocates memory with posix_memalign() and returns the pointer.  When this memory is later bound to a buffer object via a call to vkBindBufferMemory(), MVK internally calls ensureMTLBuffer(), which frees the previously allocated memory and leaves the calling application that mapped the memory with a pointer that points to freed memory.

Basic repro steps:

1. Create a buffer object //vkCreateBuffer()
2. Get the buffer memory requirements //vkGetBufferMemoryRequirements()
3. Allocate host visible memory for the buffer //vkAllocateMemory()
4. Map and get a pointer to the host visible memory //vkMapMemory()
5. Bind the memory to the buffer //vkBindBufferMemory()
6. The pointer to the memory mapped in step 4 is now invalid and writing to it causes undefined behavior.

**Comment by billhollings** [comment]
It sounds like this is related to #175.

Since you are binding to a buffer instead of an image...this can probably be fixed by having `vkMapMemory` create a `MTLBuffer` instead of raw host memory...if the memory allocation is less than the max size of a `MTLBuffer`. When the `VkBuffer` is bound to the device memory...the existing `MTLBuffer` could be connected to it...instead of being copied into it.

**Comment by ArtVandelae** [comment]
I built and tested cdavis5e's branch with the fix and everything seems to be working as expected again.

Thanks for fixing this so quickly!
