### ISSUE TITLE
Updating a sampled image descriptor (not image-sampler-combination) make app (macOS and iOS) crashes inside vkUpdateDescriptorSets() 

### ISSUE THREAD

**Issue by HongkunWang** [KhronosGroup/MoltenVK#394]
Hi,
I have a Vulkan app modified from a sample project and it runs well on Windows and Android, but crashes when update a sampled image with VkDescriptorImageInfo struct. The crashes happens when calling the API function "vkUpdateDescriptorSets(...)", there is no any error message shown in the IDE console.

After step into the MoltenVK lib with source code, I noticed that the control goes into a case that handles a **combined image sampler** (**VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER**), but the actual descriptor I try to update has type of **sampled image** (**VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE**). 

**Note**: I use a separate sampler in fragment shader, that's why I do not use image-sampler-combination. I followed LunarG API sample "separate_image_sampler" to design my shader and it works well on Windows and Android.
Could this be a bug in MoltenVK?

=========================================
Call tracing:
```
template<typename DescriptorAction>
void MVKDescriptorSet::writeDescriptorSets(const DescriptorAction* pDescriptorAction, size_t stride, const void* pData) 
{
	...    <<<=== At this point, the descriptorType is VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE !!!
        remainCnt = mvkDescBind->writeBindings(srcStartIdx, dstStartIdx, remainCnt,
	...
}

```
Then when go inside the next function, control falls into the case that handles VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER:

```
uint32_t MVKDescriptorBinding::writeBindings(uint32_t srcStartIndex, ...)
{
	uint32_t dstCnt = MIN(count, _pBindingLayout->_info.descriptorCount - dstStartIndex);
	switch (_pBindingLayout->_info.descriptorType) 
	{

		case VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER:
			...      <<<==== Control actually goes here ???
			break;

		case VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE:
			...      <<<==== Should goes here !!!
			break;

```

**Comment by cdavis5e** [comment]
The code here keys off the descriptor type that was set in the descriptor set layout, not the one in the `VkWriteDescriptorSet` struct, on the assumption that they are the same anyway. According to the Vulkan spec, when you call `vkUpdateDescriptorSets()`:

> * `descriptorType` **must** match the type of `dstBinding` within `dstSet`

In other words, you have to set the same descriptor type here that you set when you created the descriptor set layout. Otherwise, you enter "undefined behavior" territory. Anything goes here. MoltenVK is well within its rights to crash here. It just happens to work with the drivers you tried on Windows and Linux. If you had run your sample with the validation layer enabled on Windows or Linux, it would almost certainly have caught this.

**Comment by HongkunWang** [comment]
Thanks cdavis5e, upon your suggestions, I fixed the problem.
I did have validation layers turned on for Windows and Android, none of them caught this though. I guess they simply let the passed-in parameter **descriptorType** take precedence over the one in vkDescriptorSet.

**Comment by cdavis5e** [comment]
Huh... Based on my understanding of the spec, I would've thought that the validation layer would've caught that. Perhaps my interpretation is wrong, and it is in fact valid to write a `VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE` to a descriptor of type `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`. Or maybe that's just a bug in the validation layer. Would somebody better versed than I in this care to chime in?

**Comment by HongkunWang** [comment]
I have added a protection for this descriptor type mismatching problem in my classes. 
Somebody can help to label this issue as "closed"? If I close it by "Close" button, it will be gone from the main listing?

**Comment by HongkunWang** [comment]
Issue has been solved.
