### ISSUE TITLE
VkSurfaceCapabilitiesKHR's currentExtent property does not reflect the latest app window size so handling app resizing failed?

### ISSUE THREAD

**Issue by HongkunWang** [KhronosGroup/MoltenVK#398]
![screen shot 2018-12-13 at 1 32 44 pm](https://user-images.githubusercontent.com/13367835/49959484-ac7d8400-fedb-11e8-9e29-ddef893017f6.png)
I noticed that the MoltenVK's "Cube" demo does not handle window resizing properly (window is resized on macOS, or screen is rotated on iOS). I decided fix this problem but did not succeed. 

Sorry for posting a lengthy post since I have to express myself clearly:

### 1. General mechanism
Cube app uses function **demo_resize()** to respond to resize event. Inside the function it destroy and recreate swpachain, buffers and all related stuff to make the next frame is rendered according to the new content size.

```
static void demo_prepare_buffers(struct demo *demo) 
{
	...
	// Check the surface capabilities and formats
	VkSurfaceCapabilitiesKHR surfCapabilities; <<=== Supposed to contain the latest size !!!
	err = demo->fpGetPhysicalDeviceSurfaceCapabilitiesKHR(demo->gpu, demo->surface, &surfCapabilities);

	printf("@@@@ Surface Capabilities extent: %d X %d\n", surfCapabilities.currentExtent.width, surfCapabilities.currentExtent.height);
	...
```
**surfCapabilities** is retrieved here since we'll need its property **currentExtent** to provide the latest surface size when re-create our swapchain and etc.

### 2. First, let macOS/iOS app respond to resize event
The first thing I noticed that the **cube.c** uses a "passive" way to respond the size change, which relies on error "**VK_ERROR_OUT_OF_DATE_KHR**" when doing vkAcquireNextImageKHR() and vkQueuePresentKHR(). Based on my test, this passive mechanism does not work for macOS (when you resize the app window, device is not lost!), and it works for iOS (when you rotate your iPhone screen). Anyway, I decided to add a "active" and more secure way to let app respond to screen resize:

I simply add the relevant delegate (WindowDidResize for macOS, viewWillTransitionToSize for iOS) and inside the delegate function I call **demo_resize(&demo)**, this guarantees the event is handled.

### 3. Problem on macOS
Property **surfCapabilities.currentExtent** always returns the very initial app window size. as the result, the new swapchain is created with the old / wrong size, and app content is not "stretched" to fit the new window size.

### 4. Problem on iOS
Property **surfCapabilities.currentExtent** returns the new screen size, but is "one-step-late", which mean when you rotate your iphone for the first time, it returns the initial orientation size, when you rotate your iphone again, it returns the "previous" screen orientation, and so on. So the new swapchain still get wrong size

### 5. On other platforms (irrelevant to MoltenVK)
Android has similar problem to iOS, I patched it by retrieving the latest screen size manually and use it to re-create the swapchain.
Windows has no problem, every time the app window is resized, **surfCapabilities.currentExtent** gives the latest size so that it works perfectly.

**Comment by billhollings** [comment]
@HongkunWang 

I'm not sure I understand the nature of the problem you are describing.

When I resize the standard _Cube_ demo on macOS...it works as expected. The window resizes...and the demo app picks up the new surface size via the `VK_ERROR_OUT_OF_DATE_KHR` return value that you mention...and recreates the swapchain accordingly.

Similarly...if I enable the **_Portrait_** and **_Upside Down_** orientations on the **_General_** tab of the **_Cube-iOS_** target...it also works as expected...and the demo app picks up the new surface dimensions and recreates the swapchain accordingly.

Are you experiencing something different when you perform the same with the standard _Cube_ demo? Your screenshot above seems to indicate that the swapchain is not being updated...but that is not what I am experiencing.

**Comment by HongkunWang** [comment]
I'll double check it again, this will take a bit time. I did made some minor modification on the cube demo.
I have noticed that Vulkan app sometimes behaves differently due to the drivers. For example, an ill-coded app may cause vulkan device lost on Radeon but runs well on GeForce.
BTW My testing environment:
**macOS**: macBook Pro(2013), Intel i7 with HD Graphics 4000, macOS Mojave
**iOS**: iPhone 6 plus, iOS 12

On macOS, When I resize the app window, it did trigger the demo_resize() to re-construct swapchain and etc. Then it finally goes into the MoltenVK library function:

```
@implementation CAMetalLayer (MoltenVK)
-(CGSize) naturalDrawableSizeMVK {
    CGSize drawSize = self.bounds.size;		<<== always return the initial size
    ...
    return drawSize;
}
```
I noticed that  **self.bounds.size** always return the initial window size, which means no matter how you resize your window, the returned size are the same, and it will be used to re-create the new swapchain and etc. 
What I'm trying to do is retrieve the latest screen size / main window size on the fly, like follows:

```
@implementation CAMetalLayer (MoltenVK)
-(CGSize) naturalDrawableSizeMVK {
    //CGSize drawSize = self.bounds.size;
    #if (MVK_IOS)	//iOS
        CGSize drawSize = [[UIScreen mainScreen] bounds].size;
    #elif (MVK_MACOS)	//macOS
        CGSize drawSize = [[NSApp mainWindow] frame].size;
    #endif
    ...	
    return drawSize;
}

```

I have not got it working yet ...

**Comment by HongkunWang** [comment]
Have not got it working yet.
I have to leave this issue temporarily, close it first.
