### ISSUE TITLE
Feature Request: IOSurface-specific Setting Y-Axis Flip

### ISSUE THREAD

**Issue by paulreimer** [KhronosGroup/MoltenVK#405]
I am attempting to integrate with an existing software framework that shares global `IOSurface`s between macOS apps (apps can be either a "server" which publishes frames, or a "client" which receives them -- in this case I am building a "server" to publish my swapchain resolve texture.)
[Syphon Framework](http://syphon.v002.info/)

Because any existing apps already using the framework were designed expecting OpenGL-backed `IOSurface`s, the y-axis from my Vulkan apps (and by extension my `IOSurface` if using `vkUseIOSurfaceMVK`) is now flipped upside-down in these programs (eg. draws well to the screen, but other "client" apps see a flipped image).

I think that ideally MoltenVK could provide an option that would flip the orientation as it is seen by the `IOSurface` (if this is possible, it seems easiest). Or maybe there's a standard way to accomplish this in Vulkan, I'd prefer the most performant approach, whatever that is.

**Comment by billhollings** [comment]
Right now...you have a couple of options with MoltenVK:

1. When rendering to the `IOSurface` use a viewport with a negative height (part of the supported `VK_KHR_maintenance1` extension). This would probably be the most "standard Vulkan" way of flipping the rendering of an image.

2. Set the value of `MVKConfiguration::shaderConversionFlipVertexY` to `false` before compiling the render pipeline through which you will render to the `IOSurface` (and probably set it back to `true` after for other rendering). The documentation for `MVKConfiguration` and the `vkGetMoltenVKConfigurationMVK()` and `vkSetMoltenVKConfigurationMVK()` functions explain how manipulate the MoltenVK configuration...and the `MoltenVK_Runtime_UserGuide.md` document includes an example of using these functions.

Please check out the features above. If they don't help you get what you need, we can look to adding other options in a future enhancement.

**Comment by billhollings** [comment]
Closing.
