### ISSUE TITLE
VK_ERROR_FEATURE_NOT_PRESENT vkCmdDrawIndexed() on iPhone 6 plus, is this reported before?

### ISSUE THREAD

**Issue by HongkunWang** [KhronosGroup/MoltenVK#415]
Not sure this problem has been reported before?
When run the Hologram sample (source code from MoltenVK SDK, not modified) on iPhone 6 plus (iOS 12), app generates the following rum-time errors:

[***MoltenVK ERROR***] VK_ERROR_FEATURE_NOT_PRESENT: vkCmdDrawIndexed(): The current device does not support drawing with a non-zero base vertex.

Is this just a feature not supported yet by MoltenVK, or has not been found on iPhone 6/6s?

Also the rendering does not seems to be right on iPhone 6, see the attached screenshot, there is no alpha blending.
![img_0004](https://user-images.githubusercontent.com/13367835/50132444-353a4e00-0255-11e9-8d4b-af9ac371371c.PNG)

**Comment by aerofly** [comment]
We encountered the same problem. Older iOS devices do not support the non zero base vertex when rendering, it's true for iPad mini 4 as well. We fixed this by setting the base vertex to always zero when calling vkCmdDrawIndexed and applying the proper offset when calling vkCmdBindVertexBuffer.

I am not sure if this could actually be applied within MoltenVK or not.

**Comment by billhollings** [comment]
Non-zero base vertices requires an A9 SoC or better.

@aerofly Interesting idea...but I'm not sure we could deal with this internally. It sounds like it would require temporarily rebinding the right buffers during the draw call.

I'm closing this issue. If there are ideas about how to handle this internally within MoltenVK...we can open another issue as an enhancement request.
