### ISSUE TITLE
vkGetPhysicalDeviceProperties2KHR seg fault

### ISSUE THREAD

**Issue by paulreimer** [KhronosGroup/MoltenVK#417]
Trying to find out whether multiview is supported (I think it is NOT supported in MoltenVK, but just wanted to confirm, via `VK_KHR_get_physical_device_properties2` extension).

I can't seem to get either `vkGetPhysicalDeviceProperties2KHR` or `vkGetPhysicalDeviceProperties2KHR` functions working (seg fault at call site).
I have the instance extension enabled:
```
[mvk-info] Created VkInstance with the following Vulkan extensions enabled:                                                                                                                                  
                VK_KHR_get_physical_device_properties2 v1                                                                                                                                                    
                VK_MVK_moltenvk v13
zsh: segmentation fault ./app
```

I think I am using it correctly, I used a `vkp` prefix for the local function pointer, to make sure I am calling the right symbol:
```
VkPhysicalDeviceProperties2KHR deviceProps2{};
VkPhysicalDeviceMultiviewPropertiesKHR extProps{};
extProps.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES_KHR;
deviceProps2.sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHR;
deviceProps2.pNext = &extProps;
PFN_vkGetPhysicalDeviceProperties2KHR vkpGetPhysicalDeviceProperties2KHR = (
  reinterpret_cast<PFN_vkGetPhysicalDeviceProperties2KHR>(
    vkGetInstanceProcAddr(instance, "vkGetPhysicalDeviceProperties2KHR")
  )
);
if (vkpGetPhysicalDeviceProperties2KHR)
{
  vkpGetPhysicalDeviceProperties2KHR(physicalDevice, &deviceProps2);
  std::cout
  << "Multiview properties:" << std::endl
  << "\tmaxMultiviewViewCount = " << extProps.maxMultiviewViewCount << std::endl
  << "\tmaxMultiviewInstanceIndex = " << extProps.maxMultiviewInstanceIndex << std::endl;
}
```

I have a similar error when I try to use `vkGetPhysicalDeviceFeatures2KHR` (seg fault), omitted for brevity.

**Comment by billhollings** [comment]
@cdavis5e Can you review this, please?

**Comment by cdavis5e** [comment]
I recall there being a similar issue a while ago, but I fixed that. What version of MoltenVK are you using, @paulreimer?

**Comment by paulreimer** [comment]
Oddly I noticed the ordinary function symbol (with prefix `vk`) `vkGetPhysicalDeviceProperties2KHR` seemed to exist and link, even without doing a proc lookup (so, I added the `vkp` prefix to make sure I used the right symbol I just looked up). That symbol also segfaults similarly, no matter whether I've done the lookup first. But I was surprised to find that symbol existed without doing anything? Maybe it's nothing to be worried about.

**Comment by cdavis5e** [comment]
That's because you linked directly to MoltenVK. If you had linked to the Vulkan loader instead, the function wouldn't be visible.

**Comment by paulreimer** [comment]
OK that makes sense. I'll probably switch to using the MoltenVK.framework once the LunarG SDK is up-to-date.

**Comment by cdavis5e** [comment]
Hey, you know what I think the problem is? You didn't set the `pNext` pointer in `extProps` to `nullptr`. That leaves it with whatever garbage happened to be on the stack at that point. When I set it to `nullptr`, it works. (Of course, the multiview properties aren't filled in, because MoltenVK doesn't support `VK_KHR_multiview` yet.)

**Comment by paulreimer** [comment]
I think that the `{}` in `extProps{};` should do that, although it doesn't hurt to be explicit (so I added it, thanks!)

But, unfortunately the segfault result is the same. These functions could be called anytime, right? (Assuming the instance and physicalDevice are valid at that point), not like it has to be called before doing something else or cannot be called after? Other than the above code snippet (which is executed after `kkEnumeratePhyiscalDevices` but before `vkCreateDevice`) and enabling the instance extension, I'm not doing any other setup.

**Comment by cdavis5e** [comment]
I cannot reproduce this.

I've attached [a small Vulkan program](https://github.com/KhronosGroup/MoltenVK/files/2696630/test.c.txt). You can build it with:

```bash
clang -o test test.c <path/to/libMoltenVK.a> -lc++ -framework Cocoa -framework IOKit \
    -framework IOSurface -framework QuartzCore -framework Metal
```

(after renaming the file so it has a `.c` extension and replacing `<path/to/libMoltenVK.a>` with the actual path, of course). This program does not crash for me. Does it crash for you?

How are you building MoltenVK? How are you creating the `VkInstance`?

**Comment by paulreimer** [comment]
That works! Thanks for providing that, it helped to identify my issue, my `physicalDevice` had not been initialized at the point of use. My bad, sorry to take your time on this!
