### ISSUE TITLE
Stuck Running Fetch Dependencies

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#419]
I can't run the fetch dependencies script without it getting stuck. It gets stuck building glslang around 90%. The new parallel building is also unusually extreme. It completely takes over my computer. I can't open or use other programs during the process. I've sometimes can't force quit it when it gets stuck and have to shut down my computer with the power button. I didn't use to have any of these problems before the parallel build commit. 
I'm using a 2017 iMac, and I've tried running it without any other open programs using memory.

**Comment by billhollings** [comment]
If you remove the `-j` option on the `make` in `fetchDependencies` are you able to build successfully?

Perhaps we could add a command line option to `fetchDependencies` to turn parallel building off?

**Comment by DiegoAce** [comment]
It worked when I removed `-j`. It also worked using `-j4`. But I tried again and it continues to freeze with `-j`. I'm not sure why.

**Comment by KenThomases** [comment]
If you pass just `-j` with no number, that means that make won't limit the number of jobs it runs at once. It will create as many jobs as there are targets that can be built independently of each other. It's a fork bomb. The script should probably use `-j $(sysctl -n hw.activecpu)` or something like that.

**Comment by DiegoAce** [comment]
`-j $(sysctl -n hw.activecpu)` worked and also let me use my computer normally during the process.

**Comment by billhollings** [comment]
@KenThomases  Thanks for the suggestion.

@DiegoAce  Can you submit a PR with that fix?

**Comment by DiegoAce** [comment]
Sure! PR #424

**Comment by billhollings** [comment]
Thanks! Closing.
