### ISSUE TITLE
Add build support for arm64e devices

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#431]
When linking the project against libMoltenVK.a in iOS build, none of Vulkan symbols get resolved. I am using pre-built binaries from 1.1.92.1 SDK. I tried all static, dynamic and framework options, but result is the same. For macOS, everything works fine. I am building for arm64 in XCode 9.4.1.

**Comment by DiligentGraphics** [comment]
I looked at MoltenVKPackaging XCode project, and it looks like the package is only built for i386 and x86_64 architectures, which would explain unresolved symbols. The question is then, what's the point in supplying pre-built binary that does not contain arm64 architecture?

**Comment by billhollings** [comment]
Within MoltenVK...the `MoltenVKPackaging` _Xcode_ project does indeed build the iOS `arm64` versions too. They end up located in `Package/Latest/MoltenVK/iOS`.

Within the LunarG SDK...these same libraries are located in the `MoltenVK/iOS` directory.

You can verify the iOS functionality by running the iOS demos in MoltenVK...which use those built libraries (static, dynamic, and framework). I can also run the same MoltenVK demos by linking to the libraries in `MoltenVK/iOS` directory in the SDK, instead.

I'm not clear from your description what the context of your issues is...but perhaps their source is that the LunarG SDK itself (and the Vulkan layers it provides) does not officially support iOS development yet.

If so...for the time being...you may need to forego the LunarG SDK layers and link directly to the MoltenVK "driver" libraries in the `MoltenVK/iOS` directory in the SDK itself...or the `Package/Latest/MoltenVK/iOS` directory in MoltenVK if you build directly from MoltenVK using the `MoltenVKPackaging` _Xcode_ project.

**Comment by DiligentGraphics** [comment]
My issue is not related to LunarG SDK layers because in fact I do not use them. I am trying to link my source code against pre-built MotlenVK libraries that I took from LunarG SDK. It works perfectly fine in MacOS build, but when I try to build the same source for iOS, none of Vulkan functions get resolved. 

I presumed that pre-built libraries are built with the MoltenVKPackaging xcode project, so I looked at the configuration for MoltenVK-iOS project and under Architectures found something that looks very confusing to me:

* Architectures: Standard Architectures (64-bit Intel)
* Base SDK: no SDK (macOS)
* Supported platforms: macOS
* Valid architectures: i386 x86_64

The only way I can read these settings is that the project is only configured for simulator build which is even more odd since as far as I understand, Metal is not supported on simulator (btw, how can that even be possible?)

I tried adding arm64 and arm64e to Architectures/Valid Architectures, but that produced no binaries at all.

**Comment by DiligentGraphics** [comment]
@cdavis5e Am looking at the [right project settings](https://ibb.co/611HDZr)?

> Because desktop Metal doesn't support everything that mobile Metal does.

I always though that this is what simulators are actually for. If some tiled-deferred features are not supported, the simulator could implement them in software. I bet there are not so many apps that actually use them, so majority of applications would be able to run in simulator without problems.

**Comment by cdavis5e** [comment]
> @cdavis5e Am looking at the [right project settings](https://ibb.co/611HDZr)? 

That's not it. I'm not even sure what the `MoltenVK-iOS` target in the `MoltenVKPackaging` project is for. You'll have to ask @billhollings about that.

The schemes (not targets) I listed will build the `MoltenVK-iOS` target from the `MoltenVK` subproject, which *should* have the correct settings. */me looks* Yep.

> > Because desktop Metal doesn't support everything that mobile Metal does.
> 
> I always though that this is what simulators are actually for. If some tiled-deferred features are not supported, the simulator could implement them in software. I bet there are not so many apps that actually use them, so majority of applications would be able to run in simulator without problems.

Good point.

Now that I think about it, I think the other, and more likely, reason is that when Metal was introduced in iOS 8, macOS didn't support it *at all*. I think Apple intended to release Metal with 10.10, but something caused them to think it wasn't ready yet. For whatever reason--probably a lack of developer time--Apple hasn't gotten around to adding Metal support to the simulator.

**Comment by billhollings** [comment]
@DiligentGraphics 

You do not need to make any Xcode build setting changes. 

Out of the box...the `MoltenVK` target will build _both_ macOS & iOS libraries. As @cdavis5e mentions...you fire up the build by running the `MoltenVK Package` scheme from within Xcode...or via `make` from the command line.

The `MoltenVK-iOS` project will build _only_ the iOS libraries. You fire it up using the `MoltenVK Packaging (iOS only)` scheme from Xcode...or via `make ios` from the command line. For the iOS libraries...this does exactly the same thing as the `MoltenVK` target above. It just doesn't bother building the macOS libraries...as a build-time convenience for developers who are only building for one platform.

Either will work. In both cases...the iOS libraries will be built for `arm64`...and you do not need to play with any Xcode build settings to get it to do so. 

To be more precise...the `MoltenVK` and `MoltenVK-iOS` targets in the `MoltenVKPackaging` Xcode project are aggregate targets...and both have as a prerequisite the `MoltenVK-iOS` target in the `MoltenVK` subproject...which is where all the work actually happens...and is where the `arm64` architecture is specified.

You should be able to verify all this from a clean MoltenVK repo...by leaving all the Xcode settings alone...and just running the `MoltenVK Package` scheme...and then running the _Cube_ or _Hologram_ demos (in the `Demos` folder) on an iOS device.

**Comment by DiligentGraphics** [comment]
OK, so I finally figured out what the problem was. As it turned out, xcode project generated by CMake enabled both arm64 and arm64e architectures, but MoltenVK library apparently only has arm64, which is why I had all these link issues. 
Thank you for your help.
The last question is, are there plans to add arm64e architecture to pre-built binaries?

**Comment by billhollings** [comment]
Ah! Good catch!

Yes...of course...MoltenVK should definitely support arm64e. 

I'll look into it.

**Comment by billhollings** [comment]
@DiligentGraphics 

To answer about targets...as mentioned above, the `MoltenVK-iOS` target in the `MoltenVK` Xcode project is where the actually libraries are built and the architecture is specified.

The targets in the `MoltenVKPackaging` Xcode project have that target as a build prerequisite.

PR #437 adds support for arm64e builds. Please test and close if it fixes the issue you had with your build.

**Comment by DiligentGraphics** [comment]
@billhollings Honestly, this issue does not seem to be fixed as arm64e is not generated by the build because [`ARCHS` only contain arm64](https://github.com/KhronosGroup/MoltenVK/pull/437#issuecomment-450780711)

**Comment by billhollings** [comment]
Hmmm...

`ARCHS` is already set to`$(ARCHS_STANDARD)` as recommended by the error you were seeing...but Xcode does not seem to be translating that correctly to include `arm64e`.

I've tried setting `ARCHS` directly to `arm64 arm64e` but I am running into issues building with bitcode enabled. It's possible that Xcode is not handling all the combinations correctly.

Okay. We'll leave this open until we get a definitive fix.

**Comment by billhollings** [comment]
According to the [Xcode 10.1 Release Notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_1_release_notes?language=objc)...`arm64e` support is listed as a _Preview_ technology and is not currently deployable.

>Support for arm64e (Preview). 
The App Store and TestFlight don't accept submissions containing arm64e. Xcode will remove arm64e content from your app when you distribute from the Organizer window.

Since it is interfering with Bitcode deployment...and is not currently usable...I think we should wait to include support for `arm64e` in MoltenVK until Apple has worked out the integration issues...and it becomes usable, deployable technology.

Once Apple has it sorted out in Xcode...it should be a simple matter to change the `ARCHS` and `VALID_ARCHS` build settings in all MoltenVK targets (including shader converter and external libraries) from `arm64` to `arm64 arm64e`.

In the meantime...if anyone can figure out how to get `arm64e` to play nicely with Bitcode and dynamic library building...feel free to submit a PR here.

**Comment by billhollings** [comment]
PR #442 removes support for `arm64e`.

**Comment by Xioor** [comment]
I was able to use Vulkan with MoltenVK using SDL2 with libMoltenVK.dylib on a real ios device, but libMoltenVK.dylib does not work on an ios simulator because libMoltenVK.dylib is only created for arm64
(The one provided in vulkansdk-macos-1.1.114.0/MoltenVK/iOS/dynamic)

I am trying to find a way to create libMoltenVK.dylib with other architectures, but so far I have been unsuccessful. Does anyone have any ideas? I think I am close I tried playing around with MoltenVK/Scripts but no luck.

Architectures need to be: x86_64 and arm64.

Some old posts online say that metal does not work on ios simulator, but a newer forum post from an Apple developer say that Xcode 11 supports metal for ios simulators

**Comment by billhollings** [comment]
@Xioor Your request is not really related to the original topic. Can you move this to another issue, please?

Linking with the simulator will require some effort to build an x86_64 library (probably static) that can be linked when building for the simulator.

Once you create the new issue, we can discuss priority.

**Comment by Xioor** [comment]
@billhollings Here is the new issue: https://github.com/KhronosGroup/MoltenVK/issues/726

**Comment by dolphineye** [comment]
Hey guys,

Bumping an old issue. It looks like `arm64e` support was removed in early January 2019. Is there any plan to support it back as of 2020? AFAIK it is not yet supported. Or am I doing something wrong?

Thanks for helping!

**Comment by iMonZ** [comment]
Hey,

anything new?

Also now you can add support for arm64e for macOS and catalyst too!

**Comment by billhollings** [comment]
MoltenVK currently builds binaries using `ARCHS = "$(ARCHS_STANDARD_64_BIT)"`, which Xcode currently resolves to `arm64e` only for tvOS. For macOS, it includes `arm64` and `x86_64`.

Assuming Apple knows what it's doing in defining `ARCHS_STANDARD_64_BIT` with each version of Xcode, as a default, I would prefer to stay aligned with whatever the current Xcode configurations are, and automatically transition to `arm64e` support when Xcode does.

There are also hints as to perhaps why Xcode doesn't build for `arm64e` by default, at 9:00 in [this WWDC video](https://developer.apple.com/wwdc20/10686).

Are there practical reasons for deviating from this?

**Comment by iMonZ** [comment]
> MoltenVK currently builds binaries using `ARCHS = "$(ARCHS_STANDARD_64_BIT)"`, which Xcode currently resolves to `arm64e` only for tvOS. For macOS, it includes `arm64` and `x86_64`.
> 
> Assuming Apple knows what it's doing in defining `ARCHS_STANDARD_64_BIT` with each version of Xcode, as a default, I would prefer to stay aligned with whatever the current Xcode configurations are, and automatically transition to `arm64e` support when Xcode does.
> 
> There are also hints as to perhaps why Xcode doesn't build for `arm64e` by default, at 9:00 in [this WWDC video](https://developer.apple.com/wwdc20/10686).
> 
> Are there practical reasons for deviating from this?

Thank you for your research!
To use the new features in my application.
Since there aren’t ready yet we have to wait!
All Apple internal apps are using arm64e
