### ISSUE TITLE
Very poor performance on Mac compared to OpenGL

### ISSUE THREAD

**Issue by mlfarrell** [KhronosGroup/MoltenVK#434]
I had a whole detailed thing typed here and I lost it.. ugh.

MoltenVk is performing very very very poorly on my mac - worse than OpenGL by a factor of 2 or 3.  I suspect it's lack of triple buffering - swapchain acquire next image blocks way too long.  On windows, using same code, i use triple buffering with mailbox and get thousands of frames per second (even outperforming OpenGL), on mac I get disastrous performance.

Built via xcode with release settings.  Running with validation off.  CPU time spent generating CBs is negligible - 90% of time blocked in acquire next image.  

I can't upgrade my users to a slower experience, so I can't ship my product like this.

![image](https://user-images.githubusercontent.com/7664370/50552027-824bf600-0c3f-11e9-9a05-0f76a0122367.png)

**Comment by mlfarrell** [comment]
A part of me believes that we shouldn't be waiting for any fences during the acquire step.  I feel like just calling next drawable should suffice right?  My app already synchronizes command buffer usage with its own fences.

**Comment by billhollings** [comment]
See PR #433. It should be part of MoltenVK by tomorrow (Monday)...once we get the final design discussion resolved.

In the meantime...if you want to try triple buffering...pull that PR in...or simply change the value of `pSurfaceCapabilities->maxImageCount` to 3  in `MVKDevice.mm` in your local copy...and rebuild MoltenVK.

I'll be very interested to hear whether or not double-buffering was the culprit.

**Comment by mlfarrell** [comment]
That’s flippin awesome. I’m on day job until wed or Thursday. I’ll update back here then. 

I’m 80% sure it’ll fix the issue since I can’t put my extra frame in flight with only 2 swapchain frame buffers - leading to the low GPU utilization. The manual call to mvkWaitForFences under acquire does somewhat have me concerned, but I won’t worry about that until I try the PR first.

**Comment by mlfarrell** [comment]
Other office was closed today so I had a chance to test.  No dice.  It's still slow unfortunately.  

Indeed I'm getting back 3 images and I'm able using immediate present mode (fallback since mailbox isn't supported)

For some reason, I'm still not getting the performance I need.  I'm starting to wonder what the "display" red/blue colors in the metal instruments tool really represent.

![image](https://user-images.githubusercontent.com/7664370/50566027-ce537500-0ce9-11e9-99cb-240c0c2ebb53.png)

**Comment by billhollings** [comment]
@mlfarrell 

Thanks for the feedback.

Since Vulkan fences are a GPU/CPU sync mechanism...depending on where you have them in your render loop...they could definitely be creating blocking between the CPU and GPU.

If you get some further information...we can look to see if the fence implementation in MoltenVK is somehow behaving less efficiently than other native Vulkan implementation.

**Comment by mlfarrell** [comment]
Something is definitely still wrong.  See this image.  

After enabling 3-in flight buffers, my order of triple buffering is seemingly correct
My debug output:
```
...
Wait Fence 0 // unique fence  
Submit 0        //unique command buf for frame 0   -----------------------------------  vv                   
Wait Fence 1 // unique fence                                                                       
Submit 1         //unique command buf for frame 1                                                                
Wait Fence 2 // unique fence                                                                                                 
Submit 2        //unique command buf for frame 2                                                                
Wait Fence 0 // should not block unless we are backed up by 2 frames. <-------------- ^^
...
```

The fence I'm waiting on seems to not be signaled until the most recently submitted command buffer is completed - which isn't right.  I'm diving through MoltenVk code now to try to find out what's wrong.

![image](https://user-images.githubusercontent.com/7664370/50567368-fac2bd80-0cf8-11e9-81b1-46df7e13db2e.png)

**Comment by mlfarrell** [comment]
I think I may know what's wrong

```
....
Waiting for frame 0
2018-12-31 13:12:20.130741-0800 VGLPP Demo[20695:797350] Waiting for fence 0x102576e00
2018-12-31 13:12:20.130989-0800 VGLPP Demo[20695:797575] Submitting for fence: 0x102576e00
2018-12-31 13:12:20.136946-0800 VGLPP Demo[20695:797574] Signalling fence: 0x102576e00 with 1 sitters
Fence wait took 6.269 ms
Submitting frame 0

Waiting for frame 1
2018-12-31 13:12:20.137291-0800 VGLPP Demo[20695:797350] Waiting for fence 0x102577090
2018-12-31 13:12:20.137522-0800 VGLPP Demo[20695:797575] Submitting for fence: 0x102577090
2018-12-31 13:12:20.143207-0800 VGLPP Demo[20695:797674] Signalling fence: 0x102577090 with 1 sitters
Fence wait took 5.978 ms
Submitting frame 1

Waiting for frame 2
2018-12-31 13:12:20.143570-0800 VGLPP Demo[20695:797350] Waiting for fence 0x102577320
2018-12-31 13:12:20.143819-0800 VGLPP Demo[20695:797575] Submitting for fence: 0x102577320
2018-12-31 13:12:20.149412-0800 VGLPP Demo[20695:797574] Signalling fence: 0x102577320 with 1 sitters
Fence wait took 5.906 ms
Submitting frame 2

Waiting for frame 0
2018-12-31 13:12:20.149769-0800 VGLPP Demo[20695:797350] Waiting for fence 0x102576e00
2018-12-31 13:12:20.150003-0800 VGLPP Demo[20695:797575] Submitting for fence: 0x102576e00
2018-12-31 13:12:20.156313-0800 VGLPP Demo[20695:797674] Signalling fence: 0x102576e00 with 1 sitters
Fence wait took 6.616 ms
Submitting frame 0
....
```

Look at the first part, frame 0.  The submission for that is being held by MoltenVk for some reason and not actually submitted until inside vkWaitForFences call (aka one of the sitters is holding onto my queue submission which should have gone through ages ago).  Vulkan should not be implicitly synchronizing queue submissions like this.  The synch should be left up to the API user.

**Comment by mlfarrell** [comment]
Okay... I enabled MVK_CONFIG_SYNCHRONOUS_QUEUE_SUBMITS and got the fence waiting to pass without much time spent.  Big win there.  But.. now I'm losing the 6 ms inside queue present (MVKQueuePresentSurfaceSubmission::execute()).  

**The culprit here is**
```for (auto& ws : _waitSemaphores) { ws->wait(); }```

Semaphores in Vulkan are a **GPU** sync primitive, not CPU.  The CPU shouldn't be waiting on these.

**Comment by billhollings** [comment]
@mlfarrell 

I'm glad you've made such strong progress!

Yes...Vulkan semaphores should sync just between GPU activities...independent of CPU.

True GPU-GPU semaphores (Metal calls them Fences) were introduced later in Metal...and have not been incorporated into MoltenVK yet. One of the reasons for that is that almost all semaphores are used just to sync the swapchain images...and generally have very little impact on performance blocks there.

Nevertheless...MoltenVK needs to implement true GPU-GPU sync...and it's good to see someone hitting a real need for it. I've added issue #438 to track it as an enhancement.

**Comment by mlfarrell** [comment]
Great!  In the meantime, for the case of image acquire semaphore, I _think_ for swapchain present, you can leave the wait out entirely since nextDrawable seems to be doing it implicitly on the GPU.  But for other GPU-GPU sync stuff, I’m glad you’ll have a way forward on that.  Also this may be a case for making synchronous queue submits default to on?  

Regarding Apple reversing the naming of fences and semaphores, 🤦‍♂️

**Comment by billhollings** [comment]
Replaced with issue #438.

**Comment by billhollings** [comment]
PR #450 enables synchronous queue submits by default.
