### ISSUE TITLE
Implement Vulkan semaphores via MTLEvent or MTLFence if supported on the platform.

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#438]
Currently Vulkan semaphores are implemented in MoltenVK on the CPU...because Metal originally did not support any form of GPU-GPU sync.

Now that MTLFence is available...investigate whether they can be used to implement Vulkan semaphore GPU-GPU sync functionality.

**Comment by billhollings** [comment]
See issue #434 for use case.

**Comment by maddanio** [comment]
maybe as a motivating use case: we do postprocessing where the intermediate image has a resolution different from the final output, so it seems we cannot use subpasses there. so instead we do two different render passes and then we need semaphores to enforce happens-after between them.

**Comment by cdavis5e** [comment]
I'm not sure `MTLFence` *can* be used to implement `VkSemaphore`. According to the Vulkan spec:

> Semaphores **can** be used to control resource access across multiple queues.

But according to [an Apple engineer on Apple's Metal forum](https://forums.developer.apple.com/thread/108416#334883):

> You must use a fence to sychronize [sic] untracked resource across command buffers from the same queue. [...] However, you cannot use a fence to synchronize untracked resources access [sic] by two command buffers running in parallell [sic] from seperate [sic] queue (you need to use an MTLEvent for this).

So this can't be implemented properly without `MTLEvent`. I think we want to use `MTLEvent` anyway: this will make it easier to support external semaphores using `MTLSharedEvent` the way Windows Vulkan supports Direct3D 12 fences as `VkSemaphore`s.

**Comment by cdavis5e** [comment]
The example given in the [Metal Programming Guide](https://developer.apple.com/library/archive/documentation/Miscellaneous/Conceptual/MetalProgrammingGuide/ResourceHeaps/ResourceHeaps.html#//apple_ref/doc/uid/TP40014221-CH16-SW6) seems to corroborate Omachi's observation:

>>>
> You are still responsible for sequencing command buffer submission queues, as shown in Listing 13-4. However, fences do not allow you to control inter-queue command buffer sequencing.
>
> **Listing 13-4**  Sequencing fences across command buffer submission queues
>```objc
>id <MTLFence> fence = [_device newFence];
>id <MTLCommandBuffer> commandBuffer0 = [_commandQueue0 commandBuffer];
>id <MTLCommandBuffer> commandBuffer1 = [_commandQueue1 commandBuffer];
> 
>// Producer
>id <MTLRenderCommandEncoder> renderCommandEncoder = [commandBuffer0 >renderCommandEncoderWithDescriptor:_descriptor];
>/* Draw using resources associated with 'fence' */
>[renderCommandEncoder updateFence:fence afterStages:MTLRenderStageFragment];
>[renderCommandEncoder endEncoding];
> 
>// Consumer
>id <MTLComputeCommandEncoder> computeCommandEncoder = [commandBuffer1 computeCommandEncoder];
>[computeCommandEncoder waitForFence:fence];
>/* Dispatch using resources associated with 'fence' */
>[computeCommandEncoder endEncoding];
> 
>// Ensure 'commandBuffer0' is scheduled before 'commandBuffer1'
>[commandBuffer0 addScheduledHandler:^(id <MTLCommandBuffer>) {
>     [commandBuffer1 commit];
>}];
>[commandBuffer0 commit];
>```

>>>

**Comment by cdavis5e** [comment]
On the other hand, this example indicates that it *might* be possible--*if* we can control when command buffers are committed to the queue.

**Comment by billhollings** [comment]
@cdavis5e  Thanks for the research.

Hmmm...

The forced scheduling of command buffers using scheduling callbacks in that example seems to imply that there is a single physical queue underpinning the two `MTLCommandQueues`...otherwise simply scheduling one command buffer after the other wouldn't ensure they run that way across two separate queues. I wonder if we should rely on the assumption of a single physical queue?

The example is also fairly contrived in that the app knows what sequence it needs and manually forces it. I'm wondering if the logic can be made sufficiently generic to be mapped to Vulkan semaphores.

Also from that example...`MTLFence` seems almost to be more equivalent to Vulkan pipeline barriers.

But in any case...we could investigate `MTLEvents` for use in both Vulkan semaphores & events.
