### ISSUE TITLE
Handling window resize

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#443]
I am trying to understand what the right way to handle window resize is.

The cube sample simply ignores any window resize notifications and recreates the swap chain when `AcquireNextImageKHR` fails. This works, however window resizing is jagged: the window content is not re-rendered every frame during the resize, but sometimes scaled by the OS instead. As a result, everything that need not be scaled with the window size (such as UI) shiver. This can be easily reproduced by fixing viewport size in cube demo (lines 768, 769 in cube.c) and trying to resize the window:

```
 viewport.height = 1024;//(float)demo->height;
 viewport.width = 1024;//(float)demo->width;
```

Besides that, waiting for an error to resize does not seem to be the most elegant approach as other components of the system may depend on the screen size.

I tried to handle `boundsDidChange` notification and resize the swap chain from there, but this produces flickering (the screen now flashes black during resize, which is even worse).

In OpenGL mode, flickering is fixed by rendering the scene from `drawRect:`.  In Vulkan mode, `wantsUpdateLayer` returns true, but `updateLayer` is never called.

So do you know if there is a way to gracefully handle resize to avoid flickering and jaggies?

**Comment by HongkunWang** [comment]
Hi there,
I also do not like the solution of recreating swapchain triggered by error, so I did the same way like you to do it actively when detect window is resized.
As for the "screen flickering", I think if we have an app flag variable "bool isDoingResizing". Set it to true during the resizing and set it to false when resizing is done. Do not render content when the flag is true. This may avoid flickering but unfortunately we are seeing black screen during the resizing. Not sure if this is good idea.

**Comment by KenThomases** [comment]
You can try experimenting with the `presentsWithTransaction` property of `MTKView` or `CAMetalLayer`. Also, read the docs for that method and try the technique there for synchronizing presentation with AppKit.

**Comment by DiligentGraphics** [comment]
@KenThomases Looks like this techniques relies on calling `waitUntilScheduled` on the command buffer used for presenting. Not sure how I can do this since the buffer is hidden in MoltenVK.

**Comment by cdavis5e** [comment]
I wonder if MoltenVK could `addScheduledHandler:` a block that signals a `VkFence`. That'd be the Vulkanish way to do it.

**Comment by billhollings** [comment]
@DiligentGraphics 

Following on @KenThomases suggestion of playing with `presentsWithTransaction `:

You could try experimenting with setting `CAMetalLayer::presentsWithTransaction` to `YES` in `MVKSwapchain::initCAMetalLayer()`...and setting `MVKConfiguration::presentWithCommandBuffer` to `false`...to have MoltenVK call `present` on the `CAMetalDrawable` directly.

**Comment by billhollings** [comment]
@DiligentGraphics   

What do you mean when you say `drawRect:` is a solution in OpenGL? Isn't `drawRect:` an artifact of the application design...not OpenGL itself?

If so...wouldn't the equivalent be a similarly-factored render-loop function in the Vulkan app?

**Comment by DiligentGraphics** [comment]
I meant, when running the app in OpenGL mode. Yes, it is definitely an artifact of the application design. It is only called during the resize. As far as I understand, in Vulkan when `wantsUpdateLayer` is `YES` the `drawRect` counterpart would be `updateLayer`, but it is never called.
