### ISSUE TITLE
Should [mvk-info] messages be turned off?

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/MoltenVK#45]
Related to #41, I think...

When I run vulkaninfo in Terminal, I see:
```
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 560
```
and various other `[mvk-info]` messages.

These messages also show up in a Xcode panel when running windowed apps.

This happens even with the Release build.  Is this expected or do we want these messages off by default and able to be turned back on via some setting or compile option?

**Comment by emilk** [comment]
The default release logging level (info) includes logging all Vulkan extensions and all GPU devices, which for me is around 116 lines of logging on start. I'd prefer if the default log level for release would only include warnings and errors.

I've tried disabling logging completely with `make GCC_PREPROCESSOR_DEFINITIONS=-DMVK_LOGGING_ENABLED=0 macos` but have no luck (my `make` skills are severely lacking though).

**Comment by billhollings** [comment]
@emilk 

>I'd prefer if the default log level for release would only include warnings and errors

Have a look at the documentation in `vk_mvk_moltenvk.h` regarding MoltenVK configuration settings.

If you are building MoltenVK from source, you can control the logging level with the `MVK_CONFIG_LOG_LEVEL` build setting. If you are running an app that links an already-built MoltenVK binary, you an control logging by using `MVK_CONFIG_LOG_LEVEL` as an environment variable.

Either way, the values for that build setting/environment variable are determined by the enum:

```
typedef enum MVKConfigLogLevel {
	MVK_CONFIG_LOG_LEVEL_NONE     = 0,	/**< No logging. */
	MVK_CONFIG_LOG_LEVEL_ERROR    = 1,	/**< Log errors only. */
	MVK_CONFIG_LOG_LEVEL_INFO     = 2,	/**< Log errors and informational messages. */
	MVK_CONFIG_LOG_LEVEL_MAX_ENUM = 0x7FFFFFFF
} MVKConfigLogLevel;
```

Of course, when setting `MVK_CONFIG_LOG_LEVEL ` as a build setting or environment variable, you will need to set it to one of the literal numeric values: `0, 1, or 2`.
