### ISSUE TITLE
MoltenVKShaderConverter doesn't error properly when using -d flag

### ISSUE THREAD

**Issue by jamesd9** [KhronosGroup/MoltenVK#455]
I'm using MoltenVKShaderConverter to convert a folder full of GLSL shaders at build time using the -d flag. However, if there is a compile error in one of the shaders the exit state is still EXIT_SUCCESS. I'd like to use the exit state to terminate the build process if appropriate so it's important that it be correct. (Note that it is already correct when not using the -d option.)

I've had a go at fixing this myself. The first change was to return false (rather than true) if the processFile call in mvk::iterateDirectory returned true - so the appropriate line in mvk::iterateDirectory becomes:

`if(fileProcessor.processFile(absFilePath.UTF8String)) { return false; }`

The second change was to make MoltenVKShaderConverterTool::processFile's return value depend on the values returned by convertGLSL and convertSPIRV:

```
bool MoltenVKShaderConverterTool::processFile(string filePath) {
	string absPath = absolutePath(filePath);
	string emptyPath;

	string pathExtn = pathExtension(absPath);
	if (_shouldReadGLSL && isGLSLFileExtension(pathExtn)) {
        	return !convertGLSL(absPath, emptyPath, emptyPath, kMVKShaderStageAuto);
	} else if (_shouldReadSPIRV && isSPIRVFileExtension(pathExtn)) {
        	return !convertSPIRV(absPath, emptyPath);
	}

    	return false;
}
```

This seems to fix the problem in my testing so hopefully you'll consider adding it to master version.

**Comment by billhollings** [comment]
@jamesd9 

I agree...it makes sense that the overall exit code should indicate that one or more files failed to convert.

However...your change will cause the directory iterator to abort processing any further files in the directory when any shader file conversion fails.

Is that what should happen? Or would it be better to continue processing the remaining files...and to correctly indicate the failure in the final exit code?

**Comment by billhollings** [comment]
PR #456 fixes this.

The converter tool will continue to iterate all files in the directory...even if one or more fail...but will exit with an error code if _any_ of the files fail conversion.

Please retest and close this issue if it fixes this issue.

**Comment by jamesd9** [comment]
For my purposes it doesn't matter whether the tool terminates or not when a file fails to convert, so your solution works for me too. I've tested it and it solves the original issue so I'm closing the bug. Thanks!
