### ISSUE TITLE
isVertexAttributeLocationUsed always returns false when using pre-compiled metal code

### ISSUE THREAD

**Issue by jamesd9** [KhronosGroup/MoltenVK#459]
I've prebuilt a simple glsl shader into a .metallib file, which I'm then passing to moltenvk using kMVKMagicNumberMSLCompiledCode. This works fine for a super-simple vertex shader with hardcoded coordinates (i.e. there are no vertex attributes etc.).

Unfortunately, if I use a slightly more complex shader which does use vertex attributes, metal complains that I am not passing any vertex attribute information. However, I am passing this information through the appropriate VkPipelineVertexInputStateCreateInfo structure:

```
    VkVertexInputBindingDescription bindingDescriptionTestVertexFormat =
    {
        .binding = 0,
        .stride = sizeof(TestVertexFormat),
        .inputRate = VK_VERTEX_INPUT_RATE_VERTEX,
    };
    
    VkVertexInputAttributeDescription attributeDescriptionsTestVertexFormat[2] =
    {
        {
            .binding = 0,
            .location = 0,
            .format = VK_FORMAT_R32G32_SFLOAT,
            .offset = offsetof(TestVertexFormat, pos),
        },
        {
            .binding = 0,
            .location = 1,
            .format = VK_FORMAT_R32G32B32_SFLOAT,
            .offset = offsetof(TestVertexFormat, colour),
        },
    };
    
    VkPipelineVertexInputStateCreateInfo vertexInputInfoTestVertexFormat =
    {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
        .vertexBindingDescriptionCount = 1,
        .pVertexBindingDescriptions = &bindingDescriptionTestVertexFormat,
        .vertexAttributeDescriptionCount = sizeof(attributeDescriptionsTestVertexFormat)/sizeof(VkVertexInputAttributeDescription),
        .pVertexAttributeDescriptions = attributeDescriptionsTestVertexFormat,
    };
```

And here's the vertex shader code: (let me know if you want me to send the .metal or .metallib versions)

```
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec2 inPosition;
layout(location = 1) in vec3 inColor;

layout(location = 0) out vec3 fragColor;

void main() {
    gl_Position = vec4(inPosition, 0.0, 1.0);
    fragColor = inColor;
}
```

It seems that MoltenVK is not passing the information I provided to metal. This seems to be due SPIRVToMSLConverterContext::isVertexAttributeLocationUsed returning false for all attributes. My guess is that this is due to the code being precompiled into a .metallib, rather than being built by MoltenVK, so MoltenVK doesn't know those locations are used.

My hack to fix this is to make SPIRVToMSLConverterContext::isVertexAttributeLocationUsed (and SPIRVToMSLConverterContext::isVertexBufferUsed as that has a similar problem) always return true. This fixes the problem for me as everything seems to render as expected. Obviously this isn't the correct fix - I guess ideally the usage information should be extracted from the compiled .metallib, or those functions should only always return true for precompiled files.

**Comment by billhollings** [comment]
This is fixed in PR #463. When loading MSL or compiled Metal libs, all attributes and resources are enabled. Please retest and close if fixed.

**Comment by jamesd9** [comment]
The fix looks promising, but it doesn't seem to be merged into the main branch yet so I can't figure out how to download your changes with my limited git knowledge. :/

**Comment by billhollings** [comment]
@jamesd9 Sorry for the delay in pulling it into the main branch. It's there now.

**Comment by jamesd9** [comment]
Thanks, I can confirm this is fixed. Closing the issue.
