### ISSUE TITLE
Consider making logging controllable at run time

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/MoltenVK#46]
Currently, MVK logging level is set as a compile-time option.  It may be useful to change this to a run-time option, controlled by an environment variable.  The Linux system loader does this via the `LD_DEBUG` environment variable and the Vulkan loader does it via `VK_LOADER_DEBUG`.

This would obviate the need to "keep around" or build MVK libs with various logging options.  It would also facilitate debugging in the field by asking the user to run their failing scenario with the env var turned on and then collect and forward the output for analysis.

**Comment by billhollings** [comment]
Implemented by PR #482.
