### ISSUE TITLE
Deformations of PVR textures on iOS 

### ISSUE THREAD

**Issue by abeyn** [KhronosGroup/MoltenVK#461]
I am using latest MoltenVK version 1.0.31 and do:
1. load texture in buffer with vkCreateBuffer;
2. create image with vkCreateImage and type VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG;
3. copy buffer to image with vkCmdCopyBufferToImage;
No validation errors on IOS, but texture looks without vertical synchronization.

If I add code in MVKCmdTransfer.mm:787
#if MVK_IOS
        if (mvkMTLPixelFormatIsPVRTCFormat(mtlPixFmt)) {
            bytesPerRow = 0;
        }
#endif
and disable Metal validation, texture looks right.

If I enable Metal validation, I got error:
-[MTLDebugBlitCommandEncoder validateCopyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:
sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:524: 
failed assertion `sourceBytesPerRow(0) must be >= (2048).'

**Comment by jamesd9** [comment]
I've run into the same issue - see #359 which should probably be reopened. A possible workaround might be to use a staging image rather than a staging buffer as mentioned here - [ https://stackoverflow.com/questions/51838872/blit-pvrtc-texture-metal?rq=1](url) - I haven't tested that though.

**Comment by billhollings** [comment]
@abeyn 

In what way is the value 2048 significant? Is that the actual size in bytes of a compressed row of blocks in your particular texture?

What happens with Metal validation...and with the image fidelity...if in your workaround you set `bytesPerRow` to that value instead of zero?

And what does MoltenVK calculate for `bytesPerRow` before you force it to zero?

I'm wondering if MoltenVK is not correctly calculating the width of a row of compressed PVRTC blocks.

**Comment by billhollings** [comment]
@abeyn  Thanks for posting the sample app.

I've played with the app a bit. Since that sample app is a Metal-only app...this looks to be a Metal bug.

The 2048 value is the correct row width for a 4bpp 1024x1024 PVRTC image...as indicated even by the Metal validation error. 

Either Metal should require 0 for row and image byte counts (as it does for `replaceRegion`)...and which it clearly likes here...or it should work with the actual row width value 2048.

I've [posted this](https://forums.developer.apple.com/message/347978#347978) to the Apple developer forums. Next stop will be to post a Metal bug.

**Comment by billhollings** [comment]
I've now [posted this](https://bugreport.apple.com/web/?problemID=47971252) to Apple's bug reporter.

**Comment by abeyn** [comment]
This workaround doesn't work on Iphone XR and Iphone XS
Print screen:
![IphoneXS](https://user-images.githubusercontent.com/5126902/54132878-aedd7480-441d-11e9-9788-51fe51694e7a.png)

New workaround:
1. Add check for compressed texture format in MVKImage::updateMTLTextureContent
   and set bytesPerRow = 0

    VkDeviceSize bytesPerRow = (imgType != VK_IMAGE_TYPE_1D ? imgLayout.rowPitch : 0);
    
    if (_mtlPixelFormat == MTLPixelFormatPVRTC_RGB_4BPP)
    {
        bytesPerRow = 0;
    }

    [getMTLTexture() replaceRegion: mtlRegion
                       mipmapLevel: imgSubRez.mipLevel
                             slice: imgSubRez.arrayLayer
                         withBytes: pImgBytes
                       bytesPerRow: bytesPerRow
                     bytesPerImage: (imgType == VK_IMAGE_TYPE_3D ? imgLayout.depthPitch : 0)];

2. In Vulkan code:
	vkCreateImage()
	vkAllocateMemory() with type VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT
	vkMapMemory()
	memcpy - compressed data
	vkBindImageMemory()
	vkUnmapMemory()

In this case compressed texture loads without deformations on Iphone XS and Iphone XR too.

**Comment by billhollings** [comment]
@abeyn 

Thanks for the update. I should update the MoltenVK code you identify.

How is your new workaround different than your previous workaround? Both seem to just be setting `bytesPerRow` to zero.

**Comment by abeyn** [comment]
1. This workaround doesn't use vkCmdCopyBufferToImage and changes other source 
MVKImage::updateMTLTextureContent.
2. In this case no validation errors from Metal

**Comment by billhollings** [comment]
Apple has confirmed @jamesd9's [suspicion](https://github.com/KhronosGroup/MoltenVK/issues/359#issuecomment-455554818) about `MTLBlitOptionRowLinearPVRTC` expecting the buffer content to be untwiddled.

Here is Apple's response from the recent bug report I posted about this:

>So basically the sample tries to use pre-twiddled data for [blitEncoder copyFromBuffer] instead of linear strided data, which is incorrect behavior. Replacing copyFromBuffer with replaceRegion fixes the issue (as expected when using pre-twiddled texturedata). Untwiddling the inputdata before creating the buffer also fixes them problem (as copyFromBuffer expects linear strided data). The reason that using a stride 0 works is an unexpected side effect that only works on devices that don’t support tiling (as the driver copies the pre-swizzled data as-is and creates a swizzled texture using this data). On hardware that does support tiling, the data is copied as-is and then used for a tiled view, which causes tiles to be incorrect. Suggested fix is to either use [texture replaceRegion] or to unswizzle the data before creating the buffer.

PR #539 includes @abeyn's [fix](https://github.com/KhronosGroup/MoltenVK/issues/461#issuecomment-471575487) to allow host-memory mapped PVRTC image content to be loaded correctly...and documentation to the effect that staging-buffers cannot be used with PVRTC content.

@abeyn Please test the latest MoltenVK without your patch above...to ensure that it fixes the issue for you...and close this issue if it does.

**Comment by abeyn** [comment]
Thank you very much. It work's.
