### ISSUE TITLE
How to set local workgroup size when using MSL input?

### ISSUE THREAD

**Issue by mark-grimes** [KhronosGroup/MoltenVK#468]
While trying to debug slow compute shaders, I started trying to use MSL input instead of SPIR-V using the instructions for [Metal Shading Language Shaders](https://github.com/KhronosGroup/MoltenVK/blob/master/Docs/MoltenVK_Runtime_UserGuide.md#shaders).  It works fine except that the compute shader doesn't run over the full range; there are only `groupCountX` invocations instead of `groupCountX*local_size_x_id` invocations.

On investigation (I'm new to Metal) it seems the local size is not specified in the shader as with GLSL/SPIR-V but given in the dispatch command with `threadsPerThreadgroup`.  Is there a way to use MSL input and specify the local workgroup size?

I've tried multiplying `groupCountX` by `local_size_x_id` manually in my call to `vkCmdDispatch`.  It works but I get horrendous performance, presumably because I have only one lane in a SIMD group doing any work.

**Comment by mark-grimes** [comment]
I should add that I'm specifying the local size in host code with specialisation constants, but MoltenVK doesn't pick that up.  So my remark

> ...local size...specified in the shader as with GLSL/SPIR-V...

above is not actually relevant.

**Comment by billhollings** [comment]
@mark-grimes 

Hmmm...the workgroup size as specified in the shader is extracted during conversion from SPIR-V to MSL.

If you provide the MSL directly...MoltenVK has no way of extracting that. I suppose if MSL source code is provided...we could try to parse it out textually...but that would be a second choice. And for compiled MSL we would be completely blind.

Your idea of providing workgroup size as Vulkan specialization constants might be reasonable.

To enable specialization...at present MoltenVK checks if `SPIRVWorkgroupSizeDimension::isSpecialized` is set...and that, unfortunately, is also set during the conversion from SPIR-V to MSL.

Perhaps we can force the setting of the workgroup size from specialization constants through the following modifications in `SPRIVToMSLConverter.h`:

Remove the initializers in `SPIRVWorkgroupSizeDimension`:

	typedef struct {
		uint32_t size;
		uint32_t specializationID;
		bool isSpecialized;
	} SPIRVWorkgroupSizeDimension;

...and initialize them in `SPIRVEntryPoint`:

	typedef struct {
		std::string mtlFunctionName = "main0";
		struct {
			SPIRVWorkgroupSizeDimension width = { 1, 0, true };
			SPIRVWorkgroupSizeDimension height = { 1, 1, true };
			SPIRVWorkgroupSizeDimension depth = { 1, 2, true };
		} workgroupSize;
	} SPIRVEntryPoint;

This will initialize each `SPIRVWorkgroupSizeDimension` to a thread count of 1, a unique default specialization ID, and enabled for specialization.

A normal SPIRV-MSL conversion will continue to overwrite these values from the shader...but they will be left alone for direct MSL import...and can be overridden by Vulkan specialization info.

Can you give these mods a try in your environment, please? 

Hopefully I've explained the idea well enough here...but if you have any questions about what I'm suggesting...fire away.

**Comment by mark-grimes** [comment]
Yes, this works as expected. I can put a pull request in if you want?
However, I'm not sure it will work for the general case.  I have all 3 dimensions specialised at layout 0, 1 and 2 so it works for me.  If a shader only specialises one dimension will it upset the other constants?

The only other option I can think of is to use a different magic number, e.g. `0x19960412` for no specialisations (as now); `0x19960413` followed by 4 bytes for the x specialisation; `0x19960414` followed by 4 bytes x and 4 bytes y etc.  This has its own drawbacks though.

I can achieve what I want though so I'm happy to close this if you don't want to worry about the general case.  Thanks.

**Comment by billhollings** [comment]
Glad it works this far.

Moving forward...are you thinking each 4-byte value (presumably a `uint32_t`) would contain the workgroup dimension size literal value...or the `constantID` of a specialization constant that would specify the workgroup dimension size?

Or perhaps we could support both options by including a flag in there somewhere too. Some form of extended `MVKMSLSPIRVHeader`, with a different magic number, that would look like:

```
typedef struct {
    uint32_t magicNumber;
    VkBoolean32 wgSizeIsSpecialized;
    uint32_t wgSizeX;
    uint32_t wgSizeY;
    uint32_t wgSizeZ;
} MVKMSLSPIRVHeaderWorkgroup;
```

I'm not sure we would need to support separate magic numbers for one, two, or three dimensions. I think we could just insist that developers populate all three dimension values of this single header. 

I'm looking for design input here from anyone who has an interest in this.

**Comment by mark-grimes** [comment]
"4 bytes" was completely arbitrary to illustrate the idea of a fixed byte pattern after the magic number to set the information.  Your suggestion looks better.  I was thinking of using the `constantID` - my host code decides workgroup size but the magic number is added by the build system (into a static lib of all shaders), so the literal size would complicate my particular workflow.
It might be nice to have it ascii compatible, so e.g. the structure after the magic number works out as "// 0 1 2" if the memory is viewed as ascii, then changes can be made directly in the shader. Having said that I'm not convinced the extra complication and brittleness outweighs the (small) benefit.

**Comment by billhollings** [comment]
Interesting idea...having a parsable header to the shader source text.

Unfortunately that wouldn't work for compiled MSL code though...and frankly if you're going to skip the SPIR-V step...why not go all the way to compiled MSL code? 😉

**Comment by MichaelE1000** [comment]
Are there any news on this?

I'm trying to port over a complex algorithm with several larger compute shaders. Unfortunately cross compiling the spirv code for one of those does not work out as the apple metal implementation on the ipad pro does not accept the shader code anymore. I ported it over to use MSL directly as well which solved the problem of being able to run the shader. Unfortunately now I also somehow have to set the work group size which I also realized is not yet possible?

**Comment by billhollings** [comment]
The `vkSetWorkgroupSizeMVK()` function was added  about a month ago (#635 & #637)...and is in latest 1.0.35 release.

It is also included in the 1.1.108 Vulkan SDK...but unfortunately this call might now work with a `VKShaderModule` that was created using the Loader...because the intervening layers can change the opaque object that is returned.

Let me know if that meets your needs here, and we can close this issue.

**Comment by MichaEiler** [comment]
This does the trick way more nicely :-). I unfortunately cloned the repository a few days before this was merged and therefore was not aware of it :(

**Comment by billhollings** [comment]
Okay. Sounds like we can close this issue then.
