### ISSUE TITLE
vkSetMTLTextureMVK doesn't call `retain` on the MTLTexture

### ISSUE THREAD

**Issue by mark-grimes** [KhronosGroup/MoltenVK#476]
N.B. this could be intended behaviour.

**Short version:**
When calling `vkSetMTLTextureMVK`, the `MVKImage::setMTLTexture` method releases the old `MTLTexture` but never retains the new one.

**Long version:**
I have a use case where I continually change the `MTLTexture` for a `VkImage` - basically for processing video frames retrieved from AVFoundation and feeding into a Vulkan compute shader.  To do this I:
1. Get a `CVImageBufferRef` for the frame from AVFoundation
2. Create a `CVMetalTextureRef` from this with `CVMetalTextureCacheCreateTextureFromImage`
3. Get a `id<MTLTexture>` from this with `CVMetalTextureGetTexture`
4. Apply the `MTLTexture` to the `VkImage` with `vkSetMTLTextureMVK`

Everything works except for unrestrained memory growth - I need to `CVBufferRelease` the `CVMetalTextureRef` (*big* memory growth, since this is per video frame).  If I do this then it crashes because the `CVMetalTextureRef` in turn releases the `MTLTexture` while Vulkan/MoltenVK is using it.  I've worked around this by calling `retain` on the `MTLTexture` before calling `vkSetMTLTextureMVK` - it all works and memory use is as expected (note no `release` on the next frame).  This is a bit of hassle because it's an ARC project, but it's possible, and I don't see this documented anywhere. So my code is now (per video frame):
1. Get a `CVImageBufferRef` for the frame from AVFoundation
2. Create a `CVMetalTextureRef` from this with `CVMetalTextureCacheCreateTextureFromImage`
3. Get a `id<MTLTexture>` from this with `CVMetalTextureGetTexture`
4. **Call `retain` on the `MTLTexture` through some work arounds for an ARC project**
5. Apply the `MTLTexture` to the `VkImage` with `vkSetMTLTextureMVK`
6. **Call `CVBufferRelease` with the `CVMetalTextureRef`**

Following through `vkSetMTLTextureMVK ` I find it releases the old texture as I would expect ([MVKImage.mm#L317](https://github.com/KhronosGroup/MoltenVK/blob/e5a890775bf6136d54b46c5b30670321b263c938/MoltenVK/MoltenVK/GPUObjects/MVKImage.mm#L317)), but it never calls retain on the new texture.

I would expect MVKImage to increase the reference count on the texture when it stores a reference. Is this intentional?  I'm happy to put in a pull request if not.

**Comment by billhollings** [comment]
@mark-grimes 

Thanks for pointing this out. It was an oversight...not intended behaviour.

Thanks for the offer to submit a PR...but it was as simple fix and I was in doing a couple of other fixes...so I fixed this in PR #480.

Please retest and close if it fixes this issue.

**Comment by mark-grimes** [comment]
Only applied a cursory check, but it seems to work.
