### ISSUE TITLE
vkQueuePresentKHR makes calling thread wait on pWaitSemaphores not the GPU

### ISSUE THREAD

**Issue by jamesd9** [KhronosGroup/MoltenVK#486]
vkQueuePresentKHR makes the calling thread wait on pWaitSemaphores rather than only the GPU waiting - see _waitSemaphores in MVKQueuePresentSurfaceSubmission::execute.

This is a serious performance issue as it means the main thread and GPU cannot operate in parallel - e.g. one would expect a triple buffered game to run at 60 fps if GPU time was 12ms and main thread CPU time was 12ms, but this is not the case currently.

Probably the easiest way to see this is to add a usleep(12000) to demo_draw in the cube demo. This should still leave enough time to run such a simple demo at 60fps, but performance instead drops to 52 fps. (Note that I was testing on an iPad Air 2 - you might need to tweak the sleep time for your device.)

If you then run a "game performance" profile on it you can see how the GPU does not wait until the next frame to execute the queue submission - it executes it immediately instead. You can also see how, as consequence of all this, the main thread ends up unnecessarily waiting on vkQueuePresentKHR, even as it is just about to drop a frame.

Using synchronousQueueSubmits doesn't seem to fix the issue as it just moves the stall to vkWaitForFences.

**Comment by jamesd9** [comment]
On further investigation, this seems to be related to #434. However, note that although adding support for MTLFence would be great, the real problem here is that the calling thread is being blocked when it shouldn't be. It should be possible to fix this without needing to implement support for MTLFence.

In the mean time, the workaround for this seems to be to not use any wait semaphores for vkQueuePresentKHR as they are not strictly necessary on iOS due to metal blocking on the nextDrawable command anyway. This then allows triple buffering to work correctly. However this obviously isn't a good fix (it's against the vulkan spec and means that other cases where wait semaphores should be used are going to be unnecessarily slow).

**Comment by Luke-Filewalker** [comment]
Got the same problem. I am currently porting Quake 3 to Vulkan/MoltenVK and I get very bad fps on macOS because the main thread always blocks when vkQueuePresentKHR is called. I am using triple buffering and immediate mode. The fix jamesd9 mentioned works, when I remove the semaphore, I have much better frametimes, tough I get a few artifacts.

**Comment by cdavis5e** [comment]
To fix this properly, we need to fix #602. Then we can use `MTLEvent` for this, which will cause the wait to happen on the GPU.

**Comment by billhollings** [comment]
> To fix this properly, we need to fix #602. Then we can use `MTLEvent` for this, which will cause the wait to happen on the GPU.

@cdavis5e Will you be able to look into fixing #602 soon? If not...I can work on it.

**Comment by cdavis5e** [comment]
> @cdavis5e Will you be able to look into fixing #602 soon? If not...I can work on it.

I've been meaning to look at this, but with the impending release of Catalina, I've been tied up fixing stuff broken on the current beta. I don't think I'll have time to go fix this anytime soon.

**Comment by billhollings** [comment]
> I don't think I'll have time to go fix this anytime soon.

Okay. I'll have a look later this week. If things change for you, check in with me first.

**Comment by aerofly** [comment]
As I do not have the insight into the MoltenVK code with respect to this issue, I probably can't contribute to the source code, but I would happily test any fixes you apply as our app is crashing if events are active.

**Comment by billhollings** [comment]
@Luke-Filewalker Can you try running your game with the latest MoltenVK code...with one of the `MVK_ALLOW_METAL_FENCES` (preferred) or `MVK_ALLOW_METAL_EVENTS` environment variables enabled in your game...to see if that improves your performance without breaking anything?

**Comment by Luke-Filewalker** [comment]
MVK_ALLOW_METAL_FENCES does nothing, and MVK_ALLOW_METAL_EVENTS increases FPS but with a lot of visual artifacts, it basically the same as if I would remove the semaphores dependency between VkSubmitInfo and VkPresentInfoKHR.

**Comment by billhollings** [comment]
@Luke-Filewalker 

> `MVK_ALLOW_METAL_FENCES` does nothing

Can you clarify what you mean by "does nothing"?  What are the results?

Are you using the latest MoltenVK from [this repo](https://github.com/KhronosGroup/MoltenVK)? The code fixes I'm trying to exercise are not in the Vulkan SDK yet. 

You can verify that `MVK_ALLOW_METAL_FENCES` is active by looking for the following log entry:

`[mvk-info] Using MTLFence for semaphores.`

Alternate options will say:
`[mvk-info] Using MTLEvent for semaphores.`
`[mvk-info] Using emulation for semaphores.`

If you are using the SDK...to use the latest MoltenVK, clone this repo, follow the instructions in the [`README.md`](https://github.com/KhronosGroup/MoltenVK/blob/master/README.md) to build MoltenVK...then drop the `libMoltenVK.dylib` into the correct place in the macOS Vulkan SDK.

**Comment by Luke-Filewalker** [comment]
With does nothing I meant no change in fps or visual quality (artifacts).

I used the library from the sdk sorry. With the latest version from github, both environment variables increase fps dramatically, (more than 50%) MVK_ALLOW_METAL_EVENTS seems to have more visual artifacts then MVK_ALLOW_METAL_FENCES, not sure if this is just coincidence. When I limit the fps to 60 I have mostly no artifact (few flashes that look like image below), with unlimited fps they are a lot more.

With artifacts I mean:
![Screenshot 2019-09-02 at 16 36 15](https://user-images.githubusercontent.com/15105596/64121872-45bd3500-cda0-11e9-80e5-2e5c682987c4.png)

**Comment by billhollings** [comment]
>The artifacts problem...was on my end, now it works fine with `MVK_ALLOW_METAL_FENCES` active.

That is good news! Thanks for letting us know.

Does anyone have any issues with `MVK_ALLOW_METAL_FENCES` now? 

Currently...`MVK_ALLOW_METAL_FENCES` is disabled by default. But in the interests of promoting better performance...it would be nice to be able to enable `MVK_ALLOW_METAL_FENCES` by default (taking into consideration `MTLFence` availability of course)...to gain proper GPU-GPU sync without involving the CPU...as the default behaviour.

**Comment by billhollings** [comment]
>Currently...MVK_ALLOW_METAL_FENCES is disabled by default. But in the interests of promoting better performance...it would be nice to be able to enable MVK_ALLOW_METAL_FENCES by default (taking into consideration MTLFence availability of course)...to gain proper GPU-GPU sync without involving the CPU...as the default behaviour.

PR #760 now enables `MVK_ALLOW_METAL_FENCES` by default.
