### ISSUE TITLE
Is there any plan for Tessellation support in MoltenVK?

### ISSUE THREAD

**Issue by spencerkohan** [KhronosGroup/MoltenVK#501]
It is understandable that geometry shaders are not supported in MoltenVK as this feature is not implemented in Metal2, but Tessellation is available.  Is this on the roadmap for future versions?

**Comment by cdavis5e** [comment]
I'm working on it right now. A change to support tessellation evaluation shaders was just accepted into [SPIRV-Cross](/KhronosGroup/SPIRV-Cross). Hopefully, I'll be able to get this in by next week's SDK release.

**Comment by billhollings** [comment]
Duplicate of #56.
