### ISSUE TITLE
Vulkan SDK release coordination starting Feb 25

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#503]
LunarG is planning the next Vulkan SDK release for the week of Feb 25. 

Final release date has not been set yet...and will depend on planning and testing. Updates will be posted here.

MoltenVK PRs submitted by Feb 25 will be included. Please notify here if you want to get a PR into this SDK release after that date.

@cdavis5e @HansKristian-Work @jeremyk-lunarg

**Comment by HansKristian-Work** [comment]
@billhollings, I've merged some fixes under https://github.com/KhronosGroup/SPIRV-Cross/releases/tag/2019-02-20. I'll ping again if more issues come up before the end of week.

One of the commits fixes a critical and subtle bug exposed by RenderDoc, so it might be good to include in the change log.

**Comment by cdavis5e** [comment]
I have a forthcoming change to implement tessellation (finally!). I want to see this get in for the next SDK release. Right now, I'm busy testing it and ironing out the bugs.

**Comment by billhollings** [comment]
@HansKristian-Work I always pull in the latest SPIRV-Cross version and update the MoltenVK _What's New_ document accordingly before doing an SDK release. But it never hurts to have anyone else issue a PR here when SPIRV-Cross changes. If you do...don't bother updating _What's New_...it's a simple thing for me to iterate through the Git log to create that at release time.

@cdavis5e Very happy to see this coming, and looking forward to including it in the SDK release!
