### ISSUE TITLE
Shader compile error on iOS :  'data' declared as a pointer to 'metal::texture2d_array<float, metal::access::write, void>'

### ISSUE THREAD

**Issue by dom607** [KhronosGroup/MoltenVK#517]
I got error when compile following shader. It's ok on MacOS. To be precise, error occurred when compiling this line. ```imageStore(OutMip[3], ivec3(GlobalInd.xy / 8u, ArraySlice), PackColor(Src1));```

Shader code : https://github.com/DiligentGraphics/DiligentCore/blob/master/Graphics/GraphicsEngineVulkan/shaders/GenerateMipsCS.csh

Test environments
Xcode : 10.1
SDK : 12.1
Device : iPhone 6 & iPhone 8
      
Error codes
```

[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (error code 3):

Compilation failed: 



In file included from program_source:1:

In file included from /System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_stdlib:4:

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:49:23: error: 'data' declared as a pointer to 'metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC thread T *data() thread { return __elems; }

                      ^

program_source:43:100: note: in instantiation of template class 'metal::array<metal::texture2d_array<float, metal::access::write, void>, 4>' requested here

kernel void main0(constant CB& _120 [[buffer(0)]], array<texture2d_array<float, access::write>, 4> OutMip [[texture(0)]], texture2d_array<float> SrcMip [[texture(4)]], sampler SrcMipSmplr [[sampler(0)]], uint gl_LocalInvocationIndex [[thread_index_in_threadgroup]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])

                                                                                                   ^

In file included from program_source:1:

In file included from /System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_stdlib:4:

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:50:39: error: 'data' declared as a pointer to 'const metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC constexpr const thread T *data() const thread { return __elems; }

                                      ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:83:23: error: 'data' declared as a pointer to 'device metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC device T *data() device { return __elems; }

                      ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:84:39: error: 'data' declared as a pointer to 'const device metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC constexpr const device T *data() const device { return __elems; }

                                      ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:105:41: error: 'data' declared as a pointer to 'const constant metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC constexpr const constant T *data() const constant { return __elems; }

                                        ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:138:28: error: 'data' declared as a pointer to 'threadgroup metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC threadgroup T *data() threadgroup { return __elems; }

                           ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:139:44: error: 'data' declared as a pointer to 'const threadgroup metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC constexpr const threadgroup T *data() const threadgroup { return __elems; }

                                           ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:173:39: error: 'data' declared as a pointer to 'threadgroup_imageblock metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC threadgroup_imageblock T *data() threadgroup_imageblock { return __elems; }

                                      ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:174:55: error: 'data' declared as a pointer to 'const threadgroup_imageblock metal::texture2d_array<float, metal::access::write, void>'

  METAL_FUNC constexpr const threadgroup_imageblock T *data() const threadgroup_imageblock { return __elems; }

                                                      ^

/System/Library/PrivateFrameworks/GPUCompiler.framework/./Libraries/lib/clang/902.1/include/metal/metal_array:178:12: error: '__elems' declared as array of 'metal::texture2d_array<float, metal::access::write, void>'

  T __elems[N ? N : 1];

           ^

.

[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Compute shader function could not be compiled into pipeline. See previous logged error.

```

**Comment by billhollings** [comment]
Looks like there are a few issues.

Your `.csh` shader is not valid GLSL and couldn't be compiled with `glslang`. It doesn't include a `#version` statement, and is missing `layout(binding = N)` declarations.

I assume you fixed that before actually using this shader. I was able to work around that by assuming version 450 and declaring a couple of default layouts.

The main issue seems to be the use of a writable array of textures:

1. Arrays of textures requires iOS 10 and GPU3 (A9)...which means it won't run at all on your iPhone 6.
2. It doesn't look like arrays of textures can be writable. From the MSL specification:

    > An array of textures is declared as either:
array<typename T, size_t N>
const array<typename T, size_t N>
typename shall be a texture type (see section 2.8) declared with the access::read or
access::sample attribute.

Changing the `access::write` qualifier  to `access::read` (and removing the calls to `OutMip[n].write(...)`) allows the compilation to succeed.

If this is actually working on macOS, I'd consider it to be undocumented and unreliable behaviour.

**Comment by DiligentGraphics** [comment]
@billhollings `#version` and `layout(binding=N)` are assigned programmatically when the shader is processed by the engine and then compiled by glslang. Other than that, does that mean that this otherwise valid GLSL shader cannot be translated to a valid MSL? The shader seems to work (at least compile) fine on Mac

**Comment by billhollings** [comment]
Ah. Good. Thanks for the background about shader management in your engine.

Yes. It looks like that's what it means for now. The MSL is (or rather _would be_) correct...but from what I see...support for arrays of textures seems to be read-only in Metal.

To the extent that it works on macOS...or maybe just on some GPU's...is probably a driver artifact. Caveat emptor if you choose to make use of it.

**Comment by billhollings** [comment]
It's possible that this could be remedied in SPIRV-Cross by forcing an array of writable textures to be treated as individual textures (eg. `OutMip_1`...`OutMip_3`)...and assigning consecutive Metal texture indices to the declarations.

You could try posting a request (and your sample shader) to the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues), linking to this issue.

**Comment by DiligentGraphics** [comment]
Will this be transparent from Vulkan API perspective?

**Comment by billhollings** [comment]
Can you clarify what you are asking with that question?

**Comment by DiligentGraphics** [comment]
I mean, if from MSL binary treats texture array object as an array of textures instead, does it mean that on Vulkan side the resource will need to be bound accordingly, not as a texture array but as array of textures.

**Comment by cdavis5e** [comment]
There should be no difference from an API point of view, since array bindings need multiple Metal bindings anyway.

**Comment by DiligentGraphics** [comment]
Ok, thank you!

**Comment by billhollings** [comment]
@DiligentGraphics 

To be pedantically clear on the semantics between a texture array (one texture object with multiple layers/slices) and an array of textures (literally an array of multiple texture objects)...we have not been discussing texture arrays here.

You are using an array of textures. The proposal would be for MSL to break a writable array of textures into the component texture objects, and pass each texture object as a separate argument to the MSL entry point function.

Nevertheless...as @cdavis5e already mentioned...this magic would all happen under the covers...and your use of an array of textures under the Vulkan API would remain unchanged.

If that suits your needs...please post a similar enhancement request to the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues).
