### ISSUE TITLE
Use Metal argument buffers for descriptor sets

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#523]
Now that [SPIRV-Cross supports](https://github.com/KhronosGroup/SPIRV-Cross/pull/890) Metal argument buffers, we should add support for them here.

**Comment by billhollings** [comment]
@cdavis5e 

Are you keen to take this one on? Or shall I have a stab at it?

The outstanding Dota2 crash is causing a delay in bringing the latest SPIRV-Cross versions to MoltenVK. 

To give us options...I have created a [new branch](https://github.com/KhronosGroup/MoltenVK/tree/spvx-latest) in this repo to allow us to bring in the latest SPIRV-Cross versions in order to continue moving development forward.

At present, the `spvx-latest` branch contains support for the SPIRV-Cross API changes that arose from the introduction of the C API there. I've included basic support in that change for your tessellation enums.

If you want to work on this enhancment...please do so on the `spvx-latest` branch. You could also submit PR #508 there too.

Once the Dota2 issue is resolved...we can merge `spvx-latest` with `master`.

We can keep any development that do not require SPIRV-Cross updates in `master`.

**Comment by billhollings** [comment]
@cdavis5e 

I just read [Dan's comment](https://github.com/KhronosGroup/MoltenVK/pull/508#issuecomment-473392242).

Good news.

I'll go ahead and merge PR #508 and the `spvx-latest` branch into master...and we can move forward.

Let me know if you want to take this enhancement on. If not...I'm happy to do so.

**Comment by cdavis5e** [comment]
I'll do it.

**Comment by billhollings** [comment]
Thanks, @cdavis5e.

**Comment by billhollings** [comment]
**Design requirement:** Needs to support detecting and hoisting bindings that can't be part of an argument buffer (eg- writable textures on iOS) into discrete bindings.

**Comment by BearishSun** [comment]
Hi. Just want to confirm, if I use MSL that uses argument buffers, it will not work with MoltenVK? If that's the case, any ETA on this feature?

**Comment by billhollings** [comment]
@BearishSun  In what way are you using argument buffers in MSL? Are you supplying your own MSL to MoltenVK directly? Or are you submitting standard SPIR-V per normal Vulkan behaviour that MoltenVK is converting to MSL?

**Comment by BearishSun** [comment]
I'm supplying my own MSL. Technically I'm using `SPIR-V Cross` that generates the MSL from SPIR-V, with argument buffer support enabled (as I had issues with resource binding slots getting used up when not using argument buffers). It's not critical as I think I can re-work my code to work with the argument buffer approach, but it would be nicer to support them out of the box.

**Comment by starbucksDave** [comment]
Hey everyone,

Is this feature still in development?
I potentially will have a lot more textures (with different resolutions) to deal with than the 128 limit provided by Metal. So I was hoping that the argument buffers would be a way to go bindless and get around the limit.

Thanks,

**Comment by starbucksDave** [comment]
Hey everyone,

Any news on this feature? 

Cheers,

**Comment by starbucksDave** [comment]
We personally dont use VK_DESCRIPTOR_TYPE_{STORAGE,UNIFORM}_BUFFER_DYNAMIC, so for our use case its less important. However it probably makes little sense to support this feature only for the non-dynamic descriptor types when there is a potential solution that supports them all. Is there an issue raised on the SPIRV-Cross repo?

Cheers,

**Comment by starbucksDave** [comment]
I just noticed the commit to SPIRV-Cross https://github.com/KhronosGroup/SPIRV-Cross/commit/cb35934248920c2ee28e8162205ad390a6d042c9

**Comment by starbucksDave** [comment]
Hey everyone,

Just a quick checkup, since I am curious to the features development, is there a branch I can follow?

Cheers,

**Comment by starbucksDave** [comment]
@cdavis5e Any news on this feature, if there is a working branch somewhere I would love to take a look! :)

Sorry for the prompts, but very curious!

Cheers!

**Comment by billhollings** [comment]
@cdavis5e 

Where is this sitting now?

I made some simple changes to descriptor sets to reduce memory use within MoltenVK. I'd like to refactor the `MVKDescriptorXXX` class hierarchies to further reduce memory that is currently consumed by descriptor bindings being generic to all types.

Those changes will be quite intrusive...and I didn't want to undertake them if they would create significant conflicts with what you are doing here.

I wonder if there is a refactoring that can both realign the existing design AND support Metal argument buffers?

**Comment by cdavis5e** [comment]
> Where is this sitting now?

I've done a bit of refactoring of my own. [This](https://github.com/KhronosGroup/MoltenVK/files/3730505/mvk-argument-buffers.diff.txt) is what I have so far. It's still mostly incomplete.

Sadly, I haven't been able to work on this much lately. I keep getting pulled off to go work on various Catalina-related bugs in our products. (Frakkin' Apple... can't leave well enough alone...)

**Comment by starbucksDave** [comment]
@cdavis5e did you find some time to work a bit more on this?

**Comment by kattkieru** [comment]
Wanted to bump this— has this feature seen any further development? Thanks!

**Comment by plasmacel** [comment]
Is there any news on this?

**Comment by billhollings** [comment]
Initial implementation in macOS via PR #1335.
