### ISSUE TITLE
Writing to SSBO causes rendering to fail

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/MoltenVK#527]
We have a [test case](https://github.com/google/amber/blob/master/tests/cases/multiple_ssbo_update_with_graphics_pipeline.vkscript) in [Amber](https://github.com/google/amber) which currently fails on MoltenVK. The below amber test fails on MoltenVk with `data_set1_binding0_result = .5;` enabled (I haven't tested the reduction on Linux as I don't have access for the next week). Commenting out that line and the framebuffer has the correct colour. With that line enabled the framebuffer just contains the clear colour, not the colour from the fragment shader.

Issue https://github.com/google/amber/issues/216.

```
[require]
vertexPipelineStoresAndAtomics

[vertex shader]
#version 430

layout(location = 0) in vec4 position;

layout(set = 1, binding = 0) buffer block1 {
  float data_set1_binding0_result;
};

void main() {
  gl_Position = position;
  // comment out next line and test passes
  data_set1_binding0_result = .5;
}

[fragment shader]
#version 430

layout(location = 0) out vec4 final_color;

void main() {
  final_color = vec4(0.5, 0.25, 0.124, 0);
}

[vertex data]
#      position
0/R32G32_SFLOAT

#      R32  G32
      -1.0 -1.0
       1.0  1.0
      -1.0  1.0

      -1.0 -1.0
       1.0  1.0
       1.0 -1.0

[test]
clear color .5 .5 .5 .5
clear

ssbo 1:0 subdata float 0 0

draw arrays TRIANGLE_LIST 0 6
relative probe rect rgba (0.0, 0.0, 1.0, 1.0) (.5 .25 .124 0)
```

**Comment by cdavis5e** [comment]
This is a known limitation of Metal (rdar://48348476). For whatever reason, Metal vertex shaders cannot simultaneously write to a buffer and return a value to the rasterizer.

**Comment by billhollings** [comment]
I've registered this as something the Vulkan portability initiative might address to identify for a particular implementation...and I'm closing this as a MoltenVK issue.
