### ISSUE TITLE
Command queue grows indefinitely on MacBook with Iris 6100

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#530]
Hello!
I am seeing strange issue on MacBook with Iris 6100: when CPU submits more work than the GPU can handle, the command queue grows and the GPU falls indefinitely behind the CPU.

Our Vulkan backend implements D3D12-style fences: there is a pool of VK fences with increasing numbers associated with every fence. As long as a fence signals, its associated value is the last signaled fence value. The engine manages resources using these values: as soon as last signaled value exceeds the value associated with the last resource usage, the resource is reused. 

Signaled fences in the pool are reused, but if there is no available, a new one is created. Now the problem is that this pool grows indefinitely and the gap between the last signaled fence value and the current fence value increases until all resources are exhausted and the engine forcibly blocks the CPU to wait for some to release. Sometimes it even idles the GPU which reset the gap to 0, so synchronization appears to work properly.

The application also becomes very laggy: it takes couple of seconds before it reacts to user input.

It appears like if `vkAcquireNextImageKHR` was not blocking if there is no available image. I tried FIFO and Mailbox present modes to the same effect. 

Do you know what could be happening here?

**Comment by danginsburg** [comment]
> It appears like if vkAcquireNextImageKHR was not blocking if there is no available image. I tried FIFO and Mailbox present modes to the same effect.

I'm not sure you can rely on vkAcquireNextImageKHR to block.  From the spec:

>Applications should not rely on vkAcquireNextImageKHR blocking in order to meter their rendering speed. The implementation may return from this function immediately regardless of how many presentation requests are queued, and regardless of when queued presentation requests will complete relative to the call. Instead, applications can use fence to meter their frame generation work to match the presentation rate.

It sounds to me like you need to somewhere wait on a fence.  In our engine, we don't let the CPU get more than one frame ahead of the GPU.  If it does, we will block on a fence before allowing the main thread to proceed.  We do not rely on vkAcquireNextImageKHR to block.

**Comment by DiligentGraphics** [comment]
Ah, OK. That makes perfect sense then. Thanks!
