### ISSUE TITLE
MSL conversion error: Could not convert row-major matrix

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#535]
I am seeing the following error when compiling one of my shaders:

```
[***MoltenVK ERROR***] VK_ERROR_FORMAT_NOT_SUPPORTED: Unable to convert SPIR-V to MSL:
MSL conversion error: Could not convert row-major matrix.

[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Vertex shader function could not be compiled into pipeline. See previous logged error.
```

The problem is that I can't really connect this error to anything specific in the shader. All matrix declarations are the same as in the shaders that work fine. There is no `row_major` specifications or anything like that. Can you give a clue as to what can be wrong?

I am using pre-built MoltenVK library from 1.1.101.0 SDK.

**Comment by HansKristian-Work** [comment]
If you compile from HLSL, you will end up with row-major matrices everywhere (multiplication orders have to be flipped and matrix col->row major flips). Please file a SPIRV-Cross bug with the failing SPIR-V.

**Comment by DiligentGraphics** [comment]
The problem is no longer reproducible in 1.1.106.0
