### ISSUE TITLE
vkCmdCopyBufferToImage with the BC3_SRGB_BLOCK format when imageExtent + imageOffset equals the subresource dimensions, but is less than the compressed texel block dimensions, causes Metal assertion failure

### ISSUE THREAD

**Issue by hideyhole** [KhronosGroup/MoltenVK#54]
According to section 18.4 of the Vulkan spec, one of the valid uses of the VkBufferImageCopy struct is that (imageExtent[.width/height/depth] + imageOffset[.x/y/z]) must equal the image subresource width/height/depth respectively, when the VkImage of vkCmdCopyBufferToImage has a compressed format.

This causes a validation failure in the copyFromBuffer method of the MTLBlitCommandEncoder when (imageExtent + imageOffset) is less than the block size, but equal to the subresource dimensions, because the mvkMTLPixelFormatBytesPerRow function performs an integer division with the block size, and thus calculates sourceBytesPerRow erroneously as 0. The same is true for the mvkMTLPixelFormatBytesPerLayer function, which wrongly calculates the sourceBytesPerImage (as 0).

The format of the image used in the offending call was VK_FORMAT_BC3_SRGB_BLOCK, but I'd expect any BC3 format to behave this way.

**Comment by hideyhole** [comment]
> Are you attempting to copy less than a single compressed block, and MoltenVK is incorrectly rounding down to zero extent?

Yes. Certain texture exporters that export to the DDS format export DDS files with a mip chain that fully extends all the way down to 1x1. When we try to load these textures in by first uploading to a linear staging buffer and then vkCmdCopyBufferToImage-ing to an optimal-tiled image, MoltenVK crashes in the BlitCommandEncoder's copyFromBuffer call because the sourceBytesPerRow parameter, as calculated by the call to mvkMTLPixelFormatBytesPerRow, is 0, because MoltenVK incorrectly rounds down the number of blocks to be copied to 0 (because of the integer division). This is a violation of the spec, as far as I can tell.

[Given Microsoft's documentation on this](https://msdn.microsoft.com/en-us/library/windows/desktop/bb694531(v=vs.85).aspx), I think it *might* be safe to assume that the texture tools that do this already adds the padding bytes (the DDS should be invalid, otherwise), and hence, the source buffer should also have them. In that case, the fix would be straightforward - simply clamp the number of blocks to be copied to 1. 

However, as far as the Vulkan spec is concerned, there's no such requirement (AFAIK). Which means that the assumption that the source buffer should already have padding is *not* safe, and simply clamping the number of blocks to 1 could result in a wrong texture and/or a segfault.

Therefore, in this situation, the safe way to handle this would be to copy the individual texels to an internal MTLBuffer, add the padding bytes, and then use this internal buffer and the clamped number of blocks in the BlitCommandEncoder's copyFromBuffer call.

**Comment by billhollings** [comment]
@hideyhole 

The end of [Section 18.4](https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#copies-buffers-images) includes a discussion about how to interpret `VkBufferImageCopy` when copying compressed formats.

It provides pseudo code that includes an integer division (rounding down) of the `imageExtent` components.

It also describes:

- "the addressing math operates on whole compressed texel blocks"
- "Copying to or from block-compressed images is typically done in multiples of the compressed texel block size.".
- "the imageExtent must be a multiple of the compressed texel block dimension"

It does provide one exception to the last requirement...when `imageOffset` + `imageExtent` is equal to the image sub resource size.

AFAICT...MoltenVK is following this design. However...in copying small mip layers...we may be encountering that exception rule...and MoltenVK may not be handling that properly. Perhaps a rounding up on the division, with a clamp to subresource size would be more accurate.

Can you have a look at that section of the spec and give my your thoughts on design implementation, please?

**Comment by hideyhole** [comment]
Thinking further through this, I believe that it can be safely assumed that the source buffer holds enough bytes for the dimensions rounded up to a full block, since the source data has to be the raw bytes of a BC compressed image, which contain entire blocks and not texels. In the event that one of the mipmap levels has sub-block dimensions, the image file should still contain the bytes for the whole block, with the padding texels/bytes added as described above, and therefore, so should the source buffer.

In that case, simply clamping the number of blocks to 1 should fix this particular issue.

In your comments, you identified a further issue with the copy operation, which is that texels near the edge of the image subresource could be left uninitialized/populated with garbage if the subresource dimensions are not exactly divisible by the block dimensions. Rounding the division up should fix that issue. In fact, it should fix both issues.

**Comment by billhollings** [comment]
Fixed in PR #122.
