### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by TheSpydog** [KhronosGroup/MoltenVK#541]
Are there any plans for supporting MoltenVK on tvOS? I couldn’t find any information about it in the docs or in the repo. Seems like it’d be great to enable Vulkan apps to run Apple TV, especially with the upcoming Apple Arcade service.

**Comment by billhollings** [comment]
Thanks for the upvote. Happy to hear from others on the priority of this.

**Comment by jamesd9** [comment]
I would also like to upvote this.

**Comment by Xioor** [comment]
Any eta for when this could be implemented?

**Comment by tmm1** [comment]
Also interested in this. Has anyone tried compiling this project for tvOS? It should be straightforward if iOS and macOS are supported already.

**Comment by billhollings** [comment]
> It should be straightforward if iOS and macOS are supported already.

Yeah...it should be fairly straightforward.

At a minimum, it will require defining `MVK_TVOS` and `MVK_IOS_OR_TVOS` conditional macros, and working through the use of `MVK_IOS`...flipping most of those to `MVK_IOS_OR_TVOS` and adding a small number of dedicated instances of `MVK_TVOS`.

And then testing.

Not a big deal. Just mostly a labour and priority issue.

**Comment by tmm1** [comment]
@billhollings Thanks! I will start a PR with all the basic changes to the Makefile and xcode projects.

**Comment by tmm1** [comment]
I started a PR in #912, but ran into some Xcode issues. If anyone else here wants to help, please take a look!

**Comment by tmm1** [comment]
Xcode build issues have been resolved, so now the frameworks can be built for tvOS. The actual implementation of the tvOS GPU Family capabilities is still missing, if anyone is interested in helping: #921

**Comment by TheSpydog** [comment]
This appears to have been completed and merged last week, so I’ll go ahead and close the issue. Very well done @tmm1!
