### ISSUE TITLE
abs(-1) returns -1

### ISSUE THREAD

**Issue by Ardy123** [KhronosGroup/MoltenVK#549]
This is from clspv... The following opcode results in -1 with latest commit.
`%22 = OpExtInst %uint %1 SAbs %uint_4294967295`

A bug regarding this issue was fixed yesterday in spirv-cross 
https://github.com/KhronosGroup/SPIRV-Cross/issues/908
but upon updating and recompiling, abs(-1) still was returning -1.

**Comment by billhollings** [comment]
The new SPIRV-Cross was probably not compiled into MoltenVK.

How did you grab the SPIRV-Cross fix? And how did you rebuild MoltenVK?

To get and build the right SPIRV-Cross:

1. Update the contents of `ExternalRevisions/SPIRV-Cross_repo_revision` to the SPIRV-Cross Git commit hash that you want.
2. Run `./fetchDependencies`.

= or =

1. Manually fetch or clone the latest SPIRV-Cross repository into `External/SPIRV-Cross`.
2. Open `ExternalDependencies.xcodeproj` and run the `ExternalDependencies` scheme.

Either of these will build an updated `External/build/macOS/libSPIRVCross.a` & `External/build/iOS/libSPIRVCross.a`...and will clean the MoltenVK build.

After that...build MoltenVK again using `MoltenVKPackaging.xcodeproj`...or `make`.

**Comment by Ardy123** [comment]
I followed the first set of steps, used the commit 18d4f67a8760e7cd69508d0a03ff19aad216d0b5 and rebuilt it. It still didn't work correctly and returned -1 instead of 1.

**Comment by billhollings** [comment]
Strange. Can you post a file containing the SPIRV shader code...so that we can check it out?

**Comment by HansKristian-Work** [comment]
I tried this in SPIRV-Cross upstream, and codegen is:
```
uint(abs(int(4294967295u)));
```
Which looks correct to me, assuming the MSL compiler does not have any weird rules regarding strict overflow, does it?

One possibility is perhaps if you're using an older MoltenVK checkout. To use newer dependencies you have to clean the MoltenVK build explicitly before building again.

**Comment by HansKristian-Work** [comment]
Oh dear ... From spec:
```
The result of signed integer overflow is undefined.
```

**Comment by HansKristian-Work** [comment]
I tried running this on my macbook, and I do get 1 as a result. If the generated code is indeed like we expect and -1 is still returned, hopefully there is -fwrapv to save the day.

**Comment by Ardy123** [comment]
here is the code being sent to it...
%57 =   OpConstant %6 4294967295
OpExtInst %6 %1 SAbs %57

**Comment by HansKristian-Work** [comment]
-fwrapv is a common C compiler option to make signed overflow well defined. Not sure if the Metal compiler supports it though, but ... it's LLVM based so who knows.

This behavior might even be GPU specific since we're in undefined territory. If you build MoltenVK in debug mode it should dump out all the MSL it's generating. That's useful to verify the codegen is as expected.

**Comment by Ardy123** [comment]
This has been fixed in the latest code from the head branch.
