### ISSUE TITLE
Sampler depth comparison before MTLFeatureSet_iOS_GPUFamily3_v1 

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#556]
I'm getting this assertion in vkCreateSampler on iPad Air Gen 1 (A7):

validateMTLSamplerDescriptor:110: failed assertion `MTLSamplerDescriptor: setting a compareFunction is only supported on MTLFeatureSet_iOS_GPUFamily3_v1 and later'

It looks like on this family of GPU the sampler comparison function needs to be in the MSL.  It looks to be related also to this spirv-cross issue: https://github.com/KhronosGroup/SPIRV-Cross/issues/533

I'm not sure whether this is worth working around, but one question I have is whether there is anything in the MoltenVK API that lets me check whether sampler comparisons are supported?  I didn't see anything.  At a minimum I need to avoid this path in my code on this generation of hardware.

It seems it might be possible to patch Metal code to read the sampler comparison from the descriptor, but that seems probably not worth the effort here.  I'm happy to just avoid shadow comparison on this generation of hardware.

**Comment by billhollings** [comment]
>At a minimum I need to avoid this path in my code on this generation of hardware.

MoltenVK doesn't detect this...but it should. I'll add a feature boolean in the API for this so you can at least test for the feature availability.

>I'm not sure whether this is worth working around

Feature set `MTLFeatureSet_iOS_GPUFamily3_v1` is available on iOS 9 on an A9 processor. This is intended to be the minimum Metal platform for the Vulkan portability initiative...and as such would probably be unnecessary effort to work around under the covers. 

But let us know if you think requirements should cover older platforms more effectively.

**Comment by danginsburg** [comment]
> But let us know if you think requirements should cover older platforms more effectively.

I think just exposing the boolean for now is fine.  It doesn't seem like it would be straightforward to work around so I'd wait for a use case that was compelling enough.

**Comment by billhollings** [comment]
Fixed in PR #560. Please retest and close this issue if fixed.

I've added `MVKPhysicalDeviceMetalFeatures::depthSampleCompare` so you can determine whether sample compares are supported. You can retrieve it with `vkGetPhysicalDeviceMetalFeaturesMVK()`.

**Comment by danginsburg** [comment]
Thanks, I've hooked up to the new interface and confirmed this fixes the issue.  Closing.

**Comment by danginsburg** [comment]
So it turns out I was optimistic in thinking we didn't need this feature.  Perhaps having per-sampler mode is too onerous on MoltenVK, but would it be possible to be able to configure either a global a per-pipeline sampler comparison mode and use the SPIRV-Cross feature to generate code with the comparison sampler built in?  If not, we can't do shadows on A7/A8/A8X GPU and that is something we want to be able to do.

**Comment by billhollings** [comment]
@danginsburg 

Do you mean pass sampler parameters into SPRIVCross so that it could generate a fixed sampler in the MSL code?

How would you envision the app would pass the parameters to MoltenVK? Are you thinking we would identify a standard `VkSampler` and attach it to the pipeline somehow?

To allow it to be a bit more dynamic...perhaps we could make use of shader specialization to pass the sampler info...which was introduced in iOS 10 on all devices.

**Comment by danginsburg** [comment]
Well, for our particular use case we only ever need a single depth comparison state for the entirety of our application.  So I'm flexible on how this could work.  Spit balling it could be:

* Some global MVK configuration state where any time a depth comparison sampler is used in a shader it uses that global state in place of it on A7/A8/A8X GPUs
* Something hanging off the VkGraphicsPipelineCreateInfo.pNext* that provides a per-pipeline config.  A VkSampler would make sense, or something like VkSamplerCreateInfo.  I'd basically pass this to all pipelines since I don't know ahead of time if one uses a depth comparison sampler.  I'd expect MoltenVK to pass the state to SPIR-V cross for any comparison samplers in the pipeline.  This is probably cleaner and more flexible than global.

If an application wanted to actually provide the setting for multiple samplers I'm not sure how that would work, @Themaister might have suggestions.

**Comment by billhollings** [comment]
@danginsburg Your `VkGraphicsPipelineCreateInfo.pNext` idea might solve this in a Vulkan-friendly way. I'll look into it.

**Comment by HansKristian-Work** [comment]
It might be feasible to add an option to SPIRV-Cross' MSL backend which replaces all comparison samplers (sample_compare) with a given constexpr sampler rather than overriding individual samplers, since it's not known which samplers are actually comparison samplers in SPIR-V until you analyze the execution.

**Comment by billhollings** [comment]
@HansKristian-Work  Just to be clear I understand your suggestion...

>replaces all comparison samplers (sample_compare) with a given constexpr sampler rather than overriding individual samplers

Would this assume a single universal constexpr sampler? Would we know the structure of this sampler just from the SPIR-V code? And what if the app wanted to use more than one type of depth comparison sampler (different compare op, filters, or address modes, etc)?

Since the SPIRV-Cross API already has a mechanism to replace bound samplers with constexpr samplers (which you've made even easier with PR https://github.com/KhronosGroup/SPIRV-Cross/pull/1020) ...and the app (MoltenVK, etc) knows the config info of each sampler...I'm thinking it would be more generally useful, and not too difficult, to let the app specify the individual constexpr samplers as needed.

**Comment by HansKristian-Work** [comment]
Right, how this is solved is completely up to MoltenVK/app. SPIRV-Cross can deal with different constexpr samplers per sampler, so if the app provides which samplers to override, that's certainly easier.

**Comment by jamesd9** [comment]
I would like to upvote this as we've just run into this problem too. A8 support is still required even for applications that target iOS 13, so this limitation is significant issue for us. Even the most basic solution of a global constexpr sampler should fix it though.

**Comment by billhollings** [comment]
I have a WIP of this finished. However...I am having difficulty finding apps or samples, that actually use depth compare sampling, to test it against!

If anyone can point me to an app or sample that makes use of depth compare...I would appreciate it!

I don't need something that runs on iOS...where this is applicable. I can fake the depth compare feature not being available.

**Comment by danginsburg** [comment]
> If anyone can point me to an app or sample that makes use of depth compare...I would appreciate it!

Dota does, although obviously it just provides the samplers as normal (non immutable) in a descriptor set so I'm not sure how you'd be able to use that to test it.

**Comment by HansKristian-Work** [comment]
@billhollings I'll hook you up with something tomorrow.

**Comment by billhollings** [comment]
@danginsburg @jamesd9 Fixed in PR #644. Please retest and confirm we can close this issue.

**Comment by billhollings** [comment]
If anyone is interested in testing this on other devices, you can do so by changing the following line in the `MVKSampler` constructor:

	_requiresConstExprSampler = pCreateInfo->compareEnable && !_device->_pMetalFeatures->depthSampleCompare;

to:

	_requiresConstExprSampler = pCreateInfo->compareEnable && true;

Then if you enable shader conversion logging, you'll see something similar to the following line appear in any shader using depth compare:

	constexpr sampler _4506(filter::linear, mip_filter::linear, s_address::clamp_to_border, t_address::clamp_to_border, r_address::repeat, compare_func::less_equal, border_color::opaque_white);

**Comment by danginsburg** [comment]
I tested PR #644 on iOS 12 iPad Air 2 (Apple A8X GPU) and unfortunately there is a problem.  I am getting the following errors on shaders:

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:120:166: error: use of undeclared identifier 'border_color'
    constexpr sampler _4506(filter::linear, mip_filter::linear, s_address::clamp_to_border, t_address::clamp_to_border, r_address::repeat, compare_func::less_equal, border_color::opaque_white);
                                                                                                                                                                     ^
program_source:120:76: error: no member named 'clamp_to_border' in 'metal::s_address'
    constexpr sampler _4506(filter::linear, mip_filter::linear, s_address::clamp_to_border, t_address::clamp_to_border, r_address::repeat, compare_func::less_equal, border_color::opaque_white);
                                                                ~~~~~~~~~~~^
program_source:120:104: error: no member named 'clamp_to_border' in 'metal::t_address'
    constexpr sampler _4506(filter::linear, mip_filter::linear, s_address::clamp_to_border, t_address::clamp_to_border, r_address::repeat, compare_func::less_equal, border_color::opaque_white);
                                                                                            ~~~~~~~~~~~^
.
```

According to the MSL specification:

```
macOS: Supports clamp_to_border address mode and border_color since Metal 1.2.
iOS: No support for clamp_to_border address mode or border_color.
```

It looks like we need SPIRV-cross to generate the shader without clamp_to_border or border_color.  Is there a way I can force that from my side @HansKristian-Work?

**Comment by danginsburg** [comment]
UPDATE: works if I force my immutable sampler to CLAMP_TO_EDGE.

**Comment by billhollings** [comment]
Whoops! Okay. We can fix this in MoltenVK.

>It looks like we need SPIRV-cross to generate the shader without clamp_to_border or border_color. Is there a way I can force that from my side @HansKristian-Work?

Hmmm...this would silently and unexpectedly change behaviour from the app's perspective. Border colour is not available to Metal samplers on iOS...with or without constexpr samplers. Wouldn't it be better to return an error from `vkCreateSampler()`?

With that in place...

> UPDATE: works if I force my immutable sampler to CLAMP_TO_EDGE.

would be the correct app behaviour.

SPIRV-Cross is already smart enough to know not to spit out `border_color`unless the address mode is set to `clamp_to_border`...so it shouldn't require any changes.

**Comment by billhollings** [comment]
>yeah I think returning an error is the right thing

Sounds good. I'll fix this. 

MoltenVK can also advertise to the app via a new flag on `MVKPhysicalDeviceMetalFeatures`...plus the corresponding portability extension flag.

**Comment by billhollings** [comment]
> MoltenVK can also advertise to the app via a new flag on `MVKPhysicalDeviceMetalFeatures`...plus the corresponding portability extension flag.

Actually...I spoke prematurely _(sigh)_. MoltenVK _already_ has a `MVKPhysicalDeviceMetalFeatures::samplerClampToBorder` flag to advertise this.

So I'll just beef up the the error handling in `vkCreateSampler()`.

**Comment by jamesd9** [comment]
Thanks, this works great for me now. Feel free to close if you like.

**Comment by kvark** [comment]
> Thanks, I've hooked up to the new interface and confirmed this fixes the issue. Closing.

Would it be possible to un-hook this now? It blocks us from running Dota2.

**Comment by danginsburg** [comment]
> Would it be possible to un-hook this now? It blocks us from running Dota2.

The solution is not to remove the extension but for Dota to only use it when it's available.  I'll fix that.

**Comment by billhollings** [comment]
@danginsburg Is this enhancement sufficient for your needs? Can we close this now?

**Comment by danginsburg** [comment]
Yes, closing.

**Comment by alecazam** [comment]
Just wanted to point out that clamp to edge isn't correct on a shadow sampler unless you clear and then scissor the outer edge pixels to always be 0.  Otherwise, you'll get shadows smearing outside of the volume if there is a depth rendered at the edge.   This was a very old issue on A7/A8, but shadow maps are always fussy.
