### ISSUE TITLE
renderTargetArrayLength not set on iOS

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#558]
I'm testing on iOS 12.2 (iPad Air 3rd Gen) and hitting this validation error:

-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:instanceCount:baseInstance:maxVertexID:]:3883: failed assertion `the renderPipelineState has a vertex shader that writes to render_target_array_index but renderTargetArrayLength is set to zero’

The reason this is happening is because of the MVK_IOS #ifdef's here:

https://github.com/KhronosGroup/MoltenVK/blob/d95ea7e9a7589a1fc33906c673a6c835f74c716c/MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor%2BMoltenVK.m#L31

and here:

https://github.com/KhronosGroup/MoltenVK/blob/d95ea7e9a7589a1fc33906c673a6c835f74c716c/MoltenVK/MoltenVK/OS/MTLRenderPassDescriptor%2BMoltenVK.m#L39

So either the clear shader needs to not use render_target_array_index on iOS or these would need to change to support iOS.  I locally hacked them to work on iOS and on my particular 12.2 device it did work.

**Comment by cdavis5e** [comment]
Bah, I missed one. I added most of the stuff needed to support this on iPhone X in #465, but I forgot to update this.

**Comment by danginsburg** [comment]
Thanks for the quick fix!  Does anything need to be done to not set [render_target_array_index] in the shader or is that conditional already correct?

https://github.com/KhronosGroup/MoltenVK/blob/d95ea7e9a7589a1fc33906c673a6c835f74c716c/MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm#L182

**Comment by cdavis5e** [comment]
That conditional should already be correct. On iOS, `layeredRendering` is only set on A12 devices running iOS 12.
