### ISSUE TITLE
Sign extension of 8 bit types does not extend sign bit...

### ISSUE THREAD

**Issue by Ardy123** [KhronosGroup/MoltenVK#564]
When extending an char to an int, it doesn't preserve the sign value, resulting in incorrect output...

for example..
-89 + -15 + -39 + 42 should = -101 but instead equals 667

Here is the original opencl code compiled to spirv using clspv (https://github.com/google/clspv)..

void kernel func(__global int * pDst, __global char4 * pSrc) {
	const size_t id = get_global_id(0);
	int4 val = convert_int4(pSrc[id]);
	pDst[id] = val.x + val.y + val.z + val.w;
} 

here is the compiled spir-v code...

; SPIR-V
; Version: 1.0
; Generator: Codeplay; 0
; Bound: 43
; Schema: 0
               OpCapability Shader
               OpCapability Int8
               OpExtension "SPV_KHR_storage_buffer_storage_class"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %28 "func" %gl_GlobalInvocationID
               OpSource OpenCL_C 120
               OpDecorate %21 SpecId 0
               OpDecorate %22 SpecId 1
               OpDecorate %23 SpecId 2
               OpDecorate %_runtimearr_uint ArrayStride 4
               OpMemberDecorate %_struct_3 0 Offset 0
               OpDecorate %_struct_3 Block
               OpDecorate %_runtimearr_v4uchar ArrayStride 4
               OpMemberDecorate %_struct_8 0 Offset 0
               OpDecorate %_struct_8 Block
               OpDecorate %gl_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %gl_WorkGroupSize BuiltIn WorkgroupSize
               OpDecorate %26 DescriptorSet 0
               OpDecorate %26 Binding 0
               OpDecorate %27 DescriptorSet 0
               OpDecorate %27 Binding 1
       %uint = OpTypeInt 32 0
%_runtimearr_uint = OpTypeRuntimeArray %uint
  %_struct_3 = OpTypeStruct %_runtimearr_uint
%_ptr_StorageBuffer__struct_3 = OpTypePointer StorageBuffer %_struct_3
      %uchar = OpTypeInt 8 0
    %v4uchar = OpTypeVector %uchar 4
%_runtimearr_v4uchar = OpTypeRuntimeArray %v4uchar
  %_struct_8 = OpTypeStruct %_runtimearr_v4uchar
%_ptr_StorageBuffer__struct_8 = OpTypePointer StorageBuffer %_struct_8
       %void = OpTypeVoid
         %11 = OpTypeFunction %void
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%_ptr_Input_uint = OpTypePointer Input %uint
%_ptr_StorageBuffer_v4uchar = OpTypePointer StorageBuffer %v4uchar
     %v4uint = OpTypeVector %uint 4
%_ptr_StorageBuffer_uint = OpTypePointer StorageBuffer %uint
%_ptr_Private_v3uint = OpTypePointer Private %v3uint
     %uint_0 = OpConstant %uint 0
%gl_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input
         %21 = OpSpecConstant %uint 1
         %22 = OpSpecConstant %uint 1
         %23 = OpSpecConstant %uint 1
%gl_WorkGroupSize = OpSpecConstantComposite %v3uint %21 %22 %23
         %25 = OpVariable %_ptr_Private_v3uint Private %gl_WorkGroupSize
         %26 = OpVariable %_ptr_StorageBuffer__struct_3 StorageBuffer
         %27 = OpVariable %_ptr_StorageBuffer__struct_8 StorageBuffer
         %28 = OpFunction %void None %11
         %29 = OpLabel
         %30 = OpAccessChain %_ptr_Input_uint %gl_GlobalInvocationID %uint_0
         %31 = OpLoad %uint %30
         %32 = OpAccessChain %_ptr_StorageBuffer_v4uchar %27 %uint_0 %31
         %33 = OpLoad %v4uchar %32
         %34 = OpSConvert %v4uint %33
         %35 = OpCompositeExtract %uint %34 0
         %36 = OpCompositeExtract %uint %34 1
         %37 = OpIAdd %uint %35 %36
         %38 = OpCompositeExtract %uint %34 2
         %39 = OpIAdd %uint %37 %38
         %40 = OpCompositeExtract %uint %34 3
         %41 = OpIAdd %uint %39 %40
         %42 = OpAccessChain %_ptr_StorageBuffer_uint %26 %uint_0 %31
               OpStore %42 %41
               OpReturn
               OpFunctionEnd

**Comment by billhollings** [comment]
@Ardy123 

Can you repost this (and any shader conversions issues) to the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues), please? That's where it will get addressed.

...Bill

**Comment by Ardy123** [comment]
Done...
https://github.com/KhronosGroup/SPIRV-Cross/issues/939

**Comment by hrydgard** [comment]
The SPIRV-Cross bug is reported as fixed, should this be closed?
