### ISSUE TITLE
Use constant address space for SPIR-V parameters when generating tessellation control shader.

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/MoltenVK#566]
Regarding [pull request #940 of SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross/pull/940). In `MVKCommandEncoder::setComputeBytes`, the call `[MTLComputeCommandEncoder setBytes...]` requires use of the `constant` address space, but `[MTLComputeCommandEncoder setBuffer...]` requires 256-byte aligned offset. The former was a trivial fix, but the latter I don't see an obvious solution to.

**Comment by cdavis5e** [comment]
You can get a temporary `MTLBuffer` from the `MVKCommandEncoder`. See `getTempMTLBuffer()`.

I had hoped to avoid doing that, and it seems to work without Metal's validation layer on, but I guess validation doesn't like what I was doing there.
