### ISSUE TITLE
Tessellation pipeline re-clears attachments

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/MoltenVK#567]
After the tessellation control shader executes, `MVKCmdDraw::encode` calls `cmdEncoder->beginMetalRenderPass();` again. This creates a new `MTLRenderPassDescriptor`, which will clear the attachments based on the bound `VkRenderPass`'s clear modes. In practice this prevents the rendering of two or more tessellated objects unless one starts a new render pass with `VK_ATTACHMENT_LOAD_OP_LOAD`.

**Comment by cdavis5e** [comment]
Unfortunately, we have to create a new `MTLRenderPassDescriptor`, because we ended the old render pass to run the tess. control shader. This is a consequence of the weird (relative to practically every other graphics API) way Metal does tessellation. The fix, then, is to use `MTLLoadActionLoad` when restarting the render pass where the original load op was `VK_ATTACHMENT_LOAD_OP_CLEAR`.

**Comment by mbarriault** [comment]
Resolved in pull request #569.

**Comment by mbarriault** [comment]
Looks like this needs to be re-opened, my fix partially resolves the issue but it runs deeper than I anticipated. The true fix I think will need knowledge of the "future", which I don't think is necessarily impossible due to how Vulkan/MVK records commands before processing.

A typical render pass with tessellated objects might go like this, hoping I have the order of everything straight.

1. `vkCmdBeginRenderPass` is called with a render pass configured to with a color attachment that cleans on load, and stores on store, and a depth attachment that clears on load and doesn't care on store, creates the matching `MTLRenderPassDescriptor`, and creates a `MTLRenderCommandEncoder`.

2. `vkCmdDraw` with a tessellated object uses this `MTLRenderCommandEncoder` to run the vertex shader pre-pass. This should clear but otherwise not write to any color attachments, but may write to the depth attachment.

3. To properly sync with the tessellation control/compute shader, this `MTLRenderCommandEncoder` is ended, and a `MTLComputeCommandEncoder` is created, encoded, and ended to follow.

4. A new `MTLRenderCommandEncoder` with the same `MTLRenderPassDescriptor` except, with my fix, all attachments have their load actions set to load. The store actions are left based on the `vkRenderPass` configuration.

5. The actual tessellated Metal render is executed with this `MTLRenderCommandEncoder`, but any depth/stencil testing might be corrupted by the results of the vertex pre-pass.

6. Another `vkCmdDraw` call uses the `MTLRenderCommandEncoder` from step 5 for its vertex pre-pass. As colour attachments have been set to load, they shouldn't be touched, but depth attachments might be updated with new data based on the vertex shader results.

7. Again for tessellation control, this `MTLRenderCommandEncoder` gets ended too. In a typical pipeline, this will end up discarding the depth buffer. In step 3 this was irrelevant, nothing had been rendered to depth that was necessary to keep.

8. A new `MTLRenderCommandEncoder` is created, with depth attachment load set to load. However, its contents are undefined on account of the don't care store. In practice on my machine, this results in random flickering.

The full solution I have to meet the spec, which will certainly need iteration and discussion (and probably someone more confident in their familiarity with the codebase than myself to implement properly).

- `vkCmdBeginRenderPass` shouldn't create an `MTLRenderCommandEncoder` on execution. This should be deferred to the first `vkCmdDraw[Indirect]` execution that uses the attachments.

- Each `vkCmdDraw[Indirect]`, when recorded to the command buffer, should flag the MVK render pass object if it will, on execution, end one `MTLRenderCommandEncoder` and create another, based on the last pipeline that was recorded. For lack of a better term, let's call this flag `multiPass`.

- Each `vkCmdDraw[Indirect]` when recorded to the command buffer if it would set `mutliPass` will set a pointer in the MVK render pass object a pointer to itself, so that on execution the last draw call before `vkCmdEndRenderPass` will know it is so. For lack of a better term, let's call this pointer `lastMultiPassDraw `.

- Each tessellated vertex pre-pass should create its own `MTLRenderCommandEncoder`, configured with no color/depth/stencil attachments. The main `_mtlRenderEncoder` object should only be ever used (and created) in the `kMVKGraphicsStageRasterization` case.

- If `multiPass` isn't set, or there is only one draw call, the first `vkCmdDraw[Indirect]` stage writing to the input attachments will create `_mtlRenderEncoder` with load and store actions configured to the user.

- Otherwise, the first `vkCmdDraw[Indirect]` stage writing to the input attachments (known by `_mtlRenderEncoder` being null) will create a `MTLRenderCommandEncoder` with load actions configured to the user, and  all store actions override to store.

- Each intermediate `vkCmdDraw[Indirect]` stage writing to the input attachments (known by `_mtlRenderEncoder` being non-null and `this != lastMultiPassDraw `), if it has to end and start anew `_mtlRenderEncoder`, will do so with all load actions override to load, and all store actions override to store.

- The last `vkCmdDraw[Indirect]` stage writing to the input attachments (known by `this == lastMultiPassDraw`), if it has to end and start anew `_mtlRenderEncoder`, will do so with all load actions override to load, and all store actions configured to the user.

If I have the logic straight in my head, in a given Vulkan render pass, while there may be multiple constituent Metal render passes making it up, these changes should ensure that the load and store actions of the given Vulkan render pass are honoured.

**Comment by mbarriault** [comment]
I'm not sure if ending/creator more render passes has performance implications for the same amount of draw calls, but thinking about it further, we could also ensure the vertex pre-pass pipeline is created with depth/stencil writing disabled. Currently it inherits from the input `vkGraphicsPipelineCreateInfo`.

**Comment by billhollings** [comment]
@mbarriault Thanks for your detailed analysis. Are you able to reopen this issue yourself? Or I can do so if there is a permission issue stopping you.

**Comment by mbarriault** [comment]
As far as I can see Github doesn't offer me the option to re-open.

**Comment by billhollings** [comment]
Huh. Okay. Done.

**Comment by billhollings** [comment]
@mbarriault I've explicitly added you as a collaborator now. Let me know if that changes your permissions to do so in the future.

**Comment by mbarriault** [comment]
Yep, I get the re-open button on closed issues now.

I can probably hash out an initial fix this evening to this design, but as stated will certainly need discussion and iteration to ensure no other toes get stepped on.

**Comment by mbarriault** [comment]
I'm fairly confident (via stepping through code) that I have this issue fixed, the loads and stores happening appropriately across multiple draw calls, but I'm still getting the flickering rendering with indirect tessellated rendering. I'll need to investigate more but I'm pondering if there might actually be two issues going on here.

**Comment by mbarriault** [comment]
I'm still continuing my investigation to solve the flickering issue before issuing a pull request, but a thought occurred this morning. Is there any reason why an `MTLFence` couldn't be used instead of ending/restarting command encoders in each draw call? Each of the command encoder types have methods explicitly for synchronizing with other command encoders. We'd probably still need ending/restarting command encoders (with my override change) for backwards compatibility.
