### ISSUE TITLE
macOS: MoltenVK 1.0.34 crashes Dolphin emulator

### ISSUE THREAD

**Issue by pizuz** [KhronosGroup/MoltenVK#573]
Hi,

the recently released MoltenVK 1.0.34 crashes the [Dolphin emulator](https://github.com/dolphin-emu/dolphin) (latest dev build 5.0-9973) when trying to run any game. MoltenVK 1.0.33 (Dolphin ships with it) doesn't crash it. I'm getting this error:

`validateMTLStorageMode:240: failed assertion 'invalid storageMode (0). Must be one of MTLStorageModeManaged(1) MTLStorageModePrivate(2)'`

Specs: iMac14.3 (21.5'' Late 2013) with GeForce GT750M and macOS Mojave 10.14.4

Regards,
Pizuz

**Comment by cdavis5e** [comment]
Do you have a backtrace? I have a sneaking suspicion that #545 is the culprit, but I need evidence to confirm it.

**Comment by pizuz** [comment]
Is [this](https://github.com/KhronosGroup/MoltenVK/files/3078602/crash.zip) sufficient? Or shall I recompile MVK with debug symbols?

**Comment by cdavis5e** [comment]
No, that's sufficient. And yeah, that confirms my suspicion.

Does [this patch](https://github.com/KhronosGroup/MoltenVK/files/3080730/fix-shared-buffer-view.diff.txt) fix the problem?

**Comment by pizuz** [comment]
> No, that's sufficient. And yeah, that confirms my suspicion.
> 
> Does [this patch](https://github.com/KhronosGroup/MoltenVK/files/3080730/fix-shared-buffer-view.diff.txt) fix the problem?

Unfortunately no. Still crashes with the same error.

**Comment by cdavis5e** [comment]
Okay, how about [this patch](https://github.com/KhronosGroup/MoltenVK/files/3082153/fix-shared-buffer-view.diff.txt)?

**Comment by pizuz** [comment]
This one works.

**Comment by freesig** [comment]
I'm also getting a seg fault when closing a moltenvk application.
It's happening when the `~MVKSurface` destructor is called.
```
objc_msgSend
MVKSurface::~MVKSurface()
vkDestroySwapchainKHR
```

**Comment by clouds56** [comment]
same here,

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff7709c69d objc_msgSend + 29
1   libMoltenVK.dylib             	0x0000000105d75574 MVKSurface::~MVKSurface() + 68
2   libvulkan.1.dylib             	0x0000000105d312ac terminator_DestroySurfaceKHR + 110
```

after call to `VkCreateMacOSSurfaceMVK`, I let my program return and it crashes.

**Comment by cdavis5e** [comment]
The other crash is being looked at in #584.

**Comment by nsklaus** [comment]
threre might have been some regressions going on.
i've just compiled dolphin from sources, compilation succeeded, i can run it, it starts and i can see dolphin UI.
there's my games listed, i can go through configurations panel, configure my controller and so on.
but, as soon as i try to start a game, dolphin crashes.

here's the crashlog:
[Dolphin-2022-04-20-174839.log](https://github.com/KhronosGroup/MoltenVK/files/8523333/Dolphin-2022-04-20-174839.log)

**Comment by nsklaus** [comment]
i added the patch that could be found a few replies above (https://github.com/KhronosGroup/MoltenVK/issues/573#issuecomment-483427224)
and with this patch, my dolphin build gets able to start games without crashing.
