### ISSUE TITLE
MTLFeatureSet_iOS_GPUFamily5_v1 layeredRendering causes corruption

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#579]
I'm seeing corruption on MTLFeatureSet_iOS_GPUFamily5_v1 such as the iPhone XR.  I've narrowed it down to the fact that if I disable layeredRendering in MVKDevice.mm the problem goes away:

```
	if ( [_mtlDevice supportsFeatureSet: MTLFeatureSet_iOS_GPUFamily5_v1] ) {
		_metalFeatures.layeredRendering = false;
	}
```

As far as I can tell from the Metal GPU Frame Debugger, even though my vertex shader does not output [[render_target_array_index]] and my framebuffer was created with VkFramebufferCreateInfo.layers = 1, the Metal implementation appears to render two copies of my geometry, one outside the scissor/viewport I'm rendering to.  This causes corruption in the depth buffer.  There are no Metal Validation errors so it's not clear to me if this is a MoltenVK or driver bug.

I'm not sure of a simple workaround either.  If I try setting my VkFramebufferCreateInfo.layers = 0, then I get a Metal Validation error when it does a clear with the VS writing [[render_target_array_index].  For now I can workaround it by disabling layeredRendering (which I don't use anyway), but would like to understand the bug.

@cdavis5e @billhollings

**Comment by billhollings** [comment]
Duplicate of #594

**Comment by billhollings** [comment]
No longer considered a duplicate of #594. This is a different issue and was not resolved by #603.

**Comment by billhollings** [comment]
@danginsburg PR #604 should fix this. Please retest and close this if it does.

**Comment by danginsburg** [comment]
Confirmed fix, closing.
