### ISSUE TITLE
Package for Nix

### ISSUE THREAD

**Issue by TravisWhitaker** [KhronosGroup/MoltenVK#582]
[Nix](https://nixos.org/nix/) is a declarative package manager emphasizing reproducibility with good support for macOS. I'd like to use Nix to build and distribute macOS Nix packages that use MoltenVK. Naturally this will require a MoltenVK Nix package.

Doing this will require MoltenVK to be built quite differently than it is right now. It's difficult to get `xcodebuild` to play nicely in Nix's sandbox, and unfortunately the `xcbuild` alternative seems to be lacking some features required to build this package; for example, I was unable to coax it into generating the `*.inc` files in `spirv-tools` with CMake. Additionally, the required Apple SDK components and dependencies from `fetchDependencies` would be provided by Nix.

To this end, I'd like to try to provide an alternative build system as discussed in https://github.com/KhronosGroup/MoltenVK/issues/228.  I'm principally interested in building just `MoltenVK.framework`, `libMoltenVK.a`, `libMoltenVK.dylib`, and `MoltenVKShaderConverter` for macOS with a more flexible and less opaque build system.

@ioquatix, @binary132, was any progress on an alternative build process made? I'm likely to trip on some `xcodebuild` quirks along the way.

**Comment by ioquatix** [comment]
I gave up and distribute it as a binary package.

**Comment by ioquatix** [comment]
https://github.com/kurocha/vulkan-sdk-darwin/tree/master/lib/osx is the static library I use in teapot.

**Comment by o1lo01ol1o** [comment]
@TravisWhitaker I started https://github.com/o1lo01ol1o/MoltenVK-nix/blob/master/default.nix to do this but moved to the most recent lunarSDK (vis. https://github.com/achirkin/vulkan/pull/36) release before I got the final derivation to patch the correct paths.  The derivations compile and work, though

**Comment by TravisWhitaker** [comment]
@o1lo01ol1o Ah nice! I'd given up getting `xcodebuild` working inside Nix but this does the trick!

**Comment by reckenrode** [comment]
Just in case someone finds this in the search, I’ve opened https://github.com/NixOS/nixpkgs/pull/158534 to add a MoltenVK package to Nix. It’s currently impure, but that could change once x86_64-darwin is updated to a newer SDK.
