### ISSUE TITLE
Is it possible Converting glsl to spirv at runtime on arm devices (iOS)

### ISSUE THREAD

**Issue by seivan** [KhronosGroup/MoltenVK#586]
Using Shaderc right now for the glsl to spirv conversion, but since the lib doesn’t compile for iOS, I have to convert at build time.  

I was wondering if the current tools here can compile and run on an iOS device so I get hot code reloading working. 

I know Spirv Cross runs fine on iOS (thanks for that btw)

**Comment by billhollings** [comment]
@seivan 

The `MoltenVKGLSLToSPIRVConverter` library in MoltenVK runs on both macOS and iOS. It uses `glslang` internally.

Similarly the `MoltenVKSPIRVToMSLConverter` library runs on both macOS and iOS, and uses `SPIRV-Cross` internally.

The Hologram demo in MoltenVK is an example of linking to the  `MoltenVKGLSLToSPIRVConverter` library to convert GLSL at runtime.

Finally...after running `fetchDependencies` in MoltenVK...the `External/build` directory contains static libraries for both `glslang` and `SPRIV-Cross`for both iOS and macOS...in case you just wanted to use those libraries directly.

**Comment by seivan** [comment]
@billhollings Wow, that's better than I thought - thank you for replying and sorry for askins questions in the issue tracker! 

I can't seem to find the `game.h` used in the hologram example https://github.com/KhronosGroup/MoltenVK/blob/master/Demos/LunarG-VulkanSamples/Hologram/ShellMVK.cpp - I assume that's where the actual runtime loading of shaders happens.

Another question, could you point me to the build script for building glslang? I'm hoping to borrow it to make a cross platform build script for all platforms so one can static link and generate headers/bindings or other languages (e.g Rust)

**Comment by seivan** [comment]
Just want to point out when building glslang on its own using [cmake](`https://github.com/KhronosGroup/glslang/blob/master/CMakeLists.txt`) I only get libs for macOS. 
It doesn't seem to support iOS on its own - is `MoltenVKGLSLToSPIRVConverter` doing something to alter the build process?

**Comment by billhollings** [comment]
> Just want to point out when building glslang on its own using cmake I only get libs for macOS.
> It doesn't seem to support iOS on its own - is `MoltenVKGLSLToSPIRVConverter` doing something to alter the build process?

`MoltenVKGLSLToSPIRVConverter` runs it's own Xcode build process for `glslang`...specifically to support both macOS and iOS.

**Comment by seivan** [comment]
@billhollings Could you point out the build process `MoltenVKGLSLToSPIRVConverter` uses to build `glslang` to specifically support both macOS and iOS?
