### ISSUE TITLE
VK_FORMAT_D24_UNORM_S8_UINT is reported as unsupported

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#593]
Creating an image with `VK_FORMAT_D24_UNORM_S8_UINT` format generates a lot of validation layer messages. `vkGetPhysicalDeviceFormatProperties` reports that all feature flags for all tiling options are zero. Despite the error messages, the image is created successfully and works fine, so it looks like the issue is actually in format feature reporting.
H/W: MacBook PRO with Iris6100
SDK: 1.1.106.0

**Comment by cdavis5e** [comment]
I suspect this is because your hardware does not in fact support `MTLPixelFormatDepth24Unorm_Stencil8`. Or at least, the `isDepth24Stencil8PixelFormatSupported` property on the `MTLDevice` is returning `NO`. So when you query its format properties, it correctly reports that the format isn't supported for anything.

But, if you were to actually use the format to create an image, MoltenVK for some reason attempts to save you from yourself and substitutes the similar `MTLPixelFormatDepth32Float_Stencil8` format. That's why you can create images with `VK_FORMAT_D24_UNORM_S8_UINT`. Maybe MoltenVK shouldn't do that.

**Comment by danginsburg** [comment]
> Maybe MoltenVK shouldn't do that.

Yeah, a properly written Vulkan app should be able to handle D24S8 not being supported, if they have ever run on AMD hardware.

**Comment by DiligentGraphics** [comment]
@danginsburg This issue is not about Vulkan app not being able to handle unsupported d24s8 format, but rather Vulkan implementation reporting it as unsupported and still creating an image successfully.

@cdavis5e Looks like this is exactly what's going on. In fact on iOS there is a message about format being replaced. I guess similar message on Mac would've eliminated the confusion. Thanks for clarifying!

**Comment by billhollings** [comment]
I'm re-opening this for further discussion and exploration.

The backstory on this is that the concept of depth format substitution originated in the early days of MoltenVK when Metal had a very limited set of supported depth formats. All Vulkan apps at the time were, of course, originating on Vulkan platforms without regard for Metal...and so to get any apps running at all required either to change each app...or work some invisible magic under the covers.

For example...iOS _still_ does not support `VK_FORMAT_D16_UNORM`...which is a very common Vulkan depth request...so MoltenVK will indicate that, but substitute in `MTLPixelFormatDepth32Float` under the covers on iOS.

However...it does not necessarily need to stay this way. I think @DiligentGraphics & @danginsburg have a point in that MoltenVK should strive to accurately report what it supports...and not behave in surprising ways.

**Comment by DiligentGraphics** [comment]
@billhollings I actually appreciate MoltenVK transparently replacing u24s8 with f32s8 and making the app work with lots of validation errors rather than crash. With depth formats I guess the format replacement can be done transparently to the app in most cases.

My only remaining concern here is that MoltenVK on Mac does not tell the app that it replaces the format under the hood, which is the source of confusion. I tried to run the app on iOS, and there it indeed informs the app that the format is not supported and being replaced.
So I guess if the same message was displayed on Mac, there would be no confusion.

One thing is that if you replace the format, maybe it makes sense to change the image format too so that there are no validation layer errors about the original format.

**Comment by billhollings** [comment]
@DiligentGraphics Thanks for your very helpful feedback.

>Mac does not tell the app that it replaces the format under the hood, which is the source of confusion. I tried to run the app on iOS, and there it indeed informs the app that the format is not supported and being replaced.

Thanks...this will just be an oversight...and we should fix it. As @cdavis5e indicates...the `VK_FORMAT_D24_UNORM_S8_UINT`, specifically, has to be handled slightly differently than all other formats because it is optional depending on the GPU device itself, rather than the supported OS/GPU  feature set. So the error language is probably just missing from that test.

>One thing is that if you replace the format, maybe it makes sense to change the image format too so that there are no validation layer errors about the original format.

I'm not sure I understand what you are asking for here? Once the depth format is changed under the covers, in what sense is it triggering a validation error? Can you give me an example?

**Comment by DiligentGraphics** [comment]
@billhollings 

This is the full output that I get when creating D24S8 image:

```
Diligent Engine: ERROR: Vulkan debug message (validation): VUID_Undefined
                 vkCreateImage(): Format VK_FORMAT_D24_UNORM_S8_UINT is not supported for this combination of parameters.
                 Object[0] (unknown): Handle 0x0

Diligent Engine: ERROR: Vulkan debug message (validation): VUID_Undefined
                 vkCreateImage(): Format VK_FORMAT_D24_UNORM_S8_UINT is not supported for this combination of parameters.
                 Object[0] (unknown): Handle 0x0

Diligent Engine: ERROR: Vulkan debug message (validation): VUID-vkCmdClearDepthStencilImage-image-01994
                 In vkCmdClearDepthStencilImage, invalid optimalTilingFeatures (0x00000000) for format 129 used by image 0x432[Epipolar Image Depth]. The Vulkan spec states: The format features of image must contain VK_FORMAT_FEATURE_TRANSFER_DST_BIT. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdClearDepthStencilImage-image-01994)
                 Object[0] (image): Handle 0x432, Name: 'Epipolar Image Depth'

Diligent Engine: ERROR: Vulkan debug message (validation): VUID-vkCmdClearDepthStencilImage-image-01994
                 In vkCmdClearDepthStencilImage, invalid optimalTilingFeatures (0x00000000) for format 129 used by image 0x432[Epipolar Image Depth]. The Vulkan spec states: The format features of image must contain VK_FORMAT_FEATURE_TRANSFER_DST_BIT. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdClearDepthStencilImage-image-01994)
                 Object[0] (image): Handle 0x432, Name: 'Epipolar Image Depth'

Diligent Engine: ERROR: Vulkan debug message (validation): VUID-VkImageViewCreateInfo-None-02273
                 vkCreateImageView(): pCreateInfo->format VK_FORMAT_D24_UNORM_S8_UINT with tiling VK_IMAGE_TILING_OPTIMAL has no supported format features on this physical device. The Vulkan spec states: The format features of the resultant image view must contain at least one bit. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-None-02273)
                 Object[0] (image): Handle 0x432, Name: 'Epipolar Image Depth'

Diligent Engine: ERROR: Vulkan debug message (validation): VUID-VkImageViewCreateInfo-None-02273
                 vkCreateImageView(): pCreateInfo->format VK_FORMAT_D24_UNORM_S8_UINT with tiling VK_IMAGE_TILING_OPTIMAL has no supported format features on this physical device. The Vulkan spec states: The format features of the resultant image view must contain at least one bit. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-None-02273)
                 Object[0] (image): Handle 0x432, Name: 'Epipolar Image Depth'
```

What I am saying is that messages about `vkCmdClearDepthStencilImage` and `vkCreateImageView` refer to the original format that has been replaced under the hood with the one that works fine and should likely not been displayed.

The following output would tell the full story:

```
Diligent Engine: ERROR: Vulkan debug message (validation): VUID_Undefined
                 vkCreateImage(): Format VK_FORMAT_D24_UNORM_S8_UINT is not supported for this combination of parameters.
                 Object[0] (unknown): Handle 0x0

Diligent Engine: ERROR: Vulkan debug message (validation): VUID_Undefined
                 vkCreateImage(): Format VK_FORMAT_D24_UNORM_S8_UINT is not supported for this combination of parameters.
                 Object[0] (unknown): Handle 0x0

Diligent Engine: WARNING: <MoltenVK message about the format replacement>

<No more messages since vkCmdClearDepthStencilImage and vkCreateImageView work fine for replaced format>
```

**Comment by danginsburg** [comment]
If I'm understanding what you are requesting, I don't think it's possible.  The validation layers aren't aware of MoltenVK's substitution, correct?

Also, what's being done is still technically a violation of the spec.  The application should be querying for format support and only selecting D24S8 if it's supported.

**Comment by DiligentGraphics** [comment]
I am not really requesting this and understand that it may not be feasible. Like I said, a message from MoltenVK about format replacement will make everything clear and fully resolve the issue.

**Comment by billhollings** [comment]
@DiligentGraphics PR #760 finally fixes this. The substitution error is now logged when `MTLPixelFormatDepth24Unorm_Stencil8` is not supported by the `MTLDevice`. Please confirm and close this issue if this resolves the issue.
