### ISSUE TITLE
Dota: [MTLRenderPipelineDescriptorInternal validateWithDevice:]:2697: failed assertion `Pipeline rasterSampleCount (8) is greater than 1 but the pipeline vertex function is writing to render_target_array_index.'

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#594]
We shipped an update to Dota 2 last night and on some Macs (Macbook Pro 2018, Macbook Pro 2013 GT 650M) we are getting a crash when you click on a user profile.  Before the crash there is a Metal error:

[MTLRenderPipelineDescriptorInternal validateWithDevice:]:2697: failed assertion `Pipeline rasterSampleCount (8) is greater than 1 but the pipeline vertex function is writing to render_target_array_index.'

I'm going to probably ship a build that locally disables layeredRendering on macOS like I already do on iOS because of #579 .  This can be repro'd on public Dota by clicking on your user profile in the lower left of the screen.

**Comment by billhollings** [comment]
I'll have a look at this (and #579) as soon as I can today.

**Comment by danginsburg** [comment]
Thanks.  I think #579 is stalled because I wasn't able to provide a repro.  Unfortunately, we've made some changes and the bug no longer repros so I couldn't get a Metal frame capture of it.  This one is simple to repro though, should repro with public Dota 2.

**Comment by billhollings** [comment]
@danginsburg I'm not sure if I understand how to repro this issue:

>clicking on your user profile in the lower left of the screen

Do you mean this (for me _**?**_ icon)?

![Screen Shot 2019-05-09 at 3 02 36 PM](https://user-images.githubusercontent.com/356402/57479478-7f0aeb80-726b-11e9-8f89-782c539b9e5c.jpg)

Clicking it seems to safely take me to my profile. Is this the button you mean? Do I need to do anything further? Or is this device-specific?

I've tried this with the off-the-shelf 1.0.34 MoltenVK build...and the latest 1.0.35 at the repo HEAD.

**Comment by danginsburg** [comment]
Yeah, clicking that should take you to a screen with a menu PROFILE / STATS / TEAMMATES / TROPHIES / TICKETS.  It ran fine for me on AMD D500 macOS 10.14.4 but I got the crash repro'd on my Macbook Pro (Mid 2012) NV GT 650M running macOS 10.14.

**Comment by cdavis5e** [comment]
I wonder if that card doesn't support a 2D multisample array texture as a render target.

**Comment by billhollings** [comment]
@danginsburg Ah. Okay. Thanks for the info. I'm on AMD. I'll have to break out my older 2014 MacBook, update it to 10.14, etc. It has the NV GPU (and I think it's the 650).

**Comment by billhollings** [comment]
>I'll have to break out my older 2014 

I've reproduced the error on my MacBook 2014 with NV GPU. Looking into the issue.

**Comment by billhollings** [comment]
@danginsburg 

How does disabling `MVKPhysicalDeviceMetalFeatures::layeredRendering` fix the problem for you? It's hard to see how the internal MoltenVK changes when that is disabled would help if the app continued to expect it to work. 

Do you read that info out of MoltenVK and modify app behaviour? If so...do you pull it from `MVKPhysicalDeviceMetalFeatures::layeredRendering` through the MoltenVK API...or from `VkPhysicalDeviceLimits::maxFramebufferLayers` through the Vulkan API?

There seem to be two issues we need to resolve:

1. Detecting GPU's that cannot handle multi-sampled array textures.

    I've scoured Metal documentation looking into how to detect whether a device supports multi-sampled array texture rendering...but to no avail. 
    
    However...I am hopeful that we can make use of `MTLFeatureSet`. The older Mac that seems not to support multi-sampled array texture rendering has an NV GPU and reports itself as `GPUFamily1`...whereas the newer Mac that does have the required support has an AMD GPU and reports itself as `GPUFamily2`.

2. Modifying behaviour appropriately.

	I can't see any reasonable way of fixing this invisibly within MoltenVK. I'm open to options here if someone else has some ideas. Otherwise, we'll need to rely on feedback to the app, so it can modify its behaviour. 
	
	We could add a `MVKPhysicalDeviceMetalFeatures::multisampledLayeredRendering` as a compliment to `MVKPhysicalDeviceMetalFeatures::layeredRendering`. This would require the app to bother querying both of these feature flags through MoltenVK's API (or the Vulkan portability subset extension).
	
	I've been trying to find a Vulkan spec way of feeding back to the app...but although `vkGetPhysicalDeviceImageFormatProperties()` includes a `usage` flag that can identify images that are compatible with rendering attachments, it doesn't differentiate between the `sampleCounts` and `maxArrayLayers` axes of the returned `VkImageFormatProperties`. It seems we can't tell an app "you can have multisampling rendering or layered rendering, but not both" for an image intended as an attachment. 
	
	It seems the best we can do is return an error when a `VkImage` is created with attachment usage, and `samples` and `arrayLayers` both > 1.

**Comment by billhollings** [comment]
Can I get a clarification for what `layeredRendering` is being used for? 

The SPIR-V spec indicates that the `Layer` [built-in](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_a_id_builtin_a_builtin) (which triggers `render_target_array_index` in MSL) is to support Geometry shading. 

Since Geometry shading is not supported in MoltenVK or Metal...under what conditions are we generating shaders that are including the `Layer` built-in?

**Comment by billhollings** [comment]
>We could add a MVKPhysicalDeviceMetalFeatures::multisampledLayeredRendering as a compliment to MVKPhysicalDeviceMetalFeatures::layeredRendering.

I've come across this in the [Metal documentation](https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor/1437975-rendertargetarraylength?language=objc):

>Layered rendering to a multisample texture is not supported.

which would indicate that we should expect to encounter that validation error in all devices, regardless of `MTLFeatureSet`...and the logic I describe above for `MVKPhysicalDeviceMetalFeatures::multisampledLayeredRendering` should actually apply to `MVKPhysicalDeviceMetalFeatures::layeredRendering`.

However...it might be that the Metal doc has not been updated for the latest round of GPU's.

**Comment by mbarriault** [comment]
> The SPIR-V spec indicates that the Layer built-in (which triggers render_target_array_index in MSL) is to support Geometry shading.

As an aside, as I recall reading AMD has an extension that permits `Layer` to be used in vertex shaders as Metal does. There might be value in supporting it in MoltenVK.

More on topic, it feels like the kind of thing other implementations would just support against the spec, it wouldn't shock me to see applications relying on it without using a geometry shader.

**Comment by danginsburg** [comment]
@billhollings Just set layeredRendering to false inside of MoltenVK and it doesn't crash, correct?  That is all I'm doing, here's my patch:

```-- a/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
+++ b/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm
@@ -753,7 +753,7 @@
        }

        if ( [_mtlDevice supportsFeatureSet: MTLFeatureSet_iOS_GPUFamily5_v1] ) {
-               _metalFeatures.layeredRendering = true;
+               _metalFeatures.layeredRendering = false; //VALVE: Disable to workaround: https://github.com/KhronosGroup/MoltenVK/issues/579
        }

 #endif
@@ -765,7 +765,7 @@
        _metalFeatures.mtlCopyBufferAlignment = 4;
        _metalFeatures.indirectDrawing = true;
        _metalFeatures.baseVertexInstanceDrawing = true;
-       _metalFeatures.layeredRendering = true;
+       _metalFeatures.layeredRendering = false; //VALVE: Disable to workaround: https://github.com/KhronosGroup/MoltenVK/issues/594
        _metalFeatures.maxTextureDimension = (16 * KIBI);
        _metalFeatures.depthSampleCompare = true; 
```

I was hoping you would figure out why assuming you were able to repro it.  My guess was that setting [[render_target_array_index]] in the MoltenVK-built in clear shader was the problem.

**Comment by danginsburg** [comment]
I'm assuming it's this code that's problematic:

https://github.com/KhronosGroup/MoltenVK/blob/5dcc6d7501118b482a0f4214fb446635a2feb9aa/MoltenVK/MoltenVK/Commands/MVKCommandResourceFactory.mm#L184

**Comment by cdavis5e** [comment]
> As an aside, as I recall reading AMD has an extension that permits `Layer` to be used in other shader stages as Metal does. There might be value in supporting it in MoltenVK.

We already support the `VK_EXT_shader_viewport_index_layer` extension, which adds support for the `SPV_EXT_shader_viewport_index_layer` extension which does exactly as you describe.

**Comment by mbarriault** [comment]
> We already support the `VK_EXT_shader_viewport_index_layer` extension, which adds support for the `SPV_EXT_shader_viewport_index_layer` extension which does exactly as you describe.

Turns out I had neglected to update the checkout on my work computer when looking for support. It was quite out of date. My bad!

**Comment by billhollings** [comment]
@danginsburg PR #603 should fix this. Please retest and close this if it does.

**Comment by danginsburg** [comment]
Confirmed fix, closing.
