### ISSUE TITLE
Inconsistent Header Search Paths

### ISSUE THREAD

**Issue by jamesdolan** [KhronosGroup/MoltenVK#607]
MoltenVK seems to have fairly inconsistent header search path policies, and as a result things change from time to time which makes it pretty tricky to keep things working in other build systems.

1) Some code assumes third party repositories are under the Externals directory, which isn't the case in larger projects where those libraries are common dependencies outside of MoltenVK (e.g. we have tools that directly use SPIRV-Cross, SPIRV-Tools, etc and don't want MoltenVK "owning" them). Examples...
```
MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm:
 1396: #include "../External/SPIRV-Cross/mvkSpirvCrossRevisionDerived.h"
```

2) Search paths outside of third party repositories and nested search paths result in inconsistent include usage. This again makes it tricky to manage when the repositories might live someplace else. Examples...
```
MoltenVK/MoltenVKShaderConverter/include/MoltenVKSPIRVToMSLConverter/SPIRVToMSLConverter.h:
   22: #include <SPIRV-Cross/spirv.hpp>
MoltenVK/MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVReflection.h:
   22: #include "../SPIRV-Cross/spirv.hpp"
```

3) Lots of relative includes (#include "../some/path.h"), that are not actually relative to the current file, but instead relative to some random other search paths. Examples...
```
MoltenVK/MoltenVKShaderConverter/MoltenVKGLSLToSPIRVConverter/GLSLToSPIRVConverter.cpp:
   24: #include "../glslang/SPIRV/GlslangToSpv.h"
   25: #include "../glslang/SPIRV/disassemble.h"
   26: #include "../glslang/SPIRV/doc.h"
MoltenVK/MoltenVKShaderConverter/MoltenVKSPIRVToMSLConverter/SPIRVReflection.h:
   22: #include "../SPIRV-Cross/spirv.hpp"
   23: #include "../SPIRV-Cross/spirv_common.hpp"
```

4) The vulkan portability extension is stuck under a different search path than what the actual khronos  repository actually puts it...
`#include <vulkan-portability/vk_extx_portability_subset.h>`
...should be...
`#include <vulkan/vk_extx_portability_subset.h>`

I used to be able to build things without actually modifying MoltenVK, but in recent versions the header search paths have gotten so wild I need to maintain a fork just to fix the includes. Some basic rules (no nested search paths and no relative includes) and consistency would go a long way towards making life easier. Because beyond that its pretty easy to build.

**Comment by billhollings** [comment]
@jamesdolan 

Would these be solved with a consistent application of the framework references:

    #include <SPIRV-Cross/mvkSpirvCrossRevisionDerived.h>
    #include <SPIRV-Cross/spirv.hpp>
    #include <SPIRV-Cross/spirv_common.hpp>
    #include <SPIRV/GlslangToSpv.h>
    #include <SPIRV/disassemble.h>
    #include <SPIRV/doc.h>
    #include <vulkan/vk_extx_portability_subset.h>

along with the corresponding header search path build settings in `MoltenVK.xcodeproj`?

The `vulkan-portability` is the way it is so that it can be included in the same `MoltenVK/include` directory as the `vulkan` directory (since they come from difference sources). But perhaps we can find an alternate location approach for it.

**Comment by jamesdolan** [comment]
Thanks for the quick response!

So in the case of SPIRV-Cross, having `SPIRV-Cross/` in the include string means the search path is outside of the repository. In the example below it means I would need to add "MyThirdParty/" to the search path, exposing potentially other headers that I don't intend on in a given compilation unit unless I do some sort of extra sandboxing of the project. And more importantly, it also means I have to use different search paths when building MoltenVK than the other tools that use SPIRV-Cross.

```
MyThirdParty/
  MoltenVK/
    ...
  SPIRV-Cross/
    *.hpp
  SPIRV-Headers/
    include/
  SPIRV-Tools/
    include/
  Vulkan-Headers/
    include/
  Vulkan-Portability/
    include/
  cereal/
    include/
  Some/
  Other/
  Libraries/
  Here/
```

Looking at SPIRV-Cross usage itself, their expectation appears to be that the `SPIRV-Cross/` directory itself is the search path, and not the directory above the repository. e.g.

```
SPIRV-Cross/spirv_cfg.cpp:
   18: #include "spirv_cross.hpp"

SPIRV-Cross/spirv_cross.cpp:
   17: #include "spirv_cross.hpp"

SPIRV-Cross/spirv_cross_c.cpp:
   25: #include "spirv_cross.hpp"

SPIRV-Cross/tests-other/small_vector.cpp:
   17: #include "spirv_cross.hpp"
```

Keeping the search paths for third party code inside their respective repositories ensures that their path or name can change without too much fuss.

**Comment by jamesdolan** [comment]
as for the vulkan-portability thing, I do actually wish Khronos gave each extension their own directory name as you did, really does seem cleaner!  In my case `Vulkan-Headers/include` and `Vulkan-Portability/include` are just both in the search path. So they are kept separate that way. But it does feel dirty having my compiler search two "vukan" directories when try and include a header.

**Comment by billhollings** [comment]
>Keeping the search paths for third party code inside their respective repositories ensures that their path or name can change without too much fuss.

I'm not clear about what you are asking for now. Your examples of internal SPIRV-Cross files using same-directory access makes sense within that repo. But I don't see how that translates to the cross-repo access we're discussing.

Are you recommending that _**all**_ header file references be without qualifiers? So my list above would become:

	#include "mvkSpirvCrossRevisionDerived.h"
	#include "spirv.hpp"
	#include "spirv_common.hpp"
	#include "GlslangToSpv.h"
	#include "disassemble.h"
	#include "doc.h"
	#include "vk_extx_portability_subset.h"

If so...that sounds fragile...and I'd be concerned about cross-repo pollution and confusion if there are identically-named files in more than one external repo.

But if I've misinterpreted your recommendation here...can you specify the list above in terms of how you'd see it laid out in headers?

**Comment by billhollings** [comment]
PR #619 applies a consistent policy to references within MoltenVK to the external library headers. All references to external headers now include the framework component instead of relative file path references.

For example:

    #include "../glslang/SPIRV/GlslangToSpv.h"

is now:

    #include <glslang/SPIRV/GlslangToSpv.h>

This represents a compromise between the ability of an external build environment to arbitrarily locate the external libraries outside of MoltenVK, and the need within MoltenVK to identify header file references as belonging to specific external libraries and frameworks.

If further changes are required, please reopen this issue and identify them.
