### ISSUE TITLE
Make SPIRV-Tools optional?

### ISSUE THREAD

**Issue by jamesdolan** [KhronosGroup/MoltenVK#610]
Small request related to  #607 for making life easier to integrating into other build systems.

SPIRV-Tools is an extremely complicated project to build due to code-gen scripts, etc. It appears that MoltenVK only uses it for the value `SpvMagicNumber` (which SPIRV-Cross also exposes) and the function`mvk::logSPIRV` (which seems like it could be optional). So, a optional preprocessor macro to enable/disable SPIRV-Tools support would be much appreciated.

**Comment by billhollings** [comment]
This is implemented in PR #619, which includes a `MVK_EXCLUDE_SPIRV_TOOLS` build macro that will conditionally compile MoltenVK without reference to SPIRV-Tools code.

These changes are intended to provide the support for custom external build environments requested here. The MoltenVK build environment itself remains unchanged, and will continue to retrieve, build, and link the SPIRV-Tools repo and libraries.
