### ISSUE TITLE
Potential integer overflow issue

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/MoltenVK#615]
I'm wondering is this line correct?

https://github.com/KhronosGroup/MoltenVK/blob/6b556a96253de2461629ae8ec7313262bc52c256/MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm#L198

`_buffer->getByteCount()` returns the size of the buffer (not the underlying memory) while `_mtlBufferOffset` returns the offset into device memory. So if I allocate a buffer of 16 bytes, which is placed in some memory block at offset 64, byteCount will be -48. If my understanding is correct.

The reason why I think this is because my app is currently crashing in `MVKBufferView::getMTLTexture()` with the error message that texture with height of `40000000` (don't have the exact number, but it's a similarly large value) cannot be created as maximum is 16k. The code runs on normal Vulkan on Windows & Linux, and the buffer is definitely nowhere near that large. My app is also using AMD Vulkan memory allocator library, which tends to sub-divide device memory allocations and use device memory offsets internally.

I haven't had a chance to actually debug this. But regardless, this seems like the only place the error could be coming from. However my understanding of MoltenVK is limited to a few hours of exploring the code and I might be very much wrong.

Feel free to close the issue if you don't think this could be the cause, and I'll try to compile a debug version of MoltenVK and hopefully get a better understanding of what is going wrong.

**Comment by billhollings** [comment]
@BearishSun Thanks for all the research. This should be fixed in PR #617 now. Please retest and close this issue if it works.

**Comment by BearishSun** [comment]
The issue is resolved, thanks for solving it quickly.
