### ISSUE TITLE
When to expect the next release (following 1.1.106)?

### ISSUE THREAD

**Issue by mitchmindtree** [KhronosGroup/MoltenVK#618]
We're giving a presentation of a framework that uses MoltenVK under the hood tonight and I was just wondering if we could get a rough estimate on when you are hoping to release the next version? We're particularly interested in this so that we can give users an idea of when the fix for #584 (which is currently fixed on master) will be officially released. Thanks!

**Comment by billhollings** [comment]
@mitchmindtree The timing of MoltenVK's official marked releases are connected to the release of the Vulkan SDK. Typically they are on a six-week schedule...but it's best to ask LunarG.

**Comment by billhollings** [comment]
See issue #621 for latest SDK schedule.
