### ISSUE TITLE
Dota 2 GPU Hang with MTLEvent change 

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/MoltenVK#625]
I've been getting GPU hangs on startup in Dota 2 on Macbook Pro (Mid 2012) NV GT 650M on macOS 10.14.5.  I was able to use git bisect and identify that the commit that is causing the hang is b02d354be576fffb4b01501e504fe341473c75e8 "MVKSemaphore: Use MTLEvent for device-side synchronization."

@cdavis5e

**Comment by cdavis5e** [comment]
This is a known issue. See #602.

**Comment by billhollings** [comment]
PR #633 provides an automated workaround for this issue.
