### ISSUE TITLE
Simple D3D11 tesselation demo (with DXVK) renders incorrectly..

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#628]
Hi,
just testing simple D3D11 tessellation sample under DXVK 1.2.1..
notices this works on Linux/Win using DXVK so seems is not a DXVK issue..
I attach program with logs so you can reproduce.. 
logs doesn't show any errors.. 
warnings are similar if not equal to running d3d11-triangle sample under DXVK+MoltenVK and this case
renders correctly using ..
perhaps is a Metal driver bug? (I'm on 10.14.5 &Vega GPU)
EDIT: Missing correct rendering screenshoot (can obtain from executing exe file on windows).. will update post soon..
Correct rendering:
![image](https://user-images.githubusercontent.com/669305/58693286-b2cfc180-8390-11e9-8d84-0722fbd5634c.png)

Bad MoltenVK rendering:
![Captura de pantalla 2019-05-31 a las 9 24 13](https://user-images.githubusercontent.com/669305/58689207-aa728900-8386-11e9-8005-79afaef7c953.png)
Reproducer:
[tess.zip](https://github.com/KhronosGroup/MoltenVK/files/3240240/tess.zip)

**Comment by cdavis5e** [comment]
Can you retest this with #785?

**Comment by oscarbg** [comment]
will test soon.. sorry for delay..

**Comment by Rastafabisch** [comment]
Out of curiosity I just retested this with the current master ([67d4b33](https://github.com/KhronosGroup/MoltenVK/commit/67d4b335be6244ad7d5b47590d92ee58a5c5e637)).

I can report this one to be fixed.

<img width="400" alt="DXVK_Triangle" src="https://user-images.githubusercontent.com/38974866/93280795-c5ab1700-f7ca-11ea-9671-843b44a8e387.png">

**Comment by billhollings** [comment]
@Rastafabisch Thanks for the verification.
