### ISSUE TITLE
Support for VK_EXT_fragment_shader_interlock ?

### ISSUE THREAD

**Issue by Degerz** [KhronosGroup/MoltenVK#630]
With the [latest](https://github.com/KhronosGroup/Vulkan-Docs/commit/619084d44a605285e39530a0810d323ad024f897) Vulkan specification release, could we get this mapped to Metal's raster order groups feature ? 

Similarly, can we support this extension on top of another feature specific to iOS such as Metal's programmable blending feature ? 

Those are the two possible ways I can think of approaching it. Metal supports both fragment shader ordering and render target reads.

**Comment by oscarbg** [comment]
Hi,
+1
I think is "conceptually" better to map to raster order groups as seems more "equivalent" to it and generalizes to MacOS.. it's a Metal 2 feature BTW..
note just asked already for SPIRV-Cross support for it: https://github.com/KhronosGroup/SPIRV-Cross/issues/1002 (in fact I ask for more: also GLSL and HLSL backend support)
don't know once SPIRV-Cross dev supports it how much difficult & effort needed from Metal API side for MoltenVK support..

**Comment by Degerz** [comment]
Resolved in #734
