### ISSUE TITLE
Validation error with host visible+coherent buffer used as a uniform texel buffer

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/MoltenVK#639]
Hello.

When you create a `VkBuffer` with `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`, and then create a `VkBufferView` which gets used in a descriptor set for a texel uniform buffer binding, Metal validation reports an error:
`resourceOptions (0x10) must match backing buffer resource options (0x0)`

Doing some investigation, what appears to be happening is that the buffer gets `MTLStorageModeShared` set on creation, but when it tries to be bound as a uniform texel buffer, we create a texture descriptor (in `MVKBufferView::getMTLTexture`) which doesn't support `MTLStorageModeShared` so it gets switched to `MTLStorageModeManaged`. And that seems to anger the validation system.

Not sure what's the best way to fix this. Perhaps add an extension flag that lets the system know if a buffer is intended to be used for texture storage?

**Comment by cdavis5e** [comment]
> Perhaps add an extension flag that lets the system know if a buffer is intended to be used for texture storage?

There already is such a flag--two in fact. `VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT` and `VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT` indicate that the buffer will have `VkBufferView`s created out of it. The solution, then, is to force the buffer itself to use `MTLStorageModeManaged` when either of these bits is set.

**Comment by BearishSun** [comment]
The flag I suggest would need to be provided earlier on, as the buffer storage mode is determined as the memory is being allocated, before we have access to the flags above.

My intent with the flag was to avoid the case you suggest, where a secondary buffer will need to be allocated and existing contents copied, after we detect it will be used for a texel buffer. But that's also an option.

**Comment by BearishSun** [comment]
This issue appears to be resolved on the latest version.
