### ISSUE TITLE
Custom entry point names

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/MoltenVK#645]
Hi,

I'm having an issue trying to compile MSL using MoltenVK. When I run the application, I supply MSL directly to the stages and set pName to be the name of the entry point. However, the application reports that

"Shader module does not contain an entry point named 'main0'"

and looking at the MVK source code I can see that main0 is the default name. However, I've made sure that pName is populated properly. If I hack my shader by renaming the entry point it all works, but because it's asserting later on some unbound resources I've no way of knowing which shader is the problem because they all have the same name.

It's also worth noting I'm producing my MSL directly through a SPV -> SPIRV-Cross pipeline and not the tool provided by MVK.

Do you have any suggestions as to what I can do?

Thanks!

**Comment by billhollings** [comment]
Thanks for pointing this out. Looks like the `VkPipelineShaderStageCreateInfo::pName` doesn't make it to function creation when MSL is used directly. It's a bug.

 >Do you have any suggestions as to what I can do?

For now...just what you've been doing...name all your entry points `main0`...until this is fixed.

**Comment by redorav** [comment]
Thanks for your reply. I've been trying to add it myself but I'm already delving deep into MoltenVK trying to change it. Is there a place where I could add it myself with relative ease? It would really help me to debug the issues we're currently having.

**Comment by billhollings** [comment]
I haven't tested this other than to compile it...but you can try adding:

	mvkLib->_entryPoint.mtlFunctionName = pContext->options.entryPointName;

just before the last line of `MVKShaderModule::getMTLFunction(...)`. So the last two lines would then read:

	mvkLib->_entryPoint.mtlFunctionName = pContext->options.entryPointName;
	return mvkLib ? mvkLib->getMTLFunction(pSpecializationInfo, this) : MVKMTLFunctionNull;

**Comment by redorav** [comment]
I've moved to using SPIRV directly for now while I iron out the issues we're having. Once I'm ready to switch back this'll either be fixed or I'll use your suggestion. Thanks in both cases :)

**Comment by billhollings** [comment]
@redorav This has been fixed in PR #650. Function names for direct MSL are now set from `VkPipelineShaderStageCreateInfo::pName`. Please re-test and close this issue if it fixes it for you.

**Comment by billhollings** [comment]
Closing, since it's been a while. Please reopen if issue persists.
