### ISSUE TITLE
Support VK_EXT_metal_surface

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/MoltenVK#653]
It would be good for MoltenVK to support the proper VkPi surface extension, so that we can port the applications to be equally portable on MoltenVK and gfx-portability.

See https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VK_EXT_metal_surface.html

The current state of things is applications using `VK_MVK_macos_surface` directly and inconsistently: some providing `NSView`, others providing `CAMetalLayer`, which is *undocumented* and hacky.

**Comment by billhollings** [comment]
@kvark Thanks for the reminder! PR #654 adds this extension.

**Comment by billhollings** [comment]
Closing.
