### ISSUE TITLE
Plans to support MoltenVK in Unity3D?

### ISSUE THREAD

**Issue by Mikerr1111** [KhronosGroup/MoltenVK#66]
I've been using Vulkan in the Unity3D game engine for about 6 months now and things work great. I was wondering if there are plans for getting MoltenVK supported in Unity3D. I think this would be a great for  iOS game development.

**Comment by magicgoose** [comment]
Isn't it a ball in their court?

**Comment by Mikerr1111** [comment]
Yeah, I guess you got a good point there. Well, I will continue with with my own testing on Unity3D and report back if I have success.
