### ISSUE TITLE
Code checking image BLIT support interferes with image clearing

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#661]
@aerofly 

The following code in `MVKImage` is interfering with the ability of `MVKCmdClearImage` to clear an image (by rendering the clear color to it):

	// If this format doesn't support being blitted to, and the usage
	// doesn't specify use as an attachment, turn off
	// MTLTextureUsageRenderTarget.
	VkFormatProperties props;
	_device->getPhysicalDevice()->getFormatProperties(getVkFormat(), &props);
	if (!mvkAreAllFlagsEnabled(_isLinear ? props.linearTilingFeatures : props.optimalTilingFeatures, VK_FORMAT_FEATURE_BLIT_DST_BIT) &&
		!mvkIsAnyFlagEnabled(_usage, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT)) {
		mvkDisableFlag(usage, MTLTextureUsageRenderTarget);
	}

This code appeared in [this commit](https://github.com/KhronosGroup/MoltenVK/pull/376/commits/8c1581f24716781db0beeffe33e6651479d0dd7d#diff-ee7543ca32b7b1ce81aacf471ef6afcd). Bizarrely...unless I am blind...I can't find that code in the [PR that contains that commit](https://github.com/KhronosGroup/MoltenVK/pull/376)...which I am very confused about.

What was the reason for this code? What problem is it trying to solve? Can it simply be removed to clear the way for image clearing? Or can we adjust it to include `VK_IMAGE_USAGE_TRANSFER_DST_BIT` usage in the test for attachment usage?

**Comment by aerofly** [comment]
@billhollings 
I am pretty sure, I did not add or modify the above code as my commit was just introducing the MVKVector class. I did not work on anything else.

However when sending the pull request with my MVKVector class, I made a few mistakes on updating my version of MoltenVK as you can see in the conversation history.

So my assumption is, due to this issue, this code somehow found it's way back into MoltenVK even though it was previously removed by you or somebody, but I also don't see it anywhere in the history?

**Comment by billhollings** [comment]
@aerofly Thanks. 

Okay...I think I've found the [original commit](https://github.com/KhronosGroup/MoltenVK/pull/385/files).

@cdavis5e

On further examination...it turns out NOT to be the source of the error above...so we don't have to fix anything. But I am curious what this change was for. It is odd that we are turning off a Metal usage under the covers...rather than reporting via the Vulkan API...and I'm wondering if we should revisit this function in general. Do you recall why this change was made?

**Comment by cdavis5e** [comment]
I was running the CTS, and it tried to blit to a `VK_FORMAT_E5B9G9R9_UFLOAT` image. Metal--or perhaps more precisely, the driver for my Radeon card--cannot render to this format. And I think it hit the case where we fall back to a render in `vkCmdBlitImage()`.

**Comment by billhollings** [comment]
@cdavis5e Thanks.

`MTLTextureUsageRenderTarget` is being set on CTS tests that are using `VK_FORMAT_E5B9G9R9_UFLOAT_PACK32` as a BLIT source. So you turning it off under the covers doesn't affect that behaviour. And as you say...it won't ever be a BLIT destination...where removing `MTLTextureUsageRenderTarget` would cause a Metal validation error.
