### ISSUE TITLE
Vulkan SDK release coordination starting July 22

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#664]
LunarG is planning the next Vulkan SDK release for the week of July 22.

Final release date has not been set yet...and will depend on planning and testing. Updates will be posted here.

MoltenVK PRs submitted by Fri July 19 will be included. Please notify here if you want to get a PR into this SDK release after that date.

@cdavis5e @HansKristian-Work @jeremyk-lunarg

**Comment by billhollings** [comment]
> @billhollings It's probably a good idea to not pull in SPIRV-Cross with scalar block layout support until we have addressed this regression: [KhronosGroup/SPIRV-Cross#1088](https://github.com/KhronosGroup/SPIRV-Cross/issues/1088)

Thanks for the info. Can you give me a "known good" commit number sometime early next week (Monday/Tuesday)?

**Comment by HansKristian-Work** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/commit/44f688bf0b77d4f1a2c87de85980be0696974881 is the last commit before the scalar layout PR, I wouldn't pull anything later until further notice. I'm working on a rewrite of the packing logic, but not sure if it lands soon enough for next SDK release.

**Comment by billhollings** [comment]
Roger. Thanks.

**Comment by cdavis5e** [comment]
> [KhronosGroup/SPIRV-Cross@44f688b](https://github.com/KhronosGroup/SPIRV-Cross/commit/44f688bf0b77d4f1a2c87de85980be0696974881) is the last commit before the scalar layout PR, I wouldn't pull anything later until further notice. I'm working on a rewrite of the packing logic, but not sure if it lands soon enough for next SDK release.

It's too late--I've already pulled MoltenVK past that. I think we may need to revert #672 and part of #679.

> @cdavis5e is there any critical PR we need after scalar layout for next SDK release?

No, nothing critical.

**Comment by billhollings** [comment]
> It's too late--I've already pulled MoltenVK past that. I think we may need to revert #672 and part of #679.

@cdavis5e It's getting close to locking down dependency versions for the MoltenVK SDK release. Is the SPIRV-Cross version [currently used](https://github.com/KhronosGroup/MoltenVK/blob/master/ExternalRevisions/SPIRV-Cross_repo_revision) in MoltenVK good...or do we need to bump it for recent features you've added?

**Comment by cdavis5e** [comment]
We can't bump--all the commits for the features I added are *after* the commits which added scalar block layout, which are the ones which caused KhronosGroup/SPIRV-Cross#1088 and #681. If @HansKristian-Work can't get KhronosGroup/SPIRV-Cross#1089 ready in time, we'll have to revert #672 and the scalar block layout change from #679.

**Comment by HansKristian-Work** [comment]
Is there a concrete deadline to work with? I'll try very hard to have my PR merged ASAP. A ton of quirky issues with buffer packing have been fixed now in general.

**Comment by jeremyk-lunarg** [comment]
Please try to have this resolved by Thursday Morning, July 25.

**Comment by billhollings** [comment]
@jeremyk-lunarg Thanks. In the meantime...are you able to work with existing MoltenVK to test builds and ensure SDK compatibility?

**Comment by jeremyk-lunarg** [comment]
I will be checking that now.

**Comment by jeremyk-lunarg** [comment]
MoltenVK cannot build with the version of glslang we are shipping with.
It seems the version of SPIRV-Tools that glslang uses has removed the file `common_uniform_elim_pass.cpp`.

**Comment by billhollings** [comment]
> MoltenVK cannot build with the version of glslang we are shipping with.
> It seems the version of SPIRV-Tools that glslang uses has removed the file `common_uniform_elim_pass.cpp`.

Okay. I'll get an updated push out today.

**Comment by HansKristian-Work** [comment]
I should make the PR some time tomorrow (CEST). Some test fallout I'm working through.

**Comment by billhollings** [comment]
@jeremyk-lunarg PR #683 fixes the SPIRV-Tools build error...and is up to date for all MoltenVK dependencies _**except**_ SPIRV-Cross...which we will update by Thursday.

@cdavis5e Looks like the component names of the `VK_INTEL_shader_integer_functions2` extension changed between versions `1.1.114` and `1.1.115` of the Vulkan spec. I've changed the MoltenVK usage to match the `1.1.114` of this release of the SDK. We'll have to restore them to their `1.1.115` definitions on a future release.

**Comment by HansKristian-Work** [comment]
I've merged the PR :tada: . I think you can pull current master.

**Comment by billhollings** [comment]
> I've merged the PR 🎉 . I think you can pull current master.

@HansKristian-Work Thanks for the Herculean effort! I'll update MoltenVK.

**Comment by billhollings** [comment]
@jeremyk-lunarg Release [1.0.36](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.36) is ready to use for SDK 1.1.114.

**Comment by jeremyk-lunarg** [comment]
Great!  Thanks for all your hard work.
