### ISSUE TITLE
README.md should include an intro on running the demos

### ISSUE THREAD

**Issue by drhaynes** [KhronosGroup/MoltenVK#67]
The demo example projects fail to build, seemingly due to some missing files.

Steps to reproduce:
1. `git clone` with `--recursive`
2. run `MoltenVK/External/buildAll`
3. Open `MoltenVKPackaging` Xcode project
4. Run the aggregate target MoltenVK (Debug) to build everything
5. Open `Demos.xcworkspace` in `MoltenVK/Demos`
6. Try to run any of the demos, all fail to build with missing file errors.

Example from `Cube-macos` demo:

`error: /Users/someuser/dev/MoltenVK/Demos/LunarG-VulkanSamples/VulkanSamples/demos/cube-vert.spv: No such file or directory`

**Comment by geoeo** [comment]
You should read the readme.md in the demo folder. Steps are given there.

**Comment by drhaynes** [comment]
Ah yes, see it now - thanks. Quite easy to miss after following through the main project instructions.

Checking out other external repos and then modifying symlinks is somewhat non-obvious and unexpected. Perhaps this could be improved. Some suggestions:

1. Add to the main readme the steps for the demos (or at least mention that they have their own additional steps, and to go read the docs if you want to build them).
2. Change the filename in the demos folder to README.md - then it will appear on GitHub in the browser, making it more obvious, and harder to miss.
3. Could the demo dependencies be added as git submodules? Potentially eliminating the need for any additional steps to get them to work after following the main build instructions.

**Comment by geoeo** [comment]
>  modifying symlinks is somewhat non-obvious and unexpected.

Yes I agree, its quite obscure.

**Comment by billhollings** [comment]
I agree. This is a hold-over from before MoltenVK was open-source.

Building MoltenVK results in a runtime distribution package...and the real purpose of the demos and their documentation was to reside in that runtime package...where they were more obvious (and the `MoltenVK_Runtime_UserGuide.md` document, which is the primary document in the runtime package includes the kind of introduction that you are requesting).

I'll add some text to the main `README.md` explaining this. I'll also change the title of this issue to match that requirement.

**Comment by billhollings** [comment]
@drhaynes 

PR #83 includes the recommendations you made. The demos should be much more automatic now.

**Comment by drhaynes** [comment]
Great, thanks for the update @billhollings

Just tried following the instructions with a fresh clone and it's working flawlessly 👍
