### ISSUE TITLE
Wrong UBO layout since last update

### ISSUE THREAD

**Issue by aerofly** [KhronosGroup/MoltenVK#681]
A few of my shaders don't get their uniform values properly anymore since one of the last commits in the past days, e.g. I have a UBO with various vec3, mat4 and float fields and it seems like the layout has somehow changed. Using an older MoltenVK everything looks good.

Can this be linked to the new VK_EXT_scalar_block_layout extension, e.g. is it on by default maybe or do we have to do something differently during initialisation of MoltenVK?

**Comment by cdavis5e** [comment]
I strongly suspect it is linked to `VK_EXT_scalar_block_layout`, which would make it my fault.

Does building MoltenVK with KhronosGroup/SPIRV-Cross#1089 help?

**Comment by aerofly** [comment]
Ah ok, I see, I am pretty sure this is indeed the issue. I don't have the time to test it against the new SPIRV-Cross#1089, but will repeat my tests again, once SPIRV is updated.

**Comment by aerofly** [comment]
Ok, this issue is now resolved with the latest MoltenVK.
