### ISSUE TITLE
Some linear images can't be mapped to memory with VK_MEMORY_PROPERTY_HOST_COHERENT_BIT

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/MoltenVK#687]
Latest version of MoltenVK behaves in an apparently non-conformant way
by not allowing some linear images to be mapped to memory with
VK_MEMORY_PROPERTY_HOST_COHERENT_BIT. 

The spec guarantees that linear images can always be mapped to coherent memory:

> If buffer is a VkBuffer not created with the VK_BUFFER_CREATE_SPARSE_BINDING_BIT bit set, or if image is linear image, then the memoryTypeBits member always contains at least one bit set corresponding to a VkMemoryType with a propertyFlags that has both the VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT bit and the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT bit set. In other words, mappable coherent memory can always be attached to these objects.

The issue was found during testing of the macOS SDK for release 1.1.114. vkcube was throwing an exception.  The original issue can be seen [here](https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/issues/108). The problem was worked around in the vkcube for macOS and can be seen in this [pull request](https://github.com/KhronosGroup/Vulkan-Tools/pull/228).

**Comment by billhollings** [comment]
@KarenGhavam-lunarG 

I had mentioned the requirement for a staging buffer on the Cube demo on a related [Vulkan-Tools PR](https://github.com/KhronosGroup/Vulkan-Tools/pull/220#issuecomment-511903792)...but that PR never made it into the SDK release...and I guess the recommendation was missed as a result.

The recent MoltenVK changes were to accommodate CTS testing. 

The fundamental problem is that Metal textures on macOS do not support what Metal refers to as _shared memory_ (`VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT` in Vulkan). We had been faking it via black magic hacks on memory map & unmap...but it couldn't cover all Vulkan cases...and was breaking some CTS tests as a result.

Thanks for posting the spec reference. I was having trouble locating something along those lines during the changes.

I'll return to the drawing board and see if we can establish a consistent way of making this happen...and cleanly and clearly describe any non-conformance...for inclusion in the _Vulkan Portability_ spec.

**Comment by billhollings** [comment]
@KarenGhavam-lunarG Just to confirm from your comments...the Cube demo in the SDK has worked around this for now...and this is something that does _**not**_ need emergency attention for the 1.1.114 SDK...correct?

**Comment by KarenGhavam-lunarG** [comment]
@billhollings Correct. We did a workaround in the cube code for macOS only to enable us to move forward.

**Comment by billhollings** [comment]
Fixed in PR #690.
