### ISSUE TITLE
Validation error calling vkGetPhysicalDeviceSurfaceSupportKHR

### ISSUE THREAD

**Issue by trojanfoe** [KhronosGroup/MoltenVK#692]
I am writing a macOS app and have used the Cube source as an example, however I use the Vulkan SDK instead of using MoltenVK directly and loading them via `vkGetInstanceProcAddr()` as `cube.c` does.

I link against `libvulkan.dylib` and `libMoltenVK.dylib` and `#include <MoltenVK/mvk_vulkan.h>` in order to expose the metal extension automatically and to use this to create the surface:

    VkMetalSurfaceCreateInfoEXT createInfo = {};
    createInfo.sType = VK_STRUCTURE_TYPE_METAL_SURFACE_CREATE_INFO_EXT;
    createInfo.pNext = NULL;
    createInfo.flags = 0;
    createInfo.pLayer = (const CAMetalLayer*)initInfo.windowHandle;

    result = vkCreateMetalSurfaceEXT(_instance, &createInfo, NULL, &_surface);

I have enabled validation layers by setting `VK_LAYER_PATH` in the Xcode scheme (and disabled Sandboxing so the app can access the layers) and it's giving me the following validation error:

Invalid VkSurfaceKHR Object 0x6000029009a0. The Vulkan spec states: surface must be a valid VkSurfaceKHR handle (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkGetPhysicalDeviceSurfaceSupportKHR-surface-parameter)

For this code:

    VkBool32 presentSupport = false;
    vkGetPhysicalDeviceSurfaceSupportKHR(deviceInfo.device, i, _surface, &presentSupport);

However the surface pointer looks good to me:

    (lldb) p _surface
    (VkSurfaceKHR) $0 = 0x0000600002914e70
    (lldb) p deviceInfo.device
    (VkPhysicalDevice) $1 = 0x0000600000245200

Am I doing something fundamentally wrong here?  The code runs fine if I disable validation and the codebase runs fine under Windows/GLFW.

I hacked the Cube sample to also use `vkCreateMetalSurfaceEXT()` but I don't believe it honours the `VK_LAYERS_PATH` envvar as it's not using the Vulkan loader and therefore I could not enable the validation layers (I passed `--validate` to `cube_main()` and `demo->validate` is `TRUE`).

Any help greatly appreciated.

**Comment by cdavis5e** [comment]
I think the validation layer may not even support `VK_EXT_metal_surface`. I know the CTS doesn't use that extension--it just uses the old `VK_MVK_macos_surface` extension.

**Comment by trojanfoe** [comment]
Hey thanks for the reply.  Are there any disadvantages to using `VK_MVK_macos_surface` over `VK_EXT_metal_surface`?

**Comment by cdavis5e** [comment]
`VK_MVK_macos_surface` is now deprecated in favor of `VK_EXT_metal_surface`. So a future version of MoltenVK might rip the old extension out. We just need to implement support for the new extension in the validation layers, and test this in the CTS, and...

But other than that, not really. They largely provide the same functionality.

**Comment by trojanfoe** [comment]
OK nice one, many thanks.  I'll support both for now.
