### ISSUE TITLE
vkCmdBlitImage doesn't handle RGB <-> BGR swap

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/MoltenVK#704]
If you use vkCmdBlitImage to blit from a VK_FORMAT_R8G8B8A8_UNORM image to a VK_FORMAT_B8G8R8A8_UNORM image it seems to copy directly from byte to byte and the swizzle doesn't happen, so you end up with blue in red and red in blue.

I don't have a minimal repro, but if you build latest RenderDoc (or run the next nightly build for 2019-08-08 or later) and capture vkcube you'll see that the display of the lunarg.ppm texture and the backbuffer are incorrectly BGR flipped.

Tested on MoltenVK built from latest master, on an Intel HD 5000 GPU. Let me know if you need more information.

**Comment by billhollings** [comment]
Fixed in PR #717. Please retest and close if issue is fixed.

**Comment by baldurk** [comment]
Fixed for me, thanks!
