### ISSUE TITLE
Wrong include folder name for shaderc in Vulkan SDK

### ISSUE THREAD

**Issue by ePirat** [KhronosGroup/MoltenVK#719]
Not sure where else to report issues with the macOS Vulkan SDK, so I am doing it here. Please let me know if I should file an issue elsewhere.

The macOS Vulkan SDK contains external libraries, among these is shaderc. Unfortunately the headers for shaderc in the include folder are in a folder named libshaderc, which is not how shaderc installs its headers last time I tried. This leads to all projects including shaderc header files like `<shaderc/shaderc.h>` to fail compilation, even with the SDK installed and the build system able to find the library.

**Comment by billhollings** [comment]
LunarG maintains an [issue list](https://vulkan.lunarg.com/issue/home) for the Vulkan SDK.
