### ISSUE TITLE
Multiple errors when trying to use cubemap rendertargets

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/MoltenVK#72]
We are getting Metal validation errors when trying to:

- render to a cubemap (one face at a time, using image view with VK_IMAGE_VIEW_TYPE_2D and subresourceRange.baseArrayLayer 0..5)
- generate mipmaps for a cubemap (by blitting from face to face)

For the first issue, we get this Metal error:
> validateAttachmentOnDevice:267: failed assertion `Slice is 1, but the texture has only 1 slices'
durring vkCmdBeginRenderPass

For the second issue, we get this Metal error:
> validateFunctionArguments:3377: failed assertion `Fragment Function(fragCmdBlitImageF): incorrect type of texture (MTLTextureType2DArray) bound at texture binding at index 0 (expect MTLTextureType2D) for texture[0].'
from vkCmdBlitImage

It looks like the texture that we create is somehow classified as either a 2D texture or maybe a texture array instead of a cube texture? We create the texture with VK_IMAGE_TYPE_2D, arrayLayers=6 and VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT flag; after this we create the image view with type VK_IMAGE_VIEW_TYPE_CUBE; after this we create 6 image views with type VK_IMAGE_VIEW_TYPE_2D (to render into each individual face).

**Comment by billhollings** [comment]
Closing as fixed.
