### ISSUE TITLE
Vulkan SDK release build Monday Sept 9

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#721]
LunarG is planning the next Vulkan SDK release for the week of Monday Sept 9.

MoltenVK PRs approved by Friday Sept 6 will be included, and a MoltenVK release will be made Tuesday Sept 10. Please notify here if you need to get a PR into this SDK release after that date.

@cdavis5e @HansKristian-Work @jeremyk-lunarg

**Comment by billhollings** [comment]
Reminder that tomorrow, Fri Sept 6, is the last day to submit PR's for inclusion in the next Vulkan SDK.

@cdavis5e @HansKristian-Work @jeremyk-lunarg

**Comment by cdavis5e** [comment]
Great. There's some stuff I had planned--like argument buffer support and `VK_KHR_multiview` and `VK_KHR_sampler_ycbcr_conversion`--but I don't think I'm going to have all that ready in time.

**Comment by billhollings** [comment]
> Great. There's some stuff I had planned--like argument buffer support and `VK_KHR_multiview` and `VK_KHR_sampler_ycbcr_conversion`--but I don't think I'm going to have all that ready in time.

Thanks for letting me know...and thanks for the effort on those!

**Comment by oscarbg** [comment]
sorry to join.. but let me ask two questions here:
@billhollings will you sync/update your Metal 3.0 branch with all master branch changes in time for release also? (hopefully also upgrading spirv-cross to latest merging https://github.com/KhronosGroup/MoltenVK/pull/734)
@cdavis5e once VK_KHR_multiview and VK_KHR_sampler_ycbcr_conversion land at least the Metal3 branch which also has device_group support will be able to claim Vulkan 1.1 support finally.. or even then are some missing 1.1 features, still?
thanks..

**Comment by cdavis5e** [comment]
> @cdavis5e once VK_KHR_multiview and VK_KHR_sampler_ycbcr_conversion land at least the Metal3 branch which also has device_group support will be able to claim Vulkan 1.1 support finally.. or even then are some missing 1.1 features, still?

We'd still be missing external objects and shader subgroups.

**Comment by jeremyk-lunarg** [comment]
We will be using the following branches and commits in the SDK:
```
Vulkan-Headers:            sdk-1.1.121
Vulkan-Loader:             sdk-1.1.121
Vulkan-ValidationLayers:   sdk-1.1.121
KhronosGroup/Vulkan-Tools: sdk-1.1.121
LunarG/VulkanTools:        sdk-1.1.121
VulkanSamples:             sdk-1.1.121
glslang:                   34953810a62c5230cc059cfdf42dc44c5aab2246
SPIRV-Cross:               b32a1b415043f5ae368e90af7a585770ecd5546e
shaderc:                   61741808212152a3cbf37095be5f86fa3bdb5079
```

**Comment by billhollings** [comment]
@lenny-lunarg 

Thanks!

I could not find an `sdk-1.1.121` release for [LunarG/VulkanSamples](https://github.com/LunarG/VulkanSamples/releases)...so I am using commit  [`2403b94ed6463062acff8cfff563ad7ec5cf2b58`](https://github.com/LunarG/VulkanSamples/commit/2403b94ed6463062acff8cfff563ad7ec5cf2b58)...which is the current `HEAD` and is labelled _Update known good for 1.1.121 header_. Let me know if you want me to change that.

**Comment by jeremyk-lunarg** [comment]
@billhollings I might hold off on that.  Looks like there was some weirdness with how we branched.
We are going to have a meeting about it at 9:30am.
I'll update you after that meeting.

**Comment by jeremyk-lunarg** [comment]
@billhollings 
Okay, everything should be good now.
VulkanSmaples should have an sdk-1.1.121 branch.

**Comment by billhollings** [comment]
@jeremyk-lunarg 

Thanks. Working on it. Should be ready soon.

VulkanSamples does have a sdk-1.1.121 branch...and the commit I mention above is at it's HEAD...so all should be fine. 

However...in future it would be better to identify a specific release tag like in the other repos...so that we have a definite commit...since branches can move around as commits and merges are added.

**Comment by billhollings** [comment]
@jeremyk-lunarg  MoltenVK release [v1.0.37](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.37), including support for Vulkan SDK 1.1.121, is ready now.

**Comment by jeremyk-lunarg** [comment]
Thanks, @billhollings!

**Comment by billhollings** [comment]
@oscarbg 

>will you sync/update your Metal 3.0 branch with all master branch changes in time for release also?

MoltenVK release [v1.0.37-Metal-3.0](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.37-Metal-3.0) is available now.
