### ISSUE TITLE
Memory Leak in MVKInstance::initConfig

### ISSUE THREAD

**Issue by csmulhern** [KhronosGroup/MoltenVK#725]
I have noticed if I repeatedly call vkCreateInstance in a loop, memory usage of my process will grow unbounded. I have traced this to the autoreleased CFStrings that are allocated by mvkGetEnvVar, through the call to [[NSProcessInfo processInfo] environment]. Surrounding MVKInstance::initConfig in an autorelease pool would be one way to resolve the leak.

**Comment by billhollings** [comment]
@csmulhern 

What version of MoltenVK are you using?

This was fixed a couple of months ago, and was included in the MoltenVK 1.0.36 release, and the Vulkan SDK 1.114 release.

**Comment by csmulhern** [comment]
Doh, I was using version 1.1.106.0 of the Vulkan SDK. You are correct that this leak was resolved by updating.

On the latest version, I'm seeing two other leaks in the same code (that repeatedly creates and destroys an instance / device / command pool in a loop). One is a leak of MTLCommandQueueDescriptor from MVKQueue::initMTLCommandQueue, the other is a leak of CFString from [_MTLDevice name], called from mvkPopulateGPUInfo, called from 
MVKPhysicalDevice::initProperties.

Here are stack traces:
```
0 libsystem_malloc.dylib malloc_zone_calloc
1 libsystem_malloc.dylib calloc
2 libobjc.A.dylib class_createInstance
3 libobjc.A.dylib +[NSObject allocWithZone:]
4 Metal +[MTLCommandQueueDescriptor allocWithZone:]
5 Metal -[_MTLCommandQueue initWithDevice:maxCommandBufferCount:]
6 AppleIntelKBLGraphicsMTLDriver -[MTLIGAccelCommandQueue initWithDevice:maxCommandBufferCount:]
7 libMoltenVK.dylib MVKQueue::initMTLCommandQueue()
8 libMoltenVK.dylib MVKQueue::MVKQueue(MVKDevice*, MVKQueueFamily*, unsigned int, float)
9 libMoltenVK.dylib MVKDevice::initQueues(VkDeviceCreateInfo const*)
10 libMoltenVK.dylib MVKDevice::MVKDevice(MVKPhysicalDevice*, VkDeviceCreateInfo const*)
11 libMoltenVK.dylib vkCreateDevice
12 libvulkan.dylib terminator_CreateDevice
13  0x10f338f4f
14 libvulkan.dylib loader_create_device_chain
15 libvulkan.dylib loader_layer_create_device
16 libvulkan.dylib vkCreateDevice
```

```
0 libsystem_malloc.dylib malloc_zone_malloc
1 CoreFoundation __CFStrAllocateMutableContents
2 CoreFoundation __CFStringChangeSizeMultiple
3 CoreFoundation CFStringAppend
4 CoreFoundation -[NSArray componentsJoinedByString:]
5 Metal -[_MTLDevice name]
6 libMoltenVK.dylib mvkPopulateGPUInfo(VkPhysicalDeviceProperties&, id<MTLDevice>)
7 libMoltenVK.dylib MVKPhysicalDevice::initProperties()
8 libMoltenVK.dylib MVKPhysicalDevice::MVKPhysicalDevice(MVKInstance*, id<MTLDevice>)
9 libMoltenVK.dylib MVKInstance::MVKInstance(VkInstanceCreateInfo const*)
10 libMoltenVK.dylib vkCreateInstance
11 libvulkan.dylib terminator_CreateInstance
12  0x10f3369f8
13 libvulkan.dylib loader_create_instance_chain
14 libvulkan.dylib vkCreateInstance
```

**Comment by billhollings** [comment]
@csmulhern PR #751 includes a fix for this. Please retest and close this issue if the problem is fixed now.

**Comment by csmulhern** [comment]
That fixes it, thanks!
