### ISSUE TITLE
MoltenVK iOS dynamic lib for x86_64 (simulators)

### ISSUE THREAD

**Issue by Xioor** [KhronosGroup/MoltenVK#726]
I was able to use Vulkan with MoltenVK using SDL2 with libMoltenVK.dylib on a real ios device, but libMoltenVK.dylib does not work on an ios simulator because libMoltenVK.dylib is only created for arm64
(The one provided in vulkansdk-macos-1.1.114.0/MoltenVK/iOS/dynamic)

I am trying to find a way to create libMoltenVK.dylib with other architectures, but so far I have been unsuccessful. Does anyone have any ideas? I think I am close I tried playing around with MoltenVK/Scripts but no luck.

Architectures need to be: x86_64 and arm64.

Some old posts online say that metal does not work on ios simulator, but a newer forum post from an Apple developer say that Xcode 11 supports metal for ios simulators

**Comment by SpuriousWarning** [comment]
@Xioor - Heads up that dynamic linking will work fine for development on iOS, but note that Apple will reject your application if you try to submit it to the App Store with the dylib included in the bundle, at least if you follow the instructions in the MoltenVK user guide, per issue #739 that I opened a few days ago.

There may be an alternative way to include the dylib that will not be rejected, but if so I don't know what it is.

**Comment by Xioor** [comment]
@SpuriousWarning I was able to use libMoltenVK.a (static) instead and it works fine and should be approved now. But it only supports arm64 which is my original issue.

**Comment by SpuriousWarning** [comment]
@Xioor Great, glad to hear it. I'm doing something similar. I just didn't want you to be caught off-guard like I was when I tried to submit it as a dylib.

**Comment by Xioor** [comment]
@SpuriousWarning Thank you for reminding me tho because I would have forgotten to change it to static lib if you did not say so!

**Comment by Xioor** [comment]
Hey @billhollings I was wondering if you had any updates on this? Thanks!

**Comment by endanke** [comment]
I'm facing a similar issue, trying to use MoltenVK in a simulator with more or less success. I've changed the build settings in the _MoltenVK_, _Shader Converters_ and _External Dependencies_ projects to use standard architectures. Then I also had to change the _package_ext_libs_ios_ script to use _iphonesimulator_ in the folder path instead of _iphoneos_.
This way I used the _MoltenVKPackaging_ project to generate me the libs for x86_64 architecture. 

I'm using MacOS 10.15.4 and Xcode 11.4.1 so Metal should be supported in the simulator. I've tried the demo projects and they launch, but immediately crash afterwards. According to the logs the framework finds the supported Vulkan extensions in the simulator, but throws an error at _minimumTextureBufferAlignmentForPixelFormat_ saying: _MTLPixelFormatInvalid is not supported on this device._

Not sure what else should I supposed to configure, or if it's an issue specifically related to the simulator's Metal support.

**Comment by dolphineye** [comment]
I second this request. We are now using Xcode 11.14.2, and it seems it is no longer possible to embed a non-fat MoltenVK library in our Xcode project without breaking the iOS Simulator build (which we use for our unit tests). This basically makes it impossible for us to build our app with a MoltenVK backend for now.

At the very least, has anyone found a workaround for that?

**Comment by tmm1** [comment]
I believe @billhollings is looking into this according to his comment on https://github.com/KhronosGroup/MoltenVK/pull/912#pullrequestreview-432847275

**Comment by billhollings** [comment]
This is addressed in PR #935.

- Adds support for iOS Simulator and tvOS Simulator.
- Adds support for building fat iOS and tvOS binaries.
- The specific issues identified above have been addressed.

This PR represents initial Simulator support.

The iOS and tvOS Simulators provide a subset of Metal functionality available on the native platforms. This results in a reduced set of Vulkan functionality, relative to that available on the actual iOS and tvOS platforms.

Making up these differences will require a combination of ongoing MoltenVK development on the simulator platforms, and app development (in apps that intend to use the simulator) to work around any outstanding differences.

For example, known issues include:

- Simulators only allow Linear images on device local, non-host-visible memory. This is no-doubt a result of the combination of macOS Metal's lack of shared memory support for textures, and iOS/tvOS's lack of support for managed memory. To work around this, the Cube demo is configured to use staging buffers to load image content.

Now that Simulators are supported, I am closing this issue. Additional issues should be opened to identify and track individual simulator issues.

**Comment by technoir42** [comment]
@billhollings are pre-built iOS x86_64 (or fat) binaries going to be shipped as part of the upcoming Vulkan SDK release?

**Comment by billhollings** [comment]
@technoir42 That's up to the [SDK team](https://vulkan.lunarg.com/issue/home).

@jeremyk-lunarg Can you address this, please?

**Comment by jeremyk-lunarg** [comment]
@billhollings We will not be including the iOS fat binaries this SDK for 2 reasons:

1. This would require a platform selection infrastructure that our SDK currently doesn't have.

2. It is on our TODO list to someday add iOS as a target to the macSDK. To date, there has not been much demand for it. We need to evaluate developer requirements for this to do it correctly. It is possible that if we did include this fat binary with this SDK, then we would immediately have questions like "Where is my loader?", "Where are the validation layers?"

**Comment by technoir42** [comment]
@jeremyk-lunarg not sure if I get 2. SDK already includes MoltenVK binaries for iOS but they are not really useful if one wants to test on simulator. My request is simply a matter of adding x86_64 architecture to the existing binaries which would eliminate the need for developers to build MoltenVK themselves. The lack of iOS-targeting loader is not a big issue, at least for me.

I understand that it might be too late in the release cycle to make the necessary infrastructure changes for this to happen.
