### ISSUE TITLE
README.md - add list of compatible systems and GPU's

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#73]
MoltenVK relies on Metal. It would be helpful to reference in the MoltenVK `MoltenVK_Runtime_UserGuide.md` Apple's documentation about compatible devices and GPU's.

**Comment by kisak-valve** [comment]
There's a MacOS Metal-compatible hardware list compiled at http://www.idownloadblog.com/2015/06/22/how-to-find-mac-el-capitan-metal-compatible/.

An iOS compatibility list can be found at https://developer.apple.com/library/content/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/HardwareGPUInformation/HardwareGPUInformation.html.

**Comment by billhollings** [comment]
Fixed with PR #77.
