### ISSUE TITLE
Size of constant buffer cannot exceed 65536

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#730]
Can the size of a uniform buffer exceed 65536? On my Mac I get an error when I create my pipeline with vkCreateGraphicsPipelines using a shader that has a uniform buffer with a size greater than 65536. I do not get this error on iOS. Only Mac. Should I not exceed 65536 on both iOS and Mac? On Mac, my VkPhysicalDeviceLimits maxUniformBufferRang is 	1073741824. Is that not related?

**Comment by DiegoAce** [comment]
This is my output:

[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed: 

program_source:40:90: error: size of constant buffer cannot exceed 65536
vertex main0_out main0(main0_in in [[stage_in]], constant UniformData& ud [[buffer(0)]], constant UniformModel& um [[buffer(1)]], constant PushConstant& pc [[buffer(2)]], uint gl_InstanceIndex [[instance_id]])

**Comment by cdavis5e** [comment]
This actually appears to be a limitation of desktop Metal (cf. [Metal Feature Set Tables](https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf), under "Maximum function memory allocation for a buffer in the constant address space").

**Comment by DiegoAce** [comment]
Interesting. Thank you!
