### ISSUE TITLE
[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.116143 ms.

### ISSUE THREAD

**Issue by Graou74** [KhronosGroup/MoltenVK#732]
Hello,
I'm trying to implement in Java the Mac Osx part of the https://github.com/LWJGLX/lwjgl3-awt project that does not exist yet.
To test I am inspired by the code of the class **ClearScreenDemo.java** available from https://github.com/LWJGL/lwjgl3-demos.

During execution, the program enters an infinite loop by repeating the error message:
`[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.116143 ms.`

This infinite loop is triggered following the call of the function **vkQueueSubmit()** :
```
// Submit to the graphics queue
err = vkQueueSubmit(queue, submitInfo, VK_NULL_HANDLE);
```
and never give up.

I can not find any explanation for this error message. Does someone have an idea?

Traces reported by the API give other informations:
```
[mvk-info] MoltenVK version 1.0.34. Vulkan version 1.0.106.
	The following Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_descriptor_update_template v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v1
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_variable_pointers v1
		VK_EXT_host_query_reset v1
		VK_EXT_memory_budget v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_vertex_attribute_divisor v3
		VK_EXTX_portability_subset v1
		VK_MVK_macos_surface v2
		VK_MVK_moltenvk v19
		VK_AMD_gpu_shader_half_float v1
		VK_AMD_negative_viewport_height v1
[mvk-info] GPU device:
		model: AMD Radeon Pro 580
		type: Discrete
		vendorID: 0x1002
		deviceID: 0x67df
		pipelineCacheUUID: 00000000-0000-0000-0000-271300002732
	supports Metal Shading Language version 2.1 and the following Metal Feature Sets:
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
		macOS Read-Write Texture Tier 2
[mvk-info] Created VkInstance with the following Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_MVK_macos_surface v2
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 580 with the following Vulkan extensions enabled:
		VK_KHR_swapchain v70
[mvk-info] Created 3 swapchain images with initial size (0, 0).
[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.116143 ms.
[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.124134 ms.
[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.126483 ms.
[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.128368 ms.
[***MoltenVK ERROR***] Drawable could not be retrieved! Elapsed time: 559.130121 ms.
```

**Comment by billhollings** [comment]
Based on the size of your swapchain images, and the frequency with which you are failing to retrieve a drawable, I would expect that you did not pass in a `CAMetalLayer` when you created the rendering surface.

Which call did you use to create your display surface? You would have used one of `vkCreateMetalSurfaceEXT()` or `vkCreateMacOSSurfaceMVK()`. And how did you set the `CAMetalLayer` (or `NSView`) in that call?

And finally, are you using the Vulkan SDK, or using MoltenVK directly? The Vulkan SDK does not yet support the `vkCreateMetalSurfaceEXT()` call.

**Comment by Graou74** [comment]
I pass directly a CAMetalLayer (no NSView) but I realize that it is its initialization that must be missing.

Since the implementation is exclusively in Java using the JNI and Objective-C Runtime APIs and I am not familiar with these APIs, exploring the content of CAMetalLayer requires development that takes time.
All the more time that when I created this post I did not really know what information to look for.
Fortunately since I found the code MoltenVK which recovers the information of CAMetalLayer and I will be able to better target its initialization. I have not finished coding this initialization yet.

I'm using vkCreateMacOSSurfaceMVK () because the LWJGL version that supports the 
VK_EXT_metal_surface extension is not yet available. Here is the code part:

```
    	VkMacOSSurfaceCreateInfoMVK sci = VkMacOSSurfaceCreateInfoMVK.callocStack(stack)
    			.sType(MVKMacosSurface.VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK)
    			.pView(cAMetalLayerInstance);
        long surfaceAddr = stack.nmalloc(8, 8);
        int err = MVKMacosSurface.nvkCreateMacOSSurfaceMVK(data.instance, sci.address(), 0L, surfaceAddr);
```


Finally, I think to use directly the MoltenVK library since to use the Vulkan library, with LWJGL in the case for example where we want to go through a GLFW window, it is imperative to declare the VM argument "-Dorg.lwjgl.vulkan .libname = ... ". What I do not do here.

Thank you for your answer which confirms the track I discovered yesterday. Maybe you should wait until my new tests are finished and I give news. Unless of course you find an anomaly in view of new information that I have communicated.

**Comment by Graou74** [comment]
I was finally able to produce a usable CAMetalLayer (the exercise was much more difficult than it seemed).
For the moment this CAMetalLayer contains only its bounds property filled in and the trace indicates that it is well recognized:
```
[mvk-info] MoltenVK version 1.0.37. Vulkan version 1.0.121.
	The following 46 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v9
		VK_EXT_debug_utils v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_host_query_reset v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_vertex_attribute_divisor v3
		VK_EXTX_portability_subset v1
		VK_MVK_macos_surface v2
		VK_MVK_moltenvk v22
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_trinary_minmax v1
		VK_INTEL_shader_integer_functions2 v1
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: AMD Radeon Pro 580
		type: Discrete
		vendorID: 0x1002
		deviceID: 0x67df
		pipelineCacheUUID: 00002735-0000-2715-2082-E7E80189843A
	supports Metal Shading Language version 2.1 and the following Metal Feature Sets:
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
		macOS Read-Write Texture Tier 2
[mvk-info] Created VkInstance with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_MVK_macos_surface v2
[mvk-info] Using emulation for semaphores.
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 580 with the following 1 Vulkan extensions enabled:
		VK_KHR_swapchain v70
[mvk-info] Created 3 swapchain images with initial size (600, 400).
```
Of course, the rendering is not displayed since CAMetalLayer does not contain any information about the graphic area on the screen.
For the moment, I do not know what information to give to CAMetalLayer and I will try to find it in the sources.
However, if you have any information on this subject, they would be of great help to me.

**Comment by billhollings** [comment]
>if you have any information on this subject, they would be of great help to me.

I can't give you any information about how to create the `CAMetalLayer` in your Java environment...but typically you would create an instance of an `NSView` subclass that uses a `CAMetalLayer`...and add that view subclass instance to your window.

There are some properties you can set on your view subclass that helps with the integration. You can get an idea by exploring the Demo apps in MoltenVK repository. For example...the _Cube_ demo includes the following `NSView` subclass implementation:

```
/** The Metal-compatibile view for the demo Storyboard. */
@interface DemoView : NSView
@end

<...>

@implementation DemoView

/** Indicates that the view wants to draw using the backing layer instead of using drawRect:.  */
-(BOOL) wantsUpdateLayer { return YES; }

/** Returns a Metal-compatible layer. */
+(Class) layerClass { return [CAMetalLayer class]; }

/** If the wantsLayer property is set to YES, this method will be invoked to return a layer instance. */
-(CALayer*) makeBackingLayer {
	CALayer* layer = [self.class.layerClass layer];
	CGSize viewScale = [self convertSizeToBacking: CGSizeMake(1.0, 1.0)];
	layer.contentsScale = MIN(viewScale.width, viewScale.height);
	return layer;
}

@end
```

**Comment by Graou74** [comment]
Thank you, I will explore this track and see how I can do this.

For now I only get a Java AWT CALayer (CAOpenGLLayer more precisely) but I know there is (somewhere) an AWT subclass of NSView. 
I have also seen several window classes including one inherited from NSPanel which seems to me the best candidate in the context. 

Is the window to which to add the subclass of NSView you are talking about could be an NSPanel or should it be NSWindow?

**Comment by Graou74** [comment]
AWT Canvas is not attached to any window. It is well associated with a NSView but is not accessible.

It seems that it is possible to manage the rendering by passing only the CAMetalLayer but it requires an expertise that I do not have time to acquire.

Thank you for your help.
