### ISSUE TITLE
VkCmdFillBuffer threadsPerThreadgroup.width(1024) must be <= 256

### ISSUE THREAD

**Issue by starbucksDave** [KhronosGroup/MoltenVK#735]
On the Intel 630 the maximum thread group width is 256, where the compute kernel to fill a buffer has a threadgroup width of 1024. Maybe this can be reflected from the limits of the device where the pipeline is created on?

**Comment by billhollings** [comment]
MoltenVK uses `MTLComputePipelineState maxTotalThreadsPerThreadgroup` to determine the thread group width...and that property reports 1,024 for the width of an Intel 630. However...as you indicate, Metal validation uses 256 for the max on the same device.

It looks like, depending on the GPU, Metal can report different values from the `MTLComputePipelineState maxTotalThreadsPerThreadgroup` and `MTLDevice maxThreadsPerThreadgroup` properties.

PR #736 now uses the minimum of these two values to assign the threadgroup width.

Sigh.

**Comment by starbucksDave** [comment]
Tested and fixed in latest!
