### ISSUE TITLE
MoltenVK Ignores Value of MVK_CONFIG_SYNCHRONOUS_QUEUE_SUBMITS #define

### ISSUE THREAD

**Issue by SpuriousWarning** [KhronosGroup/MoltenVK#737]
From the code:
https://github.com/KhronosGroup/MoltenVK/blob/a87ef6bc77cc64e1d987b9863f8875d45670bea8/MoltenVK/MoltenVK/GPUObjects/MVKInstance.mm#L651-L657

The `#undef` clears whatever you set the `#define` to.

The comment is also a little confusing. It seems like a thought was omitted:
`should be turned off by default to ensure , whereas if MTLEvents are supported`

**Comment by billhollings** [comment]
Fixed in PR #745. Please retest and close this issue if it fixes your issue.
