### ISSUE TITLE
Why not just port mesa?

### ISSUE THREAD

**Issue by yurikoles** [KhronosGroup/MoltenVK#750]
I'm mostly sure that people behind this project had already reviewed difficulty of porting mesa to macOS. Could you please share issue that one may face when porting mesa to use real GPU acceleration on macOS? 

Mesa ticket: [1885](https://gitlab.freedesktop.org/mesa/mesa/issues/1885).

**Comment by billhollings** [comment]
I'm afraid we can't give you any advice as to how difficult it would be to generate Metal output from Mesa, as we did not look into it in any great detail during the development of MoltenVK.
