### ISSUE TITLE
Moltenvk blitting is behaving differently than pure vulkan implementations

### ISSUE THREAD

**Issue by mlfarrell** [KhronosGroup/MoltenVK#762]
I've been generating mipmaps per the "standard" techniques defined here https://vulkan-tutorial.com/Generating_Mipmaps.  

On windows, I get mipmaps that look nearly identical to the OpenGL driver's generated ones, but on moltenvk, something with the manual textured triangle-strip based blitting just isn't quite right - and they look quite ugly.  See the attached images.  It's almost as if the minification filter is skipping pixels or something.  I'm using LINEAR filter blitting (as shown the tutorial code).  My actual texture class is here - https://github.com/mlfarrell/VGL-Vulkan-Core/blob/master/src/VulkanTexture.cpp

See OpenGL vs Moltenvk comparison images (again, on windows, my vulkan implementation produces nicely-blitted mipmaps that look nearly identical to the GL driver).  Note the broken texture grain lines in the molten-vk image.  

<img width="276" alt="image" src="https://user-images.githubusercontent.com/7664370/67463607-9578e980-f5f6-11e9-8e29-286dcd06da08.png">
<img width="962" alt="image" src="https://user-images.githubusercontent.com/7664370/67463646-a6295f80-f5f6-11e9-89b2-bd774acd2603.png">

**Comment by billhollings** [comment]
@mlfarrell 

I'm having trouble seeing what the problem is. What are we looking at here? 

Which of the above image is the Vulkan vs OpenGL image? The resolutions seem to be very different. Is the first one (black background) a mipmap at a different level of the second (purple background)?

What are you expecting to see? Can you provide the OpenGL result, the native Vulkan result, and the MoltenVK result, all at the same mip-level resolution, so we can better identify the differences?

**Comment by mlfarrell** [comment]
The vulkan image is black.  The distance to the object is about the same (cropping makes this less apparent).  If i have time, I'll extract the mipmaps themselves from the GPU so you can really compare and see how the scaling is different on the moltenvk side.

**Comment by mlfarrell** [comment]
@billhollings 
Okay.  Here we go.  I put this together last night.  See attached zip.  One is OpenGL, other is molten vk.  Note that on windows' nvidia/amd vulkan drivers, the images exactly match the GL results.  Look at how blocky and incorrectly sampled the vulkan mips are.

Code to produce the mips on vulkan are using vkCmdBlit (or whatever it is).  It's exactly the same code that is in every vulkan tutorial for GPU mip generation online.  To save the mipmaps, I just copy back to a staging buffer and map it and then pass it to a png encoding routine.

For brevity, I've also posted two mip levels inline for comparison.  The smoother one is correct (GL/windows-vulkan).  The blocky one is moltenvk.

![opengl_mip4](https://user-images.githubusercontent.com/7664370/68238267-b0b40380-ffbd-11e9-8f20-8e9f33c54f67.png)
![vulkan_mip4](https://user-images.githubusercontent.com/7664370/68238269-b27dc700-ffbd-11e9-97df-a8fe8acebc02.png)

Full mipmaps (zip)
[mips.zip](https://github.com/KhronosGroup/MoltenVK/files/3810800/mips.zip)

**Comment by billhollings** [comment]
@mlfarrell Thanks. Looking into it.

**Comment by mlfarrell** [comment]
@billhollings last night I narrowed it down to a few things.
0 - The `_imageCopyRegions` path wasn't being taken, it is indeed blitting the image as it should.
1 - the blit command encoder is indeed getting the right filter (it's linear).  It's as if metal simply isn't listening to the filter and going nearest anyway.
2 - Maybe some nuance of metal rendering textures across levels prevents filtering from working properly.  I'd strongly suspect apple wants us to use MTLBlitCommandEncoder & blit commands here when possible.

**Comment by cdavis5e** [comment]
> 2 - Maybe some nuance of metal rendering textures across levels prevents filtering from working properly. I'd strongly suspect apple wants us to use MTLBlitCommandEncoder & blit commands here when possible.

Of course. Metal actually has a dedicated command for generating mipmaps--`-[MTLBlitCommandEncoder generateMipmaps:]`. One of the things I want to do is detect this case and optimize the blit calls to a `generateMipmaps:` call.

**Comment by billhollings** [comment]
>rendering textures across levels prevents filtering from working properly

This would be bizarre...and would raise concerns about Metal filtering in general.

>One of the things I want to do is detect this case and optimize the blit calls to a generateMipmapsForTexture: call.

Do-able...but ouch...what a kludge that would be...and would remove the ability for the app to choose the filtering type. Definitely a plan B.

I'm working on this now. Let's see.

**Comment by billhollings** [comment]
@mlfarrell This is fixed in PR #775. Please retest and close this issue if it fixes your issue.

**Comment by mlfarrell** [comment]
Fixed!
