### ISSUE TITLE
Inconsistent memory requirements vs. subresource size

### ISSUE THREAD

**Issue by cmccuewg** [KhronosGroup/MoltenVK#768]
We’re seeing a problem where vkGetImageSubresourceLayout and vkGetImageMemoryRequirements2KHR on iOS for the ASTC 4x4 LDR texture format appear to be returning inconsistent information.

When we create a 256x256 single-mip texture with that format, MVK returns (through vkGetImageMemoryRequirements2KHR) that its size is 64 KB which is exactly what we expect.  But when we call vkGetImageSubresourceLayout, it tells us that the size of subresource zero is 1024 KB which is far larger than the entire texture.  This causes problems when we then try to map the region with the size that was returned to us.

I’ve tracked this to MVKImage::initSubresourceLayout when that texture is created.  That function calls getBytesPerLayer, which essentially multiplies the return value of getBytesPerRow by the height.  In this case we expect bytes per row to be 1024 (the size of one row of 64 ASTC blocks) and the height to be 64 (the height in ASTC blocks).  This is what MVK thinks too, except that getBytesPerRow aligns the bytes per row by _byteAlignment, which is 16 KB!  So it ends up thinking that each row is 16 KB, and thus that the total size of the texture is 64 * 16 KB or 1024 KB.

**Comment by cmccuewg** [comment]
I just checked, and this still happens with the very latest MoltenVK code.  It also happens with BC compression when using MoltenVK on the Mac.

**Comment by billhollings** [comment]
@cmccuewg This is fixed in PR #778. Please retest and close this issue if it fixes your problem.

**Comment by cmccuewg** [comment]
Thanks!  I'm travelling most of next week so it may be the following week, but I will test this as soon as I can.

**Comment by cmccuewg** [comment]
Yes, this problem appears to be fixed.  Thank you!
