### ISSUE TITLE
Tessellation shader produces incorrect results

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#772]
[Sample application](https://www.dropbox.com/s/5hqxnjvjlk51jpe/Tutorial08_Tessellation.zip?dl=0)

Tried with the latest release (1.0.38)

OpenGL:
![image](https://user-images.githubusercontent.com/15135271/67916683-bfc92a80-fb53-11e9-8c45-2634ef86b2ff.png)

Vulkan:
![image](https://user-images.githubusercontent.com/15135271/67916749-f010c900-fb53-11e9-88a2-c5640ec6ab45.png)

**Comment by billhollings** [comment]
@cdavis5e Can you have a look at this when you get a chance, please?

**Comment by cdavis5e** [comment]
Sorry. I can't look at this right now because I'm busy with critical bugs in CrossOver 19.

**Comment by billhollings** [comment]
@cdavis5e  I've started to look at this now.

**Comment by billhollings** [comment]
@DiligentGraphics PR #785 fixes this issue. Please re-test and close this issue if it fixes your issue.

**Comment by DiligentGraphics** [comment]
@billhollings Thanks! Will test the fix soon.

**Comment by DiligentGraphics** [comment]
Verified with 1.1.130.0 sdk - everything works correctly.
Thanks!
