### ISSUE TITLE
Suggestion for More Accurate GPU Timings for vkCmdWriteTimestamp

### ISSUE THREAD

**Issue by SpuriousWarning** [KhronosGroup/MoltenVK#773]
Have you considered using MTLCommandBuffer's [GPUStartTime](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639924-gpustarttime?language=objc) and [GPUEndTime](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639926-gpuendtime?language=objc) instead of using system time at command buffer submission? These are doubles, in seconds.
Timestamp queries using VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT and VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT seem to correspond to these values.

As a further simplification, I think if you did this, you could multiply the result by one billion to convert it to nanoseconds and change VkPhysicalDeviceLimits::timestampPeriod to one rather than needing to use Mach system time computations.

**Comment by cdavis5e** [comment]
These are only available on iOS as of 10.3, and macOS as of 10.15.

Real timestamp queries are actually available on macOS in that version, too. One of the things on my todo list is to use the new support for queries in Catalina.

**Comment by prideout** [comment]
Filament uses timestamps for frame throttling so we would love to see this supported.

**Comment by danginsburg** [comment]
Yeah so does the Source 2 GPU Profiler, +1 to supporting this.

**Comment by lukexi** [comment]
+1 here too! I'm trying to profile a multi-stage compute shader pipeline and having timestamps working would be a huge help.
