### ISSUE TITLE
Invalid texture mip size passed to Metal in case of small (<4x4), compressed mips

### ISSUE THREAD

**Issue by wolfpld** [KhronosGroup/MoltenVK#774]
Hi.
I'm using MoltenVK bundled with Vulkan SDK 1.1.126 (currently the latest release) to target iOS devices.

When I'm trying to upload an 1x1 mip-map of a ETC2 compressed texture using `vkCmdCopyBufferToImage`, with `VkBufferImageCopy.imageExtent` set to `width=4`, `height=4` I get the following error during a call to `vkQueueSubmit()`:

`-[MTLDebugBlitCommandEncoder validateCopyFromBuffer:sourceOffset:sourceBytesPerRow:sourceBytesPerImage:sourceSize:toTexture:destinationSlice:destinationLevel:destinationOrigin:options:]:487: failed assertion '(destinationOrigin.x + sourceSize.width)(4) must be <= width(1).'`

Setting the `width` and `height` parameters to logical mip image size (1, 1), and not the compressed block size (4, 4) fixes the problem, but both options are equaly valid, according to my understanding of the Vulkan specification (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkBufferImageCopy.html):

> If the calling command’s VkImage parameter is a compressed image, or a single-plane, “_422” image format, imageExtent.width must be a multiple of the compressed texel block width or (imageExtent.width + imageOffset.x) must equal the image subresource width

>If the calling command’s VkImage parameter is a compressed image, or a single-plane, “_422” image format, imageExtent.height must be a multiple of the compressed texel block height or (imageExtent.height + imageOffset.y) must equal the image subresource height

I.e., passing the 4x4 mip size satisfies the "imageExtent.width must be a multiple of the compressed texel block width" rule and passing the 1x1 mip size satisfies the alternative "(imageExtent.width + imageOffset.x) must equal the image subresource width" rule.

Both ways of specifying the mip size should be working.

**Comment by billhollings** [comment]
>Both ways of specifying the mip size should be working.

Hmmm...I'm not sure that the "or" implies that you can use whichever value you want. 

Does the option to specify either value work on native Vulkan drivers?

The way I read the spec...if your copy extent does not have dimensions that align with the block size, then you should specify a copy extent that will fit inside the image (imageOffset + imageExtent == subresource width), and NOT use a multiple of the block size.

Or in other words...use a multiple of the block size...EXCEPT if doing so will extend beyond the subresource extent, in which case limit (imageOffset + imageExtent) to the subresource size.

In any case...PR #777 includes a fix to perform the desired clamping for you. Please retest and close this issue if it works for you.

**Comment by wolfpld** [comment]
> Or in other words...use a multiple of the block size...EXCEPT if doing so will extend beyond the subresource extent, in which case limit (imageOffset + imageExtent) to the subresource size.

I agree that the spec can be pretty vague about many things, but in this case this is a clear "A or B" situation. There is no extra language, which would guide someone to apply the A case in one scenario, and the B case in another one, so both must be valid at all times.

> Does the option to specify either value work on native Vulkan drivers?

Yes, the nvidia drivers on Windows accept both 1x1 and 4x4 subresource sizes for 1x1 image. Please also take a look at the validation layers error when trying to pass a 2x2 subresource size in such scenario:

`[ VUID-VkBufferImageCopy-imageExtent-00207 ] Object: 0x3d (Type = 10) | vkCmdCopyBufferToImage(): pRegion[0] extent width (2) must be a multiple of the compressed texture block width (4), or when added to offset.x (0) must equal the image subresource width (1).. The Vulkan spec states: (...)`

> In any case...PR #777 includes a fix to perform the desired clamping for you. Please retest and close this issue if it works for you.

Thanks. I won't be able to test this fix until the next Vulkan SDK is published.

**Comment by billhollings** [comment]
> I won't be able to test this fix until the next Vulkan SDK is published.

You can follow the [instructions for building MoltenVK](https://github.com/KhronosGroup/MoltenVK/blob/master/README.md#building) into a library, and then replace the existing MoltenVK libraries in the SDK with the libraries resulting from that build.
