### ISSUE TITLE
Updating from 1.1.121.1 to 1.1.126.0 results in crash on first call to vkAcquireNextImageKHR

### ISSUE THREAD

**Issue by aclysma** [KhronosGroup/MoltenVK#779]
While investigating this issue in my project (https://github.com/aclysma/skulpin/issues/18) I decided to try the latest SDK so that I could pick up PR #760. Unfortunately, my program crashes:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [7226]
```

Reverting back to 1.1.121.1 removes the crash and my program renders correctly. I do not see any debug validation when running either 1.1.121.1 or 1.1.126.0.

The fence is null, but the semaphore is not.

I'd appreciate any advice on both resolving the crash with 1.1.126.0 or with the original issue, which looks a lot like #742. Thanks!

**Comment by edoren** [comment]
I'm currently having the same issue, after switching to 1.1.121.1 it worked well.

**Comment by billhollings** [comment]
@aclysma 

You didn't provide much in the way of diagnostic info about the error.

This may be related to issue #791, and if so, PR #799 may have fixed this. 

Please retest and close this issue if it fixes the problem you encountered. If PR #799 does not fix this, please provide some further details to help us replicate and diagnose the issue.

**Comment by aclysma** [comment]
I'm fairly certain #791 is the same issue. Either of the following fix it:
 * Using queue family index 0
 * Building MoltenVK manually and copying libMoltenVK.dylib over the one installed by the 1.1.126.0 SDK
