### ISSUE TITLE
Device memory leaks MTLHeap

### ISSUE THREAD

**Issue by ystreet** [KhronosGroup/MoltenVK#780]
Using SDK 1.1.126.0:

I have an application that currently creates and destroys images every frame (yes I know that is terrible) that has a memory leak growing on the order of all of the image contents.

I believe this was introduced by https://github.com/KhronosGroup/MoltenVK/pull/711 by a missing `[_mtlHeap release]` in MVKDeviceMemory's destructor.

Unfortunately I do not currently have the build and runtime setup to test out such a change locally.

**Comment by billhollings** [comment]
@ystreet 

Thanks for reporting this and doing the detective work. PR #781 implements your suggestion. Please retest and close this issue if it fixes the problem for you.

**Comment by ystreet** [comment]
The leak is gone now! Thanks.
