### ISSUE TITLE
Vulkan SDK release feature cut-off Friday December 13

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#788]
LunarG is planning the next Vulkan SDK release in the week of Monday December 16.

MoltenVK PRs approved by Friday December 13 will be included, and a MoltenVK SDK release will be made Monday December 16.

@cdavis5e @HansKristian-Work @jeremyk-lunarg

**Comment by andystanton** [comment]
hi @billhollings, Will LunarG be notarizing the macOS binaries so they can be used with macOS Catalina? (see https://vulkan.lunarg.com/issue/view/5d9b73d786da81451cc37e7b for issue report).

**Comment by jeremyk-lunarg** [comment]
@andystanton we are working on getting the MacOS SDK notarized.  We are hoping it can be done this SDK, but it might slip to next SDK.  Until then, please follow this note in the MacOS Getting Started Guide:

> Note: macOS has a security feature that prevents the opening of unsigned applications. If you get a message stating the application cannot be opened because it is from an unidentified developer, you can control-click the application icon and then select "Open" from the shortcut menu. Then click "Open" to proceed. See this article for more information. The exact details may vary across different releases of macOS.

**Comment by andystanton** [comment]
Thanks @jeremyk-lunarg

**Comment by jeremyk-lunarg** [comment]
We aren't fully branched yet, but we have updated our repos to the version of glslang we will be using.
glslang: ebf634bcaa3e46ca8a912ed05b87281c731b2391 (commit id)
Vulkan-Headers: v1.1.130 (tag)
Vulkan-Tools: 0c2618b2c31e2f216e131ff4c1c83e2c92c6ae66 (commit id)
VulkanSamples: ae32f2390060925afa9c5b111ac94de6d13fe229 (commit id)

**Comment by jeremyk-lunarg** [comment]
@billhollings is what I gave you sufficient to start building the next MoltenVK release?

**Comment by billhollings** [comment]
> is what I gave you sufficient to start building the next MoltenVK release?

Sorry. Yup. Working on it now. Should be done by end of today (Monday).

**Comment by billhollings** [comment]
> Working on it now. Should be done by end of today (Monday).

PR #795 implements this and is in master now.

**Comment by billhollings** [comment]
@jeremyk-lunarg 

Please use [MoltenVK release v1.0.39](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.39).

Let me know if there are any issues with integration.

**Comment by jeremyk-lunarg** [comment]
Sounds good!
Thanks, Bill.
