### ISSUE TITLE
Please consider using glslang "known_good"

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/MoltenVK#79]
The glslang and SPIRV folks have done some things to make sure that the revisions of SPIRV-Tools and SPIRV-Headers are compatible with a given revision of glslang.  There is a `update_glslang_sources.py` script and a `known_good.json` file in the top of the glslang repo that are used to fetch the compatible versions of SPIRV-Tools and SPIRV-Headers for glslang.  These fetches are done in "external" directories inside the glslang tree (and not as siblings to glslang).

This approach ensures that the correct versions of the three repos are used.  Currently, this repo just pulls the latest of each of the three independently, which someday may cause a problem.

This concern should probably be motivation enough for switching, but there are other advantages.

The KhronosGroup/Vulkan-LoaderAndValidationLayers (LVL) repo pulls in (pending a PR) this MoltenVK repo as part of its build process.  The LVL repo also pulls in its own copy of glslang at a very specific "approved" revision.  It also uses the "known_good" approach to ensure that it gets the correct SPIRV revisions for the "approved" glslang revision.

Basically, the LVL build ends up fetching and building glslang/SPIRV twice since MoltenVK is doing it too. Worse, this arrangement can fetch and build different versions of these repos.

What I would like to be able to do is:
* Continue letting LVL build the glslang using the known_good approach. (It builds SPIRV as well this way)
* When building LVL for macOS, clone and build MoltenVK, but don't let MoltenVK fetch or build glslang and SPIRV
    * Don't clone the glslang and SPIRV submodules
    * Don't call the glslang/SPIRV build scripts in MoltenVK/External
* Put a symlink from MoltenVK/External/glslang to the the glslang that LVL built

I *can't* do something like replacing the three existing submodules in MoltenVK/External with symlinks to my LVL build of glslang because the `build` folders that contain things that MoltenVK needs end up being in different places.  Some of the paths to SPIRV build artifacts (e.g., `extension_enum.inc`) have to change in the MoltenVK Converter project (at least).  This is because the `build` folders in the three-repo arrangement (MVK) are in different places than in the one-repo arrangement (LVL).

I would like MoltenVK to build glslang/SPIRV using the "known_good" single-repo approach so that I can just tell it to use my glslang tree instead of using its own.

So, the steps needed for MoltenVK are:

* Remove the submodules of SPIRV-Tools and SPIRV-Headers
* Change the "make*" scripts in External so that they:
    * Don't build SPIRV-Tools (essentially remove these)
    * Call glslang's update_glslang_sources.py as part of the glslang build scripts
* Update any paths in the MoltenVK Xcode projects to point to the new build locations
    * Example:  `External/SPIRV-Tools/build/extension_enum.inc` would now be found in `External/glslang/build/External/spirv-tools`.

I'd be happy to submit a PR for this.  But I wanted to get Bill's and others' thoughts on this.

**Comment by billhollings** [comment]
@karl-lunarg 

The dependencies on `glslang`, `SPIRV-Tools`, and `SPIRV-Headers` in MoltenVK are minimal. None of them are part of any critical path within MoltenVK.

MoltenVK already includes `LVL` as a submodule.

Would it make sense to have MoltenVK remove those other three submodules...but continue to include `LVL`...and then simply defer all retrieving and building of those other three modules to scripts within `LVL`?

Would that provide consistency between MoltenVK and `LVL`?

**Comment by karl-lunarg** [comment]
Hmm, maybe...

So, the strategy here is to use LVL's glslang build script and remove all glslang/SPIRV building from MVK's External tree.

I'm trying to avoid building glslang/SPIRV twice, as well as have the correct versions.

* When MVK is the "top" repo, the steps to build things in Externals would have to change to not build glslang and spirv things, and instead go down into LVL and run the `update_external_sources.sh` script there to build glslang (and the SPIRV things inside the "new" glslang).

    * The script would need to be called with the 'glslang' parameter so that only glslang builds.  Otherwise, MVK gets downloaded and built again.
    * This has the advantage of getting LVL's notion of the "recommended version of glslang" and at the same time, getting the "known_good" SPIRV components that go with it. 
    * You will have to change any references to glslang or SPIRV components in the MVK Xcode projects from External/glslang, External/SPIRV-Tools, and External/SPIRV-Headers to their new locations under External/LVL/external/glslang.

That works fine.

BUT:

* When LVL is the "top" repo, it fetches and builds MVK.  In this arrangement, MVK already has LVL as a submodule, so LVL is there twice.  When the "top" LVL builds MVK, it ends up building the "bottom" LVL's glslang.   MVK needs for this are "minimal", but still exist, and I have to assume that glslang still needs to be built in a place where MVK can find it, which would be External/LVL/external/glslang.

    * Now the "top" LVL could forego building glslang on its own and then just symlink the "bottom" LVL's glslang up into its own.

I think this ends up being the same thing as my first proposal, except that the first proposal builds glslang in the top LVL and symlinks it to MVK/External.  This second proposal builds glslang in the bottom LVL and symlinks it to the top LVL.

Both require:
* MVK Xcode projects adjustments of references to glslang/SPIRV items

I think that the second one is better because:
* MVK can drop glslang and SPIRV submodules completely
* By MVK always using LVL's glslang, it will always get the recommended version 

Maybe we should think about it some and discuss on Wednesday.

What are the exact dependencies of MVK on glslang and SPIRV?

**Comment by billhollings** [comment]
MoltenVK uses SPIRV-Tools to disassemble SPIR-V code into human readable form during debug logging of shader conversion from SPIR-V to MSL.

MoltenVK uses `glslang` to provide a runtime convenience feature and tool to compile GLSL to SPIR-V. 

Neither use is critical to Vulkan runtime processing...and for the most part are not dependent on any particular version of either `glslang` or `SPIRV-Tools`.

**Comment by billhollings** [comment]
After external discussion:

- MoltenVK should retain `V-LVL` as submodule, but remove `glslang`, `SPIRV-Tools` and `SPIRV-Headers` and `SPIRV-HPP` submodules. 
- MoltenVK `makeAll` should call `V-LVL update_external_sources.sh` passing `glslang` arg to cause other dependencies to be retrieved and built within `V-LVL`
- MoltenVK provide `makeStubs` to remove retrieved `V-LVL` directory and replace with a symlink to a parent `V-LVL` directory...when MoltenVK is subdirectory within `V-LVL`.
- MoltenVK Xcode project needs to reference new file locations.
- MoltenVK-based Vulkan spec may not be available anymore.
- Update `ThirdPartyConfig.md` to reflect new organization.

**Comment by karl-lunarg** [comment]
> MoltenVK provide makeStubs to remove retrieved V-LVL directory and replace with a symlink to a parent V-LVL directory...when MoltenVK is subdirectory within V-LVL.

Bill, it might be better to let us worry about this script.  It isn't something that most MoltenVK users would use and it would need to reference something outside of the MVK repo, which is a bit risky.  We think it makes better sense for the parent (V-LVL) to make this link (or maybe just copy the LVL tree, etc).  And it seems that the responsibility for this should reside with the parent anyway.

**Comment by karl-lunarg** [comment]
Bill, we had some additional discussion and it is pretty likely that V-LVL is going to be broken up into smaller pieces.  Because of this breakup, it may not be best to rely on V-LVL to pull in required components, which is what your most recent approach does.

So, I Really Wish we could go back to my original more modest proposal, which will reduce the disruption and multiple changes in this repo:

* MoltenVK should retain V-LVL as a submodule (mainly for getting an ICD-related header file)
    * After the V-LVL repo split, this might need to change to the repo that has the ICD header (easy)
* MoltenVK removes `SPIRV-Tools` and `SPIRV-Headers` submodules and runs glslang's `update_glslang_sources.py` as part of MoltenVK's `External/makeglslang` script.  This pulls in the SPIRV content.
* MoltenVK project needs to reference new (SPIRV) file locations

All other aspects of MoltenVK's submodules remain the same.

This won't change things much when MoltenVK is the "top" repo.  Things work pretty much as before.  You do get the benefit of the guarantee that your SPIRV repos are the correct version for the glslang you are using.

This also achieves my goals for when V-LVL includes MVK:
* glslang/SPIRV can be built just once.  V-LVL will build it in its own `external` directory.  Instead of letting MVK build it, the V-LVL "update external" script will symlink V-LVL's built glslang to the location where MVK would have built it
* V-LVL gets to select the version of glslang it builds using its existing "known-revision" mechanism.  You've indicated that MVK is less sensitive to this, and so the V-LVL selection of version should be fine.
 
My main motivation for all this is to add macOS to V-LVL's Travis-CI build.  We try to be respectful of this free service and want to keep build times as low as possible.  Avoiding multiple builds of glslang/SPIRV is an important part of this.

**Comment by billhollings** [comment]
@karl-lunarg 

Thanks, Karl.

What about `vulkan.h` and `vulkan.hpp`? Should these come from `V-LVL/include/vulkan`? Or should I continue to generate them from a separate retrieved copy of `Vulkan-Hpp`?

**Comment by billhollings** [comment]
@karl-lunarg

PR #98 changes the way that external libraries are fetched and built, and should fix this issue.

The `glslang` version is now derived from `V-LVL`...and `SPRIV-Tools` and `SPIRV-Headers` are now fetched by `glslang`

In addition...when MoltenVk is being built as a component of `V-LVL`, the `fetchDependencies` script can be called with a `-sdk` argument that will cause it to symlink to the `V-LVL` and `glslang` directories within the parent `V-LVL`. 

The Vulkan header files used by MoltenVK are now derived from those in `V-LVL` too.

Please verify with the latest version of MoltenVK.

**Comment by karl-lunarg** [comment]
I had said before:

> Bill, we had some additional discussion and it is pretty likely that V-LVL is going to be broken up into smaller pieces. Because of this breakup, it may not be best to rely on V-LVL to pull in required components, which is what your most recent approach does.

So I guess we'll have to rework parts of this at some point.

I'll verify what is there now on March 16.
