### ISSUE TITLE
vkAcquireNextImageKHR throws std::out_of_range

### ISSUE THREAD

**Issue by maltekliemann** [KhronosGroup/MoltenVK#791]
I'm using MoltenVK from the LunarG Vulkan SDK 1.1.126.0 on macOS 10.15.1. The following issue has been discussed on stackexchange [[here]](https://stackoverflow.com/questions/59138184/vulkan-vkacquirenextimagekhr-throws-stdout-of-range-when-certain-queue-fam?noredirect=1#comment104594261_59138184) and is possibly related to #779 (and the issues referenced therein). 

### Detailed description

Calling `vkAcquireNextImageKHR` throws an uncaught `std::out_of_range` if *both* of the following are true:
* No device queue family with index `0` is created on the logical device
* The semaphore parameter is not null

Creating a device queue family with index `0` prevents the issue, even if it's never used. Using a fence instead of a semaphore for synchronisation, or no synchronisation objects at all also suppresses the problem.

Furthermore, this problem does not occur when using version 1.1.121.1 of the SDK (cf. #779). 

### Edit

Validation layer `VK_LAYER_KHRONOS_validation` does not issue any warnings.

**Comment by billhollings** [comment]
@maltekliemann 

PR #799 fixes this. Please retest and close this issue if it fixes the problem you encountered.

**Comment by maltekliemann** [comment]
@billhollings 

PR #799 has fixed the problem. Thank you!
