### ISSUE TITLE
Depth-only render pass doesn't clear depth if first draw is tessellation

### ISSUE THREAD

**Issue by mbarriault** [KhronosGroup/MoltenVK#792]
This doesn't seem to happen if there's a color attachment, but does if it's depth-only (such as a shadows pre-pass). Possible the issue comes in `MVKCommandEncodingPool::getMTLDepthStencilState`. When stepping through, `useDepth` was false. Note I first discovered this with a tessellated draw call, but putting a non-tessellated draw call first appeared to have the same issue.

Just in case I have my shadow pass configured incorrectly, the render pass is created with

    static const vk::AttachmentDescription attachmentDescription {{}, vk::Format::eD32Sfloat, vk::SampleCountFlagBits::e1, vk::AttachmentLoadOp::eClear, vk::AttachmentStoreOp::eStore, vk::AttachmentLoadOp::eDontCare, vk::AttachmentStoreOp::eDontCare, vk::ImageLayout::eUndefined, vk::ImageLayout::eTransferSrcOptimal};
    static const vk::AttachmentReference attachmentReference {0, vk::ImageLayout::eDepthAttachmentStencilReadOnlyOptimal};
    static const vk::SubpassDependency subpassDependency {0, VK_SUBPASS_EXTERNAL, vk::PipelineStageFlagBits::eLateFragmentTests, vk::PipelineStageFlagBits::eFragmentShader, vk::AccessFlagBits::eDepthStencilAttachmentWrite, vk::AccessFlagBits::eShaderRead, vk::DependencyFlagBits::eDeviceGroup};
    static const vk::SubpassDescription subpassDescription {{}, vk::PipelineBindPoint::eGraphics, 0, nullptr, 0, nullptr, nullptr, &attachmentReference, 0, nullptr};
    shadowRenderPass = device.createRenderPassUnique({{}, 1, &attachmentDescription, 1, &subpassDescription, 1, &subpassDependency});

**Comment by mbarriault** [comment]
Still investigating, I think I'm getting a lack of clear with a non-tessellated draw call too. This particular draw is full-screen so it's harder to measure.

**Comment by billhollings** [comment]
>Still investigating

Any progress? Is it possible to replicate what you're seeing in a sample app?

**Comment by mbarriault** [comment]
Not yet. I got distracted fixing the inline uniform, and generally busy with holidays. I'll try to get a reproducible demo over the next couple days.

**Comment by billhollings** [comment]
> I'll try to get a reproducible demo over the next couple days.

No rush. And certainly don't compromise the holiday season! 

We'll just leave this as is until you have time to get more info on the issue.

**Comment by mbarriault** [comment]
It's not making any more sense. Vulkan code and Metal debugger both confirm that depth is being cleared, but what's drawn shows it's not. I've cut down the project to the necessary bits to demo, but contains bits I'm not ready to open-source yet. Mind if I email it?

**Comment by billhollings** [comment]
> Mind if I email it?

Sure. You can email a test app in confidentiality to support@moltengl.com.

**Comment by mbarriault** [comment]
Slight update, vkCmdClearAttachments also doesn't clear. This is looking like it might be a Metal bug...

**Comment by billhollings** [comment]
@mbarriault PR #845 fixes this issue. Please retest and close this issue if it fixes the problem you encountered.

**Comment by mbarriault** [comment]
Apologies for delay getting back to this. This does fix the issue, and further, Apple responded to my feedback claiming the underlying MTLHeap issue has been fixed in Big Sur. I have just verified this with both the Metal and MoltenVK repro projects in beta 1 now working as intended.

**Comment by billhollings** [comment]
>MTLHeap issue has been fixed in Big Sur

Intersting. Thanks for the status update...and for verifying it.
