### ISSUE TITLE
Request: Support for VK_EXT_external_memory_host

### ISSUE THREAD

**Issue by starbucksDave** [KhronosGroup/MoltenVK#794]
Having dug around the Metal spec a bit, I discovered that it may be possible to implement the VK_EXT_external_memory_host extension in Molten.

This extension essentially allows you to create a piece of memory that points to some arbitrary pointer in system RAM. This is useful for things such as having multiple GPUs read/write to the same buffer that is backed by "imported" or "external" memory on the host, without needing explicit uploads or downloads.

Is this something that is on the roadmap for Molten?

Further reading
https://developer.apple.com/documentation/metal/mtldevice/1433382-makebuffer

**Comment by starbucksDave** [comment]
By the way, I think it is also possible to add similar support for device memory, through these constructs:

https://developer.apple.com/documentation/metal/mtlbuffer/2967416-remotestoragebuffer
https://developer.apple.com/documentation/metal/mtlbuffer/2967415-makeremotebufferview

Though adding support for this might be more complex..

**Comment by Wunkolo** [comment]
Would like to +1 this as well. I use it over on Linux/Windows to avoid having to make redundant copies of memory into a staging buffer.

**Comment by billhollings** [comment]
This enhancement is implement in PR #1854.
