### ISSUE TITLE
Interoperable Vulkan Metal Buffer

### ISSUE THREAD

**Issue by mmostajab** [KhronosGroup/MoltenVK#798]
MoltenVK's has a function to get a metal texture handle from a Vulkan image handle (vkGetMTLTextureMVK) and a function to get a Vulkan image handle from a metal texture handle (vkSetMTLTextureMVK); but we don't have any functions to make Vulkan/metal buffers interoperable.

Is there a reason for this? How hard is to realize this?

**Comment by Cry-Mory** [comment]
addressed by https://github.com/KhronosGroup/MoltenVK/pull/815
