### ISSUE TITLE
XCode may crash when capturing frame if using MTLHeap

### ISSUE THREAD

**Issue by apayen** [KhronosGroup/MoltenVK#801]
Hello,

After updating MoltenVK, we had xcode crashing when doing a frame capture. After try and error, we found out that disabling MTLHeaps by pretending the device does not support it solved the issue.

MTLHeap is the reason why we upgraded, and they are otherwise working perfectly fine. So our workaround is to have an environment variable to only disable them when we want to do a frame capture from xcode.

I think this is an issue on Apple's side, which cannot be resolved here (a crash report have been sent their way). But this can be marked as a known issue, along with adding an environment variable to force them off until Apple eventually fixes them.

Some more info:
* Captures always works if MTLHeaps are not used
* Captures never works if MTLHeaps are used with the same game code
* Captures will sometime work if we disable our draws an dispatch, with greater success rate as we disable more and more. The issue cannot be pinned to a single draw/dispatch, but is rather dependent on the complexity, with greater probability to fail with more complexity.
* Captures always works with MTLHeaps if all draw calls and dispatch are disabled. The memory view of the capture shows heaps and their contents as we expect them.
* The game behaves properly with MTLHeaps, we haven't noticed any difference/instability because of it

**Comment by billhollings** [comment]
> I think this is an issue on Apple's side, which cannot be resolved here

Disappointing to hear about this. Thanks for the suggestions and for filing the report with Apple.

**Comment by apayen** [comment]
I installed the xcode update that was just released and it seems to have fixed the issue so far.

**Comment by apayen** [comment]
The issue is still happening (though not 100% anymore), so we're sending more crash reports to Apple.

**Comment by billhollings** [comment]
`MTLHeaps` are not preferred, expect in specific situations. Apple acknowledges this too.

Consequently, their use in MoltenVK is optional, but is no longer the default behaviour.
