### ISSUE TITLE
Are MTLHeaps usable only on iOS 13.0+ ?

### ISSUE THREAD

**Issue by apayen** [KhronosGroup/MoltenVK#802]
https://github.com/KhronosGroup/MoltenVK/blob/9e09ece372b2fa383aaf60316483e5cd9243b12f/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L861-L863

Apple says ios support is SDK 10.0+ (https://developer.apple.com/documentation/metal/mtlheap?language=objc)

Is this intentionally restricted to iOS 13 here, or is it an error?

**Comment by billhollings** [comment]
`MTLHeaps` were added in MoltenVK specifically to support placement heaps...device memory heaps that can be configured with offsets. That is only available in iOS 13.

**Comment by apayen** [comment]
Ah yes, I was assuming that all the functions listed on that page were supported (TBH, I don't really see the point of heaps without placement), but these 2 functions are indeed iOS 13.0+ only

https://developer.apple.com/documentation/metal/mtlheap/3152522-newbufferwithlength?language=objc
https://developer.apple.com/documentation/metal/mtlheap/3152523-newtexturewithdescriptor?language=objc

Thanks for the clarification.
