### ISSUE TITLE
vkAcquireNextImageKHR do not properly signal the VkSemaphore

### ISSUE THREAD

**Issue by apayen** [KhronosGroup/MoltenVK#803]
Hello,

I was checking whether our engine had sane use of VkSemaphore. so I modified the MTLEvent implementation to have separates signal and wait counters, and assert when they are out of sync (they should be equal before a signal; and have signal == wait + 1 before a wait).

A first (minor) issue arose from here:

https://github.com/KhronosGroup/MoltenVK/blob/9e09ece372b2fa383aaf60316483e5cd9243b12f/MoltenVK/MoltenVK/GPUObjects/MVKSync.mm#L111-L114

Even if the command buffer is nil, the counter is being incremented.

I then ending up breaking the assert when inserting the wait after having acquired the image from the swapchain:

Our swapchain pattern is as follow (with two images):
```
Acquire, signals S0 -> returns index 0
wait on S0
frame commands
signal S0
Present image 0, wait S0
Acquire, signals S1 -> returns index 1
wait on S1
frame commands
signal S1
Present image 1, wait S1
... repeat ...
```

Acquire's behavior is:
- if the image is readily available, a command buffer is inserted in the first queue, and signals the semaphore
- If the image is not available, the semaphore is queued as a signaler for the next to be available image, and will be signaled when presenting that image.

The first case updates the counter (although the signal operation may happen much later than it should be)
In the second case, the counter is not updated and they get out of sync. The signal call will happen on the next present of this buffer. This means that, it will signal that value after the wait has been issued, and deadlock the GPU.

I notice the break would happen at the same places we sometimes had GPU crashes.

By refactoring our code to call Acquire before present, we got rid of the issue:
```
Init time:
Acquire, signals SA0 -> returns index 0
Acquire, signals SA1 -> returns index 1

Frame:
wait on SA0
frame commands
signal SP0
Acquire, signals SA0 -> returns index 0
Present image 0, wait SP0
wait on SA1
frame commands
signal SP1
Acquire, signals SA1 -> returns index 1
Present image 1, wait SP1
... repeat ...
```

Idealy, the event should be signaled by the CPU (using a MTLSharedEvent, it seems to have the same SDK requirements as MTLEvent), when the image is readily available.
When it is not, the counter would be backed up, without actually signaling (say, a DelayedSignal function). The semaphore can then be queued as is currently the case, along with the signal value. The Present already has a completion handler, where the delayed signal would actually happen (from the CPU).

Then, even if present is called before acquire, the semaphore is still signaled on the completion handler (assuming it completes after the acquire - otherwise we're on case 1, where acquire signals straight away).

**Comment by billhollings** [comment]
@apayen 

Thanks for all that research! I appreciate your insights.

Are you able to put together a Pull Request of the changes you recommend? That would be most appreciated.

**Comment by apayen** [comment]
I have put together those changes here:
https://github.com/apayen/MoltenVK/commit/a4ac715975ea3aa4cb95e91973b8f9010516304f

This is not completely shippable, in particular:
* I haven't implemented the new semaphore functions for the emulated or MTLFence implementation)
* It detects obvious (and less obvious) invalid semaphore usage, but those errors are not propagated to the client code.
* A chunk of code was dedicated to handle the case of using a single semaphore for multiple images leading to out-of-sync signal/wait operation. This is not a valid usage, as when a signal operation occurs, all previously submitted signal and wait operation on the semaphore must have completed. Thus, I did not investigate how to make it work with my implementation. Whether you want to support this case is up to you, but this is not required to be conformant to the vulkan specs.

Unfortunately, I do not have any mac or iOS device at home to provide a full implementation, and I cannot spend more time at work than required for our project to work. This should nevertheless be a good base. It works very smoothly on our project, which is a fairly complex one involving multiple queues every frame, but it can't hurt to test it on more projects and samples as well and see if it works properly everywhere.

The choice of VK_ERROR_DEVICE_LOST for semaphore errors is that it's a possible error code common to VkQueueSubmit, VkAcquireNextImageKHR and VkQueuePresentKHR. Incorrect usage would mostly lead to a GPU deadlock, so I think it makes sense to use VK_ERROR_DEVICE_LOST.

About incorrect semaphore usage, the specs states that:
> Before waiting on a semaphore, the application must ensure the semaphore is in a valid state for a wait operation. Specifically, when a semaphore wait and unsignal operation is submitted to a queue:
>
>    * The semaphore must be signaled, or have an associated semaphore signal operation that is pending execution.
>    * There must be no other queue waiting on the same semaphore when the operation executes.

It is also implictly assumed that a semaphore must be in the unsignaled state before being (re)signaled.

This implies that:
* When submitting a batch waiting on a semaphore, a batch signaling that semaphore must have been submitted before. So the submission of a signal and wait on a same semaphore cannot happen concurrently on separate threads. Submission of multiple signals concurrently is also implicitely prohibited (one of them would not be in the unsignaled state). Submission of multiple waits, concurrently or not is explicitly prohibited. Thus, mutex/atomic protections are not required.
* The signal and wait counters are always incremented in sync, and execution of the signal operations must happen in the same order as submission.

The implementation will check that the signal and read counters are always in sync; and when signaling from CPU, check that the last signal operation submited on that semaphore have been completed (order guarantee).

Please let me know if you have any question/concern

**Comment by apayen** [comment]
Hmm, some more thoughts:

> * The semaphore must be signaled, or have an associated semaphore signal operation that is pending execution.
> * There must be no other queue waiting on the same semaphore when the operation executes.

These requirements are not at submission time. So this means that the execution order or signals and waits need not be the same as submission.

To handle this, this means a different behavior of the semaphove must be implemented:
* signal always writes 1
* wait always reads 1 and writes 0 straight away

There cannot be conflicts due to multiple signaling, as it requires the semaphore to be in the unsignaled state (ie, 0).
There cannot be conflict due to multiple waits, as no other queue must be waiting on the same semaphore. Waiting and then writing doesn't need to be atomic either because there is no race allowed.

This simplifies the code above:
* no need for a delayed CPU signal to backup the counter (since signal is always 1).
* no need for counter at all
* signaling from CPU should check the runtime value to be 0, not the previous counter value

**Comment by apayen** [comment]
Actually, nevermind that last part, MTLEvent signal can only increase their value and cannot be reset to 0...

**Comment by cdavis5e** [comment]
Can you retest with latest HEAD? It should resolve the problems you were seeing.
