### ISSUE TITLE
Maximizing the window makes the app run very slow

### ISSUE THREAD

**Issue by DiligentGraphics** [KhronosGroup/MoltenVK#808]
For some reason, maximizing the application to full screen makes it run very slow. When the window is maximized but not full screen, it runs fine. When it is maximized and the title bar is shown, it also runs fine. The cube demo from the SDK runs fine.
Tested with 1.1.130.0 SDK on MacOS 10.15.
https://www.dropbox.com/s/6p9qrd4dnsvb8nc/Tutorial02_Cube.app.zip?dl=0
The app needs to be started from the command line so that the loader is able to find the dylib.

**Comment by billhollings** [comment]
@DiligentGraphics Thanks for the demo app. I'm able to replicate the issue with it...and looking into the problem.

**Comment by billhollings** [comment]
@DiligentGraphics 

The reason this doesn't happen on the Cube demo is that the Cube demo uses 3 swapchain images, whereas your app uses 2. Changing the Cube demo to use 2 swapchain images causes the same effect as you're seeing. I recommend using 3 swapchain images at all times...but particularly when your app is in fullscreen mode.

In full-screen display mode, Metal uses Direct to Display, which bypasses the display compositor. As soon as something else needs to be displayed, such as a title bar, or even a notification alert, the compositor is invoked and the delays disappear.

Interestingly (and counterintuitively), it appears that Direct to Display might cause the display system to hold onto the drawable longer than when the compositor is used, causing the `CAMetalLayer nextDrawable` call to stall. Normally, `nextDrawable` returns within microseconds. In fullscreen mode, with 2 swapchain images, it can take dozens of milliseconds (sometimes over 100 ms). Even with 3 swapchain images, `nextDrawable` can still take single-digit milliseconds to return while in fullscreen mode.

BTW...PR #810 includes some new abilities to track and report on the performance of the `CAMetalLayer nextDrawable` call. This has no effect on fixing anything...but it does help to illuminate the delays of the various `nextDrawable` scenarios. Use the `MVK_CONFIG_PERFORMANCE_TRACKING` and `MVK_CONFIG_PERFORMANCE_LOGGING_FRAME_COUNT` environment variables to enable and log this performance tracking.

**Comment by QuantumDeveloper** [comment]
@billhollings Seems this is exactly the same issue which I was talking about in #742 
Finally you found the reason which causing this.

**Comment by billhollings** [comment]
@QuantumDeveloper 

>Seems this is exactly the same issue which I was talking about in #742

I've marked #742 as a duplicate.

Can you confirm that you were also using 2 swapchain images and that moving to 3 swapchain images fixes this?

**Comment by QuantumDeveloper** [comment]
@billhollings yes, I also use 2 images before, but I cannot say that changing it to 3 fixes an issue. It definitely increase from 100 to 2500 FPS in full screen mode, BUT at the same time in windowed mode it still stays nearly 250-300 FPS, which is obviously not correct. 
FPS count should be the same independently from window mode

**Comment by DiligentGraphics** [comment]
@billhollings Thanks! Using 3 swap chain images does fix the problem. It is really quite unexpected that this causes such massive performance degradation.
If you have a list of known issues/BKMs, I think it is worth mentioning about this problem there because this might be quite a surprise for people coming from other platforms.

**Comment by billhollings** [comment]
>I think it is worth mentioning about this problem

Good suggestion. PR #811 adds the following to `MoltenVK_Runtime_UserGuide.md`:

>*Metal* supports a very small number (3) of concurrent swapchain images. In addition, *Metal* can
sometimes hold onto these images during surface presentation.
>
>**MoltenVK** supports using either 2 or 3 swapchain images. For best performance, it is recommended
that you use 3 swapchain images (triple-buffering), to ensure that at least one swapchain image will 
be available when you need to render to it. 
>
>Using 3 swapchain images is particularly important when rendering to a full-screen surface, because 
in that situation, *Metal* uses its *Direct to Display* feature, and avoids compositing the swapchain
image onto a separate composition surface before displaying it. Although *Direct to Display* can improve 
performance throughput, it also means that *Metal* may hold onto each swapchain image a little longer 
than when using an internal compositor, which increases the risk that a swapchain image will not be a
vailable when you request it, resulting in frame delays and visual stuttering.
