### ISSUE TITLE
Support into VCPKG done!

### ISSUE THREAD

**Issue by magicfoo** [KhronosGroup/MoltenVK#812]
Hello guys. Great job with this project. I just wanted to ping you about the support of MoltenVK by the VCPKG project. PR is pending here https://github.com/microsoft/vcpkg/pull/9575. Hoping you will enjoy it.

Note: the fetchDependencies script works without any problem. But I am wondering if exposing the logic of this script with an equivalent vcpkg cmake file (downloading and builing) could not be a better integration into vcpkg as it is atm really a black box for vcpkg. TBD

**Comment by billhollings** [comment]
Closing, since the linked MS PR was closed for lack of movement.
