### ISSUE TITLE
Vulkan SDK release feature cut-off Friday January 17

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#817]
LunarG is planning the next Vulkan SDK release in the week of Monday January 20.

MoltenVK PRs approved by Friday January 17 will be included, and a MoltenVK SDK release will be made Monday January 20.

@cdavis5e @HansKristian-Work @jeremyk-lunarg

**Comment by jeremyk-lunarg** [comment]
The glslang commit we will be using is: `4fc7a33910fb8e40b970d160e1b38ab3f67fe0f3`.
I'll get you the rest of the commits once I have them.

**Comment by jeremyk-lunarg** [comment]
Thank you for your patience.  Here are the branches and commits we will be using for this SDK.

Vulkan-Headers: `sdk-1.2.131` (branch)
Vulkan-Loader: `sdk-1.2.131` (branch)
Vulkan-ValidationLayers: `sdk-1.2.131` (branch)
KhronosGroup/Vulkan-Tools: `sdk-1.2.131` (branch)
Glslang: `4fc7a33910fb8e40b970d160e1b38ab3f67fe0f3` (commit)
LunarG/VulkanTools: `sdk-1.2.131` (branch)
VulkanSamples: `sdk-1.2.131` (branch)
SPIRV-Cross: `f9818f0804e6e73ec8afcc523b7e7f8bfc362632` (commit)
shaderc: `0f16fd2f0b94bdc174e795913b579b1433932118` (commit)

**Comment by billhollings** [comment]
@jeremyk-lunarg Thanks. Working on it now.

**Comment by billhollings** [comment]
@jeremyk-lunarg 

The [MoltenVK v1.0.40 release](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.0.40) is good to go for SDK 1.2.131.

**Comment by jeremyk-lunarg** [comment]
Thank you, @billhollings
