### ISSUE TITLE
Incorrect minStorageBufferOffsetAlignment for Metal device

### ISSUE THREAD

**Issue by BlueCocoa** [KhronosGroup/MoltenVK#829]
As shown in [this commit](https://github.com/KhronosGroup/MoltenVK/commit/79d434553c8c3737a03821a410fd2b36aee454e4#diff-f72eeb61ababb1cde30ba70249d6a0d4R1029), `_properties.limits.minStorageBufferOffsetAlignment` was changed from `_metalFeatures.mtlBufferAlignment` to a constant number `4`. 

While I was using [ncnn](https://github.com/Tencent/ncnn) with Vulkan SDK to do the image super-resolution neural network forwarding, Metal API complained that

```
validateComputeFunctionArguments:848: failed assertion `Compute Function(pooling_global_pack4_fp16s): the offset into the buffer _187 that is bound at buffer index 1 must be a multiple of 8 but was set to 8514276.'
```

which suggested that the buffer alignment should be `8` or `_metalFeatures.mtlBufferAlignment` instead of `4`, a constant value.

Indeed, it can run normally if I don't use Xcode to debug the program or turn off the `Metal API Validation`, but I have absolutely no idea about the reason that `_properties.limits.minStorageBufferOffsetAlignment` was set to a constant value `4`.

## Environment
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
Xcode Version: 11.3.1 (11C504)

**Comment by cdavis5e** [comment]
The docs say:

> For buffers in the *device* address space, align the offset to the data type consumed by the compute function (which is always less than or equal to 16 bytes).

This implies that the minimum alignment could be as low as 1... but that only applies if your buffer uses a byte-aligned data item. It looks like you're using something like `float2` or `uint2`, which has an 8-byte alignment. We should probably set it to 16, since that is the maximum alignment of something you could put in a buffer.

**Comment by billhollings** [comment]
> We should probably set it to 16, since that is the maximum alignment of something you could put in a buffer.

Done now in PR #834. 

@BlueCocoa  Please retest with latest code and close this issue if it fixes the error you encountered.

**Comment by BlueCocoa** [comment]
I've tested with the latest code and it worked as intended. Thank you very much :)
