### ISSUE TITLE
Need for a Vulkan Extension to support Metal-specific MoltenVK features

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#830]
MoltenVK provides the following optional feature enhancements:

1. Support for artifact interop between Vulkan and Metal, via functions such as `vkGet/SetMTLTextureMVK(VkImage, id<MTLTexture>*)`. A typical use of this is to extract a `MTLTexture` from CoreVideo to add to a Vulkan scene.

2. Support for passing MSL directly into `vkCreateShaderModule()` using a different Magic Number.

Since these features are not part of the Vulkan spec, they are not supported by the SDK or the Vulkan Layers, and can cause breakage when an app attempts to use these features by linking through Vulkan Layers, instead of linking directly with MoltenVK.

Adding a new Vulkan extension to the Vulkan spec that defines these features would allow these features to be standardized in a way that could be implemented by the Vulkan SDK and the Vulkan Layers library.

**Comment by billhollings** [comment]
Based on feedback and discussion with MoltenVK users and LunarG, the focus of this requirement is supporting interop between Vulkan and Metal textures and buffers, and that the most appropriate _(Vulkan-friendly)_ way to handle that is through the `VK_KHR_external_memory` family of Vulkan extensions.

With that in mind, the plans for resolving this issue are currently as follows:

1. Implement the existing Vulkan extensions: 
    - `VK_KHR_external_memory_capabilities`
    - `VK_KHR_external_memory`

2. Define a new Vulkan extension `VK_KHR_external_memory_metal` that would be similar in form to the existing `VK_KHR_external_memory_win32` and `VK_ANDROID_external_memory_android_hardware_buffer` extensions, and would allow the extraction and setting of pointers to Metal artifacts `MTLTexture`, `MTLBuffer`, and possibly `MTLDevice`.

**Comment by KarenGhavam-lunarG** [comment]
@billhollings I was wondering if you had a chance to begin the definition process for the VK_KHR_external_memory_metal extension. I believe that is the one needed to resolve the current moltenVK incompatibility with validation layers as identified in [this issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/931), correct?

**Comment by billhollings** [comment]
@KarenGhavam-lunarG 

The `VK_KHR_external_memory_metal` extension will cover accessing Metal textures and buffers.

[The issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/931) you refer to is about shading language support, and will be covered by a separate Vulkan extension (say `VK_KHR_platform_shaders`).

I am on the hook for both extensions, but have not had a chance to get to them yet. It's a high priority, though, so weeks, not months.

**Comment by DuncanHopkinsFoundry** [comment]
Your proposal for a `VK_KHR_external_memory_metal` sounds good. Is this also going to happen for `ioSurfaces`? We are already using them to share surfaces with NSView classes. Thanks.

**Comment by jerrans** [comment]
For our use case doing this would be hugely valuable as we wouldn't have to link to the MoltenVK library directly. The upshot being that accessing these features through the SDK would mean we could use the Vulkan Validation Layers.

**Comment by billhollings** [comment]
>Has the option of just adding another structure type that you can pass into vkCreateShaderModule been considered?

Not yet. But excellent option! Thanks very much for the suggestion. That could be a great way of defining `VK_KHR_platform_shaders`.

**Comment by billhollings** [comment]
Based on discussions, the first part of this, regarding passing Metal objects such as `MTLTexture` and `MTLQueue`, etc. can be done as a Metal-specific `EXT` extension to Vulkan, based on existing MoltenVK calls, rather than trying to fit into the `VK_KHR_external_memory` paradigm.

We should also include multi-planar textures, as requested in #916.

**Comment by billhollings** [comment]
`VK_EXT_metal_objects` extension MR has been submitted.

**Comment by billhollings** [comment]
Implemented with PR #1621.
