### ISSUE TITLE
Image Corruption

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#832]
I'm getting what looks like an image corruption. I was able to reproduce this in the Cube demo by adding VK_IMAGE_USAGE_SAMPLED_BIT to the depth image, using VK_IMAGE_TILING_OPTIMAL for depth and texture_object images, and allocating the depth and texture_object images with VulkanMemoryAllocator (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator). This could be a bug in VMA, but I thought I'd bring it here first. 

This does not occur when running the Cube demo on iOS. Only Mac. My MacOS is 10.15.3 with Radeon Pro 570 4 GB.

I'm testing with the latest commit bfde618. I've attached the modified cube.c. I attached vk_mem_alloc.h and vma.cpp which I add to the Cube demo project. I also attached a screenshot of the corruption I'm seeing when I run the Cube demo.

In my own similar demo it seems like the corruption happens when I begin/end the related renderpass. If I submit the command buffer with just the begin and end of the renderpass, with nothing in between, and afterwards transfer the texture_object image to a file I can view, then it will be corrupted.

[Archive.zip](https://github.com/KhronosGroup/MoltenVK/files/4277974/Archive.zip)

**Comment by billhollings** [comment]
Thanks for submitting the sample app demonstrating the issue. The error appears in my environment too.

I've done a fair bit of digging into it. The error is triggered by a long combination of things:

1. VMA uses a single large underlying `VkDeviceMemory` to bind to both the depth image and the samplable texture being loaded from file (via a buffer copy). The native Cube demo uses separate device memory instances. Changing back fixes this issue.

2. MoltenVK uses a placement `MTLHeap` within the device memory to create the underlying `MTLTextures` for each image. Configuring MoltenVK to avoid using `MTLHeaps` also fixes this issue.

3. The issue only appears if the the depth image includes samplable `usage`. Changing this back also fixes the issue.

There doesn't seem to be a clear reason why this is happening. I've verified that VMA is picking byte offsets and alignments for the `MTLTextures` that should avoid conflicts within the placement `MTLHeap` memory space. And it's hard to see why modifying the `usage` property should naturally have any effect on where in the heap the memory is allocated from.

At this point, I'm suspecting a possible bug within the Metal driver that triggers a layout conflict inside the placement `MTLHeap` when using samplable depth images.

I don't know if we can do much of anything about this within MoltenVK, other than to possibly provide an environment variable to optionally allow an application to disable `MTLHeaps` if they encounter this issue.

**Comment by billhollings** [comment]
@DiegoAce PR #845 fixes this issue. Please retest and close this issue if it fixes the problem you encountered.

**Comment by DiegoAce** [comment]
I'm not getting the corruption anymore relating to the conditions above. Thanks! I'll close the issue. Although, I'm still getting an identical looking corruption in another part of my project that I thought was related to this, but perhaps it's not. It's not a critical part of my project and I fear tracking it down will be difficult. So I may not do so, but if I do I'll re-open this issue.
