### ISSUE TITLE
vkQueueSubmit frozen when the commad buffer contains vkCmdCopyImage

### ISSUE THREAD

**Issue by Graou74** [KhronosGroup/MoltenVK#835]
Hello,

I wanted to integrate the image copy based on the example of Sascha Willems screenshot.cpp. I use LWJGL version 3.2.3 as my code is in java, MacOs 10.15.2, Vulkan 1.1.130.0 and a Radeon Pro 580 8 GB graphics card.

The copy freezes the application when the format of VkImageCreateInfo (destination image) is VK_FORMAT_R8G8B8A8_UNORM (correct value). And if we pass this value to VK_FORMAT_B8G8R8A8_UNORM (incorrect value), the copy no longer freezes but the destination image contains only zeros.

Exactly the same code on PC gives the expected result (copying the source image into the destination image). I deduce that the problem is on the Mac side.

I made a post on https://community.khronos.org/ which has the same title as this one.

Optionally, I can provide the Eclipse Gradle project which was used to test on Mac and PC.

**Comment by billhollings** [comment]
@Graou74 This is fixed in PR #850. Please retest and close this issue if if fixes the problem you encountered.
