### ISSUE TITLE
Is the use of vkCmdCopyImage supported on MacOs

### ISSUE THREAD

**Issue by Graou74** [KhronosGroup/MoltenVK#838]
I have already opened a [first post](https://github.com/KhronosGroup/MoltenVK/issues/835) which describes the problem.

So I tried to copy an image from the swapchain with vkCmdCopyImage() then with vkCmdCopyImageToBuffer() but without success on MacOs. However on PC, the same code works.

Is this a Vulkan limitation on MacOs?
If not it's because I'm doing it wrong and how to correct it?
If yes, is there an alternative knowing that I would also need images rendered offscreen?

Image recovery is an essential feature in my application. If it is not possible, the choice of Vulkan becomes seriously compromised.

**Comment by billhollings** [comment]
@Graou74 This is fixed in PR #850. Please retest and close this issue if if fixes the problem you encountered.
