### ISSUE TITLE
Build Failure: Please Update SPIRV-Tools (and other) Submodules

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/MoltenVK#84]
The `brew` package manager for macOS recently changed the way it configures Python so that Python 3 is now the default.

This had the odd consequence of not being able to build SPIRV-Tools at the current submodule [commit](https://github.com/KhronosGroup/SPIRV-Tools/tree/1acce99255ee28a582776372593e91b585d3c011)   due to a Python script that had a mix of tabs and spaces in it.  Python 3 is less tolerant of this than Python 2.

The problem with the Python script was fixed with this [commit](https://github.com/KhronosGroup/SPIRV-Tools/commit/b185a3d808759add903d82e50a7ff3fd64227c67#diff-d07b0ddc717d188e2da6b3342256a34c).

So we need the MVK repo to point to the SPIRV-Tools submodule at that commit or later.

It would probably be good to review the other submodules as well.

**Comment by oscarbg** [comment]
also please update SPIR-V Cross also up to https://github.com/KhronosGroup/SPIRV-Cross/commit/15a941cd3dcefbd003a98e460610809982220529
this fixes a vkquake shader error with same name used in variable and function..

**Comment by karl-lunarg** [comment]
Bump

**Comment by karl-lunarg** [comment]
The "workaround" for this is to fix the SPIRV-Tools file  `utils/generate_grammar_tables.py`.   At SPIRV-Tools @ 1acce99, this file has a mixture of tabs and spaces, which Python 3 does not tolerate.  This problem is fixed with a later revision of SPIRV-Tools, but this repo points at an earlier version.

To work around the problem with this revision, convert the tabs to spaces in this file.

**Comment by irobertmanley** [comment]
Confirmed Karl.  Thanks.

**Comment by billhollings** [comment]
@karl-lunarg

PR #98 changes the way that external libraries are fetched and built, and should fix this issue.

The `glslang` version is now derived from `V-LVL`...and `SPRIV-Tools` and `SPIRV-Headers` are now fetched by `glslang`

In addition...when MoltenVk is being built as a component of `V-LVL`, the `fetchDependencies` script can be called with a `-sdk` argument that will cause it to symlink to the `V-LVL` and `glslang` directories within the parent `V-LVL`. 

The Vulkan header files used by MoltenVK are now derived from those in `V-LVL` too.

Please verify with the latest version of MoltenVK.

@oscarbg

`SPIRV-Cross` has been updated in PR #98 too.

**Comment by karl-lunarg** [comment]
I'll verify on March 16th.

I may have some suggestions for an alternative to the `-sdk` argument.   One wouldn't use this only for SDK construction.  Rather, it would be used anytime someone was building `V-LVL`, whether it was for an SDK or not.   In any case, I'll make a PR if I see the need.
