### ISSUE TITLE
Xcode 11.4 Toolchain MoltenVK.framework: No such file

### ISSUE THREAD

**Issue by Exey** [KhronosGroup/MoltenVK#847]
After made all instructions on `sudo make install` got a

> /bin/cp -a Package/Latest/MoltenVK/macOS/framework/MoltenVK.framework /Library/Frameworks/
cp: Package/Latest/MoltenVK/macOS/framework/MoltenVK.framework: No such file or directory
make: *** [install] Error 1

macOS 10.15.3
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by billhollings** [comment]
@Exey 

I'm not seeing this behaviour. 

For some reason, `sudo make install` is not finding your MoltenVK framework. 

Before running `sudo make install`, did you run `make macoS`, or `make all`, or build MoltenVK using _Xcode_?
