### ISSUE TITLE
Successfully creates instances for API version higher than VK_API_VERSION_1_0 

### ISSUE THREAD

**Issue by Mumsfilibaba** [KhronosGroup/MoltenVK#848]
I can successfully create an instance with API version VK_API_VERSION_1_2 (Have not tried VK_API_VERSION_1_1 yet), and if I understand things correctly this creates a Vulkan instance of version Vulkan 1.2. But since not all features of 1.2 are available (neither 1.1 if I have done my research right), should not this call fail when I create an instance of a higher version than 1.0? Since technically MoltenVK does not support higher versions.

So if I pass a higher version than VK_API_VERSION_1_0 to VkApplicationCreateInfo, should not the call to vkCreateInstance fail?

**Comment by billhollings** [comment]
If I modify the Cube demo to set `VkApplicationInfo::apiVersion` to `VK_API_VERSION_1_2` for `vkCreateInstance()`, MoltenVK returns `VK_ERROR_INCOMPATIBLE_DRIVER`, and logs the following error:

    [mvk-error] VK_ERROR_INCOMPATIBLE_DRIVER: Request for Vulkan version 1.2.0 is not compatible with supported version 1.0.135.

The Cube app detects the error and shuts down.

MoltenVK seems to be operating as defined by the spec and as you expected. If you are not getting the same results, can you review how `vkCreateInstance()` is being handled in the Cube demo and clarify where your app is doing something different and where MoltenVK is not behaving as expected?

**Comment by cdavis5e** [comment]
Are you using the Vulkan loader? Even though MoltenVK only supports 1.0, the Vulkan loader lets you create 1.1 and 1.2 instances.

**Comment by Mumsfilibaba** [comment]
Ok so sorry for taking so long to respond, there has been a lot of other stuff.

So I think we use the loader since we link with the Vulkan libraries and not MoltenVK directly. 

So I read up on the docs and even tho the instance creation works, should not device creation fail? Since there are no device that can support 1.2, since MoltenVK itself does not support 1.2?

```
VkApplicationInfo appInfo = {};
appInfo.sType               = VK_STRUCTURE_TYPE_APPLICATION_INFO;
appInfo.pNext               = nullptr;
appInfo.pApplicationName    = "Lambda Engine";
appInfo.applicationVersion  = VK_MAKE_VERSION(1, 0, 0);
appInfo.pEngineName         = "Lambda Engine";
appInfo.engineVersion       = VK_MAKE_VERSION(1, 0, 0);
appInfo.apiVersion          = VK_API_VERSION_1_2;

VkInstanceCreateInfo instanceCreateInfo = {};
instanceCreateInfo.sType                    = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
instanceCreateInfo.pApplicationInfo         = &appInfo;
instanceCreateInfo.enabledExtensionCount    = (uint32_t)m_EnabledInstanceExtensions.size();
instanceCreateInfo.ppEnabledExtensionNames  = m_EnabledInstanceExtensions.data();

VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo = {};
if (desc.Debug)
{
	PopulateDebugMessengerCreateInfo(debugCreateInfo);

	instanceCreateInfo.enabledLayerCount    = (uint32_t)m_EnabledValidationLayers.size();
	instanceCreateInfo.ppEnabledLayerNames  = m_EnabledValidationLayers.data();
	instanceCreateInfo.pNext                = &debugCreateInfo;
}
else
{
	instanceCreateInfo.enabledLayerCount    = 0;
	instanceCreateInfo.pNext                = nullptr;
}

VkResult result = vkCreateInstance(&instanceCreateInfo, nullptr, &Instance);
if (result != VK_SUCCESS)
{
	LOG_VULKAN_ERROR(result, "[GraphicsDeviceVK]: Failed to create Vulkan Instance!");
	return false;
}
```

**Comment by billhollings** [comment]
>So I read up on the docs and even tho the instance creation works, should not device creation fail? 

Can you clarify where in the spec you are reading this? From my reading, the spec talks about the validation layers testing for physical device API usage, but it does not indicate that an implementation needs to run these tests.

The implementation indicates to the app the highest Vulkan API version supported by each physical device via `vkGetPhysicalDeviceProperties()`, and it is then the app's responsibility to respect that (maybe with some validation layer support), but I don't see that the spec indicates the implementation needs to validate any further. 

The `vkCreateDevice()` call does not contain any API info, so it's not clear at that point that the app might try to use API functionality that is not supported by the device.

**Comment by Mumsfilibaba** [comment]
I must have misinterpreted the spec. Read up a bit more and I cannot find the part I was thinking about. 

Closing the issue now.
