### ISSUE TITLE
vkQueuePresentKHR ignoring pResults of VkPresentInfoKHR

### ISSUE THREAD

**Issue by pmuetschard** [KhronosGroup/MoltenVK#857]
According to the spec: "If non-NULL, each entry in pResults will be set to the VkResult for presenting the swapchain corresponding to the same index in pSwapchains."

However, it appears that MoltenVK does not update the values in pResults.

**Comment by billhollings** [comment]
@pmuetschard PR #860 fixes this. Please retest and close this issue if the problem you encountered is fixed.
