### ISSUE TITLE
MoltenVK (or Metal) supports half floats on desktop profile? (vulkan_minimal_compute works ok but not with minor modifications for fp16 usage)

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/MoltenVK#86]
Hi,
testing this simple compute Mandelbrot sample:
https://github.com/Erkaman/vulkan_minimal_compute
works ok with the default shader..
i.e. loads comp.spv from shader folder and generates as result of running compute shader  a png as output showing Mandelbrot fractal..
I changed minimally the shader computation to use float16 ops:
```
#extension GL_AMD_gpu_shader_half_float: enable
#define vec2 f16vec2
```
as main computation is done in vec2 variables..
regenerated SPIR-V comp.spv as glslangValidator supports f16vec2 using when using GL_AMD_gpu_shader_half_float..
generated SPIR-V looks good, has things like:
```
           OpCapability Float16
               OpExtension "SPV_AMD_gpu_shader_half_float"
               %half = OpTypeFloat 16
               %v2half = OpTypeVector %half 2
               %92 = OpLoad %half %91
                %93 = OpFMul %half %90 %92
                %94 = OpFSub %half %88 %93.
                OpFAdd %v2half %105 %106
```
assuming Metal shader output that gets used by MoltenVK is similar to SPIRV-Cross I get good looking code ( in the sense that original vec2 operations are now half2 ops):
`spirv-cross comp.spv --msl:`
```
    float x = float(gl_GlobalInvocationID.x) / 3840.0;
    float y = float(gl_GlobalInvocationID.y) / 2160.0;
    half2 uv = half2(half(x), half(y));
    float n = 0.0;
    half2 c = half2(6.5690069410618774650762595405465e-41, 0.0) + (half2(float2(uv) - float2(0.5)) * half2(2.3202699972290321060355114440114e-41));
    half2 z = half2(0.0);
    for (int i = 0; i < 128; i++)
    {
        z = half2((z.x * z.x) - (z.y * z.y), half((2.0 * float(z.x)) * float(z.y))) + c;
        if (float(dot(z, z)) > 2.0)
        {
            break;
        }
        n += 1.0;
    }

```
I'm running the program with standard val debug layers enabled..

for whatever reason need to use 

> VK_LAYER_PATH=/etc/vulkan/explicit_layers.d ./vulkan_minimal_compute

 to find the layers..

Debug Report: SC: SPIR-V module not valid: Using a 16-bit floating point type requires the Float16 or Float16Buffer capability, or an extension that explicitly enables 16-bit floating point.

but we should not look it carefully as running spirv-val  comp.spv on that modified 16bit SPIR-V returns no errors..
and seems there were float16 related bugs up to very recently on SPIRV-Tools:
https://github.com/KhronosGroup/SPIRV-Tools/issues/1375
https://github.com/KhronosGroup/SPIRV-Tools/issues/1376
so asking two things:
1) are halfs generated by SPIRV-Cross and compiled by Metal Shader compiler supported on MacOS
desktop or are only for mobile? note I'm checking on a RX Vega that has native fp16 support..
2) MoltenVK has to fix something to support half support?

**Comment by billhollings** [comment]
@oscarbg 

Halfs should work on both macOS and iOS.

Can you clarify what the error is, please?

You seem to indicate a validation error of some sort:

    Debug Report: SC: SPIR-V module not valid: Using a 16-bit floating point type requires the Float16 or Float16Buffer capability, or an extension that explicitly enables 16-bit floating point.

That does not originate in MoltenVK or Metal.

When is that error occurring? Does it happen during the creation of your SPIR-V? Or is it coming from a Vulkan SDK validation layer that you have enabled at runtime?

And is that validation the main issue? Or is something else going wrong somewhere?

**Comment by karl-lunarg** [comment]
> for whatever reason need to use
> 
> VK_LAYER_PATH=/etc/vulkan/explicit_layers.d ./vulkan_minimal_compute
> 
> to find the layers..

This was a typo-level bug in the SDK and the SDK documentation.  The correct name for the directory is:

```
/etc/vulkan/explicit_layer.d
```

(No 's' in layers)

It looks like you copied this `explicit_layers.d` directory from the SDK into `/etc/vulkan`.
All you have to do is rename `/etc/vulkan/explicit_layers.d` to `/etc/vulkan/explicit_layer.d` and the Vulkan loader should find the layers without the need to specify `VK_LAYER_PATH`.
(The loader is behaving correctly.  But the directory in the SDK and the SDK docs used the wrong name.)

This has already been corrected for the next SDK release.

---

The Debug Report message is coming from the Shader Checker portion of the Vulkan validation layers.

**Comment by billhollings** [comment]
@oscarbg 

Should this issue still be open?

If so...can you answer the questions in my earlier response, please?

**Comment by oscarbg** [comment]
@billhollings 
allow me till end of week to retest and share what I find..

**Comment by billhollings** [comment]
@oscarbg 

Glad its working for you. Thanks for closing.

Regarding your question...I have no knowledge of what the individual GPU's will do internally. Certainly I would expect it would be transparent to any interactions (reads/writes) with buffers and textures.
