### ISSUE TITLE
Code signature invalid for libMoltenVK.dylib

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/MoltenVK#871]
Hello!
I have always used dynamic version of MoltenVK library by following the instructions in the guide: adding copy files phase, code signing it, etc. This worked just fine until I updated XCode to 11 (Version 11.4.1 (11E503a)). Now when I start the app I get this error:

```
dyld: Library not loaded: @rpath/libMoltenVK.dylib
  Referenced from: /private/var/containers/Bundle/Application/C370AE01-1CC4-4FDF-8B44-6C712E74648B/Tutorial05_TextureArray.app/Tutorial05_TextureArray
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/C370AE01-1CC4-4FDF-8B44-6C712E74648B/Tutorial05_TextureArray.app/libMoltenVK.dylib: code signature invalid for '/private/var/containers/Bundle/Application/C370AE01-1CC4-4FDF-8B44-6C712E74648B/Tutorial05_TextureArray.app/libMoltenVK.dylib'
```

I followed the history for MoltenVK_Runtime_UserGuide.md and found that there are new instructions for configuring runpath search paths, but it appears that the loader is able to find dylib, it just doesn't like the signature. The Code Sign on Copy checkbox is checked, and I follow the exact same steps like before. 

Could you suggest what may be the problem? 

Here is the [link to the app](https://www.dropbox.com/s/31lzo83we8blo5u/Tutorial05_TextureArray.zip?dl=0).

SDK Version: 1.2.135.0

**Comment by mbechard** [comment]
I'm running into the same issue. If I compile MoltenVK myself things work fine, but I'd like to avoid doing that and just use the SDK download.

**Comment by mbechard** [comment]
Seems like it works in 1.2.141.2. This thread seems to imply it should have worked in 1.2.135.0 though:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiqi6CMnNDqAhWNhXIEHXfaDnQQFjABegQIAhAB&url=https%3A%2F%2Fvulkan.lunarg.com%2Fissue%2Fview%2F5d9b73d786da81451cc37e7b&usg=AOvVaw01vuFkdsbKyOBhwxdTHFiT

**Comment by billhollings** [comment]
>Seems like it works in 1.2.141.2.

Is this working now, based on LunarG's fixes to the SDK build process for MoltenVK included in the SDK?

**Comment by Clevergua** [comment]
Same issue in 1.3.296

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/908560c5-69e1-4440-9fa3-a1abd2df6e4c" />

**Comment by richard-lunarg** [comment]
What version of XCode/macOS is this happening on?

**Comment by Clevergua** [comment]
> What version of XCode/macOS is this happening on?

<img width="304" alt="Image" src="https://github.com/user-attachments/assets/4cd7588a-89d3-4487-b563-f6d0b705200a" />
16.2

<img width="473" alt="Image" src="https://github.com/user-attachments/assets/3fa5b88e-2f06-4a3c-ae4c-ccf6aeb706b0" />
15.1

🥹 libvulkan.1.dylib & libvulkan.1.3.296.dylib also have issue..
'/Users/forgemastergua/Library/Developer/Xcode/DerivedData/osx-cskqkmhufzamjycmcupwrxicqtlb/Build/Products/Debug/osx.app/Contents/Frameworks/libvulkan.1.dylib' (code signature invalid in <D11BBCC9-A7E9-32A1-927D-21E2164D4130> '/Users/forgemastergua/Library/Developer/Xcode/DerivedData/osx-cskqkmhufzamjycmcupwrxicqtlb/Build/Products/Debug/osx.app/Contents/Frameworks/libvulkan.1.dylib' (errno=1) sliceOffset=0x0009C000, codeBlobOffset=0x000933A0, codeBlobSize=0x00005A70), '/Users/forgemastergua/Library/Developer/Xcode/DerivedData/osx-cskqkmhufzamjycmcupwrxicqtlb/Build/Products/Debug/osx.app/Contents/Frameworks/libvulkan.1.dylib' (code signature invalid in <D11BBCC9-A7E9-32A1-927D-21E2164D4130> '/Users/forgemastergua/Library/Developer/Xcode/DerivedData/osx-cskqkmhufzamjycmcupwrxicqtlb/Build/Products/Debug/osx.app/Contents/Frameworks/libvulkan.1.dylib' (errno=1) sliceOffset=0x0009C000, codeBlobOffset=0x000933A0, codeBlobSize=0x00005A70)

**Comment by Clevergua** [comment]
> What version of XCode/macOS is this happening on?

![Image](https://github.com/user-attachments/assets/cef8f92c-c3c9-4e25-9b58-538f743812fb)

I found that the Hardened Runtime caused the default Xcode app project issue. The bug was resolved after either removing it or disabling the dylib validation. thanks for your attention.
