### ISSUE TITLE
VK_KHR_sampler_ycbcr_conversion

### ISSUE THREAD

**Issue by Lichtso** [KhronosGroup/MoltenVK#873]
I started implementing the extension:
https://github.com/Lichtso/MoltenVK/commits/VK_KHR_sampler_ycbcr_conversion

But, one problem remains: As far as I can tell, the complementary part on the SPIRV-Cross side expects one texture descriptor per image plane (https://github.com/KhronosGroup/SPIRV-Cross/blob/39dce88d3b10485be380c5437fb7ecddbeafcd62/spirv_msl.cpp#L8660).
The extension requires multiple memory bindings inside one MVKImage for disjoint images and also representing them as sub resources when a linear layout is requested.

So far I could not come up with a nice solution and would like some input on how to approach modelling this.

**Comment by cdavis5e** [comment]
`IOSurface` supports planar formats like the ones provided by `VK_KHR_sampler_ycbcr_conversion`. When I added the support for this to SPIRV-Cross, I envisioned using an `IOSurface` for the image memory; then I would create a `MTLTexture` for each plane.

**Comment by Lichtso** [comment]
Ok, I implemented and refactored quite a lot, but here we are. While doing so I noticed some issues and wrote down questions:

- MVKImagePlane::initSubresources multi planar images in linear layout have the offsets of the previous planes subresources added to the next if the image is not disjoint. Is that correct?
- vkSetMTLTextureMVK and vkGetMTLTextureMVK have no way to specify the plane of a multi planar image. Should we add a planeIndex argument or VkImageAspectFlags?
- MVKCmdResolveImage::encode Am I right that we don't need to take care of multi planar images here as they are not supported as render targets anyway?
- MVKDescriptorSetLayoutBinding::push Is the user responsible for binding a separate image view to each plane of a sampled texture, so that we don't need to handle the descriptors of multi planar images here?

Fields which are currently ignored (is this correct or do we need to handle them?):
- VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR can be added to VkImageViewCreateInfo
- VkSamplerYcbcrConversionCreateInfo has a forceExplicitReconstruction flag
- MVKImage::getMTLStorageMode and MVKImage::getMTLCPUCacheMode use only the first memory binding (ignore other bindings of disjoint multi planar images)

Additionally, there is the question, when to use what (texel buffers, IOSurfaces, ImageViews, etc.) e.g. MVKImageMemoryBinding::bindDeviceMemory checks for uncompressed images but should it also take chroma subsampling into account? There are many of such small details left to decide.

**Comment by billhollings** [comment]
@Lichtso Following up on your comments above...does PR #909 address everything relevant here? If so...can you close this issue, please? If not...please highlight what is outstanding (or better yet...close this and open a separate follow-up Issue).

**Comment by Lichtso** [comment]
I tested it by replacing the image format in a texture example and changing the memoryRequirements, bindings and transfers to be multi planar. It seem to work as I can change the colors of the output by swapping the image planes. I also tested all bit depths (8, 10, 12, 16) but I haven't tested every format combination.
