### ISSUE TITLE
VK_EXT_private_data support

### ISSUE THREAD

**Issue by Mumsfilibaba** [KhronosGroup/MoltenVK#877]
Would it be possible to support VK_EXT_private_data in MoltenVK?

**Comment by billhollings** [comment]
Shouldn't be a problem. We'll put it on the enhancement list.

**Comment by oscarbg** [comment]
@Mumsfilibaba just curious what’s this ext can be useful for? can share some use case..

**Comment by billhollings** [comment]
@Mumsfilibaba This is implemented in PR #1097. Please evaluate and close this issue if it meets your requirements.
