### ISSUE TITLE
Update Vulkan header and spec to v1.1

### ISSUE THREAD

**Issue by billhollings** [KhronosGroup/MoltenVK#88]
With the release of Vulkan 1.1 specification, MoltenVK should support building with the Vulkan 1.1 headers.

**Comment by billhollings** [comment]
@karl-lunarg

PR #98 changes the way that external libraries are fetched and built, and should fix this issue.

The Vulkan header files used by MoltenVK are now derived from those in `V-LVL`.

So...MoltenVK is now structured to move to using the Vulkan 1.1 headers via `V-LVL` exposes them.

How can we make that happen?

**Comment by karl-lunarg** [comment]
@billhollings The `V-LVL` repo was updated to use the Vulkan 1.1 headers last week on March 9.  And you have already specified the revision 6d3938 for that repo, which is after the commit that moved the headers to 1.1.  So the change has already been made.

I've been out for the past week, but I will checkout #98 closely on March 16 and make sure that everything looks good from my end.

Please let me review and I will update this issue with any needed actions or if things look OK.

**Comment by billhollings** [comment]
Included in PR #98.
