### ISSUE TITLE
Framebuffer layer limit

### ISSUE THREAD

**Issue by js6i** [KhronosGroup/MoltenVK#899]
What is the source of max framebuffer layers limit?
https://github.com/KhronosGroup/MoltenVK/blob/064a45b6a0ebec55bd914bb4df1b37363d835ea0/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L1238
I could not find it in Metal Feature Set Tables, should not it be the same as maxImageArrayLayers (2048)?

**Comment by billhollings** [comment]
>should not it be the same as `maxImageArrayLayers` 

Sounds reasonable. 

@cdavis5e Any reason why `maxFramebufferLayers` was set differently?

**Comment by cdavis5e** [comment]
No. That was how I found it. It used to be hardcoded to 256 before I made it conditional on that feature.

**Comment by billhollings** [comment]
Okay. I'll fix it.

**Comment by billhollings** [comment]
@js6i PR #901 includes a fix for this. Please retest and close this issue if it is fixed.

**Comment by js6i** [comment]
Seems good, thanks!
