### ISSUE TITLE
MVKBufferView::getMTLTexture(): MTLTextureDescriptor has width (786432) greater than the maximum allowed size of 16384

### ISSUE THREAD

**Issue by eintw1ck** [KhronosGroup/MoltenVK#90]
'Large' textures aren't loaded as throws an exception for height/widths above 16384.
https://github.com/KhronosGroup/MoltenVK/blob/93c524d2f05d7a7f983354b8e53cd4e6812708c7/MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm#L210-L216

My texture is a 512x512 pixel texture (RGB8), so a width of 786432 makes sense (`512*512*3`) if you have a height of 1. Is the intended behavior? (see below):
https://github.com/KhronosGroup/MoltenVK/blob/93c524d2f05d7a7f983354b8e53cd4e6812708c7/MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm#L232-L239

How can I load textures where `height*width` is greater than 16384?

Sorry if it's obvious, I'm new to Vulkan, able to try it out because of MoltenVK being open-source (which is awesome!).

**Comment by haasn** [comment]
Just popping in here to point out that this is not the 2D texture itself, but the uniform texel buffer that we use to upload *to* the 512x512 texture.

There are two bugs here:
1. You shouldn't use 1D textures to simulate texel buffers if their size is very limited. Instead, try and use 2D textures and translate the coordinates.

2. Even if you use 1D textures, you should correctly set `VkPhysicalDeviceLimits.maxTexelBufferElements` to 16384 in this case.

**Comment by billhollings** [comment]
Fixed in PR #187. Please retest and close.

**Comment by billhollings** [comment]
Closing as fixed.
