### ISSUE TITLE
Headless rendering produces black images

### ISSUE THREAD

**Issue by Bam4d** [KhronosGroup/MoltenVK#908]
I've been struggling to get headless rendering working on macos for a while now. The issue I have is that the vkCmdCopyImage function does one of two things in the following scenarios (which i discovered while fiddling around trying to get things working: 

1) Only copies black invisible pixels
 - this happens when copying from an image that does not have VK_MEMORY_HOST_CACHED_BIT set on the image being copied
2) The value 0xB (\v)
 - this happens if the VK_MEMORY_HOST_CACHED_BIT is set on the image being copied

I thought that this would be fixed with the resolution these issues #838 #835, however I've updated to the latest vulkan sdk (1.2.141.0) which includes mvk 1.0.41 and the problem still persists.

I'm not doing anything fancy with vulkan other than rendering very simple sprite tiles or coloured shapes. 

I would note that I'm using push constants in my shader stage (which I think have limited support in MVK?). Either way, even if I set the clear colour to pure red my images are still just black, so i don't think its a shader issue.

I have two test suites that run completely fine on both linux and windows that render some images and compare them against some pre-rendered images. On macOS everything else compiles and test asserts are all fine apart from the blank images. The frame rate is still comparable to windows/linux so its doing *something* and I'm getting no errors from the standard validation layers other than complaints about vkDestroyDevice when the program exits. (Not sure if there's other debugging tools I should be trying to use?)

To reproduce:
The project is fairly simple + open source and can be found here:
https://github.com/Bam4d/Griddly
The build instructions are straightforward and there's no external dependencies (Other than running `git submodule init && git submodule update`)

To build (5 mins build) just the tests and run them:
`cmake .`
`cmake --build . --target Griddly_Test`

`ctest . --verbose` will show all the tests failing with blank images
OR
`./Debug/bin/Griddly_Test --gtest_filter="BlockObserverTest.defaultObserverConfig"` (to run a single on of the failing render tests)

Thanks for your help in advance!

**Comment by billhollings** [comment]
Thanks for submitting the test cases. I'll have a look as soon as I can. It might be a few days.

**Comment by billhollings** [comment]
@Bam4d 

I'm having trouble running the sample.

In the output from `cmake .`, I see:

```
-- Found Vulkan: /usr/local/lib/libvulkan.dylib
CMake Error at CMakeLists.txt:80 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "/Users/...../Griddly/CMakeFiles/CMakeOutput.log".
```

And then when running `cmake --build . --target Griddly_Test`, I see:

     make: *** No rule to make target `Griddly_Test'.  Stop.

Just running `cmake --build .` gets no further.

I attempted to linking to MoltenVK without doing a formal Vulkan install (my preferred way of running it, so I can swap out debug MoltenVK libraries), but I got:

```
CMake Error at /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindVulkan.cmake:71 (find_package_handle_standard_args)
  CMakeLists.txt:50 (find_package)
```

**Comment by Bam4d** [comment]
Thanks for your reply.

Did you run `git submodule init` and `git submodule update` ? The pybind11 modules are part of a git submodule so it looks like they might not be available.

As for the vulkan linking... I believe that cmake tries to find vulkan by looking for the VULKAN_SDK environmental variable. 

The *find vulkan* module is provided by cmake: 
## Docs
https://cmake.org/cmake/help/latest/module/FindVulkan.html
## Code:
https://github.com/Kitware/CMake/blob/master/Modules/FindVulkan.cmake

The way I install vulkan_sdk on macOS at the moment is to use the provided `./install_vulkan.py` script. So I guess in there it is setting the environmental variable?

**Comment by billhollings** [comment]
>Did you run git submodule init and git submodule update?

Yes...it turned out that those were failing due to lack of `ssh` permissions. Changing your `.gitmodules` to use http allowed me to proceed.

PR #926 fixes an issue in macOS where host coherent memory was not being copied back to a long-standing open host-coherent memory mapping.

With that fix in place...to get your tests to pass...in your code I had to change your use of `VK_MEMORY_HOST_CACHED_BIT` to `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`, since you weren't using `vkInvalidateMappedMemoryRanges()`, which the Vulkan spec requires the use of to sync host memory if you are not using host-coherency:

>`VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` bit specifies that the host cache management commands `vkFlushMappedMemoryRanges` and `vkInvalidateMappedMemoryRanges` are not needed to flush host writes to the device or make device writes visible to the host, respectively.

A few of your tests are still failing, but they don't seem to be related directly to this issue. Can you test, and if the host-update after copy issue is fixed, please close this issue.

**Comment by Bam4d** [comment]
Is there a tutorial/instructions anywhere to build against the fix you have here? I'm using the setup provided with the sdk so not sure how to swap in the "fixed" code? Is there a set of .dylib artifacts anywhere i can just swap or do I have to build them locally?

Thanks

**Comment by billhollings** [comment]
>Is there a tutorial/instructions anywhere to build against the fix you have here?

You can easily swap a fresh build of MoltenVK into the SDK:
1. Clone this repository.
2. Follow the instructions in `README.md` to build the MoltenVK binaries.
3. Do either one or the other of the following:
    - Replace `vulkansdk/macOS/lib/libMoltenVK.dylib` in the SDK install location with `Package/Latest/MoltenVK/macOS/dynamic/libMoltenVK.dylib` from the MoltenVK repo
    - Modify the `VK_ICD_FILENAMES` build setting of your app to point to `Package/Latest/MoltenVK/macOS/dynamic/MoltenVK_icd.json`in the MoltenVK repo.

**Comment by Bam4d** [comment]
Hi @billhollings Thanks very much for the info on how to test.

I've got this working and the images are being produced correct in *most* cases.

I think there is a potential synchronization issue with the memory read or write however because I have random test failures where the images have artifacts or are still completely black. In most cases they are fine. but running the test suites, random tests will fail with these issues.

You mentioned that there were some test failures that were not directly related? Are these the issues you are seeing also?

Would you prefer I create a new ticket with the issues and close this one as it's *mostly* working?

**Comment by billhollings** [comment]
>You mentioned that there were some test failures that were not directly related? Are these the issues you are seeing also?

I just noticed 4 or 5 tests in your suite were still failing. But I didn't run it more than once, so I didn't notice whether they were race conditions or not.

>Would you prefer I create a new ticket with the issues and close this one as it's mostly working?

Yeah...based on your description, they don't seem directly related. If you can close this and open another ticket that is focused on what is currently going wrong, that would be best.

**Comment by Bam4d** [comment]
OK cool will close and re-open another ticket.
