### ISSUE TITLE
Calling `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` triggers Objective C error

### ISSUE THREAD

**Issue by OliverBalfour** [KhronosGroup/MoltenVK#920]
Hi, I am having some issues with a Vulkan function triggering an Objective C error.

My code queries for swap chain capabilities in the following snippet. I am trying to access the `currentExtent` struct inside the `VkSurfaceCapabilitiesKHR` object.

```cpp
// instance, physicalDevice, metalSurface are initialised. logicalDevice is not yet initialised.
VkSurfaceCapabilitiesKHR surfaceCapabilities;
std::vector<VkSurfaceFormatKHR> surfaceFormats;

vkGetPhysicalDeviceSurfaceCapabilitiesKHR(physicalDevice, metalSurface, &surfaceCapabilities);

uint32_t numFormats;
vkGetPhysicalDeviceSurfaceFormatsKHR(physicalDevice, metalSurface, &numFormats, nullptr);
if (numFormats) {
    surfaceFormats.resize(numFormats);
    vkGetPhysicalDeviceSurfaceFormatsKHR(physicalDevice, metalSurface, &numFormats, surfaceFormats.data());
}
```

However for some reason the `vkGetPhysicalDeviceSurfaceCapabilitiesKHR ` call produces the following error, but when it is commented out the `vkGetPhysicalDeviceSurfaceFormatsKHR ` call works as expected.

```
2020-06-13 19:11:48.957138+1000 VulkanExperimentation[1512:56079] -[_NSViewBackingLayer naturalDrawableSizeMVK]: unrecognized selector sent to instance 0x600000c5d5f0
2020-06-13 19:11:48.957297+1000 VulkanExperimentation[1512:56079] Failed to set (contentViewController) user defined inspected property on (NSWindow): -[_NSViewBackingLayer naturalDrawableSizeMVK]: unrecognized selector sent to instance 0x600000c5d5f0
```

Similarly, when I run the following after simply commenting out the failing line above, a similar message comes up.
```cpp
vkCreateSwapchainKHR(logicalDevice, &createInfo, nullptr, &swapChain);
```

```
2020-06-13 20:47:24.897935+1000 VulkanExperimentation[2482:100730] -[_NSViewBackingLayer setDevice:]: unrecognized selector sent to instance 0x600000c7e2e0
2020-06-13 20:47:24.898175+1000 VulkanExperimentation[2482:100730] Failed to set (contentViewController) user defined inspected property on (NSWindow): -[_NSViewBackingLayer setDevice:]: unrecognized selector sent to instance 0x600000c7e2e0
```

I am on MacOSX 10.15.3 with MoltenVK 1.0.41 dynamically linked. My code adds the `VK_KHR_surface v25` and `VK_EXT_metal_surface v1` instance extensions and the `VK_KHR_swapchain` device extension when it creates the logical device.

I have looked at the cube demo which uses function pointers for the surface capabilities call, but replacing the function pointer with a standard function call does not trigger the above error in that project for some reason.

I feel like I have made an elementary mistake somewhere as I am relatively new to C++ and macOS development, but I am at a loss as to what is causing these issues. Any help would be much appreciated.

**Comment by cdavis5e** [comment]
What kind of layer did you pass to `vkCreateMetalSurfaceEXT()`? It has to be a `CAMetalLayer`, or you'll see errors like that.

**Comment by OliverBalfour** [comment]
Hi Chip, thanks for the suggestions! I have double checked my surface creation code and it should use a `CAMetalLayer`, and the `makeBackingLayer` function has been replaced to return a `CAMetalLayer`. However, when I print `[self.view.layer isKindOfClass:[CAMetalLayer class]]` it prints `NO` whereas it returns `YES` for `CALayer`.

Upon further inspection, lo and behold I used the UIKit method for creating a `CAMetalLayer` backing layer instead of the AppKit method ([source](https://developer.apple.com/documentation/quartzcore/cametallayer?language=objc), this basically means I was overriding `-(CALayer*) makeBackingLayer` and `+(Class) layerClass` _instead_ of the AppKit method of running `self.view.layer = [CAMetalLayer layer]` directly.)

Fixing that issue causes my swap chain code to work like a charm :) Thanks for the pointers, I never would have suspected the surface was the issue otherwise as it never threw any errors in any other function calls until now!

For anybody with similar issues, here is an abbreviated section of my working layer creation code:

```mm
- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.wantsLayer = YES;
    self.view.layer = [CAMetalLayer layer];
    // The C++ code needs access to the CAMetalLayer to call MoltenVK's vkCreateMetalSurfaceEXT function
    // Assuming there is a C++ class with ctor taking CAMetalLayer as a void* type
    _vulkanWrapper = new VulkanWrapper((__bridge void*)self.view.layer);
}
```

The following was my prior code closely based off the Cube demo which uses the UIKit method. If you may need to port to iOS this may (?) be useful. You can have both snippets present, they do not conflict.
```mm
-(BOOL) wantsUpdateLayer { return YES; }
+(Class) layerClass { return [CAMetalLayer class]; }
-(CALayer*) makeBackingLayer {
    CALayer* layer = [self.class.layerClass layer];
    CGSize viewScale = [self convertSizeToBacking: CGSizeMake(1.0, 1.0)];
    layer.contentsScale = MIN(viewScale.width, viewScale.height);
    return layer;
}
```

**Comment by cdavis5e** [comment]
That's curious... The UIKit method works for Wine. We don't even bother overriding `+[NSView layerClass]`. We just create a `CAMetalLayer` directly (dlls/winemac.drv/cocoa_window.m:925):
```objective-c
    - (CALayer*) makeBackingLayer
    {
        CAMetalLayer *layer = [CAMetalLayer layer];
        layer.device = _device;
        layer.framebufferOnly = YES;
        layer.magnificationFilter = kCAFilterNearest;
        layer.backgroundColor = CGColorGetConstantColor(kCGColorBlack);
        layer.contentsScale = retina_on ? 2.0 : 1.0;
        return layer;
    }
```
