### ISSUE TITLE
GLSL function imageAtomicCompSwap causes GLSL to SPIRV conversion failure

### ISSUE THREAD

**Issue by phonowiz** [KhronosGroup/MoltenVK#924]
Hi.  Am using:
```MoltenVK version 1.0.38. Vulkan version 1.0.126.```

Here is the GLSL generated by the library:

```
#version 450

layout(set = 0, binding = 2, std140) uniform UBO
{
    mat4 inverse_view_projection;
    mat4 project_to_voxel_screen;
    vec3 voxel_coords;
} ubo;

layout(set = 0, binding = 1, r32ui) uniform restrict uimage3D voxel_albedo_texture;
layout(set = 0, binding = 4, r32ui) uniform restrict readonly writeonly uimage3D voxel_normal_texture;

layout(location = 1) in vec3 frag_normal;
layout(location = 2) in vec3 frag_light_vec;
layout(location = 3) in vec3 frag_view_vec;
layout(location = 0) in vec4 frag_color;
layout(location = 0) out vec4 final_color;

void main()
{
    vec3 N = normalize(frag_normal);
    vec3 L = normalize(frag_light_vec);
    vec3 V = normalize(frag_view_vec);
    vec3 ambient = vec3(0.07999999821186065673828125);
    vec3 diffuse = frag_color.xyz * max(dot(N, L), 0.0);
    vec4 ndc = vec4(gl_FragCoord.x / ubo.voxel_coords.x, gl_FragCoord.y / ubo.voxel_coords.y, gl_FragCoord.z, 1.0);
    vec2 _72 = (ndc.xy * 2.0) - vec2(1.0);
    ndc = vec4(_72.x, _72.y, ndc.z, ndc.w);
    vec4 world_coords = ubo.inverse_view_projection * ndc;
    vec4 voxel_proj = ubo.project_to_voxel_screen * world_coords;
    ndc = voxel_proj / vec4(voxel_proj.w);
    vec2 _100 = (ndc.xy + vec2(1.0)) * 0.5;
    ndc = vec4(_100.x, _100.y, ndc.z, ndc.w);
    vec2 _106 = vec2(1.0) - ndc.xy;
    ndc = vec4(_106.x, _106.y, ndc.z, ndc.w);
    ivec3 voxel = ivec3(vec3(imageSize(voxel_albedo_texture)) * ndc.xyz);
    uint nextUint = packUnorm4x8(vec4(diffuse, 0.0039215688593685626983642578125));
    uint prevUint = 0u;
    uint currUint = 0u;
    uint count = 0u;
    uint _139 = imageAtomicCompSwap(voxel_albedo_texture, voxel, prevUint, nextUint);
    final_color = vec4(diffuse, 1.0);
}

```

If I take out the call *imageAtomicCompSwap* the conversion occurs.   The error message I receive is this:
```
"VK_ERROR_INVALID_SHADER_NV: Unable to convert SPIR-V to MSL:\nConverting SPIR-V:\n; SPIR-V\n; Version: 1.0\n; Generator: Khronos Glslang Reference Front End; 7\n; Bound: 148\n; Schema: 0\n               OpCapability Shader\n               OpCapability ImageQuery\n          %1 = OpExtInstImport "GLSL.std.450"\n               OpMemoryModel Logical GLSL450\n               OpEntryPoint Fragment %4 "main" %11 %15 %19 %33 %39 %141\n               OpExecutionMode %4 OriginUpperLeft\n               OpSource GLSL 450\n               OpSourceExtension "GL_ARB_separate_shader_objects"\n               OpName %4 "main"\n               OpName %9 "N"\n               OpName %11 "frag_normal"\n               OpName %14 "L"\n               OpName %15 "frag_light_vec"\n               OpName %18 "V"\n               OpName %19 "frag_view_vec"\n               OpName %22 "ambient"\n               OpName %25 "diffuse"\n               OpName %33 "frag_color"\n               OpName %38 "ndc"\n               OpName %39 "gl_FragCoord"\n               OpName %46 "
```

The shader itself is not in its original form, so it doesn't really work.  I simplified it as much as possible until I could find what was causing the error, the comp swap function seems to be throwing things off.

**Comment by cdavis5e** [comment]
We only support atomics on texel buffers (`*imageBuffer` in GLSL) and linear images, which are of course restricted to 2D images. This is unfortunately a limitation of Metal: it doesn't support image atomics natively, so we work around that by passing the underlying buffer and doing atomics on that. An optimal-tiled 3D image won't have a buffer underlying it, so it won't work here. The code to map the image coordinates to the location in the buffer in SPIRV-Cross also only works on 2D images and (maybe) buffers.

**Comment by cdavis5e** [comment]
Shoot, I didn't even notice you were using such an old version. I think that's long before I hooked up Epic's support for image atomics in SPIRV-Cross to MoltenVK. In other words, that version of MoltenVK doesn't support image atomics at all.

**Comment by billhollings** [comment]
>I didn't even notice you were using such an old version.

@phonowiz Can this issue be closed, pending you updating to a newer version? Once updated, if needed, post a different issue, clarifying specifics.

**Comment by phonowiz** [comment]
I looked at the Metal spec, I see something super similar to the function am trying to use, check here (Page 179):

https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf

I confess I don't know much about Metal and maybe am looking at the wrong thing.  Take a look, let me know what you guys think .

**Comment by cdavis5e** [comment]
> I looked at the Metal spec, I see something super similar to the function am trying to use, check here (Page 179):
> 
> https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf
> 
> I confess I don't know much about Metal and maybe am looking at the wrong thing. Take a look, let me know what you guys think .

That only works on buffer memory. Metal doesn't have anything equivalent for textures.

**Comment by phonowiz** [comment]
Thank you all for your time.  Great job with MoltenVK, without it wouldn't have been able to learn Vulkan using my Mac, I truly appreciate it.
