### ISSUE TITLE
API-Samples does not build

### ISSUE THREAD

**Issue by tmm1** [KhronosGroup/MoltenVK#925]
<img width="1009" alt="Screen Shot 2020-06-15 at 6 11 56 PM" src="https://user-images.githubusercontent.com/2567/84720747-c0240380-af33-11ea-9800-b33196a14ac6.png">

**Comment by tmm1** [comment]
Was able to fix the second error with `#include <string>`, but the first is a legitimate build error that I'm not sure how to resolve..

**Comment by billhollings** [comment]
Looks like you might be trying to run the `API-Samples` demo without including one of the macro definitions in `Samples.h`in the `GCC_PREPROCESSOR_DEFINITIONS` build setting.

See the instructions in `Demos/LunarG-VulkanSamples/API-Samples/Samples.h` or `Demos/README.md` for more info.

**Comment by tmm1** [comment]
You're right. Thanks for the pointers!

https://github.com/KhronosGroup/MoltenVK/blob/master/Demos/README.md#api-samples

https://github.com/KhronosGroup/MoltenVK/blob/master/Demos/LunarG-VulkanSamples/API-Samples/Samples.h#L23-L25
