### ISSUE TITLE
Add support for VK_KHR_driver_properties

### ISSUE THREAD

**Issue by flibitijibibo** [KhronosGroup/MoltenVK#933]
At a surface level this shouldn't be too hard to implement, it's one case to add to this function...

https://github.com/KhronosGroup/MoltenVK/blob/2dd34de8ee8823b9facedbc071a225191b57b6df/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L175

I don't know what `driverID` would be though. We would be happy to have the driver just be "MoltenVK 1.2.141.1" for example, but I don't know how much Metal driver info we could get from the OS.

**Comment by cdavis5e** [comment]
> I don't know what `driverID` would be though.

Probably something specific to MoltenVK. DXVK also asked for this, and they specifically wanted this to be able to ID MoltenVK and enable driver-specific hacks for it.

**Comment by flibitijibibo** [comment]
This should be resolved once the headers have been updated to 1.x.148 and `VK_DRIVER_ID_MOLTENVK` is filled in here:

https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L262

**Comment by billhollings** [comment]
> This should be resolved once the headers have been updated to 1.x.148 and `VK_DRIVER_ID_MOLTENVK` is filled in here:
> 
> https://github.com/KhronosGroup/MoltenVK/blob/master/MoltenVK/MoltenVK/GPUObjects/MVKDevice.mm#L262

Yup. PR #966 is in flight. 😉
