### ISSUE TITLE
The GLSL findMSB function does not seem to work with MoltenVK

### ISSUE THREAD

**Issue by elmar-k** [KhronosGroup/MoltenVK#938]
Dear MoltenVK team,

I started testing our Vulkan app with MoltenVK in MacOS, and it's really amazing what you have achieved so far. I'll report the issues as I encounter them.

The first is about the findMSB function.
Here is a GLSL example code:

uint edgelen;

myarray[0]=0x1234;
edgelen=20;
myarray[1]=edgelen;
myarray[2]=findMSB(edgelen);
myarray[3]=findMSB(uint(20));
myarray[4]=uint(log2(20.0));
myarray[5]=0x5678;

Running this in Linux and reading back the result gives me these expected bytes:

00001234  00000014  00000004  00000004 00000004  00005678 

In MacOS 10.14 with Geforce GT 750M and MoltenVK from the latest SDK (vulkansdk-macos-1.2.141.2.dmg  from June 11) I get

00001234  00000014  00000000  00000000 00000004  00005678 

Note that findMSB returns 0 instead of 4.

I used SPIRV-Cross to look at the Metal shader code, which is:

myarray[0] = 4660u;
myarray[1] = 20u;
uint _267 = uint(int(spvFindUMSB(20u)));
myarray[2] = _267;
myarray[3] = _267;
myarray[4] = 4u;
myarray[5] = 22136u;

So something seems wrong with spvFindUMSB. I tried to help by looking into SPIRV-Cross doing a 

git clone https://github.com/KhronosGroup/SPIRV-Cross.git SPIRV-Cross
cd SPIRV-Cross
 git checkout d385bf096f5dabbc4cdaeb6872b0f64be1a63ad0

(this was the SPIRV-Version I found I the latest MoltenVK source).

But "unfortunately" the SPIRV-Code looks OK to me:

/ Implementation of the unsigned GLSL findMSB() function
template<typename T>
inline T spvFindUMSB(T x)
{
    return select(clz(T(0)) - (clz(x) + T(1)), T(-1), x == T(0));
}

It also looks like there is a testsuite in SPIRV-Cross which checks this function, so I fear someone with more inside knowledge is needed at this point to figure out why this goes wrong.

To workaround the problem on my side, I'm using this slow workaround:

#define findMSB(VAL) uint(log2(float(VAL)))

(this wouldn't work if VAL was 0, but I don't have this case ;-)

Best regards and many thanks for your help,
Elmar

**Comment by billhollings** [comment]
This looks to be a SPIRV-Cross issue. Can you post this to the [SPIRV-Cross issue list](https://github.com/KhronosGroup/SPIRV-Cross/issues), please?

>I used SPIRV-Cross to look at the Metal shader code

FYI...in future, you can inspect the SPIRV->MSL code translation right within MoltenVK by setting the environment variable `MVK_DEBUG` to '1'. Doing so will cause MoltenVK to log the SPIRV code, the resulting MSL code, and the original GLSL code (as back-converted from the SPIRV). This is described in the `MoltenVK_Runtime_UserGuide.md` document...and the full list of MoltenVK environment variables is documented in the `vk_mvk_moltenvk.h` file.

**Comment by billhollings** [comment]
Moved to [SPIRV-Cross 1413](https://github.com/KhronosGroup/SPIRV-Cross/issues/1413).
