### ISSUE TITLE
Xcode 12 beta features required to compile latest master branch for macOS target

### ISSUE THREAD

**Issue by OliverBalfour** [KhronosGroup/MoltenVK#941]
I just cloned this repository again after seeing the changes in #935 to rebuild my app for the iOS simulator, and I encountered an error in the build process under Xcode 11 due to an Xcode 12 beta feature (MTLDrawable presentedTime) being used.

`MVKImage.mm:1169 - Property 'presentedTime' not found on object of type 'id<MTLDrawable>'`

Looking at the [MTLDrawable documentation](https://developer.apple.com/documentation/metal/mtldrawable?language=objc) with 'Show API changes' enabled shows this feature is only in Xcode 12 beta. Given Xcode 12 is still in beta and has been released so recently, I feel even though the README says to use the latest version of Xcode it would be better to check whether the feature is available before using it here, as installing Xcode 12 beta just to build MoltenVK is a little tricky.

If you comment out the `if (hasPresentTime)` block (L1169-1182) it compiles and works as expected. This does not occur for the iOS target, only the macOS build target.

Also: thanks a ton for doing the iOS simulator work, it makes life much easier :)

**Comment by cdavis5e** [comment]
> Looking at the MTLDrawable documentation with 'Show API changes' enabled shows this feature is only in Xcode 12 beta.

Actually, you need Xcode 11.5 (.4?), which should be out of beta.

**Comment by alexey-lysiuk** [comment]
`presentedTime` was added with macOS 10.15.4 SDK in Xcode 11.4.

**Comment by OliverBalfour** [comment]
Ah, my bad! I'm running Xcode 11.3, and I must have misread the API changes documentation. It would be nice if 11.3 was supported as it is quite recent, but I understand if that is not a high priority. If anybody else has the same issue they should find this page either way. Thanks anyways!

**Comment by mgwysocki** [comment]
Please update the README to reflect that MacOS 10.15 and XCode 11.4 are required. This is a pretty stringent requirement.

**Comment by billhollings** [comment]
>Please update the README to reflect that MacOS 10.15 and XCode 11.4 are required. This is a pretty stringent requirement.

The [_Building MoltenVK_](https://github.com/KhronosGroup/MoltenVK#building) section of `README.md` opens with the following:

>During building, **MoltenVK** references the latest *Apple SDK* frameworks. To access these frameworks, 
and to avoid build errors, be sure to use the latest publicly available version of *Xcode*.

We write it this way to keep it fresh and accurate, and to avoid having to update `README.md` constantly.

As described, requiring the most recent version of production _Xcode_ for the latest version of MoltenVK allows the latest version of MoltenVK to support the most recently available features available from Apple's SDK.

The master branch of MoltenVK never requires beta versions of _Xcode_. For that we create separate branches, as with the currently available [`xcode12` branch](https://github.com/KhronosGroup/MoltenVK/tree/xcode12). Then once the _Xcode_ version exists beta, we merge the branches.
