### ISSUE TITLE
MVK_BUILT_PROD_DIR vs MVK_BUILT_PROD_PATH discrepancy -> build fails

### ISSUE THREAD

**Issue by kikaxa** [KhronosGroup/MoltenVK#944]
Most scripts use MVK_BUILT_PROD_DIR, while xcode projects sets MVK_BUILT_PROD_PATH.
The packaging/build fails for at least the shader compiler tool.
Probably the project should be fixed up.

**Comment by billhollings** [comment]
@kikaxa This is fixed in PR #951. Please retest and close if this fixes your issue.

**Comment by kikaxa** [comment]
Thanks!
