### ISSUE TITLE
Regression: App-store validation failed after commit d2f1b59c4c7b2bd5edd3f04630afb6739efdfb96

### ISSUE THREAD

**Issue by kikaxa** [KhronosGroup/MoltenVK#950]
`ITMS-90338: Non-public API usage - The app references non-public symbols in : _kCGColorSpaceITUR_2020_HLG, _kCGColorSpaceITUR_2020_PQ_EOTF.`

https://github.com/KhronosGroup/MoltenVK/commit/d2f1b59c4c7b2bd5edd3f04630afb6739efdfb96
@cdavis5e

**Comment by danginsburg** [comment]
We just got rejected for this too.  Must be a new check Apple is doing?

**Comment by billhollings** [comment]
There are a few things strange about this. 

These symbols have been part of MoltenVK for over a year. 

On top of that, these are all legit color space names according to Apple’s curent SDK, but their online docs are reporting some differences now.

I think maybe they’ve pulled back support in the latest SDK, and are using that for recent app store testing.

We can certainly remove these for iOS to get these through the App Store gate...but it looks to be an arbitrary, and maybe mistaken, change on Apple’s part.

@cdavis5e Are you okay if I simply make those two symbols (which correspond to Vulkan `VK_COLOR_SPACE_HDR10_HLG_EXT` and `VK_COLOR_SPACE_HDR10_ST2084_EXT`) conditionally unavailable in MoltenVK under iOS/tvOS?

**Comment by cdavis5e** [comment]
> Are you okay if I simply make those two symbols (which correspond to Vulkan `VK_COLOR_SPACE_HDR10_HLG_EXT` and `VK_COLOR_SPACE_HDR10_ST2084_EXT`) conditionally unavailable in MoltenVK under iOS/tvOS?

Fine by me.

**Comment by cdavis5e** [comment]
Hmm, it looks like the symbol names were changed for the 14.0 SDK. We're now supposed to use `kCGColorSpaceITUR_2100_PQ` and `kCGColorSpaceITUR_2100_HLG`.

**Comment by billhollings** [comment]
> Hmm, it looks like the symbol names were changed for the 14.0 SDK. We're now supposed to use `kCGColorSpaceITUR_2100_HLG` and `kCGColorSpaceITUR_2100_PQ`. And before that, the latter was changed to `kCGColorSpaceITUR_2020_PQ` in the 13.4 SDK.

We can't change to the 14.0 SDK values yet...because it will force everyone to upgrade to Xcode Beta...and it's too early for that.

I'll replace `kCGColorSpaceITUR_2020_PQ_EOTF` with `kCGColorSpaceITUR_2020_PQ`, and bump the  OS version support for `VK_COLOR_SPACE_HDR10_ST2084_EXT` to macOS 10.15.4 & iOS 13.4.

Since there's no current substitute for `kCGColorSpaceITUR_2020_HLG`, I'll just have to remove support for `VK_COLOR_SPACE_HDR10_HLG_EXT` altogether.

Since these have been deprecated (actually deleted) on both platforms, I'll make these changes for both iOS and macOS, since there is also a macOS App Store that might have the same filter.

**Comment by billhollings** [comment]
>macOS 10.15.4 & iOS 13.4

Ha! Fun fact: 

On Xcode 11.5, `CGColorSpace.h` for the macOS 10.15 SDK has some very different OS version permission declarations  than `CGColorSpace.h` for the iOS 13.5 SDK...and it makes odd references to macOS 10.16 (ie. before it was even announced...and which has now become macOS 11.0).

**Comment by billhollings** [comment]
@kikaxa @danginsburg This is now fixed in PR #952. Please verify on App Store and close this issue if repaired.

**Comment by kikaxa** [comment]
Thanks! This should fix it, though i can't verify it right now, we're not having another release for a while.
I'm not sure kCGColorSpaceITUR_2020_PQ won't trigger another reject now/soon as it's already listed as deprecated and does not appear on the color space names page.
I'd wait for someone to report a success, but it's ok to reopen later as well.

**Comment by billhollings** [comment]
>I'm not sure kCGColorSpaceITUR_2020_PQ won't trigger another reject now/soon as it's already listed as deprecated and does not appear on the color space names page.

`kCGColorSpaceITUR_2020_PQ` did indeed trigger an App Store rejection.

PR #954 fixes this by removing `kCGColorSpaceITUR_2020_PQ` and not advertising support for the corresponding Vulkan color space: `VK_COLOR_SPACE_HDR10_ST2084_EXT`.

Removing it did fix the App Store rejections. So all should be good now regarding the App Store.
