### ISSUE TITLE
Crash when calling `vkMapMemory` or `vkUnmapMemory`

### ISSUE THREAD

**Issue by BearishSun** [KhronosGroup/MoltenVK#957]
Metal validation reports the following error:
```
-[MTLDebugBuffer didModifyRange:]:482: failed assertion `(range.location+range.length)=(65536) exceeds end of buffer (4096)'
```

With the following stack trace:
```
#7	0x0000000158213352 in MVKBuffer::flushToDevice(unsigned long long, unsigned long long) at /Users/bearishsun/Work/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKBuffer.mm:148
#8	0x00000001581cc946 in MVKDeviceMemory::flushToDevice(unsigned long long, unsigned long long, bool) at /Users/bearishsun/Work/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm:96
#9	0x00000001581cc5bc in MVKDeviceMemory::unmap() at /Users/bearishsun/Work/MoltenVK/MoltenVK/MoltenVK/GPUObjects/MVKDeviceMemory.mm:74
#10	0x00000001581a6351 in ::vkUnmapMemory(VkDevice, VkDeviceMemory) at /Users/bearishsun/Work/MoltenVK/MoltenVK/MoltenVK/Vulkan/vulkan.mm:462
```

Sometimes I get the crash during `vkMapMemory` rather than `vkUnmapMemory`. Without Metal validation I just get EXC_BAD_ACCESS during a `memcpy` operation.

My buffer is allocated using HOST_VISIBLE memory (I use it as a staging buffer). The code confirmed works on Windows as well as on previous versions on MoltenVK. It does not work in MoltenVK 1.0.43 (`e9fc62b27dcd964526fd0c0746679c44bc161701`).

The issue appear to be in `MVKDeviceMemory::flushToDevice` and `MVKDeviceMemory::pullFromDevice` methods, which will iterate over all images and buffers allocated from that `MVKDeviceMemory` instance and call equivalently named methods on those images/buffers.

The problem is that the offset/size argument for those methods is the one provided to `vkMapMemory`/`vkUnmapMemory` for the particular buffer I'm mapping, which will almost certainly be outside the bounds of those other images/buffers.

In my case I'm mapping a memory of size 65536 bytes, yet the size of one of the buffers in `MVKDeviceMemory` is 4096 bytes. This fails in an obvious way, but obviously any other size/offset also fails but perhaps does not result in a crash.

**Comment by js6i** [comment]
Please try with this change: https://github.com/js6i/MoltenVK/commit/d90528b0c9ae756587c00e1c9beb4f4b6fa5436a

**Comment by BearishSun** [comment]
Sadly I cannot run the latest master due to https://github.com/KhronosGroup/MoltenVK/issues/956.

But I see there are already some checks in place that could resolve this on master, along with your new change. I'll see if I can copy that code in my 1.0.43 version.

**Comment by BearishSun** [comment]
I added a workaround for #956 and got my code running on master. The issue there doesn't appear to be present and I'm not getting the crash, without or without the fix provided by @js6i .
