### ISSUE TITLE
Support for shaderSampledImageArrayDynamicIndexing physical device feature

### ISSUE THREAD

**Issue by Gohla** [KhronosGroup/MoltenVK#96]
The `shaderSampledImageArrayDynamicIndexing` physical device feature is not supported in MoltkenVK. This feature is supported on 98% of all Vulkan platforms (according to https://vulkan.gpuinfo.org/listfeatures.php) and makes binding many textures very convenient. Would it be possible for MoltenVK to support this feature as well?

**Comment by kruseborn** [comment]
This feature would really be appreciated, any plans for it?

**Comment by cdavis5e** [comment]
We'd need to have SPIRV-Cross translate arrays of textures to `metal::array` objects. This is supported as of Metal 1.2. Unfortunately, this is somewhat complicated by the fact that arrays of samplers aren't supported until Metal 2.0. This is a problem primarily for combined image/sampler objects--with MSL 1.2, we'd be able to have an `array` of the image parts, but not the sampler parts.

**Comment by cdavis5e** [comment]
Or maybe it will work for written images. The docs lied to me!

**Comment by kruseborn** [comment]
That sounds great, enabling shaderSampledImageArrayDynamicIndexing is enough for us at the moment.
