### ISSUE TITLE
Refcnt underflow in MVKShaderLibrary::getMTLFunction

### ISSUE THREAD

**Issue by js6i** [KhronosGroup/MoltenVK#961]
When launching a game under Xcode, I often get a method invoked on a zombie object crash on the newly created, unspecialized `mtlFunc`, usually on the `release` call just before reassignment in `MVKShaderLibrary::getMTLFunction`. I don't see any error in the code - as I understand, the `newFunctionWithName:` method, by the naming convention, returns a retained object. Releases seem to match.

I noticed that in my case `MVKShaderLibrary::getMTLFunction` gets called in parallel on the same object with the same function name. Wrapping the whole thing in `@synchronized (_mtlLibrary)` makes the issue go away, but so does for example changing `[mtlFunc release]` to `[mtlFunc autorelease]`. On the other hand, synchronizing just the `newFunctionWithName:` call does not.

**Comment by billhollings** [comment]
Thanks for your diligent research! It was extremely helpful.

`mtlFunc` is a local var...so it's hard to see where a concurrency race condition could be appearing.

Nevertheless...in PR #971 I've reworked `MVKShaderLibrary::getMTLFunction()` using your research results to try to stomp on this Heisenbug. 

Specifically, I've removed the use of discrete `retain`/`release` and leveraged the existing autorelease pool instead, and I've wrapped the entire specialization operation in `@synchronized()` to guard against Metal internals not coping with multiple simultaneous specializations.

Please retest and close this issue if it fixes the problem.

**Comment by js6i** [comment]
Yes, that fixes it. Or at least makes it way harder to reproduce. I suppose the way to go from here would be to isolate the problem and submit it to Apple.
