### ISSUE TITLE
Issue when copying from Texture to a Buffer offsetted within a memory allocation

### ISSUE THREAD

**Issue by reicrof** [KhronosGroup/MoltenVK#97]
It seems there is an issue when copying from a texture to a buffer that is created from an offsetted position in an already allocated memory. 

#### Repro steps
Create and upload data to a gpu local texture. Create 2 buffers from a single memory allocation and upload the content of the texture to the second buffer. (The one offsetted in the memory location).

In theory, you should be using something like
```
VkBufferImageCopy region = {};
region.bufferOffset = 0;
```
since the offset of the buffer object is 0. 
From the spec :
> bufferOffset is the offset in bytes from the start of the buffer object where the image data is copied from or to.

When using 
```
VkBufferImageCopy region = {};
region.bufferOffset = sizeOfFirstBuffer;
```
the download seems to be working correctly. It is also working correctly if the download buffer is created from its own memory allocation.

I believe the first version is the correct one as the offset from the buffer should be 0 even though the offset from the memory allocation is the size of the first buffer. I have tested the first version on a Linux machine and it was working as expected with the `region.bufferOffset = 0;`

**Comment by billhollings** [comment]
@reicrof This is now fixed in PR #127. Please retest and close this issue.
