### ISSUE TITLE
MoltenVKShaderConverter creates invalid MSL when multiple decorations are used for same variable

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#986]
In the attached english readable spv you can see that both 'gl_InstanceID' and 'gl_InstanceIndex' are assigned as names for 'BuiltIn InstanceIndex'. 

[test.english.txt](https://github.com/KhronosGroup/MoltenVK/files/5038787/test.english.txt)

This seems legal and works fine on Windows. In the MoltenVKShaderConverter however it ends up creating a duplicate declaration in the MSL shader:

`vertex main0_out main0(uint gl_InstanceIndex [[instance_id]], uint gl_InstanceIndex [[instance_id]])`

Which fails on shader compile.

Attached is the binary .spv file:

[test.spv.txt](https://github.com/KhronosGroup/MoltenVK/files/5038791/test.spv.txt)

**Comment by cdavis5e** [comment]
...How did you get a SPIR-V module with two variables decorated with the same `BuiltIn`? I'm amazed that's actually valid. But apparently it is; `spirv-val` doesn't throw any errors on it.

Regardless, this is a [SPIRV-Cross](/KhronosGroup/SPIRV-Cross/issues) issue. You should file your bug there.

**Comment by mbechard** [comment]
It's from an upcoming extension to the GLSL -> SPIR-V compilation mode for glslang (when in Vulkan mode) that allows for a more relaxed GLSL interpretation, such as allowing gl_InstanceID. The goal is to allow Vulkan to consume a wider range of GLSL shaders. Thanks for the direction, didn't realize spirv-cross was where this was done.
