### ISSUE TITLE
SPIR-V to MSL conversion issue

### ISSUE THREAD

**Issue by mbechard** [KhronosGroup/MoltenVK#987]
This is a strange one, and probably needs to be reported over at spirv-cross instead. However what's particularly odd about it that is only happens at runtime during vkCreateGraphicsPipelines(). When running the standalone shader conversion tool, proper MSL code is created. So I'm wondering if there is something else occurring within the MoltenVK codebase.

Working from MoltenVK release tag v1.0.44

Here is the source SPIR-V reported by MVK_DEBUG=1 output

[error.spv.txt](https://github.com/KhronosGroup/MoltenVK/files/5039202/error.spv.txt)

Specifically the issue is with the input variable `texCoord0`. In the SPIR-V is correctly declared as a vec2. However in the generated MSL it gets declared as a vec4, which causes a compile error when trying to sample sNormalMap with a vec4 instead of a vec2.

[error.msh.txt](https://github.com/KhronosGroup/MoltenVK/files/5039205/error.msh.txt)

Even the estimated original GLSL correctly has it as a vec2:

[error.glsl.txt](https://github.com/KhronosGroup/MoltenVK/files/5039208/error.glsl.txt)

The only MVK option I have set is the mvkConfig.fullImageViewSwizzle, however this error happens both with this set and not set.

One other hint, it seems likely that this cause occurs only when mat3 tangentToWorld is present in the input variables.

Any ideas on what other things could be happening that would cause this to occur? Pointers on where to debug?
Thanks

**Comment by cdavis5e** [comment]
Looks like more fallout from #931. What does the vertex shader look like?

**Comment by mbechard** [comment]
The vertex has it correctly as a vec2 in all 3 versions, the struct is declared identically in the source GLSL. Here is the SPIR-V from the vert, as output from MVK_DEBUG=1 printouts.

[vert.spv.txt](https://github.com/KhronosGroup/MoltenVK/files/5042536/vert.spv.txt)

**Comment by mbechard** [comment]
Hey @cdavis5e, any idea if this got fixed?

**Comment by cdavis5e** [comment]
> Hey @cdavis5e, any idea if this got fixed?

Sorry, I don't know. I've been busy with other stuff lately. Have you tried it again lately?

**Comment by mbechard** [comment]
Closing this one for now as I can't reproduce in the latest versions of MoltenVK
