### ISSUE TITLE
vkQueueSubmit renderTargetArrayLength crash

### ISSUE THREAD

**Issue by DiegoAce** [KhronosGroup/MoltenVK#991]
I'm getting a crash with the latest commit f3e938f when I run vkQueueSubmit. I'm submitting a command buffer that draws to the swapchain image. 
This was not happening when I was testing issue #974 with I believe commit 8f6edef.
This is only happening on iOS and not Mac. The iPad I'm testing on is model A1670, iOS 13.5.1.
The error is:
``-[MTLRenderPassDescriptorInternal validate:width:height:], line 2263: error 'renderTargetArrayLength > 0 specified, but Layered Rendering is not supported on this device.'
-[MTLRenderPassDescriptorInternal validate:width:height:]:2263: failed assertion `renderTargetArrayLength > 0 specified, but Layered Rendering is not supported on this device.'``

**Comment by cdavis5e** [comment]
Do you still have problems with #992 applied?

**Comment by DiegoAce** [comment]
No problems with #992. Thanks for the quick fix!
