### ISSUE TITLE
Prebuilt IOS binaries in Vulkan SDK

### ISSUE THREAD

**Issue by TheMostDiligent** [KhronosGroup/MoltenVK#996]
Hello!
I just downloaded the latest SDK (1.2.148.1) from LunarG site and found out that IOS binaries are missing. By looking at older releases I found out that the last release where IOS binaries were present was 1.2.141.2.
Will they *not* be distributed with the SDK anymore?

**Comment by KarenGhavam-lunarG** [comment]
This is a macOS SDK issue. Could you post it on the SDK download site issue tracker (vulkan.lunarg.com). That way folks maintaining the SDK will see it.

It will be our intent to also include iOS binaries and evaluating... But will post updates if issue created at the SDK site.

**Comment by TheMostDiligent** [comment]
The binaries are back again in 1.2.154.0
